### ISSUE TITLE
Please elaborate on the test toolkit

### ISSUE THREAD

**Issue by TheDenSter** [MicrosoftDocs/dynamics365smb-devitpro-pb#10]
First of all... this is a FANTASTIC document, in fact this whole docs website is awesome!!

https://docs.microsoft.com/en-gb/dynamics-nav/developer/devenv-extension-advanced-example-test#application-test-toolkit

It would be nice to be a little more elaborate here, and explain that you need to import the test toolkit and how you can do this in a development sandbox. I could only find a doc about the test toolkit for NAV 2016. I'm sure it still applies (I am assuming that you need to import the test toolkit into the CSIDE container and then download symbols again to make the references work in AL) but it would be nice to have some more details in the instructions here.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13813e4d-d070-3e56-dcb6-f433ff04d945
* Version Independent ID: 0688f2ca-06fd-01d5-0355-64984443c54f
* Content: [Testing the Advanced Sample Extension - Dynamics NAV](https://docs.microsoft.com/en-gb/dynamics-nav/developer/devenv-extension-advanced-example-test#identifying-the-areas-of-the-extension-that-need-to-be-tested)
* Content Source: [dynamics-nav/developer/devenv-extension-advanced-example-test.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/developer/devenv-extension-advanced-example-test.md)
* Service: **unspecified**
* GitHub Login: @solsen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks so much for your feedback. We agree - and we'll be working on adding this in a future release of the docs. Thanks again!
