### ISSUE TITLE
missing examples & link is not working

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/dynamics365smb-devitpro-pb#100]
First of all link to examples is not working: "Atom Publishing Protocol: URI Conventions."

Secondly, missed examples with datetime. spend quite some time to figure it out. Here are right example: $filter=lastModifiedDateTime gt 2012-12-03T07:16:23Z

Examples provided here. Search for 'Primitive Literals' on this website:
http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 090c9021-b9ba-59af-7dea-20f998cec823
* Version Independent ID: 0ff459c1-2620-38e5-8765-20cacf8b37f9
* Content: [Using Filter Expressions in OData URIs - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/using-filter-expressions-in-odata-uris)
* Content Source: [dynamics-nav/Using-Filter-Expressions-in-OData-URIs.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Using-Filter-Expressions-in-OData-URIs.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. Link is fixed with the next update.
