### ISSUE TITLE
MSA?

### ISSUE THREAD

**Issue by wilhil** [MicrosoftDocs/dynamics365smb-devitpro-pb#1000]
Is there any official way/method to use Managed Service Accounts? In SQL and many other apps, simply providing a MSA (e.g. domain\msauser$) automatically provisions the account locally and autofills the password.

MS recommend this process, yet, it doesn't seem to work with Nav.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db5ca7bd-5e2e-544c-2a4f-5349a9f6f161
* Version Independent ID: 7909d0e4-3797-3cc3-2a37-48a43712452e
* Content: [Provisioning the Dynamics 365 Business Central Server Service Account - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/provision-server-account#feedback)
* Content Source: [dev-itpro/deployment/provision-server-account.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/provision-server-account.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,
Thanks for the feedback! Unfortunately this does not seem to be officially supported. This might be a good candidate to add the [ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central).
