### ISSUE TITLE
Minor language glitches

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#1002]
Just something I spotted in bringing up the page.  "Upgrades a NAV App to the a specified tenant."  "to the a" should be just "to the".

Having both Parameters and Inputs sections also seems an artifact from past versioning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f176e190-4ae2-c43a-b7e0-5141f4a2abdd
* Version Independent ID: 716a4e49-7bdd-5edc-c26b-d5d797a306f1
* Content: [Start-NAVAppDataUpgrade (Microsoft.Dynamics.Nav.Apps.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/start-navappdataupgrade?view=businesscentral-ps-15)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Apps.Management/Start-NAVAppDataUpgrade.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Apps.Management/Start-NAVAppDataUpgrade.md)

**Comment by jswymer** [comment]
Thanks for the feedback! We have fixed the typo. Sorry, but I might not completely understand the feedback about the Parameters and Inputs sections. These sections are generated automatically from the source code for each cmdlet. If you can provide some more information, it would be great. Thanks!

**Comment by update-jeremy** [comment]
I guess I was mostly confused.  

Other cmdlets in the Microsoft.Dynamics.Nav.Apps.Management section do have Parameters sections such as Install-NAVApp, which do a great job of specifying the parameter names, usage, expected types.  

So, I was confused why this one cmdlet also had an Inputs section which mostly covers the same list of options as the Parameters section (for example, "Publisher").  It seemed redundant and not adding value, just noise.  

I had assumed "Inputs" must have been from some older version of the documentation, since it was also inconsistent with the other cmdlets.  Apologies for assuming wrongly and thus not explaining well.

**Comment by jswymer** [comment]
Thanks for the explanation. We have discussed a better and more consistent way of extracting, presenting, and explaining the Inputs, but have not yet been able to dedicate any time, unfortunately. I appreciate the feedback and will include it when we do look deeper into this. Best regards.

**Comment by update-jeremy** [comment]
Ok!  :)  My thanks to you and your team.  The documentation site is one of the gems of how this product family has evolved over the past several years.
