### ISSUE TITLE
Minor language glitch

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#1003]
In the intro text: "Synchronizes a NAV App to the specified tenant's database. T"   Not sure what the trailing 'T' is there.

Also, having both Parameters and Inputs sections seems redundant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5f757a9-c2b4-c024-8275-9e91300be298
* Version Independent ID: 5fdebecd-6373-6472-77bb-c9eb68dd10a2
* Content: [Sync-NAVApp (Microsoft.Dynamics.Nav.Apps.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/sync-navapp?view=businesscentral-ps-15)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md)

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
