### ISSUE TITLE
Error: The package could not be created.

### ISSUE THREAD

**Issue by rishitiwari1109** [MicrosoftDocs/dynamics365smb-devitpro-pb#1004]
I got more than 1000 warning messages like AL0432: Table 'Ext Txt ID Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146303e1-568e-7a5c-ea4f-b40afbc503fc
* Version Independent ID: 53de4696-feb9-ff31-160e-a858a0be3d40
* Content: [Publishing a Code-Customized Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-publish-code-customization#feedback)
* Content Source: [dev-itpro/developer/devenv-publish-code-customization.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-publish-code-customization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, yes, these are warnings for now - you should still be able to compile and publish, though.

**Comment by rishitiwari1109** [comment]
Hi Susanne, 
Thanks for your reply.I have one unresolved Error <DotNet 'PluralizationService' is missing> in <OfficeLineGeneration.Codeunit> Can you please help me in resolving that.All others are warnings only
Thanks a lot.
Rishi

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I am not sure about that specific dependency, but in general, you must make sure that all .NET libraries that are referenced in code, are listed in the "al.assemblyProbingPaths": setting. Thanks.

**Comment by rishitiwari1109** [comment]
Hi , 

This is what I have updated in Settings.json
{
 "al.assemblyProbingPaths": [
    "C:\\Program Files\\Microsoft Dynamics 365 Business Central\\150",
    "C:\\Program Files (x86)\\Microsoft Dynamics 365 Business Central\\150",
    "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.7.2",
    "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v3.5",
    "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\WindowsPowerShell",
    "C:\\Windows\\assembly"
 ]   
}

Do I need to add something else ?
Thanks 
Rishi

**Comment by rishitiwari1109** [comment]
Hi Sussane, 

I added following lines in Settings.json and the Error is gone .
"C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319",
    "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319"
Thanks a lot for your quick responses.

Now I am on the Step 10 as described in this page and getting the below message.

The request for path /BC150/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code 422. Reason: The extension could not be deployed because it is already deployed on another tenant.

**Comment by SusanneWindfeldPedersen** [comment]
Hi Rishi,
Good to hear you solved it - it should actually be enough to use "C:\Windows\Microsoft.NET\Framework\" and "C:\Windows\Microsoft.NET\Framework64\ only, and then it'll catch everything in that folder, then you're code would be more robust with any new update. For the other error, you must now do as described in step 10 and uninstall with "Uninstall-NavApp -Name "Base Application" -ServerInstance BC150 -Force" or as described, this should get you to the next step where you unpublish all dependencies, and then the Base App.

**Comment by rishitiwari1109** [comment]
Hi Susanne,

Yes I will do it Thanks again for your time.I corrected the assemblyProbingPaths also as per your suggestion.Thank you

Rishi

**Comment by rishitiwari1109** [comment]
Hi , 

I am getting Error in Powershell while running the scripts (created by following the Step 11) in PowerShell.
Please help

Thank you
Rishi

**Comment by SusanneWindfeldPedersen** [comment]
Hi, the script must be saved using PowerShell ISE and then run, then it'll loop through all extensions and unpublish them one at a time. I will add that info to the topic.
