### ISSUE TITLE
Dynamics Build for Testing

### ISSUE THREAD

**Issue by anada1124** [MicrosoftDocs/dynamics365smb-devitpro-pb#1005]
2 things I would like to clarify.

1. I understand that Dynamics 365 in Docker image, which is technically the same as Cloud version, can be used for the testing, but when the build is updated so frequently, how soon do we have to go through the validation after a certain build becomes available?  One month?  3 months?
2. Japanese YEN is one of the very few currencies without any decimals, but is there any CRONUS set up as such?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936119a1-4f7e-ed69-f72e-44e41464f964
* Version Independent ID: c30741c6-9408-775a-5ce0-3f6986445447
* Content: [Testing your Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-testingyourextension)
* Content Source: [dev-itpro/compliance/apptest-testingyourextension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-testingyourextension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you have reached the repo for documentation issues. Please contact your usual support channel to get help with these questions. Thanks.
