### ISSUE TITLE
Docs upgrade definition nok

### ISSUE THREAD

**Issue by MirkoDraskovic** [MicrosoftDocs/dynamics365smb-devitpro-pb#1006]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/46016477/74711656-da1f3500-5224-11ea-9522-f1d27f7d113d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8868c4-fb29-4b1f-e8ba-7560642481fc
* Version Independent ID: e838d8a4-07b9-02a8-f0b5-756220b3e64d
* Content: [Business Central 14.X to 15.X compatibility matrix - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility)
* Content Source: [dev-itpro/upgrade/upgrade-v14-v15-compatibility.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-v14-v15-compatibility.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Nice catch! The article has been fixed to state 14.6 to 15.1 or later. The update will be published soon. Thanks for the feedback.
