### ISSUE TITLE
Return value is not mentionned in the documentation

### ISSUE THREAD

**Issue by daansaveyn** [MicrosoftDocs/dynamics365smb-devitpro-pb#1007]
The actual signature in VS Code is:

trigger OnLookup(var Text: Text)  : Boolean
begin
    ...
end;

Although I never use the return value of the OnLookup in a Page, it's not mentionned throughout the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d7300c7-ba26-3283-32bd-51e2257c4b08
* Version Independent ID: 7066ccbc-994d-f3e4-9359-14a84091ef36
* Content: [OnLookup (Page fields) Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onlookup-page-fields-trigger#feedback)
* Content Source: [dev-itpro/developer/triggers/devenv-onlookup-page-fields-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onlookup-page-fields-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this. The topic will be updated with the next refresh of the docs.
