### ISSUE TITLE
Missing hint to not use customer license for APPLICATION UPDATE

### ISSUE THREAD

**Issue by sirhc101** [MicrosoftDocs/dynamics365smb-devitpro-pb#1008]
Please add a hint to not use a customer license to process APPLICATION UPDATE steps.
I had a customer who tried to do and ended up with this error:
```
Publish-NAVApp -ServerInstance BC150 -Path "C:\<..>\Microsoft_System Application.app"
Publish-NAVApp : Your program license does not allow you to publish 'Assisted Setup Group'.
In Zeile:1 Zeichen:1
+ Publish-NAVApp -ServerInstance BC150 -Path "C:\install\Dynamics.365.B ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC150/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Manag
   ement.Cmdlets.PublishNavApp
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71477e4-f2ea-1481-7597-29b324bd4f57
* Version Independent ID: a2bb3a05-e5c1-d9f7-f47f-d2f34c4a91ea
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15#feedback)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, this version is no longer supported, but we'll update the latest documentation. Thanks.
