### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by spiderted1985** [MicrosoftDocs/dynamics365smb-devitpro-pb#1009]
It says:
"In version 15, with the move to AL, the only symbols required are the _system systems_, which are still provided on the version 15.0 installation media (DVD)."

I believe it should say:
"In version 15, with the move to AL, the only symbols required are the _system symbols_, which are still provided on the version 15.0 installation media (DVD)."

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The information about which topic this is about, is missing, can you please add that? Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Okay, found the typo. This will be fixed with the next refresh of the docs. Thanks.
