### ISSUE TITLE
Example code uses FINDFIRST with REPEAT..UNTIL

### ISSUE THREAD

**Issue by ShadowXVII** [MicrosoftDocs/dynamics365smb-devitpro-pb#101]
REPEAT..UNTIL should not be used after a FINDFIRST.

Also the .Next &lt; 1 is unusual, but redundant once loop is removed.

See https://docs.microsoft.com/en-us/dynamics-nav/findfirst-function--record-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff52fc77-6649-3d58-1abe-44f03d008b6a
* Version Independent ID: 5108a7a7-54de-6ac6-8cbb-21f0846943df
* Content: [HASVALUE Function (Media) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/hasvalue-function--media-)
* Content Source: [dynamics-nav/HASVALUE-Function--Media-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/HASVALUE-Function--Media-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback.
