### ISSUE TITLE
 Documentation for DelChr function is not complete (and very unclear)

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-devitpro-pb#1011]
The DelChr function has three parameters. The following case is missing from the documentation:
[the Github interface does not do code formatting of whitespace right]

If you omit both _Where_ and _Which_ parameters, then all spaces are removed from _String_ .

Example:
`var`
`    String: Text;`
`    NewString: Text;`
`    Text000: Label '   Windy West Solutions    ';   // note: can be multiple leading and trailing spaces`
`    Text001: Label '>%1< is transformed to >%2<';`
`begin`
`    String := Text000;`
`    NewString := DELCHR(String);`
`    MESSAGE(Text001, String, NewString);`
`end;`

The message window displays the following:
`> Windy West Solutions < is transformed to >WindyWestSolutions<`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 815ff32e-5231-8233-e84b-7e08c2bb1d71
* Version Independent ID: 0ac36fe2-c3fb-a160-923b-509986272830
* Content: [DelChr Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-delchr-method)
* Content Source: [dev-itpro/developer/methods-auto/text/text-delchr-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/text/text-delchr-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your contribution - the topic will be updated with the next refresh.
