### ISSUE TITLE
Example Suggestion

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#1012]
This take as a Language ID as a parameter.  It would be good to have a similar example to the older NAV version explaining to use the Language.GetLanguageID functionality to access it.   For reference:

https://docs.microsoft.com/en-us/dynamics-nav/multiple-document-languages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38d351df-6d56-28f8-f1ac-fc3735f011dd
* Version Independent ID: 87d1e51d-d163-3321-0fbd-facce659829a
* Content: [Language Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/reportinstance-language-method)
* Content Source: [dev-itpro/developer/methods-auto/report/reportinstance-language-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/report/reportinstance-language-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the suggestion. This will be added with the next refresh of the docs.
