### ISSUE TITLE
Missing 2 characters

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#1013]
In the last example you are missing the single quote and the semi-colon at the end of the second line...

AutoFormatType = 1;
AutoFormatExpression = '$&lt;precision, 2:2&gt;&lt;standard format, 0&gt;';

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9879ff0-2324-74dd-a05e-ec14779744b5
* Version Independent ID: 290daf79-3b1a-0e97-94a6-1584a5768ce1
* Content: [AutoFormatExpression Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-autoformatexpression-property)
* Content Source: [dev-itpro/developer/properties/devenv-autoformatexpression-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-autoformatexpression-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be fixed with the next doc refresh.
