### ISSUE TITLE
Source of ProductNames

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-devitpro-pb#1014]
Please describe or add a link (dev-itpro/administration/configure-web-server ?) where the product names are set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29ccefaa-3803-9bf8-7165-0ec5c9f06ad1
* Version Independent ID: 308aba9e-e4e2-d8fe-3e72-dbaa895537f0
* Content: [ProductName Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/productname/productname-data-type)
* Content Source: [dev-itpro/developer/methods-auto/productname/productname-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/productname/productname-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This has been included in the article and will be available with the next doc refresh.
