### ISSUE TITLE
Undocumented Setting: Productname

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-devitpro-pb#1015]
Please document the Key "Productname" (+short + marketing)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a37d8a7-4a5a-37c8-df1c-4dd28e37c360
* Version Independent ID: badd39bf-9d13-e0d4-0138-8cd9920b3a9f
* Content: [Configuring Business Central Web Server instance - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-web-server#Settings)
* Content Source: [dev-itpro/administration/configure-web-server.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configure-web-server.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. These settings have been added to the article. It will be available with the next doc refresh.
