### ISSUE TITLE
Timestamp-Link correct?

### ISSUE THREAD

**Issue by aho81** [MicrosoftDocs/dynamics365smb-devitpro-pb#1016]
Hi,
doesn't the timestamp-link has to begin with "http" instead of "https"? Most tools (e.g. Set-AuthenticodeSignature") explicitly expect "http" in the Url.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21426684-ae01-f266-f21c-065bb2499692
* Version Independent ID: c8058293-0160-a4cf-6706-f904349eb194
* Content: [Signing an APP Package File - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sign-extension?source=docs#feedback)
* Content Source: [dev-itpro/developer/devenv-sign-extension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-sign-extension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this. Yes, it should be http instead of https - and is probably due to a global search and replace. Thanks, the topic will be fixed with the next refresh.
