### ISSUE TITLE
Base Application Sync Error, Upgrade from BC 14 to BC 15

### ISSUE THREAD

**Issue by itsned911** [MicrosoftDocs/dynamics365smb-devitpro-pb#1018]
Hello I'm having an issue I'm upgrading from BC14 CU04 to BC14 CU07 and then I'm upgrading to BC 15 CU 02
but whenever I  Sync-NAVApp -ServerInstance BC150 -Name "Base 
Application" -Version 15.2.39040.0

I'm getting the below error

Sync-NAVApp : The following SQL error was unexpected:

No item by the name of '"dbo"."COMP$Payment Terms$0"' could be found in the current database 'BC15', given that @itemtype was input as '(null)'.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
At line:2 char:1
+ Sync-NAVApp -ServerInstance BC150 -Name "Base Application" -Version 1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC150/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.SyncNavApp"
Any help would be appreciated.

**Comment by jswymer** [comment]
Hello,

I am not sure whether this the cause of the problem but it is not recommended to update v14 CU07 (14.6) to 15.3 or later [Dynamics 365 Business Central Upgrade Compatibility Matrix](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility). But it can cause sync problems.

**Comment by jswymer** [comment]
Hello, 

I hope this helped solve the issue. Ootherwise, let us know and we will reopen as needed. Thanks for the feedback!
