### ISSUE TITLE
This page needs information on how to create the required comment

### ISSUE THREAD

**Issue by hougaard** [MicrosoftDocs/dynamics365smb-devitpro-pb#1019]
I have tried having it on the line before, the line after and at the end of the line in question. Nothing does seem to satisfy this rule?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce3d295-a61a-e00a-d178-8f2b1f4d9299
* Version Independent ID: 8d6c4d3d-a83c-677a-dc55-49290870d7a3
* Content: [Placeholders should have a comment explaining their content. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0470-placeholdershouldhavecommentexplainingcontent)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0470-placeholdershouldhavecommentexplainingcontent.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0470-placeholdershouldhavecommentexplainingcontent.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we definitely need an example - this will be provided with the next update of the docs. The syntax for comments that should satisfy this rule is: 

MissingNodeErr: Label 'Cannot find an XML node that matches %1 or %2.', Comment = '%1 = XML node name ; %2 = Parent XML node name';

Thanks!

**Comment by SusanneWindfeldPedersen** [comment]
Just refreshed the docs. Closing this issue. Thanks.
