### ISSUE TITLE
NAV 2018 URL structure doesn't work

### ISSUE THREAD

**Issue by ShadowXVII** [MicrosoftDocs/dynamics365smb-devitpro-pb#102]
The NAV 2018 structure uses https://&lt;base URL&gt;:&lt;port&gt;/v1.0/api/&lt;API version&gt;/ -- the v1.0 is not valid, it should be https://
&lt;base URL&gt;:&lt;port&gt;/api/&lt;API version&gt;/.
In NAV 2018, the &lt;API Version&gt; comes from the Page property "APIVersion".
The example also needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17c4eef7-2ff2-eeeb-d285-095002e99475
* Version Independent ID: 2beae6be-8b5f-2a48-4b68-81810248b8f6
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics)
* Content Source: [dynamics-nav/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/endpoints-apis-for-dynamics.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by gintuoklis** [comment]
Hey Shadow, 
Does APIVersion property works for you? 
I tried to play with on my NAV2018 (onpremise installation) installation and cannot get it working. 
I change APIVersion on my custom page to foo & receive 404 error while calling new endpoint https://localhost:7048/NAV/api/foo/

Perhaps there's some extra step that needs to be taken?

Best Regards, 
Gintautas

**Comment by ShadowXVII** [comment]
Hmm. I haven't tested custom values, but could only get to the standard NAV 2018 API endpoints using https://localhost:7048/NAV/api/beta/generalLedgerEntries?company=x (for example).

It would make sense that the API endpoint always starts with /api/ -- otherwise how would it know it's looking for an API endpoint?

My assumption was that a change in property APIVersion would update the URL. Does any other combination work for you?

- https://localhost:7048/NAV/api/foo/generalLedgerEntries?company=x
- https://localhost:7048/NAV/api/foo/beta/generalLedgerEntries?company=x
- https://localhost:7048/NAV/foo/api/generalLedgerEntries?company=x

**Comment by ShadowXVII** [comment]
And you turned on the API endpoints in the Service Tier setting :)?
Do the standard ones work?
If so, I'd be curious whether setting it back to the default "beta" would also work.

**Comment by gintuoklis** [comment]
Yes, standard API works. When i modify APIVersion of one of the standard APIs, it disappears from the entity list:
https://localhost:7048/NAV/api/beta/
If I set it back to **beta**, it comes back to the list. 
So there's some kind of logic built in.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Please contact MS support for more help.

**Comment by RiaanPretoriusSA** [comment]
this guide can not be used using the sandbox : https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics 

is this normal behavior?

**Comment by UrsWedershoven** [comment]
I don't know if you've had success already, but I wanted to provide my findings:

You have to modify the URL as follows to access your own API pages: https://localhost:7048/NAV/api/<APIPublisher>/<APIGroup>/<YourVersion> 

The only version tags accepted are in the format 'v1.0' or exactly 'beta'.

**Comment by RiaanPretoriusSA** [comment]
> 
> 
> I don't know if you've had success already, but I wanted to provide my findings:
> 
> You have to modify the URL as follows to access your own API pages: https://localhost:7048/NAV/api///
> 
> The only version tags accepted are in the format 'v1.0' or exactly 'beta'.

No we had no success and abandoned NAV entirely due to no support people that can assist.  We even tried channel partner support but no luck. Thank you anyway for the reply :)

**Comment by GrzegorzSzwed** [comment]
> I don't know if you've had success already, but I wanted to provide my findings:
> 
> You have to modify the URL as follows to access your own API pages: [https://localhost:7048/NAV/api/[APIPublisher]/[APIGroup]/[YourVersion]](https://localhost:7048/NAV/api/%5BAPIPublisher%5D/%5BAPIGroup%5D/%5BYourVersion%5D)
> 
> The only version tags accepted are in the format 'v1.0' or exactly 'beta'.

Hello, it doesn't work in NAV 2018. In this version I cannot choose APIPublisher or APIGroup. 
When I type standard APIs in the browser there are shown up, but I cannot see my custom APIs. Do you have some walkarrounds?
