### ISSUE TITLE
no useful example ( as usual )

### ISSUE THREAD

**Issue by brucemcmillan** [MicrosoftDocs/dynamics365smb-devitpro-pb#1021]
no useful example ( as usual )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e5051a9-1946-cae3-f818-a8d031ca3b91
* Version Independent ID: d5f54fb1-cd57-e219-b716-2e7e03992a8e
* Content: [XMLport Triggers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-xmlport-triggers)
* Content Source: [dev-itpro/developer/triggers/devenv-xmlport-triggers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-xmlport-triggers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We know that we're lacking code examples on reference docs and in particular trigger documentation. This is on our radar, we have not been able to prioritize that work yet, but hope to get to it in a near future. Thanks.
