### ISSUE TITLE
CurrReport.NewPage() Deprecated

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#1022]
Hi,

Is the Report.NewPage() a replacement for CurrReport.NewPage()?
I'm on Business Central v13 and it tells me that CurrReport.NewPage() is deprecated.
Unfortunately, Report.NewPage() does not seam to be available in my version...

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43df8d6d-0fda-4419-6039-091663d86304
* Version Independent ID: a41f4c48-db04-b986-0a4e-50f564c5a7ca
* Content: [NewPage Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/reportinstance-newpage-method)
* Content Source: [dev-itpro/developer/methods-auto/report/reportinstance-newpage-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/report/reportinstance-newpage-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, yes Report.NewPage() is replacing CurrReport.NewPage(). If you get a warning in your version that it will be deprecated, the new option should be available. If it isn't you should still have time to shift, this is only a warning for now. But if this is not so, please file a bug through your usual support channel. I hope this will resolve for you. Thanks.
