### ISSUE TITLE
The multilanguage syntax is being deprecated. Please update to the new syntax.

### ISSUE THREAD

**Issue by Luukjn** [MicrosoftDocs/dynamics365smb-devitpro-pb#1024]
The above example gives this warning.
How should I set the text in the new syntax? Please update this example to use the new syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e978f7d-5b1b-84f9-dec9-33fdf3792f8c
* Version Independent ID: a2ad8189-852b-f76c-df36-c3fbcea8ce93
* Content: [Create a Role Center Headline - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-create-role-center-headline#feedback)
* Content Source: [dev-itpro/developer/devenv-create-role-center-headline.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-create-role-center-headline.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, this issue is fixed with the next refresh of the docs.
