### ISSUE TITLE
Enum "InitValue" like Option possible?

### ISSUE THREAD

**Issue by ThomasBrendel** [MicrosoftDocs/dynamics365smb-devitpro-pb#1025]
Hello Team,

we have an option with an initvalue.
How can i set an initvalue for the Enum?

**Comment by ThomasBrendel** [comment]
The Intellisense function dont give a clue for the new Enum

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this. This is a bug, you cannot assign an initvalue for enums right now, we've filed it and it will be fixed in a future release. Thanks.

**Comment by ThomasBrendel** [comment]
But i have entered the correct Initvalue and it is no longer a "warning"...is this correct or is this a bug that i can enter it?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, not sure I understand - you have declared an enum, and specified an initvalue for it? Can you please share that piece of code?

**Comment by ThomasBrendel** [comment]
field(90; Status; Enum "Job Status")
        {
            Caption = 'Status';
            DataClassification = CustomerContent;
            InitValue = "Open";
        }

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, you can only use base enum values as InitValue currently, and not extensible enum values as InitValue - this is on our radar. Did this unblock you, or?

**Comment by SusanneWindfeldPedersen** [comment]
closing this issue
