### ISSUE TITLE
Issues with assemblyProbingPaths and unpublishing the Base App

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1026]
I've tried to follow the instructions for a BC 15.2 DE On-Prem standard database, and I've encountered the following issues:

Step 8, updating the al.assemblyProbingPaths as suggested did not help to recognize DotNet variables inside the standard repo. 
As a workaround, I've used the path to the .netPackages of a local BC 15.x Docker container, but that cannot be the solution?

Steps 10 to 12 are totally confusing. Step 12 cannot be followed by PS beginners. Using standard demo database, in fact I needed to follow instead: 
- Create a ps1 file (as suggested at the end of step 11).
- In powershell, run:
```
  Import-Module "Path to my ps1 file"
  UninstallAndUnpublish -ServerInstance MyServerInstance -ApplicationName "Base Application"
```

I'd suggest to replace steps 10 to 12 with the steps above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146303e1-568e-7a5c-ea4f-b40afbc503fc
* Version Independent ID: 53de4696-feb9-ff31-160e-a858a0be3d40
* Content: [Publishing a Code-Customized Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-publish-code-customization)
* Content Source: [dev-itpro/developer/devenv-publish-code-customization.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-publish-code-customization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback @NKarolak - this topic was tested on a 15.0 version, possibly a 15.1, so I cannot confirm right now if something has changed since. I will have to try it out. For the steps, I agree, this could be more user-friendly - I will update the steps with the next doc refresh. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Docs will be refreshed by April 1st. Closing this. Thanks.
