### ISSUE TITLE
procedure TESTFIELD with Enum

### ISSUE THREAD

**Issue by ThomasBrendel** [MicrosoftDocs/dynamics365smb-devitpro-pb#1027]
Hello Team,

normally an Optionfield can be checked with Testfield.
Enums throw a Warning?

JobL.TestField(Status, JobL.Status::Open);

Bug or "not implemented yet"?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, even if you get a warning at compilation, it should work. If not, then please file a bug using your usual support channel. Thanks.
