### ISSUE TITLE
too many redirects

### ISSUE THREAD

**Issue by TheDenSter** [MicrosoftDocs/dynamics365smb-devitpro-pb#1028]
The Microsoft Dynamics 365 branding rules documentation link (which links to "https://worldready.cloudapp.net/Styleguide/Read?id=2858&topicid=44517") doesn't open. I am getting a 'too many redirects' error when I try to open that page. I've tried it in chrome, chromium edge, internet explorer, and safari and the same error shows up everywhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 463e4bf4-3be8-4b89-21e2-9194e264fe38
* Version Independent ID: c2619d79-96f0-bd7b-e230-5e5d59f2bc3a
* Content: [Language and Branding - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-a-languange-branding#feedback)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-a-languange-branding.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-checklist-a-languange-branding.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-liober
* Microsoft Alias: **v-liober**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this. The referenced page doesn't work at the moment. We will update the topic with the next refresh. Thanks.
