### ISSUE TITLE
no more Cloud Partner Portal

### ISSUE THREAD

**Issue by TheDenSter** [MicrosoftDocs/dynamics365smb-devitpro-pb#1029]
The information in the 'Tip' section is no longer valid. The Cloud Partner Portal has been replaced by the 'Commercial Marketplace'.

Numbers 11 (products your app works with) and 12 (search keywords) are in the "Offer listing" section, and the Hide Key is in the "Availability" section.

In addition to this, it would be great if you would have an explanation of what the hide key is for. What is the purpose of this, and how does it work? Explain what the end user will see if there is a hide key, explain whether the offer is even visible in AppSource or not. I can't find anything that explains how this works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46fcddcf-67b7-2bc3-0b0f-d55ee472d87f
* Version Independent ID: 56834f0a-279f-a469-6721-0dfb34e57633
* Content: [Supported Products, Keywords and Hide Key - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-f-supportedproducts-keywords)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-f-supportedproducts-keywords.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-checklist-f-supportedproducts-keywords.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-liober
* Microsoft Alias: **v-liober**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This was fixed in an earlier doc refresh.
