### ISSUE TITLE
unnecessary parameter; too generic example.

### ISSUE THREAD

**Issue by StanPesotskiy** [MicrosoftDocs/dynamics365smb-devitpro-pb#103]
1. RecordID parameter is not supported by SETTASKREADY(Task[,NotBefore])
2. In example section it is shown that it needs to be called after TASKSCHEDULER.CREATETASK but there is no calls of this function at all in BaseApp but we see that scheduling works. We need to understand when exactly this function should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0ae0ce-f66a-4c14-9547-f9a5181bde03
* Version Independent ID: b29bd1cf-1370-403d-eef8-c836e2c9517a
* Content: [SETTASKREADY Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/settaskready-function)
* Content Source: [dynamics-nav/SETTASKREADY-Function.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SETTASKREADY-Function.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Sorry for the long wait. Thanks for your feedback. Please use our AL documentation library, we have updated all methods just recently [AL Reference Library](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/library). Thanks.
