### ISSUE TITLE
Placing labels on a page

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1030]
Nowhere I can find information that and how labels can be placed on pages, and what separates them from fields. You can find an example in the request page of report 6699 "Move Negative Sales Lines".

When you currently search for "Label", the only thing you will find is the label data type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0363ee62-5ad8-5e9a-82f5-27b3fa351506
* Version Independent ID: cb7dcfb3-3766-35a9-dade-dc5d450f6e25
* Content: [Pages Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-pages-overview)
* Content Source: [dev-itpro/developer/devenv-pages-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-pages-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback and your patience. With the latest doc refresh we've added a new topic on labels, please find it here [Working with Labels](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-labels?branch=master).
