### ISSUE TITLE
Insufficient content

### ISSUE THREAD

**Issue by ThomasBrodkorb** [MicrosoftDocs/dynamics365smb-devitpro-pb#1031]
Great to know that there are additional parameters.
Usually, these are explained and described, not just mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bab3db4-745f-2c66-eac3-be6d6e168200
* Version Independent ID: e1479a2b-49cd-9edb-63c1-e1b0e9907d9f
* Content: [Caption Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-caption-property#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-caption-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-caption-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, this will be fixed with the next doc refresh.
