### ISSUE TITLE
Is this all as a description of the Customizations property?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1033]
This is a very weak topic. First of all the property customizations should start with a capital and then what format needs SimpleCustomization to be? Comma separated string?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee6d69d8-d604-5eb5-c979-b1250cec527e
* Version Independent ID: 8bc6b6b0-a0ce-7d40-ae49-742903ce13a8
* Content: [Customizations Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-customizations-property?source=docs)
* Content Source: [dev-itpro/developer/properties/devenv-customizations-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-customizations-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, this issue is fixed with the next refresh of the docs.
