### ISSUE TITLE
To avoid a recurrent issue with migration to cloud process guide.

### ISSUE THREAD

**Issue by Aldebarian** [MicrosoftDocs/dynamics365smb-devitpro-pb#1035]
Be very careful when composing the SQL connection string. As you may read, there are two methods noted.
The first one is:

Server={SQL Server Name};Initial Catalog={Database Name};UserID={SQL Authenticated UserName};Password={SQL Authenticated Password};

The second one, and more used, is this:

Server={SQL Server Name};Database={Database Name};User Id={SQL Server Authenticated UserName};Password={SQL Server Authenticated Password};

Pay special attention to the "space character" between "User" and "Id" at the third name parameter. 
It is mandatory; if not, Cloud Setup wizard will show up an error like "Failed to prepare the systems for replication".

Hope it helps you! 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: f79c98a9-a5dd-7d33-d2d8-f688044947ce
* Version Independent ID: 9bd56b8d-a958-1735-3277-d156758984e3
* Content: [Running the Cloud Migration Tool - Business Central](https://docs.microsoft.com/es-es/dynamics365/business-central/dev-itpro/administration/migration-tool#feedback)
* Content Source: [dev-itpro/administration/migration-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/migration-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with our next refresh of the docs.
