### ISSUE TITLE
Link not public available

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-devitpro-pb#1037]
The link on AA0218, AA0219 and AA0220  requires an Authentication.
The Information should be public or the link removed.

Link target is:
https://styleguides.azurewebsites.net/Styleguide/Read?id=2748&topicid=38066

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4cb6345-f9b7-5018-355c-6125088171f9
* Version Independent ID: c7764a10-88ca-8146-6b45-b27e12423ae0
* Content: [CodeCop Analyzer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop)
* Content Source: [dev-itpro/developer/analyzers/codecop.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This was fixed in an earlier doc refresh.
