### ISSUE TITLE
Incorrect example 2

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1038]
Example 2 is incorrect. Company Name should be like this:
"Company A", "Company B" 
instead of:
 "Company A, Company B" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf58eb84-6e5d-0128-28da-fe03c1faee22
* Version Independent ID: d828c63c-2a4a-9791-96d9-3aa4e0a594d4
* Content: [Export-NAVData (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/export-navdata?view=businesscentral-ps-15)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Export-NAVData.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Export-NAVData.md)

**Comment by blrobl** [comment]
Hi, thanks for catching this. It will be fixed with the next doc refresh.
