### ISSUE TITLE
CreateInStream: Syntax error in the example

### ISSUE THREAD

**Issue by salgiza** [MicrosoftDocs/dynamics365smb-devitpro-pb#104]
The example says:

`MyTable.MyBLOBfield.CREATEINSTREAM(MyStream, TextEncoding.WINDOWS)  `

But the correct syntax (note the "::") is:

`MyTable.MyBLOBfield.CreateInStream(MyStream, TextEncoding::Windows);  `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac054bd-7f24-6c8e-b822-f0e7fc5e3c67
* Version Independent ID: 5bcc6c83-94d8-e3de-dcb3-a5cf5d1bd9b1
* Content: [CREATEINSTREAM Method (BLOB) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-createinstream-method-blob)
* Content Source: [dev-itpro/developer/methods/devenv-createinstream-method-blob.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-createinstream-method-blob.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by skundaram** [comment]
Thanks for the feedback. We have fixed the mistake, and an update will be published soon.
