### ISSUE TITLE
Link to other article

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1040]
Could you please link that article for further help?
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-onbeforecompanyopen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aeb2e29-c2c5-7986-249b-545c0e3c9b24
* Version Independent ID: 229bd54a-3c0f-e6ee-929e-f7f25138273a
* Content: [Procedures must not subscribe to CompanyOpen events - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0061-donotsubscribetooncompanyopenevents)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop-as0061-donotsubscribetooncompanyopenevents.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop-as0061-donotsubscribetooncompanyopenevents.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, yes, makes sense - thanks for your feedback. Will be in with the next doc refresh.
