### ISSUE TITLE
Example Result?

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#1042]
The example is great, but could we by chance have the results in a screenshot?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbfa8ab-1e61-8974-f781-c59676cfc048
* Version Independent ID: 38350590-c7ed-bf50-9f8d-17b9fd709b93
* Content: [Arrange Fields Using GridLayout Control - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-gridlayout-control)
* Content Source: [dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-gridlayout-control.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-gridlayout-control.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback! The screenshot has been included and will be available with the next refresh.
