### ISSUE TITLE
"as must" --> as much

### ISSUE THREAD

**Issue by ZepposBE** [MicrosoftDocs/dynamics365smb-devitpro-pb#1043]
For Testing the Advanced Sample Extension:
In "You are required to include a Visual Studio Code test package with your extension. Ensure that you include as must code coverage as you can."  the "must" should be replaced by "much" I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 885cbacd-b3e7-1730-812c-9148ebfc90e9
* Version Independent ID: eb11ce7e-1efb-106c-5d79-19c206860da0
* Content: [Technical Validation Checklist - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission)
* Content Source: [dev-itpro/developer/devenv-checklist-submission.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-checklist-submission.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - it will be fixed with the next push to live. Thanks.
