### ISSUE TITLE
How to get the Bearer token?

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1044]
Hello,

In this documentation, there is no explanation on how to get the Bearer to give user credentials.

This page explains how to get a token for this administration center : https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api
but the token does not work for Automation APIs.

The Basic authentication seems working (this is not mentioned) with the user name + web service key... but the connection is unstable, sometimes it works and a moment later an error 401 Unauthorized is returned...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036fbaa0-3f6b-e4f7-cd1e-c35b37cdee6e
* Version Independent ID: 9efb41bd-bad8-597f-08e8-2b3c7e05f8e9
* Content: [Introduction to automation APIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/itpro-introduction-to-automation-apis)
* Content Source: [dev-itpro/administration/itpro-introduction-to-automation-apis.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/itpro-introduction-to-automation-apis.md)
* Service: **dynamics365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
The process is the same for getting a bearer token, so you should be able to use the powershell.  Alternatively you can try it through postman, following the guide for connect apps: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps

Please post the error you're getting from AAD.

**Comment by nicolassaleron** [comment]
Thanks but for now I give up, as far as I see it still requires many manual actions to make it works for each tenant and requires manual actions get a token.
It would be useful if we could script the actions without any UI and without defining a application subscription.
Logins should not be based only on credentials of the tenant but we should be able to use delegate access if we are a partner without configuring all these stuffs.

The usage I would hope for this feature: as a partner, as far as the tenant is attached to our CSP account on Partner Portal, we should be able to access to the APIs with one unique login/password or OAuth access across all tenants we manage.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. Please provide any ideas on this site [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central), thanks!
