### ISSUE TITLE
Sandbox Preview on Existing Sandbox Critical

### ISSUE THREAD

**Issue by Bob-Dzimbowski** [MicrosoftDocs/dynamics365smb-devitpro-pb#1045]
Where we fall flat on our faces with all our customers is that we cannot test the new version with the current sandbox environment which has representative, daily data, with all configurations and extensions installed. The current preview is only good to see new functionality out of the box but you have no idea what is going to happen when it hits your environment for real. It is useless in terms of preparing for the upgrade to production the way you structure it now. Think about it, currently, when it is released and you have 30 days to schedule, we have to schedule sandbox on the first day and then start testing like there is no tomorrow under duress because in (now less than) 30 days you have to get any ISV or custom programs fixed. That is bloody IMPOSSIBLE!!! Especially if the process for the ISV is that they have to submit to MSFT to publish the fixes which takes 2-4 weeks. The math does not work!!! Why do you think the the last few upgrades have been such a DISASTER for customers? 30 Days is not enough to test in a real, representative environment with real data and to feedback and coordinate with ISV products and custom developers and get ISV updates certified before things are pushed into production. Do yourself and the community a big favour and change your policies to give customers and ISV's a fighting chance to have things go a little smoother. Your support center will love you for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 902ae0f1-9617-6a80-2cdb-e5273083bc2b
* Version Independent ID: 90342bd1-56f4-94ac-3f66-572ae2ec81ae
* Content: [Prepare for major updates with preview environments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/preview-environments#feedback)
* Content Source: [dev-itpro/administration/preview-environments.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/preview-environments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This repo is used for documentation issues. Please use your usual support channel and file new product ideas through [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central). Closing the issue in this repo. Thanks.
