### ISSUE TITLE
Wrong concatenation of URLs

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1046]
On paragraph #page-level-configuration, you are suggestion that contextSensitiveHelpUrl and ContextSensitiveHelpPage are concatenated by adding a slash between both value.

In your example :
  contextSensitiveHelpUrl = https://mysite.com/documentation
  ContextSensitiveHelpPage  = sales-rewards

  It should result in https://mysite.com/documentation/sales-rewards

Actually, BC 16 (I have not tested for previous versions) does not add a slash automatically and the resulting URL will be https://mysite.com/documentationsales-rewards

The doc could be corrected to warn that the contextSensitiveHelpUrl should end with a slash, unless there might be surprises when the URL are concatenated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a37544-0705-f808-e490-0cbe386f0876
* Version Independent ID: bdac9abe-c9fd-06dc-2d0d-84d6720de7dc
* Content: [Configure Context-Sensitive Help - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help/context-sensitive-help)
* Content Source: [dev-itpro/help/context-sensitive-help.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/help/context-sensitive-help.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You are absolutely right that the URL must end with a /. This article will be updated accordingly soon.

**Comment by SusanneWindfeldPedersen** [comment]
The article was updated. Thanks for the feedback. Closing this issue.
