### ISSUE TITLE
All links are not working

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1047]
Hey Guys, 
All links on column see, are not there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abe2d3ca-a714-6bef-c797-e0894ac973d5
* Version Independent ID: f3ac9206-aac1-1a0a-20be-853b111c0c80
* Content: [Removing Elements from the User Interface According to Permissions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/hide-ui-elements)
* Content Source: [dev-itpro/administration/hide-ui-elements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/hide-ui-elements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by edupont04** [comment]
Thank you for your feedback! This has now been fixed ( and the table is removed).
