### ISSUE TITLE
401 Unauthorised errror

### ISSUE THREAD

**Issue by mrprasad2k** [MicrosoftDocs/dynamics365smb-devitpro-pb#105]
Hi,
I followed the steps as per this document. However I seem to get into a 401 error wherein on the SAML 1.0 message sent from ADFS has the attributes name and primary sid. For name the value is mapped to UPN.

NAV version is Dynamics 2016. Not sure what is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31320132-37db-2e25-2d8d-51e95f037727
* Version Independent ID: 6727d3fd-2543-add0-18ac-84846512780d
* Content: [Authenticating Users with Active Directory Federation Services - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/authenticating-users-with-active-directory-federation-service-2017#feedback)
* Content Source: [dynamics-nav/Authenticating-Users-with-Active-Directory-Federation-Service-2017.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Authenticating-Users-with-Active-Directory-Federation-Service-2017.md)
* Product: **dynamics-nav-2017**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We have to ask you to contact support on this matter; this repo is meant for documentation issues only. Thanks again.
