### ISSUE TITLE
Superfluous full stop in sample code

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#1050]
if NumberSequence.Exists.('MySequence', true) then

in the code sample should probably read

if NumberSequence.Exists('MySequence', true) then

(no full stop before the opening bracket)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2d764fe-ffa6-17e6-a5db-3a9089a10b66
* Version Independent ID: 986e0cf4-24aa-cd21-78ba-12875794b406
* Content: [Number Sequences - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-number-sequences)
* Content Source: [dev-itpro/developer/devenv-number-sequences.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-number-sequences.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this typo. The topic will be fixed with the next refresh. Thanks.
