### ISSUE TITLE
Should I sign an App for SaaS that will not be published in AppSource? 

### ISSUE THREAD

**Issue by eclipses24** [MicrosoftDocs/dynamics365smb-devitpro-pb#1051]
The documentation says how to skip validation for on-premise but does not explain clearly what to do for App created for BC SaaS that are not intended to be installed to the AppSource.
Furthermore, is there a way to access to the same process of verification of the code run by Microsoft? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21426684-ae01-f266-f21c-065bb2499692
* Version Independent ID: c8058293-0160-a4cf-6706-f904349eb194
* Content: [Signing an APP Package File - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sign-extension)
* Content Source: [dev-itpro/developer/devenv-sign-extension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-sign-extension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
It is always recommended to use a certificate purchased from a third-party certificate authority for anything which is not a test. For more information please contact your usual support channel. Thanks.
