### ISSUE TITLE
No mention of requirement to be in the Sandbox

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1052]
Nowhere in this article does it mention that the Designer option only appears when in a Sandbox. Nor is the Sandbox text present in the main title bar to the left of the Search and Settings icons.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e31ad37-068e-3007-2e46-7afc15f6b73b
* Version Independent ID: cd16bd61-cd0d-be6b-0af7-c1e9d81c81f5
* Content: [Using Designer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inclient-designer)
* Content Source: [dev-itpro/developer/devenv-inclient-designer.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-inclient-designer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
You are right - this has been fixed for now by adding a note and will be pushed live with our next refresh. We will later prioritize adding new illustrations. Thanks.
