### ISSUE TITLE
Had issue in Task 5: Convert the C/AL TXT files to AL

### ISSUE THREAD

**Issue by lebragan** [MicrosoftDocs/dynamics365smb-devitpro-pb#1054]
txt2al   command examples might be missing the   --rename   parameter, otherwise the output files will have clashes with the source .txt files. At the end, the resultant .al file from the original .txt will have only the last object details - it will be overwritten as many times as the objects contained in the .txt created in   Task 3: Export the application objects to the new TXT syntax. Wonder if I missed something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402665e0-ee3c-027b-a64f-3b4d718f0424
* Version Independent ID: 3d4a0497-8c48-1ebb-cb8c-4471eed7ea3b
* Content: [Code Conversion from C/AL to AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/devenv-code-conversion#feedback)
* Content Source: [dev-itpro/upgrade/devenv-code-conversion.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/devenv-code-conversion.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! We have now included the --rename parameter in the examples as you suggested. The updated article will be soon available.
