### ISSUE TITLE
Business Central - Debugger Tool Tip for Record Variable

### ISSUE THREAD

**Issue by Vikrasans** [MicrosoftDocs/dynamics365smb-devitpro-pb#1055]
Hi,

I am debugging my code in Extension Codeunit  and I can Hover over the Record variable and see the Primary Key value. But when I hover over the field of the record variable, it says Not Available.

Is there anyway to see the value of the record fields value while debugging.

The following is my code and I am looking to see if I can see the value of the extended fields I have added to the Location table.

    [EventSubscriber(ObjectType::Table, Database::"Transfer Header", 'OnAfterValidateEvent', 'Transfer-To Code', true, true)]
    local procedure TransferToOnAfterValidate(Var Rec: Record "Transfer Header")
    var
        LocationRec: Record Location;
    begin
        if LocationRec.get(rec."Transfer-To Code") then begin
            rec."Gen. Bus. Posting Group" := LocationRec."Gen. Bus. Posting Group";
            rec."Responsibility Center" := LocationRec."Responsibility Center";
        end;
    end;

Looking ahead to valuable inputs....

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is used for feedback on BC documentation. For help with other issues, please use your usual support channel. Thanks.

**Comment by Vikrasans** [comment]
Hi,

I am new to Github. So you mean to say that questions like the one I posted above should not be posted in Github at all or is there seperate support channel in Github.

**Comment by SusanneWindfeldPedersen** [comment]
Hi, there is not a support channel in GitHub, but the partner you usually work with should be able to help you out. Thanks
