### ISSUE TITLE
Error during OnbeforeValidate Trigger in Business central

### ISSUE THREAD

**Issue by Martin4310** [MicrosoftDocs/dynamics365smb-devitpro-pb#1056]
I created a table extension for Purchase Header. My onbeforeValidate trigger includes a call for a function in an existing Codeunit. If i call a function from the OnbeforeValidate trigger the system crashes. But if i use in this trigger only a message it works. 
My table extension code:
modify("VAT Bus. Posting Group")
        {
            trigger OnBeforeValidate()
            begin
                Port_Purchase.Purchase_Head_OnModify1();
            end;
        }

code for this function:
procedure Purchase_Head_OnModify1()
    begin
        Message('Test');
    end;

if i use the Message in OnBeforevalidate it works like here:
modify("VAT Bus. Posting Group")
        {
            trigger OnBeforeValidate()
            begin
                Message('Test');
            end;
        }

Looks like the system has a problem with a call of functions from the trigger.

Is there anybody with any idea?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is used for feedback on BC documentation. For help with other issues, please use your usual support channel. Thanks.
