### ISSUE TITLE
Clickonce for Business Central

### ISSUE THREAD

**Issue by jnpatrouillault** [MicrosoftDocs/dynamics365smb-devitpro-pb#1057]
Hello
Can you share us the system requirement for clickonce for BC v14 On Prem, please.
This page shows only information about Dynamics NAV.
thank you for your quick feed back.
best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b0aa47-5276-2fd9-173f-f05adcd420c2
* Version Independent ID: fb89206b-f5c1-6f2c-1f83-899c02aa8e89
* Content: [System Requirements for Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central)
* Content Source: [dev-itpro/deployment/system-requirement-business-central.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/system-requirement-business-central.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

We don't have an article specific to ClickOnce for the Dynamics Client Connected to Business Central (Windows Client) in the Business Central Spring 2019 help. But we link to this article, which provides some information 
[Deploying Microsoft Dynamics NAV Windows client Using ClickOnce](https://docs.microsoft.com/en-us/dynamics-nav/deploying-microsoft-dynamics-nav-using-clickonce). Is this what you are looking for? Regards

**Comment by jswymer** [comment]
Hello, I hope this answered your question. If not, let us know and we will reopen the issue. Thanks for the feedback.
