### ISSUE TITLE
Not when ShowCaption = false.

### ISSUE THREAD

**Issue by MiePlougstrup** [MicrosoftDocs/dynamics365smb-devitpro-pb#1059]
This should not be applicable when you use the property ShowCaption = false. This would only result in unused caption, that needs translations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b7dd48-b93f-725e-dee3-d0099f7656a2
* Version Independent ID: bf141ec4-d1ac-15eb-e175-4083b1b6880f
* Content: [You must specify a caption in the Caption property for Fields that exist on page objects. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0225-captionmustbefilledonpageforfields)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0225-captionmustbefilledonpageforfields.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0225-captionmustbefilledonpageforfields.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. This should be filed as a product bug instead. Please file a bug through your usual support channel. Thanks for your understanding.
