### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#106]
Individual RECORD functions are documented, but one has to search them out separately. It would be very convenient to have a list of other RECORD functions on one side of the page documenting each individual function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74f4650-4bde-bd87-0881-ef6fac238b48
* Version Independent ID: 35fcd85e-4d49-e0f7-98ba-90ddb3e2bb27
* Content: [FIND Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/find-function--record-)
* Content Source: [dynamics-nav/FIND-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/FIND-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **edupont**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We're working on improving the documentation for the AL language and will take your feedback into consideration. Thanks again.
