### ISSUE TITLE
Not when ShowCaption = false

### ISSUE THREAD

**Issue by MiePlougstrup** [MicrosoftDocs/dynamics365smb-devitpro-pb#1060]
This should not be applicable when you use the property ShowCaption = false, as the tooltips are not shown, when the caption is not shown. This would only result in unused tooltip text, that needs translations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ec6892-6853-a52a-095c-f4cf7f8a6f49
* Version Independent ID: db918e3c-7dde-0a8d-41db-7c6d6fa1ff57
* Content: [You must write a tooltip in the Tooltip property for all controls of type Action and Field that exist on page objects. See \[the style guide\](https://styleguides.azurewebsites.net/Styleguide/Read?id=2748&topicid=38066) for more information. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0218-tooltipmustbefilledonpageforfieldsandactions)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0218-tooltipmustbefilledonpageforfieldsandactions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0218-tooltipmustbefilledonpageforfieldsandactions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. If I understand you correctly, you get this validation error in the described scenario when unnecessary to provide a tooltip. This should be filed as a product bug instead in that case. Please file a bug through your usual support channel. Thanks for your understanding.
