### ISSUE TITLE
What is the default value?

### ISSUE THREAD

**Issue by chethanht** [MicrosoftDocs/dynamics365smb-devitpro-pb#1061]
There are 2 optional parameters for this function but this documentation does not tell me what is the default value of the parameters are not specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60835db-7fec-a288-a764-b84e604f3b64
* Version Independent ID: 6c3794bf-27b0-643c-b370-9ba9036da260
* Content: [LockTable Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-locktable-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/record/record-locktable-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-locktable-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, 

The default value for Wait is true and for VersionCheck is false: Record.LockTable(true, false). We will update this article. Thanks for the feedback!

**Comment by jswymer** [comment]
We have added this information to the article. The update will be published soon. Thanks for the feedback!
