### ISSUE TITLE
Example 1 wrong

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#1063]
Hi,
Example 1 is missing a dash before ConnectionType.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 265e086b-b5bc-245c-39b0-4a24a6e3ee73
* Version Independent ID: 64c32feb-8756-c4a6-98b9-369770d3a600
* Content: [New-NAVTableConnection (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/new-navtableconnection?view=businesscentral-ps-16&source=docs)
* Content Source: [businesscentral-ps-16/Microsoft.Dynamics.Nav.Management/New-NAVTableConnection.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-16/Microsoft.Dynamics.Nav.Management/New-NAVTableConnection.md)

**Comment by blrobl** [comment]
Hi, this will be fixed with the next refresh, thanks.
