### ISSUE TITLE
Misc suggestion

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1065]
This is not huge at all, maybe even picky. Almost all Code keys in Dynamics NAV for master tables are Code[20] with a Name or Description that is Text[50]. So why have an example with with Code[30] and Description[250]? All that does is give you something to pause over for a second as you realize it is not standard. Examples should be as close to standard and best practices as possible so you can focus on what you are trying to learn instead of remembering little details like a different key or description size.

I don't want to detract from a good walk-through, just trying to make it better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc13a127-253d-6438-52ed-319589d8d3ec
* Version Independent ID: 9bcc413c-55cb-a0e0-8ca2-f111658076fe
* Content: [Building your first sample extension that uses new objects and extension objects - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-example#feedback)
* Content Source: [dev-itpro/developer/devenv-extension-example.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-example.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your patience, but this is unfortunately not something that we can prioritize rewriting at this point. Thanks.
