### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1066]
The numbers have European separators. English US should use commas, not periods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98387b95-ce70-594b-b0e1-36ef1b5a6fb6
* Version Independent ID: 8a8d3822-49c4-1422-e046-0d7c9726c9b6
* Content: [Object Ranges - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-object-ranges)
* Content Source: [dev-itpro/developer/devenv-object-ranges.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-object-ranges.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, this issue is fixed with the next refresh of the docs.
