### ISSUE TITLE
Make screenshots expandable to improve poor quality

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1067]
The screenshots are so small of such poor quality that they are hardly readable. Normally, if you click a screen shot in a web page, it opens up in a separate, enlarged window. That would be extremely helpful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3f5d28-1484-ce76-b31d-7ee0d444ba0f
* Version Independent ID: bdea6ca9-e7bc-d324-03d5-364c0fcaee4e
* Content: [Debugging - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-debugging)
* Content Source: [dev-itpro/developer/devenv-debugging.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-debugging.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This is an animated .gif file that shows how to use the Debugger in VS Code. The .gif display sizes if you enlarge the browser, they get bigger. We evaluated that this was helpful for illustrative purposes and not inspecting the detail of code. This is the first time we get this feedback, we will leave it as is for now, but if we get more feedback, we can consider changing these into regular screenshots. Thanks.
