### ISSUE TITLE
Make screen shots expandable to improve poor quality

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1068]
As posted elsewhere, the VS Code screenshots are so small and of such poor quality that they are basically worthless. Usually, when you click a screenshot in a web page, it opens up in a separate page with a larger image. That would really be helpful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785520fb-23ff-62c0-ca0a-93579ea1979d
* Version Independent ID: 672f2743-3b8b-f676-f0e5-6c568ec28c20
* Content: [AL Code Navigation - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-code-navigation)
* Content Source: [dev-itpro/developer/devenv-al-code-navigation.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-code-navigation.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This is an animated .gif file that shows how to use the Go to Definition action in VS Code. The .gif display sizes if you enlarge the browser, they get bigger. We evaluated that this was helpful for illustrative purposes and not inspecting the detail of code. This is the first time we get this feedback, we will leave it as is for now, but if we get more feedback, we can consider changing these into regular screenshots. Thanks.
