### ISSUE TITLE
Is a performance hit warning needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1069]
Hello, 

I have been doing quite a bit of reading about extensions recently. One of the things I have noticed is people talking about the performance hit when using Table Extensions on large master tables, such as Item, Customer or Vendor. 

Should there be at least a passing mention about possible performance issues here with links to alternate strategies, since a newbie will never be testing with anything large enough to cause them to show up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95672845-1cc2-6535-bbec-da2ff1acd0a1
* Version Independent ID: 152f5357-cd5d-4e8a-6bdf-839a8c4b8b87
* Content: [Developing Extensions in AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-dev-overview)
* Content Source: [dev-itpro/developer/devenv-dev-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-dev-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. In the table of contents we have a whole section dedicated to Performance from different aspects, which is all that we have about performance right now, but I believe it should be visible. If you are experiencing something that is not described in that section, please let us know. Thanks.
