### ISSUE TITLE
Link is wrong

### ISSUE THREAD

**Issue by simcrest** [MicrosoftDocs/dynamics365smb-devitpro-pb#107]
The link to "Packaging the Permission Set" is not going to the right spot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 885cbacd-b3e7-1730-812c-9148ebfc90e9
* Version Independent ID: eb11ce7e-1efb-106c-5d79-19c206860da0
* Content: [Checklist for Submitting Your App - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission)
* Content Source: [dev-itpro/developer/devenv-checklist-submission.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-checklist-submission.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The link points to a topic which is very lengthy, but under the SourcePath you can read more about how to package the permission sets. With the next version of Business Central, or if you are in the Ready to Go program, you have the option of exporting permission sets using VS Code [Exporting Permission Sets](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-permission-sets).
