### ISSUE TITLE
Typo in See Also links

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#1070]
"Instal an Update" instead of "Install"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c934418-1448-eb40-9d9a-11c8c435f491
* Version Independent ID: a788c5c0-0e20-14f8-d4f4-a5e0eb646589
* Content: [The Microsoft_Application.app File - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-application-app-file)
* Content Source: [dev-itpro/developer/devenv-application-app-file.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-application-app-file.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, this will be fixed with the next push to live.
