### ISSUE TITLE
Misleading or wrong information on this page.

### ISSUE THREAD

**Issue by rkirsten** [MicrosoftDocs/dynamics365smb-devitpro-pb#1071]
In the second paragraph you state: "The navigation menu contains one or more root menu items that expand to display a set of links to pages, and other objects like reports, XmlPorts, and codeunits." That is not true. If I stick with your wording, the navigation menu is the top menu. Here, I can only link pages. Strange enough: If I refer a report, BC shows me the page where pages ID is the reports ID. (V14) In paragraph one you refer to this page https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-role-centers. Here, you have it right. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d29386a-cd69-bd44-b2be-8a63fa826690
* Version Independent ID: 5fafae47-9391-1203-b9db-592bd5c10617
* Content: [Adding Menus to the Navigation Area - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-menus-to-navigation-pane)
* Content Source: [dev-itpro/developer/devenv-adding-menus-to-navigation-pane.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-menus-to-navigation-pane.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback and patience. This issue is fixed with the next doc refresh.
