### ISSUE TITLE
Compiling RDL Layout to find Errors in BC

### ISSUE THREAD

**Issue by Lilithyan** [MicrosoftDocs/dynamics365smb-devitpro-pb#1073]
Hello,

is there a way to compile the RDL Layout in BC15 to check if there are any errors (e.g. something not right with a hidden-definition)? If I upload an app with a report whose layout has an error I only get a generic error along the lines of "Report could not be created due to Layout Error". The only two ways I have found to get an exact error message is to either look into the Event Viewer or to send the report via the option "Plan" through a job queue and then seeing the error there. 
There must be a better way to find an error in a RDL Layout, right? The old development client with C/AL would do it when compiling the report object, so there should be something now right?

Thanks for any help in advance.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. This repo is used for documentation feedback. Please use your usual support channel to get help with this question. Thanks.
