### ISSUE TITLE
The application symbols do not exist when following the steps in this article.

### ISSUE THREAD

**Issue by ndagh** [MicrosoftDocs/dynamics365smb-devitpro-pb#1074]
Hi Team when you follow these steps the application symbols don't exist, however the article seems to imply that they should by following the steps. I have found someone else with a similar issue. Can you please advise? 

https://community.dynamics.com/nav/b/olisterrs-nav-bc-blog/posts/resolving-the-tenant-default-is-not-accessible-error-or-regenerating-new-symbols-for-business-central-on-premise-for-customised-database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879a0942-86ad-c632-87b6-a06c5bee55eb
* Version Independent ID: b93ee352-5c43-c7c8-0b61-d72a0278ca29
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-publish-extensions#feedback)
* Content Source: [dev-itpro/upgrade/upgrade-publish-extensions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-publish-extensions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The article describes a version, which is no longer supported. Thanks.
