### ISSUE TITLE
FileNaming Convention is not reflected in CodeCop Rule AA0125

### ISSUE THREAD

**Issue by JulianTillmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#1077]
The CodeCop rule AA0125 Forces the Suffix or Prefix in the filename, here it's explicitely removed from the filename: &lt;ObjectNameExcludingPrefix&gt;.al

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#feedback)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - this is indeed contradictory - will be fixed with the next refresh of the docs. Thanks.
