### ISSUE TITLE
Is Field or Control triggers?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1078]
The description is now ambiguous as both is used. In IMHO it should be called "control trigger".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0e36d7-395e-ed94-2e77-f7edb74e7757
* Version Independent ID: 1f838a73-fefc-8fbd-bcb9-cc9ad899dbdd
* Content: [Page and Action Triggers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-page-and-action-triggers?source=docs)
* Content Source: [dev-itpro/developer/triggers/devenv-page-and-action-triggers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-page-and-action-triggers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by lvanvugt** [comment]
![image](https://user-images.githubusercontent.com/18466198/78715325-89bb7e00-791d-11ea-9bcf-594a1f93b381.png)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The triggers are at this point auto-generated from source code, sorted, and searchable in the table of contents. They are sorted by Field triggers (table fields) and Page Field triggers (control triggers). Thanks.
