### ISSUE TITLE
AA0214 Codecop warning while NOT saving data in a procedure. 

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-devitpro-pb#1079]
I defined a local variable of type Record in a procedure. The recordset is read, and some data is collected. I do not write the record to the database. I even use FindSet(false) to indicate that I'm not going to modify records.

Still, I get warning AA0214 'The local record should be modified before saving to the database.'

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please open a bug for this instead, this is the repo for documentation issues. The compiler should still let you compile, because you only get a warning, but it sounds like a bug. Thanks.
