### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ThomasBrodkorb** [MicrosoftDocs/dynamics365smb-devitpro-pb#108]
I'm missing examples for the usage of these new types.
It is not clear if a JsonObject must be initialized somehow or if it can be used right away.
How to test if a JsonObject has been initialized or is empty?

This would all make sense to know.

The current documentation does not provide any information beyond the information we get from Intellisense already.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573a2e00-40ff-0898-abdc-35e2711411aa
* Version Independent ID: 171b3584-0b9a-e92c-f3ed-577f2515d7f4
* Content: [JsonObject Class - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/api/jsonobject-class)
* Content Source: [dev-itpro/developer/api/jsonobject-class.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/api/jsonobject-class.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we are aware of missing examples, but working to improve the docs. We will have examples for this with one of our next refreshes. Thanks again.
