### ISSUE TITLE
How to Upgrade from BC15 -> BC16

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1080]
Please add instructions how to upgrade from BC 2019 Release Wave 2 (BC15) to BC 2020 Release Wave 1 (BC16).

Or is it same as Installing an Update?
Are there any restrictions (like upgrade to BC16.0 is maybe only possible from 15.4 or later version)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa6ac4e-7108-24ae-cf48-649864aaa872
* Version Independent ID: e8692393-899e-e511-4b42-5e4c230e5178
* Content: [Upgrade to Business Central 2019 Wave 2 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-overview-v15)
* Content Source: [dev-itpro/upgrade/upgrade-overview-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-overview-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by ywleong** [comment]
Hi, you can refer the link below-Task 4 Convert the version 14.0 application database to the version 15.0 platform
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15#task-1-install--2019-release-wave-2-version-150

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

Upgrade content for BC16 is now available at [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-overview-v16](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-overview-v16). 

We hope this answers some of your questions.
