### ISSUE TITLE
Missing colons in powershell script example

### ISSUE THREAD

**Issue by aleselias** [MicrosoftDocs/dynamics365smb-devitpro-pb#1081]
Please add colons to power shell script example to make it easier to use it as a starting point for local tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c207282-cbc6-4192-8c68-93833d882079
* Version Independent ID: d6ae70c2-0f8d-17b6-58e2-59d008049389
* Content: [AL Table Proxy Generator - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-table-proxy-generator#feedback)
* Content Source: [dev-itpro/developer/devenv-al-table-proxy-generator.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-table-proxy-generator.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this - this is fixed now, and will be available with the next doc refresh. Thanks.
