### ISSUE TITLE
index of not supported

### ISSUE THREAD

**Issue by eccountable** [MicrosoftDocs/dynamics365smb-devitpro-pb#1082]
I am getting an error when using "indexof" filter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc2d41b-a16e-2eb8-5acf-963df0a6020b
* Version Independent ID: 337d82f5-41e3-05d0-bde4-1ea6bd61b372
* Content: [Using Filter Expressions in OData URIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris)
* Content Source: [dev-itpro/webservices/use-filter-expressions-in-odata-uris.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/use-filter-expressions-in-odata-uris.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This sounds like a bug, please use your usual support channel to file a bug. Thanks.
