### ISSUE TITLE
The Important points to note line about immediately visible to all users should be highlighted near the top of the document

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1085]
This line, which is the first Important points to note: "Every time you start designing, you're effectively creating a new extension. Your changes are immediately visible to other users" is critically important and could be missed by someone scanning the page. It should be copied up to the top and appear in the colored box with the only available in Sandbox note. I would suggest that you leave it where it currently is, but also show it above as noted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e31ad37-068e-3007-2e46-7afc15f6b73b
* Version Independent ID: cd16bd61-cd0d-be6b-0af7-c1e9d81c81f5
* Content: [Using Designer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inclient-designer)
* Content Source: [dev-itpro/developer/devenv-inclient-designer.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-inclient-designer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Yes, I agree - this note will be moved up for better visibility - available with the next doc refresh. Thanks!
