### ISSUE TITLE
Additional #1085 feedback

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1086]
If you choose to leave the first line of the Important things to note as it is, then the words immediately & other should be changed to bold.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e31ad37-068e-3007-2e46-7afc15f6b73b
* Version Independent ID: cd16bd61-cd0d-be6b-0af7-c1e9d81c81f5
* Content: [Using Designer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inclient-designer)
* Content Source: [dev-itpro/developer/devenv-inclient-designer.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-inclient-designer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be further emphasized with the next doc refresh. Thanks.
