### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1088]
Near the bottom of the article, there is a list of To do this, see the links. There are no links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abe2d3ca-a714-6bef-c797-e0894ac973d5
* Version Independent ID: f3ac9206-aac1-1a0a-20be-853b111c0c80
* Content: [Removing Elements from the User Interface According to Permissions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/hide-ui-elements)
* Content Source: [dev-itpro/administration/hide-ui-elements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/hide-ui-elements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This article is work in progress, so the links are commented out for now - and will be added back later when we have that content ready. Thanks for your understanding.
