### ISSUE TITLE
Dynamics 365 Business Central restrictions on opening System or Virtual tables using RecordRef.OPEN

### ISSUE THREAD

**Issue by PrebenRasmussen** [MicrosoftDocs/dynamics365smb-devitpro-pb#109]
Why was the option of opening a RecordRef with a system or virtual table removed?
I.e. using "RecordRef.Open(Database::User)" is not allowed in Business Central.
Using "RecordRef.GetTable(tablevar) is perfectly possible when using a table variable of i.e. Database::User (2000000120).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b830ce96-2389-a04a-3787-e2bc8e71f7b5
* Version Independent ID: e951ea36-2cf1-5fc7-fcab-470dd961cc97
* Content: [OPEN Method (RecordRef) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-open-method-recordref)
* Content Source: [dev-itpro/developer/methods/devenv-open-method-recordref.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-open-method-recordref.md)
* Service: **dynamics365-financials**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation issues and bugs, please use the support or AL repo for any code-related questions. Thanks.
