### ISSUE TITLE
Simple example would be really helpful

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1095]
As the subject says :-).

Have a great day1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672a4b63-c188-3701-80b1-36c17826e9d2
* Version Independent ID: 830b23a3-012c-d567-70aa-d549aeef8c04
* Content: [Style Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-style-property)
* Content Source: [dev-itpro/developer/properties/devenv-style-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-style-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, sorry for the delayed response. A code sample will be available with the next refresh, thanks.
