### ISSUE TITLE
Change collation procedure failure

### ISSUE THREAD

**Issue by SpyFr** [MicrosoftDocs/dynamics365smb-devitpro-pb#1096]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/cside/cside-change-database-collation

The procedure described  is unsuccessful.
When importing data, the following issue occurs (in french bellow) :

Import-NAVData : Impossible d'importer les données, car le fichier spécifié contient l'extension suivante qui n'a pas été synchronisée avec la base de données: nom=Intelligent Cloud Base, 
éditeur=Microsoft, version=16.0.11240.12076.

Extensions are not synced and there is no help to get around this issue.
Something's missing ?
Is ther a way to set the collation during service setup ??

BC16 (April 2020) on-premises

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56c1e401-e53b-ffaa-c59e-661eb6145f68
* Version Independent ID: 815fc7a8-950c-60c5-dcd1-4dbe5131c304
* Content: [How to Alter Databases - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/cside/cside-change-database-collation#feedback)
* Content Source: [dev-itpro/cside/cside-change-database-collation.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/cside/cside-change-database-collation.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. I think the article needs to be updated for 16.0. 

I assume that you have installed the Demo Database during Setup wizard (setup.exe), Correct? There is no way to choose the collation during setup. If this is your scenario, then try the following steps. 

1. Follow the steps in [Changing the collation if extensions are installed on the tenant
](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/cside/cside-change-database-collation#changing-the-collation-if-extensions-are-installed-on-the-tenant) up to and including step 8 Synchronizing the Tenant. 
2. Run Sync-NAVApp to synchronize the extensions in the following order: 
 
    - System Application extension
    - Base Application extension
    - Application extension
    - other extensions
3. Import tenant data:
`Import-NAVData -ServerInstance <server instance> -Tenant <tenant ID> -FilePath <file> -IncludeGlobalData -AllCompanies`

**Comment by SpyFr** [comment]
Hello, thanks for your helpful answer.

You were right, Business Central 16 installed from DVD setup.

This methodology is correct but I will add details. Here is what I did step by step:
Considering :

   - "MySQLInstance" as SQL instance
   - "OldDB" as current database name
   - "NewDB" as targeted DB with choosen collation
   - "MyServerInstance" as Server instance name.

- Backup OldDB
- Uninstall (but not delete) all extensions but System Application, Base Application & Application.
- Restart Service

- SSMS : Create a database with desired collation named "NewDB"

- PowerShell :
   - Import-Module "C:\Program Files\Microsoft Dynamics 365 Business Central\160\Service\NavAdminTool.ps1"
   - Get-NAVAppInfo MyServerInstance
   - Keep the list in a text file
   - Export-NAVData -ServerInstance MyServerInstance -IncludeApplication -IncludeApplicationData -IncludeGlobalData -AllCompanies -FilePath c:\tempbc\MyServerInstance.navdata
   Import-NAVData -DatabaseServer "MySQLInstance" -DatabaseName New -IncludeApplication -IncludeApplicationData -FilePath c:\tempbc\MyServerInstance.navdata    
   Set-NAVServerConfiguration MyServerInstance -KeyName DatabaseName -KeyValue NewDB
   Restart-NAVServerInstance -ServerInstance MyServerInstance
   Sync-NAVTenant -ServerInstance MyServerInstance
   Sync-NAVApp -ServerInstance MyServerInstance -Name 'System Application' -Mode Add  # ! N° 1
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'Base Application' -Mode Add  # ! N° 2
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'Application' -Mode Add  # ! N° 3
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'Intelligent Cloud Base' -Mode Add  # ! N° 4
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'Business Central Intelligent Cloud' -Mode Add  # ! N° 5 (depend on Intelligent Cloud Base)
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'WorldPay Payments Standard' -Mode Add
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'Send To Email Printer' -Mode Add
   Sync-NAVApp -ServerInstance MyServerInstance-Name '_Exclude_APIV1_' -Mode Add
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'Essential Business Headlines' -Mode Add
   Sync-NAVApp -ServerInstance MyServerInstance-Name '_Exclude_ClientAddIns_' -Mode Add
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'Late Payment Prediction' -Mode Add
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'Sales and Inventory Forecast' -Mode Add
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'AMC Banking 365 Fundamentals' -Mode Add
   Sync-NAVApp -ServerInstance MyServerInstance-Name 'PayPal Payments Standard' -Mode Add
   Sync-NAVApp -ServerInstance MyServerInstance-Name '[My app]' -Mode Add
   Import-NAVData -ServerInstance MyServerInstance-IncludeGlobalData -AllCompanies -FilePath c:\tempbc\MyServerInstance.navdata

- Reinstall all extensions

I don't understand why but data from MyApp has been restored as well although the extension has been unistalled before exporting data.

**Comment by jswymer** [comment]
Hello, glad it worked out!  As for MyApp data being restored, it might be because uninstall alone will not remove the data. Sorry if I have misunderstood the issue.

**Comment by SpyFr** [comment]
That was helpful.

I recommend for end customers to evaluate the advantage of choosing any CIAI type database collation.
