### ISSUE TITLE
When to set on table level?

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1097]
Could you please add information on when best to choose a value on table level? Does a value in table level mean that it automatically applies to all fields, thus we do not need to set it on field level anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2775bc63-b9cf-b4e0-b634-d69bb2454a1a
* Version Independent ID: 0fed25f6-d097-5cb6-e4fb-0dc07738472c
* Content: [DataClassification Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-dataclassification-property)
* Content Source: [dev-itpro/developer/properties/devenv-dataclassification-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-dataclassification-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by NKarolak** [comment]
Any news? :-)

**Comment by blrobl** [comment]
Hi, sorry for the very long wait. When the **DataClassification** property is set on a table level, the fields on the table will inherit the property value. If the **DataClassification** property is set on both a table and field level, then the data classification specified on a field level will override the one from the table. This will be added in the next refresh, thanks.
