### ISSUE TITLE
type

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1098]
I believe the following sentence should read data in a similar manner

At the same time, overloaded procedures remove the need for abusing the Variant data type for the purpose of processing different types of data a similar manner and allows the developer to write strongly-typed code and rely on the compiler for validation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03fc1b85-0180-bfd5-8748-d19b8cc3ce4a
* Version Independent ID: 72ebe788-b3e0-b1da-313a-6b93d9862c3e
* Content: [Procedure overload - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-overload-method)
* Content Source: [dev-itpro/developer/methods/devenv-overload-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-overload-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this, it will be fixed with the next refresh.
