### ISSUE TITLE
Wrong counter name.

### ISSUE THREAD

**Issue by salgiza** [MicrosoftDocs/dynamics365smb-devitpro-pb#11]
Just a small correction but it should say:

5. In the Available counters list, expand *Microsoft* Dynamics NAV, and select one or more counters.

That's the name both in NAV 2017 and NAV 2018, and it can be easy to miss if you search for counters that start with 'D' instead of 'M'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0cbc546-146f-e39f-908c-a4f95aa5dc25
* Version Independent ID: 91f238a3-dad9-0a64-8765-7eac8f144faa
* Content: [How to: Set up Performance Counters in Windows Performance Monitor - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--set-up-performance-counters-in-windows-performance-monitor)
* Content Source: [dynamics-nav/How-to--Set-up-Performance-Counters-in-Windows-Performance-Monitor.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Set-up-Performance-Counters-in-Windows-Performance-Monitor.md)
* Service: **unspecified**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for your feedback. This will be fixed in the next refresh of the documentation.
