### ISSUE TITLE
App.json logo property suggests the value should be a URL

### ISSUE THREAD

**Issue by ShadowXVII** [MicrosoftDocs/dynamics365smb-devitpro-pb#110]
Instead, it's described in v0.16.26913 as a "relative path to the app package logo from the root of the package"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This is fixed in the next refresh of the docs.
