### ISSUE TITLE
Static methods does not exist

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1100]
In the first paragraph, methods Names, Ordinals and FromInteger are mentioned.
Actually these methods are not existing in AL 5.0 (2020 wave 1).

And like I mentioned here https://github.com/microsoft/AL/issues/5805,
* FromInteger might have sense but is quite weird
* Names and Ordinals do not make sense in the section "The following methods are available on the Enum data type": is not it a doc mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eae4d04-d4e8-037d-a883-8769a8532ba5
* Version Independent ID: 81be355d-9d1d-598e-cb7b-d10d5e7a963b
* Content: [Enum Data Type - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/dev-itpro/developer/methods-auto/enum/enum-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/enum/enum-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/enum/enum-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the methods do exist on the Enum Data Type. We will make the docs clearer on the fact that the static methods on the enum are related to a specific type of the enum as mentioned in https://github.com/microsoft/AL/issues/5805. Thanks.
