### ISSUE TITLE
FilterPageBuilder does not work correctly.

### ISSUE THREAD

**Issue by Tobiasgut** [MicrosoftDocs/dynamics365smb-devitpro-pb#1101]
We try to use filterpagebuilder on a table.

In the Windowsclient evrything works fine.
We can add an remove fields and filters:
![image](https://user-images.githubusercontent.com/63726214/79342377-584e3e00-7f2d-11ea-9981-fbdd1ca7fa88.png)

In the Webclient it is not possible to add or remove any fields/filters:
![image](https://user-images.githubusercontent.com/63726214/79342731-c561d380-7f2d-11ea-88d3-19047f93942a.png)

Our sourcecode:
![image](https://user-images.githubusercontent.com/63726214/79342924-0823ab80-7f2e-11ea-9931-3b758be7bca2.png)

BCVersion: 14.0.38650.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb308a6-58fb-5a70-351d-ffef8d5e84d2
* Version Independent ID: 78dd367f-edc8-1444-0c33-1b7825e519ca
* Content: [FilterPageBuilder Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/filterpagebuilder/filterpagebuilder-data-type)
* Content Source: [dev-itpro/developer/methods-auto/filterpagebuilder/filterpagebuilder-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/filterpagebuilder/filterpagebuilder-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is used for documentation feedback. This might be a bug, please use your usual support channel to file a bug. Thanks.
