### ISSUE TITLE
BC v16 app testing

### ISSUE THREAD

**Issue by arvitis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1102]
till v15 we were developing the app source extensions using the dev license from partner source containing our requested object range. What about v16 dev with app source range?Moreover, the PartnerSource platform is being retired. What are the plans here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f11a3974-3f3b-33b3-5a55-f0fa5c6d558f
* Version Independent ID: b5fd581c-4f43-24cc-8821-2a8fc5f0a647
* Content: [Add-On Apps - Getting You Started - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started#feedback)
* Content Source: [dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-liober
* Microsoft Alias: **v-liober**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is used for documentation issues only. Please reach out to d365val@microsoft.com for help with these questions. Thanks.
