### ISSUE TITLE
Additional info

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1104]
The StartsWith method has Value as the argument name instead of Chars. Chars is slightly confusing as the plural implies an array, especially since c# is an array of Chars. I think it would be a lot less confusing if Value was used with TrimStart, TrimEnd, StartsWith and EndsWith.

Ok :=   Text.StartsWith(Value: Text)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc97f924-68d4-ec58-001a-10d68f0e0a7c
* Version Independent ID: 6199c894-557a-3c58-cbef-46b88748ff4c
* Content: [TrimStart Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-trimstart-method)
* Content Source: [dev-itpro/developer/methods-auto/text/text-trimstart-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/text/text-trimstart-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is used for documentation feedback - please use [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) for requests for functionality. Thanks.
