### ISSUE TITLE
Change Page title to include Examples so that it displays that way as a google search result

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1106]
This is an excellent example of what I wish there was a lot more of, actual working examples. With the plethora of results that you get with any google search, there is nothing that stands out about this one over others. I would suggest including the word Examples somewhere in the page title so that it is know from a search without having to open up the page to see that this does indeed contain actual examples. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0887a61-8d1d-916b-7ecf-35d29714dc7c
* Version Independent ID: 804c1bb1-3812-1cf0-be9d-8e59e17e7c87
* Content: [Create FlowFields and FlowFilters - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-flowfields-and-flowfilters)
* Content Source: [dev-itpro/developer/devenv-creating-flowfields-and-flowfilters.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-creating-flowfields-and-flowfilters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the kudos and for the suggestion. We have SEO optimized the topic for now, and hope this helps. With the next doc refresh. Thanks.
