### ISSUE TITLE
In 'See Also' 'Upgrading the Data' links to Spring 2019 documentation

### ISSUE THREAD

**Issue by jiraffex** [MicrosoftDocs/dynamics365smb-devitpro-pb#1107]
In 'See Also' 'Upgrading the Data' links to 14.x documentation vs the 15.x documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa6ac4e-7108-24ae-cf48-649864aaa872
* Version Independent ID: e8692393-899e-e511-4b42-5e4c230e5178
* Content: [Upgrade to Business Central 2019 Wave 2 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-overview-v15#feedback)
* Content Source: [dev-itpro/upgrade/upgrade-overview-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-overview-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback. The links to these articles have been removed from the See Also section and replaced by relevant links to Spring 2019 articles. The updated article will be published soon.
