### ISSUE TITLE
Possible type

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1108]
In the following sentence, there is no left and right is used twice. I'm guessing the first right should be left instead.

When you set a field to span multiple columns, the field occupies the cells in the columns to the right, and existing fields in the occupied cells are moved to the right. You can also set a field to span multiple rows and columns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbfa8ab-1e61-8974-f781-c59676cfc048
* Version Independent ID: 38350590-c7ed-bf50-9f8d-17b9fd709b93
* Content: [Arrange Fields Using Grid Control - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-gridlayout-control)
* Content Source: [dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-gridlayout-control.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-gridlayout-control.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Yes, the first right should be left - this will be fixed with the next doc refresh. Thanks.
