### ISSUE TITLE
How about some sample code

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1109]
It would be great if this topic included some abbreviated code to show how the various parts are implemented. Relatively easy topics will frequently have examples, while more complex topics rarely do, an admitted generalization but a pet peeve. The more complex the topic, the less likely there is any sample code included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd18d691-5db9-38bf-422c-e70653177be3
* Version Independent ID: 549b84ba-bd7f-43c8-286a-c6e38544b1aa
* Content: [Page Parts Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-parts)
* Content Source: [dev-itpro/developer/devenv-designing-parts.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-designing-parts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @mikebcMSFT
* Microsoft Alias: **mikebc**

**Comment by blrobl** [comment]
Hi,  thanks for your feedback and sorry for the delatyed response. We have added topics about how the different page parts are implemented: [Working with List Parts](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-listparts), [Working with Card Parts](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-cardparts) and [Creating a Role Center Headline](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-create-role-center-headline), where you can find such code examples.

**Comment by j2associates** [comment]
Excellent, thank you. Are the above items linked in the original topic for
which I gave feedback?

**Comment by blrobl** [comment]
Yes, they are linked throughout the topic. You can also find them in the table of contents on the left.

**Comment by j2associates** [comment]
Excellent. One other suggestion. I have been going through the links
above, very nice work by the team responsible for creating the
content. Each of the links has very nice sample code demonstrating the
topic discussion. It would be fantastic if they were pulled in
together as a comprehensive example (e.g. a CarPage with a ListPart
and FactBox, etc). Let me know if that should be a separate feedback
and I'll be happy to provide the same. If so, please include the link
to the topic to which I should suggest it.

Have a great day!

**Comment by blrobl** [comment]
Yes, please file in a separate issue with this suggestion. You can do so in this same topic, thanks!

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
