### ISSUE TITLE
What this datatype is?

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1110]
Could you enhance the documentation to explain what this datatype is in AL?
In my understanding, this datatype does not exist or at least is not exposed to the developer.

For instance, this page :
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/database/database-userid-method
explains that the return value of Database.UserId is a String... but the actual datatype (in the point of view of the developer) is a Text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 399549f1-f42e-ff58-b058-fa567a7a8063
* Version Independent ID: 3639242b-0430-6d9c-70d9-6467a7e7fa8d
* Content: [String Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/string/string-data-type)
* Content Source: [dev-itpro/developer/methods-auto/string/string-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/string/string-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we auto-generate the methods for AL and this is a bug in our generator. There is not a String data type available, you must use Text instead. I will file a bug for this and retire the String data type topic to avoid confusion. Thanks.
