### ISSUE TITLE
Applicable version

### ISSUE THREAD

**Issue by lhtan-dev** [MicrosoftDocs/dynamics365smb-devitpro-pb#1111]
Hello, which version onwards does App Insight is able to be configured for the SaaS and On-premise model?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5110b5f-fbc7-66de-b57b-3c4a3adc7ff4
* Version Independent ID: 24a63a6f-3667-faa1-dbb9-4c8ba42b4bf1
* Content: [Environment Telemetry - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-telemetry)
* Content Source: [dev-itpro/administration/tenant-admin-center-telemetry.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/tenant-admin-center-telemetry.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Hello,

App Insights support was introduced in Business Central 2019 Release Wave 2 (Update 1), for both SaaS and On-premises. However, Business Central 2019 Release Wave 2 only supported a couple traces, specifically authorization and long running SQL queries. The articles have been tagged to include which version App Insights was introduced. Thanks for the feedback!
