### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ClausHamann** [MicrosoftDocs/dynamics365smb-devitpro-pb#1112]
The link "How to use Markdown for writing Docs" under "Working in MarkDown" does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b071c8b6-3c21-6982-4de6-1935011d1e90
* Version Independent ID: 43f07178-724f-aae9-bd2e-befb42da16e4
* Content: [User assistance model - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/user-assistance#feedback)
* Content Source: [dev-itpro/user-assistance.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/user-assistance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The referenced article is no longer available, please use [Docs Markdown reference](contribute/markdown-reference). The topic will be updated with the next refresh of the docs.
