### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by ClausHamann** [MicrosoftDocs/dynamics365smb-devitpro-pb#1113]
In the sentence "You can also create give powerful demos that will attract prospects in your market space" under "Take prospects and customers online", the word "create" or "give" should be removed or "and" should be added. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acb6c687-4014-efa0-371a-d64ed842b862
* Version Independent ID: f1dfdfb2-5b68-a6b9-dc77-bb119f71f58b
* Content: [Deployment overview for Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/deployment#feedback)
* Content Source: [dev-itpro/deployment/Deployment.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/Deployment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - it will be fixed with the next refresh of the docs.
