### ISSUE TITLE
Inversion between what the text says and the illustration

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1114]
In the paragraph Move tables and fields down the dependency graph, according to the illustration: field Field C-2 is the customization (not C-1). The inversion continues all along the paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d45b661-4242-0aad-92f2-91a2062358f3
* Version Independent ID: 3e356cf3-5e09-6881-9a7a-a92233b5f8b2
* Content: [The Migration.json File - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-table-fields)
* Content Source: [dev-itpro/developer/devenv-migrate-table-fields.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-migrate-table-fields.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! Good catch. The article has been fixed.
