### ISSUE TITLE
Typo in title

### ISSUE THREAD

**Issue by Kowa63** [MicrosoftDocs/dynamics365smb-devitpro-pb#1115]
Obsolete spelling 'Developement' -&gt; Development

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db94f60-5e26-c703-7beb-1fce11b25ddc
* Version Independent ID: 388e5659-b00b-126d-541a-2028024cdb09
* Content: [Working with Sandboxes and Entitlements - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-sandbox-entitlements)
* Content Source: [dev-itpro/developer/devenv-work-sandbox-entitlements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-sandbox-entitlements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @freddydk
* Microsoft Alias: **freddyk**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
