### ISSUE TITLE
Why has this NAV topic not been included here?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1117]
https://docs.microsoft.com/en-us/dynamics-nav/captionclass-functionality

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5321a03-193e-b6ca-81e5-2880dcf6ac65
* Version Independent ID: e8433b54-2d18-87e2-049d-cb4f4df736ec
* Content: [CaptionClass Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-captionclass-property)
* Content Source: [dev-itpro/developer/properties/devenv-captionclass-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-captionclass-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, this issue is fixed with the next refresh of the docs.
