### ISSUE TITLE
Copied more than you intended, perhaps? ;-)

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#1119]
"and this type of page cannot be displayed in the user interface" - this topic is about queries, but this sentence appears to be borrowed from the one on API pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8136165a-50e7-557b-036f-edf3ba283b2e
* Version Independent ID: 5772270e-3e62-157a-12ea-68c71446483a
* Content: [API Query Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-querytype#feedback)
* Content Source: [dev-itpro/developer/devenv-api-querytype.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-api-querytype.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this and sorry for the delay in the response. It will be fixed with the next doc refresh.
