### ISSUE TITLE
Small type

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1121]
The following sentence should be task is enqueued. 
You do not have to assign a value to this variable, because an ID will be assigned automatically when the background task enqueued.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591f8762-9808-22f5-112d-f6d80f337b0e
* Version Independent ID: 6731b849-04f3-9bd2-5877-8c2bf26b8f34
* Content: [Page Background Tasks - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-background-tasks)
* Content Source: [dev-itpro/developer/devenv-page-background-tasks.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-background-tasks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! The typo has been fixed and an update will be out soon.

**Comment by j2associates** [comment]
Hello,

It would be nice if your email resolution messages included a link to the
page from which the feedback originated.

Thanks,

Gary

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we're unfortunately not able to change the format of these messages, this is standard GitHub. But a great suggestion. Thanks.
