### ISSUE TITLE
ntauthentication "0" instead of "no"

### ISSUE THREAD

**Issue by jenswienand** [MicrosoftDocs/dynamics365smb-devitpro-pb#1122]
when using the cmdlet with username and password and a non english enviroment an error occur. 
> ---------------------------
> Microsoft Dynamics NAV Development Environment
> ---------------------------
> Die Wahlmöglichkeit 'no' ist nicht vorhanden.
> Die Wahlmöglichkeiten sind:
> Nein, Ja
> ---------------------------
> OK   
> ---------------------------
The error is caused by "ntauthentication=**no**", a param from the finsql.exe 
I would be good to change it into "ntauthentication=**0**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c4378d2-712a-2cb8-84bd-8bd5874ff3fe
* Version Independent ID: d60dda50-064b-9a5b-9bf2-98958cc5d4b4
* Content: [Export-NAVApplicationObject (Microsoft.Dynamics.Nav.Ide)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.ide/export-navapplicationobject?view=dynamicsnav-ps-2017#feedback)
* Content Source: [dynamicsnav-ps-2017/Microsoft.Dynamics.Nav.Ide/Export-NAVApplicationObject.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/dynamicsnav-ps-2017/Microsoft.Dynamics.Nav.Ide/Export-NAVApplicationObject.md)

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. This sounds like a bug. Please use your usual support channel to report this. This repo is for reporting doc issues only. Thanks.
