### ISSUE TITLE
Bad code

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1123]
This code to invoke the Background Task occurs near the bottom of the Page Extension sample code:

CurrPage.EnqueueBackgroundTask(WaitTaskId, 50100, TaskParameters, 1000, PageBackgroundTaskErrorLevel::Warning);

You hard coded the Codeunit ID 50100 from the sample code used to create the Codeunit earlier in the article. This will assuredly cause some poor soul some consternation and lost time when they innocently change the ID number of the Codeunit and then wonder why the code doesn't work.

1. Follow your own best practices and use Codeunit::PBTWaitCodeunit so that if someone made changes they will get a compile error
2. Add a note in the Codeunit and Page Extension article explanations pointing out that the actual Codeunit number is used in the Background Task invocation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591f8762-9808-22f5-112d-f6d80f337b0e
* Version Independent ID: 6731b849-04f3-9bd2-5877-8c2bf26b8f34
* Content: [Page Background Tasks - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-background-tasks)
* Content Source: [dev-itpro/developer/devenv-page-background-tasks.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-background-tasks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks! The article has been updated and the new version will be published soon.
