### ISSUE TITLE
Price Calculation Hyper Link is not working

### ISSUE THREAD

**Issue by MaheshUppala** [MicrosoftDocs/dynamics365smb-devitpro-pb#1126]
Very useful information about the extended price calculations.
If i click on Price calculations in the first  paragraph its redirecting 404-Page Not found Error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32c26d28-1789-81d6-d3df-45cf91c09ef7
* Version Independent ID: 35bfccd5-c11f-a78f-e01c-bb95d0e1ee76
* Content: [Extending Price Calculations - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-best-price-calculations#feedback)
* Content Source: [dev-itpro/developer/devenv-extending-best-price-calculations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extending-best-price-calculations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, the link will be fixed with the next refresh of the docs. This was the intended link [Best Price Calculation](/dynamics365/business-central/sales-how-record-sales-price-discount-payment-agreements#best-price-calculation). Thanks.
