### ISSUE TITLE
Explain how publisher & subscriber argument list should match

### ISSUE THREAD

**Issue by aablasco** [MicrosoftDocs/dynamics365smb-devitpro-pb#1127]
I thought that publisher & subscriber parameter list should match exactly: same number of parameters
& same types but I found an example on [Substituting Reports](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-substituting-reports):
```
codeunit 50100 "Substitute Report"
{
    [EventSubscriber(ObjectType::Codeunit, Codeunit::ReportManagement, 'OnAfterSubstituteReport', '', false, false)]
    local procedure OnSubstituteReport(ReportId: Integer; var NewReportId: Integer)
    begin
       // ...
    end;
}
```
The subscriber has only 2 parameters but when I looked for the event publisher, I found it has 5 parameters:
```
codeunit 44 ReportManagement
{
       // ...
    [IntegrationEvent(false, false)]
    local procedure OnAfterSubstituteReport(ReportId: Integer; RunMode: Option Normal,ParametersOnly,Execute,Print,SaveAs,RunModal; RequestPageXml: Text; RecordRef: RecordRef; var NewReportId: Integer)
    begin
    end;
       // ...
}
```
I tested it & it works: the subscriber gets executed but the surprise caused me some questions.

¿Which arguments can be left out? 
I think var arguments should always be used

¿Is order relevant? ¿Can publisher declare (A, B, C) and subscriber declare (C, B, A)?

¿How does arguments get assigned? ¿By name? ¿By type?

I think this question should be fully documented so users don't have to guess what the rules are

This is the first time I found something that is not explained on the superb documentation so
I decided to open this issue. I hope it will help to make the docs better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847f9637-606b-5022-0891-81481a7eb283
* Version Independent ID: 35643c3c-bb2d-e1ef-6ebd-556158d9d8e7
* Content: [Subscribing to Events - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-subscribing-to-events#feedback)
* Content Source: [dev-itpro/developer/devenv-subscribing-to-events.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-subscribing-to-events.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by j2associates** [comment]
Hello aablasco, The event publisher determines what arguments are made available and whether or not they are var. You can then use as many as you need in whatever order you declare them in your own procedure. We tend to declare them all just for documentation purposes, but that is certainly not a requirement. If we omit some, we also try to otherwise declare them in the same order as the event publisher, but again, this is not a requirement. I hope this helps.

**Comment by aablasco** [comment]
Thanks @j2associates  for your reply.

I found your answers are accurate but I would prefer it will be written on the docs site.

The VSCode & the compiler will check for them so I close this issue.
