### ISSUE TITLE
Substringof returns unknown function in get request

### ISSUE THREAD

**Issue by borisimple** [MicrosoftDocs/dynamics365smb-devitpro-pb#1128]
Cannot filter values using "substringof".

Here is the response I am getting.

`{
  "error": {
    "code": "",
    "message": "An unknown function with name 'substringof' was found. This may also be a function import or a key lookup on a navigation property, which is not allowed."
  }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc2d41b-a16e-2eb8-5acf-963df0a6020b
* Version Independent ID: 337d82f5-41e3-05d0-bde4-1ea6bd61b372
* Content: [Using Filter Expressions in OData URIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris#feedback)
* Content Source: [dev-itpro/webservices/use-filter-expressions-in-odata-uris.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/use-filter-expressions-in-odata-uris.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this should be supported if you're using the syntax provided in the topic, sounds like a product bug. Please open a bug using your usual support channel. Thanks.
