### ISSUE TITLE
How to display Limited Enum options on Page level 

### ISSUE THREAD

**Issue by PravinDangar** [MicrosoftDocs/dynamics365smb-devitpro-pb#1129]
Hello All,

I am struggling with an issue. Let me explain you here with Example.

Lets say , We have Enum "Colors" in Standard MS Code with Values "Red,Blue,White,Yellow" and I used Enum Data Type in field of Table.

Now I want to display only "Red,Blue" options(Enum Values) on page level to be selected by users.

Any solutions  ?

Thanks in Advanced.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the functionality that you are requesting is not yet implemented, but on our radar for a future release. Thanks.
