### ISSUE TITLE
The documentation is very inadequate. Since xml files can come from different sources, it should specify the different methods available for handling them.

### ISSUE THREAD

**Issue by davmac1** [MicrosoftDocs/dynamics365smb-devitpro-pb#113]
The documentation is very inadequate. Since xml files can come from different sources, it should specify the different methods available for handling them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21af53a0-b548-78b4-99d7-6ef4952f6139
* Version Independent ID: fb983c6d-3c44-f1f2-b42d-e10521082b0d
* Content: [DefaultNamespace Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/defaultnamespace-property)
* Content Source: [dynamics-nav/DefaultNamespace-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/DefaultNamespace-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We will take your input into consideration for our new docset for AL. Thanks.
