### ISSUE TITLE
Azure SQL support

### ISSUE THREAD

**Issue by NicolaiH** [MicrosoftDocs/dynamics365smb-devitpro-pb#1130]
It would be nice if cmdlets like Export-NAVApplication supported Azure SQL. Wouldn't it work if we were just able to pass on credentials?

Best regards
Nicolai Hansen
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00309f0b-524d-d3da-e9fd-8f21a71225b6
* Version Independent ID: 2e0f5b69-fca8-8c48-c676-73ff64456a74
* Content: [Merging an Application Database with a Tenant Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/merging-an-application-database-with-a-tenant-database)
* Content Source: [dev-itpro/deployment/Merging-an-Application-Database-with-a-Tenant-Database.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/Merging-an-Application-Database-with-a-Tenant-Database.md)
* Service: **dynamics365-business-central**
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you've reached the documentation repo for Business Central. Please use [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest new product features. Thanks.
