### ISSUE TITLE
Misleading description of GetBySystemId(Guid)

### ISSUE THREAD

**Issue by ph-jo** [MicrosoftDocs/dynamics365smb-devitpro-pb#1132]
"The GetBySystemId(Guid) gets the SystemId for a record" is typed, when the "GetBySystemIdMethod" uses the SystemId to get a record - this description has it the other way around

Edit:
This is related to https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-object#systemid 

I thought the issue would be linked automatically, my bad.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, will be fixed with the next doc refresh.
