### ISSUE TITLE
GetUrl links broken

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1134]
The links to the GetUrl function refer to https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-geturl-method. 
This link will be forwarded to https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/library.

From the content point of view, correct would be the link https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-geturl-clienttype-string-objecttype-integer-table-boolean-method 
However, please look at the URL itself, it's weird.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17b009cd-ffbd-c2e8-d4b0-f403bbcf2ca9
* Version Independent ID: 73747fa9-c325-7e66-6ef1-a3deebb31a87
* Content: [CurrentClientType Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/session/session-currentclienttype-method)
* Content Source: [dev-itpro/developer/methods-auto/session/session-currentclienttype-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/session/session-currentclienttype-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching that. The link will be fixed with the next refresh of the docs. I agree, the URL looks weird for the GetUrl method, but this is an auto-generated file name and probably doesn't make the bar for fixing, but thanks.
