### ISSUE TITLE
Language code incorrect

### ISSUE THREAD

**Issue by Vladislav-col** [MicrosoftDocs/dynamics365smb-devitpro-pb#1135]
Hi,
Please update Lithuanian language code to lt-LT.
Thank You

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 360d9409-840a-5ef9-9aa4-b43ed4733e2c
* Version Independent ID: 961502fa-6d30-47fa-8afe-a15a8e521304
* Content: [Country/region availability and supported languages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations#feedback)
* Content Source: [dev-itpro/compliance/apptest-countries-and-translations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-countries-and-translations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue will be fixed with the next doc refresh.
