### ISSUE TITLE
Where does InstructionalText work and is getting displayed?

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#1136]
As the Heading Applies-To implies, I would suspect that InstructionalText does work for RequestPage, but in my experience it did only work for groups on Requestpage. Not for the Requestpage itself. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 11a68b90-c1f3-9bf2-3421-53ed79cc2b56
* Version Independent ID: b2a98fb2-c7cc-706b-0ad9-65cd897d9ab9
* Content: [InstructionalText Property - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/dev-itpro/developer/properties/devenv-instructionaltext-property#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-instructionaltext-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-instructionaltext-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @ailie13
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi thanks for your feedback. The Applies To section is autogenerated from the source code, and we're not able to provide further details than the Request page, unfortunately. The tooling that we use would have to be changed to be more granular. We'll keep this in mind as an idea. Thanks.
