### ISSUE TITLE
Type casting

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#1137]
There is no info how is the type handled when type casting or how the type casting is done, e.g. how to get the value when I have the name in text. Are names and Ordinals in same order? Can I find index of the name and use it as index for the Ordinal?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, when opening a github issue the template includes the topic that you are referring to, but in this case your issue is missing that information. Can you please specify which topic you are referencing? Thanks.

**Comment by kine** [comment]
Have created the issue again, in correct way (from the page, not on the Github directly).
https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1138
