### ISSUE TITLE
Not Helpfull in the slightest

### ISSUE THREAD

**Issue by CKL-CAalstede** [MicrosoftDocs/dynamics365smb-devitpro-pb#1139]
completely worthless :).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d928206-e26d-a3ec-9093-4183f799f504
* Version Independent ID: 8530c33e-e017-ad4d-249f-74844436df5d
* Content: [ReportHandler Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-reporthandler-attribute#feedback)
* Content Source: [dev-itpro/developer/methods/devenv-reporthandler-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-reporthandler-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. Our reference documentation for this topic is a bit short. We are aware that we need more examples, this is on our backlog. Thanks.
