### ISSUE TITLE
URL No Longer Exists

### ISSUE THREAD

**Issue by momoto** [MicrosoftDocs/dynamics365smb-devitpro-pb#1142]
[The link][0] that is [this page][1] refers is no longer exists. I believe that it should refer the latest OData documentation.

[0]: https://go.microsoft.com/fwlink/?LinkId=214635
[1]: https://docs.microsoft.com/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc2d41b-a16e-2eb8-5acf-963df0a6020b
* Version Independent ID: 337d82f5-41e3-05d0-bde4-1ea6bd61b372
* Content: [Using Filter Expressions in OData URIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris#feedback)
* Content Source: [dev-itpro/webservices/use-filter-expressions-in-odata-uris.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/use-filter-expressions-in-odata-uris.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue will be fixed with the next doc refresh.
