### ISSUE TITLE
Replace "field" by "key"

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1144]
In the sentence "The last field in the primary field ..." "field" should be replaced by "key".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921b9103-2d89-fd4e-3521-058f9be64da7
* Version Independent ID: fc8dedb4-3227-9116-73e8-4cabe8fb8053
* Content: [AutoSplitKey Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-autosplitkey-property?source=docs#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-autosplitkey-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-autosplitkey-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue will be fixed with the next doc refresh.
