### ISSUE TITLE
Temporary TableType is not available

### ISSUE THREAD

**Issue by carlesi** [MicrosoftDocs/dynamics365smb-devitpro-pb#1146]
It seems TableType=Temporary is not available anymore. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ce6f5a-62dc-0bf3-621f-078ccba5f844
* Version Independent ID: 5ebef0bb-97c2-dd79-7ad0-03633c97494c
* Content: [TableType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-tabletype-property?source=docs)
* Content Source: [dev-itpro/developer/properties/devenv-tabletype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-tabletype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this. This is a feature that will come with a later version, than the released (16), so I will update the doc for now. Thanks.
