### ISSUE TITLE
Please make title show this topic's context is the query object

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1148]
Searching for topic on SetFilter method for Record variables I end up here as the title does not tell me the context (and thus the search result). The NAV topics used to have that. Please update is accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3915de08-668a-a7f6-a00e-504af37cf449
* Version Independent ID: fbfebf95-e0bb-28f6-8374-f7a4d556ba22
* Content: [SetFilter Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/query/queryinstance-setfilter-method)
* Content Source: [dev-itpro/developer/methods-auto/query/queryinstance-setfilter-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/query/queryinstance-setfilter-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Your suggestion requires a code change as these topics are auto-generated. We will consider this for a future release. Thanks.
