### ISSUE TITLE
Please make title show this topic's context is the query object

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1149]
Searching for topic on SetRange method for Record variables I end up here as the title does not tell me the context (and thus the search result). The NAV topics used to have that. Please update is accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5af00b3b-1f1a-714a-ed56-82eea2cb46a1
* Version Independent ID: 82b14314-8e52-b863-ccbd-a1f27932db05
* Content: [SetRange Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/query/queryinstance-setrange-method)
* Content Source: [dev-itpro/developer/methods-auto/query/queryinstance-setrange-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/query/queryinstance-setrange-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Your suggestion requires a code change as these topics are auto-generated. We will consider this for a future release. Thanks.
