### ISSUE TITLE
Missing information: How can I find my "ContainerName" ?

### ISSUE THREAD

**Issue by wolterOnEntocare** [MicrosoftDocs/dynamics365smb-devitpro-pb#115]
To install the test framework to my container the above page tells me to type in Powershell this command:
       Import-TestToolkitToNavContainer -containerName navserver

In this command typing "navserver" literally does not work for me.
So I assume this is a placeholder? If I am right: do something to make that more clear. Italicize it, put it in brackets, or whatever.
Next: explain how I can get to know the name of my container?
I just generated a Business Central tenant by following the easy "hello world" example on page 1. There was no explicit use of Docker involved and I did not explicitly work with "containers" I did not even know what they are. (I have read about it now... but still do not know how to get the name of my container though I am sure I have one).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7f2151-4fef-e6ab-bbc1-5b3e1b8c5b17
* Version Independent ID: 20ffa998-58d3-c843-87d5-3533e2fa7765
* Content: [Testing the Advanced Sample Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-advanced-example-test)
* Content Source: [dev-itpro/developer/devenv-extension-advanced-example-test.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-advanced-example-test.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by ailie13** [comment]
Thanks for your feedback. This is fixed in the next refresh of the docs. Thank you again!
