### ISSUE TITLE
Please make title show this topic's context is the fieldref/recref object

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1150]
Searching for topic on SetRange method for Record variables I end up here as the title does not tell me the context (and thus the search result). The NAV topics used to have that. Please update is accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f8def3b-d91a-4ef0-ac85-dab5c9602f90
* Version Independent ID: 93f9391b-b7ae-9502-0f30-4811a05cf031
* Content: [SetRange Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-setrange-method)
* Content Source: [dev-itpro/developer/methods-auto/fieldref/fieldref-setrange-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/fieldref/fieldref-setrange-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Your suggestion requires a code change as these topics are auto-generated. We will consider this for a future release. Thanks.
