### ISSUE TITLE
Available Cumulative Update List not up-to-date

### ISSUE THREAD

**Issue by dNsl9r** [MicrosoftDocs/dynamics365smb-devitpro-pb#1151]
On this page there is at least missing the CU18 for D365BC Version 13. Came here to see if 19 is already available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2556e86c-dcb8-ffe4-6f27-549dd1f35235
* Version Independent ID: cbe1a69f-2484-553c-082c-bbac0a421f55
* Content: [Cumulative updates - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/update-versions-13#feedback)
* Content Source: [dev-itpro/deployment/update-versions-13.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/update-versions-13.md)
* Service: **dynamics365-business-central**
* GitHub Login: @MartinNielander
* Microsoft Alias: **martinni**

**Comment by jswymer** [comment]
Hello,

We've changed the article to include  CU 18 for April. The updated article will be published soon. 

For CU 19, please refer to [Software Lifecycle Policy and Dynamics 365 Business Central On-Premises Updates](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/terms/lifecycle-policy-on-premises#fixed-lifecycle-policy). 

I hope this answers your question. Thanks for the feedback!
