### ISSUE TITLE
Nav2018 Upgrading to Dynamics 365 Business Central

### ISSUE THREAD

**Issue by eat110** [MicrosoftDocs/dynamics365smb-devitpro-pb#1153]
Open Nav2018 DataBase with BC Development Environment.
The following error occurs.
![image](https://user-images.githubusercontent.com/28883324/81139507-8f49c980-8f98-11ea-8678-bfff9b4f668f.png)

and I use Sql server profiler find the SQL statement.
-- Drop existing 'Object Tracking' triggers
IF EXISTS (SELECT * FROM sysobjects WHERE name = N'$ndo$objecttracking' AND type = N'TR') DROP TRIGGER [dbo].[$ndo$objecttracking]
IF EXISTS (SELECT * FROM sysobjects WHERE name = N'$ndo$objecttracking$bp' AND type = N'TR') DROP TRIGGER [dbo].[$ndo$objecttracking$bp]
IF EXISTS (SELECT * FROM sysobjects WHERE name = N'$ndo$objecttracking$ca' AND type = N'TR') DROP TRIGGER [dbo].[$ndo$objecttracking$ca]
IF EXISTS (SELECT * FROM sysobjects WHERE name = N'$ndo$objecttracking$naom' AND type = N'TR') DROP TRIGGER [dbo].[$ndo$objecttracking$naom]
IF EXISTS (SELECT * FROM sysobjects WHERE name = N'$ndo$objecttracking$nata' AND type = N'TR') DROP TRIGGER [dbo].[$ndo$objecttracking$nata]
-- Enable change tracking on individual tables
IF NOT EXISTS (SELECT * FROM sys.change_tracking_tables WHERE object_id=Object_ID('[dbo].[Object Metadata]')) ALTER TABLE [dbo].[Object Metadata]�ENABLE CHANGE_TRACKING�WITH (TRACK_COLUMNS_UPDATED = ON)
IF NOT EXISTS (SELECT * FROM sys.change_tracking_tables WHERE object_id=Object_ID('[dbo].[Debugger Breakpoint]')) ALTER TABLE [dbo].[Debugger Breakpoint]�ENABLE CHANGE_TRACKING�WITH (TRACK_COLUMNS_UPDATED = ON)
IF NOT EXISTS (SELECT * FROM sys.change_tracking_tables WHERE object_id=Object_ID('[dbo].[Add-in]')) ALTER TABLE [dbo].[Add-in]�ENABLE CHANGE_TRACKING�WITH (TRACK_COLUMNS_UPDATED = ON)
IF NOT EXISTS (SELECT * FROM sys.change_tracking_tables WHERE object_id=Object_ID('[dbo].[NAV App Object Metadata]')) ALTER TABLE [dbo].[NAV App Object Metadata]�ENABLE CHANGE_TRACKING�WITH (TRACK_COLUMNS_UPDATED = ON)
IF NOT EXISTS (SELECT * FROM sys.change_tracking_tables WHERE object_id=Object_ID('[dbo].[NAV App Tenant App]')) ALTER TABLE [dbo].[NAV App Tenant App]�ENABLE CHANGE_TRACKING�WITH (TRACK_COLUMNS_UPDATED = ON)
IF NOT EXISTS (SELECT * FROM sys.change_tracking_tables WHERE object_id=Object_ID('[dbo].[NAV App]')) ALTER TABLE [dbo].[NAV App]�ENABLE CHANGE_TRACKING�WITH (TRACK_COLUMNS_UPDATED = ON)
IF NOT EXISTS (SELECT * FROM sys.change_tracking_tables WHERE object_id=Object_ID('[dbo].[NAV App Publish Reference]')) ALTER TABLE [dbo].[NAV App Publish Reference]�ENABLE CHANGE_TRACKING�WITH(TRACK_COLUMNS_UPDATED = ON)
there are have many �.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.

**Comment by jeridang** [comment]
> Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.

First I am sorry for this late message. But Can I know how you solve this case? I got the same error when I opened the 2015 Database with h NAV Dev client while upgrading from 2015 to BC130. Please help me.
