### ISSUE TITLE
Please give an example of how to programmatically define what each value does

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1154]
As written: "... the values themselves do not perform any operations or have any specific behavior. Instead, you programmatically define what each value does, and the permissions sets it applies at runtime, by adding code in a test runner codeunit."

And how do you do that? Please provide a couple of examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9a88b1-f7e9-e4cb-6b06-4d9e11ef4e35
* Version Independent ID: c9b7c384-2643-75e6-c9cd-308d3b77042f
* Content: [TestPermissions Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-testpermissions-property)
* Content Source: [dev-itpro/developer/properties/devenv-testpermissions-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-testpermissions-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by lvanvugt** [comment]
A long time and nothing done here. @SusanneWindfeldPedersen could you please give an update?

**Comment by SusanneWindfeldPedersen** [comment]
The values for the Testpermission property have been updated  with the latest doc refresh and hopefully make more sense now. Closing this issue. Thanks.

**Comment by lvanvugt** [comment]
@SusanneWindfeldPedersen, this issue has not been tackled so far, although you say it was. I do not seen any (ä couple as I requested) examples. 
Does removing the text I mention above, i.e.  "... the values themselves do not perform any operations or have any specific behavior. Instead, you programmatically define what each value does, and the permissions sets it applies at runtime, by adding code in a test runner codeunit.", solve it?

WIth the OnBeforeTestRun and OnAfterTestRun you would be able to programmatically stear it. Shouldn't that be mentioned here?
