### ISSUE TITLE
There is no -SymbolsOnly switch for Unpublish-NAVApp

### ISSUE THREAD

**Issue by STibro** [MicrosoftDocs/dynamics365smb-devitpro-pb#1156]
Pleas fix this to something like this: To unpublish symbols, use the Unpublish-NAVAPP cmdlet with the name of the results of the following command Get-NAVAppInfo -SymbolsOnly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1d264c-efcd-b879-76d8-84966207ff17
* Version Independent ID: 5e5d562b-caad-3e0e-6cb8-064fd323519d
* Content: [Technical Upgrade - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15#feedback)
* Content Source: [dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
The article has been fixed. An update will be published soon. Thanks!
