### ISSUE TITLE
RunPageLink property on role center pages

### ISSUE THREAD

**Issue by RobKirsten** [MicrosoftDocs/dynamics365smb-devitpro-pb#1158]
According to the help page, it should be possible to filter the page via RunPageLink = FIELD = filter(VALUE). In this case, it's not. However, if I switch to RunPageView, BC shows the correct values in the page. Is there an undocumented restriction regarding role center pages? 

Version: Platform 14.0.40464.0 + Application 40471 (DE Business Central 14.10)
Azure AD tenant: common, Environment: Production

`
page 50000 MyPage
{
    PageType = RoleCenter;

    layout
    {
        area(RoleCenter)
        {
        }
    }
    actions
    {
        area(Sections)
        {
            group(MyGroup)
            {
                action("Customer Ledger Entries - Open")
                {
                    Caption = 'Customer Ledger Entries';
                    ApplicationArea = All;
                    RunObject = Page "Customer Ledger Entries";
                    // RunPageView = where(Open = filter(true)); 
                    RunPageLink = Open = filter(true);
                }
            }
        }
    }
}
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d90498e-72df-207a-5344-db408659666d
* Version Independent ID: fde80388-7526-f049-8b62-c5dcc2d1e9e8
* Content: [RunPageLink Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-runpagelink-property)
* Content Source: [dev-itpro/developer/properties/devenv-runpagelink-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-runpagelink-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question, yes I can confirm there is a difference, but will have to check if this is intentional. I will get back to you once I have an update. Thanks for your patience.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I have no update on this issue. However, we have updated the RunPageLink property with good information about also setting the RunPageView property for performance reasons, this recommendation in itself will fix the issue above. Thanks.

**Comment by hd1370** [comment]
I am encountering an issue where links are simply hidden when using RunPageView or RunPageLink in a rolecenter action.
This is with version 16. Any news on this?
