### ISSUE TITLE
--tableDataOnly not available

### ISSUE THREAD

**Issue by dNsl9r** [MicrosoftDocs/dynamics365smb-devitpro-pb#1159]
For which version of txt2al is the parameter '--tableDataOnly' available?
Checked for BC14 GA as well as BC14 CU9 - none got the parameter.
Please write more clear on this page in which version which parameter is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfebcfad-5d9d-5365-5ae0-524780e74355
* Version Independent ID: 0a3a2ef5-ceeb-7b4d-572f-6a80a4c90c46
* Content: [The Txt2Al Conversion Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool)
* Content Source: [dev-itpro/developer/devenv-txt2al-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-txt2al-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, in general, the documentation available supports the current version, in some cases we have notes that give guidance otherwise, but we do not publish versioned doc sets. This parameter was introduced with the latest release Business Central 2020 release wave 1. Thanks.

**Comment by dNsl9r** [comment]
In this case, the documentation is wrong.
In Step 7 it is written that we should navigate to the folder of _\Program Files(x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client_
For BC140 the parameter is not available if I understand correct.

**Comment by averied** [comment]
Where do we get this new txt2al version? Wave 1 doest not have include this too

**Comment by clembo67** [comment]
Is there any news? can't figure out where to download the updated tool with available tabledataonly parameter

**Comment by averied** [comment]
@clembo67 it's in the latest cumulative update of version 140. 

https://support.microsoft.com/en-us/help/4564070/cumulative-update-13-for-microsoft-dynamics-365-business-central-april

txt2al is not included in 160
