### ISSUE TITLE
Assumes too much; leaves too much out

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#116]
"The data type of the C/AL expression" -- what C/AL expression? The documentation nowhere mentions that the CaptionClass PROPERTY is an expression, can be an expression, must be an expression, can be something other than an expression (e.g., a string literal), nothing. Presumably we are supposed to know that already--all it does is make some notes about expressions when they are used. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd443e1-bfcf-d206-8fdb-a6321ed591f1
* Version Independent ID: df67f6f3-623c-a62c-85f1-811df487fecb
* Content: [CaptionClass Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/captionclass-property)
* Content Source: [dynamics-nav/CaptionClass-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/CaptionClass-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Please use our [AL documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-dev-overview), which we will be working on refining and updating in the next period of time.
