### ISSUE TITLE
Inconsistent behavior between RTC and Web Client

### ISSUE THREAD

**Issue by Peter-Conijn** [MicrosoftDocs/dynamics365smb-devitpro-pb#1161]
The creation of submenus in AL role centers does not work in the RTC client; submenus are being wholly ignored and the items show in a straight list. While it is true that the RTC is being/has been phased out, I would expect this to at least be noted on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d29386a-cd69-bd44-b2be-8a63fa826690
* Version Independent ID: 5fafae47-9391-1203-b9db-592bd5c10617
* Content: [Adding Menus to the Navigation Area - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-menus-to-navigation-pane#feedback)
* Content Source: [dev-itpro/developer/devenv-adding-menus-to-navigation-pane.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-menus-to-navigation-pane.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We have clarified this in the article. The updated article will be published soon.
