### ISSUE TITLE
Download the installation media (DVD)

### ISSUE THREAD

**Issue by momoto** [MicrosoftDocs/dynamics365smb-devitpro-pb#1164]
It would be great if it was possible to find some guidance for where you download the installation media. For each release, [October '18 release][v13], [April '19 release][v14], [2019 release wave 2][v15] and latest one, [2020 release wave 2][v16].

[v13]: https://docs.microsoft.com/dynamics365/business-central/dev-itpro/deployment/update-versions-13
[v14]: https://docs.microsoft.com/dynamics365/business-central/dev-itpro/deployment/update-versions-14
[v15]: https://docs.microsoft.com/dynamics365/business-central/dev-itpro/deployment/update-versions-15
[v16]: https://docs.microsoft.com/dynamics365/business-central/dev-itpro/deployment/update-versions-16

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f446fc6-3475-7b86-3ba3-a0bdaebf80e8
* Version Independent ID: 722a12dd-e281-ee5b-96ec-581d94166274
* Content: [Install Business Central Using Setup - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/install-using-setup#feedback)
* Content Source: [dev-itpro/deployment/install-using-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/install-using-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
The article has been updated to include the requested information, and the update will be published soon. Thanks for the feedback!
