### ISSUE TITLE
AS0045 seems to be missing from this list/page?

### ISSUE THREAD

**Issue by hougaard** [MicrosoftDocs/dynamics365smb-devitpro-pb#1165]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0045-permissionsmustbeassigned

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03cc1f40-cea7-5449-10a6-9736f9713c53
* Version Independent ID: afcd6e13-c135-08ba-f973-cab671fb579c
* Content: [AppSourceCop Analyzer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, this is a bug in the auto-generation of the overview page. I've filed a bug and once it is fixed, we'll be able to publish the updated page.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, an update to this issue is that rule as0045 has been retired together with rule as0046 - we will retire both topics with the next doc refresh. Thanks.
