### ISSUE TITLE
Recorded events not being generated

### ISSUE THREAD

**Issue by dewal1004** [MicrosoftDocs/dynamics365smb-devitpro-pb#1167]
I recorded a warehouse receipt posting event. However, nothing is being generated on the event recorder.  What could be wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84982d4a-4491-6ba8-d6ac-423f6c46dbfb
* Version Independent ID: 991c9df9-6f0e-81d7-e986-39c0f9b6fb4e
* Content: [Events Discoverability - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-events-discoverability#feedback)
* Content Source: [dev-itpro/developer/devenv-events-discoverability.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-events-discoverability.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. An important thing when using the event recorder is that it needs to run in the same session as what you're trying to record.  The event record page has to remain open while events are being recorded. The event record page uses a temporary table, so if the user leaves the event recorder page and goes back to it, all events recorded will be lost. You can use the Open this page in a new window feature for the event recorder page, press Start and then perform the actions in the UI, return to the event recorder page, and press Stop. That should work. We'll update the docs to be more clear on this with the next doc refresh. Thanks.

**Comment by dewal1004** [comment]
The steps that were used were similar to the one recommended above.  Notwithstanding the above steps were also tested without getting the expected result. Can you possibly record a video shut of how you were able to get the result from the Event Recorder?
