### ISSUE TITLE
Why do the hyperlinks behind not bring me directly to the related topic?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1168]
Above these three methods are mentioned and do have a hyeplink behind:
    EXECUTE Method
    PRINT Method
    SAVEAS Method

But the all have the same hyperlink (i.e. https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/library) that does not bring me to the related topics, being:
    EXECUTE Method: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-execute-method
    PRINT Method: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-print-method
    SAVEAS Method: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-saveas-method

Can you please update this links?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feedc94d-9103-2eed-c25f-d37a4d6ed59e
* Version Independent ID: 37a5139b-1be5-a72e-47d3-ef201c59088d
* Content: [RunRequestPage Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-runrequestpage-method)
* Content Source: [dev-itpro/developer/methods-auto/report/report-runrequestpage-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/report/report-runrequestpage-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This is due to redirection that kicked in, when we started auto-generating the methods docs. But these links are missing an update, and will be fixed with the next doc refresh. Thanks.
