### ISSUE TITLE
Sample has incorrect XML

### ISSUE THREAD

**Issue by dagirard** [MicrosoftDocs/dynamics365smb-devitpro-pb#1169]
Hello!

&lt;?xml version="1.0" encoding="utf-8"?&gt;
is missing (instead it's ding)

And the target language has invalid quotes (target-language=”da-DK”).

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#feedback)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and the update will be published soon.
