### ISSUE TITLE
Insufficient explanation

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#117]
"When you set the CaptionClass Property on a field or control, users can configure the caption of a text box that is connected to a label or the caption of a check box without having to modify code". Really? So if I set the CaptionClass property to String (without quotes), the user can suddenly configure the caption of a text box? How might they do that? Would it not be useful to place links to actual related information like the GetCaptionClass function under the "See Also" heading? Isn't that the point of "See Also"?
This is an example of an explanation that is not complete or even technically correct (see above). Surely we can do better than this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d24c5b2-cd1e-63d0-6973-2ec29f60e6d6
* Version Independent ID: ecf4ab2c-822b-86c7-2dfe-80519868f0ca
* Content: [CaptionClass Functionality - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/captionclass-functionality)
* Content Source: [dynamics-nav/CaptionClass-Functionality.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/CaptionClass-Functionality.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
We're sorry that you do not feel the content is complete. We're working hard on improving all reference documentation. For any future guidance please find the [Business Central Developer Docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/?branch=master) updated with the newest additions to AL. Thanks.

**Comment by buzzwick** [comment]
Susanne,
I can't tell you how gratifying it is to actually get a response from someone who appears to be actually working on improving documentation. I sometimes get frustrated and exasperated and vent, but if I know someone is there, listening, trying to make a difference, I can focus on being helpful instead.  I think my most valuable contribution may be as a "dumb user" who can provide feedback on the actual experience of using the documentation. Thanks again for  your attention.
