### ISSUE TITLE
Why does this topic exist?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1171]
... as we do have https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-testpermissions-property?
What is the added value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b54119e-b41f-f3c8-0548-f484773fadf1
* Version Independent ID: 3cf5b53e-c73c-a783-2277-649a26d12f58
* Content: [TestPermissions Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-testpermissions-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-testpermissions-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-testpermissions-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, there are two articles because the TestPermissions property applies only to test codeunits, whereas the TestPermissions  attribute is used for test methods. The functionality is the same but they differ in the syntax. The documentation will be updated to make this more clear. Thanks.

**Comment by lvanvugt** [comment]
OK, thanx for the explanation and with the update it makes sense.
