### ISSUE TITLE
JSON should be as string

### ISSUE THREAD

**Issue by sasha-kuzmin** [MicrosoftDocs/dynamics365smb-devitpro-pb#1172]
It works actually if JSON object is passed as a string e.g. quotation marks are escaped with backshlash
{
    "inputJson": "{
        \\"str\\": \\"Hello world!\\",
        \\"confirm\\": true
    }"
}
and JsonObject type cannot be used as a parameter in the method. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc701118-4d83-4d5a-efcc-420fb870300f
* Version Independent ID: 10a28599-afa8-a4e9-0d9a-b80749421de2
* Content: [Creating and Interacting with an OData V4 Unbound Action - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-unbound-action#feedback)
* Content Source: [dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-unbound-action.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-unbound-action.md)
* Service: **dynamics365-business-central**
* GitHub Login: @ap3rus
* Microsoft Alias: **vlnagorn**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue is fixed and the topic has been refreshed.
