### ISSUE TITLE
Section on "Totals Methods and Groups" still mentions old Query Designer

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#1174]
Judging from its url, this page is for Business Central?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6ef5d2-fc11-3941-8ca6-75f777903483
* Version Independent ID: b13c6ede-2462-6655-ecb8-60508fa29a84
* Content: [Method Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-method-property)
* Content Source: [dev-itpro/developer/properties/devenv-method-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-method-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! You're correct. The article included references to Query Designer in CSIDE. The article has been fixed and an update will be published soon.
