### ISSUE TITLE
"Post Upgrade - Change application version" leaves tenant in state OperationalDataUpgradePending and I cannot install new apps

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1175]
If I want to install new app after running optional Post Upgrade section, then I get error:

Install-NAVApp : Cannot install apps due to the state of the tenant: OperationalDataUpgradePending.
At line:8 char:5
+     Install-NAVApp -Name $AppInfo.Name -ServerInstance $servInst
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC160/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.InstallNavApp

Please add instructions how to avoid or resolve this issue.

Maybe instead of this:
Start-NAVDataUpgrade -ServerInstance &lt;server instance name&gt; -Tenant &lt;tenant ID&gt; 
we should run that:
Start-NavDataUpgrade-ServerInstance &lt;server instance name&gt; -Tenant &lt;tenant ID&gt; -FunctionExecutionMode Serial
At least that resolved this issue for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 282df301-79a2-3747-9718-f09f0b0d73ae
* Version Independent ID: b9d4f12b-05e3-fa0c-5d74-4c7372d520f7
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v16)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v16.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v16.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, you're correct. The Start-NAVDataUpgrade should be run with -FunctionExecutionMode Serial. The article has been fixed and an update will be published soon. Thanks for the feedback!

**Comment by IMRGroup** [comment]
Hello,

i ran the DataUpgrade with -FunctionExecutionMode Serial.
Get-NavDataUpgrade shows: Completed, 100%.

"Install-NAVApp -Name <Name> -ServerInstance <instance>" still brings up "Cannot install apps due to the state of the tenant: OperationalDataUpgradeInProgress."

How can i bring this to a completed state?

**Comment by erolkunman** [comment]
Hi @IMRGroup,
You have to be patient after Start-NAVDataUpgrade.

You can run:
Get-NAVTenant -ServerInstance $servInst -Tenant default -ForceRefresh

And if State = OperationalDataUpgradeInProgress, then **WAIT until it becomes Operational**

To fix Your case run again:
Start-NavDataUpgrade -ServerInstance $servInst -Tenant default -FunctionExecutionMode Serial

**Comment by jswymer** [comment]
Hi,

At what point did you run "Start-NavDataUpgrade -FunctionExecutionMode Serial"? Just curious because it doesn't appear as a step in the article. For example, was it used in connection with changing the application version or for something else? This information might help identify possible improvements to the doc. Thanks!

**Comment by IMRGroup** [comment]
@erolkunman - thanks, i guess being patient is the only way. Even thoug State was "Operational", i had to wait another 5min.

@jswymer For me its step 10 in this article: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17 
The complete command is "Start-NavDataUpgrade -ServerInstance $servInst -Tenant default -FunctionExecutionMode Serial" like @erolkunman stated...

**Comment by jswymer** [comment]
Hi, thanks for the info.

We've add information to the article, and the relevant articles for other versions. The update will be published soon. Thanks for the feedback.

**Comment by Ksoucek** [comment]
Hi, i got into this state during customer upgrade, now its stuck in this state for like 48 hours.. any ideas?

**Comment by erolkunman** [comment]
> Hi, i got into this state during customer upgrade, now its stuck in this state for like 48 hours.. any ideas?

If status from command:
#Get-NAVTenant -ServerInstance $servInst -tenant default -ForceRefresh

is Tenant OperationalDataUpgradePending or OperationalSyncPending
then I would run this powershell:
#Start-NavDataUpgrade -ServerInstance $servInst -Tenant default -FunctionExecutionMode Serial

**Comment by Ksoucek** [comment]
> You have to be patient after Start-NAVDataUpgrade.
> 
> You can run: Get-NAVTenant -ServerInstance $servInst -Tenant default -ForceRefresh
> 
> And if State = OperationalDataUpgradeInProgress, then **WAIT until it becomes Operational**
> 
> To fix Your case run again: Start-NavDataUpgrade -ServerInstance $servInst -Tenant default -FunctionExecutionMode Serial

Yeah, this worked, i have missed this soultion in replies. Thnak you anyway :)
