### ISSUE TITLE
Lot of improvements and optimizations needed

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1177]
Task 1 point 3. "If you don't uninstall version 15...or you must stop the version 15.0"
Sorry but we cannot uninstall BC version 15 nor stop server instance BC150, because then it will be impossible to execute Task 2 (for uninstalling apps from BC150 we need an existing and running server instance BC150).  

Task 6 point 6. "If you have new versions ... then publish the new versions. Otherwise, republish the same versions..."
I have 20+ third party apps installed and I have no idea where are .app files for these extensions.
If I don't have new versions of 3-rd party apps for version 16, why cant we just Repair like we do in cumulative update:
Get-NAVAppInfo -ServerInstance &lt;server instance&gt; | Where-Object {$_.Publisher -notlike '*Microsoft*'} | Repair-NAVApp  

Tasks 6 and 7 and 8 seem not optimized for me.
To me it seems we should do Technical upgrade first and then upgrade the System and Base app plus all Microsoft extensions and after that only new versions from 3-rd party apps.
Or how can we optimize tasks 6,7,8?

Post Upgrade tasks are missing "Upgrade Javascript-based control add-ins to new versions".
In technical upgrade instructions we have to update Javascript-based control add-ins so are they somehow automatically updated here or is this information just missing?
Also should we upgrade Javascript-based control add-ins with every cumulative upgrade?

---
#### Dokumendi üksikasjad

⚠ *Ärge seda jaotist redigeerige. See on vajalik docs.microsoft.com-i ➟ GitHubi probleemide linkimiseks.*

* ID: 6a99ad4b-431a-d2d6-b11f-bb467e490387
* Version Independent ID: a310818b-2861-9a15-c01d-27ea599bb22b
* Content: [Upgrading Version 15 Base Application to Version 16 - Business Central](https://docs.microsoft.com/et-ee/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16#feedback)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the valuable feedback. We have addressed the issues and updated the content. 

- The installation has been reworded.
- Repairing extensions step was missing and has been added.
- The development team confirmed that control add-ins must be upgraded to the latest platform. A new task has been added.

As for the optimizing Tasks 6 and 7 and 8, we chose to follow the pattern Publish all extensions to the server, then sync the extensions with tenant, then finally upgrade data. As you say, you could choose to publish, sync and upgrade system and base app first. Followed by Microsoft extensions, then 3rd party. If I misunderstood the question, let me know. 

Thanks!

**Comment by jswymer** [comment]
I hope this answered your questions. If not, please let us know and we will reopen the issue. Thanks for the feedback.
