### ISSUE TITLE
Information about case with multiple server instances needed

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1178]
I we have 2 or more BC server instances (for example default instance is BC150 but we have also BC150NUP (for Nav User Password authentication) and BC150AAD (for Azure Active Directory authentication), then how can we recreate these BC server instances during upgrade for BC16?
There are lot of configurations done for BC150AAD instance and we really don't want to lose that information (Azure connected app registration information etc).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a99ad4b-431a-d2d6-b11f-bb467e490387
* Version Independent ID: a310818b-2861-9a15-c01d-27ea599bb22b
* Content: [Upgrading Version 15 Base Application to Version 16 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. I think I understand the issue. The configurations can be complex especially with AAD setups.

Each instance has a CustomSettings.config file, for example, located in the C:\Program Files\Microsoft Dynamics 365 Business Central\150\Service\Instances folder. You can, to some degree, reuse these files on the new BC160 instances. Most of the changes in the CustomSettings.config file from one release to the next are additive, that is, new parameters have been included. You could compare and merge the BC150 CustomSettings.config files with a BC160 CustomSettings.config file. Then copy updated BC150 file to the new BC160 instance.

**Comment by jswymer** [comment]
Hello, I hope this answered your question. Otherwise, let us know and I will reopen the issue. Thanks!
