### ISSUE TITLE
Only for extensions which run on-premises

### ISSUE THREAD

**Issue by Kowa63** [MicrosoftDocs/dynamics365smb-devitpro-pb#118]
A note about the difference between on-prem and cloud development and the target parameter in app.json is missing.
File methods like Open, Close, Write etc. can only be used in AL if the compiler target in the app.json is set to "Internal" (= on-prem extensions) or the .vsix AL extensions from a NAV installation is used in VS Code, but not for cloud apps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d2b115-243f-bfe6-08fd-bbe7f98d2b33
* Version Independent ID: 5138a775-2c81-f2b9-1157-a518015e0575
* Content: [File Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/datatypes/devenv-file-data-type)
* Content Source: [dev-itpro/developer/datatypes/devenv-file-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/datatypes/devenv-file-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by skundaram** [comment]
Thanks for the feedback, we are in the process of developing new reference docs. We will have the docs published with one of our next refreshes. Thanks.
