### ISSUE TITLE
List Versions Typo

### ISSUE THREAD

**Issue by jiraffex** [MicrosoftDocs/dynamics365smb-devitpro-pb#1180]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/appmanagement/app-management-api#version

There is a typo in the List Versions command, with some things duplicated in the URL.
"GET https://apps.businesscentral.dynamics.com/v1.0/apps/41a68924-7fcf-4fd0-9200-f10f36a2e213/v1.0/apps/{appId}/countries/{countryCode}/versions?$filter=&lt;odata_filter&gt;"
Should be "GET https://apps.businesscentral.dynamics.com/v1.0/apps/{appId}/countries/{countryCode}/versions?$filter=&lt;odata_filter&gt;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6571d7-f265-d01b-0d0d-20e43405d84d
* Version Independent ID: 2e330825-6ff4-cb1c-f124-5df7fcc24071
* Content: [App Management API - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/appmanagement/app-management-api#feedback)
* Content Source: [dev-itpro/administration/appmanagement/app-management-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/appmanagement/app-management-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
