### ISSUE TITLE
Please mention progress bar

### ISSUE THREAD

**Issue by TheDenSter** [MicrosoftDocs/dynamics365smb-devitpro-pb#1181]
This Doc starts with mentioning that it works with # and @ fields. What is missing is that in the webclient, progress bars are NOT supported (@ doesn't work). This is mentioned in a note on the Open method's Doc (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-open-method) but I think it should be mentioned explicitly here as well.

I was trying to program a progress bar and obviously it didnt work, and I did not read the Doc about the Open method until someone pointed out to me that it was in there. I think this Doc could be better if you specifically mention that progress bars are not supported in the webclient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98ecdabb-ee53-0c80-c5b8-0d5244c52f89
* Version Independent ID: 91d49318-4682-3e7d-e680-f3da40d6fe75
* Content: [Update Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-update-method)
* Content Source: [dev-itpro/developer/methods-auto/dialog/dialog-update-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/dialog/dialog-update-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. It's a good point, this will be added to the topic with the next doc refresh.
