### ISSUE TITLE
PromotedCategory Translate issue in BC16

### ISSUE THREAD

**Issue by JulianCamiloLG** [MicrosoftDocs/dynamics365smb-devitpro-pb#1182]
Hi, I´m extending Sales Quote Card in BC16 because i need to add some actions in a new category, this case category12
The caption for the english works fine, but for spanish doesn´t. (spanish mexico)
Here some screenshoots
![errorcodigo](https://user-images.githubusercontent.com/22564585/82709428-32137080-9c46-11ea-91e2-51974b76f553.png)
![actioncode](https://user-images.githubusercontent.com/22564585/82709452-3d669c00-9c46-11ea-9d3d-92e748e28447.jpg)
![error detalle](https://user-images.githubusercontent.com/22564585/82709466-45264080-9c46-11ea-9092-35ad5aa544ff.png)
I tried with both ML and without but nothing

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
