### ISSUE TITLE
Can I use the .xlf approach in translating the base application (wave 2) to Greeke language?

### ISSUE THREAD

**Issue by tbebekis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1183]
The "Translation and Localization apps" section says in a Note that "The following section only applies to versions released before Business Central 2019 release wave 2."

And right after that says "The .xlf files approach cannot be used for translating the base application".

Is it safe to conclude that I can use the .xlf approach in translating the base application (wave 2) to Greeke language?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, yes - you can use the XLIFF approach for translating the base application for versions from Business Central 2019 release wave 2 and after.
