### ISSUE TITLE
Change Enum Caption

### ISSUE THREAD

**Issue by dominicstarkl** [MicrosoftDocs/dynamics365smb-devitpro-pb#1186]
Is it possible to change an Enum Caption in EnumExtension?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd55bfe-2599-257c-fe83-6c5c7d90b04b
* Version Independent ID: 60ac2b4a-d10a-5e8c-d2e7-ac380943cd0b
* Content: [Extensible Enums - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)
* Content Source: [dev-itpro/developer/devenv-extensible-enums.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extensible-enums.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, it is not possible to change the caption of an enum using an enumextension. You should be able to change such a caption using translation, for more information please see [Working with Translation Files](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translating-other-extensions). Thanks.

**Comment by dominicstarkl** [comment]
Hi Susanne
Thanks for your reply.
I will try this out.
Regards
Dominic

**Comment by dominicstarkl** [comment]
@SusanneWindfeldPedersen 
Hi Susanne

I just tried to place the modified Base Application XLIFF File into the Translation Folder of my Extension Project.
It doesn't seem to work.
The AL compiler says that there cannot be more than one XLIFF with the same target language (de-CH).
When I try to place the modified Base Application XLIFF File into a different Extension, as the MSFT Localization Apps do (e.g. "German language (Switzerland)"), it doesn't work either.

I also tried to adapt the original Localization App for de-CH with my desired translation change and could publish it with success. But the changed translation didn't appear too.

Could you please help me solving this problem?

Many thanks in advance.

Regards
Dominic

**Comment by thpeder** [comment]
Hi @dominicstarkl,

Enum value translations from other apps was first introduced in 16.2 so first of all make sure you are on that version.
if that is the case and you are still having issues with translating enum values then please write up the issue over at https://github.com/Microsoft/AL

The compiler only allows having one file per language with translations in, so make sure you don't have multiple xliff files where the target-language are the same.

I hope this clarifies your issues.

Best regards,
Thomas

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue for now. Thanks.

**Comment by dominicstarkl** [comment]
@thpeder @SusanneWindfeldPedersen 
Many thank you both for your appreciated help!
We will consider an update to the latest BC16 release and then check this issue again.
Regards
Dominic

**Comment by dominicstarkl** [comment]
@SusanneWindfeldPedersen @thpeder 
Works like a charm in BC16.4

**Comment by thpeder** [comment]
That is great to hear!
