### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#1187]
When a page **page** can contain a lot of contents,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f987e0c-ba34-f91e-dffc-a156ced6c02d
* Version Independent ID: abb31fda-847c-4204-ad1f-0767a4b69e9a
* Content: [Page Types and Layouts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-types-and-layouts)
* Content Source: [dev-itpro/developer/devenv-page-types-and-layouts.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-types-and-layouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jacobwj
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, it will be fixed with the next doc refresh.
