### ISSUE TITLE
Page Trigger Events text and link change

### ISSUE THREAD

**Issue by ianscho** [MicrosoftDocs/dynamics365smb-devitpro-pb#119]
In the Page Trigger Events section please update the following text from:
- _OnAfterGetRecordEvent(VAR Rec : Record)_ | Executed after the [OnAfterGetCurrRecord Trigger](https://docs.microsoft.com/en-us/dynamics-nav/onaftergetcurrrecord-trigger), which is called after the record is retrieved from the table but before it is displayed to the user.

To:
- _OnAfterGetRecordEvent(VAR Rec : Record)_ | Executed after the [OnAfterGetRecord Trigger](https://docs.microsoft.com/en-us/dynamics-nav/onaftergetrecord-trigger), which is called after the record is retrieved from the table but before it is displayed to the user.

  The text change is from 'OnAfterGetCurrRecord' to 'OnAfterGetRecord'.
  Where the [OnAfterGetRecord Trigger](https://docs.microsoft.com/en-us/dynamics-nav/onaftergetrecord-trigger) link points to the following https://docs.microsoft.com/en-us/dynamics-nav/onaftergetrecord-trigger

Just call me anal...
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a45024bd-ecad-d770-b519-4206e1b5b070
* Version Independent ID: da0cde4e-349b-cf0f-8b3d-cf5f3f0fde3f
* Content: [Event Types - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/event-types)
* Content Source: [dynamics-nav/Event-Types.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Event-Types.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback. The error has been fixed and an update will be published soon.
