### ISSUE TITLE
AL Simple Statements - With Statements

### ISSUE THREAD

**Issue by aptMattKoe** [MicrosoftDocs/dynamics365smb-devitpro-pb#1190]
In the current Release the code analyzer will say, that "with" will be an error.
This should get an hint in this area:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-simple-statements#with-statements
Or it could be deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff8af30e-3d81-30c3-44c8-fc4cb631d001
* Version Independent ID: 315c1531-77aa-c602-6c0b-41d160d791e2
* Content: [AL Simple Statements - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-simple-statements)
* Content Source: [dev-itpro/developer/devenv-al-simple-statements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-simple-statements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, in the current release of Business Central with statements are allowed. You might have a preview of the AL Language extension, available to only a specific audience. The deprecation is not introduced until the next major release, in October. The docs reflect the current release. When something is deprecated there is a warning period before something becomes an error to allow time to fix these issues.

**Comment by aptMattKoe** [comment]
Sure, but could a hint not be usefull? For beginners?
