### ISSUE TITLE
Where are the examples?

### ISSUE THREAD

**Issue by MiePlougstrup** [MicrosoftDocs/dynamics365smb-devitpro-pb#1191]
You write (in Text parameter):
"If you do not use this parameter, then default text is used as shown in the following examples."

But I see no examples. Examples would be nice :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b50e1b57-ec6b-0aa9-6a6b-59be6f268e2a
* Version Independent ID: 03858dda-2460-3301-1569-1412522b57f1
* Content: [FieldError Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-fielderror-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-fielderror-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-fielderror-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic was missing some content - this is added with the next refresh of the docs. Thanks.
