### ISSUE TITLE
Naming convention needs to mention possible conflict with deep inserts/deep updates

### ISSUE THREAD

**Issue by Repox** [MicrosoftDocs/dynamics365smb-devitpro-pb#1193]
Currently, this is [apparently a well known issue in the community](https://forum.mibuso.com/discussion/72423/api-deep-insert-not-working-in-custom-entity), but it's undocumented. Either it's a design flaw or intended (both possibilities are equally bad tbh). If this is a bug, please advise where to report this.

The issue is that if you are using Pages as parts, in a relation to an API Page, that relation Name _must_ be named exactly the same at `EntitySetName` otherwise [deep inserts](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/dynamics-rate-limits)/deep updates does not work.

This is a question that often is asked in the different communitues. It would be helpful to have this documented properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9788276f-d5a4-7742-0d2c-75db403698cf
* Version Independent ID: 8cc28734-434b-5795-0fc2-2d64e234e5de
* Content: [API Page Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-pagetype)
* Content Source: [dev-itpro/developer/devenv-api-pagetype.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-api-pagetype.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
Thank you for the input. I have marked it as bug. Name and EntitySetName should not be force to be identical. Deep patching is currently not supported.
