### ISSUE TITLE
To Modify the DropDown list in the fieldgroup

### ISSUE THREAD

**Issue by dewal1004** [MicrosoftDocs/dynamics365smb-devitpro-pb#1195]
[
Is there a function to modify the arrangemet of the fields listed in DropDown section of the fieldgroup.

e.g. Basic App field group is 
       fieldgroup(DropDown; Field1, Field2) {}

I have added a field 'Field50101' and 'Field50102' to the list through extension using
       addlast(DropDown; Field50101,Field50102) { }

_My client will like to rearrange the fields to be shown on the drop-down in this order
     Field1,Field50101,Field50102, Field2_
     ]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9979b71-a2f9-9032-5bba-161f6da5ff63
* Version Independent ID: 7fd0115f-bfec-43e1-e5c3-69bf2e4d383c
* Content: [Field Groups - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-field-groups)
* Content Source: [dev-itpro/developer/devenv-field-groups.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-field-groups.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. Reordering the items in an enum dropdown is not supported. The client displays the items in the order they are hand over from the server. Thanks.
