### ISSUE TITLE
Need a performance note when discussing Sql Server Joins

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1199]
This comment applies to every one of the Sql Server Join bullet points in this topic, Inner, Left, etc.
Even though Where clause and From clause joins produce the same result set, the related performance can be drastically different. The From clause is evaluated on the server and limits the number of records returned. The Where clause is evaluated afterwards and does NOT limit the number of records returned. This can be substantial.

Even though the Sql examples are only provided for explanatory purposes, the topic should clearly note that the strongly preferred method is the From clause method.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18009683-ecd1-1382-399d-6af2e485d592
* Version Independent ID: 581d021e-c1e0-1513-161e-a29abd462b83
* Content: [Data Item Links - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-query-links-joins)
* Content Source: [dev-itpro/developer/devenv-query-links-joins.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-query-links-joins.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've added a note about this. The update will be published soon.

**Comment by db-bc** [comment]
> The From clause is evaluated on the server and limits the number of records returned. The Where clause is evaluated afterwards and does NOT limit the number of records returned.

I don't understand this. Are you saying that a Where clause in a BC Query is not mapped directly to a SQL Server `where` clause? Because if it _does_, of course it runs on the SQL server, just as `join on` (which I assume is what you mean by "From") would. The difference is then one of semantics, where `join on` is preferable to `where`, but not one of performance.
