### ISSUE TITLE
Add some internal page links

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1201]
I would suggest a little introductory sentence at the beginning of this topic that included internal page links to the major topic sections. This would also serve as a very helpful summary of the different ways to filter a query.

Filtering on data items in a Query object
Filtering on columns and filter rows in Query object
Filtering using SETFILTER and SETRANGE methods
Equivalent SQL SELECT Statements for Query Filters

**Comment by jswymer** [comment]
Thanks for the feedback! We made some adjustments to the intro. The updated article will be published soon.
