### ISSUE TITLE
Needs an example

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1204]
This topic needs a simple example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c5a722c-0c3c-9b40-e57d-d301a0978c45
* Version Independent ID: c23a69c0-6270-aac2-7728-1f35853aaa01
* Content: [DataItemTableFilter Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-dataitemtablefilter-property)
* Content Source: [dev-itpro/developer/properties/devenv-dataitemtablefilter-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-dataitemtablefilter-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. An example has been added and will be available in the next refresh.
