### ISSUE TITLE
Add ENU to Msg: TextConst

### ISSUE THREAD

**Issue by fyuuhi** [MicrosoftDocs/dynamics365smb-devitpro-pb#1205]
[Enter feedback here]
This is an English text, so need to add `ENU`
.
❌ `Msg: TextConst = 'Hello from my method';`
⭕ `Msg: TextConst ENU = 'Hello from my method';`

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34c994f-9471-dfed-05be-e4893f63fd79
* Version Independent ID: cf609474-4520-ded4-fae2-fd4dd8235d07
* Content: [Table Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-object)
* Content Source: [dev-itpro/developer/devenv-table-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-table-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dNsl9r** [comment]
In my opinion adding ENU is obsolete nowadays because you work with XLF Files for translations.

**Comment by fyuuhi** [comment]
No, that is not my point.

Compilation is failed without ENU.
❌ Msg: TextConst = 'Hello from my method';
⭕ Msg: TextConst ENU = 'Hello from my method';

**Comment by dNsl9r** [comment]
Sorry, you are right! The example should be changed to used **Label** instead of **TextConst**.

**Comment by fyuuhi** [comment]
Thank you, dNsl9r😁

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - the topic will be fixed with the next doc refresh.

**Comment by fyuuhi** [comment]
Appreciate it.
