### ISSUE TITLE
Timestamp field: access by FieldRef

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1206]
Could you please add in the Timestamp section, that the timestamp field can also be accessed by a FieldRef alone, without the need to create another field?
Please see https://twitter.com/KarolakNatalie/status/1267739086447665153 for more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34c994f-9471-dfed-05be-e4893f63fd79
* Version Independent ID: cf609474-4520-ded4-fae2-fd4dd8235d07
* Content: [Table Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-object)
* Content Source: [dev-itpro/developer/devenv-table-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-table-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, we will add this information with the next refresh, thanks.
