### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1208]
In section [Protecting sensitive code from running during upgrade](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions?branch=master#protecting-sensitive-code-from-running-during-upgrade), the link to the **GetExecutionContext method** is broken.
The correct one is [this](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/session/session-getexecutioncontext-method).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aad761f-ad97-7f15-fd0b-81f5716d2d90
* Version Independent ID: d0f0fb7c-6a1f-efef-e43c-955bb10b1404
* Content: [Upgrading an Extension V2 to a new version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions?branch=master#protecting-sensitive-code-from-running-during-upgrade)
* Content Source: [dev-itpro/developer/devenv-upgrading-extensions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-upgrading-extensions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
