### ISSUE TITLE
Add or link code

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1209]
It would be quite handy to point to the following use case example:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions?branch=master#protecting-sensitive-code-from-running-during-upgrade

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3db26382-dacb-df03-99c5-2f75016d5281
* Version Independent ID: 78204072-def6-4ea5-2dce-0b0e2414b6d9
* Content: [GetExecutionContext Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/session/session-getexecutioncontext-method)
* Content Source: [dev-itpro/developer/methods-auto/session/session-getexecutioncontext-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/session/session-getexecutioncontext-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
That's a good point. This will be fixed with the next doc refresh. Thanks!
