### ISSUE TITLE
OptionCaptionML Property

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#121]
I guess this should be changed to OptionCaption Property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5367809-8bc3-af4d-f43c-92ec6bbbace6
* Version Independent ID: 31321a54-c0a5-d7a5-8c6e-62113b479751
* Content: [Table and Table Extension Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-table-properties)
* Content Source: [dev-itpro/developer/properties/devenv-table-properties.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-table-properties.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Yes, it would be more correct to link to OptionCaption, I agree. Although, we do still support the *ML properties for a while, it is absolutely a best practice to avoid them. This is updated in the next refresh. Thanks.
