### ISSUE TITLE
List all available page types, intended usage, differences, etc

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1210]
The current stub is useless as it lacks any useful information at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef98d5c-2b0f-10b5-1a60-e2af044b6e0b
* Version Independent ID: 3661238e-a728-345d-1c1c-e0ed66606cdf
* Content: [PageType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-pagetype-property)
* Content Source: [dev-itpro/developer/properties/devenv-pagetype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-pagetype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This reference topic is very basic, I agree. But we have a number of conceptual topics that explain page types and usage. We will update the topic to include a bit more information and relevant links. This will be fixed with the next doc refresh. Thanks.
