### ISSUE TITLE
Filter for empty value

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1211]
The article should mention that when filtering for an empty value with SetFilter, e.g. `MyRecord.SetFilter(MyTextField, '');`
it does not set a filter at all - other than `SetRange`, which would explicitly filter for the empty value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8dde5f8-90a7-8d17-8146-9de0b871b69f
* Version Independent ID: ba366fa4-9b85-1662-5a25-e26faf1d49ba
* Content: [SetFilter Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setfilter-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-setfilter-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-setfilter-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. Much appreciated. The topic will be fixed with the next doc refresh.
