### ISSUE TITLE
Codeunit Names Should be on the Page

### ISSUE THREAD

**Issue by MBK75** [MicrosoftDocs/dynamics365smb-devitpro-pb#1213]
[Enter feedback here]
Hello, instead of the codeunit IDs I think the names of the codeunits should be on this page.  There is no way in v16 to simply lookup a codeunit by ID easily.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66c0ad5-98e3-370e-2e24-c17c698fc24a
* Version Independent ID: 72059311-bb4e-e2fb-e6a8-e3ebbb2fdf1b
* Content: [Transitioning from Codeunit 1 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/transition-from-codeunit1)
* Content Source: [dev-itpro/upgrade/transition-from-codeunit1.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/transition-from-codeunit1.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We have updated the article to include the codeunit names. The updated article will be published soon.
