### ISSUE TITLE
MenuSuite Properties

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#122]
MenuSuite Properties link is broken. But I guess they do not apply to extensions anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4749e121-b119-f67b-0887-992ead0f8a0a
* Version Independent ID: f058fd88-5704-72b5-11ae-4f12a06edf05
* Content: [Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-properties)
* Content Source: [dev-itpro/developer/properties/devenv-properties.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-properties.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this bug, you're completely right, MenuSuite properties do not apply to extensions and in the next refresh, I've removed the link. Thanks again.
