### ISSUE TITLE
2 missing examples

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1222]
There are no examples for either situation described below.
The following example illustrates an XML element that has the ExtendedFormat set to false: The following example illustrates the same XML with the ExtendedFormat set to true:
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5fa09e-7f51-7efa-9017-d24c23cbc88f
* Version Independent ID: 2edba48f-c57d-45e7-a249-52a41aa05c35
* Content: [WordXmlPart Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-wordxmlpart-method)
* Content Source: [dev-itpro/developer/methods-auto/report/report-wordxmlpart-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/report/report-wordxmlpart-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! this issue has been fixed. The updated article will be published soon. Until then, updated text is:

The following example illustrates an XML element that has the ExtendedFormat set to true: \<CompanyName ElementType="Column" ElementId="3" DataType="OemText"\>

The following example illustrates the same XML with the ExtendedFormat set to false:\<CompanyName\>
