### ISSUE TITLE
Incompatible instructions

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#1223]
In Step 9 it's written:

> If you get errors on the following table objects, use the Object Designer to delete the objects because they are no longer used.
> 
> Table 470 Job Queue (replaced by the Task Scheduler)
> Table 824 DO Payment Connection Details
> Table 825 DO Payment Connection Setup
> Table 827 DO Payment Credit Card
> Table 828 DO Payment Credit Card Number
> Table 829 DO Payment Trans. Log Entry
> Table 1510 Notification Template

Then in task 11:

`Sync-NAVTenant -ServerInstance <ServerInstanceName>`

Obviously, if you delete objects in step 9, this Sync will throw error, as destructive changes will be detected. I think at least you should warn about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
No worries. It'is good feedback. The sentence may have been overshadowed by the IMPORTANT note that followed. We have now moved this sentence into the note, so maybe this will help. Thanks!
