### ISSUE TITLE
Incorrect code example

### ISSUE THREAD

**Issue by ajkauffmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#1226]
The code example about TableRelation to a SystemId field is incorrect. The field 'MyField' should be of type Guid because the SystemId is a Guid field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34c994f-9471-dfed-05be-e4893f63fd79
* Version Independent ID: cf609474-4520-ded4-fae2-fd4dd8235d07
* Content: [Table Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-object#timestamp)
* Content Source: [dev-itpro/developer/devenv-table-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-table-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be fixed with the next doc refresh.
