### ISSUE TITLE
Task 3: Create empty extensions, getting errors in VS Code

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#1228]
So according to the instructions: "The only file in the extension project that is required is an app.json"

Also it says The important settings in the app.json file id, name, and version

Si If I create an empty extension using Command Pallet AL:Go!, a new extension is created with just app.json and HelloWorld.al

- I delete HelloWorld.al
- I modify the app.json, and set the id, name and version according to the example:

My app.json looks like this:

```
{
  "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
  "name": "System Application",
  "version": "14.0.0.0"
}
```
VS Code throws this error:

> The package cache c:\MYPATH\ALSYS\./.alpackages could not be found

Please clarify if we need to take any other step for TASK 3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b2a8e-89a9-dda2-7d06-c433f2127044
* Version Independent ID: 4a968a4c-8ad7-8d9b-b966-b08daf4bda9a
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, thanks for the feedback. Strange. This error usually appears if there is an extension defined in the "dependencies" parameter of the app.json. For example:
```
"dependencies": [
    {
      "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "16.0.0.0"
    }
  ],
```
But from you snippet, it looks like you have not set the "dependencies" parameter. One thing, probably not related, is that you'll need to include the "publisher". Here is an example of what I have:

```
{
  "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
  "name": "System Application",
  "publisher": "Default publisher",
  "version": "14.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [],
  "screenshots": [],
  "platform": "16.0.0.0",
  "idRanges": [ ],
  "contextSensitiveHelpUrl": "https://bc14emptysysstemapplication.com/help/",
  "showMyCode": true,
  "runtime": "5.0",
  "target": "OnPrem"
}
```

**Comment by averied** [comment]
No luck with your same app.json. This is a screenshot of my environment:

![image](https://user-images.githubusercontent.com/10140930/84052727-d7e60f80-a9a8-11ea-813b-206c74666d51.png)

**Comment by jswymer** [comment]
Hello, I am not exactly sure what is going wrong. I did repro this issue. It seems that the project is looking for the System symbols in the .alpackage folder. 
1. Create a project using View>Command Palette> AL:Go
2. Delete the HelloWorld.Al file
3. Modify the app.json as discussed (remove dependencies, etc.)
4. Download symbols  using View>Command Palette> AL:Download Symbols

  VS Code should look something like this:
   ![image](https://user-images.githubusercontent.com/15834167/84120681-73719180-aa36-11ea-89ba-37810e62f666.png)

5. Build using crtl+shift+b.

**Comment by jswymer** [comment]
Hello, this a good point. There are a couple things:

- Downloading the symbols requires that the Symbols have been published to the server instance that is configured in the app.json. Also, it requires that connected database has the System Application and Base Application extensions published on the server and the tenant has been synced. The workaround, as you state, is to create  .alpackages folder and put in the System.app. This is like what was done in Task 2.

- If the app.json file includes "platform" parameter, when you build (Ctrl+Shift+B), the system will try to download the System symbols from the server instance.

I hope this helps explain things.

**Comment by jswymer** [comment]
The article has been updated to try to make this more clear. I hope we answered your question. Thanks for the feedback!
