### ISSUE TITLE
Task 6, Step 2. Setting DestinationAppsForMigration

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#1229]
About this step, the command I put into BC160 Admin Shell is:

`Set-NAVServerConfiguration -ServerInstance BC160 -KeyName "DestinationAppsForMigration" -KeyValue '[{"appId":"aeeddd4f-8360-4ba7-9773-3d7ca2c961c0", "name":"MYEXT", "publisher": "MYCOMPANY"}]'`

Question: is this appid the same from the extension we created in TASK 3 where we added the migration.json ?? Do we need to add the microsoft base and system apps as well in this step? Please clarify this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b2a8e-89a9-dda2-7d06-c433f2127044
* Version Independent ID: 4a968a4c-8ad7-8d9b-b966-b08daf4bda9a
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello. This is the ID of the ID of the table migration extension that was created in Task 2. The same goes for the name and publisher. We will make this more clear in the article. I hope this helps. Thanks for the feedback!

**Comment by jswymer** [comment]
The article has been updated. Thanks for the feedback!
