### ISSUE TITLE
Page Customization

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#123]
For the Page Customization there is no suggested abbreviation. Please add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0b094e-a368-aa20-e643-349515abf00e
* Version Independent ID: d3d587c3-0380-5b64-0c1a-274e393a4e58
* Content: [Best Practices for AL code - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/compliance/apptest-bestpracticesforalcode)
* Content Source: [dynamics-nav/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/compliance/apptest-bestpracticesforalcode.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. The page you have a link to there is actually living in the "old" repo, and the new URL for this topic should be [Best Practices for AL](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode) in the Business Central repo - the old topic should redirect to the new one, which is a bug in itself. So, for page customizations the best practice is to use PagCust - I will add that to the topic. Thanks again!

**Comment by SusanneWindfeldPedersen** [comment]
Page is updated and live.
