### ISSUE TITLE
Task 8: Increase application version. How do we find the exact ApplicationVersion?

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#1230]
We have downloaded from partnersource, a package of Dynamics 365 BC 2020 Wave 1, but, how do we find the exact "ApplicationVersion" parameter value for this command?? 

`Set-NAVApplication -ServerInstance <server instance name> -ApplicationVersion <new application version> -Force
`

As we are upgrading, we still don't have a working application to find this version number

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b2a8e-89a9-dda2-7d06-c433f2127044
* Version Independent ID: 4a968a4c-8ad7-8d9b-b966-b08daf4bda9a
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

For the general availability version, which you got from PartnerSource, you can get the exact version from the "version" setting in app.json file for the base application. For example, you can open the file from C:\BC16-1\dvd\Applications\BaseApp\Source\Base Application.Source.zip.

If you were using a minor update, like 16.1. you can see the application version from the [Released Updates for Microsoft Dynamics 365 Business Central 2020 Release Wave 1](https://support.microsoft.com/en-us/help/4549687) page.

This step is optional. The only thing is that if you don't increase the value, you'll have to use the -SkipAppVersionCheck switch when you get to Task 11. The application version eventually shows on the Help and Support page in the client. 

I hope this helps.

**Comment by jswymer** [comment]
Hello, the article has been changed to make this more clear. Thanks for the feedback!
