### ISSUE TITLE
Task 9. Step 2. Error when publishing migration extension

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#1231]
If my understanding is correct, in Task 3 we created a migration extension app. In task 9, when we try to publish this app with 'Publish-NAVApp' command, but we get this error:

>  You cannot publish an extension that has not been code signed.

Is it important to sign this app? How do we sign it? Or shall we just use the "-SkipVerification" option?

If we use the SkipVerification, we get this error:

> error AL1024: A package with publisher 'Microsoft', name 'System', and a version compatible with '16.0.0.0' could not be loaded. Symbols for the requested app System by
> Microsoft 16.0.0.0 could not be found in the database

How can we solve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b2a8e-89a9-dda2-7d06-c433f2127044
* Version Independent ID: 4a968a4c-8ad7-8d9b-b966-b08daf4bda9a
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

You can find information about code signing at [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sign-extension](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sign-extension). You can opt to "-SkipVerification" option, but this is not recommended if the extension will remain installed and published.

As for the second issue, it seems like the System sysmbols have not been published in Task 9. What do you get when you run Get-NAVAppinfo <server instance> -SymbolsOnly?

**Comment by jswymer** [comment]
We added a link to the code-signing article. This will be available in the next doc update. We hope the other question was also answered. Thanks for the feedback!
