### ISSUE TITLE
Incorrect table referance - price list line page example missing

### ISSUE THREAD

**Issue by imbru** [MicrosoftDocs/dynamics365smb-devitpro-pb#1235]
The following sentence is refering to an image with an example of a Price List Page. But the image actually shows a Sales Line Page. This should be corrected
The following image shows an example of a Price List page that is extended with the Attached to Line No. field. Notice that the prices are changed based on the combinations of licenses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32c26d28-1789-81d6-d3df-45cf91c09ef7
* Version Independent ID: 35bfccd5-c11f-a78f-e01c-bb95d0e1ee76
* Content: [Extending Price Calculations - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-best-price-calculations)
* Content Source: [dev-itpro/developer/devenv-extending-best-price-calculations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extending-best-price-calculations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **solsen**

**Comment by brentholtorf** [comment]
This was a nice catch. It's been fixed and will be published soon.
