### ISSUE TITLE
This procedure is not working in Business Central 14

### ISSUE THREAD

**Issue by pigualada** [MicrosoftDocs/dynamics365smb-devitpro-pb#1236]
I have tested in two different environments, following all instructions, and I'm getting this Application Log in Business Central server.

I have investigated possible source of error. Seems that Business Central when needs to verify signature of SAML and generate JWT token and send it back to client application. Federation metadata URL of course is accesible in both environments that I have tested.

Message (InvalidOperationException): This message had personal data removed. The original may still be in transient telemetry. Find it using the transientTelemetryId.
ParentException: InvalidOperationException
El documento Metadatos de la Federación no se pudo recuperar de la ubicación especificada: https://*******/federationmetadata/2007-06/federationmetadata.xml. Asegúrese de que el URI especificado señala a un recurso válido.
Detalles técnicos adicionales: 
No se pudo realizar la comprobación implícita de la referencia '#_77230fac-ba97-44f1-9c77-746db0b6c681'.
ExceptionStackTrace:
   en Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.LoadFederationMetadata(Boolean forceRefresh)
   en Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.get_SigningCertificates()
   en Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.GetValidSigningCertificateWithThumbprint(String tokenCertificateThumbprint, Boolean retry)
   en Microsoft.Dynamics.Nav.Service.NavJwtSecurityTokenFactory.<>c__DisplayClass3_0.<CreateUserTokenValidationParameters>b__1(String token, SecurityToken securityToken, String kid, TokenValidationParameters validationParameters)
   en System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   en System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   en Microsoft.Dynamics.Nav.Service.NavJwtSecurityTokenFactory.CreateAndValidateWithAudienceList(String serializedToken, FederationMetadataProvider federationMetadataProvider, IEnumerable`1 allowedAudiences, String tokenId, NavDiagnostics diagnostics)
   en Microsoft.Dynamics.Nav.Service.NavSecurityTokenFactory.Create(String response, Func`1 tokenSigningKey, FederationMetadataProvider federationMetadataProvider, String identityProviderAddress, String tokenId, String tokenType, NavTenant tenant)
   en Microsoft.Dynamics.Nav.Service.WSFederationValidator.Validate(NavTenant tenant, String userName, String password, String navAppId)
   en Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.ValidateCredentials(String userName, String password, NavTenant tenant, String navAppId)
   en Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.Validate(String userName, String password)
InnerException:
RootException: CryptographicException
ExceptionStackTrace:
   en System.IdentityModel.Reference.EnsureDigestValidityIfIdMatches(String id, Object resolvedXmlSource)
   en System.IdentityModel.StandardSignedInfo.EnsureDigestValidityIfIdMatches(String id, Object resolvedXmlSource)
   en System.IdentityModel.SignedInfo.EnsureDigestValidity(String id, Object resolvedXmlSource)
   en System.IdentityModel.EnvelopedSignatureReader.OnEndOfRootElement()
   en System.IdentityModel.EnvelopedSignatureReader.Read()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b4709ee-8ef1-8639-8940-31b51bf6f6b6
* Version Independent ID: 1f56370e-41ed-4f0b-f118-9a7644bb8d11
* Content: [Authenticating Users with Active Directory Federation Services - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-active-directory-federation-service)
* Content Source: [dev-itpro/administration/authenticating-users-with-active-directory-federation-service.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/authenticating-users-with-active-directory-federation-service.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.

**Comment by staedter** [comment]
@pigualada We got the same problem with a new environment for one of our customers with BC 16.0. The weird thing is, that we had setup an almost identical temporary evironment before within the infrastructure of our crm partner and that one worked with the same configurations in the ADFS and the NAV Servers.

We also spend much time troubleshooting this thing but have come any closer to a solution. Did you somehow manage to solve your problem or did you create a case with MS? 

`Server instance: Test
Category: Security
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 2ba554d1-cb2a-4b7b-92a9-4897e521c811
EventTime: 07/22/2020 12:17:31
Message (InvalidOperationException): This message had personal data removed. The original may still be in transient telemetry. Find it using the transientTelemetryId.
ParentException: InvalidOperationException
Der Verbundmetadaten-Beleg konnte nicht vom angegebenen Speicherort abgerufen werden: https://adfs.********.local/federationmetadata/2007-06/federationmetadata.xml. Stellen Sie sicher, dass die angegebene URI auf eine gültige Ressource verweist.
Weitere technische Details: 
Fehler bei der Digestverifizierung für Verweis "#_9ac7b823-7d99-45f2-b11a-1bac4e43c522".
ExceptionStackTrace:
   bei Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.LoadFederationMetadata(Boolean forceRefresh)
   bei Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.get_SigningCertificates()
   bei Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.GetValidSigningCertificateWithThumbprint(String tokenCertificateThumbprint, Boolean retry)
   bei Microsoft.Dynamics.Nav.Service.NavJwtSecurityTokenFactory.<>c__DisplayClass3_0.<CreateUserTokenValidationParameters>b__1(String token, SecurityToken securityToken, String kid, TokenValidationParameters validationParameters)
   bei System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   bei System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   bei Microsoft.Dynamics.Nav.Service.NavJwtSecurityTokenFactory.CreateAndValidateWithAudienceList(String serializedToken, FederationMetadataProvider federationMetadataProvider, IEnumerable`1 allowedAudiences, String tokenId, NavDiagnostics diagnostics)
   bei Microsoft.Dynamics.Nav.Service.WSFederationValidator.Validate(NavTenant tenant, String userName, String password, String navAppId)
   bei Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.Validate(String userName, String password)
InnerException:
RootException: CryptographicException
ExceptionStackTrace:
   bei System.IdentityModel.Reference.EnsureDigestValidityIfIdMatches(String id, Object resolvedXmlSource)
   bei System.IdentityModel.StandardSignedInfo.EnsureDigestValidityIfIdMatches(String id, Object resolvedXmlSource)
   bei System.IdentityModel.SignedInfo.EnsureDigestValidity(String id, Object resolvedXmlSource)
   bei System.IdentityModel.EnvelopedSignatureReader.OnEndOfRootElement()
   bei System.IdentityModel.EnvelopedSignatureReader.Read()
   bei System.Xml.XmlReader.ReadEndElement()
   bei System.IdentityModel.Metadata.MetadataSerializer.ReadEntityDescriptor(XmlReader inputReader, SecurityTokenResolver tokenResolver)
   bei System.IdentityModel.Metadata.MetadataSerializer.ReadMetadataCore(XmlReader reader, SecurityTokenResolver tokenResolver)
   bei System.IdentityModel.Metadata.MetadataSerializer.ReadMetadata(XmlReader reader, SecurityTokenResolver tokenResolver)
   bei Microsoft.Dynamics.Nav.Runtime.FederationMetadataParser.ParseFederationMetadata(String federationMetadata)
   bei Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.LoadFederationMetadata(Boolean forceRefresh)
CallerStackTrace:
   bei Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.Validate(String userName, String password)
   bei System.IdentityModel.Selectors.CustomUserNameSecurityTokenAuthenticator.ValidateUserNamePasswordCore(String userName, String password)
   bei System.IdentityModel.Selectors.SecurityTokenAuthenticator.ValidateToken(SecurityToken token)
   bei System.ServiceModel.Security.ReceiveSecurityHeader.ReadToken(XmlReader reader, SecurityTokenResolver tokenResolver, IList`1 allowedTokenAuthenticators, SecurityTokenAuthenticator& usedTokenAuthenticator)
   bei System.ServiceModel.Security.ReceiveSecurityHeader.ReadToken(XmlDictionaryReader reader, Int32 position, Byte[] decryptedBuffer, SecurityToken encryptionToken, String idInEncryptedForm, TimeSpan timeout)
   bei System.ServiceModel.Security.ReceiveSecurityHeader.ExecuteFullPass(XmlDictionaryReader reader)
   bei System.ServiceModel.Security.ReceiveSecurityHeader.Process(TimeSpan timeout, ChannelBinding channelBinding, ExtendedProtectionPolicy extendedProtectionPolicy)
   bei System.ServiceModel.Security.TransportSecurityProtocol.VerifyIncomingMessageCore(Message& message, TimeSpan timeout)
   bei System.ServiceModel.Security.TransportSecurityProtocol.VerifyIncomingMessage(Message& message, TimeSpan timeout)
   bei System.ServiceModel.Security.SecurityProtocol.VerifyIncomingMessage(Message& message, TimeSpan timeout, SecurityProtocolCorrelationState[] correlationStates)
   bei System.ServiceModel.Channels.SecurityChannelListener`1.ServerSecurityChannel`1.VerifyIncomingMessage(Message& message, TimeSpan timeout, SecurityProtocolCorrelationState[] correlationState)
   bei System.ServiceModel.Channels.SecurityChannelListener`1.SecurityReplyChannel.ProcessReceivedRequest(RequestContext requestContext, TimeSpan timeout)
   bei System.ServiceModel.Channels.SecurityChannelListener`1.ReceiveRequestAndVerifySecurityAsyncResult.ProcessInnerItem(RequestContext innerItem, TimeSpan timeout)
   bei System.ServiceModel.Channels.SecurityChannelListener`1.ReceiveItemAndVerifySecurityAsyncResult`2.OnInnerReceiveDone()
   bei System.ServiceModel.Channels.SecurityChannelListener`1.ReceiveItemAndVerifySecurityAsyncResult`2.StartInnerReceive()
   bei System.ServiceModel.Channels.SecurityChannelListener`1.ReceiveItemAndVerifySecurityAsyncResult`2.Start()
   bei System.Runtime.IOThreadScheduler.ScheduledOverlapped.IOCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   bei System.Runtime.Fx.IOCompletionThunk.UnhandledExceptionFrame(UInt32 error, UInt32 bytesRead, NativeOverlapped* nativeOverlapped)
   bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)


ProcessId: 3700
Tag: 0000237
ThreadId: 28
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: `

**Comment by pigualada** [comment]
I created a case with Microsoft, but after 2 weeks with some ping-pong emails and not having any real solution, we finally came to federate with Azure AD, which itself is federated to ADFS, so coming to a complete solution for our customer. No issues with Azure AD.
Seems Business Central is not well tested with ADFS.

**Comment by staedter** [comment]
@pigualada

Thanks for your reply. I will keep that route in mind, but we are still trying to make it work with our OnPrem ADFS. What kind of service communication certificate did you use? Because that seems to be the only real difference between the working environment  which uses an externally bought cert and our customers environment using an Domain CA self-signed one.

**Comment by melichov** [comment]
I have finally found the cause. The cause is: Business Central works with ASCII encoding. This means, if the FederationMedataData.xml from ADFS contains special characters, then this error occurs.

So there are two possibilities: Run ADFS in English language or clean the Claims Description from special characters. 

For the second part I created a PowerShell script for German environment:

$claims = Get-AdfsClaimDescription | Where-Object {$_.Name -cmatch '[^\x20-\x7F]'}
for ($i=0; $i -lt $claims.length; $i++){
    Set-AdfsClaimDescription -TargetName $claims[$i].Name -Notes $claims[$i].Notes.Replace('ä','ae').Replace('Ä','Ae').Replace('ö','oe').Replace('Ö','Oe').Replace('ü','ue').Replace('Ü','Ue')
}

$claims = Get-AdfsClaimDescription | Where-Object {$_.Name -cmatch '[^\x20-\x7F]'}
for ($i=0; $i -lt $claims.length; $i++){
    Set-AdfsClaimDescription -TargetName $claims[$i].Name -Name $claims[$i].Name.Replace('ä','ae').Replace('Ä','Ae').Replace('ö','oe').Replace('Ö','Oe').Replace('ü','ue').Replace('Ü','Ue')
}
