### ISSUE TITLE
Add info on when this property can be changed

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#124]
DataPerCompany can not be simply changed on existing tables. Please elaborate on when (and when not) DataPerCompany can be changed for these tables. This si very important to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4e8d65c-b1bb-2e92-0827-5a206d7a3962
* Version Independent ID: 1113af58-3400-02e3-f6ba-d768a39cd1d7
* Content: [DataPerCompany Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/datapercompany-property)
* Content Source: [dynamics-nav/DataPerCompany-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/DataPerCompany-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, and sorry for the late reply. This property now has a doc update and will be refreshed as soon as possible. Thanks again.
