### ISSUE TITLE
Supported language & structure

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1240]
IMHO, this statement is incorrect, or it is easily to misundestand:
_You must include all translations of countries your extension is supporting._

We are allowed to publish our extensions to countries without actually providing the language:
https://twitter.com/MeFriis/status/1204775768041164800

Furthermore, I am missing the position inside a navigation tree on the left, and/or links to a parent article or at least a link to "step 2" or "step 4" to continue reading.
... or wait, how is this article related with that here? https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b5ed4b-07ce-a1ea-3d84-188b5eb4de2b
* Version Independent ID: c249ea03-2ce7-6607-b19e-8e26f2333a40
* Content: [Step 3 - How to Develop Your App - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-develop-your-app)
* Content Source: [dev-itpro/developer/readiness/readiness-develop-your-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-develop-your-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for catching this. This version of the validation checklist was out of sync. Is fixed with the next doc refresh. The second comment - is that regarding the table of contents on the left? Do you remember where you navigated to this page from, or can you elaborate? Thanks!

**Comment by NKarolak** [comment]
I have found the [current page, no menu](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-develop-your-app) by using the search. It looks like it has been replaced by [the other page, with menu](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission), so the current could be deleted?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks! I agree, the first page doesn't add much information, but I believe it is (or has been) part of a topic that outlines step 1, 2, and 3. It does seem redundant, though. Thanks for the quick reply.
