### ISSUE TITLE
Wrong locales for Czech

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#1241]
Hi, there is wrong locales code for Czech. It should be "cs-CZ", not "cz-CZ", this locale doesn't exists, see your own list of locales e.g. here https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f

With regards

Kamil Sacek
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 360d9409-840a-5ef9-9aa4-b43ed4733e2c
* Version Independent ID: 961502fa-6d30-47fa-8afe-a15a8e521304
* Content: [Country/region availability and supported languages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations?source=docs)
* Content Source: [dev-itpro/compliance/apptest-countries-and-translations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-countries-and-translations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be fixed with the next doc refresh.
