### ISSUE TITLE
Task 9 Step 2 and Task 12 Publish Apps

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#1243]
In task 2, we create 2 versions of the migration extension, one with migration.json and one without. Which one we need to publish at Task 9, step 2?

I guess it's the one without migration.json, because in task 12 it says to publish the second version, but would like to confirm anyway. Anyway would be nice to have this clarified in Task 9.2

Also task 12, it's not detailed, but I guess we need to use the same command "Publish-NAVApp" for each app. 

Please clarify in task 12 Microsoft System Application and Microsoft Base Application, are these the empty applications we created in task 3, or do we take them from the installation media (what folder?) Base Application in media comes in different localizations, any comments on that?

(Notice that in task 9, step 3, we already Publish the empty apps)

I would also clarify in Task 10 step 3, What version of migration extension do we "Sync-NAVApp"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b2a8e-89a9-dda2-7d06-c433f2127044
* Version Independent ID: 4a968a4c-8ad7-8d9b-b966-b08daf4bda9a
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Here is some info, which will will include in the article:

-  In task 9, step 2, publish the first version of the table migration extension, which is the version that contains the table objects.

- In Task 10, step 3, you sync the first version of the table migration extension, which is the version that contains the table objects.
- In Task 12, you publish extensions using the Publish-NAVApp cmdlet like you did in previous steps.
- In Task 12, you publish the System Application (Microsoft_System Application.app) and Base Application (Microsoft_Base Application.app) extensions that are on the DVD. You do not not publish the empty versions again.
  - You find the Microsoft_System Application.app in the Applications\System Application\Source folder of installation media (DVD).
  - You find the Microsoft_Base Application.app in the Applications\BaseApp\Source folder of installation media (DVD).  The other .app files in this folder, like Microsoft_Danish language (Denmark).app include translations for objects in the base app.

Hope this answers some of your questions. Thanks for the feedback!

**Comment by jswymer** [comment]
Hello, we have updated the article to make this more clear. Thanks for the feedback!
