### ISSUE TITLE
Unsupported field change in task 13

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#1244]
Not sure if we're doing something wrong, but we are getting Unsupported field change errors in task 13

We follow this recommendation from the docs 

`The migration extension must be synchronized last`

So after system app, we are trying to sync the Base Application like this:

`Sync-NAVApp -ServerInstance bc160 -Name "Base Application" -Version 16.1.12629.12805`

At this moment, we get the error. I guess the base app does not include our custom fields, so it's detecting a destructive change in the database. This fields will be, if I'm not wrong, in the migration extension.

How do we avoid this error? How do we keep our custom fields during upgrade and at the same time Sync the Base app?

**Comment by averied** [comment]
OK.. here's un UPDATE

I think, the key is to work only the first version of the migration extension  until we reach task 12, where the Second version of the table migration extension is published

But now, when I try to Sync the Second version is when I get the error:

`Sync-NAVApp -ServerInstance bc160 -Name "MyMigApp" -Version 1.0.0.1`

> Table G/L Account :: Unsupported field change. Field:MyCustomField; Change:Remove

**Comment by nikolakukrika** [comment]
Sync of the app will delete the fields unless an extension has taken ownership of them. For this reason the extension giving the fields should be synced last. In your case no one has taken the ownership of the fields. Have you published, installed and synced the app that takes over the fields?

If you are moving fields out the flow is following:
1. Create a new base app, with a new ID and new name. Target base app should be blank. You upgrade to this middle step.
2. New base app V2 should be blank, with migration json specifying the full base app with higher version and your extension on top. Then you publish all of them, sync the base app first, your extension then and new base app last. On the last step if some fields are not taken over, you will get an error. This is a verification that nothing is dropped.

**Comment by averied** [comment]
OK.. will try this steps, but honestly I don't understand why this is not documented in the article, as the title of de doc is "(Upgrading) From version 14 Customized C/AL Application"

IMO any Customized C/AL Application is going to have at least some custom fields created in Basic tables, so instructions to upgrade from this case should be documented in the article.

**Comment by nikolakukrika** [comment]
Which part is missing? Please list the confusing items and a link to the topic and our technical writer will update the article.

**Comment by jswymer** [comment]
Glad we could help! This is good feedback and helps us improve the docs. If you have the time I would like to get a clearer understanding of how you performed the upgrade. 

As I understand it:.
- You **did not** create an empty version of the custom extension. You only created the production version.
- But you did include a rule for the custom extension in the the migration.json file of the **Migration** extension.

Is this correct?

I would like to summarize the steps you went through. Please correct me if I'm wrong. 

1. Created an extension that contained custom tables and fields
2. Created two versions of the migration extension:
   1. First version contained the tabled1 with tables
   2. Second version was empty and contained the migration.json. The migration.json included rules for **System App**, **Base App**, and **Custom** extension..
3. Created empty versions of **System App** and **Base App**.
4. Converted the old database.
5. Prepared database
6. Set the DestinationAppsForMigrations setting of the server to the **Migration** extension v1.
7. Imported license.
8. Increased application version.
9. Published extensions:
    1. Symbols
    2. **Migration** extension v1 (one with tables)
    3. Empty **System App**
    4. Empty **Base App**
 10. Synchronized:
    1. Tenant
    2. **System App** extension
    3.  **Base App** extension
11. Did the following:
    1. Ran Start-NAVDataUpgrade. This ran data upgrade and installed the **Migration** extension v1.
    2. Installed the empty **System App** and **Base App** extensions only.
12. Published the new extensions:
     1. **Migration** extension v2
     2. **System App** from DVD
     3. **Base App** from DVD
     4.  **Custom** extension
13. Synchronized the extensions:
     1. **System App**
     2. **Base App**
     3. **Custom** extension
     4. **Migration** extension version 2 (migration-json)
14. Upgraded **Migration ** extension.
15. Upgraded these extensions:
      1. **System App**
      2. **Base App**
16. Installed the **Custom** extension.

**Comment by averied** [comment]
@jswymer correct. These are the steps exactly. in migration.json I include my custom extension as you said

**Comment by jswymer** [comment]
Thanks for confirming!

I have already made a few adjustments to the article based on your feedback. I will run through it and make sure this scenario is covered. In a way, it ties in with [GitHub 1223](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1233). Thanks again.

**Comment by jswymer** [comment]
We've made some updates to the article, which we will publish soon. Thanks for the feedback!
