### ISSUE TITLE
AutoFormat numbers are incorrect in example

### ISSUE THREAD

**Issue by tfbtrading** [MicrosoftDocs/dynamics365smb-devitpro-pb#1245]
The examples at the end of AutoFormat Type 10 have incorrectly got AutoFormat Type 1. Discovered this when trying for % autoformat and blindly copy/pasting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 469a62c8-2505-8533-a1b6-d9f4d27f59b4
* Version Independent ID: fa107bb8-b17b-c938-e17c-6a67e7faa19b
* Content: [Formatting the Data in a Field - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-field-data)
* Content Source: [dev-itpro/developer/devenv-format-field-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-format-field-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this, it will be fixed with the next refresh.
