### ISSUE TITLE
Semantic error in all examples

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1247]
It would be probably helpful for all programmer newbies to see examples could that could actually compile ;-)
Namely, all statements with 
`Customer.AnyField = True`
should be 
`Customer.AnyField := True;`

BTW the whole artikel (and all linked ones) are still using the C/AL function names. e.g. [C/AL] SETRANGE instead of [AL] SetRange.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4443c9f9-7867-6145-f348-eb3dd81430c7
* Version Independent ID: c8adc140-7ee8-544e-9209-dbe6f3c327d9
* Content: [AL Database Methods and Performance on SQL Server - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/optimize-sql-al-database-methods-and-performance-on-server)
* Content Source: [dev-itpro/administration/optimize-sql-al-Database-methods-and-performance-on-server.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/optimize-sql-al-Database-methods-and-performance-on-server.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This topic was using old syntax and this will be fixed with the next doc refresh.
