### ISSUE TITLE
Add link to example

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1248]
Could you please add a link to the example in https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/optimize-sql-al-database-methods-and-performance-on-server#setautocalcfields ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 281928a1-4df6-4656-2f12-2985298e6fa3
* Version Independent ID: e4ecf777-facb-d697-f999-daf2c6cdddf7
* Content: [SetAutoCalcFields Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setautocalcfields-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-setautocalcfields-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-setautocalcfields-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've added the link and the update will be published soon.
