### ISSUE TITLE
Specify BC version

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1249]
In section [Business Central Server data caching](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/optimize-sql-data-access#-server-data-caching), you wrote 

> In earlier versions of Business Central, the data cache was isolated for each user.

On all occurrencies of "earlier version", could you please (always) specify the exact version that introduced the new feature? This is always handy when troubleshooting in customer projects. 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a8b439d-5e3b-4dfa-0c8b-7231d994e442
* Version Independent ID: d484f6f6-be68-6244-49a7-65bf3b8e6dcc
* Content: [Data Access - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/optimize-sql-data-access)
* Content Source: [dev-itpro/administration/optimize-sql-data-access.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/optimize-sql-data-access.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

The statement is wrong, sorry. The data caching change was introduced in Dynamics NAV, probably around NAV 2017 or 2018. The statement is left-over from when we transformed the content to Business Central, and should be removed or at least fixed.

**Comment by jswymer** [comment]
The statement has been removed from this article to avoid confusion. Thanks for the feedback!
