### ISSUE TITLE
Step 2 - Install Business Central from DVD

### ISSUE THREAD

**Issue by hougaard** [MicrosoftDocs/dynamics365smb-devitpro-pb#1250]
The procedure described does not work, running setup.exe gives you the options to modify(not what we want), repair(not what we want either?) and uninstall(clearly not what we want).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566ac7ba-c8e2-cd8f-370e-26e1d581a7cf
* Version Independent ID: 6961aefe-7207-d8eb-4b2b-a249d321a309
* Content: [Install a cumulative update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. Unfortunately, the article is not clear. With the minor update, you'll have to do one of two things:

- Uninstall the current version. You can do this by running setup.exe or from Control Panel. 

- Manually patch the components by copying files from DVD to current installation folders. For example:

    |Component|Copy from DVD |To current installation folder|
    |---------|---------|--|
    |Server|DVD\ServiceTier\program files\Microsoft Dynamics NAV\140|C:\Program Files\Microsoft Business Central\<140>\Service|
    |WebClient|DVD\WebClient\Microsoft Dynamics NAV\140\Web Client|C:\Program Files\Microsoft Dynamics 365 Business Central\<140>\Web Client|
    |Windows Client and Development Environment|DVD\RoleTailoredClient\program files\Microsoft Dynamics NAV\140\RoleTailored Client|C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\<140>\RoleTailored Client|
    |Microsoft Office Outlook Integration|<ul><li>DVD\Outlook\program files\Microsoft Dynamics NAV\140\OutlookAddin</li><li>Microsoft.Dynamics.NAV.OLSync.NAVSyncAddIn.dll</li></ul>|<ul><li>C:\Program Files(x64)\Microsoft Office\Office \<version\></li><li>C:\Program Files (x64)\Microsoft Office\Office\xx-XX</li></ul>|

**Comment by hougaard** [comment]
Sooo.. are you updating the article also, or just replying here?

**Comment by jswymer** [comment]
The article has been updated and the update will be published soon. Thanks.
