### ISSUE TITLE
function in Page does not have FunctionVisibility property

### ISSUE THREAD

**Issue by elvichu** [MicrosoftDocs/dynamics365smb-devitpro-pb#1251]
I could not found the property "FunctionVisibility" in Page when creating new function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b3196a-00cc-3382-f040-ef813b4029e4
* Version Independent ID: cbd09737-7acd-2534-d9aa-96a8b34c8c4f
* Content: [Walkthrough: Creating and Interacting With an OData V4 Bound Action - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action)
* Content Source: [dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the topic that you are referring to is based on Dynamics NAV development environment and ported for compatibility reasons. If you are using AL for Business Central, I recommend that you read [Creating and Interacting with an OData V4 Bound Action](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-bound-action) instead. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue for now.
