### ISSUE TITLE
Link mising to 

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1256]
It's very strange to me that the topic on the report object does not have a link to the topic **Report Data Type** https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-data-type.
And search on _report object_ does not reveal it either.
Please add a link between the two topics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0042001-b98b-71c6-f659-84af0bd52a7d
* Version Independent ID: 212b2740-288e-8c5a-9e1e-960fcfb5739c
* Content: [Report Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-object?source=docs)
* Content Source: [dev-itpro/developer/devenv-report-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-report-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Makes good sense, thanks for the feedback. Will be fixed with the next doc refresh.
