### ISSUE TITLE
DataType Defined wrong

### ISSUE THREAD

**Issue by SUD-D365** [MicrosoftDocs/dynamics365smb-devitpro-pb#126]
As per my knowledge ,DataType should be RecordRef for variable MyRecord

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c5cade-fe84-324b-4354-4e407d92e9bf
* Version Independent ID: bd01fadd-3deb-4ec8-36b2-e4a88510e194
* Content: [RECORDID (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/recordid--record-)
* Content Source: [dynamics-nav/RECORDID--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/RECORDID--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback. The article has been fixed and an update will be published soon.

**Comment by SUD-D365** [comment]
Still not updated.

**Comment by jswymer** [comment]
Hello, thanks for the follow. Good catch, as something went wrong with the publishing. What I found is that the example for the article was wrong, Here is the correct example: 

MyRecord.OPEN(18);  
MyRecord.FINDLAST;  
RecID := MyRecord.RECORDID;  
MESSAGE(MyTextConst, RecID);

So the DataType for MyRecord should be Record. Let me know if you disagree. I will publish the update.  Thanks

**Comment by SUD-D365** [comment]
Oh, I didn't noticed your updated example here.
Yes, now its looking ok.

Thanks for instant revert. :)
