### ISSUE TITLE
Add properties

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1260]
Could you please link all available properties, methods etc. for this page type, e.g. [APIPublisher Property (Page)](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-apipublisher-page-property)?
The same applies to page [API Query Type](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-querytype).
Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9788276f-d5a4-7742-0d2c-75db403698cf
* Version Independent ID: 8cc28734-434b-5795-0fc2-2d64e234e5de
* Content: [API Page Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-pagetype)
* Content Source: [dev-itpro/developer/devenv-api-pagetype.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-api-pagetype.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We have added links to the properties topics for easier access. Will be available with the next doc refresh. Thanks.
