### ISSUE TITLE
Invoke-NAVApplicationDatabaseConversion fails unless default database schema is dbo

### ISSUE THREAD

**Issue by ichladil** [MicrosoftDocs/dynamics365smb-devitpro-pb#1262]
Hello, 

in version BC16.2 (CZ) database conversion using Invoke-NAVApplicationDatabaseConversion from 15.2 is failing when the user on SQL has a different default schema than dbo.

The reason behind is that DB conversion creates two SQL functions without schema in its definition:
CREATE FUNCTION PteIsolation_ConvertScopeAndTenantIdComboToPublishedAsField
CREATE FUNCTION PteIsolation_ConvertNullTenantIdToEmpty

but it expects dbo schema when calling those sql functions ...

Regards,
  Igor

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
