### ISSUE TITLE
Expand the examples

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1263]
I don't know about everyone else here, but the somewhat cryptic breakdown of how this can work, doesn't really help me understand it. It would be useful if there were some examples making use of all the possible features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babe9dc8-8278-49b7-3f8a-0bc75dd8307b
* Version Independent ID: 7cf185fd-3e0e-6d5f-7ed4-8a3773534357
* Content: [SubPageView Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-subpageview-property)
* Content Source: [dev-itpro/developer/properties/devenv-subpageview-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-subpageview-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the topic that you are referring to is a so-called reference topic, and it is not in itself giving much context - we do have a conceptual topic that shows how the SubPageView property can be set in a page part [Adding a FactBox to a Page](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-a-factbox-to-page). We are continuously working on adding more examples to the documentation. Thanks.

**Comment by mjmatthiesen** [comment]
Note that this doesn't address my concern at all.
