### ISSUE TITLE
HTTPS Add urlacl example incorrect

### ISSUE THREAD

**Issue by peterneave** [MicrosoftDocs/dynamics365smb-devitpro-pb#127]
For example, if the service account for Microsoft Dynamics NAV Server has the domain ABC and the user name xyz, and then the command for the SOAP web service is as follows:

netsh http add urlacl url=https://+:7047/nav_server_instance user="NT AUTHORITY\NETWORKSERVICE"

Should be 
netsh http add urlacl url=https://ABC:7047/nav_server_instance user="xyz"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12542a36-9b14-c85d-6f6e-15ab6666ccc7
* Version Independent ID: 177a81a7-dfeb-97c0-e66c-4bb715f56682
* Content: [Walkthrough: Configuring Web Services to Use SSL (SOAP and OData) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--configuring-web-services-to-use-ssl--soap-and-odata-)
* Content Source: [dynamics-nav/Walkthrough--Configuring-Web-Services-to-Use-SSL--SOAP-and-OData-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Configuring-Web-Services-to-Use-SSL--SOAP-and-OData-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! We have updated the content and the changes will available soon, the next time we publish.
