### ISSUE TITLE
dbo.printer selection$11111111-aaaa-2222-bbbb-333333333333 does not exist | migration.json documentation wrong

### ISSUE THREAD

**Issue by hvandenborn** [MicrosoftDocs/dynamics365smb-devitpro-pb#1272]
the section:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-table-fields-up#create-new-empty-version-of-transition-extension-ext-z-v2

--------------------
{ 
"apprules": [ 
    { 
        "id": "11111111-aaaa-2222-bbbb-333333333333"
    }
    { 
        "id": "44444444-cccc-5555-dddd-666666666666"
    }
] 
} 
------------------

the migration.json should not contain the ID of the Z app (11111111-aaaa-2222-bbbb-333333333333) i tried alot of times, cost me allot of time!!!
problems like, dbo.printer selection$11111111-aaaa-2222-bbbb-333333333333 does not exist etc.. etc.. 

then i checked the online project https://github.com/microsoft/BCUpgrade/tree/master/Upgrade14To16ExtractFieldsToExtensions

here i checked their migration.json from the alltableapp to the final apps, and they do not include the alltableapp ID (app Z 11111111-aaaa-2222-bbbb-333333333333) and finally it works.

so please update this documentation.. 

now i understand the error of dbo.printer selection$11111111-aaaa-2222-bbbb-333333333333 does not exist etc. when having the new app and the Z app (11111111-aaaa-2222-bbbb-333333333333) in the migration.json its trying to give ownership of this table to 2 apps, while only 1 app has it.. the base of microsoft. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1766666e-4ccc-37ea-b63a-78a21ef4a3b8
* Version Independent ID: 75882ca8-c232-4601-369d-1f9028bf9fe4
* Content: [Migrating Tables and Fields Between Extensions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-table-fields-up)
* Content Source: [dev-itpro/developer/devenv-migrate-table-fields-up.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-migrate-table-fields-up.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. The example code in step 1 was incorrect. It did not match what was stated for the step. The migration.json file should include the IDs of the releasing extension Ext X and receiving extension Ext Y.

So for example, if the ID of ext X is 77777777-eeee-8888-ffff-999999999999 and ext Y is 44444444-cccc-5555-dddd-666666666666, the migration.json should look like this:
 
```
{ 
"apprules": [ 
    { 
        "id": "77777777-eeee-8888-ffff-999999999999"
    }
    { 
        "id": "44444444-cccc-5555-dddd-666666666666"
    }
] 
} 
```

Sorry for the misinformation.  The article has been fixed and an update will be published soon. Thanks again.
