### ISSUE TITLE
How to make a task scheduler run the task as a foreground service. 

### ISSUE THREAD

**Issue by JanardhanGN91** [MicrosoftDocs/dynamics365smb-devitpro-pb#1273]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c2da1a7-cbd8-9412-2bb0-9c61d25c5528
* Version Independent ID: 6b04bae7-3bdd-1582-c49c-a71fc36715ce
* Content: [Task Scheduler - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-task-scheduler)
* Content Source: [dev-itpro/developer/devenv-task-scheduler.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-task-scheduler.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
This is a product question, please use your usual support channel. Thanks.
