### ISSUE TITLE
Syntax should be with "" and no spaces, like this: .\altpgen.exe -project:"C:\Users\lohndorf\Documents\AL\OP160TableProxy" -packagecachepath:"C:\Users\lohndorf\Documents\AL\OP160TableProxy\.alpackages" -serviceuri:"https://pfctest.crm11.dynamics.com/ -entities:pfc_JobApplicant" -baseid:50106 -tabletype:CDS 

### ISSUE THREAD

**Issue by lohndorf** [MicrosoftDocs/dynamics365smb-devitpro-pb#1274]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c207282-cbc6-4192-8c68-93833d882079
* Version Independent ID: d6ae70c2-0f8d-17b6-58e2-59d008049389
* Content: [AL Table Proxy Generator - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-table-proxy-generator)
* Content Source: [dev-itpro/developer/devenv-al-table-proxy-generator.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-table-proxy-generator.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
