### ISSUE TITLE
Are CaptionML being removed from BC?

### ISSUE THREAD

**Issue by GrumpyNAVdev** [MicrosoftDocs/dynamics365smb-devitpro-pb#1276]
Some say we should not use CaptionML for Tenant Extensions as they are planned to be removed in future BC versions.
Is this true, or is it safe to use it as long as the extension is not expected to be put in App Source?

Best regards
Peter
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bfbb9ca-3b27-7151-5fbc-5986c81f6b23
* Version Independent ID: 03fd2eed-c11c-16b4-9588-26feea722301
* Content: [CaptionML Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-captionml-property)
* Content Source: [dev-itpro/developer/properties/devenv-captionml-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-captionml-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. If you are not planning on submitting your app through AppSource, it should be safe to use CaptionML. Thanks.
