### ISSUE TITLE
Migrate data from Business Central 14.x on-premises to Business Central 15.x online

### ISSUE THREAD

**Issue by ERPgruppenMW** [MicrosoftDocs/dynamics365smb-devitpro-pb#1277]
**This topic on Feature Changes is somewhat misguiding on page Update 16.2 for Microsoft Dynamics 365 Business Central online 2020 release wave 1**

On premise to 15.x online, when online is on version 16.x.  Should the topic not be upgrade to 16.x online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9b5ce2-1cf9-3cf5-6233-4f272e072202
* Version Independent ID: 860598ee-65ab-350e-b7d0-df82ac49db65
* Content: [Update 16.2 for Microsoft Dynamics 365 Business Central 2020 Release Wave 1 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/whatsnew/whatsnew-update-16-2)
* Content Source: [dev-itpro/whatsnew/whatsnew-update-16-2.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/whatsnew/whatsnew-update-16-2.md)
* Service: **dynamics365-business-central**
* GitHub Login: @ManuelaHochstrasser
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the topic is included in the 16.2 update, but that specific entry applies to migrating from 14.x to 15.x which is further described in the Release Plan. Thanks.
