### ISSUE TITLE
Datascope as a variable is accepted by AL and compiles, but...

### ISSUE THREAD

**Issue by lebragan** [MicrosoftDocs/dynamics365smb-devitpro-pb#1278]
While trying to use single Encrypt and Decrypt set of procedures, one of the parameters I decided to create was Scope: DataScope; then, when calling the procedures, the caller parameters would use, a variable declared as forScope: DataScope, where you'd set prior to calling the encrypt or decrypt the forScope to forScope::User of forScope::Module.

No errors compiling the full AL code; so far, so good. Also, Ctrl+Shift+B runs without errors.

The issue "(...)failed with code UnprocessableEntity. Reason: One or more errors occurred.
This program location is thought to be unreachable. **Normal variable of type DataScope**" appears a few moments after when you press F5 upon which it compiles again, then connects to the BC service and fails with the issue.

It looks like we shouldn't be able to declare a variable as DataScope at all, nor even call the procedures with a direct parameter DataScope::User, for example.

My initial workaround was to have 4 procedures instead of 2, like Encrypt_M, Encrypt_U, Decrypt_M and Decrypt_U which looks a bit annoying, given that each pair' internal code was almost similar, but finally had to stick to that, so far.

So, declaring a var forScope: DataScope and then assigning that var a datascope option or as well as defining a parameter in a procedure as a DataScope variable, would be better if it would raise compilation errors.

Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb191d26-9c55-baee-1b0f-40138d613b8a
* Version Independent ID: 79a8b769-eb81-31fc-731d-580a24f9e6a0
* Content: [DataScope System Option - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/datascope/datascope-option)
* Content Source: [dev-itpro/developer/methods-auto/datascope/datascope-option.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/datascope/datascope-option.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
