### ISSUE TITLE
Is it ok to use the Content area type with Card page extensions?

### ISSUE THREAD

**Issue by tbebekis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1279]
The documentation on this page says that the Content area type can be used with RoleCenter and List pages only. 

I use the Content area type in extending a Card page, specifically the "Item Card" page, and BC displays perfectly the groups I add.

Is it ok to use the Content area type with Card page extensions?

```
pageextension 50100 ItemCardExt extends "Item Card"
{
    layout
    {
        addlast(Content)
        {
            group("My Group")
            {
                field(A_FieldName_Here; A_FieldName_Here)
                {

                }
            }
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0363ee62-5ad8-5e9a-82f5-27b3fa351506
* Version Independent ID: cb7dcfb3-3766-35a9-dade-dc5d450f6e25
* Content: [Pages Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-pages-overview)
* Content Source: [dev-itpro/developer/devenv-pages-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-pages-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello thanks for your question. Yes, you can definitely use the content area in the context above as an anchor for placing controls. We will make this more clear in the documentation. This will be fixed with the next refresh of the docs. Thanks!

**Comment by tbebekis** [comment]
ok, thanks.
