### ISSUE TITLE
Don't copy/paste Thumbprint

### ISSUE THREAD

**Issue by peterneave** [MicrosoftDocs/dynamics365smb-devitpro-pb#128]
"Copy the hexadecimal characters from the box, and then paste them in a text editor, such as Notepad. These characters make up the thumbprint." This will lead to an extra character unicode character being copied over. (see https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--configuring-web-services-to-use-ssl--soap-and-odata-#Thumbprint)

Instead, follow the solution offered here.
https://support.microsoft.com/en-au/help/2023835/certificate-thumbprint-displayed-in-mmc-certificate-snap-in-has-extra

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12542a36-9b14-c85d-6f6e-15ab6666ccc7
* Version Independent ID: 177a81a7-dfeb-97c0-e66c-4bb715f56682
* Content: [Walkthrough: Configuring Web Services to Use SSL (SOAP and OData) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--configuring-web-services-to-use-ssl--soap-and-odata-#Importing)
* Content Source: [dynamics-nav/Walkthrough--Configuring-Web-Services-to-Use-SSL--SOAP-and-OData-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Configuring-Web-Services-to-Use-SSL--SOAP-and-OData-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! We have updated the content and the changes will available soon, the next time we publish.
