### ISSUE TITLE
Missing [test] tag on TestingRecords procedure

### ISSUE THREAD

**Issue by LauraNicolas** [MicrosoftDocs/dynamics365smb-devitpro-pb#1282]
The example on the documentation is not complete.

The procedure *TestingRecords* is missing the following tags:
   [Test]
   [HandlerFunctions('RemittanceAdviceJournalRequestPageHandler')]

Salut!
Laura Nicolàs
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a986f99e-5a44-7759-d893-fe9f5e45345a
* Version Independent ID: 347e8c25-eb22-b75a-f390-c4118f47ee5d
* Content: [Testing Reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-testing-reports)
* Content Source: [dev-itpro/developer/devenv-testing-reports.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-testing-reports.md)
* Service: **dynamics365-business-central**
* GitHub Login: @ailie13
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. That's right, it will be fixed with the next refresh.
