### ISSUE TITLE
Maximize button?

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#1284]
The documentation states : 
_When a page contains a lot of content, it is possible for the user to increase the dialog size with the maximize button._

However, I can't find any 'maximize' button to increase the '(Confirmation)dialog' size? Please clarify / update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f987e0c-ba34-f91e-dffc-a156ced6c02d
* Version Independent ID: abb31fda-847c-4204-ad1f-0767a4b69e9a
* Content: [Page Types and Layouts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-types-and-layouts)
* Content Source: [dev-itpro/developer/devenv-page-types-and-layouts.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-types-and-layouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jacobwj
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you should be able to see the Maximize button on dialogs, such as this one:
![image](https://user-images.githubusercontent.com/12556556/86454903-37250e80-bd20-11ea-8e59-f7ac56cd8c29.png)
But you might have an older version that doesn't have this feature. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
One additional comment; the dialogs created from the ConfirmationDialog and StandardDialog pagetypes are not currently providing a Maximize button. This could also be the issue. And the limitation will be added to the topic and pushed with the next refresh of the docs. Thanks.
