### ISSUE TITLE
Link to Dynamics 365 Business Central App Monetization whitepaper broken

### ISSUE THREAD

**Issue by louagej** [MicrosoftDocs/dynamics365smb-devitpro-pb#1285]
Hi,

The link towards [Dynamics 365 Business Central App Monetization whitepaper](https://mbspartner.microsoft.com/secure/coursematerials/D365/Standalone/Dynamics_365_Business_Central_App_Monetization_Demo_Guide.pdf)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba60e8ce-4313-a3eb-0ada-d81c240659c1
* Version Independent ID: 7ac62b7a-02fe-efc3-cf55-67335c94c303
* Content: [Development of a Localization Solution - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-develop-localization#monetization)
* Content Source: [dev-itpro/developer/readiness/readiness-develop-localization.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-develop-localization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by edupont04** [comment]
Thank you for your feedback! The link will be removed in the next doc update. When the team that owns this whitepaper have published it to a new location, we will add the new link to this page.
