### ISSUE TITLE
AL Development Object Ranges - require Licensing information

### ISSUE THREAD

**Issue by theo-stock** [MicrosoftDocs/dynamics365smb-devitpro-pb#1286]
Dear BC documentation team,
Thanks for the great documentation - getting better all the time !

Please could you add information relating to licensing for each Object Range as it relates to 
1. SaaS
2. Hosted on Azure IaaS
3. Hosted by the Partner
4. On-premise

Or perhaps it is only determined by the BC License Type:
1. Cloud Subscription
2. On-Premise
3. Perpetual (NAV 20xx)

Hope that does not make it too complicated, Or perhaps a URL to the source of this licensing information?

Best regards,
Theo Stock

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98387b95-ce70-594b-b0e1-36ef1b5a6fb6
* Version Independent ID: 8a8d3822-49c4-1422-e046-0d7c9726c9b6
* Content: [Object Ranges - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-object-ranges)
* Content Source: [dev-itpro/developer/devenv-object-ranges.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-object-ranges.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. Much appreciated! We will refresh this topic with a link to the [licensing guide](https://go.microsoft.com/fwlink/?LinkId=871590&clcid=0x409) of May 2020, which is the most current information available. Thanks again.
