### ISSUE TITLE
Could you provide the corresponding ObjectType (number) with the object name?

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1287]
Could you list in the documentation which Object Type we should use for a codeunit, a table, a tableextension and so on...

```
<?xml version="1.0" encoding="utf-8"?>
<PermissionSets>
  <PermissionSet RoleID="MyRole" RoleName="MyRole">
    <Permission>
      <ObjectID>50000</ObjectID>
      <ObjectType>0</ObjectType>
      <ReadPermission>1</ReadPermission>
      <InsertPermission>1</InsertPermission>
      <ModifyPermission>1</ModifyPermission>
      <DeletePermission>1</DeletePermission>
      <ExecutePermission>0</ExecutePermission>
      <SecurityFilter />
    </Permission>

...

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba62be20-de4f-6d05-ae77-b10380c3dba3
* Version Independent ID: 7de9447f-27b1-5265-0663-1d51bb00949c
* Content: [Exporting Permission Sets - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-permission-sets)
* Content Source: [dev-itpro/developer/devenv-export-permission-sets.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-export-permission-sets.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be added to the topic and available with the next doc refresh. Thanks!
