### ISSUE TITLE
Where is page with info for BC 16.3 release notes?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-devitpro-pb#1288]
Hello,
Business Central, version 16.3 is released few days ago and is on production for new environments etc.

Please create / update documentation page with 16.3 version as soon as possible, so users, partners and MS support have materials for correctly working with information on changes.

Thank you,
Kind regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9b5ce2-1cf9-3cf5-6233-4f272e072202
* Version Independent ID: 860598ee-65ab-350e-b7d0-df82ac49db65
* Content: [Update 16.2 for Microsoft Dynamics 365 Business Central 2020 Release Wave 1 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/whatsnew/whatsnew-update-16-2)
* Content Source: [dev-itpro/whatsnew/whatsnew-update-16-2.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/whatsnew/whatsnew-update-16-2.md)
* Service: **dynamics365-business-central**
* GitHub Login: @ManuelaHochstrasser
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the Minor update 16.3 topic can be found here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/whatsnew/whatsnew-update-16-3. Thanks.
