### ISSUE TITLE
Simplify the ACL

### ISSUE THREAD

**Issue by peterneave** [MicrosoftDocs/dynamics365smb-devitpro-pb#129]
I had no luck with "Configuring the Access Control List and the Web Services Ports for SSL" https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--configuring-web-services-to-use-ssl--soap-and-odata-#ACL . Using the command line seemed more complicated when I could achieve the same result with the GUI Admin Console instead.

I kept getting an error "SSL cannot be enabled when the certificate is not present". Found the solution by reading https://forum.mibuso.com/discussion/65657/ssl-cannot-be-enabled-when-the-certificate-is-not-present . Dave_Cintron mentions including the certificate thumbnail in the General Section.

This section could be replaced with
For your navision instance:
1) Paste your Certificate Thumbprint in the General Section
2) In OData/Soap section, click Enable SSL and input the OData Base Url to be the domain for the certificate. (ie if your certificate was for https://nav.example.com then use nav.example.com )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12542a36-9b14-c85d-6f6e-15ab6666ccc7
* Version Independent ID: 177a81a7-dfeb-97c0-e66c-4bb715f56682
* Content: [Walkthrough: Configuring Web Services to Use SSL (SOAP and OData) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--configuring-web-services-to-use-ssl--soap-and-odata-#ACL)
* Content Source: [dynamics-nav/Walkthrough--Configuring-Web-Services-to-Use-SSL--SOAP-and-OData-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Configuring-Web-Services-to-Use-SSL--SOAP-and-OData-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, thanks for the feedback. The subject article is out-dated. We have updated the article [How to: Implement Security Certificates in a Production Environment](https://docs.microsoft.com/en-us/dynamics-nav/How-to--Implement-Security-Certificates-in-a-Production-Environment), which will act as the replacement. This change will be available soon. Thanks again
