### ISSUE TITLE
Cloud Migration Manager [v1.6.2] Company Selection

### ISSUE THREAD

**Issue by KTL-KSweeney** [MicrosoftDocs/dynamics365smb-devitpro-pb#1290]
In version 1.6.2, there is no  **Select Companies to Migrate** option in the **Cloud Migration Management** list page (4003). This option exists solely within the Assisted Setup, **Set up Cloud Migration**.

Company selection only appears after waiting a long period of time (5+ minutes) for the MS Integration to query the DYNAMICS based on the SQL Connection String and integration runtime.

If users fail to wait for the assisted setup to populate the companies, then users will see an error on the **Cloud Migration Management** page that no company has been selected for migration with no easy option to select companies outside of the slow **Set up Cloud Migration** utility.

D365BC Information:
Version: US Business Central 16.2 (Platform 16.0.13440.14360 + Application 16.2.13509.13619)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8064280-eae4-9181-8ef2-c591fd357f7d
* Version Independent ID: 952f5564-d7dc-4124-fe6f-724a00beddd2
* Content: [Manage the cloud migration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/migration-management)
* Content Source: [dev-itpro/administration/migration-management.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/migration-management.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
