### ISSUE TITLE
Processing report is showing: 'Report is being rendered'

### ISSUE THREAD

**Issue by MaartenGerritsen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1291]
In a report with the following properties:
ProcessingOnly = true;
ShowPrintStatus = false;
there is still a window shown saying: 

Working on it...
The report is being rendered. This can take a while, depending on the number of rows that have been generated.

![image](https://user-images.githubusercontent.com/25688441/86739274-0d2c5e80-c036-11ea-8d4a-5e7b5a225a16.png)

unless an own dialog is programmed, like:
Window.Open('test #1#############');
Window.Update(1, i);
Window.Close;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42798cd-f73f-25cf-9424-91f88894d19b
* Version Independent ID: f0ba44e4-9d57-c985-7e1f-516b3d593e8d
* Content: [ShowPrintStatus Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-showprintstatus-property)
* Content Source: [dev-itpro/developer/properties/devenv-showprintstatus-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-showprintstatus-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
