### ISSUE TITLE
Camera not found on Webclient on a Smartphone

### ISSUE THREAD

**Issue by MarkusWinBI** [MicrosoftDocs/dynamics365smb-devitpro-pb#1293]
Following this document

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-implement-camera-al

I implemented a camera usage, finding the camera properly when using the phone client. As it is a very very limited client (no Subpages etc.) I wanted the customer use the webclient within the phone. Sadly the camera is not found in webclient on phone.

Is there any solution for this?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. If you want to suggest a product feature, please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central). Thanks

**Comment by MarkusWinBI** [comment]
@SusanneWindfeldPedersen 
Hi Susanne, 
in the documentation there is written that you can implement the camera on webclient and on phone / tablet app. This is not true. :-)
The implementation on web client is a potential new feature on bc 17, so the documentation is not correct. ;-)
