### ISSUE TITLE
Missing Application Areas

### ISSUE THREAD

**Issue by StanislawStempin** [MicrosoftDocs/dynamics365smb-devitpro-pb#13]
Please see https://github.com/Microsoft/AL/issues/1996#issuecomment-380746654

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0035ebd9-2a88-4293-83c4-30b3ee5a69ea
* Version Independent ID: f8716731-3439-dfdb-0bef-489aa515a7dc
* Content: [Page Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-object)
* Content Source: [dev-itpro/developer/devenv-page-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The topic has been updated and will be available with the next refresh of the docs.
