### ISSUE TITLE
How to define variables

### ISSUE THREAD

**Issue by renebrummel** [MicrosoftDocs/dynamics365smb-devitpro-pb#130]
Perhaps an idea to also demonstrate how to declare array variables in AL. The documentation speaks of dimension properties which is C/Side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f69b1cd4-9800-ac85-3f9d-3f70b0182f1b
* Version Independent ID: ef290221-1264-d52a-df84-9b43dc91694e
* Content: [Dimensions Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-dimensions-property)
* Content Source: [dev-itpro/developer/properties/devenv-dimensions-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-dimensions-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi! Thank you for the feedback. We will have examples for this with one of our next refreshes.
