### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1300]
The following example illustrates an XML element that has the ExtendedFormat set to false: The following example illustrates the same XML with the ExtendedFormat set to true:

There are no examples.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, can you please add information about the topic that this issue is filed for - that seems to have disappeared. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
