### ISSUE TITLE
An example here would be very helpful

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1301]
The resultant file can be used in Word as a custom XML part.

The topic shows how to create the WordPart xml file. It would be really helpful if there was then sample code or instructions about how to actually incorporate the xm into a Word document custom xml file.

**Comment by SusanneWindfeldPedersen** [comment]
Please add information about the topic that this issue is filed for. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this as more detail is needed.
