### ISSUE TITLE
BC16.2 page action - run object

### ISSUE THREAD

**Issue by matthewmartin-nvg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1302]
There is no longer a "PushAction" property on a page action, and if you set the "RunObject" property then the action does not display.
So please either restore the "PushAction" property or make the "RunObject" work without it.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
