### ISSUE TITLE
Signature format missing for handler function

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1303]
Where the NAV topic https://docs.microsoft.com/en-us/dynamics-nav/how-to--create-handler-functions?source=docs clarly states the signature of each type of uihandler, this topic do not discuss them at all.  think thi is a omission. So, please add them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 941d8e77-be5a-ba5f-8e97-1099abfafbb8
* Version Independent ID: eab11fdf-d298-57e1-bd5c-802ea715d669
* Content: [Creating Handler Methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-handler-methods)
* Content Source: [dev-itpro/developer/devenv-creating-handler-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-creating-handler-methods.md)
* Service: **dynamics365-business-central**
* Product: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The signature for each handler method has been added to the topic, and it will be available with the next refresh.
