### ISSUE TITLE
BC16.2 page action - run object property does not work

### ISSUE THREAD

**Issue by matthewmartin-nvg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1304]
There is no longer a "PushAction" property on a page action, and if you set the "RunObject" property then the action does not display.
So please either restore the "PushAction" property or make the "RunObject" work without it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dec21678-8db3-a288-43b3-fa34035809b8
* Version Independent ID: e9714314-893c-7a1c-8c38-5373826931cc
* Content: [RunObject Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-runobject-property)
* Content Source: [dev-itpro/developer/properties/devenv-runobject-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-runobject-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
