### ISSUE TITLE
Page action no longer works when using "RunObject" property.

### ISSUE THREAD

**Issue by matthewmartin-nvg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1307]
BC16.2 - According to "https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-runobject-property": first select RunObject in the PushAction property.

This is impossible since the "PushAction" property is no longer there!
So please either enable the "RunObject" property to work by itself, and update the documentation, or restore the "PushAction" property.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the PushAction property seems to have gone a long time ago. The RunObject property should be working on it's own. We'll update the topic to reflect this. Thanks.
