### ISSUE TITLE
NAVDataUpgrade is stuck at 55,56 %

### ISSUE THREAD

**Issue by krregg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1308]
I am following steps for upgrading Business Central 15.1 to 16.0 and in the post-upgrade task, I try to run `Start-NAVDataUpgrade -ServerInstance $serverInstance -Force` and after when I check the progress I can see that process is somehow stuck regarding progress bar. 

<img src="https://i.ibb.co/xYZr4x0/code.png" alt="code" border="0">

If I open Web Client and I go on Help page I can see that the Application Number has changed to 16.0.38071.0. 

<img src="https://i.ibb.co/1L7Z78J/number.png" alt="number" border="0">

Everything looks pretty much normal except few warning in Event Viewer, saying: 

`Message Unable to find defining app group for a table with ID 2000000120, when initializing query from app group 2.`

Is this normal that the Upgrade process gets stuck? I remember something similar to version 14. Would the restart of the instance help in that case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a99ad4b-431a-d2d6-b11f-bb467e490387
* Version Independent ID: a310818b-2861-9a15-c01d-27ea599bb22b
* Content: [Upgrading Version 15 Base Application to Version 16 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
