### ISSUE TITLE
Business Central API - Authentication with Client ID and Secret (No Prompt)

### ISSUE THREAD

**Issue by aherrick** [MicrosoftDocs/dynamics365smb-devitpro-pb#131]
Is it possible to get a valid token from the Business Central API with just the App ID and Secret? Without involving a user prompt/login?

We need to pull data from Business Central without having a user authenticating. Obviously we can't pull from the API in a secondary app and have a user re-login every hour.

In testing, we've found it to not be possible.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#setting-up-azure-active-directory-(aad)-based-authentication

https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code

http://paulryan.com.au/2017/oauth-on-behalf-of-flow-adal/

Are there additional resources which show how to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#setting-up-azure-active-directory-(aad)-based-authentication)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We currently only have the published docs, I suggest that you ask support. Thanks.

**Comment by wolterOnEntocare** [comment]
I asked this same question to support.
https://community.dynamics.com/business/f/758/p/304644/879753#879753

Their answer is that Basic Auth CAN be used in prdoction! Contrary to what's stated on this page !

Basic Auth even seems to be necessary in case you do not want your connect app to login on behalf of a human user but you need it to connect just with its own login. Like in aherick 's use case, and mine.

**Comment by aherrick** [comment]
We've been using the basic Auth in testing without issue for a few months now. Glad it can work in Prod too.

**Comment by TclasenITVT** [comment]
@SusanneWindfeldPedersen Can we get an offical statement regarding server-to-server authentication scenarios? I personally feel uneasy just using basic auth when the docs state explicitly that it is not to be used in production. Could you bring up with the Team to maybe support the OAuth2 client_credentials Flow? Automaticaly creating a 'ServiceUser' Identitfied by the application/client id?

**Comment by saboorawan** [comment]
Is this issue resolved ? I need a machine to machine authentication. without user input.
