### ISSUE TITLE
Check settings to create rdl layout

### ISSUE THREAD

**Issue by stefanoPrimo** [MicrosoftDocs/dynamics365smb-devitpro-pb#1310]
I will specify also that if the rdl layout is not created after the build of the app, the settings need to be modified like that:

```
    "al.compilationOptions": {
        "generateReportLayout": true
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b7f14d-d6ca-7248-7621-47669905bea0
* Version Independent ID: c1e289a5-c3cc-a748-4f59-6a56001c4b8d
* Content: [Creating an RDL Layout Report - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-howto-rdl-report-layout)
* Content Source: [dev-itpro/developer/devenv-howto-rdl-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-howto-rdl-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, that's a good point. We will add this to the topic with the next doc refresh.
