### ISSUE TITLE
Need example Please

### ISSUE THREAD

**Issue by ara3n** [MicrosoftDocs/dynamics365smb-devitpro-pb#1311]
Hello.  There is no example on how to use these in BC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aef185c-794a-dd4d-e226-8678a9087c04
* Version Independent ID: 8db38723-0f86-bd54-8071-fe7e496b9cc9
* Content: [MediaSet Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/mediaset/mediaset-data-type)
* Content Source: [dev-itpro/developer/methods-auto/mediaset/mediaset-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/mediaset/mediaset-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, you can find examples on how to use these methods in the articles linked from the **Method name** column of the table.
