### ISSUE TITLE
Great topic, but why not add a link to download page

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1312]
I really appreciate having these CU topics. But a major thing is failing: a direct link to the download page. It's a nuisance to get to that from these topics. If you really want to help us "out there", please add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7114290e-5b73-3f14-8f76-a14477a42196
* Version Independent ID: 494b506b-bd78-f010-b3d2-42907afa29ba
* Content: [Update 16.3 for Microsoft Dynamics 365 Business Central 2020 Release Wave 1 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/whatsnew/whatsnew-update-16-3?source=docs)
* Content Source: [dev-itpro/whatsnew/whatsnew-update-16-3.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/whatsnew/whatsnew-update-16-3.md)
* Service: **dynamics365-business-central**
* GitHub Login: @ManuelaHochstrasser
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - in the first link in each of these topics [Link to Hotfixes](https://support.microsoft.com/help/4533389) there's a link to the download page. But we can move that into the topic to make it easily accessible. Will fix this with 16.3 and refresh the topic. And then going forward. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, just a heads up. After internal feedback we've decided to remove the download link from this topic because it is a link to downloading on-premise versions and it was confusing when these update topics only are about online versions that automatically get rolled out. Hope for your understanding. Thanks.
