### ISSUE TITLE
Needs link to Worksheet design page

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1313]
First of all, thank you. This topic is excellent, screenshot with labels, lots of links, etc.

Near the bottom of the topic, is the following sentence:
If you want to design a page that includes controls in the content area other than a repeater, then try using a Worksheet page type instead.

It would be very helpful if some part of "using a Worksheet page" was a link to the same.

Have a great day!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f12e363e-38d7-f053-9266-d78e290e3fcf
* Version Independent ID: ed2e594c-a609-a5b9-708e-c87ee733568e
* Content: [Designing List Pages for Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-list-pages?tabs=structure#structure-1)
* Content Source: [dev-itpro/developer/devenv-designing-list-pages.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-designing-list-pages.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by blrobl** [comment]
Hi, thanks for tour feedback, the link will be added with the next refresh.

**Comment by j2associates** [comment]
Is there any way to know when the refresh will actually happen?

Thanks

**Comment by blrobl** [comment]
It will take place early next week.
