### ISSUE TITLE
Getting Error in Task 9

### ISSUE THREAD

**Issue by dbezzant** [MicrosoftDocs/dynamics365smb-devitpro-pb#1318]
Not sure if this is the right spot to ask questions, but I don't see anywhere else to do so.

Testing converting Custom fields and tables to BC160 (from BC140).
I am stuck on Task 9 - Publishing the empty versions of the Base and Ssytem Applications.

I get the following error: 
PS C:\WINDOWS\system32> Publish-NAVApp -ServerInstance $ServerInstance -Path "C:\DEV\UpgradePD\EmptyBase\Microsoft_Base Application_14.0.0.0.app" -SkipVerification
Publish-NAVApp : A package with name 'Application', and a version compatible with '14.0.0.0' could not be found.

Not sure what I am missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b2a8e-89a9-dda2-7d06-c433f2127044
* Version Independent ID: 4a968a4c-8ad7-8d9b-b966-b08daf4bda9a
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Does the app.json file for your empty Base Application include the "application" parameter? If so, this might be causing the problem.

**Comment by jswymer** [comment]
Hello, I hope you solved the problem. We've verified the steps for good measure. We will close this issue, but if you have more feedback on it, we'll be happy to reopen it. Thanks!
