### ISSUE TITLE
Update Documenation for Optional Value SkipFieldsNotMatchingType

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#1319]
The Documentation should be updated to reflect the following change

https://github.com/Microsoft/AL/issues/4265

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e39077c2-1259-3bd9-aa07-61a37785d24c
* Version Independent ID: fd613eac-8f85-f035-aea6-d7a245eec6a1
* Content: [TransferFields Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-transferfields-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-transferfields-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-transferfields-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. You can find the article about the **TransferFields Method** overload that takes the **SkipFieldsNotMatching** parameter [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-boolean-method).
