### ISSUE TITLE
Orphaned?

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1320]
Hi, 
this page looks orphaned, like it could be deleted?

**Comment by edupont04** [comment]
Please add information about the topic that this issue is filed for. Thanks.

**Comment by NKarolak** [comment]
Sorry Eva, I did not see that the information had not been added (as usual).
Since I cannot remember the page anymore (it was part of a search result that I can remember neither), I'll close the current case.

**Comment by edupont04** [comment]
Thanks, Natalie! It would appear that the feedback mechanism has had a couple of glitsches, which is why the information got lost.

**Comment by NKarolak** [comment]
I've found the page again :-)
Please compare it with https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b5ed4b-07ce-a1ea-3d84-188b5eb4de2b
* Version Independent ID: c249ea03-2ce7-6607-b19e-8e26f2333a40
* Content: [Step 3 - How to Develop Your App - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-develop-your-app)
* Content Source: [dev-itpro/developer/readiness/readiness-develop-your-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-develop-your-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this - the topic was actually supposed to be redirected because, like you say, it is redundant, but something must've gone wrong with the PR. We'll get this fixed with the next doc refresh. Thanks!
