### ISSUE TITLE
Method parameters are separated with semicolon

### ISSUE THREAD

**Issue by BandaruSrinivasulu** [MicrosoftDocs/dynamics365smb-devitpro-pb#1323]
"the parameters are separated by commas" this is written in the document. but parameters are separated by Semicolon, not by commas.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-methods#parameters-optional

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f33c0c-cd0d-28b2-d09d-5f17f93223b0
* Version Independent ID: d74d84ee-6fde-7f73-e2c2-50a3992c2fb8
* Content: [Working with AL methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-methods)
* Content Source: [dev-itpro/developer/devenv-al-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by BandaruSrinivasulu** [comment]
Great
