### ISSUE TITLE
Typo on page "Duration-data-type"

### ISSUE THREAD

**Issue by ph-jo** [MicrosoftDocs/dynamics365smb-devitpro-pb#1326]
Typo in code-example, there's a "1" at the second datetime assignment
is: "DateTime1"
should be: "DateTime"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebf589b9-2295-565c-7af9-03a75e08fa7a
* Version Independent ID: 9f371e61-cf4a-2ba7-bb06-15d9568607a7
* Content: [Duration Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/duration/duration-data-type)
* Content Source: [dev-itpro/developer/methods-auto/duration/duration-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/duration/duration-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been fixed and the update will be published soon.
