### ISSUE TITLE
Broken links in section "Remarks"

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1328]
Please update all links in the "Remarks" section. All links are forwarded to https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/library

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 530e38d5-5d31-d271-4e95-a3344d5a9ec0
* Version Independent ID: 688d369c-d36d-f551-21db-3846a93d4296
* Content: [Run Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-run--method)
* Content Source: [dev-itpro/developer/methods-auto/page/page-run--method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/page/page-run--method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The links have been fixed and an update will be published soon.
