### ISSUE TITLE
Please add a Clear() method to List Data Type

### ISSUE THREAD

**Issue by tbebekis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1329]
There is no Clear() method in the List Data Type.
Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c760a1-0ba5-814b-94bf-c50008364769
* Version Independent ID: 235f987b-1062-26ba-81a7-b72ff35c099b
* Content: [List Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/list/list-data-type)
* Content Source: [dev-itpro/developer/methods-auto/list/list-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/list/list-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
