### ISSUE TITLE
Update instructions to VS 2017

### ISSUE THREAD

**Issue by soerenBoisen** [MicrosoftDocs/dynamics365smb-devitpro-pb#133]
In Visual Studio 2017 the "Add Service Reference" option is gone. You now have to install the Microsoft extension "OData Connected Service" from the VS marketplace and use "Add Connected Service". Please update the instructions, so everyone trying to follow the example don't have to Google this and find this SO issue: https://stackoverflow.com/questions/43981604/how-to-update-odata-wcf-in-visual-studio-2017/48470007

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ab2d51-62c3-fa9a-7a3f-556097ef3c43
* Version Independent ID: a93c5d06-2ca9-f8d5-7b49-b69429e7f613
* Content: [Walkthrough: Creating and Interacting with a Page Web Service (OData) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--creating-and-interacting-with-a-page-web-service--odata-)
* Content Source: [dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by DavideVD** [comment]
I agree with Soeren. Please update instructions. It will be very useful

**Comment by jswymer** [comment]
Hello, the article has been updated with instructions about using the OData Connected Service. The updated article will be published soon. Thanks for the feedback!
