### ISSUE TITLE
Start Admin Shell 

### ISSUE THREAD

**Issue by LauraNicolas** [MicrosoftDocs/dynamics365smb-devitpro-pb#1330]
Hello,

On task 2.2 it says:
"Start Business Central Administration Shell for **version 16** as an administrator."

It should say **version 15**

Salut!
Laura Nicolàs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a99ad4b-431a-d2d6-b11f-bb467e490387
* Version Independent ID: a310818b-2861-9a15-c01d-27ea599bb22b
* Content: [Upgrading Version 15 Base Application to Version 16 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been fixed and the updated article will be published soon.
