### ISSUE TITLE
Missing file name requirement

### ISSUE THREAD

**Issue by TheDenSter** [MicrosoftDocs/dynamics365smb-devitpro-pb#1331]
Hi there

When uploading my logo files to Commercial Marketplace, it gave me an error message "The filename "MyApp logo 216x216.png" is invalid. Please rename to use only alphanumeric characters, dashes (-), or underscores"

Please add the file name requirement to the documentation

Thanks and have a wonderful day
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ed17a-40aa-2294-ff87-54812e7db96a
* Version Independent ID: 179288ab-c34d-ba7f-101b-a1bc8d89b840
* Content: [Marketing Artifacts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-g-marketingartifacts-logo-video-docs-screenshots)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-g-marketingartifacts-logo-video-docs-screenshots.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-checklist-g-marketingartifacts-logo-video-docs-screenshots.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-liober
* Microsoft Alias: **v-liober**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your contribution. Your PR is merged and the docs will be refreshed soon. thanks.
