### ISSUE TITLE
Wrong Page Navigation

### ISSUE THREAD

**Issue by BandaruSrinivasulu** [MicrosoftDocs/dynamics365smb-devitpro-pb#1332]
When we click on Lock Table Method, it is navigating to data types page. It should navigate to Lock Table Method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd3a4f27-9380-2b95-f9f9-6d7c97da03e0
* Version Independent ID: 1698b06c-6eed-e114-4de8-8ab46d4f7234
* Content: [Essential AL Methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-essential-al-methods)
* Content Source: [dev-itpro/developer/devenv-essential-al-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-essential-al-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The link has been fixed and the update will be published soon.

**Comment by BandaruSrinivasulu** [comment]
Great
