### ISSUE TITLE
Wrong instructions: must use async

### ISSUE THREAD

**Issue by soerenBoisen** [MicrosoftDocs/dynamics365smb-devitpro-pb#134]
When running the sample code above for our own Nav test instance, I receive the following error: 
"System.NotSupportedException: 'This target framework does not enable you to directly enumerate over a data service query. This is because enumeration automatically sends a synchronous request to the data service. Because this framework only supports asynchronous operations, you must instead call the BeginExecute and EndExecute methods to obtain a query result that supports enumeration.'"

It seems that we can no longer directly enumerate OData queries. Please update the instructions so they will work for current versions of WCF framework / OData extension / Visual Studio version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ab2d51-62c3-fa9a-7a3f-556097ef3c43
* Version Independent ID: a93c5d06-2ca9-f8d5-7b49-b69429e7f613
* Content: [Walkthrough: Creating and Interacting with a Page Web Service (OData) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--creating-and-interacting-with-a-page-web-service--odata-)
* Content Source: [dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue as it will be covered in the work for Github issue #133. Thanks.
