### ISSUE TITLE
The example in the "Find methods" section is not for the Find() method, but the SetCurrentKey() and SetRange().

### ISSUE THREAD

**Issue by tbebekis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1340]
It says: "The OnDelete trigger of the Item Variant table includes the following code that illustrates using Find"

...but the example that follows the above line does not illustrate using Find().

```
SalesOrderLine.SetCurrentKey(Type, "No.");
SalesOrderLine.SetRange(Type, SalesOrderLine.Type::Item);
SalesOrderLine.SetRange("No.", "Item No.");
SalesOrderLine.SetRange("Variant Code", Code);
if not SalesOrderLine.IsEmpty then
    Error(Text001, Code, SalesOrderLine.TableCaption);  
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8ab790c-fa2b-0e9f-5ed3-a7b81e2bc923
* Version Independent ID: 86ebf4c4-bb01-2976-8903-7f95e4ed4914
* Content: [Get, Find, and Next Methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-find-and-next-methods)
* Content Source: [dev-itpro/developer/devenv-get-find-and-next-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-get-find-and-next-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. That's true, it will be fixed with the next refresh.
