### ISSUE TITLE
Content does not match the title

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1341]
For me, it looks like the [latest content change](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/commit/e90d3e877e34ad4a9168267e7dcb962c2be38383#diff-cf0c3a56ed81941cdceded3dd628c855) has been applied to the wrong article.

The content somehow applies to this article (part) instead: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#formatting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4037b75d-704e-4990-0073-f3f4238e3e53
* Version Independent ID: 7f0a3d8d-a626-0a14-fb03-09846f84f863
* Content: [An affix is required for procedures defined in extension objects. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0079-extensionproceduresmusthaveaffix)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop-as0079-extensionproceduresmusthaveaffix.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop-as0079-extensionproceduresmusthaveaffix.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks a lot for catching this - you're right - the Remarks section belongs to the [CodeCop Rule AA0241](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0241-uselowercaseforlanguagekeywords) and we'll fix it with the next refresh of the docs. Thanks again!
