### ISSUE TITLE
Awkward sentence

### ISSUE THREAD

**Issue by gary-PSSI** [MicrosoftDocs/dynamics365smb-devitpro-pb#1342]
Whether the extensions that are dependent on the Application compile and work is up to the partner redefining the application to ensure by not introducing breaking changes.

this sentence is very awkward and needs to be reworked

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c934418-1448-eb40-9d9a-11c8c435f491
* Version Independent ID: a788c5c0-0e20-14f8-d4f4-a5e0eb646589
* Content: [The Microsoft_Application.app File - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-application-app-file)
* Content Source: [dev-itpro/developer/devenv-application-app-file.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-application-app-file.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The topic will be updated to hopefully be more clear with the next doc refresh.
