### ISSUE TITLE
When/Where to the Reference Assemblies folders get created?

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1346]
At Step 
> 8 Configure User Settings or Workspace Settings to include the following paths for the "al.assemblyProbingPaths" setting.

```
"al.assemblyProbingPaths": [
    "C:\\Program Files\\Microsoft Dynamics 365 Business Central\\160",
    "C:\\Program Files (x86)\\Microsoft Dynamics 365 Business Central\\160",
    "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.7.2",
    "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\WindowsPowerShell"
],
```
There are wo (2) folders noted:
1. "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.7.2"
2. "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\WindowsPowerShell".3. 
They don't exist on my machine after I have installed BC16 CU03.  Is there an installation step required?

![image](https://user-images.githubusercontent.com/4333956/88937849-94a76f00-d27c-11ea-995a-b1f0d574e609.png)

![image](https://user-images.githubusercontent.com/4333956/88937442-0f23bf00-d27c-11ea-9691-3a167e821ac8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146303e1-568e-7a5c-ea4f-b40afbc503fc
* Version Independent ID: 53de4696-feb9-ff31-160e-a858a0be3d40
* Content: [Publishing a Code-Customized Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-publish-code-customization)
* Content Source: [dev-itpro/developer/devenv-publish-code-customization.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-publish-code-customization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the .NET framework version specified in the probing path in this topic is tested with version 16, so if you have issues getting it to work, I suggest that you update your .NET framework to version 4.7.2 and likewise update to the later version of Windows PowerShell. Hope this answers your question. Thanks.

**Comment by GreatScott000** [comment]
No this does NOT resolve my issue.

I have .NET Framework 4.8 installed on my computer.  The Reference Assemblies folder is not created for 4.7.2.  When/how does it get created.  If 4.7.2 was NOT installed then per the page, the installer would have installed it so what is missing? 

How do I get this folder and its contents created?

Per this article [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) the image below indicates 4.8 is installed.

![image](https://user-images.githubusercontent.com/4333956/89883628-508f6500-dbc0-11ea-84c9-edafbdd30b92.png)

As for PowerShell I believe 5.1 is the current version.
![image](https://user-images.githubusercontent.com/4333956/89883987-ce537080-dbc0-11ea-85e5-29c125a314c9.png)
