### ISSUE TITLE
Businness central cloud Migration error 

### ISSUE THREAD

**Issue by FrancCastle** [MicrosoftDocs/dynamics365smb-devitpro-pb#1347]
Hi, I'm getting this error when runthe migration , i did a simple test betwen Bc15  cu 13 standart no modifications to my business central coud 

Description | Name | null | Version | Logo
-- | -- | -- | -- | --
Microsoft | Business Central Cloud Migration - Previous Release (ES) |   | v. 16.3.14085.14947

The error occurred on the "Sink" side. 'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=A database operation failed. Please search error to get more details.,Source=Microsoft.DataTransfer.ClientLibrary,''Type=System.InvalidOperationException,Message=Value of specified type String of data source cannot be converted to bittype of specified destination column. ,Source=System.Data,''Type=System.FormatException,Message=Error converting String parameter value to Boolean.Source=System.Data,''Type=System.FormatException,Message=Cannot recognize the string as a valid boolean type.,Source=mscorlib,'

there`s an Api to see which column is causing the error?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. Please use your usual support channel to ask or file a bug. Thanks.
