### ISSUE TITLE
Error in the SQL script

### ISSUE THREAD

**Issue by rogerlarssoncgi** [MicrosoftDocs/dynamics365smb-devitpro-pb#135]
The two last statements must be executed in the master database.
The script should be update as follows..

USE [master]  
GO  
CREATE LOGIN [domain\accountname] FROM WINDOWS   
CREATE USER [domain\accountname] FOR LOGIN [domain\accountname]   
GRANT SELECT ON [master].[dbo].[$ndo$srvproperty] TO [domain\accountname]  
ALTER SERVER ROLE [dbcreator] ADD MEMBER [domain\accountname]

GO  
USE [Microsoft Dynamics NAV Database]  
GO  
CREATE USER [domain\accountname] FOR LOGIN [domain\accountname]  
ALTER ROLE [db_owner] ADD MEMBER [domain\accountname]  
GRANT VIEW DATABASE STATE TO [domain\accountname]  

USE [master]  
GO 
GRANT VIEW SERVER STATE TO [domain\accountname]
GRANT ALTER ANY EVENT SESSION TO [domain\accountname]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b92a74ce-0daa-5c14-a5c4-81ae7e7c6813
* Version Independent ID: 30483825-69a7-02d4-d67a-f64053a8c5b7
* Content: [Provisioning the Microsoft Dynamics NAV Server Account - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/provisioning-the-microsoft-dynamics-nav-server-account#DUA)
* Content Source: [dynamics-nav/Provisioning-the-Microsoft-Dynamics-NAV-Server-Account.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Provisioning-the-Microsoft-Dynamics-NAV-Server-Account.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The statements have been added to the script and the updated article will be published soon.
