### ISSUE TITLE
Upgrading to V16

### ISSUE THREAD

**Issue by andrewbackway** [MicrosoftDocs/dynamics365smb-devitpro-pb#1350]
In the help, https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v15-v16

it lists, "This process won't upgrade the application to the latest version."

How do we upgrade to the latest version, looks to be steps missing.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc5f87b-22d2-5653-e646-bb49ae487055
* Version Independent ID: 86a7dfa4-402b-5166-1f24-3d0bdb062dfc
* Content: [Technical Upgrade from Version 15 to Version 16 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v15-v16)
* Content Source: [dev-itpro/upgrade/upgrade-technical-upgrade-v15-v16.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-technical-upgrade-v15-v16.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, 

Does your BC 15 use the Microsoft Base Application? If so, then follow the steps in [Upgrading Version 15 Base Application to Version 16](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v15-to-v16).

**Comment by andrewbackway** [comment]
Thanks for the quick reply, very much appreciated, giving that a go now.

**Comment by danicarudio** [comment]
Hi,

Andrew and I are working on this. Managed to get to Version 16.0 but noticed that the old extensions are still in the list. Is this normal?
![BC old extensions](https://user-images.githubusercontent.com/69191565/89271785-c8650900-d66f-11ea-87f8-c52bbdfb55d8.jpg)

Thanks!

**Comment by jswymer** [comment]
Yes, This is normal. The start-navdataupgrade installs the new versions. But the old versions are still published on the server instance. so they show as not installed.  To remove them, you'd have to run the Unpublish-NAVApp - version [number].

**Comment by jswymer** [comment]
Hello, I hope your questions have been answered. If not, let us know and we'll reopen this issue. Thanks!
