### ISSUE TITLE
Control Add-In in PageType = HeadlinePart causes freeze

### ISSUE THREAD

**Issue by RobKirsten** [MicrosoftDocs/dynamics365smb-devitpro-pb#1351]
I am trying to add a control addin to the role center headline. The app compiles. However, opening/refreshing the role center page leads to loading freeze. 

```
controladdin "Demo"
{
    Scripts = 'JsScript/demo.js';
    StyleSheets = 'StyleSheet/StyleSheet.css';
    StartupScript = 'JsScript/Start.js';

    event Ready()

    procedure doSomething()
}
```
and 
```
page 50000 "My Page"
{
    // PageType = CardPart;
    PageType = HeadlinePart;
    layout
    {
        area(Content)
        {
            usercontrol(CtrlAddIn; CtrlAddIn)
            {
                ApplicationArea = All;

                trigger Ready()
                begin
                    CurrPage.CtrlAddIn.doSomething();
                end;
            }
        }
    }
}
```

The javascript function _doSomething_ renders some html. If the _PageType_ is _CardPart_ everything works and the controladdin is rendered into the first insights block.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This might be a product bug. Please use your usual support channel to file a bug. Thanks.
