### ISSUE TITLE
Link to Interfaces page directs to locked MS-only page

### ISSUE THREAD

**Issue by JuricaB** [MicrosoftDocs/dynamics365smb-devitpro-pb#1352]
[Enter feedback here]
Reference to Interfaces in AL page in Interface Objects section (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-best-price-calculations#interface-objects) points to https://review.docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-interfaces-in-al?branch=April-2020 instead of https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-interfaces-in-al

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32c26d28-1789-81d6-d3df-45cf91c09ef7
* Version Independent ID: 35bfccd5-c11f-a78f-e01c-bb95d0e1ee76
* Content: [Extending Price Calculations - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-best-price-calculations)
* Content Source: [dev-itpro/developer/devenv-extending-best-price-calculations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extending-best-price-calculations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been fixed and the updated article will be published soon.
