### ISSUE TITLE
word repeated twice

### ISSUE THREAD

**Issue by BandaruSrinivasulu** [MicrosoftDocs/dynamics365smb-devitpro-pb#1353]
the "versions" word repeated twice in the first note section
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f49ce81e-e0c2-c484-8ec3-e8e8a9012692
* Version Independent ID: 7bf2f01b-522b-f372-b3c9-1ca36e870818
* Content: [Encrypting Data in Dynamics 365 for Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-encrypting-data)
* Content Source: [dev-itpro/developer/devenv-encrypting-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-encrypting-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been fixed and the update will be published soon.
