### ISSUE TITLE
Two minor corrections for the "AL Control Statements" page

### ISSUE THREAD

**Issue by steveendow** [MicrosoftDocs/dynamics365smb-devitpro-pb#1354]
I found two small items on the "AL Control Statements" page, under "AL conditional statements".

**1. Under "If-then else statements", the syntax example shows:**

```
if <Condition> then  
  <Statement1>  
else  
  <Statement2>
```

Below the example, the text explains:  "The square brackets around else <Statement2> mean that this part of the statement is optional."  But in the example, the else <Statement2> does not have square brackets.  It seems as if square brackets should be present around the else lines?  A later syntax example does have the square brackets.

**2.  Under Case Statements, there is a Programming Conventions paragraph, which says:**

"When you use a case statement, indent the value sets by two character spaces."

This formatting convention does not seem to be accurate when using VS Code with AL as of August 2020.  If you attempt to use only two spaces, VS Code with the AL Language extension (with completely default settings) will automatically reformat the AL Case statement to indent each value set with 4-spaces (a tab).

![image](https://user-images.githubusercontent.com/11199908/89719145-29475680-d97a-11ea-867e-bb1c2436a2fe.png)

It seems like that recommendation should be changed to tab or 4 spaces, and the subsequent Example below should also be updated:

```
case Field of  
  Field::A:  
    begin  
     x := x + 1;  
     y := -y - 1;  
    end;  
  Field::B:  
    x := y;  
  Field::C,Field::D:  
    y := x;  
  else begin  
    y := x;  
    a := b;  
  end;  
end;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49792c3f-b5cc-d7bb-cb70-23609e64b09c
* Version Independent ID: 805fa013-f489-05bb-2465-e082a03a3a92
* Content: [AL Control Statements - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-control-statements#al-conditional-statements)
* Content Source: [dev-itpro/developer/devenv-al-control-statements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-control-statements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be fixed with the next refresh of the docs.
