### ISSUE TITLE
Wrong Item Numbers 

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1357]
The two articles linked here (on the right)
 ![image](https://user-images.githubusercontent.com/34504100/89792661-29d02080-db25-11ea-9328-f90a53dd9b3b.png)
do not share the sameor all the item numbers and content mentioned on the left side.
The [first link](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-d-supportedcountries-languages) covers items7 to 10,
the [second link](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-f-supportedproducts-keywords) covers items 11 to 13

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95478ad1-ca6c-1204-b752-3dceee6a9a05
* Version Independent ID: 36916ccc-04c5-63a3-35ee-ab5ddeb61137
* Content: [Marketing Validation Checklist - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-marketing)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-marketing.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-checklist-marketing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-liober
* Microsoft Alias: **v-liober**

**Comment by blrobl** [comment]
Hi, thanks for catching this, it will be fixed with the next refresh.
