### ISSUE TITLE
Question regarding file naming

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [MicrosoftDocs/dynamics365smb-devitpro-pb#1361]
Could you please clarify the best practice for naming the files - is the prefix/suffix is needed in the filename?
If I have prefix "XYZ" specified in the AppSourceCop.json and I'm creating "Sales Header" table extension what should the filename be? XYZSalesHeader.PageExtension.al or just SalesHeader.PageExtension.al?
The documentation states that it should be "MyPrefixSalesperson.PageExt.al" - this looks like the naming convention that was introduced after release of AL but it was changed later and now it's reverted - is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by IceOnly** [comment]
I think #1077 was the wrong descission.
It only needs a reference to AppSourceCop.json settings.

The MS default apps also ignores Suffix and Prefix in file names (one sample):
https://github.com/microsoft/ALAppExtensions/blob/master/Apps/DE/Elster/app/src/Codeunits/Management.Codeunit.al

File names with suffix/prefix makes the projects more unreadable.

Maybe @JesperSchulz can deliver a clear response from the developer team here.

**Comment by IceOnly** [comment]
Is it possible to get an answer here? This quetion is now over three months old.

The closed Issue #1495 asked the same.

The article for AA0215 refers to this article https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming

But the code cop rule still allows to remove the prefix/suffix from the filename. Is there any technical reason why we should add the prefix/suffix to the filename?

The guideline was only changed on the issue request from @JulianTillmann in Issue #1077:

> The CodeCop rule AA0125 Forces the Suffix or Prefix in the filename, here it's explicitely removed from the filename: <ObjectNameExcludingPrefix>.al

But the CodeCop Rule AA0215 never forced the suffix/preffix, it only wants the objectname in the filename. If the prefix/suffix is declared in the AppSourceCop.json a filename without prefix/suffix is no longer a warning in the code cop analyser.

**Comment by JesperSchulz** [comment]
Sorry, I didn't not monitor this repository! Let me see if I can dig out an answer for you :-) We've been back and forth on file naming. Need to get up to speed with the latest best practices on those.

**Comment by JesperSchulz** [comment]
I understand the confusion - the information on file names is not perfectly clear. Let's start with the facts: what you name your files, is entirely up to you. If you want to know about the rules in general you need to follow before submitting apps to AppSource, please check here: [aka.ms/checkbeforeyousubmit](http://aka.ms/checkbeforeyousubmit). That list does not mention anything about file names and file names hence don't need to follow any rules.

We do have best practices though and those can be checked by CodeCop. From what I can tell, CodeCop only suggests that the object name is part of the file name - which indeed is a good best practice. Whether you want to add any affix to the file name is up to you. That is not what our documentation says though, and we should adjust that.

I hope that clarifies things a little? You decide on the file names yourself. If you want to follow best practices, include object name in file name. Whether you want affixes in the files names, is your call. If you don't care about our best practices at all, feel free to disable CodeCop rule AA0215.

@SusanneWindfeldPedersen, could you update the docs?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback and discussion. This topic will be updated with the next doc refresh.
