### ISSUE TITLE
Deploying Business Central in a Two-Computer Topology

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [MicrosoftDocs/dynamics365smb-devitpro-pb#1362]
Hi
Is it correctly understood that in Two-Computer Topology that it is not supported to install Web server og Business Central Server on the same server and the database on a separate server? If so, why is it not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a875b48-aeb1-a11b-8a35-58d4c4a9f3e0
* Version Independent ID: ec0f7628-1c5c-f94e-7340-ad3461c21fec
* Content: [Web Server Components Deployment Scenarios - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/deployment-scenarios)
* Content Source: [dev-itpro/deployment/deployment-scenarios.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/deployment-scenarios.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

You can deploy install Web server and Business Central Server on the same server and the database on a separate server. You can install Web server, Business Central Server, and Database in any combination on multiple machines.

The documentation is a bit misleading. The article is written to a specific scenario where the web server is on one machine while the server and database are on another. The steps in the article might not match exactly the scenario you are talking about, but the scenario is supported. We'll try to make this clearer in the docs. Thanks for the feedback!

**Comment by jswymer** [comment]
We have added some information that will hopefully make this more clear. The update will be published soon. Thanks!
