### ISSUE TITLE
Missing documenation on SessionEventTablePurgeLookupPeriod setting

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1363]
You are missing documenation on about nav server setting: SessionEventTablePurgeLookupPeriod

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30dd402-c112-00be-9c66-4f8bd6a2184f
* Version Independent ID: 215be880-512c-a76b-5463-bfd1b349dd81
* Content: [Microsoft Dynamics 365 Business Central Server Configuration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-server-instance)
* Content Source: [dev-itpro/administration/configure-server-instance.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configure-server-instance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

The SessionEventTablePurgeLookupPeriod setting is tagged for internal use only, so it does not appear in the Administration tool or in the CustomSettings.config file for the server instance. This article doesn't describe internal settings. But we do realize that in some cases, these settings have to be modified. If you need information about this setting, please use your usual support channel. Thanks.

**Comment by gintuoklis** [comment]
I find it bizzar that we need to find out about these settings from [3rd party blogs ](https://demiliani.com/2018/03/26/nav-session-event-table-cleanup/) or customer support and it's not documented in official documentation. Even if internal please document, so we could know the format and meaning of it.

In addition to that, this property is mentioned in one of the examples on your documentation. See example 1 [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/get-navserverconfiguration?view=businesscentral-ps-16). And the worst is, that it comes with wrong format

**Comment by jswymer** [comment]
Hello,

We've updated this article with information about the **SessionEventTablePurgeLookupPeriod** setting. We hope this answers some questions. Thanks for the feedback.
