### ISSUE TITLE
Small typos in Code Example

### ISSUE THREAD

**Issue by Dimitris-Arabatzis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1366]
In the example codeunit::MyPublishingCodeunit2 should be codeunit::MyPublishingCodeunit (the codeunit above).

codeunit 50102 **_MyPublishingCodeunit_**
{
 .
.
.
}

codeunit 50103 MySubscribingCodeunit
{
    [EventSubscriber(ObjectType::Codeunit, Codeunit::**_MyPublishingCodeunit2_**, 'OnAddressLineChangedEvent', '', true, true)]
    local procedure SubcribeToOnAddressLineChangedEvent(sender: Codeunit **_MyPublishingCodeunit2_**; myGlobalVar: Integer)
.
.
.
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36793433-053a-b52e-0fdc-9e67f4733a10
* Version Independent ID: 3c4eebce-a23b-2231-3363-20cc63922ef0
* Content: [IntegrationEvent Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-integration-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-integration-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-integration-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this. It will be fixed with the next refresh.
