### ISSUE TITLE
Is anyone reading these documents?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#137]
"This property supports support..."? First, the obvious typo. Is there no one proofreading these pages?
Two, what does "this property supports..." even mean? What does it mean, to "support" a CSV file? Any idiot with a mouse can see what the "available options" are. So what is the purpose of this page other than to tell us what we all can see already? What does each of those options DO? Why does "Variable Text" still yield XML on export? Is Variable Text the same as XML? Documentation that simply restates what a user can see by opening a dropdown menu is not documentation, it is a waste of time. We can do better. If someone wants to pay me, I will proofread all of this and make sure it actually says something.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c9b8e3-5030-dab5-84c3-bc2a69b62f03
* Version Independent ID: 75849367-2a44-165c-e38b-16a8ff3404f1
* Content: [Format Property (XMLports) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/format-property--xmlports-)
* Content Source: [dynamics-nav/Format-Property--XMLports-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Format-Property--XMLports-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We try to keep the documentation updated and to correct any mistakes, but as you probably also know, we have quite a large docset to maintain.
