### ISSUE TITLE
Should be noted this method has OnPrem attribute attached to it

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1373]
There should be a prominent note at or near the top of anything with the OnPrem attribute attached to it alerting the user to that fact, so they don't waste time trying to setup example code only to find out that it is unusable in the SaaS solution.

It would also be extremely helpful if there was a link to alternate ways that would work with the SaaS solution.

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b74bac-ba1e-7a92-0062-adb43219c19e
* Version Independent ID: 270320a6-4b8c-64d7-bdc3-f5d34e9f607d
* Content: [CreateInStream Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-createinstream-method)
* Content Source: [dev-itpro/developer/methods-auto/file/file-createinstream-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/file/file-createinstream-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This has been resolved.
