### ISSUE TITLE
Wrong information about maximal length of option string

### ISSUE THREAD

**Issue by RaKuNbg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1376]
I think the statement about the maximum length (250) of the option string is not up to date.
I just created an option field with 40 option members with length 10 each option (Option0000,Option0001,...Option0039) and also captions for ENU and translations in the xlif with 40 characters each ==> No problems with compiling and no problems in the client.

==> Could you please check and correct the statement about the maximum length.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d64a53-4e2a-6eb3-e9b0-618160a01b3c
* Version Independent ID: 0a941f99-ef01-4570-de2f-45a927ddc792
* Content: [OptionString Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-optionstring-property)
* Content Source: [dev-itpro/developer/properties/devenv-optionstring-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-optionstring-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This issue has been resolved.
