### ISSUE TITLE
Use of term Form is long time outdated

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#138]
Change for Form to Page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df9e971-7add-8c07-ee20-23ec2d68b370
* Version Independent ID: dde40150-e097-b8f1-ff07-160861d6edad
* Content: [Be careful about UI for web services - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-webservices)
* Content Source: [dev-itpro/compliance/apptest-webservices.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-webservices.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This is fixed in the next doc refresh.
