### ISSUE TITLE
Default locale for App-level configuration

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1384]
In the section #app-level-configuration, under the _supportedLocales_ sample, it says: 
_All other Help calls will go to the default location on the docs.microsoft.com site._

But this is not the current behavior (BC16.4). 

There is a tooltip for _supportedLocales_ in app.json when running VSCode:
_List of locales supported by this app in the format - i.e. en-US, en-CA, da-DK. The first locale on the list is considered the default._

The tooltip in VSCode seems to be the way this is implemented: If the user's current language is not one of those configured in _supportedLocales_, the user gets directed to the help page with the first locale in the list of supported locales.

Sample:
```
  "contextSensitiveHelpUrl": "https://mysite.com/{0}/documentation/",
  "supportedLocales": [
    "en-GB", "en-IE
  ],
```
If the user is running en-GB or en-IE in Business Central, they will be directed to https://mysite.com/en-GB/documentation/ resp. https://mysite.com/en-IE/documentation/
If the user is running da-DK in Business Central, they will be directed to https://mysite.com/en-GB/documentation/ since "en-GB" is the first supported locale.

I hope that this is a documentation error and not a bug in the runtime. ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a37544-0705-f808-e490-0cbe386f0876
* Version Independent ID: bdac9abe-c9fd-06dc-2d0d-84d6720de7dc
* Content: [Configure Context-Sensitive Help - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help/context-sensitive-help)
* Content Source: [dev-itpro/help/context-sensitive-help.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/help/context-sensitive-help.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hej Johannes,
Thank you for your feedback! I'll admit that this is complicated, but the way it's supposed to work is that an AppSource app uses the  "contextSensitiveHelpUrl" property to control Help calls for the objects in that app only. If the user can access both your objects and Microsoft's objects, then they get sent to MySite.com for your objects, and docs.microsoft.com for Microsoft's objects.
The language hierarchy then makes things a bit more complicated. For the objects in the AppSource app, the "supportedLocales" property lists the supposed locales (no surprise there) with the first one as the default, as you say. So if the user clicks a Learn More link on one of your objects, and they are using a language that is not specified in your app manifest, then they get sent to the default location on your webserver (the equivalent of https://mysite.com/en-gb/documentation, in this example). But only if they are using your app's functionality, obviously.

You're right that this is not quite what the article says.  I'll get that clarified as part of our upcoming 2020 release wave 2 as part of a larger refresh.

**Comment by jwikman** [comment]
Thanks for the clarification @edupont04 

Then we'll proceed to implement our help docs according to how it really works, despite the docs saying otherwise.

Looking forward to the doc update!

**Comment by SusanneWindfeldPedersen** [comment]
Issue seems to be resolved, closing.
