### ISSUE TITLE
Browser Cookie Policy - Incorrect

### ISSUE THREAD

**Issue by JellebBE** [MicrosoftDocs/dynamics365smb-devitpro-pb#1386]
Hi,

The article describes the browser cookie policy is fixed from update Business central 2019 Wave 2 - Build 15.1.
![image](https://user-images.githubusercontent.com/35337017/91146986-f01c1f80-e6b7-11ea-985e-381cf72cd508.png)

We Have tested this for this build and this is not working.
![image](https://user-images.githubusercontent.com/35337017/91146833-b6e3af80-e6b7-11ea-96e2-3e468a3f4b40.png)

The solution for this build is to set the following:
set chrome://flags/#cookies-without-same-site-must-be-secure to Disabled.

Best Regards
Jelle
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bacea9dc-ec11-bbe5-ac4a-e40e57b27cec
* Version Independent ID: 0f4ce40f-0411-872c-8137-787774db06a9
* Content: [Cookie Samesite policy - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/prepare-for-cookie-samesite-policy)
* Content Source: [dev-itpro/administration/prepare-for-cookie-samesite-policy.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/prepare-for-cookie-samesite-policy.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, 

Thanks for the feedback! It should work as documented, so we'll try to take a look at this issue. It would be great if you could provide some more information:
- Is this an on-premises deployment?
- Are you using Http vs https?
- What authentication type are you using, i.e. Windows, NavUserPassword, Azure AD? 

Regards

**Comment by JellebBE** [comment]
Hi,

We are using the following configuration:
On-premise
HTTP
Windows auth


Best Regards
Jelle

**Comment by jswymer** [comment]
Thanks! I'll pass this on to the dev team.

**Comment by jswymer** [comment]
Hello, sorry for the delayed response. We have identified the problem. Instead of 15.1, the minimum recommended update is 15.2. We have updated the article to reflect this, and the updated article will be published soon.
