### ISSUE TITLE
Where to get TXT2AL.EXE

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1387]
It would be useful to know what version of Txt2AL.EXE supports the --tableDataOnly switch.  BC14 CU07 does NOT.  I found it in BC14 CU15 but it might be in an earlier version.  It is not on the BC15 or BC16 DVDs, which is not surprising but if you are looking for it that is a natural place to look for a tool you are upgrading to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b2a8e-89a9-dda2-7d06-c433f2127044
* Version Independent ID: 4a968a4c-8ad7-8d9b-b966-b08daf4bda9a
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! The Txt2AL.EXE with the --tableDataOnly switch should be available from BC 14 (CU 11) and BC 15 (CU5). We will verify this and update the docs accordingly.

**Comment by jswymer** [comment]
We have updated the article with information about this. The update will be published soon. Thanks for the feedback!
