### ISSUE TITLE
Content Type: Joker

### ISSUE THREAD

**Issue by eknraw** [MicrosoftDocs/dynamics365smb-devitpro-pb#139]
Can documentation referencing "joker" be updated to that actual data type? 

Content
 Type: Joker
The content to add to this document.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e84f204d-0f3f-3360-3504-b224bb2f6f8c
* Version Independent ID: 3fd70e15-970b-bc50-c200-d01c4905955f
* Content: [Create Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/api/xmldocument-create-content-method)
* Content Source: [dev-itpro/developer/api/xmldocument-create-content-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/api/xmldocument-create-content-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, we're currently in the process of rewriting our reference documentation, so within the next months you should be able to see updated information for methods, not only this particular method. Thanks for your patience.
