### ISSUE TITLE
Task 2.2 not clear you need to export original, modified first then create deltas

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1392]
The implication reading Task 2.2 is that all you need do is export the modified objects and run Txt2AL as described.  The description should indicate that you have use the DELTA to run TXT2AL against because it is just happy to run against the exported objects from 2.1

If you don't you get a lot of errors on the non-modified fields of tables exported that can't be resolved because base.app is not in the dependencies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b2a8e-89a9-dda2-7d06-c433f2127044
* Version Independent ID: 4a968a4c-8ad7-8d9b-b966-b08daf4bda9a
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by GreatScott000** [comment]
Or do we need to export all object, modified or not?  That is not really clear as that would not be my default expectation.

**Comment by jswymer** [comment]
Hello, 

For this scenario, you have export all table objects from the C/AL application, not the Deltas. This is required for transferring ownership of the tables to the either the Microsoft System and Base Application extensions, or new table extension objects that you created to cover custom tables or fields that you had in C/AL application. 

I hope this helps, otherwise let us know. Thanks for the feedback.

**Comment by GreatScott000** [comment]
Thank you for the clarification.

**Comment by jswymer** [comment]
You're welcome. We've tried to make this more clear for the next major update. We'll close this issue for now, but we can open it again if needed. Thanks again.
