### ISSUE TITLE
Please add info on why you would want to continuously generate symbols

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#140]
Why would I choose one (running commandline) or the other (using startup parameter)? We have been discussing on this and found out that the latter on the whole is less time consuming. Good info to add to the topic so people can read straight away what to choose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dec0c0-fadb-4096-9d80-2e1cdcb03b95
* Version Independent ID: 9a3b20ad-3897-44b3-0be9-eff89c4f6777
* Content: [Running C/SIDE and AL Side-by-Side - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side)
* Content Source: [dynamics-nav/developer/devenv-running-cside-and-al-side-by-side.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi! Thank you for the feedback. The topic has been updated and will be available with the next refresh of the docs.
