### ISSUE TITLE
There are 2 Task 6's

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1401]
There are 2 Task 6 descriptions

> Task 6: Import version 16 license

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v16#task-6-import-version-16-license

> Task 6: Publish symbols and extensions

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v16#task-6-publish-symbols-and-extensions

--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f11859-074f-540a-2c03-5555a6bc92a4
* Version Independent ID: a2d16959-9c3c-58df-251a-f163465ecdd2
* Content: [Upgrading Unmodified C/AL Application to Version 16 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v16)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v14-v16.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application-v14-v16.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by GreatScott000** [comment]
Of course you will have to renumber the remaining tasks as well.

**Comment by jswymer** [comment]
Thanks for the feedback! The numbering has been fixed and the update will be published soon.
