### ISSUE TITLE
fyi, in BC you don't have development environment anymore!

### ISSUE THREAD

**Issue by wic365** [MicrosoftDocs/dynamics365smb-devitpro-pb#1405]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f550935-9732-f48a-f6c2-f0b05b0b79ee
* Version Independent ID: cf804858-80b8-b10b-208e-5c35dd837b32
* Content: [How to: Upload the License File - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/cside/cside-upload-license-file)
* Content Source: [dev-itpro/cside/cside-upload-license-file.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/cside/cside-upload-license-file.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! Correct. For versions later than BC14, the way to upload a license is by using the Import-NAVServerLicense cmdlet. We have fixed the article and an update will be published soon. Sorry for any confusion this might have caused.
