### ISSUE TITLE
Do not use a single alias as escalation contact 

### ISSUE THREAD

**Issue by hoffe86** [MicrosoftDocs/dynamics365smb-devitpro-pb#1406]
Maybe it make sense to replace the single alias contact with a group alias.
Do not use mailto links to avoid any collection by web crawlers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b5e292-66fa-d3aa-a2ca-2f270723baee
* Version Independent ID: 11e34cf9-7a6e-05a1-3536-f6951f2966c7
* Content: [Lifecycle of apps and extensions FAQ - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-update-app-life-cycle-faq)
* Content Source: [dev-itpro/developer/devenv-update-app-life-cycle-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-update-app-life-cycle-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. You have a good point. This is, however, the process at this point in time. But we will take your feedback into consideration. Thanks.
