### ISSUE TITLE
Wrong syntax for XML format

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1408]
Hello,

Each time XML format is mentioned in the tables of the paragraph Standard Formats, it should enclosed between < and >, like this :

```
<XML format>
```

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5468dbfb-e0a2-6c51-58eb-d73580d2bbc1
* Version Independent ID: 63893c18-9b04-b5b9-a8a9-45bf23bb3d56
* Content: [Format Property - Business Central](https://docs.microsoft.com/fr-fr/dynamics365/business-central/dev-itpro/developer/properties/devenv-format-property)
* Content Source: [dev-itpro/developer/properties/devenv-format-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-format-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. It will be fixed with our next refresh of the docs.
