### ISSUE TITLE
UICop not yet described?

### ISSUE THREAD

**Issue by waldo1001** [MicrosoftDocs/dynamics365smb-devitpro-pb#141]
UICop not yet described?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a5b68ec-d706-ab10-8cb9-22e8d98c3494
* Version Independent ID: 3da84c14-159f-3ac7-ee94-5e0faff222d8
* Content: [Using the Code Analysis Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool)
* Content Source: [dev-itpro/developer/devenv-using-code-analysis-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-using-code-analysis-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi! You can find the UICop Analyzer Rules article here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-codeanalyzer-uicop-rules. 
Thank you!

**Comment by epernst** [comment]
Where it also has the same (wrong) description: UICop is an analyzer that enforces rules that must be respected by extensions meant to be installed for individual tenants.
