### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by IngeSanders** [MicrosoftDocs/dynamics365smb-devitpro-pb#1424]
The link to the example page does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0738b431-7018-e6a4-ae1f-21799b52f368
* Version Independent ID: 7ea9a2e0-49fa-0e67-53ca-cd0872382355
* Content: [Help and Customer Support - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-h-help-support)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-h-help-support.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-checklist-h-help-support.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-liober
* Microsoft Alias: **v-liober**

**Comment by edupont04** [comment]
Hello IngeSanders,

Thank you for catching this! We'll get this updated in our next major update (October 1), but until then, you can use the Continia site for inspiration: https://docs.continia.com/docs.continia-home/en-GB/index.html

**Comment by SusanneWindfeldPedersen** [comment]
This should be fixed now. Closing issue. Thanks.
