### ISSUE TITLE
NAVDataUpgrade Error

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1426]
When running [Task 10 Upgrading the data
](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v16#task-10-upgrade-data)

I get the error 

> Unable to encrypt data. The provided string is too long.

ModuleName        : Base Application by Microsoft
WorkflowStep      : OnUpgrade
ExtensionName     : Base Application
ExtensionId       : 437dbf0e-84ff-417a-965d-ed2bb9650972
ExtensionVersion  : 16.4.14693.15445
ExecutionSourceId : 437dbf0e-84ff-417a-965d-ed2bb9650972
SessionId         : 74
CompanyName       : Unity Well
StartTime         : 08/09/2020 16:35:00
Duration          : 
State             : Failed
Error             : Unable to encrypt data. The provided string is too long.
PostUpgrade       : False

Someone has suggested that this is related to https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/prepare-for-cookie-samesite-policy but I don't see how. 

We are going from BC14.07 to BC16.04.

Suggestions would be appreciated.  Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f11859-074f-540a-2c03-5555a6bc92a4
* Version Independent ID: a2d16959-9c3c-58df-251a-f163465ecdd2
* Content: [Upgrading Unmodified C/AL Application to Version 16 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v16)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v14-v16.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application-v14-v16.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, 

There might be a prerequisite missing from the article. For other upgrade articles, we have state to disable data encryption in the application before doing the upgrade.

**Comment by GreatScott000** [comment]
Seems this related to the Postcode Service Config table for the UK PostCode Address lookup extension.  Clearing the table resolves the issue.  Is there a step missing for this somewhere?  Note this is a 14.7 to 16.4 upgrade.

**Comment by jswymer** [comment]
Hello,

Just to be sure, did you disable encryption before starting the upgrade?

**Comment by GreatScott000** [comment]
There is no encryption setup in this database.  But no I did not specifically disable the encryption.  I can try that in another test.

**Comment by GreatScott000** [comment]
I have verified that the encryption was/is turned off and still get the stated error.

**Comment by Siva1818** [comment]
I am getting the same error when upgraded to BC V18 from NAV 2017. Have anyone found the solution?

**Comment by jswymer** [comment]
Hello, 

I've tried the upgrade on various versions and unfortunately haven't been able to reproduce the error. This might be a code defect. If you experience this issue, please contact support, who can better help identify the problem. If an update to documentation is required, we will be notified. Thanks.

**Comment by gunnargestsson** [comment]
I just got this error after an CU upgrade in BC 19.  The thing is that I updated the encryption key in the application database and it seems that the information in that encryption keys is used to encrypt the data in the [$ndo$tenants] table.
I stopped all service instances and then deleted all entries from this SQL table.  
Then remounted all tenants and the error is gone.

**Comment by GreatScott000** [comment]
Hmm, I am always working on single tenant db's but thank you for the information.
