### ISSUE TITLE
Where does this page fit in the site's navigation?

### ISSUE THREAD

**Issue by wolterOnEntocare** [MicrosoftDocs/dynamics365smb-devitpro-pb#143]
This page is probably meant to be part of the "AL reference guide"?
(https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-reference-guide)
But it is no referenced from that page in a clear way. Also I cannot find this page through the site menu on the left.
After finding the page, the breadcrumb at the top does not tell me that I am in a page that belongs to the "AL reference guide", so possible my assumption was wrong. I don't know where I am. It is a useful page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff8af30e-3d81-30c3-44c8-fc4cb631d001
* Version Independent ID: 315c1531-77aa-c602-6c0b-41d160d791e2
* Content: [AL Simple Statements - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-simple-statements)
* Content Source: [dev-itpro/developer/devenv-al-simple-statements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-simple-statements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. You are right, this page is not listed in the table of contents, and it should be. It will be fixed with the next refresh of the docs. Thanks.
