### ISSUE TITLE
Numerical / Alphanumerical - Dates

### ISSUE THREAD

**Issue by mh1205** [MicrosoftDocs/dynamics365smb-devitpro-pb#1430]
I have two issues with the possibilities "Open in Excel - Edit in Excel"

1) Numerical fields (eg. quantity) become alphanumerical in Excel.  hence no possibility to use a Pivot table and Sum
2) In "Edit in Excel" the dates are exported in European format but need to be modified in American format to be reimported (eg with Configuration package")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5c53847-a111-f746-cc85-af3dcc702f84
* Version Independent ID: 06c03c31-a8a9-40e7-2847-bc22cea91344
* Content: [Setting up the Excel Add-In for Editing Data - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configuring-excel-addin)
* Content Source: [dev-itpro/administration/configuring-excel-addin.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configuring-excel-addin.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
