### ISSUE TITLE
Add menu or links to countries

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1434]
Since the countries are not a top menu level, they don't appear on the menu on the right.
If it is not possible to enhance the menu to display the country level, could ypu please at least add links at the beginning of each main section to link all the countries that will follow? That would be very helpful. Currently, it is very difficult to navigate through this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099e4c9c-6893-2d35-6ece-6c056a2c752f
* Version Independent ID: 8a51d9d5-605d-d442-337b-ef992d25395d
* Content: [Fields that are Moved, Removed, or Replaced - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-fields#fields-marked-as-obsoletestatepending-in-)
* Content Source: [dev-itpro/upgrade/deprecated-fields.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/deprecated-fields.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Natalie,

Than you for your feedback! It fits nicely in with some other work we're planning, so I hope you'll see an improved experience in a few weeks.

**Comment by SusanneWindfeldPedersen** [comment]
This seems to have been fixed. The countries are in the table of contents for a better overview.
