### ISSUE TITLE
Can not find customized Role Center

### ISSUE THREAD

**Issue by Byron-Zhang** [MicrosoftDocs/dynamics365smb-devitpro-pb#144]
I create a new page with property PageType = RoleCenter , after published it to the server , I could not find the role center in My Settings-&gt;Role Center -&gt; Available Role Center. Does it support this? And how to set the role center as the default when opening the BC ? My env is online. Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baccd8df-f503-da27-3198-07aa5a5ea6ed
* Version Independent ID: 09faac4b-946c-956d-be75-469627ecc3b5
* Content: [Designing Role Centers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-role-centers)
* Content Source: [dev-itpro/developer/devenv-designing-role-centers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-designing-role-centers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, the issue might be that the new Role Center page has not been associated with a Profile. You can do this from the client, after the extension with the new Role Center has been published/installed. 

If you have not done this yet, do the following in the client:
1. Search for (using the light bulb) Profiles, and select link in the results.
2. On the Profiles page, select New.
3. On the Profile Card page, set Scope to Tenant.
4. In the Profile ID field, enter some brief text for identifying the profile, such as sample-rc.
5. In the Description field, enter a description of the profile, such as Sample Role Center.   
5. Set the Role Center ID to the page ID assigned to the new Role Center page.
6. Exit the Profile Card page and Profiles page.
7. Go to My Settings, and look for the new profile in the Role Center field.

Let me know if this works out. I will update the article accordingly. Thanks for the feedback!

**Comment by Renee0312** [comment]
But the "New" button does not enable on the Profiles page of BC online. I am not allow to new a profile on BC online.
Have I missed some set up?
Thank you.
