### ISSUE TITLE
Can we change Base App's existing caption with Translation File?

### ISSUE THREAD

**Issue by TravisChe** [MicrosoftDocs/dynamics365smb-devitpro-pb#1440]
Version: Business Central 16.0
AL Language: 5.0.335750

We're trying to change all the captions that having VAT in Base App to GST, the targeting language would be en-SG.
We copied the translation file from Business Central's installer and place it into a new extension project which only contained the translation file, we published the extension and change the language in My Settings but the caption doesn't reflect.

Seek for advice is there any experts who had done any similar things before.
Many thanks!

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I am not sure what prevents your translation from kicking in - if you have all settings and files in place. I have found a previous issue that you might find interesting: https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1296.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
