### ISSUE TITLE
Circular link

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1443]
The See Also has a circular reference back to itself.

See Also
Basic Page Operations

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aed19bc-8665-86df-264a-8bda4e632bba
* Version Independent ID: ab2597f4-9be8-4c85-d741-859714cf5cf4
* Content: [Basic Page Operations - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/basic-page-operations)
* Content Source: [dev-itpro/webservices/Basic-Page-Operations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/Basic-Page-Operations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks, we changed the link and an update will be published soon.
