### ISSUE TITLE
Source code "Customer Rewards" example extension

### ISSUE THREAD

**Issue by StijnBt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1448]
It would be useful if a hyperlink was provided the source code of the complete "Customer Rewards" extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7f2151-4fef-e6ab-bbc1-5b3e1b8c5b17
* Version Independent ID: 20ffa998-58d3-c843-87d5-3533e2fa7765
* Content: [Testing the Advanced Sample Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-advanced-example-test)
* Content Source: [dev-itpro/developer/devenv-extension-advanced-example-test.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-advanced-example-test.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. Unfortunately, we do not have anywhere to store this source code, the repo is for documentation only. 
Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
