### ISSUE TITLE
Any way to remove the navigation menu of Finance

### ISSUE THREAD

**Issue by Byron-Zhang** [MicrosoftDocs/dynamics365smb-devitpro-pb#145]
After reading this document, I can add a navigation menu and sub item. Does it support to remove a navigation menu or item? Like Finance, under Business Manager role center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d29386a-cd69-bd44-b2be-8a63fa826690
* Version Independent ID: 5fafae47-9391-1203-b9db-592bd5c10617
* Content: [Adding Menus to the Navigation Area - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-menus-to-navigation-pane)
* Content Source: [dev-itpro/developer/devenv-adding-menus-to-navigation-pane.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-menus-to-navigation-pane.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. No, you cannot programmatically remove navigation menus or items. Thanks again.
