### ISSUE TITLE
Microsoft.Dynamics.NAV.InvokeExtensibilityMethod does not work when it's called from inside of a function

### ISSUE THREAD

**Issue by dibyanugraha** [MicrosoftDocs/dynamics365smb-devitpro-pb#1451]
[Enter feedback here]
I've created 3 files: a control add in, a page to be shown in as a part in another page, and a startup Javascript file as the StartupScript of the control addins.

When I called Microsoft.Dynamics.NAV.InvokeExtensibilityMethod from outside function, it works. But when I invoked it from a button from BC, the function doesn't work - or the button doesn't invoke the javascript function.

Please see the screenshot for detailed problems.
![arVS3tRjoF](https://user-images.githubusercontent.com/11976855/94252091-aa1fd900-ff4d-11ea-801f-a7635f986ae1.png)
![qIhdQc4zzv](https://user-images.githubusercontent.com/11976855/94252168-c15ec680-ff4d-11ea-9bf3-eab0d6be440b.png)
![RnX6yDkEbw](https://user-images.githubusercontent.com/11976855/94252203-cd4a8880-ff4d-11ea-9dc5-2cd73af6dcd3.png)
![CbnGhnMEWA](https://user-images.githubusercontent.com/11976855/94252222-d3406980-ff4d-11ea-844c-c35a39bcbcea.png)

Did I do anything wrong?

My environment version is: 16.5.15897.16082
Country Code: W1
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237ce502-edd7-65fb-de3a-8bd4d044a9b7
* Version Independent ID: 6a1f466c-97f8-b5f5-2b99-bc0ee81ffc4c
* Content: [Control Addin Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-control-addin-object)
* Content Source: [dev-itpro/developer/devenv-control-addin-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-control-addin-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback and very thorough examples. However, this repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.

**Comment by dibyanugraha** [comment]
> Thanks for your feedback and very thorough examples. However, this repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.

I completely understand, however where do send this bug report? This is not AL language/compiler issue, so certainly I can't report to  [https://github.com/microsoft/AL/issues](url) since it's the repo for the AL language/compiler. The code is compiled fine and published without any problems.

I'm quite certain this is not environment specific issue. I've replicated the same thing with other sandbox environment and got the same result as well. However I haven't tried with the latest 17.x, just found out it was just released.
