### ISSUE TITLE
Update for BcContainerHelper?

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#1457]
This page still talks about NavContainerHelper. Shouldn't it use BcContainerHelper instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6979fc73-1395-b63f-50bf-b2fb1bfda4df
* Version Independent ID: eaf8c4d6-15a5-6444-bc72-48bd0a2e326a
* Content: [Running a Container-Based Development Environment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-container-development?source=docs#using-the-navcontainerhelper-powershell-module)
* Content Source: [dev-itpro/developer/devenv-running-container-development.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-running-container-development.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. You are right, both work, but we want to promote using BCContainerHelper going forward as this is also the version being updated. Will be fixed with the next doc refresh. Thanks.
