### ISSUE TITLE
https://trials.dynamics.com/ is taking a really long time to complete

### ISSUE THREAD

**Issue by srenders** [MicrosoftDocs/dynamics365smb-devitpro-pb#1459]
https://trials.dynamics.com/ is taking a really long time to complete...

Usually it takes only a couple of minutes, but since a couple of weeks, it usually takes between 2 and 6 hours to complete. 

Is that normal?
Where do I report this?

Since this is the first experience many potential new customers get about Business Central I can imagine you (Microsoft) might want to fix this asap...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88af6b6b-4656-73c4-a199-1a50eb10773d
* Version Independent ID: 646d240a-ee7d-7bc9-402f-df79a192c9e5
* Content: [Trials and Sign-ups for Business Central online - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/customer-signup)
* Content Source: [dev-itpro/deployment/customer-signup.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/customer-signup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Steven,
I'm closing this Issue because it's not about the docs. Also, I saw that you reported this on the private Yammer network as well, and I hope we'll find you the right answer there.
