### ISSUE TITLE
Syntax wrong

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#146]
Syntax is not: DAN=Navn;DEU=Name;ESP=Nombre;FRA=Nom
But: DAN=Navn,DEU=Name,ESP=Nombre,FRA=Nom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bfbb9ca-3b27-7151-5fbc-5986c81f6b23
* Version Independent ID: 03fd2eed-c11c-16b4-9588-26feea722301
* Content: [CaptionML Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-captionml-property)
* Content Source: [dev-itpro/developer/properties/devenv-captionml-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-captionml-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The syntax has been corrected and an update will be soon published.
