### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1462]
Hello,

The following sentence contains a broken link.

For more information, see **API Page Type**.

It points to: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-api-pagetype.md.

It should point to: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-pagetype.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53dbbe8-f479-2e9e-7555-9e7b10804827
* Version Independent ID: fc3fd536-d521-040f-aeba-d2adeb7025e9
* Content: [APIPublisher Property (Page) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-apipublisher-page-property)
* Content Source: [dev-itpro/developer/properties/devenv-apipublisher-page-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-apipublisher-page-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - will be fixed with the next doc refresh.
