### ISSUE TITLE
Link brocken

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1465]
Hi, 
could you please correct the link in section [Remarks](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-setposition-method#remarks)? It appears to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ce2d8b-d0d1-6e50-24b3-e6eb61c8cf1c
* Version Independent ID: ba1383c2-475d-caeb-2fab-a7df23bbb25a
* Content: [SetPosition Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-setposition-method)
* Content Source: [dev-itpro/developer/methods-auto/recordref/recordref-setposition-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/recordref/recordref-setposition-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! This link has been fixed and the update will be published soon.
