### ISSUE TITLE
Delete section Limitations

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1467]
Hi Susanne,

the section [Limitations](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-open-method#limitations) needs to be deleted. It seems to be accidently copied from or for a totally different article.

On a side note: the code examples are still C/AL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd763007-eec4-95da-5750-faba18a723b1
* Version Independent ID: 378c9bd0-5ddf-e49f-d1f0-87f2a9e79a2c
* Content: [Open Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-open-method)
* Content Source: [dev-itpro/developer/methods-auto/recordref/recordref-open-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/recordref/recordref-open-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi Natalie, thanks for catching this - I agree that this looks weird, will be fixed with the next doc refresh. Thanks!
