### ISSUE TITLE
AA0073 suggests TempBlob name to be changed to TempTempBlob

### ISSUE THREAD

**Issue by bwdeleeuw** [MicrosoftDocs/dynamics365smb-devitpro-pb#1471]
This rule seems overzealous in the case where a temp table already begins with the name Temp. NAV uses the TempBlob name, which the system suggests should be changed to TempTempBlob. 
We also indicate some tables in our solutions to also be used as temp, for instance Temp Report Buffer. 

I'd suggest this rule be changed to ignore the variable if it already contain Temp at the beginning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36dc9cfc-73bf-2d48-bf5d-2683f5bfb641
* Version Independent ID: 2724ea2b-d104-0647-1261-b8290b90871f
* Content: [The name of temporary variable must be prefixed with Temp. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0073-temporaryvariablesmustbeprefixedtemp)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0073-temporaryvariablesmustbeprefixedtemp.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0073-temporaryvariablesmustbeprefixedtemp.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
