### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Jupentti1** [MicrosoftDocs/dynamics365smb-devitpro-pb#1472]
There is a broken link in the part **Setting the TableType to Temporary** that has a link to **Performance of BACPAC generation**  https://docs.microsoft.com/en-us/performance/performance-onprem.md#performance-of-bacpac-generation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d3aca9-8d36-d509-86b5-01c304b39a60
* Version Independent ID: 2beaf080-7fd7-569c-9738-c7158ac7dd8c
* Content: [Temporary Tables - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-temporary-tables)
* Content Source: [dev-itpro/developer/devenv-temporary-tables.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-temporary-tables.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
