### ISSUE TITLE
Replace references from 15 to 16

### ISSUE THREAD

**Issue by yrest** [MicrosoftDocs/dynamics365smb-devitpro-pb#1474]
The document meant to demonstrate upgrade path from v 16 to v 17 and throughout the document it references v 15 instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33157c57-b602-c02f-bcd3-0ed452cd29c4
* Version Independent ID: 9bb54d75-1587-ad90-c0a3-1d6800fc89cf
* Content: [Upgrading Version 16 Base Application to Version 17 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v16-to-v17)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v16-to-v17.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application-v16-to-v17.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, the article has been fixed, and the update will be published soon. Thanks for the feedback!
