### ISSUE TITLE
upgadeDate?

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1475]
In the response for "Get Scheduled Update" (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api#response-16)  there seems to be a typo.

`  "upgadeDate": datetime, // The currently selected scheduled date of the update.
`

I don't know if this should be `upgradeDate` or `updateDate`, both seems plausible in the context. And since it is not yet possible to schedule an upgrade/update, I cannot test this out.

It could also be a typo in the Admin API, so that the documentation is correct - But I just cannot know :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c4240e-3064-4e29-63cf-202b47e86c96
* Version Independent ID: fa3bfa13-4b7b-011c-62a6-1baa9aab4792
* Content: [Business Central Administration Center API - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api#response-16)
* Content Source: [dev-itpro/administration/administration-center-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/administration-center-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! It should be upgradeDate. The article has been fixed and an update will be published soon.
