### ISSUE TITLE
Introduced in BC 17?

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1477]
Hi,
could you please add 

> APPLIES TO: Business Central 2020 release wave 2 and later

Background: https://twitter.com/KarolakNatalie/status/1313343599241818112?s=20

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 245a6ad9-dfb0-13ed-3936-48d049967717
* Version Independent ID: a26186f1-b94d-e9b0-a94d-7c91047e3136
* Content: [CommitBehavior Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-commitbehavior-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-commitbehavior-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-commitbehavior-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Absolutely - this is now fixed and will be pushed with the next doc refresh. Thanks!
