### ISSUE TITLE
Upgrade sandbox to enable Visual Studio Code to run this function

### ISSUE THREAD

**Issue by Frantic42** [MicrosoftDocs/dynamics365smb-devitpro-pb#148]
Could you kindly provide some information on how to upgrade an existing docker generated development environment so that the "AL: Generate permission set containing current extension objects" is available? I need to be able to do this from within the sandbox (installed as a virtual machine on Azure and building an extension).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba62be20-de4f-6d05-ae77-b10380c3dba3
* Version Independent ID: 7de9447f-27b1-5265-0663-1d51bb00949c
* Content: [Exporting Permission Sets - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-export-permission-sets)
* Content Source: [dev-itpro/developer/devenv-export-permission-sets.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-export-permission-sets.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by freddydk** [comment]
If you are running Docker locally, using navcontainerhelper, you just re-run the same script again (as you used to create the container) adding the -alwaysPull parameter to get the latest version.

If you have an Azure VM generated by aka.ms/navdeveloperpreview (as it looks), you can open a navcontainerhelper powershell prompt and run

Replace-NavServerContainer -imageName microsoft/bcsandbox:<language>

Where <language> is the localization.
NOTE: It will Delete the container and create a new one with the latest version - and install the latest vsix in VS Code. 

Remember to close all application first.

But all in all - it is all about removing the existing container and creating a new one.
The .vsix is in the docker container and can be installed from there.
