### ISSUE TITLE
Version 15 compatibility - is blank from 15.0 - 15.4 to 17.0 Means?

### ISSUE THREAD

**Issue by MngKeck** [MicrosoftDocs/dynamics365smb-devitpro-pb#1483]
As per Title, is it means from 15.0 - 15.4 no directly compatible to 17.0? It needs to go thru 16.0?

<img width="514" alt="Issue" src="https://user-images.githubusercontent.com/65142889/95545460-84580100-0a30-11eb-9edb-46599095c10a.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8868c4-fb29-4b1f-e8ba-7560642481fc
* Version Independent ID: e838d8a4-07b9-02a8-f0b5-756220b3e64d
* Content: [Business Central compatibility matrix - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility)
* Content Source: [dev-itpro/upgrade/upgrade-v14-v15-compatibility.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-v14-v15-compatibility.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, There is a mistake in the article. 15.0 - 15.4 **is** directly compatible with 17.0 and later. The article has been fixed and an update will be published soon. Thanks for the feedback!.
