### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1487]
There is a link for Recall on this topic about Notifications. But the link given for Recall is

Data Types and Methods in AL
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/library

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87fc7637-4e16-c566-a99a-0f2e01aa22a6
* Version Independent ID: cb3cd413-3471-8411-98c5-5d25b22ba777
* Content: [Notifications - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-notifications-developing)
* Content Source: [dev-itpro/developer/devenv-notifications-developing.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-notifications-developing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Thanks for your feedback, this will be fixed with the next refresh.
