### ISSUE TITLE
QueryCategory  - is it still internal use only?

### ISSUE THREAD

**Issue by mynavblog** [MicrosoftDocs/dynamics365smb-devitpro-pb#1489]
Dear Team,

I think the description of QueryCategory property is not correct anymore. Since on yammer group it is stated it can be used. Also in other documentation page it is said:

_With the SmartLists functionality that was added, we also made some underlying platform changes to make it possible to create SmartLists based on queries. With this functionality, you can now create your own lists through extensions. The created list can then be assigned to an entity by setting the QueryCategory property._

_By being able to create a new list page based on a query, you can get the data you want on one list even if all the data isn’t in a single table in the database._

[https://docs.microsoft.com/en-us/business-applications-release-notes/April19/dynamics365-business-central/enhancements-intelligent-cloud](https://docs.microsoft.com/en-us/business-applications-release-notes/April19/dynamics365-business-central/enhancements-intelligent-cloud
)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecacafbf-bba5-f3e4-8da9-f408e7a17074
* Version Independent ID: 77b1226e-488c-09c6-38ad-44fc2bdbb9ca
* Content: [QueryCategory Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-querycategory-property)
* Content Source: [dev-itpro/developer/properties/devenv-querycategory-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-querycategory-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **t-blrobl**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for this. Yes, the topic needs an update. We will provide one with the next doc refresh.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The topic has been updated here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-querycategory-property.
