### ISSUE TITLE
Using parameter --object ignores Modified Standard objects

### ISSUE THREAD

**Issue by theo-stock** [MicrosoftDocs/dynamics365smb-devitpro-pb#149]
Using --type=ObjectType caused Txt2Al to ignore DELTA files relating to extended standard objects altogether. Only totally Custom Objects were considered when using this Parameter.
e.g. Folder .\DELTA contained DELTA files for both added fields to a Standard NAV Tables, plus some total new Tables. Running the following from the CMD prompt
mkdir ..\..\AL\MyApp\Table
"C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client\Txt2Al.exe" --source=.\DELTA\ --target=..\..\AL\MyApp\Table\ --rename --type=Table --extensionStartID=220xxxxx

..contained no al files for the Table Extensions at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfebcfad-5d9d-5365-5ae0-524780e74355
* Version Independent ID: 0a3a2ef5-ceeb-7b4d-572f-6a80a4c90c46
* Content: [The Txt2Al Conversion Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool)
* Content Source: [dev-itpro/developer/devenv-txt2al-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-txt2al-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. Please contact your support channel or the AL code repo. Thanks.
