### ISSUE TITLE
Application Insights Key not visible in the menu

### ISSUE THREAD

**Issue by eclipses** [MicrosoftDocs/dynamics365smb-devitpro-pb#1491]
Hi, 

probably something has been changed with the release of 2020 Wave 2, Application Insights Key is not visible anymore in the menu.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5110b5f-fbc7-66de-b57b-3c4a3adc7ff4
* Version Independent ID: 24a63a6f-3667-faa1-dbb9-4c8ba42b4bf1
* Content: [Environment Telemetry - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-telemetry#appinsights)
* Content Source: [dev-itpro/administration/tenant-admin-center-telemetry.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/tenant-admin-center-telemetry.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Yes, the Applications Insights Key field has moved to the Environments page. We'll get this clarified in the next doc refresh.

**Comment by eclipses** [comment]
Could you please let me know at least from where to enable the Telemetry of
if now it is enabled by default?

Thank you

**Comment by edupont04** [comment]
On the Environment page, the Application Insights Key field shows if the environment already uses application insights.

To enable application insights, choose the Define caption, and then, in the Set Application Insights Key pane, choose the Enable application insights field and enter the instrumentation key in the Instrumentation Key field.

 Note: In version 15 and 16, to enable application insights, choose the Application Insights Key action, and then specify the instrumentation key.

**Comment by eclipses** [comment]
Perfect, thank you, I did not notice the Define link.

**Comment by eclipses** [comment]
If I may add an extra note, I did not find specific information on how to enable the Telemetry if in case of multiple Production environments in the same tenant. I mean, we need to create a separate Application Insight Key for each environment or can the same one used for multiple environments?

**Comment by edupont04** [comment]
Theoretically, you should be able to use the same instrumentation key for all environments in a specific tenant, but I have not tested this myself, and the people who might know for sure are on vacation this week (due to a school break here in Denmark). I would encourage you to try using the same key if you have the need, but at the same time encourage you to use Application Insights just for production environments.

**Comment by jswymer** [comment]
Hello,

You can use the same Application Insights instrumentation key on multiple environments. Most traces in the Application Insights will include the **environmentName** and **environmentType** dimensions to help you identify the environment and whether it's a production, sandbox, or trial.

**Comment by eclipses** [comment]
Great,

Thank you for your response.

**Comment by jswymer** [comment]
You're welcome. We've added a note to the article to make this more clear. The update will be published soon. We'll close this issue, but if you have other questions about it, let us know. Thanks for the feedback!
