### ISSUE TITLE
CodeCop Rule AA0072

### ISSUE THREAD

**Issue by titofffffff** [MicrosoftDocs/dynamics365smb-devitpro-pb#1493]
hello,

this rule is not clearly documented.

I try to respect the rule by without success, I think it could be good to provide some examples.

here below the test I've done 

my variable is a record

![image](https://user-images.githubusercontent.com/5903546/95737267-b2834e00-0c87-11eb-96bc-a040a8740821.png)
![image](https://user-images.githubusercontent.com/5903546/95737347-d3e43a00-0c87-11eb-8980-02f138e286db.png)
![image](https://user-images.githubusercontent.com/5903546/95737427-f0807200-0c87-11eb-9e0f-338ed46f0805.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56280e32-c114-b769-c475-ee4a749dd869
* Version Independent ID: 082f7b34-b8bc-4870-5170-e05576de3f30
* Content: [The name of variables and parameters must be suffixed with the type or object name. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0072-nameofvariablesmustbesuffixedwithtypeobjectname)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0072-nameofvariablesmustbesuffixedwithtypeobjectname.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0072-nameofvariablesmustbesuffixedwithtypeobjectname.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the guidelines for prefix and suffix were just updated, please check this topic: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix - I hope that helps. Thanks.

**Comment by rdebath** [comment]
@SusanneWindfeldPedersen 

The affix document you are have referenced is for the partner identifier on publicly visible objects.
This is not related to the requirements for variable names coded by Codecop error AA0072.
You need to reopen and revisit this issue.
