### ISSUE TITLE
Examples for file names

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#1495]
In the description for this page it says that the prefix/suffix rules apply to object/field/control names etc. It says nothing about file names. And still the only examples you show are for file names (.al). 
It has previous been my understanding that there are different rules for the actual file names, but including the prefix/suffix here was not among them. Must the prefix/suffix now be used by source file names?
If not, then many the examples should be updated. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e572f37f-91f5-e8b2-aa5b-242adb0ad329
* Version Independent ID: 32e50127-f6e4-1107-289e-c0b18b1c2d91
* Content: [Prefix and suffix for naming in extensions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix)
* Content Source: [dev-itpro/compliance/apptest-prefix-suffix.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-prefix-suffix.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback - this topic has recently been updated - hope this helps. Thanks.
