### ISSUE TITLE
Wrong step referenced?

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1498]
[Enter feedback here]

> Task 8: Build object search index
> Build the object search index to make objects able to be searched from Tell Me in the client. If you completed step 6, you can skip this step.
> 
Step 6 is setting the application version.  I suspect you mean Step 7 that updates the pages/reports from the MenuSuite.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b69c11d2-4915-8e2e-f38c-7bb1a3777bf9
* Version Independent ID: 0028111c-4f1a-df24-0d47-48b7f6e6d98a
* Content: [Upgrade Application Code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-application-code)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Application-Code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Application-Code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, good catch. Thanks for the feedback! An update will be published soon.
