### ISSUE TITLE
Incorrect cmdlet name in PS Help example

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1499]
[Enter feedback here]
In the PowerShell help example for the Set-ObjectPropertiesfromMenusuite cmdlet the cmdlet name is spelled incorrectly.  It is shown as 

> Set-ObjectsPropertiesfromMenusuite

 With a plural "Objects" rather than the correct Set-ObjectPropertiesfromMenusuite .

> -------------------------- EXAMPLE 1 --------------------------
>     
>     PS C:\>Set-ObjectsPropertiesfromMenusuite -RoleTailoredClientFolder "C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client" -DataBaseName "Navision_NAV" -OutPutFolder "C:\Temp"
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00ecb53f-3816-6c06-7685-97060cec6cff
* Version Independent ID: b30de908-8377-e4e6-96e4-eb1c5a7ed9b9
* Content: [Making Pages and Reports in the MenuSuite Searchable in Business Central After Upgrade - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-pages-report-for-search)
* Content Source: [dev-itpro/upgrade/upgrade-pages-report-for-search.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-pages-report-for-search.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Good catch, thanks for the feedback! We have updated the example in script file where the help comes from. The update will be available in an upcoming cumulative update.
