### ISSUE TITLE
INSIGHT FROM LAST WEEK

### ISSUE THREAD

**Issue by KristofKlein** [MicrosoftDocs/dynamics365smb-devitpro-pb#15]
I have found a small glitch on the Insight from last week: Running the Role Center for "Business Manager" it says: "Your top customer was Klubben, bought for £11,772" while clicking on it to see more: the column says: 11,772 $. so £ vs $ but same amount. (btw. it would also be very nice to access the Customer Klubben via that subpage").

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This forum is for documentation issues only. Please file bugs and issues through product feedback. Thanks.
