### ISSUE TITLE
Meaningless description

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#150]
For any outsider this is totally abacadabra. This topic is not helping in any way. I personally think TableNo should be deprecated in D365BC (see https://github.com/Microsoft/AL/issues/3845). Nevertheless, fr the time being make sure to update this topic so it tells anybody (also newbies) what TableNo actually stands for - i.e. setting the signature of the OnRun trigger - and that the OnRun trigger now has a Rec (and not a global variable CurrRec) parameter by reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b688a777-6183-5f7d-0e65-6b6d9c382d2d
* Version Independent ID: 8649326c-bbdd-c474-87e5-f5efd6957dab
* Content: [TableNo Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/tableno-property)
* Content Source: [dynamics-nav/TableNo-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/TableNo-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by KSH-audibene** [comment]
Also error in phrase "then you can use the CurrRec global variable" - there should be Rec global variable

**Comment by jswymer** [comment]
Thanks for the valuable input. We have made some changes to the article as a result. The updated article will be publsihed soon.
