### ISSUE TITLE
sandboxName is obsoleted

### ISSUE THREAD

**Issue by pmohanakrishna** [MicrosoftDocs/dynamics365smb-devitpro-pb#1500]
This setting is obsoleted. we need to use the ‘sandbox’ environmentType and the environmentName settings instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files#Launchjson)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by edupont04** [comment]
See linked Issue in the AL repo: https://github.com/microsoft/AL/issues/6219

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Yes, it is deprecated and there are two new settings. The docs will be updated with the next refresh.
