### ISSUE TITLE
Could you please add information on what is shown in the debugger

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1502]
The topic is more or less no rephrase what the property description itself says: enableSqlInformationDebugger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16da61c7-7e29-b6b3-7619-2616a99427d7
* Version Independent ID: c00dc763-b41e-4428-b62d-e92a5158ffe5
* Content: [EnableSqlInformationDebugger Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-enablesqlinformationdebugger-property)
* Content Source: [dev-itpro/developer/properties/devenv-enablesqlinformationdebugger-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-enablesqlinformationdebugger-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback and for catching this. This topic is redundant as the EnableSQLInformationDebugger setting is actually a [JSON](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files) file Boolean setting that enables SQL information as described here: [Debugging](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-debugging#DebugSQL). Equally, the server has an enableSqlInformationDebugger setting, which actually does the same [Configuring Business Central Server](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-server-instance). This will be cleaned up with the next doc refresh.

**Comment by lvanvugt** [comment]
Thanx @SusanneWindfeldPedersen , but none of the topics you reference do mention enableSqlInformationDebugger. SO the suggest way of "solving" does not make sense.

**Comment by SusanneWindfeldPedersen** [comment]
Hi Luc, the JSON topic contains the information --> enableSqlInformationDebugger | Yes | Specifies whether the debugger shows the SQL information. It toggles whether you have the SQL information, described in [Debugging SQL behavior](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-debugging#DebugSQL) available in the debugger.

**Comment by lvanvugt** [comment]
Ouch, overlooked the JSON link.

**Comment by SusanneWindfeldPedersen** [comment]
But we'll link back and forth so that the setting hopefully makes sense combined with the description in the Debugging topic. Thanks for the input.
