### ISSUE TITLE
For internal use only

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1505]
Could we some more info on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecacafbf-bba5-f3e4-8da9-f408e7a17074
* Version Independent ID: 77b1226e-488c-09c6-38ad-44fc2bdbb9ca
* Content: [QueryCategory Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-querycategory-property)
* Content Source: [dev-itpro/developer/properties/devenv-querycategory-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-querycategory-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **t-blrobl**

**Comment by lvanvugt** [comment]
Found #696 on the same.

**Comment by lvanvugt** [comment]
And this give an explanation http://www.mynavblog.com/2020/10/19/from-gp-to-bc-the-smartlists/

**Comment by lvanvugt** [comment]
And #1489 has already all in it.

So , sorry for spamming, but in the past, when logging an issue on a topic you would see a lsit of what was already logged. Would be very useful to have that back again.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The topic has been updated here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-querycategory-property.
