### ISSUE TITLE
Typo: 

### ISSUE THREAD

**Issue by BelarminoVicenzo** [MicrosoftDocs/dynamics365smb-devitpro-pb#1506]
[
Typo on **set.exe** and **set.up exe**
And thre's no **CustomSetting** but **CustomSettings**
]

Install Business Central components of the cumulative update.

There are two ways to install components. You can use the **set.exe** file from the installation media or manually patch files to the existing installation:

Using **set.up exe** 

Before you install, save a copy of the configuration files for the Business Central Server (**CustomSetting**.config)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566ac7ba-c8e2-cd8f-370e-26e1d581a7cf
* Version Independent ID: 6961aefe-7207-d8eb-4b2b-a249d321a309
* Content: [Install a cumulative update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, the issues have been fixed, and an update will be published soon. Thanks for the feedback!

**Comment by BelarminoVicenzo** [comment]
> Hello, the issues have been fixed, and an update will be published soon. Thanks for the feedback!

:) Thankss :) 👍
