### ISSUE TITLE
File Structure: global variables after triggers

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1507]
Provided that the examples I've seen in the standard (e.g. [here](https://github.com/microsoft/ALAppExtensions/blob/master/Apps/W1/AMCBanking365Fundamentals/app/Tables/AMCBankingSetup.Table.al)), the section [File Structure](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-structure) is not complete.
![image](https://user-images.githubusercontent.com/34504100/96689618-f1e62480-1382-11eb-8131-a0a11e709d8a.png).

According to the example above, it should be
1. Properties
2. Object-specific [...]
3. Triggers
4. Global variables [...]
5. Methods

or probably

1. Properties
2. Object-specific [... listing triggers]
3. Global variables [...]
4. Methods

Can you please verify my assumption?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi Natalie, the guidelines are meant as a best practice and there will probably be places where we do not strictly adhere to some of them ourselves. However, you are right that triggers are missing - and having consulted one of our app developers, we think that these most logically belong under object-specific constructs. We will update the topic to reflect this with the next refresh, thanks for pointing this out.
