### ISSUE TITLE
Documentation needs modernization

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#1509]
Hello, I recently needed to use a CaptionClass-Property and feel like there should be something done with your documentation on that topic. 

1st of all: 
_"Business Central passes the value of the CaptionClass property to the CaptionClassTranslate method trigger in codeunit 42. This method trigger translates the CaptionClass property value to a caption that users can see."_
Isn't really helpful in the modern BC Development environment.
- From my research, it looks like "codeunit 42" is called "Caption Class" and its sourcecode is hidden somewhere in the system app. Where even Partners can't get access to. But there are two Events OnResolveCaptionClass & OnAfterCaptionClassResolve
- it shouldn't be mandatory to load up and reverse engineer the BaseApps' source code to figure out how to use a property in the first place.

Then i'd recommend to point out two important facts (please verify with your team if I am correct, but it worked in my tests):
1. If you omit the pattern of "starting with an integer, followed by a comma", apparently the caption becomes the value of whatever string has been given to the "CaptionClass"-Property. Which means, you can use the fieldcaption-function form Records that are not the SourceTable-Record on a Page.
e.g. `CaptionClass = ItemRec.Fieldcaption("Location Code");` works. - Or any other function with a Text as return Data Type.
2. If you need more logic and/or re-usability than that, there is an Event you can subscribe. (Codeunit::"Caption Class", 'OnResolveCaptionClass') If you want to use the event, start with an Integer that is within your licenses' ID-Range and a ','-Char. After that you can add any form of Text you'd like to parse later. Most programmers stick with the three integers though, because those where in the code samples from the introduction of the global dimensions.

The second solution could really benefit from some sample code, like the one i attached here: 
[sample_MyCaptionClassMgmt.Codeunit.al.txt](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/files/5417282/sample_MyCaptionClassMgmt.Codeunit.al.txt)

Or you could use a more practical example like this one from the BaseApp:

[VATCaptionClassMgmt.Codeunit.al.txt](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/files/5417326/VATCaptionClassMgmt.Codeunit.al.txt)

I'd also reconsider if content of chapters "Syntax", "Remarks" and "Functionality" aren't more confusing than helping.
- Syntax shows an example that would make use of the codeunit::"Caption Class" wich is mentioned but not explained.
- Remarks Is more about the topic how Data-Types work, than the fact that i accepts a Text[80] parameter.
- Functionality refers to unreachable code in "codeunit 42". And all in all leaves you with more questions than answers.

Hope, you can use my input to improve this section to become more understandable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5321a03-193e-b6ca-81e5-2880dcf6ac65
* Version Independent ID: e8433b54-2d18-87e2-049d-cb4f4df736ec
* Content: [CaptionClass Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-captionclass-property)
* Content Source: [dev-itpro/developer/properties/devenv-captionclass-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-captionclass-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
First of all, thank you for your feedback and for taking time to submit this suggestion along with examples. We are aware that the Caption Class information is not current and needs an update. We will put this on our backlog and prioritize it. Thanks so much!

**Comment by SusanneWindfeldPedersen** [comment]
We have published an update of the topic, please go here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-captionclass-property. And we've taken the liberty to use your nice example in there as well. Thanks much for your input!
