### ISSUE TITLE
API for Dynamics 365 Business Central: Expose Dimensions for G/L entries as you do for gen. journal line

### ISSUE THREAD

**Issue by michael-toolpack** [MicrosoftDocs/dynamics365smb-devitpro-pb#151]
We use the API for Dynamics 365 Business Central and we really could use the dimensions for G/L entries.
I can see that the API expose dimensions i relation to Journal Line. Is there any  way to get dimensions i relation to G/L entries or can you provide information on where this feature will we realized in your Roadmap.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation bugs and issues only, please use the support channel for questions.
