### ISSUE TITLE
CfMD

### ISSUE THREAD

**Issue by waldo1001** [MicrosoftDocs/dynamics365smb-devitpro-pb#1513]
I'm not sure the CfMD information is still up-to-date.  If it is, it might be interesting update the link to information about it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f11a3974-3f3b-33b3-5a55-f0fa5c6d558f
* Version Independent ID: b5fd581c-4f43-24cc-8821-2a8fc5f0a647
* Content: [Add-On Apps - Getting You Started - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started#object-ranges)
* Content Source: [dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-liober
* Microsoft Alias: **a-emniel**

**Comment by edupont04** [comment]
Hello Waldo,
As Kurt explained on the invitation-only forum, an update will be announced soon. When that announcement is published, this content will be updated.

**Comment by edupont04** [comment]
closing since the programs have changed.
