### ISSUE TITLE
Clears any AL variables on the record?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1519]
In the last sentence at the start of this topic it's written:

`Also removes any marks on the record and clears any AL variables on the record`

What does _clears any AL variables on the record_ mean? what are (any) **AL variables on the record**?

I think this needs clarification on the topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f615a4-d0c3-217f-d22c-6f2e2939412c
* Version Independent ID: 780d64e4-f1a8-5876-f7e2-a9d5ed3bd60d
* Content: [Record.Reset Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-reset-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-reset-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-reset-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We're updating this topic with the next doc refresh.
