### ISSUE TITLE
SPN registration

### ISSUE THREAD

**Issue by AldisB** [MicrosoftDocs/dynamics365smb-devitpro-pb#1522]
When service starts it registers SPNs to DynamicsNAV/BCserver:port, but in document is written that SPN must be registered with instance name (BC160/BC150):

"For example, if BCSERVER is the name of the computer that is running Business Central Server and BC160 is the instance name, the actual command has the following format.

setspn -A BC150/BCSERVER.corp:7046 corp\bcdomainuser"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9871474-165d-c6bf-93f8-e11ea14c6596
* Version Independent ID: a881c98f-927d-f458-7e42-e9380404da6f
* Content: [Configure Web Client Delegation - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/configure-delegation-web-server)
* Content Source: [dev-itpro/deployment/configure-delegation-web-server.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/configure-delegation-web-server.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback!

There was an error in the paragraph that you mentioned, and it has been updated to this:

For example, if BCSERVER is the name of the computer that is running Business Central Server and **BC160** is the instance name, the actual command has the following format.

setspn -A **BC160**/BCSERVER.corp:7046 corp\bcdomainuser  


Does this change address your issue? Otherwise, let us know.

**Comment by AldisB** [comment]
> Hello, thanks for the feedback!
> 
> There was an error in the paragraph that you mentioned, and it has been updated to this:
> 
> For example, if BCSERVER is the name of the computer that is running Business Central Server and **BC160** is the instance name, the actual command has the following format.
> 
> setspn -A **BC160**/BCSERVER.corp:7046 corp\bcdomainuser
> 
> Does this change address your issue? Otherwise, let us know.

Not realy. BC150/BC160 is typo error. 

But confusing part is when service account is configured to register SPNs automaticaly when BC service starts. SPN will be registered as

**DynamicsNAV**/BCSERVER.corp:7046 corp\bcdomainuser and not **BC160**/BCSERVER.corp:7046 corp\bcdomainuser

**Comment by jswymer** [comment]
Hello, Sorry for long wait on this issue. We've finally got clarification on this issue. As you noted, the SPN is always registered with DynamicsNAV, which is a hard coded value. This is used when the service account is configured to register SPNs automatically, and, when not, you should create the SPN using DynamicsNAV as well, like: 
```
DynamicsNAV/BCSERVER.corp:7046 corp\bcdomainuser 
```
We've updated the article accordingly. Thanks for the feedback!
