### ISSUE TITLE
Additional links needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1526]
Hello,

It would be very helpful if the bolded terms in the section below (e.g. List, ListPart, Worksheet and API) were links.

A list is a characteristic element of the layout of pages of the type **List** and **ListPart**. You define the type of a page using the PageType Property. List pages are designed for using a single repeater() control, which must be defined at the beginning of the content area. If you include more than one repeater or another control like a group or grid, the page might not behave as expected. If you want to design a page that includes controls in the content area other than a repeater, then try using a **Worksheet** page type instead.

Pages of the type **API** are also designed to integrate a repeater control, but they cannot be displayed in the user interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2928d741-dbd4-2033-2fe4-6f9dd2809822
* Version Independent ID: 21011262-7127-295e-f115-b5bdadf9f04e
* Content: [Working with Repeater Controls - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-repeater-controls)
* Content Source: [dev-itpro/developer/devenv-repeater-controls.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-repeater-controls.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the suggestion. Added links to content that we have. This topic will be updated with the next doc refresh.
