### ISSUE TITLE
What is trigger order

### ISSUE THREAD

**Issue by wintg-zns** [MicrosoftDocs/dynamics365smb-devitpro-pb#153]
It is not clear from this page what the order of the various triggers are.
What is the order of operations in XMLport, what steps are taken as it processes the documents?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68f2a1de-6246-dd9e-6414-74459aef2b2f
* Version Independent ID: 1e353a6a-6f7d-adc4-db44-dcc6db113784
* Content: [XMLport Triggers - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/xmlport-triggers)
* Content Source: [dynamics-nav/XMLport-Triggers.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/XMLport-Triggers.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. When a trigger is run is supposed to be implicit in the name, I believe the table describes when each of them is run. The order will be dependent on which code is executed and it is therefore difficult to write more information. Closing this, but thanks for your feedback.
