### ISSUE TITLE
Typo in page

### ISSUE THREAD

**Issue by MBK75** [MicrosoftDocs/dynamics365smb-devitpro-pb#1531]
"The OnAfterCaptionClassResolve event is used to overwrite the above logic" should read "The OnAfterCaptionClassResolve event is used to **override** the above logic"

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The information about which topic this issue is about, is missing - can you please add that?

**Comment by SusanneWindfeldPedersen** [comment]
Okay, found it :) Will be fixed with the next doc refresh. Thanks.
