### ISSUE TITLE
query object is missing in listing

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1534]
We can also access a query object with a url like table, page or report. Please add the option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef919ec1-3780-e58f-cbe4-2fc303f645ea
* Version Independent ID: 82d0833c-b4b3-d76f-987f-8f84ba7fa638
* Content: [Web Client URL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-web-client-urls)
* Content Source: [dev-itpro/developer/devenv-web-client-urls.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-web-client-urls.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The query option has been added, and the update will be published soon.
