### ISSUE TITLE
AA0072 

### ISSUE THREAD

**Issue by SorenKlemmensen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1535]
[Enter feedback here]
It would be nice with a link here to the page describing how these should be done. It took me a few minutes extra to find it out.

Secondly it actually is giving a "false" warning on Events as the variable names are already defined as part of the event by Microsoft we cannot do anything to resolve it.

Keep up the great work.

Happy Code,
Soren

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56280e32-c114-b769-c475-ee4a749dd869
* Version Independent ID: 082f7b34-b8bc-4870-5170-e05576de3f30
* Content: [The name of variables and parameters must be suffixed with the type or object name. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0072-nameofvariablesmustbesuffixedwithtypeobjectname)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0072-nameofvariablesmustbesuffixedwithtypeobjectname.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0072-nameofvariablesmustbesuffixedwithtypeobjectname.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, that's a good point. And thank you for the kind words. We'll add the link with the next doc refresh.
