### ISSUE TITLE
AzureKeyVaultAppSecretsPublisherValidationEnabled in OnPrem?

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#1536]
Is really the setting AzureKeyVaultAppSecretsPublisherValidationEnabled available for OnPrem? How it could work for the OnPrem Apps when I need to register the app for the KeyVault acccess during the AppSource app validation, which means that it works only for SaaS environment hosted by Microsoft?

Trying to set this settings OnPrem gives us 
````
The configuration setting 'AzureKeyVaultAppSecretsPublisherValidationEnabled' is not valid for Microsoft Dynamics 365 Business Central Server.
````
Thanks

Kamil Sacek
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d7116b-73f6-2ba6-3c81-3ff9800521e2
* Version Independent ID: 88b013d0-c13c-b578-a0e1-822a2bf6a3e9
* Content: [Setting up App Key Vaults for Business Central on-premises - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/setup-app-key-vault-onprem#configure-the-business-central-server-to-use-the-apps-key-vault-feature)
* Content Source: [dev-itpro/administration/setup-app-key-vault-onprem.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/setup-app-key-vault-onprem.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, 

The `AzureKeyVaultAppSecretsPublisherValidationEnabled` setting was introduced in Business Central 2020 release wave 2 (v17).  In the Business Central Administration tool, it appears as **Enable Publisher Validation** under the **Azure Key Vault Extension Secrets** tab.

**Comment by kine** [comment]
Ok, have this setting meaning for OnPrem at all? How the publisher validation is working in OnPrem? How can publisher "register" the onprem app for such an access? I think it cannot work in OnPrem...

**Comment by jswymer** [comment]
Hello,

We have this section in the docs which might answer your question: [Using Key Vault Secrets in Business Central Extensions - Enable publisher validation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-app-key-vault#validation). 

I hope it helps, otherwise let us know!

**Comment by kine** [comment]
Ok, thanks, missed this. But still not sure how it could help to prevent the "malicious" app to identify itself as app of different publisher (publisher X) and enter the real publisher AAD tenant ID (AAD tenant ID of the company X - which is not secret) when publishing the app, thus getting access to the keyvault. But this is out of scope of the original issue.

Ok, the value is available on OnPrem. This is the "solution" to my issue. I think you can close this.

**Comment by jswymer** [comment]
Hello,

Sorry I couldn't have been more helpful. I ran your issue by the development team. One thing they thought we should make clear is that when Publisher Validation is enabled, you have to provide the AAD tenant ID when publishing an app. You do this by using the [Publish-NAVApp cmdlet](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/publish-navapp) with the -AzureActiveDirectoryTenantId parameter set. 

I made a couple small adjustments to the article, which will be published soon.  Also, if you find that this feature doesn't suit your needs, feel free to make a suggestion at [ideas](https://aka.ms/bcideas).

Thanks for feedback!
