### ISSUE TITLE
Preprocessor-need clarifications

### ISSUE THREAD

**Issue by albgen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1537]
Hello,

Suppose you define some code that runs under DEBUG symbol and some other code that run under for example another symbol called RELEASE.
It is not clear on the documentation how do you switch between those symbols.

 Basically this is a classic example how it is used the preprocessor directives in C# and Visual Studio. You tell the compiler to run some code in one configuration and run some other code in another config. Switching between those configs, currently seems not possible with VS code or at least it is not explained on the doc. Xan you please provide this info?

Thank you

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1d090c6-31b0-9d48-1c14-6d332babdc04
* Version Independent ID: 84c9558d-397f-12b5-7547-984610c8a9c1
* Content: [Preprocessor Directives in AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directives-in-al#conditional-directives)
* Content Source: [dev-itpro/developer/directives/devenv-directives-in-al.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/directives/devenv-directives-in-al.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. This should work like it does in C#. In your app.json you can write "preprocessorSymbols": [ "DEBUG","RELEASE"]. We will update the docs to mention that.

**Comment by albgen** [comment]
Thank yoy.

One suggestion: I think these preprocessor directives should be in the launch.json file
The idea is that you define different config with different symbols.

Thanks

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your suggestion. Since this repo is only for doc issues, I suggest you go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature/change. Thanks again!
