### ISSUE TITLE
App.json

### ISSUE THREAD

**Issue by cboyle02703** [MicrosoftDocs/dynamics365smb-devitpro-pb#1539]
I guess you didn't want to show an example app.json file.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We have not included an example app.json file for several reasons; it can be quite lengthy and with new releases it is quickly outdated. Instead, we've inserted a link to an example app.json file from the Business Central Performance Toolkit that you can see here: https://github.com/microsoft/ALAppExtensions/blob/master/Modules/DevTools/BusinessCentralPerformanceToolkit/app.json.
But there will be many different examples of how this file looks, depending on the complexity of a solution. The topic will be updated with the next doc refresh. Thanks.
