### ISSUE TITLE
HttpClient.Timeout usage.

### ISSUE THREAD

**Issue by wmstreet** [MicrosoftDocs/dynamics365smb-devitpro-pb#154]
Having an issue setting a timeout value for the HttpClient Class.  myHttpClient.Timeout(60); Compiles, but then throws a run time exception.   Also, could someone clarify the type of the parameter to the method.  The documentation indicates seconds, but code assist types the parameter as duration.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We're working on improving the documentation for these classes, these will be available with one of the next refreshes of the docs.
