### ISSUE TITLE
Example seems to suggest that MaxLength is encapsulated in the Comment property

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#1540]
This example: 

`Label 'ALLOWED POSTING DATE', Comment='{MaxLength=30}'`

seems to suggest that MaxLength it not a separate label property, but is encapsulated in the Comment property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15813f6-f9d6-5008-5d18-c69fd4f0f761
* Version Independent ID: 0ac4ae64-4482-818b-b0fd-0b59f7d7a962
* Content: [Label Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/label/label-data-type)
* Content Source: [dev-itpro/developer/methods-auto/label/label-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/label/label-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, the example is misleading and will be fixed with the next doc refresh.
