### ISSUE TITLE
Setcurrentkey with no valid key is possible

### ISSUE THREAD

**Issue by JoergPernberg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1541]
The sentence "If you do not test the return value, a run-time error occurs." is not correct.
You can specify values in setcurrentkey even if there is no key with this values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3deb3a10-af88-008f-dbf0-3cd797f4c0c4
* Version Independent ID: 0d3690ac-c99d-0ad7-d803-c72132e90b34
* Content: [Record.SetCurrentKey Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setcurrentkey-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-setcurrentkey-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-setcurrentkey-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next doc refresh.
