### ISSUE TITLE
SQL Connection Timeout

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1544]
Is it correct that "SQL Connection Timeout" has 1.5 hours value. Shouldn't it be minutes?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fc3b614-8a3a-0858-80e2-781b1b6e1253
* Version Independent ID: eabcadf6-051e-6631-f5d6-16ccdcef62a7
* Content: [Operation Limits in Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/operational-limits-online)
* Content Source: [dev-itpro/administration/operational-limits-online.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/operational-limits-online.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! You're correct. The value is 1.5 minutes. We have fixed the article and the update will be published soon.
