### ISSUE TITLE
Missing description for multi-tenant environments

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#1545]
Hi, what should I set when I am using multi-tenant environment, where each tenant should be connected to different AAD tenant for authentication? (partner hosted onprem multitenant environment)

Thanks

With regards

Kamil Sacek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff0aa19-50aa-c461-cd97-4be8fbe4e393
* Version Independent ID: f72d929a-7fea-246f-8b2e-4f3b14c5c92d
* Content: [User Authentication with Azure AD for Single Sign-on - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory)
* Content Source: [dev-itpro/administration/authenticating-users-with-azure-active-directory.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/authenticating-users-with-azure-active-directory.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

Sorry, the documentation is not clear. We are in the process of updating this content. In the meantime, here is a short explanation of what you can do:
1. Instead specifying the Azure AD Tenant ID in the **WSFederationLoginEndpoint** and **ClientServicesFederationMetadataLocation** settings on the server instance, use the placeholder `{AADTENANTID}`. For example:

   ```powershell
   Set-NAVServerConfiguration -ServerInstance BC -KeyName WSFederationLoginEndpoint -KeyValue "https://login.microsoftonline.com/{AADTENANTID}/wsfed?wa=wsignin1.0%26wtrealm=https://cronusinternationltd.onmicrosoft.com/businesscentral%26wreply=https://cronusinternationltd.onmicrosoft.com/BC170/SignIn"
   ```
   ```powershell
   Set-NAVServerConfiguration -ServerInstance BC -KeyName ClientServicesFederationMetadataLocation -KeyValue "https://login.microsoftonline.com/{AADTENANTID}/FederationMetadata/2007-06/FederationMetadata.xml"
    ```
2. Then, when you mount your tenants, specify the Azure AD Tenant ID. This will replace the `{AADTENANTID}` placeholder. For example:

   ```powershell
   Mount-NAVTenant –ServerInstance BC -Tenant Tenant1 –DatabaseServer ..\BCDEMO -DatabaseName "BC Demo Database" - AadTenantId 1111-aaaa-2222-bbbb-333333333333
   ```

I hope this helps. Thanks for the feedback!

**Comment by jswymer** [comment]
One more thing, in case you weren't aware. You only register an application on one of the Azure AD tenants, and make it a *Mulitenant* application so it is available for the other Azure AD tenants.

**Comment by kine** [comment]
Thanks, 
but I am still getting 

```
The value for the WSFederationLoginEndpoint configuration settings cannot be empty.
```

Our config (edited):
```
key                                               value                                                                                                               
---                                               -----                                                                                                               
AppIdUri                                                                                                                                                              
AzureActiveDirectoryClientCertificateThumbprint                                                                                                                       
AzureActiveDirectoryClientId                      00000000-0000-0000-0000-000000000000                                                                                
AzureActiveDirectoryClientSecret                                                                                                                                      
ClientServicesFederationMetadataLocation          https://login.windows.net/{AADTENANTID}/FederationMetadata/2007-06/FederationMetadata.xml                           
WSFederationLoginEndpoint                         https://login.windows.net/{AADTENANTID}/wsfed?wa=wsignin1.0%26wtrealm=https://XXXXXX/YYYYY%26wreply=https://xxxxxx.ccc/xxx/sssss
```
wtrealm is our AppIdUri used for the multitenant application registered in our Azure AD. (I have followed https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/560 )

Thanks.

**Comment by jswymer** [comment]
Hello, Not sure what's causing this. Does it occur before you see the sign-in page? I can get this error if try to open the Web client without providing the ?tenant=tenantID in the URL or I haven't signed out of an earlier session.

**Comment by kine** [comment]
Hmm,
ok, seems that this is somehow connected to the fact, that we are using the host url to select the tenant (URL Rewrite). it means we have urls like:
tenant1.domain.cloud
tenant2.domain.cloud

and I get the error when I use them. If I add ?tenant=xxx I will not get this error, but another one (Problem detected for the tenant) and in the event log there is error 'Ambiguous tenant selection. Host name points to tenant XX and query parameter points to tenant YY'
where
XX is the "tenant" based on the name used in the replay URL and YY is the one from the parameter. How can I combine this together with the host name base tenant? How to setup correctly the reply url?

**Comment by kine** [comment]
Ok, sorry, my bad. I forget to enable the URL rewrite on the site I created to test this. But still, the reply url problem persists. It means, how correctly setup the reply url when host name based tenant is used (reply url is different for each tenant) - is the reply url mandatory? Somewhere I saw setting without it...

**Comment by jswymer** [comment]
Hi,

Task 3.3 has this statement:

The wreply parameter is optional. The wreply query parameter tells the Azure AD authentication service where to send the authentication token. If you do not specify the wreply parameter, it will be deducted from the URL in the browser.

Maybe be something there?

**Comment by kine** [comment]
Ok, but then I get:

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'xxxxx'.

Does it mean that each tenant must have registered reply URL on the app?

**Comment by jswymer** [comment]
I'll try to run this by the development team, but perhaps this a case for using the -AlternateId parameter of the [Mount-NAVTenant cmdlet](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/mount-navtenant?view=businesscentral-ps-17#parameters).

**Comment by kine** [comment]
Yes, I have the alternate id which is same as the host name for the tenant (e.g. tenant1.xxx.ff).

**Comment by jswymer** [comment]
Hello,

The dev team confirmed that the alternate ID should be used, as you've done. This means that you have to have a valid reply url for each of the tenants dns, because when the web client runs on, for example, tenant1.domain.cloud, it passes tenant1.domain.cloud on as a wreply.

So each address needs to be registered in the Azure AD app reply urls.

**Comment by kine** [comment]
Ok, thanks, include this, please, into the documentation... :-)

I succeeded and the integration is now working on our multitenant env. Thanks!

Summary:

- Application Client ID setting: 00000000-0000-0000-0000-000000000000 (not used)
- Application Client Secret: '' (not used)
- Azure AD App ID Uri: '' (not used)
- WS-Federation Login Endpoint: 'https://login.windows.net/{AADTENANTID}/wsfed?wa=wsignin1.0%26wtrealm=<AppIDUri>'
- WS-Federation Metadata Location: https://login.windows.net/{AADTENANTID}/FederationMetadata/2007-06/FederationMetadata.xml
- AadTenantId parameter set when mounting tenant to the AAD domain ID/Name
- BC Server instance Credential Type: NavUserPassword
- Web Server instance Credential Type: AccessControlService
- User in BC must have set "Authentication Email Address" to AAD login name
- ReplyUrl on the AAD Application used (with the AppIDUri used) must have ReplyURL for each tenant in format 'https://<Tenant alternate id>/BCAAD/SignIn'

hope that I wrote all .

**Comment by jswymer** [comment]
That's good news! Thanks for providing the setup. I am updating the content. 

So just confirm. on the registered application in Azure AD, you added three reply URLs, for example:

- myserver.domain
- tenant1.domain.
- tenant2.domain.

Then, on the server instance you set something like:

`https://login.windows.net/{AADTENANTID}/wsfed?wa=wsignin1.0%26wtrealm=https://XXXXXX/YYYYY%26wreply=https://myserver.domain`

I heard a bit more from the dev team that, in this case, it should be possible to just set "myserver.domain" as the reply URL on the server and on the registered application in Azure AD. The server should then translate tenant1.domain to tenant1.mydomain?tenant=tenant1 and that in turn will append ?tenant=tenant1 to the wreply. But this might not work as expected.

**Comment by kine** [comment]
Yes, I have registered Reply URL on the App for each tenant, and have NOT SET the wreply in the setting of BC Server. It means the setting is only:

```
https://login.windows.net/{AADTENANTID}/wsfed?wa=wsignin1.0%26wtrealm=https://XXXXXX/YYYYY
```

I will try to use some "generic" URL which is not connected to any tenant (not used as alternateId on any tenant) as a wreply in he setting and register it on the app, if it will work. Will inform you...

**Comment by kine** [comment]
Ok, I tested this:

1) Create one host name without connection to any tenant through AlternateID (businesscentral.domain.nam)
2) Registered this as part of the ReplyURL on the App in AAD (https://businesscentral.domain.nam/InstanceName/SignIn)
3) Set the setting on BC Server to
```
https://login.windows.net/{AADTENANTID}/wsfed?wa=wsignin1.0%26wtrealm=https://XXXXXX/YYYYY%26wreply=https://businesscentral.domain.nam/InstanceName/SignIn
````

Seems that it works without need to register replyURL for each tenant - but of course, it will redirect the user to https://businesscentral.domain.nam/InstanceName/?tenant=tenantid

**Comment by jswymer** [comment]
Thanks for trying this out! I've made the dev team aware of your findings. I'll keep you posted with any additional information.

**Comment by jswymer** [comment]
Hello,
We've made significant changes to this article based on this issue. The update will be published soon. Thanks for the feedback!
