### ISSUE TITLE
Please use best practice of placeholder in message

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1547]
Please change this code line

`Message('Hello, world! It is: ' + now.ToString());`

to

`Message('Hello, world! It is: %1 ', now.ToString());`

This is best practice.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6350ffb-3e0f-92de-8455-bbf3a316f62e
* Version Independent ID: 96ee3cfc-16c4-ae11-6a69-15e33ae85c1d
* Content: [Getting started with Microsoft .NET Interoperability from AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-call-dotnet-from-al)
* Content Source: [dev-itpro/developer/devenv-get-started-call-dotnet-from-al.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-get-started-call-dotnet-from-al.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This is fixed with the next doc refresh.
