### ISSUE TITLE
List the different Icons

### ISSUE THREAD

**Issue by JulianTillmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#1548]
Would it be possible to list all the icons in this documentation or somewhere else? It's rather cumbersome to scroll through all images inside the Development Envorinment and it would be nice to have an overview somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31e72d71-172f-e784-eaab-4f4e26897eae
* Version Independent ID: 36635fe0-cfc5-836a-fdd4-98a422cf0309
* Content: [Image Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-image-property)
* Content Source: [dev-itpro/developer/properties/devenv-image-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-image-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by JulianTillmann** [comment]
are these issues even tracked?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. I am sorry we haven't gotten back to you sooner. This seems to be a product idea, to have a preview of the images in VS Code. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
