### ISSUE TITLE
typo -then-

### ISSUE THREAD

**Issue by Peter-plus-is-1** [MicrosoftDocs/dynamics365smb-devitpro-pb#155]
service account for then SQL Server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bcef8a5-d65d-4fba-22cd-438a232f990c
* Version Independent ID: 164e0e97-04a4-1a14-30c4-a92da0ad3315
* Content: [Installation Considerations for Microsoft SQL Server and Microsoft Dynamics NAV - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/installation-considerations-for-microsoft-sql-server)
* Content Source: [dynamics-nav/Installation-Considerations-for-Microsoft-SQL-Server.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Installation-Considerations-for-Microsoft-SQL-Server.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **kepontop**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, this is fixed and merged in our private repo and then pushed live. Thanks again.
