### ISSUE TITLE
Broken link to release plan

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1550]
The link to release plan is broken, it should be with a /smb/ in the path:
https://docs.microsoft.com/dynamics365-release-plan/2020wave2/smb/dynamics365-business-central/planned-features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc577a6-829d-0fdd-2d01-4b4d7e1654e7
* Version Independent ID: dbd80567-539c-e357-d93c-42376d850576
* Content: [Update 17.1 for Microsoft Dynamics 365 Business Central 2020 Release Wave 1 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/whatsnew/whatsnew-update-17-1)
* Content Source: [dev-itpro/whatsnew/whatsnew-update-17-1.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/whatsnew/whatsnew-update-17-1.md)
* Service: **dynamics365-business-central**
* GitHub Login: @EmmaNielsson
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this and providing the right link :). The topic will be updated with the next refresh.
