### ISSUE TITLE
Preprocessor Directives in Launch file

### ISSUE THREAD

**Issue by jrrdk** [MicrosoftDocs/dynamics365smb-devitpro-pb#1551]
Why is it in the app.json file you have to define preprocessor directives symbole and not in the launch configuration it make no sens to me you have to modify the app manifest to define preprocessor directives

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1d090c6-31b0-9d48-1c14-6d332babdc04
* Version Independent ID: 84c9558d-397f-12b5-7547-984610c8a9c1
* Content: [Preprocessor Directives in AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directives-in-al)
* Content Source: [dev-itpro/developer/directives/devenv-directives-in-al.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/directives/devenv-directives-in-al.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The short answer to your question is that this is based on how the compiler works.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
