### ISSUE TITLE
Throws an error

### ISSUE THREAD

**Issue by BrianThorChristensen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1561]
[Enter feedback here]
This page should say that an error is thrown if there is no filter on the specified field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f018aa7b-3398-2dc9-4a43-c459c119568f
* Version Independent ID: 38edf573-7cdf-e1b8-20d7-8a3de9b96da0
* Content: [Record.GetRangeMin Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-getrangemin-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-getrangemin-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-getrangemin-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This is fixed with the next doc refresh.
