### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by JSebastianN** [MicrosoftDocs/dynamics365smb-devitpro-pb#1562]
"abnandon" 😀

Also, does this work for Web-service sessions ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9fd9657-bab8-f124-a370-4683bd43d0cf
* Version Independent ID: 5cfb95fb-0a02-27cd-b92c-3754e53f9cb3
* Content: [SessionSettings.TimeZone Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/sessionsettings/sessionsettings-timezone-method)
* Content Source: [dev-itpro/developer/methods-auto/sessionsettings/sessionsettings-timezone-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/sessionsettings/sessionsettings-timezone-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The method should also work with web service sessions. We have added this info and fixed the typo. The updated article will be published soon.
