### ISSUE TITLE
Interface Page is missing the "APPLIES TO:" section

### ISSUE THREAD

**Issue by dannoe** [MicrosoftDocs/dynamics365smb-devitpro-pb#1563]
The information for which BC versions this is valid is missing.
Most pages have an "APPLIES TO:" at the start of the document.
E.g. I couldn't use this for 140CU6 / 14.7.37609.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74a50675-ddc9-df2c-0c8e-361896f0331b
* Version Independent ID: 89912f08-7252-758d-a02a-e0600159c562
* Content: [Interfaces in AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-interfaces-in-al)
* Content Source: [dev-itpro/developer/devenv-interfaces-in-al.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-interfaces-in-al.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Interfaces in AL were introduced with Business Central 2020, release wave 1. We will update the docs to reflect that with the next refresh.
