### ISSUE TITLE
Inconsistent naming in the script

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#1565]
In the script

```
USE [Business Central Database]  
GO

CREATE ROLE bc_server_runtime
ALTER ROLE db_datareader ADD MEMBER bc_server_runtime
ALTER ROLE db_datawriter ADD MEMBER bc_server_runtime
ALTER ROLE db_ddladmin ADD MEMBER bc_server_runtime
GRANT VIEW CHANGE TRACKING on schema::[dbo] TO  bc_server_runtime
GRANT VIEW DATABASE STATE TO bc_server_runtime
GRANT ALTER ON DATABASE::[Business Central Database] TO bc_server_runtime
GO

CREATE USER [domain\accountname] FOR LOGIN [domain\accountname]  
GO

ALTER ROLE BCServer_runtime ADD MEMBER [domain\accountname] 
GO
```
There is inconsistent naming of the role: bc_server_runtime vs BCServer_runtime in the ALTER ROLE line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db5ca7bd-5e2e-544c-2a4f-5349a9f6f161
* Version Independent ID: 7909d0e4-3797-3cc3-2a37-48a43712452e
* Content: [Provisioning the Dynamics 365 Business Central Server Service Account - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/provision-server-account)
* Content Source: [dev-itpro/deployment/provision-server-account.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/provision-server-account.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
