### ISSUE TITLE
Typo in Syntax example

### ISSUE THREAD

**Issue by SimonOfHH** [MicrosoftDocs/dynamics365smb-devitpro-pb#1567]
If I didn't miss anything the below example (`20180325D`) results in a DateTime for 25th of March, 2018 and not 26th

> The syntax for defining Date format is yyyymmddD, where D is a mandatory letter. For example, 201803**25**D, read as the **26**th of March, 2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8b5aed-979e-b1fe-845f-06008cff98e0
* Version Independent ID: 12bd4c37-f88b-3429-dd9b-d7a2d8fa4002
* Content: [DateTime Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/datetime/datetime-data-type)
* Content Source: [dev-itpro/developer/methods-auto/datetime/datetime-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/datetime/datetime-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
You are absolutely right, thanks for catching this. Will be fixed with the next refresh of the docs. Thanks!
