### ISSUE TITLE
Wrong naming of Parameters for field VALIDATE Subscribers

### ISSUE THREAD

**Issue by RaKuNbg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1569]
The naming of parameter CurrentFieldNo is not correct - it must be CurrFieldNo to work in AL Code.

![image](https://user-images.githubusercontent.com/46022628/101144985-6a463380-3619-11eb-8d9b-5877f283acf1.png)

Please correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 256aabb4-8d5d-cc06-6c1f-5558c668491b
* Version Independent ID: 51d1427c-130d-b5c0-3d04-89c01caa89f8
* Content: [Event Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-event-types)
* Content Source: [dev-itpro/developer/devenv-event-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-event-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This is fixed with the next refresh of the docs.
