### ISSUE TITLE
Inconsistent reference

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#157]
Page is about prefixes; documentation refers to them as tags. Are they prefixes or are they tags?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e572f37f-91f5-e8b2-aa5b-242adb0ad329
* Version Independent ID: 32e50127-f6e4-1107-289e-c0b18b1c2d91
* Content: [Prefix and suffix for naming in extensions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix)
* Content Source: [dev-itpro/compliance/apptest-prefix-suffix.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-prefix-suffix.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for pointing out this inconsistency. It is a prefix or suffix - the topic is updated and pushed live with the next refresh. Thanks again.
