### ISSUE TITLE
Required runtime version

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1570]
Would it be possible to add since which version try methods are available, just like e.g. in https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/byte/byte-data-type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c9b78f4-1a5e-a177-1674-d947b69b56ef
* Version Independent ID: 903a9845-3fdd-21b1-4d6d-08fa02875b0f
* Content: [Handling Errors by Using Try Methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-handling-errors-using-try-methods)
* Content Source: [dev-itpro/developer/devenv-handling-errors-using-try-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-handling-errors-using-try-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. Try methods are available since runtime version 2.0. This will be added to the documentation with the next refresh.
