### ISSUE TITLE
Typo for IsReportFormat of Variant Data Type

### ISSUE THREAD

**Issue by dannoe** [MicrosoftDocs/dynamics365smb-devitpro-pb#1571]
The description for `IsReportFormat` is

> Indicates whether an AL variant contains a **RecordFormat** variable.

but should be

> Indicates` whether an AL variant contains a **ReportFormat** variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0573ed31-a484-b665-0dca-885018a796b3
* Version Independent ID: 3ff5aa86-3516-d9eb-7883-c85ba999090b
* Content: [Variant Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/variant/variant-data-type)
* Content Source: [dev-itpro/developer/methods-auto/variant/variant-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/variant/variant-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this will be fixed with the next refresh.
