### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1572]
It loos like the page is missing some information or images, else we cannot understand what the descriptions are for:
![image](https://user-images.githubusercontent.com/34504100/101366843-bb6a5780-38a5-11eb-9067-38634ea844dd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ba7faa-0990-85f7-acde-2f569c2c6508
* Version Independent ID: 877f2886-264c-34f8-04a4-4dd15b47589c
* Content: [Calculation Formulas and the CalcFormula Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-calculation-formulas-and-the-calcformula-property)
* Content Source: [dev-itpro/developer/devenv-calculation-formulas-and-the-calcformula-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-calculation-formulas-and-the-calcformula-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The content is there, but not formatted correctly in Markdown :) will be fixed with the next doc refresh.
