### ISSUE TITLE
some strange code

### ISSUE THREAD

**Issue by albgen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1574]
[Enter feedback here]
this is not AL programming language.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e8c55c0-782b-f7d7-132c-15818763f7c2
* Version Independent ID: 02d7823a-f4ce-3800-bdf6-2086b1f89000
* Content: [GetImageResource Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-getimageresource-method)
* Content Source: [dev-itpro/developer/methods/devenv-getimageresource-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-getimageresource-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. You're absolutely right, this is marked up wrongly, it is JavaScript code. This will be fixed with the next doc refresh.
