### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1579]
As of BC14 CU17 there are a number of parameters for TXT2AL that are not included in this description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfebcfad-5d9d-5365-5ae0-524780e74355
* Version Independent ID: 0a3a2ef5-ceeb-7b4d-572f-6a80a4c90c46
* Content: [The Txt2Al Conversion Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool)
* Content Source: [dev-itpro/developer/devenv-txt2al-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-txt2al-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We have added the missing parameters to the article. An update will be published soon.
