### ISSUE TITLE
Ambiguous reference

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#158]
Documentation says:
"You must use a prefix/suffix when naming all new objects." 
"When you modify a core Dynamics 365 object..."
but then it says "the prefix must be defined at the control or field level."

So what this means is that ANY object must have its prefix defined "at the control or field level".

What about a page object? What about a codeunit object? How could those prefixed be defined "at the control or field level"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e572f37f-91f5-e8b2-aa5b-242adb0ad329
* Version Independent ID: 32e50127-f6e4-1107-289e-c0b18b1c2d91
* Content: [Prefix and suffix for naming in extensions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix)
* Content Source: [dev-itpro/compliance/apptest-prefix-suffix.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-prefix-suffix.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by ailie13** [comment]
Thank you for your feedback! The topic has been updated and it will be pushed live with the next refresh.
