### ISSUE TITLE
Mention multiple previews

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1580]
It would be helpful to mention (or at least link to) that SaveValues = true will enable the multiple previews feature with BC 17, which can have side effects:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-allowscheduling-property#remarks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dce95ba-a175-0884-d851-173c7c13e897
* Version Independent ID: 711c1256-ed89-152c-3fca-bf11363bdc00
* Content: [SaveValues Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-savevalues-property)
* Content Source: [dev-itpro/developer/properties/devenv-savevalues-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-savevalues-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback and for your patience. This will be included in the article with the next refresh.
