### ISSUE TITLE
Txt2al for BC 2020 Release Wave2

### ISSUE THREAD

**Issue by imbru** [MicrosoftDocs/dynamics365smb-devitpro-pb#1584]
The page does not describe where you can find the Txt2al tool if you are going to convert to BC2020 Release Wave 2. The txt2al tool is not provided on the product DVD for the newest releases ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402665e0-ee3c-027b-a64f-3b4d718f0424
* Version Independent ID: 3d4a0497-8c48-1ebb-cb8c-4471eed7ea3b
* Content: [Code Conversion from C/AL to AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/devenv-code-conversion)
* Content Source: [dev-itpro/upgrade/devenv-code-conversion.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/devenv-code-conversion.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, thanks for the feedback.

The Txt2Al tool that you should use is only available with BC Spring 2019 (version 14). You can find it on the installation media (DVD) in the DVD\RoleTailoredClient\program files\Microsoft Dynamics NAV\140\RoleTailored Client folder. Or, it is installed locally with the Dynamics NAV Development Environment, for example, in the C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client folder.

Regardless of which version you will be upgrading to, you use the Txt2Al tool from version 14. The generated AL will be compatible with later versions for upgrade.

We will update the documentation to make this more clear. I hope this answers your question.

**Comment by jswymer** [comment]
We've made an update to this article, which will hopefully clear things up. The update will be published soon. Thanks for the feedback!
