### ISSUE TITLE
2 Links on 1 line in See Also 

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1587]
This line contains 2 links

EntitySetName Property Developing Extensions

It should be 2 lines, each with one link

EntitySetName Property 
Developing Extensions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9788276f-d5a4-7742-0d2c-75db403698cf
* Version Independent ID: 8cc28734-434b-5795-0fc2-2d64e234e5de
* Content: [API Page Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-pagetype)
* Content Source: [dev-itpro/developer/devenv-api-pagetype.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-api-pagetype.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Topic will be fixed with the next doc refresh.
