### ISSUE TITLE
Additional example needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1588]
The APIVersion can be specified as **one version, or a list of versions**, if the API is supported through multiple versions. The same could also be said for the equivalent API Page topic.

It would be very helpful if there was an example included that showed how to support multiple or a list of versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9788276f-d5a4-7742-0d2c-75db403698cf
* Version Independent ID: 8cc28734-434b-5795-0fc2-2d64e234e5de
* Content: [API Page Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-pagetype)
* Content Source: [dev-itpro/developer/devenv-api-pagetype.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-api-pagetype.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The syntax for APIVersion can be found here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-apiversion-page-property. This topic is updated to reflect that with the next doc refresh. Thanks.
