### ISSUE TITLE
Link to further information

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1590]
Could you please link to this article?
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-working-with-media-on-records

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aef185c-794a-dd4d-e226-8678a9087c04
* Version Independent ID: 8db38723-0f86-bd54-8071-fe7e496b9cc9
* Content: [MediaSet Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/mediaset/mediaset-data-type)
* Content Source: [dev-itpro/developer/methods-auto/mediaset/mediaset-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/mediaset/mediaset-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The topic will be updated with the next doc refresh.
