### ISSUE TITLE
Misc Typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1592]
These lines contains typos

page 500100 **MyPage**
pageextension 500101 MyPageExt extends MyPage

should be

page **50100** MyPage
pageextension **50101** MyPageExt extends MyPage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3bb501-007c-dd1a-66ac-bdbb77d748bb
* Version Independent ID: 3e48a1c7-d767-983e-2597-fb095c28885d
* Content: [Protected Variables - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-protected-variables)
* Content Source: [dev-itpro/developer/devenv-protected-variables.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-protected-variables.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The fixes are in and an update will be published soon.
