### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by javisoft** [MicrosoftDocs/dynamics365smb-devitpro-pb#1593]
Under "Application stack" -> "Application extension" there is a typo:
_extension is required **fro** Microsoft extensions_  should be:
_extension is required **for** Microsoft extensions_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77a0ff77-d5c2-3df3-f7fa-cf5914b69f1d
* Version Independent ID: 7f11e180-b1d1-54d5-4e53-21165472ceaf
* Content: [Install a version 17 update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v17)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v17.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v17.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The typo has been fixed and the update will be published soon.
