### ISSUE TITLE
Formatting and link

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1595]
Hi,

the formatting went wrong here, it should be all code:
![image](https://user-images.githubusercontent.com/34504100/102457287-c8740d00-4042-11eb-87cc-cd2aa1dbb94e.png)

Wouldn't it helpful to link https://freddysblog.com/2020/12/03/run-alvalidation-and-run-alcops/ as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 885cbacd-b3e7-1730-812c-9148ebfc90e9
* Version Independent ID: eb11ce7e-1efb-106c-5d79-19c206860da0
* Content: [Technical Validation Checklist - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission#running-technical-validation-yourself)
* Content Source: [dev-itpro/developer/devenv-checklist-submission.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-checklist-submission.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **freddyk**

**Comment by SusanneWindfeldPedersen** [comment]
You're fast :) thanks for catching this. It was pushed with an update the other day and I was trying to fix another error that our build system gave on indented code blocks, but it resulted in this. Will be fixed with the next doc refresh and yes, a link to Freddy's blog will make sense. Thanks!
