### ISSUE TITLE
The "Style Guide" link does not work.

### ISSUE THREAD

**Issue by salgiza** [MicrosoftDocs/dynamics365smb-devitpro-pb#1596]
Clicking on the links to the "style guide", in the explanation for some of the rules, takes you to an URL that requires an username and password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4cb6345-f9b7-5018-355c-6125088171f9
* Version Independent ID: c7764a10-88ca-8146-6b45-b27e12423ae0
* Content: [CodeCop Analyzer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop)
* Content Source: [dev-itpro/developer/analyzers/codecop.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this has now been fixed.
