### ISSUE TITLE
Report request page triggers are executed on every preview

### ISSUE THREAD

**Issue by SwissSalaryBoris** [MicrosoftDocs/dynamics365smb-devitpro-pb#1597]
Hi

> The request page and the request page triggers **won't be executed** on every preview. The new report instances will receive the request page parameters from the initial request page.

Unfortunately the behavior mentioned in the documentation cited above is not true. On a small sample AL project we can demonstrate that:
https://github.com/SwissSalaryBoris/BCReportRequestPageShowCase

The sample report has a logging functionality on various triggers. If we start the sample report, on the _OnInitReport_ trigger, a GUID is generated as global variable which will be logged together with the related trigger.

Let us go trough the example.

1. We start the report (the main report instance get the guid _68DC39E4..._) and _SomeGlobalVariableA_ is initialized by the trigger _RequestPage-OnOpenPage_
![image](https://user-images.githubusercontent.com/58562631/102497387-de042980-4078-11eb-891e-e9fb74d8687b.png)

2. We change _SomeGlobalVariableA_  and run the preview
![image](https://user-images.githubusercontent.com/58562631/102496321-8c0ed400-4077-11eb-8f9e-6aa6bdfe94a0.png)

3. The preview report instance gets the guid _666707AD..._ and shows the content of the _SomeGlobalVariableA_ as it gets it from the _RequestPage-OnOpenPage_ trigger
![image](https://user-images.githubusercontent.com/58562631/102496690-07708580-4078-11eb-9250-826bd7e50dd6.png)

4. Then we print the main report and get the result we expect, even in the preview
![image](https://user-images.githubusercontent.com/58562631/102496913-50c0d500-4078-11eb-8555-5e73b4d8dba8.png)

As we can see in the log too, the request page triggers will also be executed on the preview run:
![image](https://user-images.githubusercontent.com/58562631/102496971-60d8b480-4078-11eb-85f1-16c114c5ff87.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c95669-cf57-f5a6-cbd2-2ee42f81f740
* Version Independent ID: ba9ab523-41d9-3c7d-7886-89466fe3da4c
* Content: [Report Triggers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-report-triggers#trigger-execution-with-multiple-previews)
* Content Source: [dev-itpro/developer/triggers/devenv-report-triggers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-report-triggers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. I just want to make sure that your example is made with Business Central 2020 release wave 2 (version 17)? Can you please confirm before we investigate further, thanks!

**Comment by SwissSalaryBoris** [comment]
Yes, sorry, I forgot to provide this important detail :)
![image](https://user-images.githubusercontent.com/58562631/102509913-64276c80-4087-11eb-8374-39e2329e6f1f.png)

**Comment by jswymer** [comment]
Hello again,

We've recently published an update to the report triggers article. We hope that this will answer your questions. If you have more feedback, let us know and we'll reopen this issue. Regards.

[Report Triggers and Runtime Operations](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-triggers)
