### ISSUE TITLE
Replace ZIP Stream Wrapper

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1598]
Hi,
this issue applies to a bunch of articles including the current one:
https://docs.microsoft.com/en-us/search/?scope=BusinessCentral&terms=%22Zip%20Stream%20Wrapper%22

In all those, please replace `706 ZIP Stream Wrapper` with `425 Data Compression`, see
https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md#data-compression-module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362b245a-50b0-26e1-7578-03efaae73a70
* Version Independent ID: be84c6ce-f172-3207-2f89-9eeb42484d43
* Content: [Report.RunModal Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-runmodal-method)
* Content Source: [dev-itpro/developer/methods-auto/report/report-runmodal-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/report/report-runmodal-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this will be fixed with the next refresh.
