### ISSUE TITLE
It says available for Environment but cannot get the trial of business central

### ISSUE THREAD

**Issue by amaddev** [MicrosoftDocs/dynamics365smb-devitpro-pb#1599]
[Enter feedback here]

In the link, it say the environment is supported for Thailand. But the I go to https://trials.dynamics.com/ then "GET STARTED" for business central. I got this message below.

We don’t support your country or region yet.
We’ll add more countries and regions in the near future, so come back again. 

Could you help to check please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 360d9409-840a-5ef9-9aa4-b43ed4733e2c
* Version Independent ID: 961502fa-6d30-47fa-8afe-a15a8e521304
* Content: [Country/region availability and supported languages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations)
* Content Source: [dev-itpro/compliance/apptest-countries-and-translations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-countries-and-translations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Dynamics 365 Business Central is available in Thailand, but only through a partner. We're currently working on fixing the https://trials.dynamics.com/ site to be clear on this. Hope this clarifies your question. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
