### ISSUE TITLE
Please add information about new URLs and authorization change in Business Central asked in the linked GitHub questions

### ISSUE THREAD

**Issue by StanislawStempin** [MicrosoftDocs/dynamics365smb-devitpro-pb#16]
https://github.com/Microsoft/AL/issues/2018
https://github.com/Microsoft/AL/issues/1933
https://github.com/Microsoft/AL/issues/1982

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by naveenpinnama** [comment]
HI Stain,

Will this documentation still relavent to BC? Because the format of SOAP url is not same in BC.

https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-publish-web-service

Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We will investigate and update the documentation accordingly if needed. Closing this as this is now added to our backlog. Thanks again.
