### ISSUE TITLE
Upgrade appsource app procedure missing BCAC process

### ISSUE THREAD

**Issue by AskeHolst** [MicrosoftDocs/dynamics365smb-devitpro-pb#1600]
The process of updating using BC Admin Center should be mentioned as the primary option. The uninstall-reinstall comes with a risk if something goes wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac07d83-45c1-324d-d292-b79e04939cdc
* Version Independent ID: 76985863-66fa-1583-7632-27949149d90c
* Content: [Upgrading AppSource Apps in Production - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrade-appsource-app-in-prod)
* Content Source: [dev-itpro/developer/devenv-upgrade-appsource-app-in-prod.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-upgrade-appsource-app-in-prod.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **freddyk**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, using the UI should be stable and we stand by our decision to mention the two ways in this order. Thanks again.
