### ISSUE TITLE
Suggested Edit for Task 3.

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1601]
For [Task 3](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17#task-3-create-empty-extensions-system-base-and-customization-extensions) using the examples for the app.json file caused an error in Task 8 step 3.
> The runtime version of the extension package is currently set to '6.2'. The runtime version must be set to '6.1' or earlier in the app.json file in order to install the extension package on this server.

AL Language extension version is 6.1.381323
BC17 Version 17.2.19367.19735

If I add the line below to the app.json the error goes away.
`"runtime": "6.0"`

I suggest adding these to your app.json examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d341fc60-f5a8-af65-f2a4-80726c3419cf
* Version Independent ID: 761a2e5c-c0e9-47bc-0503-a526eae49697
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application for version 17 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've changed the article to include this information. The update will be published soon.
