### ISSUE TITLE
Confusing misc typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1606]
I'm confused about what the original query code is supposed to be demonstrating. I'm guessing that it is NOT trying to show aggregation, in which case the following typos need to be fixed.

In its current state, the query does not specify the Method property so it does implement aggregate method.

should be

 In its current state, the query does not specify the Method property so it does **not** implement **aggregate** methods.

In addition, the method property should also be removed from the first example

 // Change the value of the property to perform a different aggregate method on grouped columns: Sum, Average, Max, Min, or Count
Method = Sum;

Regardless, the explanation and code need to be fixed so that they are in sync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cd8989-54cc-e96c-c12b-10d5ce791a3e
* Version Independent ID: 54120d28-3288-13bd-bfca-01f3b3021f83
* Content: [Query Totals and Grouping - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-query-totals-grouping)
* Content Source: [dev-itpro/developer/devenv-query-totals-grouping.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-query-totals-grouping.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the valuable feedback! The article has been fixed accordingly and an update will be published soon.
