### ISSUE TITLE
Image is broken in Start designer section

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/dynamics365smb-devitpro-pb#161]
The image found under the Start Designer Section Below the note is broken. The URL does not work https://docs.microsoft.com/en-us/media/new-start-design.gif

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e31ad37-068e-3007-2e46-7afc15f6b73b
* Version Independent ID: cd16bd61-cd0d-be6b-0af7-c1e9d81c81f5
* Content: [Using Designer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inclient-designer)
* Content Source: [dev-itpro/developer/devenv-inclient-designer.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-inclient-designer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for reporting this, what a bummer. It's fixed and pushed live asap. Thanks again.

**Comment by SusanneWindfeldPedersen** [comment]
Topic should be live in a few minutes.
