### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Kushal5** [MicrosoftDocs/dynamics365smb-devitpro-pb#1612]
[Enter feedback here]

Valicate instead of Validate
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46e94f76-2e21-1b6e-3fb7-97ff2f992e7c
* Version Independent ID: 1165050e-a395-14be-3c43-2f613b738d16
* Content: [Application Testing Example: Testing Purchase Invoice Discounts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-test-application-example-purchase-invoice-discounts)
* Content Source: [dev-itpro/developer/devenv-test-application-example-purchase-invoice-discounts.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-test-application-example-purchase-invoice-discounts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be fixed with the next doc refresh.
