### ISSUE TITLE
Random NAV 2018 Web Client Crashes FormNotFoundException

### ISSUE THREAD

**Issue by josephgress2** [MicrosoftDocs/dynamics365smb-devitpro-pb#1619]
Are there any known issues that result in frequent NAV 2018 web client crashes? If so, would you let me know what is causing the crash and how to prevent it?  As background information, we have dozens of modifications in two separate extensions - one created by our VAR and one that I created as an end user developer.  All of the modifications work as desired except for the random web client crashes.

We have experienced these crashes for three extended periods in our test database in 2020 – in late September, in mid November and in late December. This would be very challenging if we were to experience this in our production database.

The crashes appear to occur at random times. For example, I experienced a crash once when I went to the Item List and attempted to set a filter on Item Category Code. However, I tried it again 30 seconds later and NAV did not crash. Another time, I experienced the crash while attempting to personalize a custom page. After I restarted the web client, I was able to personalize the page without crashing.

The crash message says "Sorry, that didn't work. An error has occurred. Restart."

At this point, I am not able to reproduce the issue. The event log contains information about these crashes but I am not sure what it means. Here is the first part from one of the event logs:

Error accessing Website

Raw Url:
Url:
Type: Microsoft.Dynamics.Framework.UI.FormNotFoundException
Message: The logical form as specified in parameter with name 'LogicalControlReference' could not be found in the current session.
StackTrace: at Microsoft.Dynamics.Framework.UI.InteractionParameterHelper.GetLogicalControl(UISession uiSession, ClientLogicalControlReference clientLogicalControlReference) in S:\Depot\NAV\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionParameterHelper.cs:line 82

I would note that this is similar to issue 169 Webclient crash (FormNotFoundException).  However, our crashes occur at random times instead of repeatedly with a specific page.

Can you advise what is causing these web client crashes and how to prevent them.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.

**Comment by josephgress2** [comment]
Susanne,

Would you clarify a couple things for me.  Where does it say that this github repository is for documentation issues only?  Would you clarify that you mean by “documentation issues only”? I would note that the ABOUT section on the repository states

Welcome to the repository for partner-focused content for Microsoft Dynamics 365 Business Central! It also provides a way for you to actively contribute to the current Business Central content.

It does not say anything about “documentation issues only”.

Are there any github repositories where a developer (such as myself) for an end user with 20 years of NAV CSIDE development experience and 3 years of AL development experience can ask questions about issues we are experiencing with NAV extensions?

Is our only option to ask our NAV reseller to submit a ticket with Microsoft?

Thanks,
Joseph Gress
Application Developer
Orca Bay Foods

**Comment by josephgress2** [comment]
One of my colleagues informed me that I should have posted my issue in the Microsoft/AL repository instead of this repository.  Sorry for my confusion.

Thanks,
Joseph Gress
Application Developer
Orca Bay Foods

From: Joseph Gress
Sent: Wednesday, January 6, 2021 10:08 AM
To: 'MicrosoftDocs/dynamics365smb-devitpro-pb' <reply@reply.github.com>; MicrosoftDocs/dynamics365smb-devitpro-pb <dynamics365smb-devitpro-pb@noreply.github.com>
Cc: Author <author@noreply.github.com>; Matt Teemer <mattT@orcabayfoods.com>; Louis Kaplan <louisk@orcabayfoods.com>
Subject: RE: [MicrosoftDocs/dynamics365smb-devitpro-pb] Random NAV 2018 Web Client Crashes FormNotFoundException (#1619)

Susanne,

Would you clarify a couple things for me.  Where does it say that this github repository is for documentation issues only?  Would you clarify that you mean by “documentation issues only”? I would note that the ABOUT section on the repository states

Welcome to the repository for partner-focused content for Microsoft Dynamics 365 Business Central! It also provides a way for you to actively contribute to the current Business Central content.

It does not say anything about “documentation issues only”.

Are there any github repositories where a developer (such as myself) for an end user with 20 years of NAV CSIDE development experience and 3 years of AL development experience can ask questions about issues we are experiencing with NAV extensions?

Is our only option to ask our NAV reseller to submit a ticket with Microsoft?

Thanks,
Joseph Gress
Application Developer
Orca Bay Foods
