### ISSUE TITLE
Please provide screenshot of Gear Icon in context of application

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/dynamics365smb-devitpro-pb#162]
Also please provide a hyperlink or instructions if Gear icon is missing. New Business Central Users will not know what to do.  Please treat the content like Unit Testing in code by always providing the negative path meaning, if you instruct someone to find or click on an item, then please inform them of what to do or expect if that item is missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e31ad37-068e-3007-2e46-7afc15f6b73b
* Version Independent ID: cd16bd61-cd0d-be6b-0af7-c1e9d81c81f5
* Content: [Using Designer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inclient-designer)
* Content Source: [dev-itpro/developer/devenv-inclient-designer.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-inclient-designer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The Gear icon should not be missing, it has been available for many updates now. Do you not see it?

**Comment by SusanneWindfeldPedersen** [comment]
I am closing this issue - the Gear icon should always be available. Thanks.
