### ISSUE TITLE
Web Service Key not accessible

### ISSUE THREAD

**Issue by albgen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1620]
[Enter feedback here]
The instructions are not clear.
You must specify that in order to access the generated key, you must login with that account otherwise you will see only asterix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0617e3b-c3af-7f9e-ec75-6f7c69866287
* Version Independent ID: c6bf5953-2917-9d3d-8dfc-29a2f53b3a1c
* Content: [Web Services Authentication - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/web-services-authentication)
* Content Source: [dev-itpro/webservices/Web-Services-Authentication.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/Web-Services-Authentication.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the valuable feedback. We've made changes to the article to make this clear. The update will be published soon.
