### ISSUE TITLE
Additional See Also section content

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1624]
The help for OData seems to be a little bit fragmented with no comprehensive roadmap topic that I have found. It would be helpful to add the following link, and maybe others to the See Also section

Query options overview: https://docs.microsoft.com/en-us/odata/concepts/queryoptions-overview

That way you would at least have access to general concepts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc2d41b-a16e-2eb8-5acf-963df0a6020b
* Version Independent ID: 337d82f5-41e3-05d0-bde4-1ea6bd61b372
* Content: [Using Filter Expressions in OData URIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris)
* Content Source: [dev-itpro/webservices/use-filter-expressions-in-odata-uris.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/use-filter-expressions-in-odata-uris.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've added the link you suggested. We'll look at possible others when we revisit this content soon.
