### ISSUE TITLE
No feedback mechanism at bottom of page

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1625]
A. Sorry to hijack an existing page, but the following page has no Feedback links at the bottom, so I wasn't sure how to proceed

Query options overview
https://docs.microsoft.com/en-us/odata/concepts/queryoptions-overview

B. My feedback for the Query options overview topic is that it would be nice if there were additional links in the See Also section
    1. Using Filter Expressions in OData URIs: 
       https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris

    2. Something like the nice, concise summary below that I found on a blog post should be included in the topic near the top
**$filter**: specify column name, operator and filter value that you want to apply to the query, join multiple filters together with and/or operators
**$select**: a comma-separated list of columns to return i.e. only return the columns that you are actually interested in
**$orderBy**: specify a column to order the results by – use in combination with $top to get the min/max value of a column in the dataset
**$top**: the number of rows to return
**$skip**: skip this many rows in the dataset before returning – useful if the dataset is too large for the service tier to return in a single call
**$count**: just return the count of the rows in the dataset – if you only want the count there is no need to parse the JSON response and count them yourself

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 645865e2-5892-f8a1-c47d-cc9c0b89e56b
* Version Independent ID: ed9491a0-4d71-de3b-11b6-4cbee3d5a812
* Content: [Using Containments and Associations - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-containments-associations)
* Content Source: [dev-itpro/webservices/use-containments-associations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/use-containments-associations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, 

Sorry, I just want to make sure I understand correctly. Is this a request to change the https://docs.microsoft.com/en-us/odata/concepts/queryoptions-overview or the https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris? If the former, do you have access to the Edit button at the top of the page?

![image](https://user-images.githubusercontent.com/15834167/104022482-a2183c00-51c0-11eb-83fc-00bd4941d6ae.png)

If so, this would be a way to provide feedback for the article.

**Comment by j2associates** [comment]
Hello,

Sorry, what I was trying to say is that most Business Central 365 topics
provide the opportunity to provide feedback via links at the bottom of the
page as displayed in the screenshot below. The little feedback link at the
top of the page takes you to the actual links at the bottom of the page.
The Query Options overview page above does not have the Feedback links at
the bottom of the page so I didn't know how or where to go to provide the
same.

Whatever feedback I posted in the OData uris topic was intended for the
Query Options overview that I had no way to access.

Yes, I do have access to the Edit button, but I don't know what its purpose
is.

Sorry for the confusion.

[image: image.png]

**Comment by jswymer** [comment]
Hello, Thanks for the clarification.

The Query Options overview page is in another documentation set, which is owned by a different Microsoft team. The source articles are stored and managed in a different repository than Business Central.

Not all Microsoft documentation sets, like this one, provide a feedback link on the bottom like BC. In this case, maybe you could use the **Yes** or **No** option under **Is this page helpful?**. When you choose one of these options, I think you're presented with a small text box for additional feedback  Or, you could try to use the **Edit** button. This allows you to add your proposed changes directly in a copy of the source document (it's actually in fork off the main repo), and then submit to the owner team for review. 

You may already be aware of some of this, but I hope it helps.

**Comment by j2associates** [comment]
Thanks for taking the time to respond. I was not aware that the edit button
in the upper right could be used in that manner.

If you should happen to have access to the information I posted in the
wrong place pertaining to the above threads, I would appreciate it if you
could send it to me so that I can post it in the correct place.

Have a great day!

**Comment by jswymer** [comment]
My pleasure, glad we could help. Sorry, I only have access to the information in this post, which you probably do as well. Is this what you mean?

**Comment by jswymer** [comment]
We'll close this issue for now. If you have more feedback or questions on the issue, we'll be happy to open it again.
