### ISSUE TITLE
Topic is incomplete

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1627]
There is no example given for defining a table option field, although it does reference the Purchase Header table Status field in the topic text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 438a22fc-c08d-927a-62f6-70810dd2ef69
* Version Independent ID: 47d47438-f6c9-7509-a768-d7867afdc06f
* Content: [Option Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/option/option-data-type)
* Content Source: [dev-itpro/developer/methods-auto/option/option-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/option/option-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello - thanks for the feedback. Yes, looking back I can see that the NAV documentation had the same sample. In AL the example will lead to a Warning (AL0603) - implicit conversion from a value of type 'Enum "Purchase Document Type"' to a value of type 'Integer', which can lead to unexpected runtime issues. The warning becomes an error in a future release, so I will remove it for now with the next doc refresh.

**Comment by j2associates** [comment]
I'm not sure where to suggest this, but it would be nice if there was a
topic explaining usages of options and enums, when to use each, how to
convert from one to the other, etc.

**Comment by SusanneWindfeldPedersen** [comment]
Yes, I agree. And you're suggesting this in the right forum :) Let me put that on our backlog and then hopefully we'd be able to prioritize that. Thanks.

**Comment by j2associates** [comment]
Appreciate the timeliness of the response.

**Comment by SusanneWindfeldPedersen** [comment]
TFS item added to backlog. Closing this issue as bug is fixed with latest push.
