### ISSUE TITLE
Misc typo and clarification needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1628]
First of all, major kudos for the rewrite of this topic. It is much, much better now.

1. The last sentence under Sample Query, just before the code is very awkward and confusing.

In its current state, the query does not specify the Method property so it does implement aggregate method.

The sample code shown does indeed implement the Sum method.

2. Show the sample customer data in Customer Number order so I can quickly note the sums and counts. Having to scan an unordered list of sample data wastes time and hurts concentration and makes it a lot less intuitive.

Customer_Number | Customer_Name | Qty
20000 | Selangorian Ltd. | 200
30000 | Blanemark Hifi | 150
20000 | Selangorian Ltd. | 300
40000 | Deerfield Graphics | 250
20000 | Selangorian Ltd. | 400
30000 | Blanemark Hifi | 350

should be

Customer_Number | Customer_Name | Qty
20000 | Selangorian Ltd. | 200
20000 | Selangorian Ltd. | 300
20000 | Selangorian Ltd. | 400
30000 | Blanemark Hifi | 150
30000 | Blanemark Hifi | 350
40000 | Deerfield Graphics | 250

3. Sample code
// Change the value of the property to perform a different aggregate method on grouped columns: Sum, Average, Max, Min, or Count

should be

// Change the value of the property to perform a different aggregate method on grouped columns: 
// Sum, Average, Max, Min, or Count

Where ever possible, lines should be split to avoid having to scroll to the right to see sample code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cd8989-54cc-e96c-c12b-10d5ce791a3e
* Version Independent ID: 54120d28-3288-13bd-bfca-01f3b3021f83
* Content: [Query Totals and Grouping - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-query-totals-grouping)
* Content Source: [dev-itpro/developer/devenv-query-totals-grouping.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-query-totals-grouping.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback!

1. I can't see the text in question, but we recently published changes based on [issue 1606](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1606)., so maybe that's why.
2. The items should have been listed in descending order on the QTY column, based on the code example. We have verified this and changed the table accordingly. 
3. Fixed. 

The update will be published soon. Thanks again.
