### ISSUE TITLE
Best Practices: ModifyAll -vs- Looping with Validate/Modify Triggers

### ISSUE THREAD

**Issue by KTL-KSweeney** [MicrosoftDocs/dynamics365smb-devitpro-pb#1629]
Does the ModifyAll method modify records that already match the field value?

Please provide documentation on when ModifyAll method is preferred over looping through records to make changes.

Off the top of my head, I can think of a few cons to using this method:
- This only works on one field per method call; so, worst-case efficiency becomes O(n*f) where **n** is the number of records and **f** is the number of fields modified.
- Devs should typically employ the **Record.Validate()** method to ensure validation triggers proc. This will provide better code extensibility.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebc9f93-2d35-2d05-7c78-84935606ef64
* Version Independent ID: 5cc4c2dd-8882-64b2-199e-7a7104f56f64
* Content: [Record.ModifyAll Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-modifyall-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-modifyall-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-modifyall-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello and thanks for your questions. Trying to address some of them here:
If we update records where the field is already equal to the new value? Yes, we do – we don’t issue a SQL clause that excludes rows where the current value is equal to the new value. A Modify() will update/lock the record even if no value is changed.

As for guidance, we would recommend using ModifyAll() if field validation is not wanted or needed.

The topic will be updated with this information with the next doc refresh. Thanks.

**Comment by KTL-KSweeney** [comment]
Thanks!


Kieran Sweeney
Business Software Consultant
Office:301-360-0001
Direct:301-517-6694
KTL Solutions, Inc. - Disclaimer
 This message contains confidential information and is intended only for the individual(s) addressed in the message. If you are not the named addressee, you should not disseminate, distribute, or copy this e-mail. If you are not the intended recipient, you are notified that disclosing, distributing, or copying this e-mail is strictly prohibited.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this and awaiting push to live.
