### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by eapomazkov** [MicrosoftDocs/dynamics365smb-devitpro-pb#1632]
The method **will return information about extension A**, not B, because ext A is the caller module.
Same typo on page "NavApp Data Type".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b81c298-e28d-c730-6cf4-dd7e77902359
* Version Independent ID: 95cd391f-d495-d41b-f602-d9566e614777
* Content: [NavApp.GetCallerModuleInfo Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/navapp/navapp-getcallermoduleinfo-method)
* Content Source: [dev-itpro/developer/methods-auto/navapp/navapp-getcallermoduleinfo-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/navapp/navapp-getcallermoduleinfo-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this will be fixed with the next refresh.
