### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by tfenster** [MicrosoftDocs/dynamics365smb-devitpro-pb#1634]
I think this is a mistake

![image](https://user-images.githubusercontent.com/15346084/104583236-2fe0a500-5661-11eb-84cc-22266642aea2.png)

And I don't see anything on those topics in the linked document:

![image](https://user-images.githubusercontent.com/15346084/104583317-4981ec80-5661-11eb-85ab-b48c44ddc9d0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 274a9478-07c5-49ce-8f1b-8c770735083a
* Version Independent ID: f4a9c73a-1659-a4b3-0b5a-bd0a72b56d90
* Content: [Performance of Business Central On-Premises Installations - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/performance/performance-onprem)
* Content Source: [dev-itpro/performance/performance-onprem.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/performance/performance-onprem.md)
* Service: **dynamics365-business-central**
* GitHub Login: @KennieNP
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

We have made some improvements to the article. The link should have targeted [Performance Tip for Business Users](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/performance/performance-users). An update will be published soon.
