### ISSUE TITLE
Change links to "Format Property", since it's content has moved

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1635]
The links for "Format Property" on this page are linking to "dev-itpro/developer/properties/devenv-format-property.md", but the content on that page has been updated and moved to "dev-itpro/developer/devenv-format-property.md" in [this commit](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/commit/883e17c96610b63b127dd089b4e5596db7fcc4ff#diff-efca768fc6ce9e807c4b773649c96e0a59f578135453bcc81d1251d3014ba362)

So please, point all links for "Format Property" to "dev-itpro/developer/devenv-format-property.md"

You might want to check if links on other pages that points to "dev-itpro/developer/properties/devenv-format-property.md" should be updated as well, since the content is completely changed.... 

Thanks 
Johannes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c745c7fa-6517-541f-d18a-36226db7fb64
* Version Independent ID: f41b2a8c-8545-a5a2-4550-092786b1fde9
* Content: [System.Format Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for pointing this out and thank you for your patience with the response. All relevant links will be fixed with the next refresh.
