### ISSUE TITLE
Country Code for South Korea is KR, not KO

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1638]
Please change "Environment Country in Tenant Admin Center" for South Korea from KO to KR. (KO is the language, KR is the country)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 360d9409-840a-5ef9-9aa4-b43ed4733e2c
* Version Independent ID: 961502fa-6d30-47fa-8afe-a15a8e521304
* Content: [Country/region availability and supported languages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations)
* Content Source: [dev-itpro/compliance/apptest-countries-and-translations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-countries-and-translations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with next doc refresh.
