### ISSUE TITLE
Example does not match the description

### ISSUE THREAD

**Issue by mpsoares** [MicrosoftDocs/dynamics365smb-devitpro-pb#1641]
For the description:
The following example combines the Get-NAVAppInfo and **Unpublish-NAVApp** cmldets into a single command:

The example is instead using the **Uninstall-NAVApp**
Get-NAVAppInfo -ServerInstance YourDynamicsNAVServer -Name 'My Extension' -Version 1.0.0.0 | **Uninstall-NAVApp**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 224dcbbb-4289-2ac5-8071-1d70d06ccb19
* Version Independent ID: 4f836bf8-7c1d-5060-e8d3-519ac9ebea0d
* Content: [How to Unpublish and Uninstall an Extension v2.0 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-unpublish-and-uninstall-extension-v2)
* Content Source: [dev-itpro/developer/devenv-unpublish-and-uninstall-extension-v2.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-unpublish-and-uninstall-extension-v2.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! We've have made the fix and the updated article will be published soon.
