### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by AllTaken** [MicrosoftDocs/dynamics365smb-devitpro-pb#1642]
Documentation for "Disable SQL Query Hint FORCE ORDER" talks about "OPTIMIZE FOR UNKNOWN".
Same is true for "Disable SQL Query Hint LOOP JOIN"

E.g. it says "If you clear the check box (false), the OPTIMIZE FOR UNKNOWN hint is used in queries." where it probably should say: "If you clear the check box (false), the FORCE ORDER hint is used in queries.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30dd402-c112-00be-9c66-4f8bd6a2184f
* Version Independent ID: 215be880-512c-a76b-5463-bfd1b349dd81
* Content: [Microsoft Dynamics 365 Business Central Server Configuration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-server-instance)
* Content Source: [dev-itpro/administration/configure-server-instance.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configure-server-instance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by AllTaken** [comment]
![image](https://user-images.githubusercontent.com/6959993/104730065-a9e45d00-5739-11eb-90f1-58d804d29d2e.png)

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! We've fixed the article and the update will be published soon.
