### ISSUE TITLE
Can add a DropDown with addlast when there is no DropDown

### ISSUE THREAD

**Issue by HennieBink** [MicrosoftDocs/dynamics365smb-devitpro-pb#1643]
tableextension 50100 CustomerExercise extends Customer
{
    fields
    {
        field(50100; "V02Max"; Decimal) { }
    }
   
    fieldgroups
    {
        addlast(DropDown; V02Max) { }
    }
}

This works only when the is an existing fieldgroup DropDown. 
In most/all cases you want to add a DropDown fieldgroup because there isn't one. 

Please change this so you can add a DropDown when there is no DropDown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9979b71-a2f9-9032-5bba-161f6da5ff63
* Version Independent ID: 7fd0115f-bfec-43e1-e5c3-69bf2e4d383c
* Content: [Field Groups - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-field-groups)
* Content Source: [dev-itpro/developer/devenv-field-groups.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-field-groups.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
This seems to not be documentation related, so closing the issue.
