### ISSUE TITLE
Make sample code easier to read

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1651]
Kudos for the excellent sample code included with this topic!

Example code should be structured, when possible, so that the code does not need to be scrolled to be visible. In light of this, the following code changes would remove the scrollbar.

1. if myAppInfo.DataVersion = Version.Create(0,0,0,0) then // A 'DataVersion' of 0.0.0.0 indicates a 'fresh/new' install

should be

// A 'DataVersion' of 0.0.0.0 indicates a 'fresh/new' install
if myAppInfo.DataVersion = Version.Create(0,0,0,0) then

2. HandleReinstall; // If not a fresh install, then we are Re-installing the same version of the extension

should be

// If not a fresh install, then we are Re-installing the same version of the extension
HandleReinstall;

3. // - Data 'patchup' work, for example, detecting if new 'base' records have been changed while you have been working 'offline'.

should be

// - Data 'patchup' work, for example, detecting if new 'base' records have been 
//        changed while you have been working 'offline'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dd7c9e-51a5-eeea-a2f6-dd4d40b93295
* Version Independent ID: d6fb1d1b-fa2e-606e-6c79-115651b60a29
* Content: [Writing extensions installation code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-install-code)
* Content Source: [dev-itpro/developer/devenv-extension-install-code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-install-code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've changed the article per your suggestions. The update will be published soon.
