### ISSUE TITLE
Missing default value for parameter "SaveRecord"

### ISSUE THREAD

**Issue by stefanoPrimo** [MicrosoftDocs/dynamics365smb-devitpro-pb#1655]
[Enter feedback here]

In the Dynamics NAV doc the default value is True, is still in Business Central? 
ref: https://docs.microsoft.com/en-us/dynamics-nav/update

![image](https://user-images.githubusercontent.com/36199751/105200158-d2a49200-5b3f-11eb-9202-745f73a4bcee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6515aa1-75f5-d10f-fa5e-c31c91006f26
* Version Independent ID: abcdaa06-7059-db42-233a-f0adc57529b7
* Content: [Page.Update Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-update-method)
* Content Source: [dev-itpro/developer/methods-auto/page/page-update-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/page/page-update-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. The short answer is that SaveRecord default value is true. (The longer answer is that the default value of SaveRecord depends on whether SourceTable is specified or not. If SourceTable is not defined (== null) then the default value is false. If SourceTable is specified then the default value is true.) Hope this helps. We will update the topic with one of the next doc refreshes. Thanks.

**Comment by dnpb** [comment]
I have opened https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2129
