### ISSUE TITLE
Embed links are broken

### ISSUE THREAD

**Issue by jpagessummar** [MicrosoftDocs/dynamics365smb-devitpro-pb#1656]
The links of Embed section are not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a949477-f2ae-3884-ef15-9996ef4b05c0
* Version Independent ID: 7d19695e-ef88-fcbb-45d5-feae07ed6a50
* Content: [The SMB opportunity for app publishers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/opportunity-app-publisher)
* Content Source: [dev-itpro/developer/readiness/opportunity-app-publisher.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/opportunity-app-publisher.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **kurtju**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! We'll investigate this and get the links updated in an upcoming doc update. The links point to the AppSource apps, so you might be able to find the right apps there.

**Comment by edupont04** [comment]
Now live.
