### ISSUE TITLE
Code need to modify

### ISSUE THREAD

**Issue by AmolSalvi** [MicrosoftDocs/dynamics365smb-devitpro-pb#166]
This code is not working as not getting record from Application Are Setup for modification and it is throwing error

procedure EnableExampleExtension()
    var
        ApplicationAreaSetup: Record "Application Area Setup";
        ExperienceTierSetup: Record "Experience Tier Setup";
        ApplicationAreaMgmtFacade: Codeunit "Application Area Mgmt. Facade";
    begin
        if ExperienceTierSetup.Get(CompanyName()) then; 
        if not ExperienceTierSetup.Essential then
            exit;

        if ApplicationAreaMgmtFacade.GetApplicationAreaSetupRecFromCompany(ApplicationAreaSetup, CompanyName()) then begin
ApplicationAreaSetup.Get(Companyname(),'','');
            ApplicationAreaSetup."Example App Area" := true;
            ApplicationAreaSetup.Modify();

            // Without this line the app area is enabled only at the next login
            ApplicationAreaMgmtFacade.SetupApplicationArea();
        end;
    end;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a3450e9-9c90-8384-3fd1-0a207713fad6
* Version Independent ID: a0d40f3c-17e3-0024-c845-452b05b47354
* Content: [Extending Application Areas - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-application-areas)
* Content Source: [dev-itpro/developer/devenv-extending-application-areas.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extending-application-areas.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by chethanht** [comment]
@AmolSalvi can you please give more details about the error that you have mentioned in the issue above?
Secondly, the line of code ApplicationAreaSetup.Get(Companyname(),'',''); inside the IF statement does not exist in the documentation.

**Comment by AmolSalvi** [comment]
That's the code which need to add in documentation.
Without .Get statement system is not getting required application area and it throws error that application area setup not found.
I written following code.

If ExperienceTierSetup.Get(CompanyName()) then;
        if not ExperienceTierSetup.Essential then
            exit;
        if ApplicationAreaMgmtFacade.GetApplicationAreaSetupRecFromCompany(ApplicationAreaSetup, CompanyName()) then begin
            **ApplicationAreaSetup.Get(CompanyName(), '', '');**  //Added by me
            ApplicationAreaSetup."DSVC WHT APP AREA" := true;
            ApplicationAreaSetup.Modify();
            ApplicationAreaMgmtFacade.SetupApplicationArea();

**Comment by chethanht** [comment]
ApplicationAreaSetup.GET(CompanyName,'','') should already be called as part of the ApplicationAreaMgmt.GetApplicationAreaSetupRecFromCompany. Can you please try it again and send us the sample extension?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. I am closing this issue as this is not really documentation related. Please use our support channel for further questions. Thanks.
