### ISSUE TITLE
Error in sample code showing line ending

### ISSUE THREAD

**Issue by steveendow** [MicrosoftDocs/dynamics365smb-devitpro-pb#1664]
The code sample on this page show the following value assignments for the CRLF array:

    CRLF[1] := 10;
    CRLF[2] := 13;

The assigned values are backwards.  The values should be 13 first and 10 second.

    CR = 13
    LF = 10

The sample CRLF array value assignment should look like this:

    CRLF[1] := 13;
    CRLF[2] := 10;

ASCII Reference:    http://www.asciitable.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2f4f68-c2ff-18ae-a814-8dbc03c2a322
* Version Independent ID: d1154955-7f82-a233-6b24-6de213debeb4
* Content: [Write, WriteText, Read, and ReadText Method Behavior - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-write-read-methods-line-break-behavior)
* Content Source: [dev-itpro/developer/devenv-write-read-methods-line-break-behavior.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-write-read-methods-line-break-behavior.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for seeing this. It will be fixed with the next refresh.
