### ISSUE TITLE
Additional values needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1665]
This is not huge, but why doesn't the example include ENU and ENC? Examples are readily available in multiple places, but why wouldn't the official topic include values for the most commonly used languages? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bfbb9ca-3b27-7151-5fbc-5986c81f6b23
* Version Independent ID: 03fd2eed-c11c-16b4-9588-26feea722301
* Content: [CaptionML Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-captionml-property)
* Content Source: [dev-itpro/developer/properties/devenv-captionml-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-captionml-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback and for your patience. Examples using ENU and ENC have been included and will be available with the next refresh.
