### ISSUE TITLE
Move Appsource and .xliff translation files to the very top of the page

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1666]
I know the Note about AppSource and .xliff files is near the top of the topic, but it is not visible when the page is first loaded. 

A. Please consider moving the Note to the very top of the page to ensure that no one misses it.

B. It would also be helpful if the Working with Translation Files link was include in the See Also section.

C. Does this mean that CaptionML will be deprecated in the future? 
    1. If so, please provide a note to that effect.
    2. If not,
        a. Is it just a matter of for AppSource or not for AppSource
        b. Otherwise, could the topic be expanded to include some discussion about when and where each should be used and 
            what is the best practice.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bfbb9ca-3b27-7151-5fbc-5986c81f6b23
* Version Independent ID: 03fd2eed-c11c-16b4-9588-26feea722301
* Content: [CaptionML Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-captionml-property)
* Content Source: [dev-itpro/developer/properties/devenv-captionml-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-captionml-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. Properties topics are auto-generated, which means that the content is reflected 100% from code - the way we auto-generate, it is not possible to insert a note closer to the top than what's already done, unfortunately. This is a limitation that we have to live with. The Working with Translation Files topic which is linked to in the note describes the current guidance. Thanks.
