### ISSUE TITLE
Additional topic content

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1667]
1. It would be helpful if there was a note somewhere that this technique replaces the old CapionML property in AppSource.
2. Does this mean CaptionML will be deprecated in the future? If so, a note to that effect would be helpful.
3. If CaptionML is not scheduled to be deprecated, is the new best practice for multi language support? If so, say so please.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We actually did have a note about CaptionML being deprecated and XLIFF being the new way to handle translations. This was removed a while back; the feedback from some partners was that they were not ready for that change. So, instead we still support both ways. I believe that the note about XLIFF and AppSource is there, in this section (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#generating-the-xliff-file). The guidance might change in the future, but this is what we can provide at this moment, unfortunately. Thanks.

**Comment by j2associates** [comment]
Thanks for the explanation, but it just seems like there should be a little note in the CaptionML topic mentioning that you must use XLIFF files for AppSource and then maybe link to the topic you referenced above. 

In any event, thanks for all you do. Your name shows up a lot in the docs.

**Comment by SusanneWindfeldPedersen** [comment]
Thank you :)
There's already a note in the topic: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-captionml-property#remarks. Does that suffice? I understand if this can be confusing, and I am happy to help out if there's some information gap. Thanks.

**Comment by j2associates** [comment]
Thanks, there is a note further down in the topic that specifically
mentions CaptionML, etc.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue
