### ISSUE TITLE
Wrong link to Format information

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#1672]
The link in 

> For the Format parameter, see Format Property for more information.

refers to the Format property for XmlPort elements, not the intended page for general formatting information, which is likely to be https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-property. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c745c7fa-6517-541f-d18a-36226db7fb64
* Version Independent ID: f41b2a8c-8545-a5a2-4550-092786b1fde9
* Content: [System.Format Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue will be fixed with the next doc refresh.
