### ISSUE TITLE
"Designer" key in navsettings.json not detailed

### ISSUE THREAD

**Issue by mtaanquist** [MicrosoftDocs/dynamics365smb-devitpro-pb#1673]
Missing documentation about the "Designer" key in navsettings.json (and possibly other keys?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a37d8a7-4a5a-37c8-df1c-4dd28e37c360
* Version Independent ID: badd39bf-9d13-e0d4-0138-8cd9920b3a9f
* Content: [Configuring Business Central Web Server instance - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-web-server)
* Content Source: [dev-itpro/administration/configure-web-server.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configure-web-server.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've added the "Designer" key and will try to keep this article up to date. The update will be published soon.
