### ISSUE TITLE
OdataV4 doesnt return atompub documents

### ISSUE THREAD

**Issue by Joerio** [MicrosoftDocs/dynamics365smb-devitpro-pb#1675]
Business Central is deprecating V3 of OData. V3 is returning atom documents as described, however V4 seems to ignore the $format parameter and you have no way of getting an atompub document.
This isn't reflected at all in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8c71eac-5ea4-6763-ab3d-c616b627e14d
* Version Independent ID: 6d25ae53-dcd0-729b-6773-e05ea8da021d
* Content: [How to: Use OData to Return-Obtain an AtomPub Document - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/return-obtain-an-atompub-document)
* Content Source: [dev-itpro/webservices/return-obtain-an-atompub-document.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/return-obtain-an-atompub-document.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've have made it more clear that this article applies only to OData V3. The update will be published soon.
