### ISSUE TITLE
[Improvement Request] Upgrade Steps - Code to Copy

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#1676]
In the Upgrade Steps, there are lots of bits of code you can copy, which is fantastic.

It occurred to me while using the guide, if the text containing "\<server instance name\>" was instead changed to "$serverInstanceName", when you're working through these scripts in order, if you assigned the value of your $serverInstanceName at the beginning, code that relies on that variable would be instantly runnable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e435e27-0b74-7dcd-555d-977517fd3774
* Version Independent ID: ea922161-12f9-3f86-69f9-2044369d6574
* Content: [Upgrade an unmodified application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by JeremyVyska** [comment]
I think the markdown mangled that one a bit.

I was referring to replacing the text **\<server instance name\>** with $serverInstanceName

**Comment by JeremyVyska** [comment]
As I follow the guide for v18, I find myself desperately wishing this was done.   If all the \<\> tagged items were PowerShell variables, we could just set things, copy and paste all the steps.

**Comment by edupont04** [comment]
Hey @JeremyVyska 
We have a first stab at this here:
[https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v18#powershell-variables-used-in-tasks](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v18#powershell-variables-used-in-tasks)

Does that reflect what you were asking about? If so, we'll continue with sections like that :-)

**Comment by JeremyVyska** [comment]
Yas!  That is amazing and perfect.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this
