### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by equisyscr** [MicrosoftDocs/dynamics365smb-devitpro-pb#168]
To have the factbox displayed, you need this additional property in the FactBox area control:
ApplicationArea = All;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 605a1acd-e3b5-7f1b-bdc8-335ff00fb141
* Version Independent ID: 7eb6b1f3-55f5-8ec0-d5fc-89d82decea57
* Content: [Adding a FactBox to a Page - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-a-factbox-to-page)
* Content Source: [dev-itpro/developer/devenv-adding-a-factbox-to-page.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-a-factbox-to-page.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been corrected and the update will be available soon.
