### ISSUE TITLE
Correct code example

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1681]
The code example does not compile in line
`Answer := YesNo.FromInteger(10); // Ordinal value for 'No'`

You'd need to use instead
`Answer := Enum::YesNo.FromInteger(10); // Ordinal value for 'No'`

See also https://github.com/microsoft/AL/issues/6003

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f34d30c-00f5-9b4b-2d5e-e38525b7b098
* Version Independent ID: c1b7c216-90b0-432b-6833-c581ff89b63b
* Content: [Enum.FromInteger Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/enum/enum-frominteger-method#example)
* Content Source: [dev-itpro/developer/methods-auto/enum/enum-frominteger-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/enum/enum-frominteger-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks so much for your input, and sorry for the very delayed response. This is fixed with the next doc refresh.
