### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1686]
The link in the Remarks section to the " Format Method (Integer, Text)" article is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 286fe842-d3a2-ba49-77d4-4513e2ce350a
* Version Independent ID: dfc559a5-1f4c-8a61-7b58-76f5d2771397
* Content: [Format Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-property)
* Content Source: [dev-itpro/developer/devenv-format-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-format-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks! The link has been fixed and an update will be published soon.
