### ISSUE TITLE
This doc is for NAV not for Business Central

### ISSUE THREAD

**Issue by salgiza** [MicrosoftDocs/dynamics365smb-devitpro-pb#169]
This document explains how to implement OData V4 Bound Actions using the old NAV Development Environment. 

It would be nice to know whether this functionality still exits in BC, and how it would be implemented using Visual Studio Code and the AL Extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b3196a-00cc-3382-f040-ef813b4029e4
* Version Independent ID: cbd09737-7acd-2534-d9aa-96a8b34c8c4f
* Content: [Walkthrough: Creating and Interacting With an OData V4 Bound Action - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action)
* Content Source: [dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Yes, this particular topic is for on-premises. We have a topic for AL here: [Creating and Interacting with an OData V4 Bound Action](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-bound-action). Thanks.

**Comment by jhoek** [comment]
@Susanne I think by now, the information is simply outdated, regardless of your deployment target (cloud/on-premises).
