### ISSUE TITLE
Example needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1697]
A simple example would be very helpful here. Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eba62cb1-b031-8836-e164-28229fc2d983
* Version Independent ID: c746c714-2e9d-245a-aa8e-6b97fe26064b
* Content: [Page.SetSelectionFilter Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-setselectionfilter-method)
* Content Source: [dev-itpro/developer/methods-auto/page/page-setselectionfilter-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/page/page-setselectionfilter-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. An example will be added with the next refresh.
