### ISSUE TITLE
Guid Data Type Compatibility Example Typo

### ISSUE THREAD

**Issue by eapomazkov** [MicrosoftDocs/dynamics365smb-devitpro-pb#1699]
In section **Compatibility** sentence
'**Assigning a GUID to a Text** can be done as follows'
is followed by a code example of **assigning a Text to a GUID**, which is opposite.
The correct description is
'Assigning a Text to a GUID can be done as follows'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8805d123-2953-cb91-1894-ec6ec2bbede4
* Version Independent ID: f7e40620-a112-7f91-e75f-abc9666abd7a
* Content: [Guid Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/guid/guid-data-type)
* Content Source: [dev-itpro/developer/methods-auto/guid/guid-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/guid/guid-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue will be fixed with the next doc refresh.
