### ISSUE TITLE
Examples not adjusted to Business Central

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#170]
The examples given are not correct in Business Central context. 

Correct is (tested):
PRODUCTNAME.FULL: Microsoft Dynamics 365 Business Central
PRODUCTNAME.MARKETING: Microsoft Dynamics 365 Business Central
PRODUCTNAME.SHORT: Dynamics 365 Business Central

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb9c4242-b992-677a-5776-af3e60e05a49
* Version Independent ID: 6bae15cf-c9fe-3bd6-1044-b4e68d1218f3
* Content: [PRODUCTNAME Methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-productname-method)
* Content Source: [dev-itpro/developer/methods/devenv-productname-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-productname-method.md)
* Service: **dynamics365-financials**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The examples have been corrected and the fix will be published soon.
