### ISSUE TITLE
Can't remove base applications before upgrade (BC 17.0 -> 17.*)

### ISSUE THREAD

**Issue by krregg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1700]
I have a problem when I try to upgrade Business Central from 17.0 to 17.4. When I want to prepare BC170, that means I want to uninstall and unpublish all apps, I get the error when unpublishing System Application, Base Application, or Application:

```
Unpublish-NAVApp : The Extension cannot be unpublished because it is in use by 
the following tenants: default
At line:1 char:1
+ Unpublish-NAVApp -ServerInstance $serverInstance -Name Application
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Unpublish-NAVApp], Invali 
   dOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$bc170/nav-systemappli 
   cation,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.UnpublishNavApp
```
Tenant default does not exist, and I am stuck at this point.

Here below are the steps I take to process the upgrade. I am working with multitenant.
```
# 1. step: Uninstall all apps from all tenants

$tenants = "t1,t2,t3"

foreach ($tenant in $tenants.Split(",")) {

    Get-NAVAppInfo -ServerInstance $serverInstance -Tenant $tenant -TenantSpecificProperties |  where { $_.Tenant -eq $tenant } | ForEach-Object { Uninstall-NAVApp -ServerInstance $serverInstance -Tenant $tenant -Name $_.Name -Force }
    Get-NAVAppInfo -ServerInstance $serverInstance -Tenant $tenant -TenantSpecificProperties |  where { $_.Tenant -eq $tenant } | ForEach-Object { Unpublish-NAVApp -ServerInstance $serverInstance -Tenant $tenant -Name $_.Name }
    Uninstall-NAVApp -ServerInstance $serverInstance -Name "Application"  -Tenant $tenant -ErrorAction SilentlyContinue
    Uninstall-NAVApp -ServerInstance $serverInstance -Name "Base Application" -Tenant $tenant -ErrorAction SilentlyContinue
    Uninstall-NAVApp -ServerInstance $serverInstance -Name "System Application" -Tenant $tenant -ErrorAction SilentlyContinue

}

Unpublish-NAVApp -ServerInstance $serverInstance -Name "Application" -Version 17.0.16993.0
Unpublish-NAVApp -ServerInstance $serverInstance -Name "Base Application" -Version 17.0.16993.0
Unpublish-NAVApp -ServerInstance $serverInstance -Name "System Application" -Version 17.0.16993.0

foreach ($tenant in $tenants.Split(",")) {
	Get-NAVTenant -ServerInstance $serverInstance -Tenant $tenant | format-table id, state, databasename, DatabaseServer
	Dismount-NAVTenant -ServerInstance $serverInstance -Tenant $tenant -Force
}

Stop-NAVServerInstance -ServerInstance $serverInstance

# 2. step: install BC17.4
# 3. step: upgrade database
# 4. step: reinstall system, system application, base application, application
# 5. step: mount tenants
# 6. step: install per tenant apps
```

I can skip unpublishing System Application, Base Application, or Application and proceed with the process. I can install the new version of System Application, Base Application or Application, symbols, and other apps, but I can never unpublish the old version of System Application, Base Application, or Application.

How can I remove System Application, Base Application, or Application for 17.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77a0ff77-d5c2-3df3-f7fa-cf5914b69f1d
* Version Independent ID: 7f11e180-b1d1-54d5-4e53-21165472ceaf
* Content: [Install a version 17 update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v17)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v17.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v17.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback. I could also reproduce this issue. I think this can happen if you migrate an existing single-tenant database to a multitenant database deployment, and you don't uninstall extensions before you make the split. For example, if you followed [these guidelines](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/separating-application-data-from-business-data). 

The problem here is that there are tables in the db, like the Installed Applications table, which will still include records for the  "default" tenant. Then, when you do operations like unpublishing or repairing an app, you hit this problem.

**Comment by krregg** [comment]
Thank you @jswymer for your reply. 

What you are saying is true. When we switched to multitenant we probably didn't remove all apps before. I tested on the default Cronus database the same script I used a few months ago and I hit the same problem when I try to upgrade.

Is it safe to remove entries where the tenant is set to default from table [Installed Application] manually in my case?

**Comment by jswymer** [comment]
Hello,

I spoke with the development team, and as long as the "default" tenant is not used, then it should be safe to delete it's entries.

**Comment by jswymer** [comment]
Hello, We hope this has helped. 

We've updated the [these guidelines](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/separating-application-data-from-business-data) to include a step to uninstall extensions, which should hopefully prevent others from having the same problems going forward. The updated article will be available soon.

We'll close this issue, but if you have more comments, please let us know and we'll open it again. Thanks for the feedback!

**Comment by krregg** [comment]
Thank you for the information.

I would just like to mention, that after you remove items from table [Installed Application] that are related to tenant default, you have to run a command to unpublish System Application, Base Application, or Application. Only clearing the table in DB is not enough.

I think we can close this issue now.

Thank you for the help @jswymer!
