### ISSUE TITLE
Topic incomplete

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1702]
The following pertains to a format number according to the topic. But there is no list defining the valid numbers and how they format.

This optional parameter specifies the format that you want to use.

Should this link to Format Property be included? 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d597e2a-5db8-0651-a063-bbece8ef89a9
* Version Independent ID: 8c4a04e2-ea61-16e2-9c9d-903c244c9a13
* Content: [System.Format Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-format-joker-integer-integer-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-format-joker-integer-integer-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/system/system-format-joker-integer-integer-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
thanks for the feedback, this was fixed with an earlier refresh.
