### ISSUE TITLE
OnPrem note needed for clarification

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1708]
The example assignment code samples include references to the file system, which is not allowed in the cloud version. There should be an OnPrem only note to avoid confusion. Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4112e1e-236f-8e96-5407-ab4796e5ecf8
* Version Independent ID: 2c99e7d0-d60b-57f5-20ba-8d31abcb0594
* Content: [TryFunction Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-tryfunction-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-tryfunction-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-tryfunction-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Can you please elaborate, the topic this is filed on doesn't seem to have a code example with reference to the file system?

**Comment by j2associates** [comment]
Good morning,

My apologies, I believe I may have posted from this link accidentally. AL
Simple Statements:
https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-simple-statements.md
.

I would have the same comment for that topic as well.

Have a great day!

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the clarification, we've added a note with the next doc refresh. Thanks!
