### ISSUE TITLE
Please consider adding += and -= examples

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1709]
It would be helpful to include += and -= examples in the assignment section, especially for strings, which is not intuitive.

Counter += 1;
Counter -=1;
Text += 'Hello ';
Text += 'World;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4112e1e-236f-8e96-5407-ab4796e5ecf8
* Version Independent ID: 2c99e7d0-d60b-57f5-20ba-8d31abcb0594
* Content: [TryFunction Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-tryfunction-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-tryfunction-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-tryfunction-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. A small section has been added within [Assignment statements](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-simple-statements#assignment-statements) showing this, which will be available with the next refresh. Some code examples across the documentation have been modified to use this notation where relevant.
