### ISSUE TITLE
Return Value clarification needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1712]
A return value is a defined by a name, data type, and optional length depending on the data type.

I believe the name is optional because you can still use exit(blah blah blah) to return a value. Or will the exit statement be deprecated down the road which would require a named return value? Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f33c0c-cd0d-28b2-d09d-5f17f93223b0
* Version Independent ID: d74d84ee-6fde-7f73-e2c2-50a3992c2fb8
* Content: [Working with AL methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-methods#Callmethod)
* Content Source: [dev-itpro/developer/devenv-al-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue will be fixed with the next doc refresh.

**Comment by j2associates** [comment]
Hello,

I noticed a typo that I missed earlier in this topic. There should be no a
after value is defined by a

A return value is *a* defined by a name, data type, and optional length
depending on the data type.
