### ISSUE TITLE
Decorating a method is not defined

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1715]
For example, decorating a method with the Integration attribute sets the method to be an event publisher. 

The above line uses the term **decorating a method** without defining it. I would suggest adding something like the following before the above line

Placing an attribute on a method is termed decorating the method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86beb5d6-159d-d085-fd1a-ce53327fa152
* Version Independent ID: 45b0caf5-4a2c-8128-10c7-2c4795e47594
* Content: [Method Attributes - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-method-attributes)
* Content Source: [dev-itpro/developer/methods/devenv-method-attributes.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-method-attributes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue will be fixed with the next doc refresh.
