### ISSUE TITLE
Can methods have multiple attributes assigned to them

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1716]
I know that underlying c# code allows multiple attributes. Does AL code allow this? If so, it would be helpful if that was mentioned here and perhaps a simple example mentioned. Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86beb5d6-159d-d085-fd1a-ce53327fa152
* Version Independent ID: 45b0caf5-4a2c-8128-10c7-2c4795e47594
* Content: [Method Attributes - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-method-attributes)
* Content Source: [dev-itpro/developer/methods/devenv-method-attributes.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-method-attributes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The method attributes that you find in the docset under https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-method-attributes in the table of contents to the left, are 100% reflected on the source code, so these are the attributes supported by AL. Thanks.
