### ISSUE TITLE
incorrect indenting in case sample code

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1717]
I believe the else in this and other case examples in the topic should be aligned with the case and end statements.

case <Expression> of  
    <Value set 1>:  
        <Statement 1>;  
    <Value set 2>:  
        <Statement 2>;  

    <Value set n>:  
        <Statement n>;  
    [else  
        <Statement n+1>]  
end;  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f33c0c-cd0d-28b2-d09d-5f17f93223b0
* Version Independent ID: d74d84ee-6fde-7f73-e2c2-50a3992c2fb8
* Content: [Working with AL methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-methods#Callmethod)
* Content Source: [dev-itpro/developer/devenv-al-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - can you please elaborate - there doesn't seem to be a statement in the topic that fits this comment?

**Comment by j2associates** [comment]
My apologies, I don't know how I added so many cross linked feedback posts.

I believe this came from the topic AL Control Statements:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-control-statements.
I believe the case else should be alighted as
case
   ...
else
end;

**Comment by SusanneWindfeldPedersen** [comment]
Good catch, will be fixed with the next doc refresh. Thanks.
