### ISSUE TITLE
Azure Active Directory Authentication

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#172]
Many features on this list require AAD Authentication for OnPrem.
I couldn't find a specific topic page that addresses how to deploy that method. Does such a page exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db917c4-601c-b6f1-863f-17b83d35e814
* Version Independent ID: 22279a66-57b2-7f98-16b6-3cfb394b7fda
* Content: [Features not implemented in on-premises deployments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/features-not-implemented-on-premises)
* Content Source: [dev-itpro/features-not-implemented-on-premises.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/features-not-implemented-on-premises.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Bleika,

You can find information about AzureActive Directiory here: https://docs.microsoft.com/en-us/azure/active-directory/

**Comment by Bleika** [comment]
Thank you Eva,
Actually, I was refering to the specifics on BC OnPrem + AAD Authentication.
Today I found what I was looking for, but you might consider adding a link to it from the page that lists the limitations for OnPrem, or adding a topic in the IT TOC under OnPrem, because it doesn't show up in search on Docs:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory
