### ISSUE TITLE
choice of "runtime": Please provide best practices

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1725]
This issue has been created on request by @atoader in https://twitter.com/AlexToader13/status/1361918362666868739?s=20.

![image](https://user-images.githubusercontent.com/34504100/108168507-b7558400-70f7-11eb-8736-d698b85f12ea.png)

Could you please elaborate which runtime to choose? The community apparently is missing some guidance on best practices for that topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, Natalie. Will have a talk with Alex to gather some more best practices, if possible.

**Comment by NKarolak** [comment]
Any news on that topic?

**Comment by SusanneWindfeldPedersen** [comment]
We have pushed the following topic live: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-choosing-runtime - this topic contains the information that we've gathered internally for choosing runtime.
