### ISSUE TITLE
RecordRef FieldCount Typo 

### ISSUE THREAD

**Issue by eapomazkov** [MicrosoftDocs/dynamics365smb-devitpro-pb#1730]
'Gets the number of fields in the table that **are** currently selected'
should be
'Gets the number of fields in the table that **is** currently selected'

The sentence is a bit confusing at the moment as it implies you need to somehow select the fields you want to count.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ccff5f-bcd0-3bae-f030-7c0da4ee6c41
* Version Independent ID: 7c52cd97-79c7-3d93-0f1d-ed72f2e61250
* Content: [RecordRef.FieldCount Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-fieldcount-method)
* Content Source: [dev-itpro/developer/methods-auto/recordref/recordref-fieldcount-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/recordref/recordref-fieldcount-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for noticing this, it will be fixed with the next refresh.
