### ISSUE TITLE
This Page should be in the TOC.

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#1731]
This Page should be in the TOC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a67f630a-2e23-ba6c-a722-e3de1edc3830
* Version Independent ID: 407d6ebf-41ac-24d8-803e-144da841937f
* Content: [Using Filtering with APIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-connect-apps-filtering)
* Content Source: [dev-itpro/developer/devenv-connect-apps-filtering.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-connect-apps-filtering.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. It will be with the next refresh of the docs.
