### ISSUE TITLE
Text.TrimStart() and Text.TrimEnd() have wrong documentation for return value

### ISSUE THREAD

**Issue by dtkb** [MicrosoftDocs/dynamics365smb-devitpro-pb#1733]
* https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-trimstart-method
* https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-trimend-method

The blurb states

> Removes all **leading occurrences of a set of characters specified** in an array from the current Text object.

but the Return Value section says

> Result: Type: Text A copy of this string **without all leading white-space characters**.

The pages should state that the result is a copy of the string but with the leading/trailing end stripped of all characters specified in the `Chars: Text` array parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d1741f-fa24-f1a6-9dfe-9bfc34e00ceb
* Version Independent ID: 3aac0cbc-3198-43b5-e63b-f1b3d5f94304
* Content: [Text.TrimEnd Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-trimend-method)
* Content Source: [dev-itpro/developer/methods-auto/text/text-trimend-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/text/text-trimend-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Thanks for your feedback, both pages will be fixed with the next doc refresh.
