### ISSUE TITLE
Available Properties in Page-Extensions

### ISSUE THREAD

**Issue by MAC-Christian** [MicrosoftDocs/dynamics365smb-devitpro-pb#1734]
Hi,

is this page up-to-date? In the column "Available for Page Extension Object" are properties marked as not available in page-extensions, which in fact are available to use.
Examples: ShowMandatory, Editable, BlankZero

bg,
christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2612295b-ecb2-93f1-2097-c5e055ed5123
* Version Independent ID: ec810858-2ada-8915-c110-7634c6b791b4
* Content: [Page, Page Fields, and Page Extension Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-property-overview)
* Content Source: [dev-itpro/developer/properties/devenv-page-property-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-page-property-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This page is manually maintained, and it is not up-to-date. With our next major release we're pushing a set of auto-generated properties topics and these pages will go away. The properties will be alphabetically sorted and each property states where and how it can be used instead.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this one as we plan on refreshing with a different structure as explained above. Thanks.
