### ISSUE TITLE
Small Typo in HandlerFunctions Syntax

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#1735]
[Enter feedback here]

Syntax has a typo, should have closing quote and parens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ac3c49-5fb3-f8b7-bbf0-d26302d10909
* Version Independent ID: a476e9b7-49a7-3bc4-dd52-50557de39b5f
* Content: [HandlerFunctions Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-handlerfunctions-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-handlerfunctions-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-handlerfunctions-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Thanks for noticing this, it will be fixed with the next refresh.
