### ISSUE TITLE
Article not found when searching for preprocessorSymbols

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1737]
If searching the docs for `preprocessorSymbols`, this article (specifically: section [Defining Symbols](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directives-in-al#defining-symbols)) won't be found.
Found instead will be only https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files. Although that page links to the current article, could you please add this page to the preprocessorSymbols search result set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1d090c6-31b0-9d48-1c14-6d332babdc04
* Version Independent ID: 84c9558d-397f-12b5-7547-984610c8a9c1
* Content: [Preprocessor Directives in AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directives-in-al)
* Content Source: [dev-itpro/developer/directives/devenv-directives-in-al.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/directives/devenv-directives-in-al.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I have tried to optimize more for this by including it in the descriptive text - this should pick up in Search once it is pushed live. Closing this for now. Thanks.
