### ISSUE TITLE
Query object ColumnFilter property

### ISSUE THREAD

**Issue by GarethFox-TTL** [MicrosoftDocs/dynamics365smb-devitpro-pb#1739]
The documentation page provides no examples, it's not clear how to use the feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9de91f0-15a0-83fa-23f1-076d839eb0dc
* Version Independent ID: 47bf1b33-2bc9-e970-3876-7da1a8606db4
* Content: [ColumnFilter Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-columnfilter-property)
* Content Source: [dev-itpro/developer/properties/devenv-columnfilter-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-columnfilter-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

We have a more detailed example [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-query-filters#columns), which should provide more insight into how to use this property. We've added a link to this example from ColumnFilter property article, plus links to other query-related articles. We hope this helps. The update will be published soon. Thanks for the feedback! If you have more input, we'll be happy to reopen this issue.
