### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#174]
Under "See Also", the link for "FAQ for developing in AL" results in HTTP-404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0ef3bc-7516-dae7-6cca-d5a9b680364f
* Version Independent ID: 288d30ad-0b2d-8c18-63fa-d5555eb7416e
* Content: [FAQ about developer and IT-Pro experiences - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/faq)
* Content Source: [dev-itpro/faq.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thanks for catching this! A fix is ready and will be part of our next update later today.
