### ISSUE TITLE
Link to example is not working

### ISSUE THREAD

**Issue by mynavblog** [MicrosoftDocs/dynamics365smb-devitpro-pb#1742]
Dear Team,
Link to documentation example from Continia is not working

![image](https://user-images.githubusercontent.com/37371997/108912853-7a265000-7629-11eb-87a5-55a651c3db9b.png)

Best regards,
Krzysztof

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0738b431-7018-e6a4-ae1f-21799b52f368
* Version Independent ID: 7ea9a2e0-49fa-0e67-53ca-cd0872382355
* Content: [Help and Customer Support - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-h-help-support#help-link)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-h-help-support.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-checklist-h-help-support.md)
* Service: **dynamics365-business-central**
* GitHub Login: @a-emniel
* Microsoft Alias: **a-emniel**

**Comment by a-emniel** [comment]
Can we use this link instead? https://docs.continia.com/en-us/continia-document-capture

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be updated with the next refresh - please use this link for an example page: https://docs.continia.com/en-us/continia-document-capture. Thanks.
