### ISSUE TITLE
Mention Performance Impact / Restrictions

### ISSUE THREAD

**Issue by JulianTillmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#1743]
Maybe include the performance impact mentioned in the Anti-patterns section of this page?
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/performance/performance-developer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d3aca9-8d36-d509-86b5-01c304b39a60
* Version Independent ID: 2beaf080-7fd7-569c-9738-c7158ac7dd8c
* Content: [Temporary Tables - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-temporary-tables)
* Content Source: [dev-itpro/developer/devenv-temporary-tables.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-temporary-tables.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **solsen**

**Comment by JulianTillmann** [comment]
@SusanneWindfeldPedersen 
Are these issues even being tracked?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for not getting back on this sooner. It's a good idea. The article will be updated with the next doc refresh. Thanks!
