### ISSUE TITLE
File Storage Maximum Capacity

### ISSUE THREAD

**Issue by KVerstuyft** [MicrosoftDocs/dynamics365smb-devitpro-pb#1744]
Hi,

Max database storage capacity is 80gb, but what about file capacity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ea85c7-94cb-7af6-8351-57ba45bb139f
* Version Independent ID: 06bd1519-c792-a657-e987-b5e67fe2e24e
* Content: [Managing Capacity - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-capacity)
* Content Source: [dev-itpro/administration/tenant-admin-center-capacity.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/tenant-admin-center-capacity.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. There is currently no limit on file storage, but it is important to note that this will likely change in an upcoming release. There is some information about this under the [Exceeding Capacity Quotas](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-capacity#exceeding-capacity-quotas) but perhaps we could make this more clear.

**Comment by jswymer** [comment]
Hello, We hope this answered your question. We'll close this issue for now but if you have more feedback, let us know. Thanks!
