### ISSUE TITLE
Typo: there is too much parenthesis in the See Also section

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1745]
In section See Also, there is a closing parenthesis after Method that should not be here.

[Enter feedback here]
![image](https://user-images.githubusercontent.com/44807684/109176604-46613c80-7787-11eb-85e5-09ce52f677f6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4443c9f9-7867-6145-f348-eb3dd81430c7
* Version Independent ID: c8adc140-7ee8-544e-9209-dbe6f3c327d9
* Content: [AL Database Methods and Performance on SQL Server - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/optimize-sql-al-database-methods-and-performance-on-server)
* Content Source: [dev-itpro/administration/optimize-sql-al-Database-methods-and-performance-on-server.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/optimize-sql-al-Database-methods-and-performance-on-server.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! This has been fixed and an update will be published soon.
