### ISSUE TITLE
Debug Console text cut off for text length > 1024

### ISSUE THREAD

**Issue by ewaldventer** [MicrosoftDocs/dynamics365smb-devitpro-pb#1746]
According to this paragraph, I should be able to see the full value of a Text with length > 1024
![image](https://user-images.githubusercontent.com/8598877/109273858-6c382100-781b-11eb-8695-7e45720d2244.png)

But text is still cuts off in the Debug Console.
![image](https://user-images.githubusercontent.com/8598877/109274411-229c0600-781c-11eb-95bb-c02084820fcc.png)

![image](https://user-images.githubusercontent.com/8598877/109274451-30ea2200-781c-11eb-8ded-4284d679187b.png)

Might need config similar to this?
https://stackoverflow.com/questions/45634654/remove-character-limit-in-vs-code-phpdebug

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3f5d28-1484-ce76-b31d-7ee0d444ba0f
* Version Independent ID: bdea6ca9-e7bc-d324-03d5-364c0fcaee4e
* Content: [Debugging - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-debugging)
* Content Source: [dev-itpro/developer/devenv-debugging.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-debugging.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, the ability to debug large size variables is available from CU 17.4 of the server and the latest vsix extension. Can you check if you have that? Thx

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue for now.
