### ISSUE TITLE
CodeCop Rule AA0235 has invalid code due to wrong codeunit name

### ISSUE THREAD

**Issue by dtkb** [MicrosoftDocs/dynamics365smb-devitpro-pb#1747]
The code is not valid. `Codeunit::"Company - Initialize"` is not a valid codeunit. The correct name is `Codeunit::"Company-Initialize"` - no spaces around the hyphen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e85d3ca3-f7b4-c488-be95-dac2559b3afc
* Version Independent ID: df394ab2-8e91-ba74-c244-f5c37c50cbc0
* Content: [When using 'OnInstallPerCompany' you should also add 'Company - Initialize'::'OnCompanyInitialize' event subscriber. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0235-whenusingoninstallpercompanyaddcodetocompanyinitializesubscription)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0235-whenusingoninstallpercompanyaddcodetocompanyinitializesubscription.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0235-whenusingoninstallpercompanyaddcodetocompanyinitializesubscription.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, this will be fixed with the next doc refresh.

**Comment by db-bc** [comment]
for posterity, new location of 404d old link: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0235
