### ISSUE TITLE
Shouldn't OnPreXMLItem be OnPreXmlItem?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1748]
Shouldn't OnPreXMLItem be OnPreXmlItem as the latter is what the AL Language extension uses?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 948b342d-dc56-b099-dd21-ae000cb5e40d
* Version Independent ID: e3488cf0-da46-a4f6-0deb-bb8ab0f500f7
* Content: [OnPreXMLItem Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onprexmlitem-trigger)
* Content Source: [dev-itpro/developer/triggers/devenv-onprexmlitem-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onprexmlitem-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Yes, and the same goes for OnPostXmlPort etc. This will be fixed with the next doc refresh.
