### ISSUE TITLE
Check indexing

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1749]
Is it possible to optimize the indexing of this page?
If you [search for OnAfterGetRecord](https://docs.microsoft.com/en-us/search/?scope=BusinessCentral&terms=OnAfterGetRecord), this article appears only on page 2. 
As the first search result entry, OnAfterGet**Curr**Record is shown instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c1ff70-73a6-9f20-9975-a8b2200f9e59
* Version Independent ID: 46982170-1d2f-c8fa-94c7-52f6dd66f4ec
* Content: [OnAfterGetRecord Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onaftergetrecord-trigger)
* Content Source: [dev-itpro/developer/triggers/devenv-onaftergetrecord-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onaftergetrecord-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, if I run your query, I get

**Comment by SusanneWindfeldPedersen** [comment]
Hi, if I run your query, I get a fair search result. See below. Thanks.
![image](https://user-images.githubusercontent.com/12556556/109644579-f3580280-7b55-11eb-8c0a-1972daa24b76.png)

**Comment by NKarolak** [comment]
Interesting.
See the my result, running on Chrome mobile, but the same on PC:
![Screenshot_20210302-130326_Chrome](https://user-images.githubusercontent.com/34504100/109645952-d7556080-7b57-11eb-922c-95c7720918d3.jpg)

**Comment by SusanneWindfeldPedersen** [comment]
Right, that is weird. I am using Edge, of course :)

**Comment by NKarolak** [comment]
On my PC, even Edge and the good ol' Internet Explorer return the same result as my Chrome does:
![image](https://user-images.githubusercontent.com/34504100/109652581-433bc700-7b60-11eb-9b2b-75bf88c5ec36.png)

**Comment by SusanneWindfeldPedersen** [comment]
Hi Natalie - I am not sure what's going on, it seems unpredictable. I am not able to repro, so if you're okay with it, I will close this for now as unresolved. We do not have control over the search results other than a few options in metadata for the topic. Thanks.

**Comment by NKarolak** [comment]
Oh pity, but I understand.
