### ISSUE TITLE
OnPrem Limitations: MS Flow

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#175]
The information on Flow integration is quite confusing:

**Features that require specific circumstances:**
Built-in Microsoft Flow Management:
**The integration with Microsoft Flow** requires Azure Active Directory as the authentication mechanism.

**Features not intended for use in on-premises deployments:**
Create workflow from Flow:
**Microsoft Flow does not integrate** with on-premises workflow functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db917c4-601c-b6f1-863f-17b83d35e814
* Version Independent ID: 22279a66-57b2-7f98-16b6-3cfb394b7fda
* Content: [Features not implemented in on-premises deployments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/features-not-implemented-on-premises)
* Content Source: [dev-itpro/features-not-implemented-on-premises.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/features-not-implemented-on-premises.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
I am working on getting an explanation from the owner of the functionality.

**Comment by edupont04** [comment]
We're about to publish an update, but essentially you can connect to Microsoft Flow so that you can use the built-in workflows. But you cannot create new workflows based on Microsoft Flow templates.

**Comment by edupont04** [comment]
Closing the issue because the update of the feature limitation for Flow and on-premises deployments of Business Central is now live at https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/features-not-implemented-on-premises
