### ISSUE TITLE
CRLF is wrong in the example

### ISSUE THREAD

**Issue by hougaard** [MicrosoftDocs/dynamics365smb-devitpro-pb#1750]
It's 13 before 10, not the other way around. The variable name is correct, but CR is 13 and LF 10. So the correct code should be:

CRLF[1] := 13;
CRLF[2] := 10;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2f4f68-c2ff-18ae-a814-8dbc03c2a322
* Version Independent ID: d1154955-7f82-a233-6b24-6de213debeb4
* Content: [Write, WriteText, Read, and ReadText Method Behavior - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-write-read-methods-line-break-behavior)
* Content Source: [dev-itpro/developer/devenv-write-read-methods-line-break-behavior.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-write-read-methods-line-break-behavior.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This is the same issue as #1664. It has now been fixed and will be reflected with the next refresh.
