### ISSUE TITLE
Phrase "Marks whether the table, field, or key is or will become obsolete (deprecated)." appears to be outdated

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#1751]
The phrase "Marks whether the table, field, or key is or will become obsolete (deprecated)." no longer matches the Applies To list immediately below it. Maybe something along the lines of "Marks whether the object or object element is or will become obsolete (deprecated)."? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 065836e3-0874-ca58-4f76-2ca76891bb83
* Version Independent ID: 4cec430d-5aeb-cbe2-b9b9-6e4f22269596
* Content: [ObsoleteState Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-obsoletestate-property)
* Content Source: [dev-itpro/developer/properties/devenv-obsoletestate-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-obsoletestate-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Thanks for noticing this, it will be fixed with the next refresh.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next doc refresh.
