### ISSUE TITLE
SelectTokens

### ISSUE THREAD

**Issue by jrrdk** [MicrosoftDocs/dynamics365smb-devitpro-pb#1756]
Can we please have this method to so it is possible to select a list of json tokens

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
