### ISSUE TITLE
The content of this article is only valid for the SaaS environment

### ISSUE THREAD

**Issue by Frederig** [MicrosoftDocs/dynamics365smb-devitpro-pb#176]
The upload extension action is only available for the SaaS environment and not for the OnPremise version.
Apparently for the OnPremise we should use PowerShell commands Publish-NAVApp / Sync-NAVApp / Install-NAVApp powershell.

See discussion on Yammer: https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=1168549033

Should be could to add this as a note in the beginning of this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1617d3fe-41ee-548f-aa90-e9bdefe02818
* Version Independent ID: 460df5dc-5cf7-56e6-1ec1-d970158f4b0e
* Content: [Deploying a Tenant Customization - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deploy-tenant-customization)
* Content Source: [dev-itpro/developer/devenv-deploy-tenant-customization.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-deploy-tenant-customization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. Yes, this is only applicable to the SaaS environment and contains terminology that should not be confused with on-premise. This repo contains cloud-first documentation, and when a feature is applicable to on-premise it is called out. Thanks.
