### ISSUE TITLE
Installing minor update

### ISSUE THREAD

**Issue by DavideVD** [MicrosoftDocs/dynamics365smb-devitpro-pb#1760]
Using the documentation here
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v17

u arrive at this point 
Unpublish the existing system symbols.

To unpublish the system symbols, use the Unpublish-NAVApp cmdlet as follows:
PowerShell

Unpublish-NAVApp -ServerInstance <server instance> -Name System -version <version>

which is the version of the system.app?

using get-Navapp i get all publishing extensions, except system
MicrosoftDynamicsNavServer$bc170 08d69832-9231-429e-be2c-8bab2c96905b Email - Current User Connector  Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 bae453ed-0fd8-4416-afdc-4b09db6c12c3 WorldPay Payments Standard      Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 e6328152-bb29-4664-9dae-3bc7eaae1fd8 Email - Outlook REST API        Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 c526b3e9-b8ca-4683-81ba-fcd5f6b1472a Sales and Inventory Forecast    Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 16319982-4995-4fb1-8fb2-2b1e13773e3b AMC Banking 365 Fundamentals    Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 10cb69d9-bc8a-4d27-970a-9e110e9db2a5 _Exclude_APIV2_                 Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 3d5b2137-efeb-4014-8489-41d37f8fd4c3 Late Payment Prediction         Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 c1335042-3002-4257-bf8a-75c898ccb1b8 Application                     Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 aceb66c8-472e-437c-81d3-27e6c07d0f14 Email - Microsoft 365 Connector Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 8c972578-fe72-4aa5-ae51-cc5575fef2ea Send To Email Printer           Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 437dbf0e-84ff-417a-965d-ed2bb9650972 Base Application                Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 c512d720-63b9-4b26-b062-a0c09b4ed322 Company Hub                     Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 63ca2fa4-4f03-4f2b-a480-172fef340d3f System Application              Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 d09fa965-9a2a-424d-b704-69f3b54ed0ce PayPal Payments Standard        Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 8b3609cf-3947-44c3-9f20-ce6edc6da33f _Exclude_ClientAddIns_          Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 8afe7b40-8c87-4beb-ada0-451d1761bf95 _Exclude_APIV1_                 Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 2a89f298-7ffd-44a5-a7ce-e08dac98abce Essential Business Headlines    Microsoft         17.3.20469.20605     ModernDev Global       
MicrosoftDynamicsNavServer$bc170 68e13fa3-217a-4be0-9141-99e5bf0ca818 Email - SMTP Connector          Microsoft         17.3.20469.20605     ModernDev
thanks

**Comment by jswymer** [comment]
Hello, Thanks for the feedback and sorry for the delayed response. 

You should unpublish all versions of the system symbols. You can see what versions are published by using:
```powershell
 Get-NAVAppInfo -ServerInstance <BC server instance> -SymbolsOnly
```
If you only have one version of the symbols published, you can unpublish the symbols by omitting the -Version:

```powershell
 Unpublish-NAVApp -ServerInstance <BC server instance> -Name System
```

We've updated the article to make this more clear. Thanks!
