### ISSUE TITLE
User Scenario Documentation Typo

### ISSUE THREAD

**Issue by eapomazkov** [MicrosoftDocs/dynamics365smb-devitpro-pb#1767]
'You know your app well, but other users Microsoft does not'
should be
'You know your app well, but other Microsoft users do not'
(?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c32e452-ab94-4557-4062-feba4951c112
* Version Independent ID: 421e93e8-857d-4f1d-c433-afc9910f8c2f
* Content: [User Scenario Documentation - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-userscenario)
* Content Source: [dev-itpro/compliance/apptest-userscenario.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-userscenario.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **freddyk**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. It will be fixed with the next refresh of the docs.
