### ISSUE TITLE
Tasks 4 and 6 are missing

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#177]
Either two tasks are missing completely, or the task titles need some numbering update as Task 4 and 6 are not mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The tasks were numbered wrong. A fix will be published soon.
