### ISSUE TITLE
Task 3: Convert the version 14 database

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [MicrosoftDocs/dynamics365smb-devitpro-pb#1771]
[Enter feedback here]
When running the Invoke-NAVApplicationDatabaseConversion and the database is Azure SQL the command fails after short time., like one minute. I found this link (https://www.yammer.com/dynamicsnavdev/threads/993327454838784) on Yammer which helped me. I temporarily set the DTUs to 3000 and the conversion worked. I had used a lot of time looking for the reason without luck. There was nothing in the PowerShell error message or in the event viewer that pointed in this direction. Can you updated the documentation with some explanation about what is needed when the Azure SQL is used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0452213f-014b-ef1d-4108-b49bf90c12fb
* Version Independent ID: 5a6ac90b-35e4-5e2c-b590-e346ff91bf85
* Content: [Upgrading Unmodified C/AL Application to Version 17 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v17)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v14-v17.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application-v14-v17.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've updated this article, and others that deal with conversion, with information about how to fix this issue by temporarily scaling up the database resources. The updates will be published soon.
