### ISSUE TITLE
Excluisve Access information is not correct in your examples

### ISSUE THREAD

**Issue by krregg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1772]
Hi,

I would just like to report that examples 3 and 4 have some incorrect parameters.

For example 3 the correct command would be:
```
$exlusiveAccessTicket = Set-NAVTenant -ServerInstance ServerInstance -Tenant Tenant -Justification "Perform exclusive operation on tenant before dismount" -AcquireExclusiveAccess
```

- Parameter `TenantId` is not working, the right one is `Tenant` only.
- Parameter `AcquireExclusiveAccess` can only be placed as the last parameter otherwise it throws an error:
```
PS C:\WINDOWS\system32> $exlusiveAccessTicket = Set-NAVTenant -ServerInstance ServerInstance -Tenant Tenant -Justification "Perform exclusive operation on tenant before dismount" -ExclusiveAccessTicket 
Set-NAVTenant : Missing an argument for parameter 'ExclusiveAccessTicket'. Specify a parameter of type 'System.String' and try again.
At line:1 char:143
+ ... exclusive operation on tenant before dismount" -ExclusiveAccessTicket
+                                                    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-NAVTenant], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Microsoft.Dynamics.Nav.Management.Cmdlets.SetNavTenant
```

For example 4 the correct command would be:
```
Set-NAVTenant -ServerInstance ServerInstance -Tenant Tenant -ExclusiveAccessTicket $exlusiveAccessTicket -ReleaseExclusiveAccess
```

- Parameter `TenantId` is not working, the right one is `Tenant` only.
- Parameter `ReleaseExcluisveAccess` can only be placed as the last parameter otherwise it throws an error:

```
PS C:\WINDOWS\system32> Set-NAVTenant -ServerInstance ServerInstance -Tenant Tenant -ReleaseExcluisveAccess -ExclusiveAccessTicket $exlusiveAccessTicket
Set-NAVTenant : A parameter cannot be found that matches parameter name 'ReleaseExcluisveAccess'.
At line:1 char:48
+ ... nant -ServerInstance ServerInstance -Tenant Tenant -ReleaseExcluisveAccess -Exclus ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-NAVTenant], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Dynamics.Nav.Management.Cmdlets.SetNavTenant
```

This was tested on Business Central version 17.4.
Version: W1 17.4 (Platform 17.0.21485.21516 + Application 17.4.21491.21531)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f412fe24-4433-6124-69d1-1855dc344847
* Version Independent ID: fc38c8ec-ddd6-d049-89fe-420a141ad641
* Content: [Set-NAVTenant (Microsoft.Dynamics.Nav.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/set-navtenant?view=businesscentral-ps-17)
* Content Source: [businesscentral-ps-17/Microsoft.Dynamics.Nav.Management/Set-NAVTenant.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-17/Microsoft.Dynamics.Nav.Management/Set-NAVTenant.md)
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed, and the update will be published soon.
