### ISSUE TITLE
Table of Contents not in alphabetical order.

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1774]
Is there a reason why the "Methods" section of the Table of Contents is not is alphabetical order?  I could not find the Record entry because it is not in the "R's" that come before the "S's".  And there are a number of other issues.

![image](https://user-images.githubusercontent.com/4333956/112031521-588a8c80-8b33-11eb-86a1-ade1d1aa1402.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 281928a1-4df6-4656-2f12-2985298e6fa3
* Version Independent ID: e4ecf777-facb-d697-f999-daf2c6cdddf7
* Content: [Record.SetAutoCalcFields Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setautocalcfields-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-setautocalcfields-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-setautocalcfields-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This part of the table of contents is auto-generated and fixing the sequence requires a code fix. We will put this on the backlog and prioritize it accordingly. Meanwhile, the fact that all methods are now visible in the table of contents allows using the Filter by Title field for searching:
![image](https://user-images.githubusercontent.com/12556556/114675346-68e3f080-9d08-11eb-8eb8-5a1ff2160c11.png)

Thanks.
