### ISSUE TITLE
IndentationColumn Property Missing?

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1775]
The IndentationColumn property appears to be missing from the Page properties list.  It applies to the same controls as the IndentationControls property.  The IndentationColumn property can be found by searching so the documentation exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2612295b-ecb2-93f1-2097-c5e055ed5123
* Version Independent ID: ec810858-2ada-8915-c110-7634c6b791b4
* Content: [Page, Page Fields, and Page Extension Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-property-overview)
* Content Source: [dev-itpro/developer/properties/devenv-page-property-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-page-property-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback. We've added the property to the list, and the update will be available soon!
