### ISSUE TITLE
example 2 incorrect

### ISSUE THREAD

**Issue by dkiehl** [MicrosoftDocs/dynamics365smb-devitpro-pb#1779]
the code in example 2:

if (STRPOS('Rec.Address', '+') > 0) then begin
            MESSAGE('Can''t use a plus sign (+) in the address [' + 'Address' + ']');
        end;

is incorrect.  Should be:

if (STRPOS(Rec.Address, '+') > 0) then begin   //  no single quotes around Rec.Address
            MESSAGE('Can''t use a plus sign (+) in the address [' + Address + ']');    // no quotes around Address
// or the preferred way: 
            MESSAGE('Can''t use a plus sign (+) in the address [%1]', Rec.Address);
        end;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847f9637-606b-5022-0891-81481a7eb283
* Version Independent ID: 35643c3c-bb2d-e1ef-6ebd-556158d9d8e7
* Content: [Subscribing to Events - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-subscribing-to-events)
* Content Source: [dev-itpro/developer/devenv-subscribing-to-events.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-subscribing-to-events.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! We've made changes to the article based on your input. The update will be published soon.
