### ISSUE TITLE
NAV Apps installed or published

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1780]
The various examples get a concluding line saying either "... the NAV Apps installed ..." or "... the NAV Apps published ...". This seems ambiguous to me. But even more it does not related to get-NAVAppInfo does (as far as I know). It will always list (with the filter) all apps that apply, whether they are installed or published.
Could you please get this reflected in the topic?

BTW: it would also be nice to tell how to get info on whether an app is (only) published (and not installed) or whether it is installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5dab1b-a999-5cb7-c77a-2751c2a66629
* Version Independent ID: 7038e976-0307-8b61-8e23-81045b5c60c4
* Content: [Get-NAVAppInfo (Microsoft.Dynamics.Nav.Apps.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappinfo?view=businesscentral-ps-17)
* Content Source: [businesscentral-ps-17/Microsoft.Dynamics.Nav.Apps.Management/Get-NAVAppInfo.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-17/Microsoft.Dynamics.Nav.Apps.Management/Get-NAVAppInfo.md)
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. We'll take a look at this article to see how we can improve the experience. 

To hopefully help in the meantime:

- Without the -Tenant <tenant ID> parameter, the cmdlet returns the extensions that are published to application/server.
- With the  -Tenant <tenant ID> parameter, the cmdlet returns the extensions installed on the specified tenant.

**Comment by jswymer** [comment]
We've added some more information to the articles, which we hope will help. The update will be published soon. Thanks for the feedback!
