### ISSUE TITLE
Broken links on Microsoft Power Platform Integration with Business Central

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1781]
The links for `Table overview` and `Create and edit virtual tables that contain data from an external data source` seems to broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28370b2f-fedb-ba1e-31e4-b30b64039d24
* Version Independent ID: 98f25d46-ec3a-46a1-359b-314fa972ad2b
* Content: [Microsoft Power Platform integration with Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/powerplatform/powerplat-overview)
* Content Source: [dev-itpro/powerplatform/powerplat-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/powerplatform/powerplat-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I cannot reproduce this, the Table overview links to https://docs.microsoft.com/en-us/powerapps/maker/data-platform/entity-overview and the Create and edit... to this link https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-edit-virtual-entities - both of them open fine on my browser. Can you please re-check? Thanks.

**Comment by jwikman** [comment]
Hi Susanne, 

It seems as if Eva updated those links the very same day as I reported this issue 😁

The  links seems fine now,  problem solved!
