### ISSUE TITLE
<error> in Xml Comments

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1783]
I've seen the use of \<error>\</error> in XML Comments in BC code. (See the [Camera codeunit](https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/39b9682a0bcf306c7e821d41b19dc78f88662633/System%20Application/Source/System%20Application/Camera%20and%20Media%20Interaction/src/Camera.Codeunit.al) for example.)

In the new `Writing tips` section you state "List any exceptions the method may throw (and under what circumstances).".
Should this list of exceptions be done with the error element? If so, please update the docs :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2fc02e0-107b-e062-19c4-2952e25ac4d8
* Version Independent ID: f51ce1eb-e22f-b0bf-af9a-0acdce111001
* Content: [XML Comments in Code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-xml-comments)
* Content Source: [dev-itpro/developer/devenv-xml-comments.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-xml-comments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The <error> tag is actually not yet supported, although it is, as you have seen, used in the Sys App. This is because those tags were introduced prior to the XML comment feature. In time, we might be able to expand the support, it is on our radar and thanks for asking.
