### ISSUE TITLE
SetRecFilter() documentation should be clearer that it might use a secondary key

### ISSUE THREAD

**Issue by dtkb** [MicrosoftDocs/dynamics365smb-devitpro-pb#1789]
Right now it just says

> Sets the values in the current key of the current record as a record filter.

Which I had always assumed meant the current **primary** key fields, but after some days of confusion... I realise it will use **any** key that is the current key, including secondaries.

This code reproduces what I mean:
```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Customer: Record Customer;
    begin
        Customer.FindLast();
        Customer.SetCurrentKey(Name);
        Customer.SetRecFilter();
        Message(Customer.GetFilters());
    end;
}
```

The resulting message reads:

> No.: CASH, Name: Cash Customer hey fun, Address: '', City: ''

So, the `SetCurrentKey(Name)` really got mapped to a larger key _containing_ the `Name` field, and _all_ fields in that key are filtered to their current values.

Perhaps the doc could instead read something like:

> Sets the values in the current key of the current record as a record filter. **This is not necessarily the primary key, as the table view might be set to use a secondary key. All fields in the key as defined on the table are filtered (even if the table view only requests a subset of those fields).**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9812c244-cb0d-a55b-4193-91382d4d4f4b
* Version Independent ID: cddb6d21-00cf-2ac1-4a84-fab5f61bcf07
* Content: [Record.SetRecFilter Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setrecfilter-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-setrecfilter-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-setrecfilter-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the valuable feedback. The key selection is explained a bit in the [SetCurrentKey method](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setcurrentkey-method) article, but it could be more prominent here as well. We've added some content based on your feedback, which hopefully helps. The update will be published soon. Thanks!
