### ISSUE TITLE
Remove unneeded GLEntry variable references

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#179]
This code:

GLEntry.SETCURRENTKEY("G/L Account No.","Posting Date");  
GLEntry.SETRANGE(GLEntry."G/L Account No.",'1110');  
GLEntry.SETRANGE(GLEntry."Posting  
Date",DMY2DATE(1,1,2007),DMY2DATE(15,12,2007));  
GLEntry.CALCSUMS(Amount);

Should be changed to:

GLEntry.SETCURRENTKEY("G/L Account No.","Posting Date");  
GLEntry.SETRANGE("G/L Account No.",'1110');  
GLEntry.SETRANGE("Posting  Date",DMY2DATE(1,1,2007),DMY2DATE(15,12,2007));  
GLEntry.CALCSUMS(Amount);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a26e11d-7017-52d3-3189-714153e3705f
* Version Independent ID: 6205913f-580d-e800-233b-98ed9091ce72
* Content: [SIFT and SQL Server - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/sift-and-sql-server)
* Content Source: [dynamics-nav/SIFT-and-SQL-Server.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SIFT-and-SQL-Server.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @KennieNP
* Microsoft Alias: **kepontop**

**Comment by jswymer** [comment]
Thanks for the feedback! The example has been adjusted and the update will be available soon.
