### ISSUE TITLE
app.json Test Attribute Limitations

### ISSUE THREAD

**Issue by MFCKSweeney** [MicrosoftDocs/dynamics365smb-devitpro-pb#1790]
Please add an entry for the **test** attribute in the **app.json** file and indicate it's limitation to older versions of BC with C/AL remnants.

In [this](https://github.com/microsoft/navcontainerhelper/issues/1869) BCContainerHelper Git Issue , Freddy provides information on why I cannot download test symbols using the Test attribute, but there is no documentation in this article that would have spared me the time and trouble.

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The test attribute is added with a note about the limitation. This will be available with the next refresh of the docs.
