### ISSUE TITLE
Punctuation Typo In Converting Extensions V1 to Extensions V2 Doc

### ISSUE THREAD

**Issue by eapomazkov** [MicrosoftDocs/dynamics365smb-devitpro-pb#1792]
'converting V1 extensions, written in C/SIDE. to V2 extensions; written'
should be
'converting V1 extensions, written in C/SIDE, to V2 extensions, written'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dba54fc-a7cd-d3ad-f53c-6f0aa0b12d23
* Version Independent ID: e1554d91-f623-5fe2-0525-2fd37e0c30ec
* Content: [Converting Extensions V1 to V2 Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrade-v1-to-v2-overview)
* Content Source: [dev-itpro/developer/devenv-upgrade-v1-to-v2-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-upgrade-v1-to-v2-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been fixed and the update will be published soon.
