### ISSUE TITLE
Link "Using Saved Settings" directs to 404 - Page Not Found

### ISSUE THREAD

**Issue by markborges** [MicrosoftDocs/dynamics365smb-devitpro-pb#1794]
The last link on this page, under section "See Also" (link "Using Saved Settings") is broken. It takes me to a 404 - Page not found error page.

![image](https://user-images.githubusercontent.com/55449604/114069399-f50b9900-986c-11eb-9e00-689665033196.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dce95ba-a175-0884-d851-173c7c13e897
* Version Independent ID: 711c1256-ed89-152c-3fca-bf11363bdc00
* Content: [SaveValues Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-savevalues-property?source=docs)
* Content Source: [dev-itpro/developer/properties/devenv-savevalues-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-savevalues-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The links have been fixed and the updated article will be published soon. In the meantime, here are a couple links: [https://docs.microsoft.com/en-us/dynamics365/business-central/reports-saving-reusing-settings](https://docs.microsoft.com/en-us/dynamics365/business-central/reports-saving-reusing-settings) and [Using default values - predefined settings](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-work-report#SavedSettings)
