### ISSUE TITLE
Error in Changing the table type

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1795]
This is what the section says
> You can change from Normal to Temporary, and the other way around. When changing Normal to Temporary the table, you will have to synchronize the extension with the database. This step will remove the table from the database. So if the table contains data, you will have to synchronize the schema using the ForceSync mode.

However, this can only be done on prem, as this is a destructive change. The ForceSync hints at this, however it would be better if this was explicitly stated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d3aca9-8d36-d509-86b5-01c304b39a60
* Version Independent ID: 2beaf080-7fd7-569c-9738-c7158ac7dd8c
* Content: [Temporary Tables - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-temporary-tables#changing-the-table-type)
* Content Source: [dev-itpro/developer/devenv-temporary-tables.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-temporary-tables.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've added this info to the article. The update will be published soon.
