### ISSUE TITLE
Small error, on-premises should be online

### ISSUE THREAD

**Issue by ClausHamann** [MicrosoftDocs/dynamics365smb-devitpro-pb#1798]
Under Behavior overview, you are writing the following
.....

Installing and uninstalling extensions

For on-premises, data for these operations is recorded when an extension is installed or uninstalled by using the Install-NAVApp cmdlet or Uninstall-NAVApp cmdlet. Or, when an extension is installed or uninstalled from the Extension Management page in the client.

For on-premises, data for these operations is recorded when an extension is installed or uninstalled from the Extension Management page in the client.

The second section should be (on-premises replaced with online)
For online, data for these operations is recorded when an extension is installed or uninstalled from the Extension Management page in the client.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a9815c-6e88-45b7-c27e-38a0e17929ef
* Version Independent ID: b07b37e4-4580-3ab5-ce0e-55b6984d4a16
* Content: [Extension Lifecycle Trace Telemetry - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/telemetry-extension-lifecycle-trace#behavior-overview)
* Content Source: [dev-itpro/administration/telemetry-extension-lifecycle-trace.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/telemetry-extension-lifecycle-trace.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the article and an update will be published soon.
