### ISSUE TITLE
Production extensions on Container Sandbox are not installed automatically

### ISSUE THREAD

**Issue by dkatson** [MicrosoftDocs/dynamics365smb-devitpro-pb#18]
Hi team, on this page under Production extensions you say that "Production installed extensions are automatically installed" on "Container Sandbox" which is not true. Or may be this needs additional explanation. I've made an experiment 
- installed extension from Marketplace on production D365BC tenant
- downloaded locally hosted container Sandbox environment script
- after running script i checked Extension management in local sandbox container, and found only default extensions (without installed by me)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 259bfcfa-ad5b-a264-9400-193459f34bad
* Version Independent ID: e61ee3e5-f778-ed02-869d-fe8a03b1b06d
* Content: [Choosing Your Dynamics 365 Business Central Development Sandbox Environment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sandbox-overview)
* Content Source: [dev-itpro/developer/devenv-sandbox-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-sandbox-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The information in the documentation was not correct and has been updated with the next documentation refresh. Thanks again for notifying us.
