### ISSUE TITLE
Topic not synced to the TOC

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/dynamics365smb-devitpro-pb#180]
By design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0cbc546-146f-e39f-908c-a4f95aa5dc25
* Version Independent ID: 91f238a3-dad9-0a64-8765-7eac8f144faa
* Content: [How to: Set up Performance Counters in Windows Performance Monitor - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--set-up-performance-counters-in-windows-performance-monitor)
* Content Source: [dynamics-nav/How-to--Set-up-Performance-Counters-in-Windows-Performance-Monitor.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Set-up-Performance-Counters-in-Windows-Performance-Monitor.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Yes, this is by design. However, for Business Central we are thinking about including all topics in TOC for searchability. Thanks.
