### ISSUE TITLE
Record.Locktable(false) gives error

### ISSUE THREAD

**Issue by tinfister** [MicrosoftDocs/dynamics365smb-devitpro-pb#1803]
I wrote function with PurchaseHeader.Locktable(false) and when I called that function I got error.
![image](https://user-images.githubusercontent.com/29481795/115127099-23f3de80-9fd4-11eb-880c-21ab438bb458.png)

Is Record.Locktable(false) even supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60835db-7fec-a288-a764-b84e604f3b64
* Version Independent ID: 6c3794bf-27b0-643c-b370-9ba9036da260
* Content: [Record.LockTable Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-locktable-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-locktable-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-locktable-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. Yes, it should be supported, but you might have discovered a bug. Please use your usual support channel to file a bug. Thanks.
