### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#1804]
In Task 1, Step 2, the Redirect URI must be "https://businesscentral.dynamics.com/OAuthLanding.htm". Otherwise, Grand Access will not work later. 

And for Task 2, Step 6, you need to add the permission sets "D365 AUTOMATION" and "D365 EXTENSION MGT" for the AAD application, not just "Dynamics 365 Automation". Otherwise, the deployment will not work and you will get the error message "You do not have sufficient permissions to manage extensions. Please contact your administrator.".  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1555e693-76e8-b1d9-267f-bf06f068c9f4
* Version Independent ID: 725078be-b4d2-ced1-1ce0-52fc379f6a4e
* Content: [Using Service to Service Authentication with Automation APIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/automation-apis-using-s2s-authentication)
* Content Source: [dev-itpro/administration/automation-apis-using-s2s-authentication.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/automation-apis-using-s2s-authentication.md)
* Service: **dynamics365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the valuable feedback! We've updated the article with the information, and it will be published soon.
