### ISSUE TITLE
Max date an update can pe postponed not clear

### ISSUE THREAD

**Issue by eclipses** [MicrosoftDocs/dynamics365smb-devitpro-pb#1807]
Hi, 

Following the documentation is not clear what is the maxim number of days an upgrade can be postponed and also should distinguish between Minor and Major Updates.

Here ad example of details found in the Admin Center

"Schedule environment update
Production
Visit Business Central Updates to find out more about the update roll-out process.
Current Version: 17.5.22499.22680
Scheduled Version: 18.0.23013.23532
Current Scheduled Update Date: 6/15/2021
Select a date to schedule the update of this environment. The update will occur within the time frame defined in the update window settings for the environment.
The update must be scheduled between **4/16/2021 and 6/15/2021**."

The documentation says 21 days but the range here is 2 months.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26796e6-7fa5-33f3-8ad4-8bae8a965b51
* Version Independent ID: 2464c219-c5d3-a5c3-8077-03ca9ece75de
* Content: [Major Updates and Service Updates for Business Central Online - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/update-rollout-timelime)
* Content Source: [dev-itpro/administration/update-rollout-timelime.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/update-rollout-timelime.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The article now has two different sections for major updates and minor updates, and each section has different date ranges.

- This section is for major updates and mentions 60 days (two months) as the longest you can postpone an update: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/update-rollout-timelime#timelines-for-major-updates
- This section is for minor updates and mentions 21 days as the longest you can postpone an update: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/update-rollout-timelime#timelines-for-minor-service-updates

Based on your screenshot, you are looking at an environment that can be updated to version 18, which is a major release. But based on your question, you were reading the section about minor service updates.

I hope this answers your question. However, we will be updating the article in the coming weeks based on feedback from you and others.
