### ISSUE TITLE
What is the meaning of the string of the format "o"?

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1808]
Hello,

I think there might be an issue with this sentence:
```
If the JsonValue does not contain a string of the format "o" as specified here the operation will fail with a run-time error.
```

What is this **"o"** format ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 351a84b1-6500-cf37-a477-749d9f0c44ca
* Version Independent ID: be9fa1f0-e30e-a6e2-fbea-c368727eeb8c
* Content: [JsonValue.AsDateTime Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonvalue/jsonvalue-asdatetime-method)
* Content Source: [dev-itpro/developer/methods-auto/jsonvalue/jsonvalue-asdatetime-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/jsonvalue/jsonvalue-asdatetime-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The "o" format refers to the [The round-trip ("O", "o") format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier). The documentation will be updated to include this.
