### ISSUE TITLE
Co-admin privileges needed to download publish settings?

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/dynamics365smb-devitpro-pb#181]
At Step 3, I get the message:
The selected subscription 'Bot Framework Support Team' is missing co-admin priviledges. Please check permissions.

Do I really need co-admin privileges? The document should mention that in any case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836135bf-5f7f-2424-cfaf-11578f1e8d31
* Version Independent ID: 0deea7c7-a15c-fe7e-26ca-b9c0932b29b8
* Content: [How to: Download and Import Publish Settings and Subscription Information - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--download-and-import-publish-settings-and-subscription-information)
* Content Source: [dynamics-nav/How-to--Download-and-Import-Publish-Settings-and-Subscription-Information.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Download-and-Import-Publish-Settings-and-Subscription-Information.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by edupont04** [comment]
Hi Kyle,
It sounds like a problem on the side of your Azure subscription. This article is about how to prepare to deploy Dynamics NAV to Azure, and you do need to be an admin to do that. Please contact me or John directly.

**Comment by turowicz** [comment]
@v-kydela did you find out how to fix this problem with co-admin priviledges?

**Comment by v-kydela** [comment]
@turowicz - Sorry, I don't remember
