### ISSUE TITLE
Query field Method property is documented as related to HTTP Method

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#1818]
This property has nothing to do with _Gets or sets the method type as defined in the HTTP standard._ as mentionned at the beginning.

It is a way to group records in a query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6ef5d2-fc11-3941-8ca6-75f777903483
* Version Independent ID: b13c6ede-2462-6655-ecb8-60508fa29a84
* Content: [Method Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-method-property)
* Content Source: [dev-itpro/developer/properties/devenv-method-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-method-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This has now been fixed.
