### ISSUE TITLE
"Report extension layout" section does not explain how to select the new report layout

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1819]
"Report extension layout" section does not explain how to select the new report layout. Please add that. In the past You could only select a different layout when selecting _Custom Layout_ in the **Select Layout** column. Apparently now (thanx to the launch event demo by Peter Boring) you can select the report extension layout in the **Layout Description** column when the **Select Layout** is (still) _RDLC (built-in)_.
Please add this, so, all readers directly know how it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fedbf190-9d38-889f-4158-0d06e88d8b87
* Version Independent ID: 369fde2e-6cfc-cdae-b2f3-dc2a95a6d7a9
* Content: [Report Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-ext-object)
* Content Source: [dev-itpro/developer/devenv-report-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-report-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. I believe this is described in this section: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-ext-object#report-extension-layout? Thanks

**Comment by lvanvugt** [comment]
True, but not exactly enough. Previously you had to select custom layout when choosing another layout, but now it is a new build-in layout. It took me a while before I found out (with Peter Boring's presentation).

**Comment by SusanneWindfeldPedersen** [comment]
Okay, thanks - we'll try to be more specific and push an update to this section with the next refresh. Thanks!
