### ISSUE TITLE
Test Framework should not be referenced in app.json

### ISSUE THREAD

**Issue by Fkoehnen** [MicrosoftDocs/dynamics365smb-devitpro-pb#182]
As per this issue: https://github.com/Microsoft/AL/issues/2903
there should not be any reference to the Test Framework anymore. (In the Text "Import symbols for the Test framework." and following)

The Test Symbols are already downloaded through the base Application.

Moreover adding the test entry in the app.json will cause problems to show up, as described in the Issue above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7f2151-4fef-e6ab-bbc1-5b3e1b8c5b17
* Version Independent ID: 20ffa998-58d3-c843-87d5-3533e2fa7765
* Content: [Testing the Advanced Sample Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-advanced-example-test)
* Content Source: [dev-itpro/developer/devenv-extension-advanced-example-test.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-advanced-example-test.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, very much appreciated. The topic has been updated and will be pushed live with the next refresh. Thanks.
