### ISSUE TITLE
Version Typo in v18 upgrade steps

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#1820]
Quick/small typo issue:
"Download the latest available update for Business Central **2020** (version 18) "

Right under Task 1.  Should say **2021**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab367758-d435-42cd-a1e1-d0b89c33ad25
* Version Independent ID: 4ea22d59-5d20-c0af-7bf8-e678c181b663
* Content: [Upgrading Version 15, 16, or 17 Base Application to Version 18 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v18#feedback)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by JeremyVyska** [comment]
To be fair, pandemic times.  What year IS it anymore...

**Comment by jswymer** [comment]
So true. Thanks for the feedback! We've fixed the article and an update will be published soon.

**Comment by JeremyVyska** [comment]
@jswymer - I should have kept reading before opening the ticket: there are a few places that also refer to version 16 that probably should say 17 also.

**Comment by jswymer** [comment]
Thanks! They are fixed as well.
