### ISSUE TITLE
Migrate modified tables from Business Central 14.x on-premises to Business Central 18.x extensions

### ISSUE THREAD

**Issue by davmac1** [MicrosoftDocs/dynamics365smb-devitpro-pb#1822]
I am using the same procedures I used to update BC14 to BC16 to go from BC14 to BC18.
I get errors for missing tables.
These tables are marked:
#pragma warning disable AS0034
    TableType = Temporary;
#pragma warning restore AS0034
Tables are Document Entry
Entry Summary
Option Lookup Buffer
Field Content Buffer
Bin Content Buffer

Is it required to upgrade to BC16 or BC17 and then do another upgrade step to BC18 and beyond (future)?

**Comment by jswymer** [comment]
Hello, 

In version 18, these tables have been changed to temporary table, We have some information about this in Task 4 of this article;
[Upgrading Customized C/AL Application to Microsoft Base Application Version 18](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v18?create-the-second-version#create-the-second-version). I hope this helps. Thanks for the feedback!

**Comment by davmac1** [comment]
After the upgrade is completed, do I need to delete these tables from SQL Server since BC18 does not have them as physcial tables?

**Comment by jswymer** [comment]
Hello,

I think it's recommended. There is a step [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v18?create-the-second-version#task-16-clean-sync-and-unpublish-table-migration-extensions) that talks a bit about it. But I can verify with the development team.

**Comment by davmac1** [comment]
Thanks for your help.
Do you know how long they will keep supporting this upgrade method? Will there come a point like the NAV2009 upgrade up to NAV 2015, where it stops being supported? And will there be an official announcement when this happens?
I work for an ISV and we still have a lot of companies left to move.
Until I did my first upgrade with this method last year, we had been doing re-implementations migrating only some of the data.

**Comment by davmac1** [comment]
task 12 step 3: says to install-navapp for all the empty extensions.
I get this message: Cannot install extension System Application by Microsoft 14.0.0.0 for the tenant default because it is already
 installed.
Does sync-navapp now do the install-navapp?
Does this affect the start-NAVDataUpgrade? (This executes instantaneously.)

**Comment by davmac1** [comment]
Task 15
Start-NAVAppDataUpgrade -ServerInstance <server instance> -Name "<table migration extension>" -version <version 2>
gets error: Start-NAVAppDataUpgrade : Cannot upgrade the extension 'TableMigration by XTIVIA 1.0.0.1' because no previous version was found.
In SQL Server, it looks like the sync already moved the tables to the extension suffix.
Also get the same error with Application
Cannot upgrade the extension 'Application by Microsoft 18.0.23013.23795' because no previous
version was found.

**Comment by jswymer** [comment]
Hello, 

1. Sorry, but I don't know how long we expect to support this upgrade method. 
2. Task 12 step 3 issue

    This seems odd because the only extension that should be installed at this time is the first version of the table migration extension (that is, the one that contains the table object definitions). This extension is installed automatically in Task 12.1, when you run the Start-NAVDatUpgrade cmdlet. This is because it was defined in the DestinationAppsForMigration key of the server instance config in Task 8, step 2.

    What extensions do you see if you run `Get-NAVAppinfo -ServerInstance <name> -Tenant <tenant ID or default>`?
3. Task 15

    It seems like the  first version of the table migration extension was never installed by Task 12, step1.

**Comment by jswymer** [comment]
Hello,

We've recently ran through the upgrade and did not experience any issues. We just wanted to follow up on this issue, and see whether come further and have any more comments. Thanks!

**Comment by jswymer** [comment]
Hello, 

We hope we've answered your questions and you've succeeded in your upgrade. We'll close this issue for now. But if you have more feedback or information, let us know and we'll reopen it. Thanks!
