### ISSUE TITLE
Link pointing to wrong URL for "Released Updates for Microsoft Dynamics 365 Business Central 2020 Release Wave 2 on-premises"

### ISSUE THREAD

**Issue by spiderted1985** [MicrosoftDocs/dynamics365smb-devitpro-pb#1823]
In Task 11: Change application version, the link to get the build number for the different BC17 versions is pointing to BC 2020 Wave 1, instead of Wave 2.

![URL Link MSFT](https://user-images.githubusercontent.com/48030526/116598882-60d5a480-a8f5-11eb-968e-bdcadf9783ba.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33157c57-b602-c02f-bcd3-0ed452cd29c4
* Version Independent ID: 9bb54d75-1587-ad90-c0a3-1d6800fc89cf
* Content: [Upgrading Version 16 Base Application to Version 17 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v16-to-v17)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v16-to-v17.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-v16-to-v17.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback!  The link has been fixed to target [https://support.microsoft.com/en-us/help/4583507](https://support.microsoft.com/en-us/help/4583507). The update will be published soon.
