### ISSUE TITLE
Please provide more detail and an example.

### ISSUE THREAD

**Issue by christian-clausen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1826]
Please provide more detail and an example.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031b4660-46e5-801d-199f-42ef30d0ead1
* Version Independent ID: cce7930c-a42f-cd4a-1540-3fc982019ce2
* Content: [ControlType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-controltype-property)
* Content Source: [dev-itpro/developer/properties/devenv-controltype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-controltype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This seems to be an old article ported from Dynamics NAV, but is no longer applicable to Business Central. In Business Central you specify the type of a control directly when defining a new control in AL code, such as `field`, `group`, `repeater`, `area`, and so on. This article will be removed to avoid confusion.
