### ISSUE TITLE
Please give an example

### ISSUE THREAD

**Issue by christian-clausen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1829]
Please give an example of how to use this property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea80097b-5d2e-8f56-8f92-55900361561d
* Version Independent ID: 27ad6299-c31d-a079-aa19-48d2d4d70d86
* Content: [CustomAPIName Property (Page) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-customapiname-page-property)
* Content Source: [dev-itpro/developer/properties/devenv-customapiname-page-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-customapiname-page-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Please check #1828 for a reply. Closing this issue. Thanks.
