### ISSUE TITLE
Missing Purpose of Evaluation Company

### ISSUE THREAD

**Issue by AR101** [MicrosoftDocs/dynamics365smb-devitpro-pb#183]
It would be nice, if the purpose of the evaluation company switch could be explained in more detail or reference another link, which explains the purpose of evaluation companies.

After a quick search I was not able to find out what it does explicitly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e55b7ded-5f97-ebcf-5c2d-90d4fc8a3eda
* Version Independent ID: f0d2c4b2-75ef-ace2-7d14-c945e5ccb08e
* Content: [New-NAVCompany (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/new-navcompany?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Management/New-NAVCompany.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Management/New-NAVCompany.md)

**Comment by edupont04** [comment]
Hello, and thank you for your feedback! The -EvaluationCompany parameter is used in connection with Microsoft Dynamics 365 Business Central online deployments and has no impact on on-premises deployments of Dynamics NAV or Dynamics 365 Business Central. I'll see what we can do to mark the parameter as irrelevant for your use.

**Comment by jswymer** [comment]
The -EvaluationCompany parameter help has been updated to indicate that it for online deployments only. The updated content will be available soon.
