### ISSUE TITLE
Upgrading Business Central 14 

### ISSUE THREAD

**Issue by Lethager** [MicrosoftDocs/dynamics365smb-devitpro-pb#1830]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7580ad2e-b731-a55f-99eb-431a5fd5210b
* Version Independent ID: de64736d-2690-0047-596b-3ccd65f13693
* Content: [Technical Upgrade From Version 14 to Version 18 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v18)
* Content Source: [dev-itpro/upgrade/upgrade-technical-upgrade-v14-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

It seems that there are no comments for this issue. Let us know if there is something you would like to add. Thanks!

**Comment by jswymer** [comment]
I will close this issue, because it is covered by #1835.
