### ISSUE TITLE
Updrading Stndard Business Central 14 to standard Business Central 18

### ISSUE THREAD

**Issue by Lethager** [MicrosoftDocs/dynamics365smb-devitpro-pb#1831]
What is the steps when I need to upgrade an standard Business Central from version 14 to version 18?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7580ad2e-b731-a55f-99eb-431a5fd5210b
* Version Independent ID: de64736d-2690-0047-596b-3ccd65f13693
* Content: [Technical Upgrade From Version 14 to Version 18 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v18)
* Content Source: [dev-itpro/upgrade/upgrade-technical-upgrade-v14-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

Thanks for the reply. I'll try to to guide, but I might need some more info. 

This procedure is only if you want to upgrade the platform.

If you have an unmodified Business Central 14 solution, for example, just the Cronus Demo application with no custom code, and you want to upgrade to the version application, you can follow this procedure:
[Upgrading Unmodified C/AL Application to Version 18](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v18)

If you have customized version 14 application, you should follow this procedure:

[Upgrading Customized C/AL Application to Microsoft Base Application Version 18](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v18)

**Comment by jswymer** [comment]
Hello, 

I hope this information has helped. We'll close this issue for now, but if you have more questions, let us know and we'll reopen it. Thanks!
