### ISSUE TITLE
Max value of DecimalValue

### ISSUE THREAD

**Issue by oki-g** [MicrosoftDocs/dynamics365smb-devitpro-pb#1834]
The specification of the maximum number of DecimalPlaces which can be set should be documented (actually 18).
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51404c6c-17e6-6135-62ca-88ff804c0ebf
* Version Independent ID: 398f7548-f7d7-2a15-8558-28a86e2c27e4
* Content: [DecimalPlaces Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-decimalplaces-property)
* Content Source: [dev-itpro/developer/properties/devenv-decimalplaces-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-decimalplaces-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thank you for the feedback. It has been specified in this article and will be available with the next refresh.
