### ISSUE TITLE
Non-standard table and card page in the sample code

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#1837]
Regarding the sample table: did you perhaps intend to give the Code field NotBlank=true? Having a potentially blank code but a required Description does not seem to make much sense to me?

Regarding the card page: in situations where a table has both a list and a card page, I don't think the card page should be treated as a task (UsageCategory = Tasks)? See for example the Customer Card - that does not have a UsageCategory, either?

Thanks for considering my comments. Apologies if I misunderstood the gist of the sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc13a127-253d-6438-52ed-319589d8d3ec
* Version Independent ID: 9bcc413c-55cb-a0e0-8ca2-f111658076fe
* Content: [Building your first sample extension that uses new objects and extension objects - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-example)
* Content Source: [dev-itpro/developer/devenv-extension-example.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-extension-example.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. I think that your comments make good sense, and this topic was essentially one of the first long examples back when we launched AL - and has not been thoroughly revised since then. We will definitely consider your comments and when time allows make a couple adjustments to the topic. Thanks!
