### ISSUE TITLE
Description of "-GenerateSymbolReference" switch is missing

### ISSUE THREAD

**Issue by AR101** [MicrosoftDocs/dynamics365smb-devitpro-pb#184]
The description could be copied directly from here I guess:
https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.ide/compile-navapplicationobject?view=businesscentral-ps

Would have adjusted it myself, but could not find the edit button as on other docs sites. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb8b066-05c0-2933-1540-00128f4a7ba3
* Version Independent ID: 43268fed-f5b1-a98d-0f65-e9fecd4bb975
* Content: [Compile-NAVApplicationObject (Microsoft.Dynamics.Nav.Ide)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.ide/compile-navapplicationobject?view=dynamicsnav-ps-2018)
* Content Source: [dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Ide/Compile-NAVApplicationObject.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Ide/Compile-NAVApplicationObject.md)

**Comment by jswymer** [comment]
The missing parameter has been included and the updated article will be published soon. Thanks for the feedback!
