### ISSUE TITLE
BC 18.1 method PackageId is not documented

### ISSUE THREAD

**Issue by christian-clausen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1841]
I noticed that following yesterday's release of Business Central 18.1 and runtime 7.1, the new PackageId method is not yet documented. I don't know if this is due to the OnPrem delay or normal process. In general, it would be great if technical (devitpro) documentation would always be published at release time, as up-to-date documentation allows developers and administrators to quicker get familiar with new capabilities.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e356cba4-8f4e-bbd4-2294-e21433e6cd47
* Version Independent ID: 804d33ae-022e-7641-3c72-1b85a5481907
* Content: [ModuleInfo Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/moduleinfo/moduleinfo-data-type?source=docs)
* Content Source: [dev-itpro/developer/methods-auto/moduleinfo/moduleinfo-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/moduleinfo/moduleinfo-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, the docs are updated with the refresh today.
