### ISSUE TITLE
meaning of Return Value for calcsums not clear

### ISSUE THREAD

**Issue by ReneGubler** [MicrosoftDocs/dynamics365smb-devitpro-pb#1842]
It would be great if you can describe what "the operation does not execute successfully" means. 

If you refere to the oder versions  it was very clear what it means:

"Not successfully" :  _"If you omit this optional return value and if one of the fields is not a SumIndexField, a run-time error occurs. If you include a return value, you must handle any errors."_

[NAV documentation](https://docs.microsoft.com/en-us/dynamics-nav/calcsums-function--record-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e484a82-12eb-7ed7-caa2-1e4224f14123
* Version Independent ID: dbf1db1d-6625-81fd-693b-554d24dbf555
* Content: [Record.CalcSums Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-calcsums-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-calcsums-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-calcsums-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this has been clarified in the article and will be available with the next refresh.
