### ISSUE TITLE
CaptionManagement does not exist or replaced by other Codeunit

### ISSUE THREAD

**Issue by SUD-D365** [MicrosoftDocs/dynamics365smb-devitpro-pb#1844]
[Enter feedback here]
In latest version of BC i am not able to find CaptionManagement codeunit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 256aabb4-8d5d-cc06-6c1f-5558c668491b
* Version Independent ID: 51d1427c-130d-b5c0-3d04-89c01caa89f8
* Content: [Event Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-event-types)
* Content Source: [dev-itpro/developer/devenv-event-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-event-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback.

These events were moved to codeunit 42 "Caption Class" of the System Application in BC 2019 release wave 2. You can this in [Breaking Changes](https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md#caption-class-module). 

The article will be updated. I hope this answers your question.
