### ISSUE TITLE
Minor clarification needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1847]
Hello,

The main topic does not mention that you can put text after the #region directive, although the example does show it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 848d8a4c-36eb-fcd8-9356-41f6b9aaa374
* Version Independent ID: 7d4a0936-c48e-3507-91f8-8fbf1f560817
* Content: [Event example - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-events-example)
* Content Source: [dev-itpro/developer/devenv-events-example.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-events-example.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. Your comment doesn't seem to apply to the topic in question here. Can you elaborate? Thanks.

**Comment by j2associates** [comment]
Hello,

Sorry about that. It should have been attached to topic Region Directive in
AL:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-region
.

There is a bug in the comments code. If you leave multiple comments in a
fairly short time frame, even though it says new comment, it will remember
some of your old content. If you check the GitHub link above, you will
notice that I left some comments there first. And then when I switched to
the Region Directive topic and attempted to leave a comment there, it cross
posted. I have seen that behavior multiple times in the past, but never
thought to actually bring it up.

Have a great day!

Gary

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the clarification, it makes sense. Unfortunately, we're not able to fix the behavior, but it's good to know. For the #region directive, we will look into this. Thanks!

**Comment by SusanneWindfeldPedersen** [comment]
Hello again, with the next push to live the topic is updated with a note on this. Thanks.
