### ISSUE TITLE
ID confusion

### ISSUE THREAD

**Issue by ibachus** [MicrosoftDocs/dynamics365smb-devitpro-pb#185]
I don't understand where ID 70000900 comes from.  The documentation says that it adds field ShoeSize with ID 70000900 but that number is not referenced anywhere in the code.  Actually, while we are at it, where does the ID 50115 come from in the tableextension declaration?  Since this isn't a new object (just adding a new field), that can't be an object id.  I'm confused about where that ID comes from too.  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c348c2-9e0a-3100-890d-66d31e088acd
* Version Independent ID: 79dc7696-ce78-a5a0-418f-d7d81263de66
* Content: [Table Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-ext-object)
* Content Source: [dev-itpro/developer/devenv-table-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-table-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. You're absolutely right the ID 70000900 is a leftover that should've been corrected to 50116, the ID of the ShoeSize field. The ID for the page extension object needs to be there, though, extension objects have IDs even though the extend exsisting objects. The fix will be available with the next doc refresh. Thanks again.

**Comment by rcfoyn** [comment]
@SusanneWindfeldPedersen, I take it you meant "The ID for the *table* [not page] extension object needs to be there". What determines the table extension ID? Set by the developer or assigned automatically?
