### ISSUE TITLE
Semicolon in example is missing

### ISSUE THREAD

**Issue by dennisroczek** [MicrosoftDocs/dynamics365smb-devitpro-pb#1854]
A semicolon is missing in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a823b7d-67d3-9312-e00a-49f880a728a0
* Version Independent ID: d24658ae-7feb-e32d-534b-b7311ffa6c95
* Content: [AppSourceCop Rule AS0094 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0094-permissionsetsshouldnotbeinxml)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop-as0094-permissionsetsshouldnotbeinxml.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/analyzers/appsourcecop-as0094-permissionsetsshouldnotbeinxml.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your contribution. This will be available with the next doc refresh.
