### ISSUE TITLE
Redirecting link fails

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#186]
Deliver consulting services as a VAR: 
https://aka.ms/BusinessCentralConsultingServices

Redirects to https://www.microsoft.com/es-es/

This happens even if I've first signed in with my partner credentials.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee3fa1ff-6b4d-2215-7fa8-566933f336d5
* Version Independent ID: 67386d86-8e5b-565f-537a-e46197bfb9b8
* Content: [Ready to Go - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-ready-to-go?tabs=learning)
* Content Source: [dev-itpro/developer/readiness/readiness-ready-to-go.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-ready-to-go.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by edupont04** [comment]
We've reached out to the team owning that link. Hang on!

**Comment by edupont04** [comment]
The redirection has been fixed so that the link takes you to the equivalent of https://appsource.microsoft.com/en-us/marketplace/consulting-services?country=US&page=1&product=dynamics-365%3Bdynamics-365-business-central

**Comment by Bleika** [comment]
Thank you Eva, but I would have expected that - being a part of ReadyToGo - it would contain some kind of readiness material for this particular development scenario (like you have for the other scenarios), rather than just the actual offers listings on Appsource???

**Comment by edupont04** [comment]
Hi Bleika,
I understand your surprise and disappointment. You can choose to share that with the ReadyToGo team through the normal channels.

**Comment by Bleika** [comment]
Hi Eva,
By chance I stumbled upon what seems to be the right link:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-consulting
(it contains a link to App source as well)
