### ISSUE TITLE
Documentation for TransferFields does not explain what it means by "matching fields"!

### ISSUE THREAD

**Issue by dtkb** [MicrosoftDocs/dynamics365smb-devitpro-pb#1860]
It just says:

> Copies all matching fields in one record to another record.

It should explain what "matching" means, i.e. that it'll try to copy based on fields with the same ID in source/destination tables - but those fields must have the same or compatible(?) type, otherwise it'll generate a runtime error instead of just ignoring them.

Please revise to properly document what a "match" is and in what situations we should expect fields with the same IDs to copy succesfully, be ignored, or cause a runtime error.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c66ab2a9-7864-bbdb-7dce-2f8779dfc327
* Version Independent ID: 18950d13-7624-300f-4246-8f4001a1a6cb
* Content: [Record.TransferFields Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dtkb** [comment]
The [NAV documentation](https://docs.microsoft.com/en-us/dynamics-nav/transferfields-function--record-) said this. Not sure why the documentation was lobotimised while being migrated to BC?

***

_**Remarks**_

*TRANSFERFIELDS copies fields based on the Field No. Property of the fields. For each field in Record (the destination), the contents of the field that has the same Field No. in FromRecord (the source) will be copied, if such a field exists.*

*The fields must have the same data type for the copying to succeed (text and code are convertible, other types are not.) There must be room for the actual length of the contents of the field to be copied in the field to which it is to be copied. If any one of these conditions are not fulfilled, a run-time error will occur.*

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - the method topic was auto-generated based on AL code and the remarks were not re-added after this. The functionality hasn't changed, so NAV documentation is still valid in this case. The issue will be fixed with the next doc refresh.

**Comment by db-bc** [comment]
The link against which I reported this has not been updated. Should I be looking somewhere else, or did the update get lost?

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-method
