### ISSUE TITLE
AutoFormatExpression = '$<precision, 2:2><standard format, 0>;

### ISSUE THREAD

**Issue by Kushal5** [MicrosoftDocs/dynamics365smb-devitpro-pb#1861]
[Enter feedback here]

AutoFormatExpression = '$<precision, 2:2><standard format, 0>;

There needs to be an ' at the end. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b62aefc-7ada-dbb7-cc0b-81cd16a2e1ee
* Version Independent ID: b196487a-58e7-b137-2581-5bb4b60aaf57
* Content: [AutoFormatType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-autoformattype-property)
* Content Source: [dev-itpro/developer/properties/devenv-autoformattype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-autoformattype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue will be fixed with the next doc refresh.
