### ISSUE TITLE
Changing the syntax text of the method documentation

### ISSUE THREAD

**Issue by DuttaSoumya** [MicrosoftDocs/dynamics365smb-devitpro-pb#1862]
Hi Susanne,

The syntax of the function should be changed from,
Ok :=   Record.AreFieldsLoaded(Fields: Any,...)
to
Ok :=   Record.AreFieldsLoaded([Fields: Any,...])

Note the square brackets which implies that there are multiple fields. For reference, take a look at,
https://docs.microsoft.com/da-dk/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-addloadfields-method

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: e7fce1a4-217e-7dae-563b-fb54365a9646
* Version Independent ID: 97968c14-73c4-ac44-1f6a-d2e23fa85640
* Content: [Record.AreFieldsLoaded Method - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-arefieldsloaded-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-arefieldsloaded-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-arefieldsloaded-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The [] square brackets are meant to imply that a parameter in this case is optional. But that is most likely not true for the example you linked to record.addloadfields method - I have created a bug to have an engineer look into this. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
closing as this is fix in code. thanks
