### ISSUE TITLE
standard integer formats

### ISSUE THREAD

**Issue by grantbrimhall** [MicrosoftDocs/dynamics365smb-devitpro-pb#1865]
can you please provide an example for integer thousand? this should take 30 seconds for an inexperienced developer to find a page to tell them this. and I've spent too much time trying to find a very simple answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 286fe842-d3a2-ba49-77d4-4513e2ce350a
* Version Independent ID: dfc559a5-1f4c-8a61-7b58-76f5d2771397
* Content: [Format Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-property)
* Content Source: [dev-itpro/developer/devenv-format-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-format-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry that you had trouble finding this. In the topic you mention there's a table https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-property#standard-decimal-formats - with examples of the formats - if this is not what you're looking for, can you please elaborate. Thanks.

**Comment by grantbrimhall** [comment]
Hi Susanne, thanks for you note. Here is the section that I hoped had more examples:

STANDARD INTEGER FORMATS

I'm trying to extend a page, with a calculated number that is an integer. And I cannot figure out what I need to do with AutoFormatType or AutoFormatExpression to make the number appear with a thousand seperator.

This does not work:

                    field(NumberOfSalesOrders; NumberOfSalesOrders)
                    {
                        Caption = 'Number of Sales Orders';
                        ApplicationArea = Planning;
                        AutoFormatType = 10;
                        AutoFormatExpression = '<Integer Thousand>';
                        Editable = false;
                    }

Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I just replied on the other github issue. Thanks for your question, this is a bit complicated because there are so many options for settings. I think your example works, if only you switch your regional setting in BC to English(US). At least Message(Text000, Format(-1234, 12, '<Integer Thousand>')); gives 1,234 when I switch in Business Central (under Settings/Region). Hope it works, thanks!

**Comment by grantbrimhall** [comment]
Hi Thanks for your note ...

I guess I was looking for something similar to formatting a decimal field ...

Column(DecimalField; SomeDecimalVariable)
{
                DecimalPlaces = 2:5;
}

... where I could just take the column, and format the field using properties. Perhaps:

Column(IntegerField; someIntegerVariable)
{
                AutoformatExpression = '<Integer Thousands>';
}

But I guess that's not possible? I have to write my column as a text variable that I set following the example you showed?

Thx for your help.

-Grant

Grant Brimhall
SENIOR ERP ARCHITECT
O: 385.381.2822  |  M: 801.717.5712
JourneyTEAM  |  www.journeyteam.com<https://nam04.safelinks.protection.outlook.com/?url=www.journeyteam.com&data=02%7C01%7Cgrant.brimhall%40journeyteam.com%7C0d64a5c8884e43335d4e08d7c5154eab%7Cb59c07c69496463aab8177697ac73d11%7C1%7C0%7C637194568818019651&sdata=p25w61X7xEz2kxQ5op6W8AQjaTwqh7Q5%2B7ehnRN6lhA%3D&reserved=0>

***@***.***D758B6.0CD7CB40]

**Comment by SusanneWindfeldPedersen** [comment]
Hi - please allow me to check this with an experienced developer - thanks

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your patience. We have checked and it seems that converting to text would be the only solution. The AutoFormat property works only on decimals. Feel free to suggest a product idea through [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central). But on the short term, your suggestion seems to be the solution for now. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue
