### ISSUE TITLE
JsonValue.AsDateTime example missing 

### ISSUE THREAD

**Issue by dNsl9r** [MicrosoftDocs/dynamics365smb-devitpro-pb#1866]
In the "Remarks" Part the is the following text:

> If the JsonValue does not contain a string of the format "o" as specified here the operation will fail with a run-time error.

Is it possible, that there format description is missing? It says "o" - seems not correct to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 351a84b1-6500-cf37-a477-749d9f0c44ca
* Version Independent ID: be9fa1f0-e30e-a6e2-fbea-c368727eeb8c
* Content: [JsonValue.AsDateTime Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonvalue/jsonvalue-asdatetime-method)
* Content Source: [dev-itpro/developer/methods-auto/jsonvalue/jsonvalue-asdatetime-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/jsonvalue/jsonvalue-asdatetime-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback! The "o" format refers to [The round-trip ("O", "o") format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier). The article has been updated to include this information.
