### ISSUE TITLE
No mention of On-Prem only

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1869]
1. There is no mention made in the article that this applies to On-Prem only. Of course, the poor developer that tries to use it will find out soon enough when their code won't compile. Every topic pertaining to File Management should contain a fairly prominent note about this topic only applies to On-Prem.

2. Where are the topics about how to display and interact with the File Chooser that the SaaS solution uses (e.g. when Downloading a custom report layout)? I have searched multiple times and all I find are many references to the File Management codeunit which is not available in SaaS.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200d72e3-3134-b81a-44bf-8e8050aa8b4f
* Version Independent ID: d0003d57-5e71-5e5b-fef3-117b78e406c0
* Content: [File.DownloadFromStream Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-downloadfromstream-method)
* Content Source: [dev-itpro/developer/methods-auto/file/file-downloadfromstream-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/file/file-downloadfromstream-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback and sorry for the hassle - most of the other methods under the File Data Type are marked with a note about on-prem, this one for example: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-download-method - so this must be a bug, we will look into how this topic was missed.

As for your second question, I will try to find out. Keeping this issue open.

**Comment by j2associates** [comment]
I appreciate your helpfulness and look forward to the answer to #2 above.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your patience, I think we now have a solution that you can hopefully use. 1) the method is available for SaaS, but not all parameters are supported, so it's correct that the topic itself doesn't have a note about on-prem only. 2) we have refreshed the content of that topic to contain a valid example for cloud, you can see that here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-downloadfromstream-method.
When downloading in the cloud, the browser will display a Download dialog in the corner typically - it's not possible to write to a path. I hope this helps. Thanks!

**Comment by SusanneWindfeldPedersen** [comment]
Docs are live with new example. Closing this issue. Thanks.
