### ISSUE TITLE
Section "Enabling .NET Interoperability"

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#187]
Regarding Section "Enabling .NET Interoperability":
It would be nice, if there would be a sentence that you need to add `"target": "Internal"` to app.json.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6350ffb-3e0f-92de-8455-bbf3a316f62e
* Version Independent ID: 96ee3cfc-16c4-ae11-6a69-15e33ae85c1d
* Content: [Getting started with Microsoft .NET Interoperability from AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-call-dotnet-from-al)
* Content Source: [dev-itpro/developer/devenv-get-started-call-dotnet-from-al.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-get-started-call-dotnet-from-al.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This is fixed with the next doc refresh.
