### ISSUE TITLE
Add documentation for odata.maxpagesize

### ISSUE THREAD

**Issue by dagirard** [MicrosoftDocs/dynamics365smb-devitpro-pb#1871]
In version 17, we added support for the HTTP Prefer header => odata.maxpagesize=<int> => Which allows to override the server setting ODataServicesMaxPageSize.

Similar to here (Powerapps doc):
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/query-data-web-api#specify-the-number-of-tables-to-return-in-a-page

Note: odata.maxpagesize cannot be greater than the server setting "ODataServicesMaxPageSize".

Also, for the page: "Using OData with Queries That are Set with a Top Number of Rows", it must be added that using the setting "odata.maxpagesize" is prefered over using $top and $skip.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 608b13bf-87f9-a39d-86ea-6bf9891bfa3d
* Version Independent ID: 16990f54-8e59-478c-91b4-53a7f177dcd9
* Content: [Server-Driven Paging in OData Web Services - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/server-driven-paging-in-odata-web-services)
* Content Source: [dev-itpro/webservices/Server-Driven-Paging-in-OData-Web-Services.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/webservices/Server-Driven-Paging-in-OData-Web-Services.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
The content has been updated by https://github.com/MicrosoftDocs/dynamics365smb-devitpro/pull/2707. Thanks for the feedback!
