### ISSUE TITLE
Wrong command usage for the page with "Get-NAVAppTableModification"

### ISSUE THREAD

**Issue by RedFoxUA** [MicrosoftDocs/dynamics365smb-devitpro-pb#1874]
Hi All.
I can see the wrong command usage for the page with the description "Get-NAVAppTableModification" : 
e.g. for each Example we can see something like "Get-NavAppTableModification**_s_** -ServerInstance DynamicsNAV91", but correct value is "Get-NavAppTableModification -ServerInstance DynamicsNAV91" (without "s")

The source link is https://docs.microsoft.com/es-es/powershell/module/Microsoft.Dynamics.Nav.Apps.Management/get-navapptablemodification?view=businesscentral-ps-18

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

We've fixed the examples, and an update will be published soon.

**Comment by RedFoxUA** [comment]
I can see it is still the same :(

**Comment by jswymer** [comment]
Hello, The update has not yet been published.
