### ISSUE TITLE
"Only guaranteed to work with same version"

### ISSUE THREAD

**Issue by mitrov** [MicrosoftDocs/dynamics365smb-devitpro-pb#1879]
"Runtime packages are guaranteed to work only if published to a platform with the same version as the one where they were produced."

Same version? What does that mean? Same Major? Same Minor? Same Build?

If I create a runtime package with 18.0, will it work with 18.1 ... 18.x?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aea33a83-64c0-a56b-363a-b5aae7eb15f5
* Version Independent ID: a7919faa-7603-573b-ef43-10c60c3803d9
* Content: [Creating Runtime Packages for Business Central On-Premises - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages)
* Content Source: [dev-itpro/developer/devenv-creating-runtime-packages.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-creating-runtime-packages.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by thpeder** [comment]
Hi @mitrov,
Strictly speaking we will only guarantee them to work on the same build, but it is unlikely something will change within the same minor and we try to not break them within a major, but sometimes there are security updates that could break these package.

**Comment by mitrov** [comment]
Thanks @thpeder 

As an ISV this is really hard for us to maintain properly. We'll try to ship Runtime Packages which were created with RTM onPrem versions and hope that they still work even when someone has a new minor installed.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks all, closing this issue.
