### ISSUE TITLE
Instructions state "expand OData Services Tab"

### ISSUE THREAD

**Issue by W0GER** [MicrosoftDocs/dynamics365smb-devitpro-pb#1880]
There isn't any tab named "OData Services" in our Business Central Admin tool. 

Available tabs are: 
1. Environments
2. Notification Recipients
3. Telementry
4. Reported Outages
5. Operations
6. Capacity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb34a28d-cadf-e5f7-ae56-156b3109e038
* Version Independent ID: 67096d75-38b2-d87f-664e-d6d2dec98322
* Content: [Enabling APIs for Microsoft Dynamics NAV - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/enabling-apis-for-dynamics-nav)
* Content Source: [dev-itpro/api-reference/v2.0/enabling-apis-for-dynamics-nav.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/enabling-apis-for-dynamics-nav.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by W0GER** [comment]
Thank you for the clarification that this article pertains to the on-premises version. As a reader, I don't see any reference to on-premises vs online version in the article; is there some indicator I'm missing?

**Comment by jswymer** [comment]
Hello again, we've added a note indicating that the article pertains to on-premises only. The update will be published soon.

Thanks!
