### ISSUE TITLE
D365 EXTENSION MGT has become obselete

### ISSUE THREAD

**Issue by srenders** [MicrosoftDocs/dynamics365smb-devitpro-pb#1883]
Hi,

Since BC18 the D365 EXTENSION MGT permission set has apparently become obsolete:
![D365 EXTENSION MGT Obselete](https://user-images.githubusercontent.com/17511254/119963972-fcb40800-bfa8-11eb-8653-627c5ef9bf26.jpg)

Maybe this docs page (and others) need to be updated to explain how this impacts the ability to be able to publish/install an app from VSCode?
![pte](https://user-images.githubusercontent.com/17511254/119964394-75b35f80-bfa9-11eb-9c71-ef06824f7d13.jpg)

Greetings,
Steven

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e08e71d8-8646-47c4-31d4-b3227fa4d958
* Version Independent ID: 12dcd23f-6600-b90a-7724-5d5cf3f4a5c3
* Content: [Getting Started with AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started)
* Content Source: [dev-itpro/developer/devenv-get-started.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-get-started.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback.

This D365 EXTENSION MGT permission set has been replaced by the EXTEN. MGT. - ADMIN permission set. We've updated the documentation. The update will be published soon. Thanks
