### ISSUE TITLE
Microsoft images blog post link does not contain the information promised

### ISSUE THREAD

**Issue by territowelling** [MicrosoftDocs/dynamics365smb-devitpro-pb#1884]
Click on the AppSource get it badge and it redirects to a blog post from September 2019 with no valid links to the image.  I'm unable to find where to go to get this badge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 463e4bf4-3be8-4b89-21e2-9194e264fe38
* Version Independent ID: c2619d79-96f0-bd7b-e230-5e5d59f2bc3a
* Content: [Language, Branding, and Images - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-a-languange-branding#branding-requirements)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-a-languange-branding.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/readiness/readiness-checklist-a-languange-branding.md)
* Service: **dynamics365-business-central**
* GitHub Login: @a-emniel
* Microsoft Alias: **a-emniel**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. On the blog post page, there's a link to the Marketing Resources Guide, which should download a AppSource and Azure Marketplace Marketing Resources Guide with images to use. Hope that helps. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this
