### ISSUE TITLE
Add Documentation to Setup AL.assemblyProbingPaths for modifying the system application

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#1885]
Could you please add a example how to setup the assemblyProbingPaths correctly?
https://github.com/microsoft/ALAppExtensions/pull/12538#issuecomment-851440048
See this issue for the correct syntax and maybe ask those developer for a dynamic expanation what paths are needed that the System Application will compile

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb3ed382-91a7-c867-605b-ff8fbf956d79
* Version Independent ID: 6a955fe9-c42e-3e32-f895-622d2745086b
* Content: [Set Up an Environment for Developing a Module - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-set-up-an-environment)
* Content Source: [dev-itpro/developer/devenv-set-up-an-environment.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-set-up-an-environment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello, 
Thank you for your feedback! This has now been fixed in today's doc update as a new step 8 at https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-set-up-an-environment#get-the-repository-on-your-local-machine
