### ISSUE TITLE
SaveValues of pages don't save filtervalues 

### ISSUE THREAD

**Issue by dennisroczek** [MicrosoftDocs/dynamics365smb-devitpro-pb#1887]
SaveValues of Pages (not RequestPages) don't save user inserted filters. Only RequestPages do save the filters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dce95ba-a175-0884-d851-173c7c13e897
* Version Independent ID: 711c1256-ed89-152c-3fca-bf11363bdc00
* Content: [SaveValues Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-savevalues-property)
* Content Source: [dev-itpro/developer/properties/devenv-savevalues-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-savevalues-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback and for your contribution!
