### ISSUE TITLE
Transitioning GP and NAV customers to Business Central shortcode doesn't work

### ISSUE THREAD

**Issue by philstubbington** [MicrosoftDocs/dynamics365smb-devitpro-pb#1892]
https://aka.ms/BCmigrations doesn't lead anywhere.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee3fa1ff-6b4d-2215-7fa8-566933f336d5
* Version Independent ID: 67386d86-8e5b-565f-537a-e46197bfb9b8
* Content: [Ready to Go - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-ready-to-go)
* Content Source: [dev-itpro/developer/readiness/readiness-ready-to-go.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/readiness/readiness-ready-to-go.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The link should work now and point to https://dynamicspartners.transform.microsoft.com/products/dynamics-365-business-central?tab=go-to-market - thanks
