### ISSUE TITLE
First example block does not compile

### ISSUE THREAD

**Issue by TrippyZ** [MicrosoftDocs/dynamics365smb-devitpro-pb#1895]
First example block does not compile.  The var declaration of Customer breaks the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516301a7-15c8-d7cf-6026-e5cb19437b93
* Version Independent ID: c15bc744-7d2e-8c5f-0aa8-fa3f01da6912
* Content: [AL Complex Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-complextypes)
* Content Source: [dev-itpro/developer/devenv-al-complextypes.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-al-complextypes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @esbenk
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The code example is updated with the next doc refresh.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. There's currently a known issue with the exit(); statement which will be fixed with a future minor update. Is that what you meant?

**Comment by TrippyZ** [comment]
No, I meant that the declaration for the Customer variable in the Var declaration section is not permitted according to the compiler.
This appears to be due to the Customer variable being already declared as the returning variable and thus already exists.

Therefore the following two lines;
var
 Customer: record Customer;

are an attempt to declare a variable that has already been declared.

Hopefully I have made myself clear.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the clarification. I can compile the code example - what version are you using?

**Comment by SusanneWindfeldPedersen** [comment]
Happy to hear that. And no bother at all. Thanks!
