### ISSUE TITLE
License agreement example not found

### ISSUE THREAD

**Issue by TKapitan** [MicrosoftDocs/dynamics365smb-devitpro-pb#1896]
The link to Plumbline Consulting’s License Agreement does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2511a190-4fe2-45ba-cfc3-a7d21d42b218
* Version Independent ID: e5996aeb-f342-5082-dd6c-589a44a03841
* Content: [Privacy Policy and Terms of Use - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-i-privacypolicy-termsofuse)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-i-privacypolicy-termsofuse.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/readiness/readiness-checklist-i-privacypolicy-termsofuse.md)
* Service: **dynamics365-business-central**
* GitHub Login: @a-emniel
* Microsoft Alias: **a-emniel**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. It seems like that page has been taken down. We will remove the link from the documentation with the next doc refresh. Thanks
