### ISSUE TITLE
The link for June 2021 update does not work

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#1899]
The link to the description of the june 2021 update https://support.microsoft.com/help/5003472 does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9afb787-c62c-1a40-53e0-fa345de5f7cf
* Version Independent ID: c2c7c805-d4cc-eef8-bf8f-f96d5c264e1d
* Content: [Cumulative updates for the Spring 2019 version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/update-versions-14?source=docs)
* Content Source: [dev-itpro/deployment/update-versions-14.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/deployment/update-versions-14.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, thanks for the feedback. The link should work now.
