### ISSUE TITLE
NAV Major versions

### ISSUE THREAD

**Issue by bgbak** [MicrosoftDocs/dynamics365smb-devitpro-pb#19]
Consider replaceing references to NAV major versions with e.g. _<major version>_
Currently both version 90 and 110 are referenced in the docs.
If not replacing version with version tag, consider replacing all references to versions with the current version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7da0a91-781a-6b5a-3257-364301f98d49
* Version Independent ID: 35b14bd0-dea0-92a6-9fc7-5702045d3aca
* Content: [Windows Client Configuration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/configuring-the-windows-client)
* Content Source: [dynamics-nav/Configuring-the-Windows-Client.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Configuring-the-Windows-Client.md)
* Service: **unspecified**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for your feedback. This will be fixed in the next refresh of the documentation.
