### ISSUE TITLE
Repair-navapp for runtime packages creates problems with function IDs

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#1901]
Hi,
in the step 7. Recompile extensions not build on version 18. is used the repair-navapp cmdlet which recompiles the apps but will generate new IDs for the functions. This makes problem later, when some depending app is deployed as runtime package to the upgraded solution, because it will not match the IDs of the repaired apps. See https://www.yammer.com/dynamicsnavdev/threads/1228324111155200 
This should be described and in case of runtime packages there should be warning that it is better to republish the app through newly created runtime packages, if runtime packages must be used.

With regards

Kamil Sacek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab367758-d435-42cd-a1e1-d0b89c33ad25
* Version Independent ID: 4ea22d59-5d20-c0af-7bf8-e678c181b663
* Content: [Upgrading Version 15, 16, or 17 Base Application to Version 18 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v18)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

We've updated the article with a note stating that this cmdlet shouldn't be used for runtime packages in upgrade scenarios, but new packages should be generated instead. We've also made this clear in other related articles. The updated articles will be published soon.
