### ISSUE TITLE
Repair-navapp on v18 and runtime packages leads to new IDs of functions and potentially to errors connected to this fact

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#1902]
Hi,
for more details, see https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=1228324111155200 . If runtime packages are used (and they are used on customer's onprem systems), using repair-navapp will generate new IDs of functions, thus making all depending apps not working correctly. They must be fixed by repair-navapp but this leads only to shift of the problem to next level or the problem reappears when new version of the depending app is deployed into the solutions. This should be somehow described on this page.

With regards

Kamil Sacek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48b48c61-9ef6-c03e-929c-13e3b32f33d6
* Version Independent ID: 2f8339ec-c29b-f73a-3e83-66d8ddceb126
* Content: [Repair-NAVApp (Microsoft.Dynamics.Nav.Apps.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/repair-navapp?view=businesscentral-ps-18)
* Content Source: [businesscentral-ps-18/Microsoft.Dynamics.Nav.Apps.Management/Repair-NAVApp.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-18/Microsoft.Dynamics.Nav.Apps.Management/Repair-NAVApp.md)
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

We've updated the article with a note stating that this cmdlet shouldn't be used for runtime packages in upgrade scenarios, but new packages should be generated instead. We've also made this clear in other related articles. The updated articles will be published soon.
