### ISSUE TITLE
Two typos

### ISSUE THREAD

**Issue by caroleeschuck** [MicrosoftDocs/dynamics365smb-devitpro-pb#1904]
Below:
- MyBlogTable should be MyBlobTable
- ext should be Text

To help understand this, consider the following code examples. These example assume that a BLOB field called MyBlobField exists in a table called **MyBlogTable**.

AL

Copy
var
    myInt: Integer;
    MyRecord: Record MyBlobTable;
    MyOutStream: OutStream;
    MyInStream: InStream;
    Result: **ext**;
    CRLF: Text[2];

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2f4f68-c2ff-18ae-a814-8dbc03c2a322
* Version Independent ID: d1154955-7f82-a233-6b24-6de213debeb4
* Content: [Write, WriteText, Read, and ReadText Method Behavior - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-write-read-methods-line-break-behavior)
* Content Source: [dev-itpro/developer/devenv-write-read-methods-line-break-behavior.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-write-read-methods-line-break-behavior.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching these typos - the topic will be fixed with the next doc refresh. Thanks!
