### ISSUE TITLE
UnknowValueImplementation link in Remarks sections point to current page

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#1907]
Link should point to https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-unknownvalueimplementation-property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73d3e572-242b-95e1-2fc9-bfda513cddcd
* Version Independent ID: 01c0332c-30c9-99e3-2a75-6539fca9c5f4
* Content: [DefaultImplementation Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-defaultimplementation-property)
* Content Source: [dev-itpro/developer/properties/devenv-defaultimplementation-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-defaultimplementation-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic is fixed with the next doc refresh.
