### ISSUE TITLE
Task 4 - not task 2 I think :)

### ISSUE THREAD

**Issue by Kznoll** [MicrosoftDocs/dynamics365smb-devitpro-pb#1909]
Synchronize the tenant with the table migration extension. This is the tables only extension you created in task 2.

The Table Migration Extension was created in task 4 - not task 2 (That was in the older guides)
Synchronize the tenant with the table migration extension. This is the tables only extension you created in task 4.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1845f646-9ac3-4876-6958-fb797a78e63e
* Version Independent ID: 79fdd7f3-54b8-b1cd-cef6-a2e950e9dcda
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application for version 18 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v18)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed as suggested. The update will be published soon.
