### ISSUE TITLE
API - Accounts - Note incorrect

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#1913]
The (Note) "Only accounts with the account type set to Posting and the Direct Posting flag set to true are returned." is false.

Both in the product and in the example shown at the bottom.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2dfe156-6685-00ac-bcf7-08cc35abb99e
* Version Independent ID: a7d52999-3862-315b-7c7f-db2f650484a8
* Content: [Get accounts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_account_get)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_account_get.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_account_get.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This issue will be fixed with the next doc refresh.
