### ISSUE TITLE
Interface nomenclature question

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1914]
In other languages, such as c#, by convention an Interface variable is prefixed with I. In the example code in this topic there is an Interface variable defined. 

Should it be

IBarcodeFontProvider: Interface "Barcode Font Provider";

instead of 

BarcodeFontProvider: Interface "Barcode Font Provider";

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04fb2aaa-8676-c0ae-434b-eb3d85bddca4
* Version Independent ID: 9d634195-090b-8b48-1059-e45233d7dcba
* Content: [Adding barcodes to reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-add-barcodes)
* Content Source: [dev-itpro/developer/devenv-report-add-barcodes.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-report-add-barcodes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Yes, this would be more accurate adding discoverability to the code - will be fixed with the next doc refresh. Thanks!

**Comment by j2associates** [comment]
Just in case you are all sitting around twiddling your thumbs, would it be
possible to review all topics referencing interfaces to check for
consistency?

Thanks
