### ISSUE TITLE
Layout examples needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1915]
After very nice sample code explaining how to setup a report to print barcodes, there is nothing about the actual Word document layout except for the following sentence.

To use a barcode font in the report layout, mark the encoded string from the dataset with the font.

What does the above sentence mean and how do I go about implementing it?

Stefano Demiliani has a blog based upon the sample code in this topic entitled 
Dynamics 365 Business Central: native support for barcodes:
https://demiliani.com/2021/04/06/dynamics-365-business-central-native-support-for-barcodes/

In the blog, he gives an example of how to setup the Word layout. Following his blog, I set the Font name for the Content Control containing the Barcode to IDAutomationC39S. The first time I assigned it I got the error displayed in his blog screenshot.

But when I run the report, it does not display a barcode, it displays the Item No. in parentheses e.g. (1000).

Rather than a single somewhat obscure sentence, could the topic please be expanded to include at a minimum, a couple screenshots of how to setup the Word doc? It is very frustrating to follow a topic and then not have all of the information needed to produce a Word based report with a barcode.

Ideally, the topic should be expanded to include examples for both layouts, Word and RDLC.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04fb2aaa-8676-c0ae-434b-eb3d85bddca4
* Version Independent ID: 9d634195-090b-8b48-1059-e45233d7dcba
* Content: [Adding barcodes to reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-add-barcodes)
* Content Source: [dev-itpro/developer/devenv-report-add-barcodes.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-report-add-barcodes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by j2associates** [comment]
I was able to get the sample code to work after I made the following changes:

1. Changes to OnAfterGetRecordTrigger
    a. Added variable: BarcodeString: Text;
    b. Setup variable: BarcodeString := '*' + GTIN + '*';
    c. Passed variable to EncodeFont method: EncodedText := BarcodeFontProvider.EncodeFont(BarcodeString, BarcodeSymbology);

2. Changes to Word document
    a. Changes to Content Control holding Barcode: Hard coded font to IDAutomationC39C
        I only knew how to do this because of the blog post referenced above
        The topic example used EAN-13 but no guidance was provided on how to setup the Word layout document font

**Comment by j2associates** [comment]
I was also able to get an RDLC report to work in a similar manner as above. I hardcoded the Font in the RDLC document Textbox to IDAutomationC39S and it works.

**Comment by jswymer** [comment]
Hello,

We've made an update to the content. We hope it helps. Thanks for the feedback.
