### ISSUE TITLE
Why allow PK with 16+ fields?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1916]
In the note is stated:

`In the development environment, it's technically possible to create a primary key based on up to 20 fields. However, because of SQL Server limitations, only the first 16 are used.
`
Why does the platform allow me to enter 20 fields in the PK, where SQL Server will restricted it to 16? Why not let the platform also restrict it to 16? Does not make sense to me, but surely want to learn "the sense of it".

And if it does make sense, why not add that to the info box?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7516d3dc-c374-b3b8-e4ee-d01477b9244b
* Version Independent ID: 71253386-31b9-9f63-1919-1e429953a0a7
* Content: [Table Keys - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-keys#primary-keys)
* Content Source: [dev-itpro/developer/devenv-table-keys.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-table-keys.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by git-no** [comment]
I see your point, academically.
But if you want to develop a key with more than 10 fields, I would assume there is something generally wrong with the database design.
What happens if you create a key with 20 fields? Any warnings?
There was a time NAVISION supported more than one database engine. Maybe it will be in the future again.

**Comment by lvanvugt** [comment]
The topic is not about design flaws or whatsoever, it's about what the system enables and the info should be acurate.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thank you both for the feedback. In short, the fact that we allow 20 fields has to do with compatibility for older implementations. This is, however, becoming less of an issue and we might consider changing this with a future release. We will not update the note in the docs to elaborate on that. Thanks.
