### ISSUE TITLE
Variables in PascalCase and camelCase

### ISSUE THREAD

**Issue by DSaladinCH** [MicrosoftDocs/dynamics365smb-devitpro-pb#1917]
In my personal opinion the variable naming convention is unclear and not really usable.
The documentation clearly says that all variables has to follow PascalCase, but your function example does have 2 parameters in camelCase.
```
var
    Number: Integer;

local procedure MyProcedure(a: Integer; b: Integer): Integer
```

I think you should follow the naming convention of csharp. So global variables should use PascalCase and local variables (and parameters) should use camelCase. It is also a bit annoying if you need to variable with the same type and would like to use the same name (without a number or something like that). It is also more visible, if local variables are always lowercase at the beginning, that does are local variables.

I would love to hear what you think about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - will be fixed with the next doc refresh. As for best practices these have been established for a very long time, and are used internally by our developers too. For ideas on future improvements, please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
