### ISSUE TITLE
More examples Please

### ISSUE THREAD

**Issue by MasterAce** [MicrosoftDocs/dynamics365smb-devitpro-pb#1921]
I can't tell how to use this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 286fe842-d3a2-ba49-77d4-4513e2ce350a
* Version Independent ID: dfc559a5-1f4c-8a61-7b58-76f5d2771397
* Content: [Formatting Values, Dates, and Time - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-property)
* Content Source: [dev-itpro/developer/devenv-format-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-format-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by git-no** [comment]
More description of your issue, please. What exactly do you miss?
If it is about the `format`command there a lot of examples in the internet. This command is used over 20 years. The help description by MS seems sufficient to me and worked for me.
