### ISSUE TITLE
add(Integer) what does it mean and what are the alternatives when using Integer is not an option?

### ISSUE THREAD

**Issue by wolterOnEntocare** [MicrosoftDocs/dynamics365smb-devitpro-pb#1924]
Whithin the dataset {....} element the phrase add(Integer) appears.
The text does not explain the choice of "Integer" here.
Can one use it always? To my experience: not. When extending e.g. report 1308 I get a syntax error that says "A DataItem with name 'Integer' could not be found in the target Standard Sales - Shipment". What can one use if Integer is not an option? Please explain.

See the code below that produces this syntax error:
reportextension 70001 My1308SalesShipment extends "Standard Sales - Shipment"
{
    dataset
    {
        add(Integer)
        {
            //Add changes to dataset here
        }
    }
    requestpage
    {
        // Add changes to the requestpage here
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fedbf190-9d38-889f-4158-0d06e88d8b87
* Version Independent ID: 369fde2e-6cfc-cdae-b2f3-dc2a95a6d7a9
* Content: [Report Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-ext-object)
* Content Source: [dev-itpro/developer/devenv-report-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-report-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by git-no** [comment]
The data item name is *CopyLoop* not *Integer* as you can see by looking into the standard object.
I assume you have to use `add(CopyLoop)`.
By the way if you would format your code within this ticket it improve the readability and support.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback @wolterOnEntocare and @git-no - and yes, this repo is mainly for documentation issues, please contact your usual support channel or visit a Developer forum as suggested. If you think functionality is missing, you can also file an 
[Idea](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central). Thanks!
