### ISSUE TITLE
Doesn't delete without adding If-Match to header

### ISSUE THREAD

**Issue by anotherRedbeard** [MicrosoftDocs/dynamics365smb-devitpro-pb#1926]
I found this documentation to only get me part of the way to actually deleting a subscription.  To get it to work first you need '' around the subscription ID, then you need to add an If-Match header with the ETag value from the subscription you are trying to delete.  Once I added all that things worked as expected.  Please add this to the documentation or provide another way to delete a subscription.

Here is a link that provided step-by-step:
https://community.dynamics.com/business/f/dynamics-365-business-central-forum/314827/deleting-a-webhook-subscription?pifragment-96728=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e6969e7-29e7-368e-9bee-34ba8f2b76e4
* Version Independent ID: cdf31f85-7519-63db-0d60-4a8e3ec8b4e5
* Content: [DELETE subscriptions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_subscriptions_delete)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_subscriptions_delete.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_subscriptions_delete.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, this will be fixed with the next doc refresh.
