### ISSUE TITLE
Wording?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#1928]
" For a field to be included in the resulting dataset, a field must meet the conditions of the filter"

Shouldn't this read " For a **record** to be included in the resulting dataset, **its value in this field** must meet the conditions of the filter"? Or something to that effect?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fc851d-b806-cb8b-6b79-940f26689fea
* Version Independent ID: 36bca5d6-8691-17cd-8ef6-82d8c7ea9640
* Content: [Filtering in Query Objects - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-query-filters)
* Content Source: [dev-itpro/developer/devenv-query-filters.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-query-filters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The text has been fixed and an update will be published soon.
