### ISSUE TITLE
Task 9: Upgrade Data Description Missmatch

### ISSUE THREAD

**Issue by git-no** [MicrosoftDocs/dynamics365smb-devitpro-pb#1929]
In Task 9: Upgrade Data, section *single instance* (of https://docs.microsoft.com/de-ch/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v18#task-9-upgrade-data) it is described:

1. Run the data upgrade for the System Application, followed by the Base Application.
To run the data upgrade, use the `Start-NavDataUpgrade` cmdlet:

But the example does use a other command `Start-NAVAppDataUpgrade`.

So, it is unclear what the correct procedure and command it should be:

- a.) generally use `Start-NavDataUpgrade` or
- b.) `Start-NAVAppDataUpgrade` for each extension. 

Is `Start-NavDataUpgrade` obsolet?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: ab367758-d435-42cd-a1e1-d0b89c33ad25
* Version Independent ID: 4ea22d59-5d20-c0af-7bf8-e678c181b663
* Content: [Upgrading Version 15, 16, or 17 Base Application to Version 18 - Business Central](https://docs.microsoft.com/de-ch/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v18#task-9-upgrade-data)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, thanks for the feedback!

The text "To run the data upgrade, use the Start-NavDataUpgrade cmdlet" is incorrect as you point out. The cmdlet to use is Start-NavAppDataUpgrade cmdlet.

The Start-NavDataUpgrade cmdlet is not obsolete, just not used in this scenario. It's used in some upgrade scenarios for upgrading data to the new platform, for example, [here](https://docs.microsoft.com/de-ch/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v18#task-10-upgrade-data).

We've fixed the article, and the update will be published soon.

**Comment by git-no** [comment]
Thank you for your fast response time.
By the way, this mismatch description is also in previous BC versions of the upgrade documentation.

**Comment by jswymer** [comment]
Thanks again! We've also fixed the other instances. Hopefully, we've covered them all.
