### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1931]
At the beginning of the topic, it says that Report extensions can add columns to existing dataitems in the report dataset, but no example of how to do that is given. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fedbf190-9d38-889f-4158-0d06e88d8b87
* Version Independent ID: 369fde2e-6cfc-cdae-b2f3-dc2a95a6d7a9
* Content: [Report Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-ext-object)
* Content Source: [dev-itpro/developer/devenv-report-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-report-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by j2associates** [comment]
After playing around a bit, I was able to add some formatted date columns as below.

reportextension 50100 "Standard Purchase - Order ext." extends "Standard Purchase - Order"
{
    dataset
    {
        add("Purchase Header")
        {
            column(DocumentDateFormatted; Format("Document Date", 0, '<Day,2>/<Month,2>/<Year4>'))
            {
            }
            column(DueDateFormatted; Format("Due Date", 0, '<Day,2>/<Month,2>/<Year4>'))
            {
            }
        }
        add("Purchase Line")
        {
            column(PlannedReceiptDateFormatted; Format("Planned Receipt Date", 0, '<Day,2>/<Month,2>/<Year4>'))
            {
            }
            column(ExpectedReceiptDateFormatted; Format("Expected Receipt Date", 0, '<Day,2>/<Month,2>/<Year4>'))
            {
            }
            column(PromisedReceiptDateFormatted; Format("Promised Receipt Date", 0, '<Day,2>/<Month,2>/<Year4>'))
            {
            }
            column(RequestedReceiptDateFormatted; Format("Requested Receipt Date", 0, '<Day,2>/<Month,2>/<Year4>'))
            {
            }
        }
    }
}

As an aside, I have searched high and low and cannot find an example of formatting a date in a Word document when the date is bound to a Text Content Control from Custom Xml Mapping. You can format the date by reacting to Content Control events but SaaS will not accept anything other than a .docx as a Word layout document for reports.

1. Do I really have to write a Report Extension every time I want a decently formatted date?
2. The default date layout in the reports appears to be Format(Date, 0, 4) which is full Month Name Day, Year. This is absurd given how long some of the month names are and all of the wasted wrapping space will be needed to accommodate them.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The referenced page actually does illustrate the column syntax. 
reportextension 50110 MyExtension extends "Customer - Top 10 List"
{
    dataset
    {
        add(Integer)
        {
            // add existing field from base table to dataset
            column(fromBaseTable; Customer.GLN) { }
            // add field from table extending Customer
            column(fromBaseTableExt; Customer.MyField) { }
        }
    }

1) Yes, that seems to be the only option at this point - to create a new report ext object.
2) For this issue, I'd suggest that you go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
