### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#1933]
The See Also Report and DataItem triggers link goes to a generic triggers topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b988ac8-535e-8b57-30ef-80166e9bf791
* Version Independent ID: 54be3a11-ac98-1594-dee2-28241d0ca64e
* Content: [Report Triggers and Runtime Operations - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-triggers)
* Content Source: [dev-itpro/developer/devenv-report-triggers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-report-triggers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The target of the link doesn't exist. We've fixed the article to include proper links. The update will be published soon.
