### ISSUE TITLE
Typo in the docs for BC18 Upgrade

### ISSUE THREAD

**Issue by ekansh-hash** [MicrosoftDocs/dynamics365smb-devitpro-pb#1937]
It says extension name instead of extension version in Task 8 first example.

![image](https://user-images.githubusercontent.com/15551914/123547442-6ed16580-d77e-11eb-85e8-bd33d5d330b2.png)

Link to the documentation :- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v18

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a1fd93-5a4f-a65e-3c69-afd6d67e252f
* Version Independent ID: bb0ae4f3-55ba-39a2-ad07-13e40b683ec3
* Content: [Technical Upgrade from Version 17 to Version 18 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v18)
* Content Source: [dev-itpro/upgrade/upgrade-technical-upgrade-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-technical-upgrade-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by ekansh-hash** [comment]
Created a pull request to fix this issue https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/pull/1938.

**Comment by jswymer** [comment]
Thanks for the feedback and fix! Your pull request has been merged, and the changed will be published live soon.
