### ISSUE TITLE
Why no C/AL code example of how to check or set the enabled state

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#194]
For novice developers, an example here about how to check or set the property from C/AL code would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec4381af-0e83-07f4-b13b-8d196947f707
* Version Independent ID: ecb8da82-3e52-6e24-5429-e310efb100cc
* Content: [Enabled Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/enabled-property)
* Content Source: [dynamics-nav/Enabled-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Enabled-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your suggestion! For historical reasons, we do not have code examples showing how to set properties in C/AL code. But you can take the course "Development Environment Introduction in Microsoft Dynamics NAV 2017 and Dynamics 365 " in the Dynamics Learning Portal here: [https://mbspartner.microsoft.com/NAV/CourseOverview/1524](https://mbspartner.microsoft.com/NAV/CourseOverview/1524)

Alternatively, you can get started with AL development, which is the new developer experience for Dynamics 365 Business Central, the next generation of Dynamics NAV. For more information, see [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-programming-in-al](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-programming-in-al).
