### ISSUE TITLE
customer payment not working

### ISSUE THREAD

**Issue by Xeolex** [MicrosoftDocs/dynamics365smb-devitpro-pb#1942]
POST https://{businesscentralPrefix}/api/v1.0/companies({id})/customerPayment
Content-type: application/json

{
  "lineNumber": 10000,
  "customerId": "customerId-value",
  "customerNumber": "10400",
  "contactId": "contactId-value",
  "postingDate": "2015-12-31",
  "documentNumber": "1234",
  "externalDocumentNumber": "",
  "amount": -1500,
  "appliesToInvoiceId": "appliesToInvoiceId-value",
  "appliesToInvoiceNumber": "100000",
  "description": "",
  "comment": "",
}

{
    "error": {
        "code": "BadRequest_NotFound",
        "message": "No HTTP resource was found that matches the request URI 'https://{businesscentralPrefix}/api/v1.0/companies({id})/customerPayment'.  CorrelationId:  xxxxxxxxx."
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fb9b900-0946-1aca-4516-474786ddf87a
* Version Independent ID: 696da15a-b2af-37d8-fc18-7014aa5d3ee5
* Content: [(v1.0) Create customerPayments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v1.0/api/dynamics_create_customerpayment)
* Content Source: [dev-itpro/api-reference/v1.0/api/dynamics_create_customerpayment.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v1.0/api/dynamics_create_customerpayment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This might be a product bug. Please use your usual support channel to file a bug. Thanks.

**Comment by johnkmaina** [comment]
Hi...I am getting the same error when trying to do a post into Dynamics 365 BC13 in postman..
{
    "error": {
        "code": "BadRequest_NotFound",
        "message": "No HTTP resource was found that matches the request URI

My header looks as below:

http://127.0.0.1:7048/BC130/api/beta/companies(xxxx)/salesOrders(yyyy)/Microsoft.NAV.Post
