### ISSUE TITLE
Upgrade V18 - Publish version 18 system symbols extension failed

### ISSUE THREAD

**Issue by git-no** [MicrosoftDocs/dynamics365smb-devitpro-pb#1945]
## Issue
The documentation step **Publish version 18 system symbols extension** failed with error, symbols with this version do exists already from https://docs.microsoft.com/de-ch/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v18#task-7-publish-extensions

It seems the previous step of **converting the database integrates the symbols of the new version**. Is this so? This is not documented. If so the step of publishing the new system symbols is not required to do manually.

**Comment by jswymer** [comment]
Hello, Thanks for the valuable feedback! You're correct. Starting with v18, the database conversion will include the symbols. We've fixed the article and the update will be published soon.
