### ISSUE TITLE
Clearly PromotedIsBig is not doing what the topics describes

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1947]
As was already reported in #885 **PromotedIsBig** is clearly not doing what the topics describes. And even though the topic was updated (as mentioned in #885) the topic is actually nonsense.

First sentence in the topic: 
> Sets a value that indicates whether the promoted action is displayed on the ribbon with a large icon.

This is not the case at all.

Later with the example:
> However, because the PromotedIsBig property is true, it will appear before the Sales Quote action in the client.

This is indeed the case and to me this seems to only thing **PromotedIsBig** is doing. So, let that be described in the first sentence of the topic and nothing else. Indeed, you might want to explainn that this worked differently on the Windows client.

BTW: what is this line in the example code actually telling:
```
PromotedCategory = Category5;  // PromotedActionCategories = New Document
```

Shouldn't **PromotedCategory** be set to _New_?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0865ca2c-f735-3e44-16da-a78607034dda
* Version Independent ID: 46b76622-068b-c705-8e2b-346e7fda961e
* Content: [PromotedIsBig Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-promotedisbig-property)
* Content Source: [dev-itpro/developer/properties/devenv-promotedisbig-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-promotedisbig-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
We'll take a look.

**Comment by jswymer** [comment]
Thanks for the feedback. We've updated the article. The update will be published soon.
