### ISSUE TITLE
Promoted will only have effect when PromotedCategory is defined

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1949]
It seems to me that this topic fails one important detail: **Promoted** will only have effect when **PromotedCategory** is defined. So, I think this should be added the topic.
The topic should also have a link to https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-promotedcategory-property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4af5b1f-69a0-2e92-06d8-f8347d75bce3
* Version Independent ID: 65d8a700-3844-717d-f1fe-1daffd54065e
* Content: [Promoted (Action) Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-promoted-action-property)
* Content Source: [dev-itpro/developer/properties/devenv-promoted-action-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-promoted-action-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback. The article has been updated to your suggestions. The update will be published soon
