### ISSUE TITLE
Topic seems only to describe the on-premises context

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#195]
It seems to me that this topic only describes the on-premises context. It's all the old fashioned data upgrade. SO how about getting my data directly into D365BC Cloud? I do not see anything relating to that. It's confusing. Or is it just me misreading things?
Would appreciate a response on this and then also an update to the info here. Thanx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 477f688d-8f74-d141-eef2-bf570c56207b
* Version Independent ID: f56f56c5-07ca-32ff-6f5f-2d57e1cb54b2
* Content: [Upgrading to Microsoft Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-to-business-central)
* Content Source: [dev-itpro/upgrade/upgrading-to-business-central.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-to-business-central.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hi Luc,
You can import data to Business Central online using Excel, RapidStart, or one of the migration extensions. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/across-import-data-configuration-packages
The upgrade content that we have here is specifically for upgrading from Dynamics NAV to Business Central on-premises - different tools and different opportunities depending on whether you're going to online or on-premises deployment of Business Central.

**Comment by edupont04** [comment]
Hi Luc,
We added a section for how to migrate to Business Central online:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-to-business-central#moving-to--online
Does that help?

**Comment by srenders** [comment]
The documentation is indeed, imho, very basic and does not cover the complete scenario. Also, did anyone at Microsoft ever tried do to a data migration using RapidStart? It's very slow, sometimes just stops. Nice to demo, but imho not really suited for a data migration... It's more of a data export/modify/import tool.

Thanks for adding "Moving to Business Central online", but this documentation is a bit like spagetti-code. It jumps from here to there and there's no detailed explanations on how to really do this... Also, Microsoft is saying everywhere (fora, github, yammer, and other groups) that Intelligent Cloud is NOT a data migration tool, it was not designed to do that. Are you saying now that it the tool to use for data migration?

Also, data migration is not really about migrating master data, like customers, items, vendors... it's more about historical data (posted transactions, ledgers,...), from NAV to BC. And to migrate that kind of data, RapidStart, imho, is not suited.

I don't want to be negative, and I appreciate your hard work and the available documentation, it's better then having no documentation at all, and I know you are dependent on the dev-team and what's available in the product. I just think that you need to be very clear in the documentation. Either you explain step by step how to do it, or you simply say: We do not provide a tool for this scenario.

**Comment by edupont04** [comment]
Hi Steven,

Thank you for your feedback! Yes, we depend on the PMs and engineers to help us describe the processes and workflows in the docs. When it comes to data migration, we're still figuring out what works and doesn't work, but you are absolutely right that the Intelligent Cloud is not a data migration tool. 
Adding @JodiChristiansen for potential insights.

**Comment by Mr-Pingu** [comment]
I couldn't agree more with @srenders

Ever tried to import 27k items with about  100 columns filled columns, including vendors and vendor item catalog? 

Please try this simple scenario and you know why this tool left much to be desired.

**Comment by edupont04** [comment]
Hi everyone,
We've made some structural changes to the Upgrade section based on your feedback. I'm going to close this issue, not because I don't want to get your feedback but because our team recognizes your feedback and will dedicate time in the coming months to make the upgrade path to Business Central online much clearer and easier. This is feature work and less so docs work, which is why the continued discussion will take place under NDA in the development Yammer network.

**Comment by lvanvugt** [comment]
Clear, appreciated and thanx. ;-)

**Comment by srenders** [comment]
Super, very much appreciated, thanks Eva!
