### ISSUE TITLE
Example for creating taxArea gives error taxType is read-only

### ISSUE THREAD

**Issue by coder925** [MicrosoftDocs/dynamics365smb-devitpro-pb#1953]
I'm trying to create a **taxArea** according to the [example ](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_taxarea_create#example) provided in the documentation:

```
POST https://api.businesscentral.dynamics.com/v1.0/api/v2.0/companies({id})/taxAreas?$schemaversion=2.0
Content-type: application/json
```
```json
{
    "id": "405c8124-1c9d-4b3c-80ed-ffa732b2a2f0",
    "code": "ATLANTA, TEST",
    "displayName": "ATLANTA, TEST",
    "taxType": "Sales Tax",
    "lastModifiedDateTime": "2021-07-05T15:24:25.847Z"
}
```

Expected result:
- An example that works to create a new taxArea in a new sample tenant.
- I should be able to set the _taxType_.

Actual result:
- I receive _400 Bad Request_ error:
```json
{
    "error": {
        "code": "BadRequest",
        "message": "Control 'taxType' is read-only.  CorrelationId:  86be6b7c-8c80-4c27-8a27-3d8d203363f4."
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96f53379-93f3-fbd9-ccaf-965566c3f178
* Version Independent ID: 0bc1e577-18b3-79c4-177d-c53ec1210296
* Content: [Create taxAreas - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_taxarea_create)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_taxArea_create.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_taxArea_create.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The taxType is read-only and should be removed from the example, the same goes for id and lastModifiedDateTime. This will be fixed with the next doc refresh. Thanks.

**Comment by coder925** [comment]
@SusanneWindfeldPedersen , according to [Properties](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/resources/dynamics_taxarea#properties):
- `id` is **Non-editable**,
- `lastModifiedDateTime` is **Read-Only**.

Therefore, it should be fine to keep `id` in the sample as it is quite common that the client generates the identifier.

`taxType` it is not currently marked as **Read-Only** under [Properties](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/resources/dynamics_taxarea#properties). If taxType becomes Read-Only, there will be no way to create a new taxArea where you can specify its type being either `VAT` or `Sales Tax`. Is this really by-design?
