### ISSUE TITLE
How to import Encryption Key in SaaS Environment

### ISSUE THREAD

**Issue by MakerX101** [MicrosoftDocs/dynamics365smb-devitpro-pb#1954]
Why in SaaS environment don't have import button?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb5c13a7-b508-df5c-97dd-6690a22bceb2
* Version Independent ID: 60d9e0d1-b90a-0084-ef7c-ad675d4e3995
* Content: [How to: Export and Import Encryption Keys - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/how-to-export-and-import-encryption-keys)
* Content Source: [dev-itpro/upgrade/how-to-export-and-import-encryption-keys.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/how-to-export-and-import-encryption-keys.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only and not for product questions as such. Please elaborate on the issue if this pertains to documentation. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue
