### ISSUE TITLE
Missing info on select & filter options

### ISSUE THREAD

**Issue by wikap** [MicrosoftDocs/dynamics365smb-devitpro-pb#1955]
[Enter feedback here]
Can we select columns and make filter in accessing the endpoint? 

I ask since I would like to optimize Power BI dataloads - it would be easy to optimize our data loads, if you gave examples on how to do this in power bi, e.g. examples like

1) https://api.businesscentral.dynamics.com/v2.0/*environment*/api/v2.0/items?$select=id,number,displayName

AND IF POSSIBLE IN POWER BI (I CAN'T FIND INFORMATION ON THIS)

2) Select columns in Power Query by modifying the bold line:
let
    Source = Dynamics365BusinessCentral.ApiContents("*environment*", "*regnskab*", "v2.0"),
    items_table = **Source{[Name="items",Signature="table"]}[Data],**
    #"Removed Other Columns" = Table.SelectColumns(items_table,{"number", "displayName", "type", "itemCategoryCode", "blocked", "inventory", "unitPrice", "unitCost", "baseUnitOfMeasureCode", "lastModifiedDateTime"}),
    #"Extracted Date" = Table.TransformColumns(#"Removed Other Columns",{{"lastModifiedDateTime", DateTime.Date, type date}})
in
    #"Extracted Date"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a5495f-193a-9ad6-490d-8bb5d0b2d709
* Version Independent ID: 95da6841-b4a7-932c-de90-4b3b93bf8eea
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/endpoints-apis-for-dynamics)
* Content Source: [dev-itpro/api-reference/v2.0/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/endpoints-apis-for-dynamics.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. For product-related questions please contact your usual support channel - this repo is meant for documentation bugs and issues. Thanks.

**Comment by wikap** [comment]
Thanks – so ”feedback” buttom is not ment for feedback 😊


/Henrik

WIKAP
+45 23 34 59 34 ***@***.******@***.***>

Fra: Susanne Windfeld Pedersen ***@***.***>
Sendt: 8. juli 2021 10:32
Til: MicrosoftDocs/dynamics365smb-devitpro-pb ***@***.***>
Cc: Henrik Kappel ***@***.***>; Author ***@***.***>
Emne: Re: [MicrosoftDocs/dynamics365smb-devitpro-pb] Missing info on select & filter options (#1955)


Hello, thanks for your question. For product-related questions please contact your usual support channel - this repo is meant for documentation bugs and issues. Thanks.
