### ISSUE TITLE
Detail what the order should be

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1956]
In vs code the order is detailed, however on this page it isn't.
It would be the obvious choice to do so on the page.

![image](https://user-images.githubusercontent.com/16603906/124664338-87b9d500-de68-11eb-80b0-4c8407d740e8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b5ddc84-66fc-dac7-2473-efbd8abc4ba7
* Version Independent ID: d30b3aa4-da57-3c42-d22b-035d45cdbc71
* Content: [CodeCop Rule AA0021 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0021-variabledeclarationsshouldbeorderedbytype)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0021-variabledeclarationsshouldbeorderedbytype.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/analyzers/codecop-aa0021-variabledeclarationsshouldbeorderedbytype.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - the topic should reflect the same content, so this is a bug which will be fixed with the next doc refresh. Thanks.
