### ISSUE TITLE
Sample is missing a begin end causing it to always EXIT(TRUE);

### ISSUE THREAD

**Issue by SebastiaanLubbers** [MicrosoftDocs/dynamics365smb-devitpro-pb#1958]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31c576e0-1082-8db4-8968-d9ac1b28f20b
* Version Independent ID: 32683ad5-b43c-7792-bc7c-6329de77b596
* Content: [TryFunction Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-tryfunction-attribute)
* Content Source: [dev-itpro/developer/attributes/devenv-tryfunction-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/attributes/devenv-tryfunction-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The issue will be fixed with the next doc refresh.
