### ISSUE TITLE
A query is a new object in Dynamics 365 Business Central  ...

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#196]
Badly copied or left unchanged from previous version. Query object has been there since NAV 2013, so not so new anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e3cd48-4855-ecb8-8e1e-a2860897bbc8
* Version Independent ID: 15658872-411e-87b2-5cb9-c8c25df14ddf
* Content: [Query Objects and Performance - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/optimize-sql-query-objects-and-performance)
* Content Source: [dev-itpro/administration/optimize-sql-query-objects-and-performance.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/optimize-sql-query-objects-and-performance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi! Thank you for your feedback! You are right and the topic has been updated. The change will be noticeable with one of the next doc refreshes.
