### ISSUE TITLE
ForceSync can be used if there is more than one tenant in the database

### ISSUE THREAD

**Issue by atoader** [MicrosoftDocs/dynamics365smb-devitpro-pb#1965]
ForceSync: This mode is also intended for use during development, but unlike the Development and Add modes, it supports destructive schema changes (like removing fields, renaming them, changing their datatypes, and more). This mode is useful in development because it enables you to make these kinds of changes without losing data. Because destructive changes are not backwards compatible, this mode should not be used in production. To use this mode, the App must first be uninstalled from the tenant, and there can be only one tenant in the database.

Should be changed to 

ForceSync: This mode is also intended for use during development, but unlike the Development and Add modes, it supports destructive schema changes (like removing fields, renaming them, changing their datatypes, and more). This mode is useful in development because it enables you to make these kinds of changes without losing data. Because destructive changes are not backwards compatible, this mode should not be used in production. To use this mode, the App must first be uninstalled from the tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0487be-7680-3da5-d47b-e39fd04f449e
* Version Independent ID: 5fdebecd-6373-6472-77bb-c9eb68dd10a2
* Content: [Sync-NAVApp (Microsoft.Dynamics.Nav.Apps.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/sync-navapp?view=businesscentral-ps-18&source=docs)
* Content Source: [businesscentral-ps-18/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-18/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md)
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks! The article has been fixed and the update will be published soon.
