### ISSUE TITLE
Codeunit 1 is no longer

### ISSUE THREAD

**Issue by SorenKlemmensen** [MicrosoftDocs/dynamics365smb-devitpro-pb#197]
Just noticed Codeunit 1 is mentioned but it doesn't exist any more :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 256aabb4-8d5d-cc06-6c1f-5558c668491b
* Version Independent ID: 51d1427c-130d-b5c0-3d04-89c01caa89f8
* Content: [Event Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-event-types#feedback)
* Content Source: [dev-itpro/developer/devenv-event-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-event-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi and thank you for your feedback! You are right. The topic has been updated and the change will be noticeable with one of the next doc refreshes.
