### ISSUE TITLE
The properties 'Asignable' and 'Caption' cannot be used on a permission set extension

### ISSUE THREAD

**Issue by MiljanSinghammer** [MicrosoftDocs/dynamics365smb-devitpro-pb#1970]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41dc4127-f2f5-ee4c-a6dd-60ff7acda509
* Version Independent ID: 54f21c03-228c-a4d1-616d-ce78a1652cde
* Content: [Permission Set Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-permissionset-ext-object)
* Content Source: [dev-itpro/developer/devenv-permissionset-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-permissionset-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks your your feedback, it will be fixed with the next refresh.
