### ISSUE TITLE
Uses an undefined term of 'module '

### ISSUE THREAD

**Issue by TrippyZ** [MicrosoftDocs/dynamics365smb-devitpro-pb#1971]
I think this should contain an explanation of what the term 'module' is specifically referring to.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85cca83d-dc32-fdac-683d-9d8ecb05a130
* Version Independent ID: df10b0db-543f-db79-ba03-15e95b3a9930
* Content: [Access Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-access-property)
* Content Source: [dev-itpro/developer/properties/devenv-access-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-access-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback!

'Module' does refer to 'extension'. We've changed the article, and an update will be published soon.
