### ISSUE TITLE
Seems Assignable and Caption is not allowed on permissionsetextensions (maybe only on permissionsets?)

### ISSUE THREAD

**Issue by glynge** [MicrosoftDocs/dynamics365smb-devitpro-pb#1973]
Seems:
    Assignable = true;
    Caption = 'Extended Sales Doc'
...is not allowed on permissionsetextension (at least my Visual Studio Claims it is not allowed :-) ).
I probably only works on permissionssets?

VSC says "The property 'Assignable' cannot be used in this context AL(AL0124)"
and "The property 'Caption' cannot be used in this context AL(AL0124)"

Best regards
Gert Lynge
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41dc4127-f2f5-ee4c-a6dd-60ff7acda509
* Version Independent ID: 54f21c03-228c-a4d1-616d-ce78a1652cde
* Content: [Permission Set Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-permissionset-ext-object)
* Content Source: [dev-itpro/developer/devenv-permissionset-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-permissionset-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks your your feedback! These properties are indeed only allowed on Permissionsets. It will be fixed with the next refresh.
