### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by Easystep2** [MicrosoftDocs/dynamics365smb-devitpro-pb#1978]
You are missing some quotes in the example when getting the CustomerNumber data it should be GetData('CustomerNumber')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87fc7637-4e16-c566-a99a-0f2e01aa22a6
* Version Independent ID: cb3cd413-3471-8411-98c5-5d25b22ba777
* Content: [Notifications - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-notifications-developing)
* Content Source: [dev-itpro/developer/devenv-notifications-developing.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-notifications-developing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the article. The update will be published soon.
