### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1979]
> For more information about formatting AL data types, see [Formatting Values, Dates, and Time.](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-format-property) For more information about evaluating variables, see [EVALUATE Method](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-evaluate-method). For more information about using temporary tables, see [Temporary Property (XMLports)](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-usetemporary-xmlports-property).

Hi, 
link 1 forwards to the wrong article. Correct would be: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-property
Link 2 is correct.
Link 3 is not working at all. And there is no such property for XMLports. Did you mean [UseTemporary](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-usetemporary-xmlport-property)?

BTW, at the very beginning of the article ... ;-)

> Sets the data that is being imported or exported as XML data types or as the standard **C/SIDE** data types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 565fcdce-c626-6d3b-4516-6478dc4c045e
* Version Independent ID: 09fe80a3-1a95-c316-e74d-d561fa777759
* Content: [FormatEvaluate Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-formatevaluate-property)
* Content Source: [dev-itpro/developer/properties/devenv-formatevaluate-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-formatevaluate-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The changes have been made as suggested. The updated article will be published soon.
