### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by szepa** [MicrosoftDocs/dynamics365smb-devitpro-pb#198]
Recently we have set Business Central on Premise with AccessControlService credential type. 
Windows Client works as expected but Web Client fails to open. Web Client was running authentication "infinite loop".
With Microsoft we have identified problems around settings for Sign-on URL (App URL), App ID URI, Reply URL, and WS-federation login endpoint.
What made difference :
a.	settings should be in lower case
b.	we have added character "/" on the end of the application 
-	in Azure portal for AAD, App IU URI (e.g. https://cronusinternationltd.onmicrosoft.com/financials/  instead https://CRONUSInternationLtd.onmicrosoft.com/Financials)
-	in Azure portal for AAD, home page URL (e.g. https://cronusinternationltd.onmicrosoft.com/bc130/ instead https://CRONUSInternationLtd.onmicrosoft.com/BC130)
-	in Azure portal for AAD, single entry for “return url” with SignIn (e.g. https://cronusinternationltd.onmicrosoft.com/bc130/SignIn) instead https://dynamicsnavwinclient/
-	in CustomSettings.config for the NST: 
o	for AppIdUri : https://cronusinternationltd.onmicrosoft.com/bc130/
o	for WSFederationLoginEndpoint :
https://login.windows.net/CRONUSInternationLtd.onmicrosoft.com/wsfed?wa=wsignin1.0%26wtrealm=https://cronusinternationltd.onmicrosoft.com/financials/%26wreply=https://cronusinternationltd.onmicrosoft.com/bc130/SignIn
instead 
https://login.windows.net/CRONUSInternationLtd.onmicrosoft.com/wsfed?wa=wsignin1.0%26wtrealm=https://CRONUSInternationLtd.onmicrosoft.com/Financials%26wreply=https://CRONUSInternationLtd.onmicrosoft.com/BC130/SignIn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff0aa19-50aa-c461-cd97-4be8fbe4e393
* Version Independent ID: f72d929a-7fea-246f-8b2e-4f3b14c5c92d
* Content: [User Authentication with Azure AD for Single Sign-on - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory)
* Content Source: [dev-itpro/administration/authenticating-users-with-azure-active-directory.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/authenticating-users-with-azure-active-directory.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The content has been fixed and the update will be published soon.
