### ISSUE TITLE
There is a mistake in the EXAMPLE 1. There should be no empty space before ApplicationDatabaseServer 

### ISSUE THREAD

**Issue by nvtopalov** [MicrosoftDocs/dynamics365smb-devitpro-pb#1980]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77809d6f-98a5-3837-a891-59ee616ef184
* Version Independent ID: 3aee6416-38e0-490b-b06c-5f8403fcd5e5
* Content: [Import-NAVEncryptionKey (Microsoft.Dynamics.Nav.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/import-navencryptionkey?view=businesscentral-ps-18)
* Content Source: [businesscentral-ps-18/Microsoft.Dynamics.Nav.Management/Import-NAVEncryptionKey.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-18/Microsoft.Dynamics.Nav.Management/Import-NAVEncryptionKey.md)
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and the update will be published soon.
