### ISSUE TITLE
Broken link - DataItemTableFilter Property

### ISSUE THREAD

**Issue by TrippyZ** [MicrosoftDocs/dynamics365smb-devitpro-pb#1981]
In this paragraph;

In addition to the SetRange method, you can apply filters to a query using the SetFilter method and the DataItemTableFilter Property and ColumnFilter Property.

This text;
DataItemTableFilter Property

has this url;
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/query/devenv-dataitemtablefilter-property

which is 404 not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5af00b3b-1f1a-714a-ed56-82eea2cb46a1
* Version Independent ID: 82b14314-8e52-b863-ccbd-a1f27932db05
* Content: [Query.SetRange Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/query/queryinstance-setrange-method)
* Content Source: [dev-itpro/developer/methods-auto/query/queryinstance-setrange-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/query/queryinstance-setrange-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the link, and the update will be published soon.
