### ISSUE TITLE
filed in error

### ISSUE THREAD

**Issue by TrippyZ** [MicrosoftDocs/dynamics365smb-devitpro-pb#1982]
The text contains the word 'filed' when it should be the word 'field'
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fc851d-b806-cb8b-6b79-940f26689fea
* Version Independent ID: 36bca5d6-8691-17cd-8ef6-82d8c7ea9640
* Content: [Filtering in Query Objects - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-query-filters)
* Content Source: [dev-itpro/developer/devenv-query-filters.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-query-filters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and the update will be published soon.
