### ISSUE TITLE
Dynamics 365 Business Central OAS downloading missing

### ISSUE THREAD

**Issue by idubs** [MicrosoftDocs/dynamics365smb-devitpro-pb#1983]
> Download OAS for Business Central as shown above.

There's no download for the yaml file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1baf2582-6d3b-68da-47b9-f42f81ad0f9c
* Version Independent ID: 25a0b3d1-0de8-bce1-083c-974f8921acfb
* Content: [OpenAPI Specification - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/dynamics-open-api)
* Content Source: [dev-itpro/api-reference/v2.0/dynamics-open-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/dynamics-open-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. At this point in time there is no available .yaml file for version 2.0. We have updated the topic to use version 1.0 and inserted a note for awareness for now. The topic is updated with these changes with the next doc refresh. Thanks.
