### ISSUE TITLE
Endpoint misleading: currently cashFlowStatement when it should be cashFlowStatements

### ISSUE THREAD

**Issue by AbdulCodat** [MicrosoftDocs/dynamics365smb-devitpro-pb#1984]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 722e1c4a-8c27-dae0-f0fe-166591b4e7d2
* Version Independent ID: 1aedc433-2132-b2c8-f35d-610661e56538
* Content: [Get cashFlowStatement - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_cashflowstatement_get)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_cashflowstatement_get.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_cashflowstatement_get.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and the update will be published soon.
