### ISSUE TITLE
Out of date references?

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1985]
The [prerequisites](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action#prerequisites) list NAV2017.  The code is C/AL not AL.

Will this be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b3196a-00cc-3382-f040-ef813b4029e4
* Version Independent ID: cbd09737-7acd-2534-d9aa-96a8b34c8c4f
* Content: [Walkthrough: Creating and Interacting With an OData V4 Bound Action - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action)
* Content Source: [dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The topic was ported from the NAV docs, but we decided to deprecate it. A similar topic for AL is found here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-bound-action. Thanks.
