### ISSUE TITLE
Error in example code

### ISSUE THREAD

**Issue by PeterConijn** [MicrosoftDocs/dynamics365smb-devitpro-pb#1987]
In the example code:

[ModalPageHandler]
procedure ModalPageHandler(var Page: Page, var Response: Action)

The arguments are separated by comma. This should be a semicolon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4cdd085-91b8-6763-9b14-d2316e089e97
* Version Independent ID: d7425067-392d-6dca-934b-c0fbe857db96
* Content: [ModalPageHandler Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-modalpagehandler-attribute)
* Content Source: [dev-itpro/developer/attributes/devenv-modalpagehandler-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/attributes/devenv-modalpagehandler-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This will be fixed with the next refresh.
