### ISSUE TITLE
Procedure Name in AddAction

### ISSUE THREAD

**Issue by rkirsten** [MicrosoftDocs/dynamics365smb-devitpro-pb#199]
In the example you've given, you missed to add some text to the "OpenCustomer" text var, which leads to a runtime error. 
Changing the addaction-call to CreditBalanceNotification.ADDACTION('Text004', CODEUNIT::"Action Handler", 'OpenCustomer'); or adding OpenCustomer := 'OpenCustomer' resolves the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87fc7637-4e16-c566-a99a-0f2e01aa22a6
* Version Independent ID: cb3cd413-3471-8411-98c5-5d25b22ba777
* Content: [Notifications - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-notifications-developing)
* Content Source: [dev-itpro/developer/devenv-notifications-developing.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-notifications-developing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by rkirsten** [comment]
There is also a typo in the second part: You wrote Custec instead of CustRec...

**Comment by jswymer** [comment]
Thanks for the feedback. The article has been fixed and an update will be published soon.
