### ISSUE TITLE
The working with Webhooks link 404s

### ISSUE THREAD

**Issue by ironinthesoul** [MicrosoftDocs/dynamics365smb-devitpro-pb#1991]
Clicking on "Working with Webhooks - Dynamics NAV" goes to a dead page: 

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/dynamics_subscriptions

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8eb2c50-c0d1-7e64-0d00-8ad72f8a968a
* Version Independent ID: f0fd2b39-733e-c38d-ad5f-02f6538d06e6
* Content: [API(V2.0) for Dynamics 365 Business Central   - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/)
* Content Source: [dev-itpro/api-reference/v2.0/index.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The page in question does not contain that link Working with Webhooks, but we have fixed an issue that might be what you meant. This will be pushed with the next refresh. If the issue still pertains, feel free to open a new GitHub issue. Thanks.
