### ISSUE TITLE
Wrong file naming example

### ISSUE THREAD

**Issue by DSaladinCH** [MicrosoftDocs/dynamics365smb-devitpro-pb#1992]
In the section file naming you got some examples with different object types.
But in the section for page extension, you only show an example of an action instead of the page extension name.
Is this intended?
[https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#page-extension](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#page-extension)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This is confusing, and the header meant to say Action - there are plenty of examples of the object naming, which becomes quite repetitive, so we've fixed the header and moved the sections a bit to hopefully make it clearer. Live with the next doc refresh. Thanks.
