### ISSUE TITLE
Update apps is now possible via Admin Center

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1993]
Hi,

Currently instructions on this page for Saas are to uninstall app and reinstall from AppSource, but there is also a more convinient way:
In Admin Center (https://businesscentral.dynamics.com/TenantId/admin) users with appropriate rights (like delegated admins) can select Environment and from there Apps and just click on Install update.

Please add at least link to Admin Center instructions:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-manage-apps

Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac07d83-45c1-324d-d292-b79e04939cdc
* Version Independent ID: 76985863-66fa-1583-7632-27949149d90c
* Content: [Upgrading AppSource Apps in Production - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrade-appsource-app-in-prod)
* Content Source: [dev-itpro/developer/devenv-upgrade-appsource-app-in-prod.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-upgrade-appsource-app-in-prod.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **freddyk**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with a link with the next refresh. Thanks.
