### ISSUE TITLE
Code samples Wrongly coloured

### ISSUE THREAD

**Issue by RDLT-FAA** [MicrosoftDocs/dynamics365smb-devitpro-pb#1996]
[Enter feedback here]
Please when you can adjust the colors for some lines of the code examples.

some comments and lines of code are wrongly coloured and make the code sample look like a little bit messy.

Example1:
// Modifying the caption of the field 'Address 2' -->This line should be green but it is not.
        modify("Address 2") -->
Example2:
Error('Feet too small');--> 'Feet too small' should be dark red.

Thank you a lot for your documentation and have a nice day!.

Kind regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdda7e30-30d9-ac83-abf7-267a7f634c6d
* Version Independent ID: 5bf5ce87-f59a-d2ae-10b3-05eda02406b5
* Content: [Page Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)
* Content Source: [dev-itpro/developer/devenv-page-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-page-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the article, so that the color-coding is correct. The update will be published soon.
