### ISSUE TITLE
Link to SubType property is not working

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1999]
Link to SubType property is not working.

It is now:

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-subtype-codeunit-property

But should be:

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-subtype-codeunit-property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aad761f-ad97-7f15-fd0b-81f5716d2d90
* Version Independent ID: d0f0fb7c-6a1f-efef-e43c-955bb10b1404
* Content: [Upgrading Extensions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions)
* Content Source: [dev-itpro/developer/devenv-upgrading-extensions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-upgrading-extensions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The link has been fixed and the update will be published soon.
