### ISSUE TITLE
PageExt <-> Pag

### ISSUE THREAD

**Issue by waldo1001** [MicrosoftDocs/dynamics365smb-devitpro-pb#2]
The example on a Page Extension doesn't really allign with the "PageExt" abbreviation?

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: fd0b094e-a368-aa20-e643-349515abf00e
* Version Independent ID: d3d587c3-0380-5b64-0c1a-274e393a4e58
* Content: [Best Practices for AL code - Dynamics NAV](https://docs.microsoft.com/da-dk/dynamics-nav/compliance/apptest-bestpracticesforalcode)
* Content Source: [dynamics-nav/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/compliance/apptest-bestpracticesforalcode.md)
* Service: **unspecified**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by edupont04** [comment]
Thanks for reporting this! The team will process this issue after the holidays.

**Comment by TKapitan** [comment]
I disagree - It will be too confusing to have more than 10 objects named by Name instead of by ID. The order of the objects will be different than it is in current development and it will be too confusing for programmers too.

**Comment by waldo1001** [comment]
What do you mean?
You don't agree with the current? You don't agree with the PageExt - or my comment (which is merely a comment that the documentation is not consequent)?

**Comment by MarcHansenMicrosoft** [comment]
I think @TKapitan refers to issue #1.

**Comment by waldo1001** [comment]
oh.. ok.  That would make sense ;-)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The topic has been updated and will be pushed live with the next refresh.
