### ISSUE TITLE
What steps a and b?

### ISSUE THREAD

**Issue by JulianTillmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#20]
it says two times "Upgrade to the latest Microsoft Dynamics NAV 2017 cumulative update (CU) by following steps a and b above."

But there are no steps a and b anywhere in this document and it's not clear what to do with a higher CU for NAV2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd117bf-692a-a466-873f-2000c4d78852
* Version Independent ID: 280c6e15-ff52-6815-f34a-748b9cadf5a2
* Content: [Upgrade Microsoft Dynamics NAV - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/upgrading-to-microsoft-dynamics-nav-2017)
* Content Source: [dynamics-nav/Upgrading-to-Microsoft-Dynamics-NAV-2017.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Upgrading-to-Microsoft-Dynamics-NAV-2017.md)
* Service: **unspecified**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for your feedback. This will be fixed in the next refresh of the documentation.
