### ISSUE TITLE
Create Sales Order and Lines in a single call

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#200]
How can we create SalesOrder and Lines in a single call without knowing the GUID for the item?

For example this works:

POST http://localhost:7048/DynamicsNAV110/api/beta/companies(9b562fdb-5071-4aef-8bf6-d7aa6fd0b474)/salesOrders

```
{
    "customerNumber": "10780",
    "salesOrderLines": [
	{
		"itemId": "fb326b66-26be-4e38-a53f-301da19f445b",
		"quantity": 1
                    
	},
	{
		"itemId": "ffe070fb-6bcf-4721-8b7a-e399af66ebe9",
		"quantity": 1
	}
    ]
}
```

But when using the actual Item No., it returns invalid request body

```
{
    "customerNumber": "10780",
    "salesOrderLines": [
	{
		"itemId": "1001",
		"quantity": 1
                    
	},
	{
		"itemId": "1000",
		"quantity": 1
	}
    ]
}

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab8727c9-7b8e-2c83-680f-7f5c8a4ec22c
* Version Independent ID: dc43f5e7-d5d9-48e7-b74d-460b5a70150e
* Content: [Create salesOrderLines - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_create_salesorderline)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_create_salesorderline.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_create_salesorderline.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
hi averied,
You need to use the itemId (Guid) and not the number. itemId is immutable.

Can you elaborate why you want to use the number (which is not immutable)?

**Comment by SusanneWindfeldPedersen** [comment]
Have to close this issue, no reply.
