### ISSUE TITLE
Editable Parameter does not work

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#2001]
Hi,

I've been fighting this in v17.1 and it does not appear that passing a parameter to the editable function.
I've tried it in many locations, when creating the page, on init, on openpage, onaftergetrecord, even onaftergetcurrrecord.

Thanks
Yann

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa18ed00-c64a-b31f-6824-fce50ab40319
* Version Independent ID: 862ad8b6-574b-bc16-8633-549b9f8747e6
* Content: [Page.Editable Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-editable-method)
* Content Source: [dev-itpro/developer/methods-auto/page/page-editable-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/page/page-editable-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This could be a product bug. Please contact your usual support channel to file a bug. Thanks.
