### ISSUE TITLE
C/AL Guidelines Note links to a deadlink

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#2002]
[Enter feedback here]
The first Note section, linking to a C/AL Coding Guidelines post, which in turn links to a PDF file... the PDF file no longer exists at that link, so the Pre-C/AL Coding Guidelines file mentioned should be located from the NavTeam and reuploaded, then linked to.

It still provides great value, so please fix to a new PDF file link, rather than remove the note.  Worst case scenario, I still have a C/AL Coding Guidelines doc from Navision in 2002, so if you truly can't find a copy internally, I'll send it over.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by edupont04** [comment]
Hello Jeremy,
Thank you for reaching out to us about this issue! It looks like the PDF got lost when we migrated the original blog post to the current platform. I'll try to figure out how to bring it back. However, I suspect that the CodeCop rules are a more sustainable approach to learn best practices for good AL code (apart from learning from the community, obviously)....

**Comment by JeremyVyska** [comment]
New Suggestion:  Update the note at the top to link to ALGuidelines.dev, as it is an official [Microsoft repo](https://github.com/microsoft/alguidelines) of community "design patterns" and "best practices".

That is more relevant than the old PDF would be and covers many of the same elements.

**Comment by edupont04** [comment]
Hej Jeremy,

I appear to have dropped this one, my apologies for the delay! And yes, AL coding design patterns are being rebooted. I'll add a link to the ALGuidelines.dev content. This will be fixed in the next doc update.
