### ISSUE TITLE
Record.Get() documentation needs to mention special overload for Get(RecordId)

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2005]
from https://github.com/Microsoft/AL/issues/4622

> One scenario that needs to be excluded is the Record.GET(Some_Var_Of_Type_RecordId)

This also needs to be documented... It is not at all: [Record.Get([Any,...]) Method
](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-get-method)

The closest hint is this:

> You cannot use the Get method to retrieve a record in a table by its primary key value if the primary key field in the table has the data type RecordID. In this case, you can retrieve the record by using the SetRange Method.

But it doesn't explain why one can't do that, namely because `Get(RecordId)` is overloaded to mean 'Get the record whose PK field(s) combine to form this RecordId', not the expected 'Get the record whose PK is a single field consisting of this RecordId'.

Please update to mention that `Record.Get(RecordId)` is a special case and how it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7714b8e-5cbb-8bb0-16ac-d4ef027b8d15
* Version Independent ID: 40a722d0-0566-72b6-cf2e-cb931a3dad83
* Content: [Record.Get(\[Any,...\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-get-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-get-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-get-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, the article will be updated to include this information with the next refresh.

**Comment by dnpb** [comment]
I'm afraid the added wording is not that clear or helpful as to why one cannot use `Get(RecordId)` if the PK is a RecordId.

It also doesn't mention at all that said overload exists so that one **can** do `SomeRecord.Get(SomeRecordId)` if `SomeRecordId` is a PK for `SomeRecord`.
