### ISSUE TITLE
Record.Get() documentation wrongly says it ignores prior calls to SetAutoCalcFields() for FlowFields

### ISSUE THREAD

**Issue by db-bc** [MicrosoftDocs/dynamics365smb-devitpro-pb#2006]
[The page](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-get-method) states this:

> This method ignores any call to the SetAutoCalcFields Method. Therefore, a Get call on a record after a SetAutoCalcFields call does not automatically calculate FlowFields in the record.

After nearly having a heart attack thinking about how much code I've written that relies on `Get()` honouring `SetAutoCalcFields()` and which would be broken by this... I decided to actually test it.

Code:
```al
pageextension 50100 Foo extends "Customer List"
{
    trigger OnOpenPage()
    var
        Customer, Customer2 : Record Customer;
    begin
        Customer.SetFilter(Balance, '<>0');
        Customer.FindFirst();

        Customer2.SetAutoCalcFields(Balance);
        Customer2.Get(Customer."No.");
        Message('%1', Customer2.Balance);
    end;
}
```

Result: `Customer2` has the correct non-zero `Balance`, indicating that said FlowField *was* automatically calculated:
![image](https://user-images.githubusercontent.com/63455896/130482924-600705f1-cd43-4ebc-ba58-9985ab678994.png)

Also, plenty reports now do `CompanyInfo.SetAutoCalcFields(Picture); CompanyInfo.Get()` which 'self-documents' that this is expected to work. And it'd be useless if it didn't work!

Meaning: `Get()` **does** honour `SetAutoCalcFields()`, and this documentation needs fixed (to not imply the sky is falling!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7714b8e-5cbb-8bb0-16ac-d4ef027b8d15
* Version Independent ID: 40a722d0-0566-72b6-cf2e-cb931a3dad83
* Content: [Record.Get(\[Any,...\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-get-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-get-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-get-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by db-bc** [comment]
Also, if that _were_ true, then [SetAutoCalcFields documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setautocalcfields-method) would need loudly updated to mention it - but again, it's **not** true.

**Comment by db-bc** [comment]
This might be a relic from a bygone age where the statement was true. This old NAV page has the same warning and was modified in 2016: https://docs.microsoft.com/en-us/dynamics-nav/get-function--record-

**Comment by SusanneWindfeldPedersen** [comment]
Thanks very much for your elaborate feedback. This is indeed an "old" leftover from NAV. The topic will be fixed with the next doc refresh.

**Comment by db-bc** [comment]
Great, thank you @SusanneWindfeldPedersen !
