### ISSUE TITLE
Create a company - Incorrect API URL

### ISSUE THREAD

**Issue by snapehun** [MicrosoftDocs/dynamics365smb-devitpro-pb#2007]
The POST URL "https://api.businesscentral.dynamics.com/v2.0/{environment name}/api/microsoft/automation/2.0/companies({companyId})/automationCompanies" is incorrect. The stated version is automation/2.0/ thus giving error 404.

The correct version is automation/v2.0/.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036fbaa0-3f6b-e4f7-cd1e-c35b37cdee6e
* Version Independent ID: 9efb41bd-bad8-597f-08e8-2b3c7e05f8e9
* Content: [Introduction to automation APIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/itpro-introduction-to-automation-apis)
* Content Source: [dev-itpro/administration/itpro-introduction-to-automation-apis.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/itpro-introduction-to-automation-apis.md)
* Service: **dynamics365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be fixed with the next doc refresh.
