### ISSUE TITLE
Where is it?

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/dynamics365smb-devitpro-pb#201]
How do you get to the Intelligent Cloud Management page in the Business Central cloud tenant? There's no link anywhere, even after setup. Searching for it at Dynamics home returns nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4c4a098-0844-b136-ed33-51dc861c5554
* Version Independent ID: 9f498ec2-a39b-ee66-e087-b1075dd19eba
* Content: [Administration of the Intelligent Edge for on-premises - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/manage-intelligent-edge)
* Content Source: [dev-itpro/administration/manage-intelligent-edge.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/manage-intelligent-edge.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you should be able to run the assisted setup, for more information see [this](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/about-intelligent-edge). thanks.

**Comment by edupont04** [comment]
Closing the issue.

**Comment by pyoungberg** [comment]
Opened a support case and they were able to resolve this by running some scripts on the backend. Now the Intelligent Cloud Management page shows in search results with the lightbulb. You can also get here by clicking the 'Replication Status' tile from the Business Central home page.
