### ISSUE TITLE
What do the options of ctrl+f5 and f5 reference?

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2012]
Hi,

This is specifically concerning steps five and six:

> It is important to make sure to publish your app by pressing Ctrl+F5, alternatively Alt+Ctrl+F5 for RAD publishing. Your app will not be published if you only press F5.
> After publishing the app, press F5 to start a debugging session. 

Ctrl+F5 is publish without debug.
F5 is publish and debug.

So I publish, and then publish again? I'm not sure if maybe these options have changed or these shortcuts were remapped. But none of the suggested options appear to work for me. If I start a new web client session (instead of using the one opened for me), the breakpoint is not caught.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0b843a-3810-414d-1374-443829ce8dad
* Version Independent ID: 75b366e0-5b6d-a0b0-79bf-aa68115232e9
* Content: [Attach and Debug Next - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-attach-debug-next)
* Content Source: [dev-itpro/developer/devenv-attach-debug-next.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-attach-debug-next.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you need an attach configuration to attach debug, the attach configuration will not publish, only a launch configuration publishes. Hence the "repeated" step. Hope this helps. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue for now. Thanks.
