### ISSUE TITLE
SkipFieldsNotMatchingType

### ISSUE THREAD

**Issue by AJasp** [MicrosoftDocs/dynamics365smb-devitpro-pb#2016]
Hi,
please add the default value for SkipFieldsNotMatchingType parmeter. 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1095e80a-902d-eaa7-a750-f3fa08d72a19
* Version Independent ID: 1d1b4943-8a1d-e478-d14b-ddd52b935c07
* Content: [Record.TransferFields(var Record, Boolean, Boolean) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-boolean-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-boolean-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-boolean-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, I am pretty sure that the default is true for this parameter. Why it is not picked up by our auto-generation, I am not sure. It is a tool bug, I will file it and put it on our backlog. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
This is a bug on our backlog. We will prioritize it accordingly. Closing this doc issue. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, looking into this a bit more. The SkipFieldsNotMatchingType is not optional, so there isn't a default value, which means that the docs are correct as they are. Thanks.
