### ISSUE TITLE
specify the correct target Language code

### ISSUE THREAD

**Issue by KristofKlein** [MicrosoftDocs/dynamics365smb-devitpro-pb#2019]
Hi,

I think the documentation should mention the correct format of the language code. Why? Well, we had a developer that place a 'de' only in the target language. And the funny thing here was: it worked for some of the translations! Like captions worked fine in german with this. but all translated labels - in the same xliff file - still showed up in english....it took as while to spot that. So it would be nice if this is made clear in the documentation that it has to be e.g. de-DE to work proper. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The .xlf file generates the correct locale code for the source language and the target language must follow the same guideline as shown in the example. But we have tried to make it clearer in the topic, which will be available with the next doc refresh. Thanks.
