### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by Frantic42** [MicrosoftDocs/dynamics365smb-devitpro-pb#202]
Permissions =
  TableData 27 = RIMD,
  TableData 313 = R;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cc6aff-1250-cb04-7284-36a70fb0ffa5
* Version Independent ID: eca39949-6e5c-3160-0741-0fc57e5cdf1f
* Content: [Permissions Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-permissions-property)
* Content Source: [dev-itpro/developer/properties/devenv-permissions-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-permissions-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
This feedback is not understandable. Closing the issue. Thanks.

**Comment by RasmusTidselbak** [comment]
I needed this Example, thank you Frantic42

**Comment by RasmusTidselbak** [comment]
Example:
Permissions =
        tabledata "Sales Cr.Memo Header" = rim,
        tabledata "Item Ledger Entry" = rim;

**Comment by Frantic42** [comment]
I guess this was supposed to be attached to a thread originally...
