### ISSUE TITLE
event subscriber to OnBeforeHandleCustomIntegrationTableMapping doesn't compile

### ISSUE THREAD

**Issue by spiderted1985** [MicrosoftDocs/dynamics365smb-devitpro-pb#2025]
The event subscriber to OnBeforeHandleCustomIntegrationTableMapping doesn't compile. It needs these local variables

        IntegrationFieldMapping: Record "Integration Field Mapping";
        CDSWorker: Record "CDS Worker";
        Employee: Record "Employee";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540cdab0-3f9b-3bca-3290-a55672dcd878
* Version Independent ID: 738291c4-afe9-fab0-dedb-9888b5e178a2
* Content: [Customizing an Integration with Microsoft Dataverse - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-custom-cds-integration)
* Content Source: [dev-itpro/administration/administration-custom-cds-integration.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/administration-custom-cds-integration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this and for the nice contribution. The topic is fixed and will be available with the next doc refresh.
