### ISSUE TITLE
Format Tooltips

### ISSUE THREAD

**Issue by Aioli18** [MicrosoftDocs/dynamics365smb-devitpro-pb#2026]
Hello There,
Would be nice to habe an Option to format the Tooltip with 'Line Breaks' and stuff.
Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd74fd6-548d-095d-34c6-0c3b7b00d22e
* Version Independent ID: 298b8ca2-450f-0015-5fdb-001cae86124b
* Content: [ToolTip Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-tooltip-property)
* Content Source: [dev-itpro/developer/properties/devenv-tooltip-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-tooltip-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, sounds like a good idea. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
