### ISSUE TITLE
Links don't link

### ISSUE THREAD

**Issue by anotherRedbeard** [MicrosoftDocs/dynamics365smb-devitpro-pb#2027]
[Enter feedback here]
The links at the bottom of this page just redirect you back to the existing page.  I'm looking for a solution on how to connect to the BC api using ADF with oauth2.  The documentation is not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8eb2c50-c0d1-7e64-0d00-8ad72f8a968a
* Version Independent ID: f0fd2b39-733e-c38d-ad5f-02f6538d06e6
* Content: [API(V2.0) for Dynamics 365 Business Central   - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/)
* Content Source: [dev-itpro/api-reference/v2.0/index.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for the feedback. The information you are looking for is not something we have at the moment. I am not sure, I understand that the links redirect, I just checked and they link to other topics. Links under Recommended content are not generated by us, so we have no control over them. Sorry to not be able to provide you with the information you were looking for.
