### ISSUE TITLE
At least mention that Conditional Access is not supported

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/dynamics365smb-devitpro-pb#2028]
As it turns out, even though implementing MFA is recommended, Business Central is not available for use when defining your Cloud Apps in a conditional access policy. So even though you can enable MFA global (which no one using Conditional Access is doing), you cannot leverage your Conditional Access policies to properly protect Business Central (MFA, compliant device etc)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c36d03-7f72-72d0-bbe1-d60f881a9e66
* Version Independent ID: c5775944-717d-d054-c016-a82a2efed79c
* Content: [Multi-Factor Authentication - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/security/multifactor-authentication)
* Content Source: [dev-itpro/security/multifactor-authentication.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/security/multifactor-authentication.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! Unfortunately, when setting up a Conditional Access policy, you can't select Business Central as a Cloud App.  We've updated the article to indicate what is currently supported as far as Conditional Access goes. The update will be published soon.
