### ISSUE TITLE
API v1.0 Links no longer work

### ISSUE THREAD

**Issue by EionRobb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2029]
The links to the old v1.0 API no longer work, eg https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_create_salesorder (which, coincidentally is linked from the Recommended Content section at the bottom of https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/) will redirect to the v2.0 API, however on-premise installs of NAV/BC still use v1.0 and the docs are now no longer available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8eb2c50-c0d1-7e64-0d00-8ad72f8a968a
* Version Independent ID: f0fd2b39-733e-c38d-ad5f-02f6538d06e6
* Content: [API(V2.0) for Dynamics 365 Business Central   - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/)
* Content Source: [dev-itpro/api-reference/v2.0/index.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The API documentation has been moved from one repo to another, and that is why the information is redirected. The docs for version 1.0 do indeed exist - here is a direct link: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v1.0/ - we might want to change the redirection, but version 1.0 can be found from the table of contents on the BC docset here:
![image](https://user-images.githubusercontent.com/12556556/133590602-2a782286-090f-4210-a614-cf340e13d594.png)

Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
The redirection has been fixed to go to v1.0 docs - top-level node, but hope this helps anyway. Thanks.
