### ISSUE TITLE
TransactionModel Property link

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#2031]
The TransactionModel Property  link shows no real info on the actual property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f1b2d-e76a-e830-3e2c-078849a056b2
* Version Independent ID: 1aa4a0c6-de99-c84b-5c1b-bf229c26f16e
* Content: [Test Codeunits and Test Methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-test-codeunits-and-test-methods)
* Content Source: [dev-itpro/developer/devenv-test-codeunits-and-test-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-test-codeunits-and-test-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The reason for the redirection is that the TransactionalModel is an attribute and not a property, which is now caught by our new and improved auto-generation. The topic can instead be found here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-transactionmodel-attribute - we will update the link with the next doc refresh. Thanks.
