### ISSUE TITLE
Upgrading AppSource Apps through BC Admin Center

### ISSUE THREAD

**Issue by steveendow** [MicrosoftDocs/dynamics365smb-devitpro-pb#2032]
I recently learned that BC Apps can be updated from the BC Admin Center without requiring a manual Uninstall then Reinstall from AppSource, as indicated on the Docs page.

Can the "Upgrading AppSource Apps in Production" Docs page be updated to include this upgrade method?

![image](https://user-images.githubusercontent.com/11199908/133664801-3efca88c-df63-45ec-a65c-f62a30ceb10a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac07d83-45c1-324d-d292-b79e04939cdc
* Version Independent ID: 76985863-66fa-1583-7632-27949149d90c
* Content: [Upgrading AppSource Apps in Production - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrade-appsource-app-in-prod)
* Content Source: [dev-itpro/developer/devenv-upgrade-appsource-app-in-prod.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-upgrade-appsource-app-in-prod.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **freddyk**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The topic has already been updated, please see here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrade-appsource-app-in-prod - thanks.
