### ISSUE TITLE
Record Links are not moved

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#2033]
Hello,

Could you document the fact Record Links are not supported during cloud migration?

See this topic: https://www.yammer.com/dynamicsnavdev/threads/1389817335136256?message_id=1389817335136256

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2837e7aa-ce6e-5e8b-0cfe-dc8396194b68
* Version Independent ID: d7cfb529-94b1-7c74-7708-8cb4c4f1bb08
* Content: [FAQ about Migrating to Business Central Online - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/faq-migrate-data)
* Content Source: [dev-itpro/administration/faq-migrate-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/faq-migrate-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now fixed.
