### ISSUE TITLE
Syntax error (Missanderstanding)

### ISSUE THREAD

**Issue by DmitrijYudin** [MicrosoftDocs/dynamics365smb-devitpro-pb#2035]
Hello, 
It seems to me that in the method signature must be ";" not "," .
Here we have:  local procedure MyProcedure(Rec: Record, RunTrigger: Boolean)
Must be:          local procedure MyProcedure(Rec: Record; RunTrigger: Boolean)

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b41ed09-2b78-956a-84cb-02f46a0d7ff7
* Version Independent ID: 93807815-a05a-0c7f-a1e4-5553abe2007a
* Content: [OnAfterDeleteEvent (Table) Trigger Event - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/events/table/devenv-onafterdeleteevent-table-trigger)
* Content Source: [dev-itpro/developer/triggers-auto/events/table/devenv-onafterdeleteevent-table-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/triggers-auto/events/table/devenv-onafterdeleteevent-table-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this, it will be fixed with the next refresh.
