### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#2036]
The link in the initial note does not work: https://docs.microsoft.com/en-us/dynamics365/dynamics-nav/api-reference/v2.0/enabling-apis-for-dynamics-nav
 Note

For information about enabling APIs for Business Central see Enabling the APIs for Dynamics 365 Business Central.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 984f06f5-a71d-687f-e9be-c6621178b907
* Version Independent ID: ab2bb694-710d-e9fc-21ad-717c6fbf88e0
* Content: [userGroupMember resource type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/resources/dynamics_usergroupmember)
* Content Source: [dev-itpro/administration/resources/dynamics_usergroupmember.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/resources/dynamics_usergroupmember.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by epernst** [comment]
The same link is used an wrong on all the other section headers under Automation (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. It will be fixed with the next doc refresh.
