### ISSUE TITLE
New-NAVWebServerInstance parameters

### ISSUE THREAD

**Issue by EasyStep2Lean** [MicrosoftDocs/dynamics365smb-devitpro-pb#204]
Te parameters in the scripts should be -ContainerSiteName instead of -ContainerName and -PublishFolder instead -PublisherFolder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5005da-8a57-4bf8-5cd6-43a5b0339e21
* Version Independent ID: 1752f4ac-bb39-1a7c-0bfc-028916b63f6f
* Content: [How to: Set Up Multiple Web Server Instances for the Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/configure-multiple-web-server-instances#feedback)
* Content Source: [dev-itpro/deployment/configure-multiple-web-server-instances.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/configure-multiple-web-server-instances.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The parameter references have been fixed. The updated content will be available soon.
