### ISSUE TITLE
Dead Link for Upgrading NAV 2009 R2 or NAV 2009 SP1 Database to NAV 2015.pdf

### ISSUE THREAD

**Issue by Kowa63** [MicrosoftDocs/dynamics365smb-devitpro-pb#2044]
In Section **Through Microsoft Dynamics NAV 2015**
the link for **Upgrading NAV 2009 R2 or NAV 2009 SP1 Database to NAV 2015.pdf** on 
https://cloudblogs.microsoft.com/dynamics365/no-audience/2014/11/09/cumulative-update-1-for-microsoft-dynamics-nav-2015-has-been-released/?source=nav
is dead.
https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/10/56/97/14/Upgrading%20NAV%202009%20R2%20or%20NAV%202009%20SP1%20Database%20to%20NAV%202015.pdf
yields
> ResourceNotFound
> The specified resource does not exist. 

There is a website with  the same content as the PDF: 
https://cloudblogs.microsoft.com/dynamics365/no-audience/2015/02/23/upgrading-from-microsoft-dynamics-nav-2009-r2-or-microsoft-dynamics-nav-2009-sp1-to-microsoft-dynamics-nav-2015/
3rd party link to PDF: https://kappiwebhosting.blob.core.windows.net/dynamcisis/2014/11/Upgrading-NAV-2009-R2-or-NAV-2009-SP1-Database-to-NAV-2015.pdf
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05ac89ef-8c34-7d8e-f8db-9f66b32609a4
* Version Independent ID: 20692e88-8f1f-a98f-055a-7da5998e7582
* Content: [Upgrading to On-Premises v.14 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-to-business-central-on-premises)
* Content Source: [dev-itpro/upgrade/upgrading-to-business-central-on-premises.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrading-to-business-central-on-premises.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The link has been fixed. The update will be published soon.
