### ISSUE TITLE
Impercise definition of parameter „Clear“.

### ISSUE THREAD

**Issue by sd484** [MicrosoftDocs/dynamics365smb-devitpro-pb#2047]
What is the default value of the optional parameter „Clear“?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0149bbe6-13aa-bfb0-7cfc-64342acf1f78
* Version Independent ID: a2645a50-087e-5c8f-abe7-84c0ba4fc575
* Content: [System.GetCollectedErrors(\[Boolean\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-getcollectederrors-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-getcollectederrors-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/system/system-getcollectederrors-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The default is **false**. We've added this to the article. The update will be published soon.
