### ISSUE TITLE
Create Multiple

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#205]
I'm getting errors when trying to create multiple records through the API. Doesn't the API accept multiple records by sending a Json request like this?:

POST https://api.businesscentral.dynamics.com/v1.0/api/beta/companies({id})/itemCategories
Content-type: application/json
```
[
{
  "code": "CHAIR",
  "displayName": "Office Chair"
},
{
  "code": "TABLE",
  "displayName": "Office Table"
}
]
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43dc7f7-cac4-8708-10c3-9e39e4775ec3
* Version Independent ID: 7b515f6e-be46-050f-a79c-9c3b771eacc1
* Content: [Create itemCategories - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_create_itemcategories)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_create_itemcategories.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_create_itemcategories.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Posting multiple entities is currently undocumented, this will be fixed with the next doc refresh. You can use $batch. Thanks.

**Comment by manichoy** [comment]
how to use $batch in Business Central API?

POST https://api.businesscentral.dynamics.com/v1.0/{tenantid}/api/v1.0/$batch
Content-Type: application/json
Accept: application/json

{
	"requests": [
		{	
	    	"id":"1",
	    	"method":"get",
		"url":"/companies"
		}
}


Currently above call get a "No HTTP resource" message

Response
{
    "responses": [
        {
            "id": "1",
            "status": 404,
            "headers": {
                "content-type": "application/json; charset=utf-8"
            },
            "body": {
                "Message": "No HTTP resource was found that matches the request URI 'https://api.businesscentral.dynamics.com/v1.0/XXXXXX/api/v1.0/companies'."
            }
        }
    ]
}

**Comment by manichoy** [comment]
how to use $batch in Business Central API?

POST https://api.businesscentral.dynamics.com/v1.0/{tenantid}/api/v1.0/$batch
Content-Type: application/json
Accept: application/json

{
"requests": [
{
"id":"1",
"method":"get",
"url":"/companies"
}
]
}

Currently above call get a "No HTTP resource" message

Response
{
"responses": [
{
"id": "1",
"status": 404,
"headers": {
"content-type": "application/json; charset=utf-8"
},
"body": {
"Message": "No HTTP resource was found that matches the request URI https://XXXXXXXXXXXXX.applicationservices.businesscentral.dynamics.com:7048/companies'."
}
}
]
}
