### ISSUE TITLE
Record.GetPosition() does not document parameter UseNames (or is it UseCaptions?)

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2050]
It should. `RecordRef.GetPosition()` does... However, before referring to, or copying and pasting from, there - please see

* [RecordRef.GetPosition() parameter UseNames is also called UseCaptions and causes use of captions, not names #2049](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2049)

and accordingly fix/unify the naming there first. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d016f7d9-e6c1-2d2c-365c-d5802f0ef0be
* Version Independent ID: b3bf1d0c-e89f-fd03-c8e7-fd5cfb5dfa09
* Content: [Record.GetPosition(\[Boolean\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-getposition-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-getposition-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-getposition-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've updated the article. The update will be published soon.
