### ISSUE TITLE
misleading

### ISSUE THREAD

**Issue by klauskaan** [MicrosoftDocs/dynamics365smb-devitpro-pb#2052]
This description is misleading at best.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d37a1f5d-28c2-66eb-045c-ea4d2422ad11
* Version Independent ID: d2827583-32ea-367a-dfba-336e70bee5cd
* Content: [Record.TestField(Any) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-testfield-joker-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-testfield-joker-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-testfield-joker-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - this method has a number of overloads, they're all displayed in the table of contents under this topic, these have descriptions of the various parameters. Can you please elaborate on what is misleading - thanks.

**Comment by dnpb** [comment]
Not the OP, but I'm pointing out what I see missing, which might psychically align with whatever mystery they want changed ;-)

I hadn't noticed the overloads, but:

> Can you please elaborate on what is misleading - thanks.

As I said above, `TestField(Any)` says

> Tests whether the contents of a field match a given value.

...but it _has_ no parameter for what value to test against!

Shouldn't it be something like this, as I wrote above?

> Tests that the field is not the 'blank'/'null' value for its type

**Comment by SusanneWindfeldPedersen** [comment]
This is fixed with the next refresh of the docs. Thanks!
