### ISSUE TITLE
Syntax section is not addressing the right data type

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2055]
Syntax section is not addressing the right data type as it is talking about `Date `and `Time` format, but not `DateTime`. Please correct this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8b5aed-979e-b1fe-845f-06008cff98e0
* Version Independent ID: 12bd4c37-f88b-3429-dd9b-d7a2d8fa4002
* Content: [DateTime Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/datetime/datetime-data-type)
* Content Source: [dev-itpro/developer/methods-auto/datetime/datetime-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/datetime/datetime-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
