### ISSUE TITLE
Default Encoding

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#2057]
What's the default value used for the Encoding parameter if it is not provided?

This is missing from a lot of pages where the Encoding parameter is optional. A few that I found:
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-createinstream-method
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/blob/blob-createinstream-method
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-open-method
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-createoutstream-method
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/blob/blob-createoutstream-method
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-createtempfile-method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a24eaf49-8adb-0e32-0800-e30e23a46bbc
* Version Independent ID: 87e447e6-2b31-ade9-b90c-976d361aa8df
* Content: [Blob.CreateOutStream(OutStream \[, TextEncoding\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/blob/blob-createoutstream-method)
* Content Source: [dev-itpro/developer/methods-auto/blob/blob-createoutstream-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/blob/blob-createoutstream-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This might be a bug in our auto-generation of the topics. We will have to look into it. Please stay tuned.

**Comment by SusanneWindfeldPedersen** [comment]
This is fixed with the next doc refresh. Thanks!
