### ISSUE TITLE
BC

### ISSUE THREAD

**Issue by jnpatrouillault** [MicrosoftDocs/dynamics365smb-devitpro-pb#206]
Hello
Are these limitations the same for BC Web client on premise and BC in SAS ?

In the header of the document we can see NAV 2017 & NAV 2018. Nothing about BC.

thank you for the explanation.
regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b3a845-b388-9c69-478f-87cc70b87819
* Version Independent ID: af209cd5-e554-fe3f-30f0-05d771b21a17
* Content: [Feature Limitations of the Web Client - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/feature-limitations-of-the-microsoft-dynamics-nav-web-client)
* Content Source: [dynamics-nav/Feature-Limitations-of-the-Microsoft-Dynamics-NAV-Web-Client.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Feature-Limitations-of-the-Microsoft-Dynamics-NAV-Web-Client.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please find documentation about Business Central [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/). Thanks.

**Comment by jnpatrouillault** [comment]
Where can I find the limitation for BC Web client ? The link you provided is talking about BC in general. thanks

**Comment by Ichorao** [comment]
Where can I find the limitations for Business Central Web client? I can only find for NAV.
