### ISSUE TITLE
Reference is made to menu Debug but should be Run

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2064]
In the text a number of times reference is made to menu **Debug** but should be **Run**. 
For example:

In Visual Studio Code, under **Debug**, choose **Add configuration**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0b843a-3810-414d-1374-443829ce8dad
* Version Independent ID: 75b366e0-5b6d-a0b0-79bf-aa68115232e9
* Content: [Attach and Debug Next - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-attach-debug-next)
* Content Source: [dev-itpro/developer/devenv-attach-debug-next.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-attach-debug-next.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
It should - thanks for catching this! Will be fixed with the next doc refresh.
