### ISSUE TITLE
v1.0 vs v2.0

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#2068]
It's not clear in the listed samples which version to use to connect to the BC api.
Some samples list v1.0 vs v2.0 (first part of url) against v2.0 (in the last part of the url)

https://api.businesscentral.dynamics.com/**v2.0**/<environment name>/api/v2.0

![image](https://user-images.githubusercontent.com/25268332/137758729-2a02e98a-bdd6-4e01-901a-bfeba1f1c61b.png)

Is it always v1.0 when you don't specify the environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a5495f-193a-9ad6-490d-8bb5d0b2d709
* Version Independent ID: 95da6841-b4a7-932c-de90-4b3b93bf8eea
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/endpoints-apis-for-dynamics)
* Content Source: [dev-itpro/api-reference/v2.0/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/endpoints-apis-for-dynamics.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
Thanks for the feedback. 
You should use v2.0 (in the first part). That enable access to named environments. With v1.0 you can only access the environment named "production" and "sandbox" if you include it in the URL.

I will update the doc page, as theres no reason to use v1.0.
