### ISSUE TITLE
Examples would be appreciated

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#2073]
The generic description of this function is not conclusive how the properties are supposed to be used. Something along these lines would be appreciated:
https://docs.microsoft.com/en-us/dynamics-nav/rename-function--record-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b72acbf-c21d-065f-e7f4-e85ece7f8121
* Version Independent ID: da07888f-f5d2-9ced-d3aa-5ad13d5a1781
* Content: [Record.Rename(Any \[, Any,...\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-rename-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-rename-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-rename-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dnpb** [comment]
Indeed, the BC version of this documentation is extremely vague, and should explain what types/values of arguments should be passed, i.e. those that match the types of all PK fields and specify their new values.

**Comment by SusanneWindfeldPedersen** [comment]
The topic is now updated and live, thanks for your patience!
