### ISSUE TITLE
Unclear / Invalid AssemblyProbingPaths

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#2074]
One of our developers followed the documentation on setup up a dev environment to get started contributing to the system module app. The page contains recommended setting for the AssemblyProbingPaths, including below path

`C:/NugetCache/NET_Framework_48_TargetingPack.4.8.3761`

Packaging the system app with this path gives an unclear error message

`error AL0999: Internal error: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)`

Changing the AssemblyProbingPaths as below, solves the issue:

```
{
    "al.assemblyProbingPaths": [                
        "C:/Windows/Microsoft.NET/Framework64/v4.0.30319",   //  <<<< REPLACED THIS VALUE
        "C:/bcartifacts.cache/onprem/19.0.29894.30693",        
        "C:/WINDOWS/assembly"
    ]
}
```

Would be good if documentation could be updated to be a bit more clear on where to get the .NET framework assemblies from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb3ed382-91a7-c867-605b-ff8fbf956d79
* Version Independent ID: 6a955fe9-c42e-3e32-f895-622d2745086b
* Content: [Set Up an Environment for Developing a Module - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-set-up-an-environment)
* Content Source: [dev-itpro/developer/devenv-set-up-an-environment.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-set-up-an-environment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hello,

.NET assemblies are something of a moving target because they can be kept in various places, depending on your setup, and there can also be various versions. Thanks a lot for your suggestion though. I'll update the example to include the path you've provided, and make it clear that it's just one example.

Thanks again for pointing this out, and for providing a fix.
