### ISSUE TITLE
Is known limitation still correct? Updates might be available via virtual table events 

### ISSUE THREAD

**Issue by mlathouwers** [MicrosoftDocs/dynamics365smb-devitpro-pb#2081]
How does these BC virtual entities relates to the artcle https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/enable-virtual-table-event-support

Would it be possible to have update triggers from changes in BC by using the event support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89aa1a4a-56ef-c76d-6767-d018a7d11e61
* Version Independent ID: 26e43ee4-5306-e816-fd7e-1fa37f328e3e
* Content: [Business Central and \[!INCLUDE\[cds_long_md\](../includes/cds_long_md.md)\] admin reference - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/powerplatform/powerplat-admin-reference)
* Content Source: [dev-itpro/powerplatform/powerplat-admin-reference.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/powerplatform/powerplat-admin-reference.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
