### ISSUE TITLE
Date2DMY() documentation doesn't explain parameter Value, which specifies which day/month/year part to get

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2082]
Dupe of https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/746 - but that was closed saying *it* was a duplicate, but not saying of *what*... and I can't see any other issues searching for `Date2DMY()`.

The documentation of `Date2DMY()` just says this for the argument that specifies which part to get:

> Value
> Type: Integer

That tells us precisely nothing.

It should be documented. It used to be. From the other issue:

> Copied from the old C/AL help file:
> 
> ```
> Specifies what the function should return. The valid options are 1, 2, and 3. 
> The value 1 corresponds to Day (1-31).
> The value 2 corresponds to Month (1-12).
> The value 3 corresponds to Year.
> ```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12d9137b-ddc5-f248-44f8-da1bd0a3518e
* Version Independent ID: 972423dd-7ea4-70d3-47f2-da5edc4b5fe7
* Content: [System.Date2DMY(Date, Integer) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-date2dmy-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-date2dmy-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/system/system-date2dmy-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, that's definitely a mistake. This will be fixed with the next refresh of the docs.

**Comment by SusanneWindfeldPedersen** [comment]
keeping this open until the topic is live

**Comment by SusanneWindfeldPedersen** [comment]
This is now live
