### ISSUE TITLE
Consistent examples?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2084]
Just a suggestion: Maybe have #'s 3 and 4 under "Create an application database" use the same ServerInstance value, to reinforce the idea that 1) first create the server instance, then 2) reference THAT server instance to set the version on the database. It would seem that "to the new database" and "on the database" are referring to the same newly-created database, so presumably the same server instance name would be used both when creating the instance and setting the version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31a3849-669f-609d-2401-9f41e61639c4
* Version Independent ID: fe5e6447-cd5c-fe08-32c7-0c9cf99b2451
* Content: [Creating and Altering Business Central Databases - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/devenv-create-databases)
* Content Source: [dev-itpro/deployment/devenv-create-databases.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/deployment/devenv-create-databases.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the article as suggested. The update will be published soon.
