### ISSUE TITLE
Parameter Id is misspelled, the name is AppId

### ISSUE THREAD

**Issue by git-no** [MicrosoftDocs/dynamics365smb-devitpro-pb#2087]
Parameter `Id` is misspelled, the correct parameter name is `AppId`.
Maybe this is worth to correct the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7db55e-2c23-1e7f-0165-642240929bb4
* Version Independent ID: 7038e976-0307-8b61-8e23-81045b5c60c4
* Content: [Get-NAVAppInfo (Microsoft.Dynamics.Nav.Apps.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappinfo?view=businesscentral-ps-19)
* Content Source: [businesscentral-ps-19/Microsoft.Dynamics.Nav.Apps.Management/Get-NAVAppInfo.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-19/Microsoft.Dynamics.Nav.Apps.Management/Get-NAVAppInfo.md)
* Product: **dynamics365-business-central**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

`-AppId` is an alias or alternate name for `-Id`. Here is a clip from the article:

<html>
<body>
<strong>-Id</strong><p>Specifies the ID of the Business Central app to be returned.</p>

Type: | Guid
-- | --
Aliases: | AppId
</div>
...
</body>
</html>

I think `-AppId` was the original parameter name, but we switched to `-Id` at some point. Both can be used, although `-Id` is preferred.  We'll close this issue for now, but if you have more feedback, we'll gladly reopen it.
