### ISSUE TITLE
Disable AutoSave ?

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#2088]
One potential other recommendation from MS is to turn off any `AutoSave` settings from VS Code. 

Reference :  MS Case 2110200060002622 Compilation errors / @kalberes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53eff08e-0449-dbf1-7dcc-09066ac5152d
* Version Independent ID: fea86b79-b558-c46a-3fe3-5db7f4df30e0
* Content: [Optimize Visual Studio Code Editing and Building Performance - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-optimize-visual-studio-code)
* Content Source: [dev-itpro/developer/devenv-optimize-visual-studio-code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-optimize-visual-studio-code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by kalberes** [comment]
true, autosave should be turned off on large projects (large project ~ base app kind of projects)
Until we do not fix it it could mess up with incremental background compilation.
