### ISSUE TITLE
FreezeColumn one or more

### ISSUE THREAD

**Issue by DOM-Log** [MicrosoftDocs/dynamics365smb-devitpro-pb#2091]
[Enter feedback here]
Hello. Can you add more than one column the the freezeColumn property?
If yes, how?
If no, then the Tooltip is confusing.

(property) FreezeColumn: String
Specifies the columns in a list that remain in view on a page, even when you scroll right.

BC here its written in plural :/
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c4e2ce-ceb4-930d-521d-e4b2338ee11f
* Version Independent ID: 1a43a957-7f4b-6f6a-efa0-a196217fbfca
* Content: [FreezeColumn Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-freezecolumn-property)
* Content Source: [dev-itpro/developer/properties/devenv-freezecolumn-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-freezecolumn-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
This should be fixed by adding the Remarks section mentioned in the other github issue. The property takes only one column, but the columns before it are "frozen" and will remain in view on the page. Hope this helps. The fix will be ready with the next doc refresh. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Live here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-freezecolumn-property - closing issue - thanks!
