### ISSUE TITLE
Please add additional info from NAV documentation to BC documentation

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#2092]
see title
[Enter feedback here]
https://docs.microsoft.com/en-us/dynamics-nav/freezecolumnid-property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c4e2ce-ceb4-930d-521d-e4b2338ee11f
* Version Independent ID: 1a43a957-7f4b-6f6a-efa0-a196217fbfca
* Content: [FreezeColumn Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-freezecolumn-property)
* Content Source: [dev-itpro/developer/properties/devenv-freezecolumn-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-freezecolumn-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - this also addresses issue #2091. We will add this with the next doc refresh. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
This is now live here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-freezecolumn-property
