### ISSUE TITLE
BLOB field default value of the Compressed property

### ISSUE THREAD

**Issue by ashirokikh** [MicrosoftDocs/dynamics365smb-devitpro-pb#2094]
Hi Folks,

I've checked the default value of the Compressed property in Business Central versions 13, 14, and 18. The default value seems to be **true**. 

![image](https://user-images.githubusercontent.com/17916422/141432658-884f85c4-b4a6-4935-bdb6-6e0345cd6e66.png)

Thanks,
Alex 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1710eae-78af-c6a1-1a14-0125ac939e00
* Version Independent ID: 24aaa7c2-ae79-a5f8-7623-8263e8a6e8a5
* Content: [Compressed Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-compressed-property)
* Content Source: [dev-itpro/developer/properties/devenv-compressed-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-compressed-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
You are absolutely right, thanks for catching this! Will be fixed with the next doc refresh.
