### ISSUE TITLE
Settings ignored if published from VS Code

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#2095]
Please add a warning that the settings are ignored when publishing from VS Code:
https://github.com/microsoft/AL/issues/6831#issuecomment-967114187

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 161ddd1b-3d2c-d2fc-0d20-ad8331c809e4
* Version Independent ID: d5153e86-ac7c-4b93-43e2-ae6b06becb8e
* Content: [Resource Exposure Policy Setting - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-security-settings-and-ip-protection)
* Content Source: [dev-itpro/developer/devenv-security-settings-and-ip-protection.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-security-settings-and-ip-protection.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi Natalie, we already have a note in this section: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-security-settings-and-ip-protection#allowdebugging - about DEV extensions. I have read through (most of the thread and I think the note covers it. Do you want it be more prominent or stand out more? What are your thoughts? Thanks

**Comment by NKarolak** [comment]
Hi Susanne,
sorry for that, you are right (of course). I just didn't find it. Or should I say: I didn't expect it on that place.
The reason: I would assume that all resource exposure policy settings (not only allowDebugging) are ignored for DEV extensions.
But that's only me, I suppose. I just didn't look careful enough.

**Comment by SusanneWindfeldPedersen** [comment]
I think it is only allowDebugging, but I will re-check with our PM. And then I think I will change the NOTE to a WARNING so that it stands out more from the other note in there. Thanks again, Natalie.
