### ISSUE TITLE
Warehouse Activity "Source Subtype" to Enum

### ISSUE THREAD

**Issue by TriangleSPV** [MicrosoftDocs/dynamics365smb-devitpro-pb#2096]
Hi

We have some developments that we have created FlowFields to relate sales/purchase document headers or lines to their "Warehouse Activity Header" or "Warehouse Activity Lines" documents.

Since some weeks ago we see the error "An implicit conversion is being performed from a value of type 'Enum "Sales Document Type"' to a value of type 'Option'" in these calcfields because we relate the "Source Subtype" of the warehouse document (Option) to the sales/purchase "Document Type" (updated to Enum).

We cannot use functions like FromInteger or AsInteger to transform the values because we are in a CalcFormula.

Do you have any idea how we can solve these warnings? Or the only way is wait until you update the field "Source Subtype" of the warehouse tables to Enum?

This is an example of the calcformula that we have in sales headers (for sales orders or return orders):
CalcFormula = Exist("Warehouse Activity Header" where("Source Subtype" = field("Document Type"), "Source No." = field("No."), "Source Type" = const(37)));

**Comment by dnpb** [comment]
wrong repo; you want https://github.com/microsoft/ALAppExtensions

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Please go to https://github.com/microsoft/ALAppExtensions for help on this issue as specified above. Thanks.
