### ISSUE TITLE
Please provide a complete example

### ISSUE THREAD

**Issue by PeterBizz** [MicrosoftDocs/dynamics365smb-devitpro-pb#21]
the example is lacking the initial call to retrieve the orginal odata.DataLink. 
the documentation says put odata.track-changes  in prefer header, but when I create a header
"Prefer:odata.track-changes"  the call ends in 500 Error.
{
    "error": {
        "code": "Unknown",
        "message": "One or more errors occurred."
    }
} 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24dd3a74-cb61-41a4-e9eb-b08e1afdc0ae
* Version Independent ID: 230e037d-c936-3af8-218d-3c80bd7d2fd6
* Content: [Using Delta Links With APIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-connect-apps-delta)
* Content Source: [dev-itpro/developer/devenv-connect-apps-delta.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-connect-apps-delta.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. Closing this issue as this is now added to our backlog. Thanks again.
