### ISSUE TITLE
"See also" link "triggers" leads to just  trigger

### ISSUE THREAD

**Issue by wolterOnEntocare** [MicrosoftDocs/dynamics365smb-devitpro-pb#2102]
Under "See also" there is a "triggers" link that leads to just one trigger. I expected to see a list or overview of them, but concluded that XmlPorts probably support just one trigger. That turned out later to be a wrong conclusion!
The page could have contained a explanation of the various levels at which triggers can be placed (on the XmlPort itself, on a tableelement, or on a field) and then lists of available triggers, or a remark to point the reader to look at the left column where I failed to look. In any case, a link to one single trigger is misleading and doesn't fit the title of the link!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1326351-92cf-6e3c-48fc-8dc3487a7b90
* Version Independent ID: fe4f4489-5677-5a1d-6426-dfdde2fd0368
* Content: [XMLport Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-xmlport-overview)
* Content Source: [dev-itpro/developer/devenv-xmlport-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-xmlport-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **t-blrobl**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The link from the XMLPort Overview topic links to the first of 3 triggers that are supported. The triggers documentation is auto-generated and reflects the source code. The reason that we cannot add a link to a XML overview of triggers is that we only generate what is actually in the source code and do not maintain overviews for all of the objects. We cannot, for accessibility reasons, link to the XML port triggers node in the table of contents, so we link to the first trigger on the list instead. If you look at the table of contents, you can see the three triggers that can be used. We have not gotten this feedback before, but we'll consider adding all three links to the XMLPort Overview topic instead. Thanks.
