### ISSUE TITLE
Missing information regarding ClientServicesCredentialType=Impersonate

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/dynamics365smb-devitpro-pb#2103]
Hey Guys, 

In the latest version (at least v18), we see new option "Impersonate" for ClientServicesCredentialType. Could you please describe it in the documenation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30dd402-c112-00be-9c66-4f8bd6a2184f
* Version Independent ID: 215be880-512c-a76b-5463-bfd1b349dd81
* Content: [Microsoft Dynamics 365 Business Central Server Configuration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-server-instance)
* Content Source: [dev-itpro/administration/configure-server-instance.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/configure-server-instance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The **Impersonate** option is for internal use only, and shouldn't be used. We've added this info to the [Authentication and Credential Types](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/users-credential-types#credential-types) article. The update will be available soon.
