### ISSUE TITLE
Add json as secret value not clearly described.

### ISSUE THREAD

**Issue by foodware365** [MicrosoftDocs/dynamics365smb-devitpro-pb#2104]
Hi,

In the documentation isn't described that its not possible to set the json secret value thru the Azure Portal and needs to be set via a PowerShell command as described in this blog:
https://demiliani.com/2021/11/02/dynamics-365-business-central-overriding-the-extensions-resource-policy-for-a-particular-tenant/

> Adding a JSON value to an Azure Key Vault secret cannot be done directly via the Azure Portal (multi-line secrets are not supported), so you can use Azure Powershell for this:
> 
> $json = '{ 
>     "allowDebugging": [ 
>       "9e2b6561-1ba6-4790-abcc-c84abf9a8961" 
>     ], 
>     "allowDownloadingSource": [ 
>       "9e2b6561-1ba6-4790-abcc-c84abf9a8961" 
>     ], 
>     "includeSourceInSymbolFile": [ 
>       "9e2b6561-1ba6-4790-abcc-c84abf9a8961" 
>     ] 
> }'
> $Secret = ConvertTo-SecureString -String $json -AsPlainText -Force
> Set-AzKeyVaultSecret -VaultName "YourKeyVaultName" -Name "BC-ResourceExposurePolicy-Overrides" -SecretValue $Secret

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 161ddd1b-3d2c-d2fc-0d20-ad8331c809e4
* Version Independent ID: d5153e86-ac7c-4b93-43e2-ae6b06becb8e
* Content: [Resource Exposure Policy Setting - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-security-settings-and-ip-protection)
* Content Source: [dev-itpro/developer/devenv-security-settings-and-ip-protection.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-security-settings-and-ip-protection.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. I agree, this should be mentioned in the topic - will be fixed with the next doc refresh. Thanks!
