### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by naradae** [MicrosoftDocs/dynamics365smb-devitpro-pb#2105]
The link to 'Publishing and Installing an Extension' is

https://docs.microsoftcom/en-us/dynamics365/business-central/dev-itpro/developer/devenv-how-publish-and-install-an-extension-v2

Which is missing a period between 'microsoft' and 'com' in the hostname

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f74f95a-9b5c-c0d2-a2da-337d0e66768d
* Version Independent ID: 5fdebecd-6373-6472-77bb-c9eb68dd10a2
* Content: [Sync-NAVApp (Microsoft.Dynamics.Nav.Apps.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/sync-navapp?view=businesscentral-ps-19)
* Content Source: [businesscentral-ps-19/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-19/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md)
* Product: **dynamics365-business-central**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback. The link has been fixed and the update will be published soon.
