### ISSUE TITLE
RecordRef Data Type - Missing Methods section

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#211]
Many data types have a nice "Methods" listing.  RecordRef does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4192d4a6-27a3-9ffa-501f-079e0a8e6a20
* Version Independent ID: 55411335-11da-7dd0-04dc-f593c5e800d4
* Content: [RecordRef Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/datatypes/devenv-recordref-data-type)
* Content Source: [dev-itpro/developer/datatypes/devenv-recordref-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/datatypes/devenv-recordref-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi and thank you for your feedback! We are working on providing a better experience for the methods section. It will be available soon. Thank you for your patience!

**Comment by update-jeremy** [comment]
Quick question, as I'm new to providing feedback and seeing the results - I notice the issue is now marked close, though the content available online has not changed.

If I'm guessing, you have the update in your private repo and it will be pushed to live as part of a scheduled/triggered update later?

Thanks again for addressing the issue and having this really great system for feedback and collaborative improvement in place!

**Comment by ailie13** [comment]
Hi again! Yes, indeed. They will be pushed live very soon. Thank you for your feedback!
