### ISSUE TITLE
FieldRef.OptionMembers() Method has no info on its format and no examples, but OptionString() says to use it!

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2119]
[FieldRef.OptionString() Method](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-optionstring-method) says:

> The 'OptionString' property has been deprecated and will be removed in the future. Use the 'OptionMembers' property instead.

but the latter page has no info on what format it returns, no examples on how to use it... etc.

Surely the info and examples should be moved to the non-deprecated page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a07c9a31-f970-f374-1f80-e500805ed051
* Version Independent ID: deda4092-9d09-8854-9273-edc90fe77080
* Content: [FieldRef.OptionMembers() Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-optionmembers-method)
* Content Source: [dev-itpro/developer/methods-auto/fieldref/fieldref-optionmembers-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/fieldref/fieldref-optionmembers-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Absolutely, thanks for catching this. Will be fixed with the next doc refresh.
