### ISSUE TITLE
Minor Typo at Task 13: Change application version

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#2121]
At the Change application version, step one the command is 
`
Set-NAVApplication -ServerInstance $NewBcServerInstance -ApplicationVersion $NewVersion -Force
`
and should be 
`
Set-NAVApplication -ServerInstance $NewBcServerInstance -ApplicationVersion $NewBCVersion -Force
`
$NewBCVersion instead of $NewVersion

And thank you for the new code snippet formats they are great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c4713aa-6a18-32d4-2f34-be03e3cc87a5
* Version Independent ID: 398a09ff-fe8b-ba2d-18c8-31b2f84a87e8
* Content: [Upgrading Version 15, 16, 17, or 18 Base Application to Version 19 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v19)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v19.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v19.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We're glad the snippets are helpful. The article has been fixed and an update will be published soon.
