### ISSUE TITLE
Example code needed please

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#2124]
In the section Using a barcode font in the report layout, it gives a description of what should be done, but there is no example code give about how to actually do it. The font 3of9 is a free barcode font that is commonly used, I think, to create barcodes for reports. 

Would it be possible to include an example demonstrating how to use an external barcode font in a report? This is especially true given how difficult it is to work with the File System in Business Central 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04fb2aaa-8676-c0ae-434b-eb3d85bddca4
* Version Independent ID: 9d634195-090b-8b48-1059-e45233d7dcba
* Content: [Adding barcodes to reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-add-barcodes)
* Content Source: [dev-itpro/developer/devenv-report-add-barcodes.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-report-add-barcodes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

We've updated the content. We hope this helps. Thanks for the feedback.

**Comment by j2associates** [comment]
Many thanks, very much appreciated!
