### ISSUE TITLE
Section upgrade Path error/incomplete/inconsistant

### ISSUE THREAD

**Issue by PeterBizz** [MicrosoftDocs/dynamics365smb-devitpro-pb#2125]
Section upgrade Path :
- refers to upgrading to version 18 , should this be version 19?  ( a direct upgrade to version 18 (*19*) isn't always .... )
- Upgrade Path table  from 
     Business Central 2020 release wave 2 (version 17)   states "Direct to version 19"
     
     from other sources (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility#version-17-compatibility) I understand this is only true as of version 17.5  
   
     For me this is unclear - what are proper steps from 17.4 to 19.x version full upgrade ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6382910-e49d-0e74-e2a7-87f1d246dfce
* Version Independent ID: f9de1ba9-4cde-46ab-2dc4-3b832534214e
* Content: [Upgrade to Business Central 2021 Wave 2 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-overview-v19)
* Content Source: [dev-itpro/upgrade/upgrade-overview-v19.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-overview-v19.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

Regarding your first bullet, we've changed "version 18" to "version 19".

From 17.4, you can go to 19.0 or 19.1, although we recommend 19.1. We'll be making changes to this article to make things clearer going forward.
