### ISSUE TITLE
empty Cells in upgrade matrix BC16/BC17

### ISSUE THREAD

**Issue by PeterBizz** [MicrosoftDocs/dynamics365smb-devitpro-pb#2126]
Need clarification of empty cells in upgrade matrix from BC16 and BC17  to BC19. What do these mean? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8868c4-fb29-4b1f-e8ba-7560642481fc
* Version Independent ID: e838d8a4-07b9-02a8-f0b5-756220b3e64d
* Content: [Business Central compatibility matrix - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility)
* Content Source: [dev-itpro/upgrade/upgrade-v14-v15-compatibility.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-v14-v15-compatibility.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

That cells should have shown 19.0, This has been fixed and an update will be published soon. Thanks for the feedback!

**Comment by PeterBizz** [comment]
> Hello,
> 
> That cells should have shown 19.0, This has been fixed and an update will be published soon. Thanks for the feedback!

Does this mean that I can directly upgrade from 17.4 to 19.1 ? (since 19.0 apparently is **minimal** version).  (That would be great news)

**Comment by jswymer** [comment]
Hello, yes you can. We're making some updates the these articles to hopefully make things clearer.
