### ISSUE TITLE
Link to Cumulative Update Page wrong

### ISSUE THREAD

**Issue by JulianTillmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#2127]
The Link in [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v18#task-13-change-application-version](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v18#task-13-change-application-version ) points to BC15, it should point to BC18. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab367758-d435-42cd-a1e1-d0b89c33ad25
* Version Independent ID: 4ea22d59-5d20-c0af-7bf8-e678c181b663
* Content: [Upgrading Version 15, 16, or 17 Base Application to Version 18 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v18)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the link and the update will be published soon
