### ISSUE TITLE
Is the word 'upgrade' correct in the following sentence?

### ISSUE THREAD

**Issue by mhenricus** [MicrosoftDocs/dynamics365smb-devitpro-pb#2128]
[Enter feedback here]

Is the word 'upgrade' correct in the following sentence? The page is about install codeunits, not about upgrading!?

_This example uses the OnInstallAppPerDatabase() trigger to check whether the data version of the previous extension version is compatible for the upgrade._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dd7c9e-51a5-eeea-a2f6-dd4d40b93295
* Version Independent ID: d6fb1d1b-fa2e-606e-6c79-115651b60a29
* Content: [Writing extensions installation code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-install-code)
* Content Source: [dev-itpro/developer/devenv-extension-install-code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-extension-install-code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

You're correct. 'upgrade' shouldn't be mentioned in this case. In short, the example checks whether an extension is being installed for the first time or it's being reinstalled. We've fixed the article, and the update will be published soon. Thanks!
