### ISSUE TITLE
Page.Update() has unnecessarly long / self-contradictory wording for default value of SaveRecord

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2129]
> The SaveRecord default value is true. The default value of SaveRecord, however, depends on whether SourceTable is specified or not. [...]

This is pointlessly verbose and seemingly self-contradictory. Shouldn't it just be:

> The default value of SaveRecord depends on whether SourceTable is specified or not. [...]

?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6515aa1-75f5-d10f-fa5e-c31c91006f26
* Version Independent ID: abcdaa06-7059-db42-233a-f0adc57529b7
* Content: [Page.Update(\[Boolean\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-update-method)
* Content Source: [dev-itpro/developer/methods-auto/page/page-update-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/page/page-update-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. And agreed, unnecessarily long - this is more precise with the next doc refresh. Thanks!
