### ISSUE TITLE
The code example doesn't conform to CodeCop Rule AA0008

### ISSUE THREAD

**Issue by nickgoddard777** [MicrosoftDocs/dynamics365smb-devitpro-pb#2138]
The code example on this page doesn't conform to CodeCop Rule AA0008 and could lead to confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dfee6b8-07ff-e89c-864d-9400f9057b8d
* Version Independent ID: 1f3eee29-0daa-b9d0-8c86-781ffefcfde5
* Content: [TestPage.Next() Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testpage/testpage-next-method)
* Content Source: [dev-itpro/developer/methods-auto/testpage/testpage-next-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/testpage/testpage-next-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, the code has been updated to conform with AA0008, thanks.
