### ISSUE TITLE
Dialog object in BC Web Client doesn't have a cancel action. 

### ISSUE THREAD

**Issue by CanuckNav74** [MicrosoftDocs/dynamics365smb-devitpro-pb#214]
There is no cancel action on the Business Central web client dialog. Only the windows client on-prem has this functionality. This is a pretty important omission in the BC Web Client and should be reflected in the documentation web client limitations documentation (without it, users cannot cancel out of a long running action). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b3a845-b388-9c69-478f-87cc70b87819
* Version Independent ID: af209cd5-e554-fe3f-30f0-05d771b21a17
* Content: [Feature Limitations of the Web Client - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/feature-limitations-of-the-microsoft-dynamics-nav-web-client)
* Content Source: [dynamics-nav/Feature-Limitations-of-the-Microsoft-Dynamics-NAV-Web-Client.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Feature-Limitations-of-the-Microsoft-Dynamics-NAV-Web-Client.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This is by design. Feel free to provide product feedback by using the Product Feedback button on our help topics. Thanks.
