### ISSUE TITLE
Signing App to be published on Appsource

### ISSUE THREAD

**Issue by GlobalMediator** [MicrosoftDocs/dynamics365smb-devitpro-pb#2140]
Hi,
as we are planning to publish our App for BC cloud on Microsoft App Source, I am stuck with choosing of appropriate certificate.
Could you please advice if The host Sectigo/Comodo Code signing certificate could be used for this purpose?

Regards,
Anastasiia.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please use your usual support channel for product-related questions. Thanks.
