### ISSUE TITLE
Updates don't work

### ISSUE THREAD

**Issue by sammy1188** [MicrosoftDocs/dynamics365smb-devitpro-pb#2141]
{
    "error": {
        "code": "BadRequest_InvalidToken",
        "message": "Could not validate the client concurrency token required by the service. Please provide a valid token in the client request.  CorrelationId:  fefa518d-7b91-48d0-aa7a-85e6564e6fa5."
    }
}

**Comment by dnpb** [comment]
This does not seem related to documentation. If it is, the doc page you have an issue with should have a button near the bottom like 'Submit feedback for this page', which will create an issue here with required info for the docs team to link to the source file.

**Comment by dnpb** [comment]
Also, even if it were the right repo, you should not just dump an error message without context, but instead explain exactly what process you performed to get that error...

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
