### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by SShadowS** [MicrosoftDocs/dynamics365smb-devitpro-pb#2142]
"Starting from 2022 release **wave 2**, the Dynamics 365 Business Central server is running on .NET Standard and if you are using on-premises .NET add-ins that targets .NET Framework, you need to convert them to use .NET Standard, because add-ins compiled with .NET Framework will stop working in Business Central 2022 release **wave 1**."

Is it wave 1 or 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Version Independent ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Content: [Migrating from .NET Framework to .NET Standard - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard)
* Content Source: [dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md)
* Service: **dynamics365-business-central**
* GitHub Login: @KennieNP
* Microsoft Alias: **kepontop**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this is a typo, and thanks for catching this. In both cases it should be Business Central 2022 release wave 2. This is fixed with the most recent doc refresh. Thanks
