### ISSUE TITLE
Variant.IsDate does not return true for actual date

### ISSUE THREAD

**Issue by AlexanderSchaetzel** [MicrosoftDocs/dynamics365smb-devitpro-pb#2143]
I have a valid date variant (containing 20210403) and am using the Variant to check if it's a date.
Exptected behaviour: 
DateVar.IsDate returns true.
Behaviour: 
DateVar.IsDate returns false.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
