### ISSUE TITLE
Invoke-NAVSanitizeField says 'trims all the unsupported characters from fields of type "Code"' but not what those are

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2148]
It would be preferable to list what those unsupported characters are, so users know what to expect will be removed...! Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad80d88e-18bd-100d-b07c-05c9b315a9f4
* Version Independent ID: 55d2ee6f-d413-f6fd-7e17-b457c2ac5440
* Content: [Invoke-NAVSanitizeField (Microsoft.Dynamics.Nav.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/invoke-navsanitizefield?view=businesscentral-ps-19)
* Content Source: [businesscentral-ps-19/Microsoft.Dynamics.Nav.Management/Invoke-NAVSanitizeField.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-19/Microsoft.Dynamics.Nav.Management/Invoke-NAVSanitizeField.md)
* Product: **dynamics365-business-central**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback.

The cmdlet removes leading and trailing Unicode whitespace characters, for example, characters from a keystroke like Enter and TAB. The cmdlet is similar to the [System.Trim method](https://docs.microsoft.com/en-us/dotnet/api/system.string.trim?view=net-6.0#system-string-trim) which removes characters identified as Unicode by the [Char.IsWhiteSpace Method](https://docs.microsoft.com/en-us/dotnet/api/system.char.iswhitespace?view=net-6.0#remarks).

We've update the article with this info. The update will be published soon. We hope this helps.
