### ISSUE TITLE
Wrong link in the documentation on section Available telemetry 

### ISSUE THREAD

**Issue by mynavblog** [MicrosoftDocs/dynamics365smb-devitpro-pb#2149]
Dear Team,

The link to Table index trace page is wrong. 

it links to: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/telemetry-field-monitoring-trace
instead of: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/telemetry-table-index-trace

Best regards,
Krzysztof

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c87c7e1-d0b5-df8a-d4f3-1d7f806c7c91
* Version Independent ID: 9080b8fb-4bf6-222c-717c-221e2966f79e
* Content: [Monitoring and Analyzing Telemetry - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/telemetry-overview)
* Content Source: [dev-itpro/administration/telemetry-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/telemetry-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the link and the updated article will be published soon.
