### ISSUE TITLE
Use the Simplified Filters - wrong filter

### ISSUE THREAD

**Issue by ClausHamann** [MicrosoftDocs/dynamics365smb-devitpro-pb#215]
If the setting is disabled (which is default), the search filter **man* returns all records that contain the text man, regardless of the case.

shouldn't the text be changed to (one of two * changed to @)

If the setting is disabled (which is default), the search filter *@man* returns all records that contain the text man, regardless of the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e77b5afc-fe2d-56f9-2418-07d17da7a3d8
* Version Independent ID: a1a9791c-0112-6579-8eef-906ef110a82b
* Content: [Dynamics NAV Server Configuration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/configuring-microsoft-dynamics-nav-server)
* Content Source: [dynamics-nav/Configuring-Microsoft-Dynamics-NAV-Server.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Configuring-Microsoft-Dynamics-NAV-Server.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! Yes, the content was wrong. I have tested this out and rewritten the help to be (note this will go live in a few days):

Specifies how the quick filter on pages works for plain text search filters (that is, filters that do not use search symbols like @ or *).

If you enable this setting, the quick filter uses a case sensitive and accent sensitive search to find fields that start with the provided filter text. For example, the search filter man returns all records that include a field that starts with man (with a lowercase m), and the search for Man returns all records that include a field that starts with Man (with an uppercase M). Notice that you can get the same results by entering man* and Man* respectively.

If the setting is disabled (which is default), the search filters man and Man return the same results, which is all records that include fields that contain the text man, regardless of the case.
