### ISSUE TITLE
Can this Migrating Tables and Fields Between Extensions be possible in future for SAAS?

### ISSUE THREAD

**Issue by krishnaGottuparthi** [MicrosoftDocs/dynamics365smb-devitpro-pb#2150]
We have 40 plus apps in SAAS(apps are already in market place) which extend different standard tables.
To improve performance, we want to migrate table extensions under one app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d45b661-4242-0aad-92f2-91a2062358f3
* Version Independent ID: 3e356cf3-5e09-6881-9a7a-a92233b5f8b2
* Content: [Migrating Tables and Fields Between Extensions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-table-fields)
* Content Source: [dev-itpro/developer/devenv-migrate-table-fields.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-migrate-table-fields.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by dnpb** [comment]
It seems more a question/request for BC Ideas than an issue with the documentation.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
