### ISSUE TITLE
Version not sepified

### ISSUE THREAD

**Issue by ReneGubler** [MicrosoftDocs/dynamics365smb-devitpro-pb#2156]
Could you please specify whicht NAV/BC versions support the bclicense file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f550935-9732-f48a-f6c2-f0b05b0b79ee
* Version Independent ID: cf804858-80b8-b10b-208e-5c35dd837b32
* Content: [Upload the License File - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/cside/cside-upload-license-file)
* Content Source: [dev-itpro/cside/cside-upload-license-file.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/cside/cside-upload-license-file.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

The current supported versions are for only Business Central versions 17 and later, starting with the November updates:  17.12, 18.7, 19.1. We've included this info in the article. The update will be published soon. Thanks for the feedback!
