### ISSUE TITLE
Following best readability practices

### ISSUE THREAD

**Issue by ashirokikh** [MicrosoftDocs/dynamics365smb-devitpro-pb#2158]
Hi Folks,

The code samples in the article do not follow the best practices in terms of the begin-end block usage. Please consider updating them in accordance with this [Begin-End - Compound Only](https://alguidelines.dev/bcbestpractices/readability/begin-end/)

![image](https://user-images.githubusercontent.com/17916422/147009307-875304cd-08d8-46c0-b08a-c46f06632dd9.png)

Kind regards,
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c04d0987-98cd-f11e-eb8c-432515b70507
* Version Independent ID: 41ad0925-d71c-da6a-6691-5cb6a50f3702
* Content: [Record.FindSet(\[Boolean\] \[, Boolean\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central//dev-itpro/developer/methods-auto/record/record-findset-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-findset-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-findset-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this! This will be fixed with the next doc refresh.
