### ISSUE TITLE
What is the scope of the marks?

### ISSUE THREAD

**Issue by wolterOnEntocare** [MicrosoftDocs/dynamics365smb-devitpro-pb#2165]
[Enter feedback here]
What is the scope of the marks that are made?
Does each Record instance only see the marks that it made itself, or does it see marks made by other instances?
Are the marks persistent like an extra yes/no column in the table? Or are they e.g. local to a certain user of to... whatever?
It's easy to write a test to find it out, but it's less work if the docs tell me. Knowing the scope makes possible the decision when to use this feature.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c5dbc52-9925-14e5-c9f3-5fafa3ccdec3
* Version Independent ID: 632decfa-ced4-9e06-2b80-ee1b645d5437
* Content: [Record.Mark(\[Boolean\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-mark-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-mark-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-mark-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. With the next doc refresh the topic will be updated with some examples and a bit more explanation: The mark on a record is temporary, and disappears when the current session ends. The Mark method is valid for the specific record instance/variable, and not shared between all variables of the same record type in a session.
Thanks!
