### ISSUE TITLE
Salesline API documentation

### ISSUE THREAD

**Issue by ingebruvik** [MicrosoftDocs/dynamics365smb-devitpro-pb#2166]
[Enter feedback here]
You should specify that the shippedQuantity and invoiceQuantity  are read only fields.
It is specified for a lot of other fields on the sales line documentation but not for these two fields. Would really be helpful to people that use the API but are not so familiar with the whole Business Central functional side.
Kind regards
Inge M. Bruvik
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc8cf904-b908-d126-4f24-7fd314f84da2
* Version Independent ID: 475e4a2a-945b-91e3-eeb6-4b6fe1808a85
* Content: [salesOrderLine resource type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/resources/dynamics_salesorderline)
* Content Source: [dev-itpro/api-reference/v2.0/resources/dynamics_salesorderline.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/resources/dynamics_salesorderline.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
