### ISSUE TITLE
Reference to GoDaddy should be removed, because they will no longer offer Code Signing Certificates

### ISSUE THREAD

**Issue by sd484** [MicrosoftDocs/dynamics365smb-devitpro-pb#2167]
Starting June 1st, 2021 GoDaddy will no longer offer/ issue Code Signing Certificates. This reference should be removed.
Source: https://de.godaddy.com/help/request-code-or-driver-signing-certificates-4777?lc=en-US

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21426684-ae01-f266-f21c-065bb2499692
* Version Independent ID: c8058293-0160-a4cf-6706-f904349eb194
* Content: [Signing an APP Package File - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sign-extension)
* Content Source: [dev-itpro/developer/devenv-sign-extension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-sign-extension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be updated with the next refresh.
