### ISSUE TITLE
Certificate Thumbprint - wrong default value

### ISSUE THREAD

**Issue by ClausHamann** [MicrosoftDocs/dynamics365smb-devitpro-pb#217]
Default: WarnClient 
This is wrong. Default should be blank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e77b5afc-fe2d-56f9-2418-07d17da7a3d8
* Version Independent ID: a1a9791c-0112-6579-8eef-906ef110a82b
* Content: [Dynamics NAV Server Configuration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/configuring-microsoft-dynamics-nav-server)
* Content Source: [dynamics-nav/Configuring-Microsoft-Dynamics-NAV-Server.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Configuring-Microsoft-Dynamics-NAV-Server.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and the update will be published soon.
