### ISSUE TITLE
The page suggests deprecated feature

### ISSUE THREAD

**Issue by momoto** [MicrosoftDocs/dynamics365smb-devitpro-pb#2170]
The page suggests deprecated feature [Web Service Access Keys (Basic Auth)](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-features-platform#accesskeys). I believe that it should mention that Web Service Access Key will remain for on-premises at least. See screenshot below:

![image](https://user-images.githubusercontent.com/836856/148155319-8fb89d63-102f-40b8-a9ae-b7ea531164f4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be updated with this info with the next doc refresh. Thanks!
