### ISSUE TITLE
Editable Property documentation has invalid/illogical code/fields

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2179]
This line:

> The Boolean field on the page can be either a true/false Boolean or a Boolean expression, such as "Credit Limit > Sales YTD".

This `"Credit Limit > Sales YTD"` is not valid AL code and does not refer to any fields that exist on the Customer table, which was presumably the idea. It also does not seem to make much sense logically, even if it were valid syntactically? It should be something like

    "Balance Due (LCY)" > "Credit Limit (LCY)"

and maybe mention 'as an example for a page showing the Customer table'.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd6c70d-7fef-0f5a-1a0b-37f102b853f5
* Version Independent ID: f5637137-69b3-9b33-1ba6-786ace43bf90
* Content: [Editable Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-editable-property)
* Content Source: [dev-itpro/developer/properties/devenv-editable-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-editable-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next update of the docs.
