### ISSUE TITLE
Editable Property documentation should clarify that dynamic expressions only work on Pages, not on Tables

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2180]
While some of us 'just know' this, other developers do not; see e.g. https://github.com/microsoft/AL/issues/6881

It says:
> The Boolean field on the page can be either a true/false Boolean or a Boolean expression, such as "Credit Limit > Sales YTD".

I opened https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2179 for the syntactical/logical problems with that example code. But...

I think to avoid issues like the above being filed with the compiler, it would be worth clearly stating that tables do not support  dynamic expressions or InDataSet Booleans or whatever - only literal/constant values.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd6c70d-7fef-0f5a-1a0b-37f102b853f5
* Version Independent ID: f5637137-69b3-9b33-1ba6-786ace43bf90
* Content: [Editable Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-editable-property)
* Content Source: [dev-itpro/developer/properties/devenv-editable-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-editable-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next update of the docs.
