### ISSUE TITLE
Default Value of AssignmentCompatibility

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-devitpro-pb#2182]
Please add the default value of AssignmentCompatibility.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd74208b-3dde-5caf-7697-57354c9c19e8
* Version Independent ID: aec6243a-dc7f-94a9-598c-72fe4617d7ae
* Content: [AssignmentCompatibility Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-assignmentcompatibility-property)
* Content Source: [dev-itpro/developer/properties/devenv-assignmentcompatibility-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-assignmentcompatibility-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The default value of this property is false. The topic will be updated with the next doc refresh. Thanks.
