### ISSUE TITLE
POST a new image to associate with an existing item.

### ISSUE THREAD

**Issue by gregarican** [MicrosoftDocs/dynamics365smb-devitpro-pb#2183]
So I found this page --> https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_item_create_picture.md. Without a basic example of the request body I'm unsure if this particular API endpoint accomplishes what I'm looking to do. Which is importing in a new image to be associated with an existing item. 

Is the request body looking for something along the lines of **Content-Type: image/jpeg** with a Base64-encoded **Content** block representing the image itself? @SusanneWindfeldPedersen can you provide any insight? Thanks!

**Comment by gregarican** [comment]
For something concrete, here is what I attempted. POST to http://ls-test01:9048/LSCentral/ODataV4/Company('CRONUS%20-%20LS%20Central')/items(d2c4bcd9-186f-ec11-9fdb-000c29b1037b)/picture. Where the items GUID represents an existing item. In my JSON request body I passed along:

`{
    "Content-Type": "image/jpeg",
    "Content": "data:image/jpeg;base64,/9j/4...
}`

Where I am just truncating the long Base64-encoded image text string for brevity here. After sending off this request, the response was:

`{
    "error": {
        "code": "BadRequest_NotFound",
        "message": "The URI segment 'picture' is invalid after the segment 'items(d2c4bcd9-186f-ec11-9fdb-000c29b1037b)'.  CorrelationId:  e13ead82-233e-40ed-b205-0d17d8d4b67c."
    }
}`

I know I'm probably amiss in terms of the JSON request body, but I figure I also might need to configure something on the server end in order to expose this picture URI endpoint.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We have just refreshed this topic with some more information, can you please check and see if that helps answer your question. Please find it right here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_item_create_picture

**Comment by gregarican** [comment]
Great! This makes it very clear. Thank you very much.
