### ISSUE TITLE
Editable logic seems reversed

### ISSUE THREAD

**Issue by AskeHolst** [MicrosoftDocs/dynamics365smb-devitpro-pb#2184]
The note about CurrPage.Editable states "If the page is editable, then CurrPage.Editable will return false."
Is it not the other way around? 
"If the page is **not** editable, then CurrPage.Editable will return false."
or
"If the page is editable, then CurrPage.Editable will return true."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd6c70d-7fef-0f5a-1a0b-37f102b853f5
* Version Independent ID: f5637137-69b3-9b33-1ba6-786ace43bf90
* Content: [Editable Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-editable-property)
* Content Source: [dev-itpro/developer/properties/devenv-editable-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-editable-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this! You're absolutely right - very important omission of 'not' here. This will be fixed with the next refresh of the docs.
