### ISSUE TITLE
"DataItemLink property (Query)" has missing quotes around column name

### ISSUE THREAD

**Issue by db0451** [MicrosoftDocs/dynamics365smb-devitpro-pb#2186]
> `DataItemLink = Salesperson Code=Salesperson.Code`

That won't compile. It should be

> `DataItemLink = "Salesperson Code" = Salesperson.Code`

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9a6f19-33c6-87a1-b9a9-8d7a96f3dacd
* Version Independent ID: 5703128f-f364-5cba-577d-a2f201110bb9
* Content: [DataItemLink Property (Query) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-dataitemlink-query-property)
* Content Source: [dev-itpro/developer/properties/devenv-dataitemlink-query-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-dataitemlink-query-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
