### ISSUE TITLE
Lacking in the finer details to be usefull

### ISSUE THREAD

**Issue by PhilDOakley** [MicrosoftDocs/dynamics365smb-devitpro-pb#2187]
Given the complexities of this process the doc  needs more finer detail in the steps to be a stand alone documnet. The statements like
"Start Business Central Administration Shell for your current version as an administrator" does not help when the new version 19 has been installed and the links default to the v19 tools which do not work! What is needed is a note of where and how to run the previous versions admin without the reader having to resort to digging into the file system or google.
Disapointing as MS really need to do a better job on the docs 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c4713aa-6a18-32d4-2f34-be03e3cc87a5
* Version Independent ID: 398a09ff-fe8b-ba2d-18c8-31b2f84a87e8
* Content: [Upgrading Version 15, 16, 17, or 18 Base Application to Version 19 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v19)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v19.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v19.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
We've updated the article and others with a link to a new section about the different ways to start the Administration Shell. The update will be published soon. Thanks for the valuable feedback!
