### ISSUE TITLE
Where is at least a link to an exampe

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#219]
How about a report walk through that uses an Integer table and explains how to use it properly? I have googled many times and everyone just assumes that you know how to use an integer table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 080aceef-caef-350a-2286-216b86015296
* Version Independent ID: f1425196-8f17-77aa-2932-6d8c1120ffd9
* Content: [Integer Virtual Table - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/integer-virtual-table)
* Content Source: [dynamics-nav/Integer-Virtual-Table.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Integer-Virtual-Table.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We will consider this for a future topic, but we would want to include it for our Business Central solution. Thanks again.
