### ISSUE TITLE
Mark BC available in Ukraine on the "Countries and languages" page

### ISSUE THREAD

**Issue by sergeyol** [MicrosoftDocs/dynamics365smb-devitpro-pb#2190]
Business Central is available in Ukraine since 19.1. Please change its status from "Planned" to "Available".

Ukrainian language pack is also [available ](https://appsource.microsoft.com/en-us/product/dynamics-365-business-central/PUBID.smart-businessllc2412077-2412077%7CAID.sol-63175-dbg%7CPAPPID.818e1730-0293-45fe-a59f-37588a0a15df)on AppSource, so uk-UA language should be marked as supported.

Pull request is created: #2189 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 360d9409-840a-5ef9-9aa4-b43ed4733e2c
* Version Independent ID: 961502fa-6d30-47fa-8afe-a15a8e521304
* Content: [Country/region availability and supported languages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations)
* Content Source: [dev-itpro/compliance/apptest-countries-and-translations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/compliance/apptest-countries-and-translations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Thank you for your contribution. I have merged your pull request, and the updated article will be part of our next doc update.

**Comment by edupont04** [comment]
Now live.
