### ISSUE TITLE
Improper wordings

### ISSUE THREAD

**Issue by ajaysankard07** [MicrosoftDocs/dynamics365smb-devitpro-pb#2192]
[Enter feedback here]

The words are placed and referenced improperly. For example: The document uses "They" instead of "The", the code snippet has a value defined and used ad 50100 but the document references it as 5100.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8ce13e2-a6d0-8ede-5aad-49512102bba0
* Version Independent ID: a6ab37aa-aae7-d034-1d46-4512347aa00f
* Content: [Walkthrough: Implementing New Workflow Events and Responses - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-walkthrough-workflow-events-responses)
* Content Source: [dev-itpro/developer/devenv-walkthrough-workflow-events-responses.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-walkthrough-workflow-events-responses.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next doc refresh.
