### ISSUE TITLE
Inclusive language

### ISSUE THREAD

**Issue by potatoqualitee** [MicrosoftDocs/dynamics365smb-devitpro-pb#2194]
Please change all instances of `he` to `they`. It's not only easier to read, but more inclusive.

```
On the other hand, if someone gained access to the drive via a network a share or other services that share data from the drive, he could copy data 
```
becomes
```
On the other hand, if someone gained access to the drive via a network a share or other services that share data from the drive, they could copy data 
```

And 
```
But if the attacker gains access to the whole drive, including SQL Server, he can start SQL Server and read the data using SQL
```
becomes
```
But if the attacker gains access to the whole drive, including SQL Server, they can start SQL Server and read the data using SQL
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e3407c-a7dc-c090-46d9-bf71f660b1de
* Version Independent ID: 1451cc79-ff38-5b78-78dc-4160c57ead32
* Content: [Data Encryption at Rest, Transparent Data Encryption (TDE) and BitLocker - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/security/transparent-data-encryption)
* Content Source: [dev-itpro/security/transparent-data-encryption.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/security/transparent-data-encryption.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **kepontop**

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback! We've changed the article as suggested. The update will be published soon.
