### ISSUE TITLE
Where are the possible page types defined?

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [MicrosoftDocs/dynamics365smb-devitpro-pb#22]
VS Code will give me a listing of the possible values, but where can I find any documentation that tells me what each type of page is?  As an example, what is the difference between "ConfirmationDialogue" and "StandardDialogue".  I can experiment, but I'd rather see an explanation for each possible value in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef98d5c-2b0f-10b5-1a60-e2af044b6e0b
* Version Independent ID: 3661238e-a728-345d-1c1c-e0ed66606cdf
* Content: [PageType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-pagetype-property)
* Content Source: [dev-itpro/developer/properties/devenv-pagetype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-pagetype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We forgot to include the page overview in the table of contents for discoverability, so I have fixed that with the next refresh of the docs. In the meantime, please visit this page: [Pages Overview](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-pages-overview). Over the next time we'll be focusing on adding more information about how to build, for example, pages. Thanks again for your feedback.
