### ISSUE TITLE
Event Subscriber OnAfterValidateEvent uses var-Parameter

### ISSUE THREAD

**Issue by GuntherGebauer** [MicrosoftDocs/dynamics365smb-devitpro-pb#2200]
[Enter feedback here]
local procedure MyProcedure(Rec: Record; xRec: Record; CurrFieldNo: Integer) is wrong, the parameters to the record ar var-Parameters:

local procedure MyProcedure(var Rec: Record; var xRec: Record; CurrFieldNo: Integer)

Same for 
[EventSubscriber(ObjectType::Table, Database::<Table Name>, 'OnAfterModifyEvent', '', <SkipOnMissingLicense>, <SkipOnMissingPermission>)]
local procedure MyProcedure(Rec: Record; xRec: Record; RunTrigger: Boolean) 

should be 
local procedure MyProcedure(var Rec: Record; var xRec: Record; RunTrigger: Boolean) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7bc750-6cb2-23af-137b-47099fb7b290
* Version Independent ID: 543da9dd-2024-7f82-309d-573634f51cfb
* Content: [OnAfterValidateEvent (Table) Trigger Event - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/events/table/devenv-onaftervalidateevent-table-trigger)
* Content Source: [dev-itpro/developer/triggers-auto/events/table/devenv-onaftervalidateevent-table-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/triggers-auto/events/table/devenv-onaftervalidateevent-table-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this. It has been fixed and will be available with the next refresh.

**Comment by SusanneWindfeldPedersen** [comment]
This is fixed and pushed live. Thanks for the feedback.
