### ISSUE TITLE
Typo on Page Walkthrough: Implementing New Workflow Events and Responses

### ISSUE THREAD

**Issue by eapomazkov** [MicrosoftDocs/dynamics365smb-devitpro-pb#2205]
Hi!

Step 2 of section 'To create a workflow event code that identifies the workflow event' describes creating a regular AL procedure but it is suggested to use snippet **teventint** which actually creates an integration event.

So the correct sentence should be:
Optionally, use the shortcut **tprocedure**.

There is also a typo in the To subscribe to the event and implement the workflow event section:
Go back to the MyWorkflowEvents.codeunit.al **file file** and...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8ce13e2-a6d0-8ede-5aad-49512102bba0
* Version Independent ID: a6ab37aa-aae7-d034-1d46-4512347aa00f
* Content: [Walkthrough: Implementing New Workflow Events and Responses - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-walkthrough-workflow-events-responses)
* Content Source: [dev-itpro/developer/devenv-walkthrough-workflow-events-responses.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-walkthrough-workflow-events-responses.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
