### ISSUE TITLE
Wrong Signature for Events

### ISSUE THREAD

**Issue by chrischbo** [MicrosoftDocs/dynamics365smb-devitpro-pb#2209]
Hi,
the signature of the procedures is in most cases incorrect. The var Parameter is missing (for example on the OnAfterValidateEvent and so on).

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 256aabb4-8d5d-cc06-6c1f-5558c668491b
* Version Independent ID: 51d1427c-130d-b5c0-3d04-89c01caa89f8
* Content: [Event Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-event-types)
* Content Source: [dev-itpro/developer/devenv-event-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-event-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this, it will be fixed with the next doc refresh.
