### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#222]
"The following figure illustrates the general layout and elements of a list page."
should be 
"The following figure illustrates the general layout and elements of a card or document page."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f45d21ea-f6e1-0439-967f-8f9124c6977b
* Version Independent ID: 9696b739-1e59-56b2-bb44-bb6c98e5e1ad
* Content: [Designing Card Pages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-card-pages?tabs=structure)
* Content Source: [dev-itpro/developer/devenv-designing-card-pages.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-designing-card-pages.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! An update to the article will be published soon.
