### ISSUE TITLE
I get: {'error': {'code': 'BadRequest',   'message': "An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected.  CorrelationId:  abf55a01-42e7-40c5-884d-59ccc790e312."}}

### ISSUE THREAD

**Issue by gbrault** [MicrosoftDocs/dynamics365smb-devitpro-pb#2221]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74270a57-78cf-d98a-d640-725f6740be26
* Version Independent ID: cb3f681d-baef-b0be-a828-45c7edfcde40
* Content: [Create customers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_customer_create)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_customer_create.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_customer_create.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. Please use your usual support channel for help with this issue. Thanks.
