### ISSUE TITLE
Two runtime versions specified

### ISSUE THREAD

**Issue by mattkeyeswc** [MicrosoftDocs/dynamics365smb-devitpro-pb#2224]
Not a huge deal, but this page shows conflicting runtime versions:

_Version: Available or changed with runtime version 3.0.

Provides a structure for grouping information about an error. Supported for Business Central online from runtime 8.0._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91556dde-f5bb-9e01-b341-008100ed7638
* Version Independent ID: 7e7e6576-0068-2766-2acd-32085ebd08c8
* Content: [ErrorInfo Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/errorinfo/errorinfo-data-type)
* Content Source: [dev-itpro/developer/methods-auto/errorinfo/errorinfo-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/errorinfo/errorinfo-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. I believe this is because the ErrorInfo data type has been around since version 3.0, but the collectible part of error handling is introduced with runtime 8.0 - I agree this can be confusing. I will file a bug on this. Thanks

**Comment by SusanneWindfeldPedersen** [comment]
This is fixed with the recent doc refresh. Thanks.
