### ISSUE TITLE
Execution of Installer Codeunit

### ISSUE THREAD

**Issue by mitrov** [MicrosoftDocs/dynamics365smb-devitpro-pb#2227]
Based on this article it's not very clear when a "Installer Codeunit" is actually executed.

If I'm not mistaken, when an app gets an update with a new version ... the old version is uninstalled and the new version is installed. In this case the installer codeunit is not executed. For that scenario only upgrade codeunits are executed.
But the code example in this doc suggests that the installer codeunit can handle fresh installations and also reinstallations.

I was a bit surprised by this behaviour. As a user I expect that an installation of an app always runs through some installer code and makes sure that important base data is always there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dd7c9e-51a5-eeea-a2f6-dd4d40b93295
* Version Independent ID: d6fb1d1b-fa2e-606e-6c79-115651b60a29
* Content: [Writing extensions installation code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-install-code)
* Content Source: [dev-itpro/developer/devenv-extension-install-code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-extension-install-code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback!

We've updated the article in hopes of making this more clear.

Install code is run only when an extension version is first installed or reinstalled by running the Install-NAVApp cmdlet or from the **Extension Management** page in the client. Install code isn't run when a new version of an existing extension is installed as part the upgrade operation using the Start-NAVAppDataUgrade cmdlet.

The update will be available soon.
