### ISSUE TITLE
Register the console application in the Azure AD tenant - Step 2

### ISSUE THREAD

**Issue by carlkitching** [MicrosoftDocs/dynamics365smb-devitpro-pb#2228]
Should be something more like:

Grant the console application delegated permissions to the Business Central application.

Select API Permissions > Add a permission > Select APIs my organization uses.
Search for and select the Business Central application,
Select Delegated Permissions, tick the required permissions and select Add permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11619df3-eda7-a534-74c6-8199e8d0dd90
* Version Independent ID: 788d6906-d248-0483-1bcd-33e67e977445
* Content: [Using OAuth to Authenticate Business Central Web Services (OData and SOAP) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/authenticate-web-services-using-oauth)
* Content Source: [dev-itpro/webservices/authenticate-web-services-using-oauth.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/webservices/authenticate-web-services-using-oauth.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
We've made the suggested changes. The updated article will be published soon. Thanks!
