### ISSUE TITLE
Apply to Business Central

### ISSUE THREAD

**Issue by JeffLoucksPersonal** [MicrosoftDocs/dynamics365smb-devitpro-pb#223]
This article appears to need an update for information that may be different as it relates to Business Central. Please provide guidance as to what products this article applies and if the process is the same or different for Business Central. Is this CDS 2.0 or 1.0? If not 2.0 what is the 2.0 process. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cc6e64e-b32e-2b8a-30a1-659a811497a5
* Version Independent ID: 374df32b-2fea-8167-3381-64002cc0d093
* Content: [Setting Up Dynamics 365 for Sales Integration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/setting-up-dynamics-crm-integration)
* Content Source: [dynamics-nav/Setting-Up-Dynamics-CRM-Integration.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Setting-Up-Dynamics-CRM-Integration.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article pertains to Dynamics NAV 2018, not Business Central. For Business Central, you can see this [Preparing Dynamics 365 for Sales for Integration](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration). We will be working on an update to this content.

As for CDS, our integration with Sales currently does not use CDS, only the CRM SDK. I hope this helps.
