### ISSUE TITLE
Incorrect example URL(s)

### ISSUE THREAD

**Issue by martip** [MicrosoftDocs/dynamics365smb-devitpro-pb#2231]
The URL for getting the shipment lines related to a specific shipment is not correct.

Wrong:
`GET businesscentralPrefix/companies({id})/salesShipmentLines({id})/salesShipmentLines({salesShipmentLineId})`

Correct:
`GET businesscentralPrefix/companies({id})/salesShipments({id})/salesShipmentLines({salesShipmentLineId})`

Hope it helps!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5054013-73f7-db07-e7d4-24e2203fceee
* Version Independent ID: b108e33e-7b81-9914-bed0-6356ad9f97de
* Content: [GET salesShipmentLines - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_salesshipmentline_get)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_salesshipmentline_get.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_salesshipmentline_get.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
