### ISSUE TITLE
Wrong paratmer in the request 

### ISSUE THREAD

**Issue by vremeni4** [MicrosoftDocs/dynamics365smb-devitpro-pb#2235]
[Enter feedback here]
The link given on the website 
GET businesscentralPrefix/companies({id})/attachments$filter=parentId eq {journalLineId} and parentType eq ‘Journal’

is incorrect.
The correct one is 
GET businesscentralPrefix/companies({id})/attachments?$filter=parentId eq {journalLineId} and parentType eq ‘Journal’

So there is ? before $ 

Alos the one in the example 
GET https://{businesscentralPrefix}/api/v1.0/companies({id})/attachments$filter=parentId eq {journalLineId}

is incorrect it shoudl be 
GET https://{businesscentralPrefix}/api/v1.0/companies({id})/attachments?$filter=parentId eq {journalLineId}

so again there is ? before $ 
If called with out ? the error message is 

No HTTP resource was found that matches the request URI

It would be nice if someone could update the website and correct this 
---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f266f4-356e-5ecc-224f-1efac6bbb9a2
* Version Independent ID: 1b3eb625-850c-a817-5d19-41cf4c8e295b
* Content: [GET attachments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_attachment_get)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_attachment_get.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_attachment_get.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
