### ISSUE TITLE
Sync-NavApp Error with Base Application 19.0 - 19.3

### ISSUE THREAD

**Issue by VISIONDATAGMBH** [MicrosoftDocs/dynamics365smb-devitpro-pb#2237]
Hello!

I am currently trying to upgrade a customer's system from BC19.0 to 19.3.
During the sync from the Base Application the following error occurs:

Sync-NAVApp -ServerInstance BC193 -Name "Base Application" -Version 19.3.34541.35002

Sync-NAVApp : Table Exchange Contact :: The table "Exchange Contact" was not found. Removal of tables is not allowed, unless they are temporary or they are removed
moved to another app during a migration process.
Table Booking Service :: The table "Booking Service" was not found. Removing tables is not allowed unless they are temporary or are moved to another app during a migration operation.
moved to another app during a migration process.
Table Booking Mailbox :: The table "Booking Mailbox" was not found. Removing tables is not allowed unless they are temporary or are moved to another app during a migration operation.
moved to another app during a migration process.
Table Booking Staff :: The table "Booking Staff" was not found. Removing tables is not allowed unless they are temporary or are moved to another app during a migration operation.
moved to another app during a migration process.
Table Booking Item :: The table "Booking Item" was not found. Removing tables is not allowed unless they are temporary or are moved to another app during a migration operation.
moved to another app during a migration operation.

The same error also occurs when upgrading from 19.0 to 19.2.

I have already compared the objects in Base 19.0 and 19.3. They are identical.
The only thing I noticed is that the tables are from type = Exchange, Microsoft Graph...

Does anyone know the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8631cba-07bc-2fe1-eefb-ab5e26353212
* Version Independent ID: e864d2ca-5a2e-f74e-41ed-1cfce5f53961
* Content: [Install a version 9 update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v19)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v19.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrading-cumulative-update-v19.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by dnpb** [comment]
Not sure the specific issue is on-topic as it seems more like support, but... saying that

![image](https://user-images.githubusercontent.com/63455896/154240456-4da36120-b696-42b9-ae7b-28adf955729a.png)

Shouldn't that be "version 19", not "version 9"?

**Comment by jswymer** [comment]
Hello,

I've recently tested the article on a couple builds going from 19.0 to 19.2 and 19.3. I was using the W1 package. I didn't run into the same problem. I would recommend contacting support, sorry. If there's a doc update, they'll let us know. 

On a side note, I changed the version from "9" to "19" (thanks dnpb).
