### ISSUE TITLE
Missing example for using in code

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#224]
Hello, there is no example how to address the specific enum value in code, e.g. in Case statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd55bfe-2599-257c-fe83-6c5c7d90b04b
* Version Independent ID: 60ac2b4a-d10a-5e8c-d2e7-ac380943cd0b
* Content: [Extensible Enums - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)
* Content Source: [dev-itpro/developer/devenv-extensible-enums.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extensible-enums.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. This is definitely missing and I will include a codeunit example in the docs for how to address a specific enum value. The docs will be updated soon, but for your reference this is the example below. Thanks again.

codeunit 50140 EnumUsage
{
    procedure Foo(p: enum Loyalty)
    var
        LoyaltyLevel: enum Loyalty;
    begin
        if p = p::Gold then begin
            LoyaltyLevel := p;
        end;
    end;
}
