### ISSUE TITLE
can we get links to example usage in AL

### ISSUE THREAD

**Issue by grantbrimhall** [MicrosoftDocs/dynamics365smb-devitpro-pb#2247]
Hi:

where can we find sample AL code to use (for example) PDF417? those would be very helpful links on this page.

thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32480258-f5bd-15ac-474e-47971b800d2e
* Version Independent ID: 75dafb69-4482-ed6c-6e6e-eb799c4b7a25
* Content: [Barcode Fonts with Business Central Online - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-barcode-fonts)
* Content Source: [dev-itpro/developer/devenv-report-barcode-fonts.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-report-barcode-fonts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

We've made some updates to the article. We hope this helps. Thanks for the feedback!
