### ISSUE TITLE
HTTP, JSON, TextBuilder, and XML API Overview has typo "HttpReponseMessage" instead of HttpResponseMessage

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2253]
Title says it all :-)

![image](https://user-images.githubusercontent.com/63455896/155302419-1a1dc45b-b81b-4dc4-bc91-81e6ffd32418.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba420104-eccf-1d8a-17d9-1dc53f16ca7b
* Version Independent ID: 56e40a99-25db-1e13-c436-c5794c6f69aa
* Content: [HTTP, JSON, TextBuilder, and XML API Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-restapi-overview)
* Content Source: [dev-itpro/developer/devenv-restapi-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-restapi-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, will be fixed with the next doc refresh.
