### ISSUE TITLE
What happens when al.snapshotOutputPath is blank?

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2256]
I don't have any of the snapshot settings configured, so al.snapshotOutputPath is blank.
Somehow vs code believes that I currently have a snapshot session.
https://i.imgur.com/jDHQgU8.png
I don't have a .snapshot folder. I don't use snapshot debugging (have the shortcuts disabled).

I'm at a loss as to where this snapshot is, or how I can remove it. The article doesn't give me any clear direction for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc5e406-d2a3-14dd-7399-92e7df9707a2
* Version Independent ID: 2f75dceb-4b27-fa4f-60d2-f797175c8da0
* Content: [Snapshot Debugging - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-snapshot-debugging)
* Content Source: [dev-itpro/developer/devenv-snapshot-debugging.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-snapshot-debugging.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by kalberes** [comment]
1. Do you have a workspace/folder settings set somewhere for the al.snapshotOutputPath?
2. Do you have anything in your default .snapshots folder?

**Comment by mjmatthiesen** [comment]
> 1. Do you have a workspace/folder settings set somewhere for the al.snapshotOutputPath?
The only setting that I have is in my general vscode settings.json (the one in user/appdata/roaming/.../code/...):
"al.snapshotDebuggingPath": "",
"al.snapshotOutputPath": "",
There are no specific settings for this project.

> 2. Do you have anything in your default .snapshots folder, the default, if the settings is not set ?
There's no default folder, unless you mean the one above. The snapshot folders aren't even being created in the projects.

**Comment by kalberes** [comment]
I do not know than how you can get that info without debugging your environment. Do you by any chance have a snapshots,json file lying in your workspace cone (all folders of your workspace root directory)

**Comment by mjmatthiesen** [comment]
Hi Kalman, I accidentally figured it out. In the project I built the app, then made a zip of said app. That zip file in the root is recognized as a snapshot.

I don't know what snapshot files look like as I don't have experience with them / haven't needed them.

Anyway, that solves the mystery for me.
