### ISSUE TITLE
Is copy complete or shallow

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#2265]
Could you please add if a copy of a list is shallow or a complete copy?
Ex. 
List1 = {1,2,3}
List2 := List1

Shallow
List1.add(4)  =>   List2 = List1 = {1,2,3,4}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c760a1-0ba5-814b-94bf-c50008364769
* Version Independent ID: 235f987b-1062-26ba-81a7-b72ff35c099b
* Content: [List Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/list/list-data-type)
* Content Source: [dev-itpro/developer/methods-auto/list/list-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/list/list-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question - this is defined in the compiler and it's using shallow copy. We will update the topic with the next doc refresh. Thanks.
