### ISSUE TITLE
Filter syntax is wrong

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#227]
The syntax in section "Filtering Data on the Page" is described as
&filter='&lt;field&gt;'-IS-'&lt;value&gt;'[-AND-'&lt;field&gt;'-IS-'&lt;value&gt;']  

but it is in reality

&filter='&lt;field&gt;' IS '&lt;value&gt;'[ AND '&lt;field&gt;' IS '&lt;value&gt;']  

There is no mentioned that '-' are space in reality. Using -AND- and -IS- is not working...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f33556-5071-49c4-f035-b731c1b27274
* Version Independent ID: 73b81c02-b93b-2e86-18b8-91c66234f590
* Content: [Opening a Page in the Microsoft Dynamics NAV Web Client by Using a URL - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/opening-a-page-in-the-microsoft-dynamics-nav-web-client-by-using-a-url)
* Content Source: [dynamics-nav/Opening-a-Page-in-the-Microsoft-Dynamics-NAV-Web-Client-by-Using-a-URL.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Opening-a-Page-in-the-Microsoft-Dynamics-NAV-Web-Client-by-Using-a-URL.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
