### ISSUE TITLE
Version 19 is missing from this page..

### ISSUE THREAD

**Issue by albgen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2274]
[Enter feedback here]
Version 19 is missing from this page..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ad2a569-9830-92a8-300a-3ddd2c38d86c
* Version Independent ID: bbe7bdcf-76bd-48a3-38f6-67317cb61bd2
* Content: [Version numbers in Business Central and what they mean - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/version-numbers)
* Content Source: [dev-itpro/administration/version-numbers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/version-numbers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Oops, you're right. We'll get that fixed in the next doc update.

**Comment by edupont04** [comment]
Fixed a month ago.
