### ISSUE TITLE
Copy From api1.0 so most things on the page are wrong as api2.0 works differntly 

### ISSUE THREAD

**Issue by vremeni4** [MicrosoftDocs/dynamics365smb-devitpro-pb#2276]
This page seems to be a copy from the same page for API1.0
The problem is that API2.0 works differently, so example is wrong, If-match was not explained and it is wrong.   

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb6e97a2-7b0d-71c5-2104-d6705dfcab79
* Version Independent ID: 41270478-54a9-cb6d-a1e6-0fc1d7115835
* Content: [Upload attachment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_attachment_update)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_attachment_update.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_attachment_update.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by christianbraeunlich** [comment]
Only after opening the PR https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/pull/2293 I found this Issue already existing. It confused me that there are quite a few things that were missing as already mentioned by @vremeni4.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the contribution. Will be pushed live with next doc refresh.
