### ISSUE TITLE
Typo and dead link.

### ISSUE THREAD

**Issue by DavidRoys** [MicrosoftDocs/dynamics365smb-devitpro-pb#2277]
the word the should come before the word same and not after it…

You cannot deploy a Global app with same the id and version, but different content to multiple environments.

the link in this note does not exist:

The resourceExposurePolicy applies differently to DEV extensions. For more information, see Resource Exposure Policy Setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 927a5e82-106a-3afe-7fa1-eb08382f8506
* Version Independent ID: 927a5e82-106a-3afe-7fa1-eb08382f8506
* Content: [Extension Types and Scope - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-types-and-scope)
* Content Source: [dev-itpro/developer/devenv-extension-types-and-scope.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-extension-types-and-scope.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with our next doc refresh.
