### ISSUE TITLE
Numbers missing in Navigation and Actions areate

### ISSUE THREAD

**Issue by nickgoddard777** [MicrosoftDocs/dynamics365smb-devitpro-pb#2280]
In the table in the Navigation and Actions area section the No. and Area numbers are miising for the bottom three rows.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baccd8df-f503-da27-3198-07aa5a5ea6ed
* Version Independent ID: 09faac4b-946c-956d-be75-469627ecc3b5
* Content: [Designing Role Centers - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/dev-itpro/developer/devenv-designing-role-centers)
* Content Source: [dev-itpro/developer/devenv-designing-role-centers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-designing-role-centers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by dnpb** [comment]
It's because they are subordinate to the preceding row, as written:

> You can define the actions by using the three different area() controls that are described below:

**Comment by jswymer** [comment]
Thanks for the feedback, and for the answer @dnpb.

We're making a change to the article, which will hopefully make this clearer. The update will be published soon.
