### ISSUE TITLE
Why is it recommended to use odata.maxpagesize instead of $top and $skip ?

### ISSUE THREAD

**Issue by osolliec** [MicrosoftDocs/dynamics365smb-devitpro-pb#2289]
Hello ! 
On this page, there is a note that says 
```In HTTP requests, It's recommended to use the odata.maxpagesize preference instead of the system query options $top and $skip.```
It does not say why though. If there are no drawbacks, we might as well only use $top and $skip, no ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b01adb78-cee8-df80-6f1b-1f61b9c16ac7
* Version Independent ID: b2161d4e-634b-043b-be56-2dc2beb0fbf6
* Content: [Using OData with Queries That are Set with a Top Number of Rows - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-odata-with-queries-set-with-top-number-of-rows)
* Content Source: [dev-itpro/webservices/use-odata-with-queries-set-with-top-number-of-rows.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/webservices/use-odata-with-queries-set-with-top-number-of-rows.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback.

I think the statement was intended to highlight that there are benefits to using `odata.maxpagesize`. For example, `odata.maxpagesize` automatically includes `nextlink` in the response, which lets you continuously retrieve a large dataset in limited chunks. There's nothing that prohibits you from using `$top` and `$skip`. We've adjusted the statement in the article a bit. The update will be published soon. We hope it helps clear things up.
