### ISSUE TITLE
Duplicate rows?

### ISSUE THREAD

**Issue by ctatoiu** [MicrosoftDocs/dynamics365smb-devitpro-pb#229]
5th row in the table is the same as the 3rd row, is this on purpose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6699d64-e383-4de7-adb9-bfd2d8782697
* Version Independent ID: 14a447a4-6875-a1f2-f2ad-d022d52edc6c
* Content: [Multitenant Deployment Architecture - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/multitenant-deployment-architecture)
* Content Source: [dynamics-nav/Multitenant-Deployment-Architecture.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Multitenant-Deployment-Architecture.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
The third row should be yes|1|2|no. The article has been fixed and an update will be published soon. Thanks for the feedback!
