### ISSUE TITLE
Table Missing Errors in Empty Migration app

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#2290]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v19#create-the-second-version---empty

At this stage in the process, the --tableDataOnly includes tablerelations in the .AL files and these need to be removed if you are to build the APP.  Maybe note for this would help others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5883e8f6-4224-0f8d-bac8-cb66ded5dcb9
* Version Independent ID: 6a158969-21b0-2840-c8d1-d21f2e519313
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application for version 19 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v19)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app-v19.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v19.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback!

In step 3 of section **Create the second version - empty**, it states to delete all objects except: BinContentBuffer.Table.al	DocumentEntry.Table.al,	EntrySummary.Table.al, FieldContentBuffer.Table.al. Are you referring to table relations in these files?

**Comment by tscottjendev** [comment]
Yes

**Comment by jswymer** [comment]
Thanks for the help! We added this info to the article. The update will be published soon.
