### ISSUE TITLE
default parameter value missing

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-devitpro-pb#2295]
Please document default value for Ascending parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b1f445-c2d1-c84a-5b04-e13608642987
* Version Independent ID: 932b35ff-0a7d-52cc-9b6d-b59ba4e7843b
* Content: [Record.Ascending(\[Boolean\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-ascending-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-ascending-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-ascending-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The value is optional, so there is no default value. Thanks.
