### ISSUE TITLE
Missing parameter

### ISSUE THREAD

**Issue by alanb999** [MicrosoftDocs/dynamics365smb-devitpro-pb#23]
Please provide the description for the NAV service tier parameter XmlMetadataCacheSize

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e77b5afc-fe2d-56f9-2418-07d17da7a3d8
* Version Independent ID: a1a9791c-0112-6579-8eef-906ef110a82b
* Content: [Dynamics NAV Server Configuration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/configuring-microsoft-dynamics-nav-server)
* Content Source: [dynamics-nav/Configuring-Microsoft-Dynamics-NAV-Server.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Configuring-Microsoft-Dynamics-NAV-Server.md)
* Service: **unspecified**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback,

This setting is primarily for internal use now. It is in the CustomSetting.config file temporarily for backwards compatibility with older versions of Dynamics NAV, which cached metadata primarily based on XML. This has changed for newer versions, which use NCLMetadata objects that are type based.  There are no benefits of changing this setting from the default. We will eventually remove this setting from the file.

I have updated the content to indicate that this is for internal use only. This change will be available the next time we refresh the content. 

Thanks again
