### ISSUE TITLE
Upgrade to version 19 does not mention Business Central version 15

### ISSUE THREAD

**Issue by git-no** [MicrosoftDocs/dynamics365smb-devitpro-pb#2301]
Why is this upgrade procedure only for:

Business Central 2021 release wave 1 (version 18)
Business Central 2020 release wave 2 (version 17)
Business Central 2020 release wave 1 (version 16

Why does this page not mention version 15 ?
It is confusing and suggests the upgrade description is not for version 15.
More confusing, there is no extra page / description mention how to upgrade from version 15 to Business Central 19.

Can you clarify and check why version 15  and 16 upgrades to Business Central 19 are not documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c4713aa-6a18-32d4-2f34-be03e3cc87a5
* Version Independent ID: 398a09ff-fe8b-ba2d-18c8-31b2f84a87e8
* Content: [Upgrading Version 15, 16, 17, or 18 Base Application to Version 19 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v19)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v19.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v19.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback. The article can also upgrade from v15. We've changed the article to hopefully make things clear. The update will be published soon.
