### ISSUE TITLE
BC20 is not release April 2021

### ISSUE THREAD

**Issue by milamaksimovic** [MicrosoftDocs/dynamics365smb-devitpro-pb#2302]
It says on the Page "20 is the Business Central 2022 release wave 1 update in April 2021 and forward"

It should be "20 is the Business Central 2022 release wave 1 update in April 2022 and forward"

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback, but this issue is not attached to any topic. Can you elaborate on where you've found this issue? Thanks

**Comment by SusanneWindfeldPedersen** [comment]
Okay, all good - found it in our Version Numbers topic. This will be fixed with the next doc refresh. Thanks.
