### ISSUE TITLE
CU 34 incorrect link

### ISSUE THREAD

**Issue by martonnagy** [MicrosoftDocs/dynamics365smb-devitpro-pb#2305]
The link for Cumulative Update 34 is incorrect. it points to "Cumulative Update 51 for Microsoft Dynamics NAV 2018 (Build 48514)"
Would you mind correcting it, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9afb787-c62c-1a40-53e0-fa345de5f7cf
* Version Independent ID: c2c7c805-d4cc-eef8-bf8f-f96d5c264e1d
* Content: [Cumulative updates for the Spring 2019 version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/update-versions-14)
* Content Source: [dev-itpro/deployment/update-versions-14.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/deployment/update-versions-14.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback!

The correct link is [5013419](https://support.microsoft.com/help/5013419). We've fixed the article and an update will be published soon.

**Comment by martonnagy** [comment]
Awesome! Thank you very much. Have a great weekend
