### ISSUE TITLE
4) upgrade toolkit FOB files confusion

### ISSUE THREAD

**Issue by rehansatti-DI** [MicrosoftDocs/dynamics365smb-devitpro-pb#2306]
[The step no 4 is described as "You have the upgrade toolkit FOB files for the version that you are upgrading from"
This does not look true as we are upgrading from NAV 2017. Our target version is Business Central v14. It is always used target version upgrade tool kit. objects from the local object folder version.  According to the above sentence, we should use the 2017 upgrade tool kit, as we are upgrading from 2017. You will not find those upgrade tool kit objects in NAV 2017 installation DVD. You will find these Objects in the business Central V14 upgrade tool kit.  This correct sentese is "You have the upgrade toolkit FOB files for the version that you are upgrading to" which mean we need to use the upgrade tool kit from Business Central V14 installation DVD,

1. **UpgradeToolKit\Local Object** files NAV 2017 DVD
 "Upgrade710HF1000.DK
Upgrade7001000.DK
Upgrade7101000.DK
Upgrade8001000.DK
Upgrade9001000.DK"
2. **UpgradeToolKit\Local Object** files Business Central V14 DVD
 "Upgrade13x14x.DK
Upgrade80014x.DK
Upgrade90014x.DK
Upgrade100014x.DK
Upgrade110014x.DK"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Data to in Single-Tenant Deployment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback. We've changed the article to hopefully make this clearer. The update will be published soon.
