### ISSUE TITLE
Why are 3 out of 4 descriptions of the values the same? They have different functionality.

### ISSUE THREAD

**Issue by josnelissen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2307]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9a88b1-f7e9-e4cb-6b06-4d9e11ef4e35
* Version Independent ID: c9b7c384-2643-75e6-c9cd-308d3b77042f
* Content: [TestPermissions Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-testpermissions-property?source=docs)
* Content Source: [dev-itpro/developer/properties/devenv-testpermissions-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-testpermissions-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We have just updated the property topic with our latest doc update. Closing this issue now.
