### ISSUE TITLE
minor thing but at bit confusing

### ISSUE THREAD

**Issue by OysteinAker** [MicrosoftDocs/dynamics365smb-devitpro-pb#2309]
Hi not a big thing but a bit confusing

the first line in the article for news in version 19.5 might be a copy paste from the last article because it refers to version 19.4 when actually being about version 19.5 if i understand it correct :)

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 34979b49-7621-4a5d-82a5-49c88a117cef
* Version Independent ID: 34979b49-7621-4a5d-82a5-49c88a117cef
* Content: [Update 19.5 for Microsoft Dynamics 365 Business Central 2021 Release Wave 2 - Business Central](https://docs.microsoft.com/nb-no/dynamics365/business-central/dev-itpro/whatsnew/whatsnew-update-19-5)
* Content Source: [dev-itpro/whatsnew/whatsnew-update-19-5.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/whatsnew/whatsnew-update-19-5.md)
* Service: **dynamics365-business-central**
* GitHub Login: @EmmaNielsson
* Microsoft Alias: **a-emniel**

**Comment by jswymer** [comment]
Thanks! We've fixed the article as suggested. The update will be published soon.
