### ISSUE TITLE
Title property

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#231]
The Title property (for text fields) is not described. Why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ade33329-40dd-55e9-08e0-3bd9211ea768
* Version Independent ID: ccf52795-2e86-7e48-daaf-3d6b726b5e36
* Content: [Table Object Properties - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/table-properties#text-properties)
* Content Source: [dynamics-nav/Table-Properties.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Table-Properties.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Hello, the Title property was in fact deprecated a few releases back. However, it was not removed from CSIDE. Although you can set the property, it has no effect in the client. The documentation will be updated to state this, and we will remove this from the development environment in a future release. Thanks for the feedback!

**Comment by lvanvugt** [comment]
Hi @jswymer , that's what I exactly thought, but as I could not find any info on that I was wondering whether I was doing something wrong.
