### ISSUE TITLE
Wrong PowerShell command parameter

### ISSUE THREAD

**Issue by catadumitru** [MicrosoftDocs/dynamics365smb-devitpro-pb#2312]
In Task 5
Some of the PowerShell commands, like:
Set-NAVWebServerInstanceConfiguration -ServerInstance BC200 -KeyName ClientServicesCredentialType -KeyValue "AccessControlService"

Would error out because there is no parameter called ServerInstance, there is a WebServerInstance parameter that can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de3338bf-8bdf-7d6a-884e-3afdb4d37165
* Version Independent ID: de3338bf-8bdf-7d6a-884e-3afdb4d37165
* Content: [Configure Azure Active Directory Authentication with OpenID Connect - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect?tabs=singletenant%2Cadmintool)
* Content Source: [dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks! We've fixed the article, and the update will be published soon.
