### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mau-co** [MicrosoftDocs/dynamics365smb-devitpro-pb#2314]
![grafik](https://user-images.githubusercontent.com/79905099/164231783-97788e85-58df-4246-a0b7-7a4dcfec8070.png)

Typo, should be "an API"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73d19576-22d5-b44d-0cc0-3a612f7a5a23
* Version Independent ID: aabda29a-5a84-d72e-945f-56b6cb9ba6cc
* Content: [Developing a custom API - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-custom-api)
* Content Source: [dev-itpro/developer/devenv-develop-custom-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-develop-custom-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next doc refresh.
