### ISSUE TITLE
On operating system date

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#232]
Make please clear whether "Gets the current date set in the operating system" applies to client OS or service tier OS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f93856-3097-173e-4c8e-aba67fa0c7f5
* Version Independent ID: a9d74b5f-34c1-141c-bc03-78bca4053b97
* Content: [TODAY Function (Date) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/today-function--date-)
* Content Source: [dynamics-nav/TODAY-Function--Date-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/TODAY-Function--Date-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback. I will try to clear things up in the article. For the most part, it is the client that determines the date.  It is different for the Windows client and Web client. For the Windows client, TODAY returns the current day of the computer that is running the Windows client , as determined by the OS date and time settings. For the Web client, the day is determined by the Regional Settings that are set under My Settings in the client. The very first time you sign-in, the system automatically determines the Regional Setting based on your browser/computer settings.  Then, no matter where you open the client from, the date returned for TODAY is based on the Regional Settings under My Settings in the client - until you manually change them. The same holds true for the TIME function.

**Comment by jswymer** [comment]
An updated article will be published soon. Thanks again for the feedback.
