### ISSUE TITLE
Creating new multi tenant environment using this script is broken

### ISSUE THREAD

**Issue by tvandruten** [MicrosoftDocs/dynamics365smb-devitpro-pb#2321]
[Enter feedback here]
This is very broken. Creating an empty database and mounting it to the app database gives an error about missing tables... But it's an empty database right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369ef361-8740-4777-2f6d-32e73df71e43
* Version Independent ID: e2d76464-650f-3a97-d15c-f6d50245bfa4
* Content: [Manage Application and Tenant Databases in a Multitenant Deployment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/multitenant-setup-guide#feedback)
* Content Source: [dev-itpro/administration/multitenant-setup-guide.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/multitenant-setup-guide.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello again,

I followed the instructions in the article and didn't run into any problems. The issue mentions broken script, but the article doesn't explicitly include a script, so perhaps I misunderstood something. Would it be possible to provide a bit more information pointing to where the issue occurred? Thanks

**Comment by tvandruten** [comment]
Hi there @jswymer,

I created a new multi-tenant environment and wanted to make a new tenant.
The web-page states you can create an empty database, mount it and sync it and it should be working.
Though mounting an empty database does not work as it gives an error.

In this instance I meant the 4 steps on the webpage when using the word 'Script'.

**Comment by jswymer** [comment]
Hello,

Sorry, I'm not sure what the issue could be. More detailed steps can be found here, although I'm not sure this will solve the problem.

[Create databases]https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/devenv-create-databases#tenant)

 It could something to contact support about. If there is a documentation issue, we'll be notified.

**Comment by jswymer** [comment]
Hello again, I just wanted to follow up on this issue. I tried to repro it on version 19.2, but I didn't get the error. I recommend that you contact support, so they can better analyze the issue. Sorry we couldn't help more. Kind regards.
