### ISSUE TITLE
Typo in Join-NAVApplicationObjectFile Documentation

### ISSUE THREAD

**Issue by jdeaguiar** [MicrosoftDocs/dynamics365smb-devitpro-pb#2327]
[Enter feedback here]
There is a backslash missing in the sentence below "For example, to use all text files in the SOURCE folder that is a subfolder to the current folder, type .\SOURCE*.txt.".  You should say "..., type .\SOURCE\\*.txt."  (You may need to escape the backslash before the asterisk.)

-Source
Specifies the folder that stores the text files with application objects that you want to merge into a single text files with all application objects.

For example, to use all text files in the SOURCE folder that is a subfolder to the current folder, type .\SOURCE*.txt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7833e6f6-304a-0a3c-a8ee-9a8d85bd9c2d
* Version Independent ID: 6bccf4b9-b603-60a2-e9a3-25d29a72b240
* Content: [Join-NAVApplicationObjectFile (Microsoft.Dynamics.Nav.Model.Tools) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.model.tools/join-navapplicationobjectfile?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Model.Tools/Join-NAVApplicationObjectFile.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Model.Tools/Join-NAVApplicationObjectFile.md)
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the help! The article has been fixed and the update will be published soon.
