### ISSUE TITLE
Where are the links for 2021 and 2022?

### ISSUE THREAD

**Issue by ndfan77** [MicrosoftDocs/dynamics365smb-devitpro-pb#2329]
This page needs to be updated with the BC download links for 2021 and 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f446fc6-3475-7b86-3ba3-a0bdaebf80e8
* Version Independent ID: 722a12dd-e281-ee5b-96ec-581d94166274
* Content: [Install Business Central Using Setup - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/install-using-setup)
* Content Source: [dev-itpro/deployment/install-using-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/deployment/install-using-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks! The links have been included in the article, which will be published soon:


   - [Business Central 2021 Release Wave 2](https://support.microsoft.com/en-us/topic/released-updates-for-microsoft-dynamics-365-business-central-2021-release-wave-2-0d9263bf-e474-41c1-ae41-d98de5cd6e84)
   - [Business Central 2022 Release Wave 1](https://www.microsoft.com/en-us/download/details.aspx?id=104062)
