### ISSUE TITLE
Task 10: Increase the application version of the database - gives error on dataupgrade

### ISSUE THREAD

**Issue by ERPgruppenMW** [MicrosoftDocs/dynamics365smb-devitpro-pb#233]
This step, gives error on dataupgrade process:
Task 10: Increase the application version of the database
We give database same version as new BC database/version
When starting upgrade using start-navdataupgrade an error comes saying that version is same as upgrade-to version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, following the guidelines, I just successfully tested upgrading a single-tenant deployment of NAV 2018  (version 11.0.25938.0) to Business Central (13.0.25904.0). For step 10, I changed the application version from 11.0.25938.0 to  13.0.25904.0 (using the following cmd), synced, and then ran the upgrade: 
Set-NAVApplication -ServerInstance bc130 -ApplicationVersion 13.0.25904.0 -Force

If you did not sync after changing the application version, this might cause the problem. Is there any more information that you can provide, like the detailed message?

**Comment by jswymer** [comment]
Also, can you check the application version is in the $ndo$dbproperty and $ndo$tenantproperty? Thanks

**Comment by jswymer** [comment]
Hello, I hope you solved the issue. I will close this issue for now. If you are still having problems, please create another issue. Thanks for the feedback.
