### ISSUE TITLE
Markdown Table Broken

### ISSUE THREAD

**Issue by njackson1582** [MicrosoftDocs/dynamics365smb-devitpro-pb#2330]
Bottom Markdown table is broken on the attached report: 

![chrome_O1mrvrQMkZ](https://user-images.githubusercontent.com/92820461/166805250-2c13d8e9-55b2-4be7-a3f2-f7b8c7977701.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d25d9de3-9362-0c4a-5eb4-b831b51e8d62
* Version Independent ID: 47555a66-659f-3101-ee25-1ab859ae3238
* Content: [Report Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-data-type)
* Content Source: [dev-itpro/developer/methods-auto/report/report-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/report/report-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This is fixed with the recent doc refresh.
