### ISSUE TITLE
Repair-NAVApp: missing space between previous switch's parameter, and next switch's hyphen

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2335]
This is clearly syntactically wrong:
![image](https://user-images.githubusercontent.com/63455896/167456798-d580dddf-9922-4504-b424-b17c93fd7d83.png)

It should be
```
Repair-NAVApp -ServerInstance BC -Name 'Proseware SmartApp' -Version 2.3.4.500
```

i.e. add a space before `-Name` so that it's actually treated as a switch, not a continuation of the `-ServerInstance`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe517c5-c229-275f-9200-e58fbdc769b2
* Version Independent ID: df7feaca-3c2a-3cd4-c395-20cda286ec33
* Content: [Repair-NAVApp (Microsoft.Dynamics.Nav.Apps.Management) - Dynamics NAV](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/repair-navapp?view=businesscentral-ps-20)
* Content Source: [businesscentral-ps-20/Microsoft.Dynamics.Nav.Apps.Management/Repair-NAVApp.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-20/Microsoft.Dynamics.Nav.Apps.Management/Repair-NAVApp.md)
* Product: **dynamics-365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks! The example has been fixed and the update will be published soon.
