### ISSUE TITLE
Parameter description has been placed under wrong parameter

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#2339]
The text `True exposes the global methods in the object that contains the event publisher function to event subscriber functions; false does not. The default value is false.` should be moved up to the `IncludeSender` parameter. It is not related to the `Isolated` parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae6882c-7efc-adcb-a807-45dc5bb4da05
* Version Independent ID: 610c89e8-b3ea-9f3c-24d8-c11eafc6ac83
* Content: [BusinessEvent Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-businessevent-attribute)
* Content Source: [dev-itpro/developer/attributes/devenv-businessevent-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/attributes/devenv-businessevent-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dnpb** [comment]
But it is not really relevant to `IncludeSender` either. That only adds the publishing object to the subscriber arguments. It does not add global methods per se. I think the doc of `IncludeSender` already covers it, and the mentioned line should just be removed.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, this will be fixed with the next doc refresh.
