### ISSUE TITLE
OData Base URL

### ISSUE THREAD

**Issue by KDGundermann** [MicrosoftDocs/dynamics365smb-devitpro-pb#234]
what is a "correct" OData Base URL ?

- https://docs.microsoft.com/en-us/dynamics-nav/microsoft-dynamics-nav-web-services-overview
gives a URL of:
`http://localhost:7048/DynamicsNAV/OData/Company('CRONUS-International-Ltd.')/Customer?Tenant=Tenant1`

- https://docs.microsoft.com/en-us/dynamics-nav/walkthrough-creating-and-interacting-odata-v4-bound-action
gives a URL of:
`http://<Server>:<WebServicePort>/<ServerInstance>/api/beta/companies(<companyid>)/salesInvoices(<invoiceid>)/Microsoft.NAV.Copy)`

- https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics
gives URL of:
`https://<base URL>:<port>/v1.0/api/<API version>/`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e91e4d8-5e4e-80a4-0e46-e2d23fc83155
* Version Independent ID: 07a13af1-543c-f8de-0daa-6fd2cc27cea0
* Content: [Enabling APIs for Microsoft Dynamics NAV - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/enabling-apis-for-dynamics-nav)
* Content Source: [dynamics-nav/enabling-apis-for-dynamics-nav.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/enabling-apis-for-dynamics-nav.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi! Thank you for your feedback! The correct OData Base URL is http://<Server>:<WebServicePort>/<ServerInstance>/ODataV4/Company(<CompanyId>)/<ServiceName>(<RecordId>)/Microsoft.NAV.Copy

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback and sorry for the long wait. 
We have updated the [first](https://docs.microsoft.com/en-us/dynamics-nav/microsoft-dynamics-nav-web-services-overview) topic after testing the walkthrough. The ODataV4 endpoint is used there. I think you can still use the second option that you have in your question, but then it is not ODataV4, but probably an OData V3 endpoint. For the last option, this topic is up-to-date with the various endpoints depending on whether you have an on-premises or an online tenant. We offer both Web Services and standard APIs that are reached in different ways. Thanks.
