### ISSUE TITLE
This article name has a typo at the end, "languange" sb "language"

### ISSUE THREAD

**Issue by emuench** [MicrosoftDocs/dynamics365smb-devitpro-pb#2343]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 463e4bf4-3be8-4b89-21e2-9194e264fe38
* Version Independent ID: c2619d79-96f0-bd7b-e230-5e5d59f2bc3a
* Content: [Language, Branding, and Images - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-a-languange-branding)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-a-languange-branding.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/readiness/readiness-checklist-a-languange-branding.md)
* Service: **dynamics365-business-central**
* GitHub Login: @a-emniel
* Microsoft Alias: **a-emniel**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, that's annoying, I agree. We will, however, not fix this right now because then we'll have to set up redirection for the file. So, leaving as is for now. But thanks for the feedback, and we encourage you keep it coming.
