### ISSUE TITLE
Copy DateFormula Examples

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#2344]
The examples from this page:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-dateformula-property

Should be brought over to this page.

Additionally, there should be a note to add the Greater/Less Than brackets around it to make it multilanguage.

Or, add a See Also to a page with that content.
(Sorry this isn't a PR instead, busy weekend)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b659a96-ac9d-4c56-4e7d-b85abc8eb465
* Version Independent ID: 050cf5d3-4c38-4b3a-cc0f-e56891d7249b
* Content: [DateFormula Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dateformula/dateformula-data-type)
* Content Source: [dev-itpro/developer/methods-auto/dateformula/dateformula-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/dateformula/dateformula-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next doc refresh.
