### ISSUE TITLE
Old/wrong information specified for the IncludeCaption property.

### ISSUE THREAD

**Issue by salgiza** [MicrosoftDocs/dynamics365smb-devitpro-pb#2346]
There seem to be several things wrong with this page, up until the point that I had to double check that I was looking at the correct docs, even though I actually got here using the contextual help of the IncludeCaption property in Visual Studio Code/AL.

In no particular order (tested using the property in a BC20 report):

1. The default value is false, not true. Unless specified, the captions are not being included in the dataset.
2. Remarks: Applies to... RDLC report datasets. Err... no? I'm using the property to include the captions in a Word report (and it works fine, I mean).
3. The property is set from Visual Studio Code, not from Visual Studio Report Designer. In fact, I've double checked using Google, and there is not such thing as "Visual Studio Report Designer" (even if it were a reference to the RDLC designer, it's currently called Microsoft RDLC Report Designer).
4. In the gibberish of the last two paragraphs (Report Dataset Designer? Wasn't that something from the old NAV Object Designer?), it mentions that the property can be specified both for a dataitem or a column. The property does not currently exist at the dataitem level.

Regards,
Salva.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe293b4-3fbd-b2ef-4578-98005b18238b
* Version Independent ID: ab1efaa1-9560-f345-ae56-1ee0400dc45d
* Content: [IncludeCaption Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-includecaption-property)
* Content Source: [dev-itpro/developer/properties/devenv-includecaption-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-includecaption-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dnpb** [comment]
Great points!

> Remarks: Applies to... RDLC report datasets. Err... no? I'm using the property to include the captions in a Word report (and it works fine, I mean).

I think at one point it didn't work, at least not in report extensions, but that was presumably a bug and not intentional ;-)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We've hopefully cleaned this up right now, as this topic contained content that hadn't been revised in a long time. This will be fixed with the next doc refresh.
