### ISSUE TITLE
Syntax complete?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2348]
Since the name of the property is ODataKeyFields, plural, shouldn't there also be an example of .syntax how to specify more than one key field? Or a note as to whether that is supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81737b49-133b-8d4d-b61b-3fd958c5d79a
* Version Independent ID: d4d3e978-5fa7-a989-18d5-fdd23942fa22
* Content: [ODataKeyFields Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-odatakeyfields-property)
* Content Source: [dev-itpro/developer/properties/devenv-odatakeyfields-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-odatakeyfields-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, the ODataKeyFields takes a list of comma-separated fields - the example will be updated with the next doc refresh.
