### ISSUE TITLE
Compatibility level requirements

### ISSUE THREAD

**Issue by ERPgruppenMW** [MicrosoftDocs/dynamics365smb-devitpro-pb#235]
Might be worth mentioning that Compatibility level on Database must be 130

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bffc19c-cc0a-fec5-b46b-16e58b034c19
* Version Independent ID: 0a79027a-c75c-f003-1c89-b0b64d4510de
* Content: [Frequently Asked Questions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/faq-intelligent-cloud#which-products-and-versions-are-supported-for-connecting-to-the-intelligent-cloud)
* Content Source: [dev-itpro/administration/FAQ-Intelligent-Cloud.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/FAQ-Intelligent-Cloud.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by ERPgruppenMW** [comment]
Says so in system requirements, my bad. Delete this feedback

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the heads-up. Will close the issue.
