### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#2351]
There are Examples mentioned in the Description of the optional error text parameter. I think they got lost somehow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8757295-183d-afeb-3030-cee24e0516e1
* Version Independent ID: c8757295-183d-afeb-3030-cee24e0516e1
* Content: [Record.FieldError(Any \[, Text\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-fielderror-joker-string-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-fielderror-joker-string-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-fielderror-joker-string-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The examples are indeed missing and will be added with the next doc refresh. Meanwhile, please go here for the examples: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-fielderror-method. Thanks.
