### ISSUE TITLE
Deep Insert

### ISSUE THREAD

**Issue by mjjoachim** [MicrosoftDocs/dynamics365smb-devitpro-pb#2353]
Business Central only supports "deep insert" for APIs, not web services (Pages exposed as web services). It might be nice if that was clarified here and throughout the OData documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adfd5c32-86a0-6079-d62f-0697f41b3e53
* Version Independent ID: adfd5c32-86a0-6079-d62f-0697f41b3e53
* Content: [Known OData Limitations  - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/odata-known-limitations)
* Content Source: [dev-itpro/webservices/odata-known-limitations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/webservices/odata-known-limitations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
We've updated the article as suggested. The update will be published soon. Thanks for the feedback!
