### ISSUE TITLE
Data from dependend apps are deleted also - not documented!

### ISSUE THREAD

**Issue by yurim108** [MicrosoftDocs/dynamics365smb-devitpro-pb#2354]
Hi,

we have had an unexpected behaiviour during upgrade from BC18 to BC19 On-Prem.
One colleague has uninstalled an old version of one app in web client and selected the option to delete extension data.
He actually wanted to install a new version of that app right afterwards.
Well, it was his mistake to do it this way, but the results where more fatal as expected.
The data was deleted in several dependend apps as well.
I could not find any documentation about this behaviour.
May be it is a bug? 
If not then please document this behaviour.
An extra warning in BC would be of a great help.

Best regards,
Yuri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 224dcbbb-4289-2ac5-8071-1d70d06ccb19
* Version Independent ID: 4f836bf8-7c1d-5060-e8d3-519ac9ebea0d
* Content: [How to Unpublish and Uninstall an Extension v2.0 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-unpublish-and-uninstall-extension-v2)
* Content Source: [dev-itpro/developer/devenv-unpublish-and-uninstall-extension-v2.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-unpublish-and-uninstall-extension-v2.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the valuable feedback.

We recently made an update to the Extension Management page for version 19 and later, which improves the message when you try to uninstall extension and delete data if the extension has dependents: 
![uninstall1](https://user-images.githubusercontent.com/15834167/170203707-7c2a19c7-e115-4451-8e28-5fd4d1221ed3.png)

We've also tried to make this more clear in the documentation, in the following articles:

- [Install and Uninstall Extensions in Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions-install-uninstall) in the business functionality help
- [Unpublishing and Uninstalling Extensions](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-unpublish-and-uninstall-extension-v2) in the developer and admin help.
- [Uninstall-NAVApp](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/uninstall-navapp) in the PowerShell help

We hope these changes help.
