### ISSUE TITLE
License Required to Access? 

### ISSUE THREAD

**Issue by MariusWeiss** [MicrosoftDocs/dynamics365smb-devitpro-pb#2355]
I tried to access the BC Admin Center but I only get a blank page. My colleague is able to access the Admin Center without any issues. I have the Global Administrator Role assigned as well as the Dynamics 365 Admin Role (even through it is not necessary). The only difference is that my colleague has a BC License assigned. But as far as I know there is nothing written on this Documentation about License requirements. Is it possible that this is a mistake in the Documentation or did I missed a step? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f495bb1-bd83-5b17-ad11-fe48910d2315
* Version Independent ID: 65a8141e-9503-3120-6269-88b34e721909
* Content: [Business Central Admin Center - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center)
* Content Source: [dev-itpro/administration/tenant-admin-center.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/tenant-admin-center.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello, thank you for your feedback! The Business Central admin center does not require a license. I'm not sure what is going on for you, but if your organization has set up granular delegated admin permissions for the tenant, then both you and your coworker ought have the Dynamics 365 Admin Role and have equal access to the Business Central admin center.
For more information, see https://docs.microsoft.com/partner-center/gdap-introduction

**Comment by MariusWeiss** [comment]
@edupont04 : Thank you for your reply. I made a mistake and only applied the Global Administrator Role, which seems not work. As soon as I applied to the Dynamics 365 Admin Role, I was able to access the BC Admin Center.

**Comment by edupont04** [comment]
Excellent news! 
Closing Issue.
