### ISSUE TITLE
Missing information about standard filter to use

### ISSUE THREAD

**Issue by ERPgruppenMW** [MicrosoftDocs/dynamics365smb-devitpro-pb#2356]
Hi,
Please add how to use filters on the specific endpoints. The templateDisplayName filter, gives the possibility to get journals for journaltemplate other than the first found on the list. 
Usage is like this below.
/journals?$filter=templateDisplayName eq '<YourTemplateNameHere>'

If there are other endpoints with same "hidden" vital knowledge about filters, please supply info on filters on these endpoints as well..

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 777dff17-aad7-aaea-ec1e-a13635354d4a
* Version Independent ID: 58cc61b0-64c1-fed4-7cbf-eca02d5700ab
* Content: [Get journals - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_journal_get)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_journal_get.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_journal_get.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. We do have a topic on filtering, but it's not discoverable from the specific api topics. You can access it here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-connect-apps-filtering. We'll move a couple of topics into the table of contents for easier access, with the next doc refresh. Thanks.

**Comment by ERPgruppenMW** [comment]
Hi,

But the link you refer to only gets around stand filtering, not the filters only visible in code?

Med venlig hilsen
Mads Westen
________________________________
Fra: Susanne Windfeld Pedersen ***@***.***>
Sendt: Tuesday, May 24, 2022 3:53:36 PM
Til: MicrosoftDocs/dynamics365smb-devitpro-pb ***@***.***>
Cc: Mads Westen ***@***.***>; Author ***@***.***>
Emne: Re: [MicrosoftDocs/dynamics365smb-devitpro-pb] Missing information about standard filter to use (Issue #2356)


Hello, thanks for the feedback. We do have a topic on filtering, but it's not discoverable from the specific api topics. You can access it here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-connect-apps-filtering. We'll move a couple of topics into the table of contents for easier access, with the next doc refresh. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Getting back to this. The docs will be updated with the next doc refresh. The templateDisplayName filter is the only filter available. Thanks.
