### ISSUE TITLE
Change log activated

### ISSUE THREAD

**Issue by ERPgruppenMW** [MicrosoftDocs/dynamics365smb-devitpro-pb#236]
Seems that Activation of Change Log is needed on local database - got this error: 
Customer	Failed	Failure preparing data for table. Error message: Change tracking is not enabled on table '2018_1$Customer'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bffc19c-cc0a-fec5-b46b-16e58b034c19
* Version Independent ID: 0a79027a-c75c-f003-1c89-b0b64d4510de
* Content: [Frequently Asked Questions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/faq-intelligent-cloud#which-products-and-versions-are-supported-for-connecting-to-the-intelligent-cloud)
* Content Source: [dev-itpro/administration/FAQ-Intelligent-Cloud.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/FAQ-Intelligent-Cloud.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Please refer to this [blog post](https://community.dynamics.com/business/b/businesscentraldevitpro/archive/2018/11/29/intelligent-cloud-fixing-the-change-tracking-error) which was just released for more guidance on this matter. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
