### ISSUE TITLE
Different variables used

### ISSUE THREAD

**Issue by OussamaSabbouh** [MicrosoftDocs/dynamics365smb-devitpro-pb#2367]
Dear,
As per below code existing in the documentation page https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-rename-method , you declare a variable "CustomerRecRef" but in the code you uses another variable not declared "CustRecRef"

var
    CustomerRecRef: RecordRef;
    NewNo1: Code;
    NewNo2: Code;
    result: Boolean;
    CustomerRec: Record Customer;
begin 
    CustomerRec.Get('0112121');  
    NewNo1 := ‘9999999’;  
    NewNo2 := ‘8888888’;  
    Message('Customer name: %1; Customer number: %2',CustomerRec.Name, CustomerRec."No.");  
    result := CustomerRec.Rename(NewNo1);  
    if result then  
      Message('After rename - Customer name: %1; Customer number: %2',CustomerRec.Name, CustomerRec."No.")  
    else  
      Message('No rename.');  
    CustRecRef.GetTable(CustomerRec);  
    result := CustRecRef.Rename(NewNo2);  
    if result then begin  
      CustomerRec.Get(NewNo2);  
      Message('After rename 2 - Customer name: %1; Customer number: %2',CustomerRec.Name, CustomerRec."No.")  
    end else  
      Message('No rename.');  
end;

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, this will be fixed with the next refresh of the docs.
