### ISSUE TITLE
Task 11: Run the schema synchronization on the imported objects error Command

### ISSUE THREAD

**Issue by aconcato** [MicrosoftDocs/dynamics365smb-devitpro-pb#237]
Is this Set-NAVTenant -ServerInstance &lt;ServerInstanceName&gt;
or
Sync-NAVTenant  &lt;ServerInstanceName&gt; ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data#feedback)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
The command has been corrected to "Sync-NAVTenant <ServerInstanceName>". The updated article will be publsihed soon. Thanks for the feedback!
