### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2370]
Article identifies JSON as "JavaScript Object Notification"; actual acronym name is "JavaScript Object Notation"

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1fd7a9e-7ba2-62b1-14bd-6e45e15b26ff
* Version Independent ID: da31ff3b-726f-03a8-f05a-4e2d7d8e694d
* Content: [Users and Credential Authorization - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/users-credential-types)
* Content Source: [dev-itpro/administration/users-credential-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/users-credential-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Thanks! We've made the fix.
