### ISSUE TITLE
Authentication and authorization: Companies don't seem to refresh after setting different environments in new Table view

### ISSUE THREAD

**Issue by virakones** [MicrosoftDocs/dynamics365smb-devitpro-pb#2373]
Since the update to change the dataverse tables, business central configuration record for virtual tables edited through new editable grid view doesn't seem to refresh companies after typing in new environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28370b2f-fedb-ba1e-31e4-b30b64039d24
* Version Independent ID: 98f25d46-ec3a-46a1-359b-314fa972ad2b
* Content: [Microsoft Power Platform integration with Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/powerplatform/powerplat-overview)
* Content Source: [dev-itpro/powerplatform/powerplat-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/powerplatform/powerplat-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. Please use your usual support channel to get help or file a bug. Thanks.
