### ISSUE TITLE
Shouldn't it read......

### ISSUE THREAD

**Issue by sauerkreut** [MicrosoftDocs/dynamics365smb-devitpro-pb#2378]
in the example in the article it's written:
```
TestOutStream.WriteText('</html>');  
FileMyHTML.Close; 
```
Schouldn't it read MyHTMLFile.Close ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 156bc1e7-af05-d289-ef28-c52202aa19e9
* Version Independent ID: 7f89a511-387e-ab24-10da-f9201a0860d2
* Content: [OutStream.WriteText(\[Text\] \[, Integer\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/outstream/outstream-writetext-method)
* Content Source: [dev-itpro/developer/methods-auto/outstream/outstream-writetext-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/outstream/outstream-writetext-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

We've fixed the example as suggested. The updated article will be published soon. Thanks!
