### ISSUE TITLE
Subtitle is wrong in article Business Central 2022 Release Wave 1

### ISSUE THREAD

**Issue by ramos-e** [MicrosoftDocs/dynamics365smb-devitpro-pb#2379]
The subtitle on the page about: "Dynamics 365 Business Central On-Premises 2022 Release Wave 1 Updates" is wrong.

The subtitle reads: "Available updates for Business Central 2021 Release Wave 2"

But should be: "Available updates for Business Central 2022 Release Wave 1"

Link: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/update-versions-20#available-updates-for-business-central-2021-release-wave-2

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d8a99c-a4f4-5de2-05ec-c73f4174935a
* Version Independent ID: 77d8a99c-a4f4-5de2-05ec-c73f4174935a
* Content: [Updates for the Business Central 2022 Release Wave 1 versions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/update-versions-20)
* Content Source: [dev-itpro/deployment/update-versions-20.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/deployment/update-versions-20.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, we've fixed the article and the update will be published soon. Thanks for the feedback!
