### ISSUE TITLE
Task 21: Publish and install/upgrade extensions

### ISSUE THREAD

**Issue by aconcato** [MicrosoftDocs/dynamics365smb-devitpro-pb#239]
Publishing the extension from DVD version 13.0.24623 
I get this error: Error AL1024: A package with publisher 'Microsoft', name 'Test', and a version compatible with '11.0.0.0' could not be loaded 
Example:UKPostCodeGetAddressIO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data#feedback)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

Just to confirm, was this error returned during Task 21, step 2 when you tried to publish the Test symbols from the DVD using the following cmd "Publish-NAVApp -ServerInstance <ServerInstanceName> -Path <SymbolFilePath> -PackageType SymbolsOnly"? 

I tried to reproduce the error, but could not. If you can you provide more details, that would be great. Thanks!

**Comment by aconcato** [comment]
Hi,
Thank you for your reply,
The issue is that I can't see the extension on the list of the extensions or with the command "Get-NAVAppInfo" by using the command "the command Publish-NAVApp -ServerInstance -Path -PackageType SymbolsOnly".
And if I run the command "Install-NAVApp" I'll receive the message "PackageType that are of SymbolsOnly type cannot be installed.
Does that make any sense?-

**Comment by aconcato** [comment]
Hi,
I can confirm you that with Get-NAVAppInfo -SymbolsOnly I can see the extension installed.
The issue is that the page 2500 Extension Management is filtered for Package Type=FILTER(=0|2)) but  with the test extension  "SymbolsOnly" is value 1 and I can't see extension SymbolsOnly on Page 2500.
I've investigated on Demo Database v 13.0.24623 and the test extension packagetype is 0..
I'm confused.. is it the page filter wrong or the test extension packagetype?

**Comment by jswymer** [comment]
Hi, the way it should work is that the Package Type is determined by whether or not you use the "-PackageType SymbolsOnly" switch when you publish the Test  extension. If you use the "-PackageType SymbolsOnly" switch, then the PackageType is set to 1; otherwise I think it is 0 or 2. The Extension Management page is filtered to show only 0 and 2 because users typically would not install Symbol extensions on tenants.

**Comment by aconcato** [comment]
Sorry but it still unclear how I can re-install extensions "Test" such as:
Business Central Intelligent Cloud,GetAddress.io UK Postcodes,GetAddress.io UK Postcodes etc. upgrading from Dynamics NAV 2018 to Business Central.
At the moment I've installed only SymbolsOnly but I can't install them or see them on page 2500.

**Comment by jswymer** [comment]
Sorry, I guess I misunderstood the issue. I thought it was only with the Test symbols extension (Test.app) The Test.app is a standalone extension that contains the test symbols. This only need to be published using the PackageType SymbolsOnly. 

So, as I understand it, during upgrade, you uninstalled several extensions, like Business Central Intelligent Cloud,GetAddress.io UK Postcodes. Now you reached Task 21 and you want to reinstall them. The flow is:   

1. Publish system and test symbols, and generate application symbols. (this is steps 21.1, 21.2, and 21.3)
2. Publish, synchronize, and upgrade to new versions of Microsoft extensions from installation media (step 21.4). This is where you will publish the updated extension versions found on the DVD, for example GetAddress.io UK Postcodes
3. Repair, synchronize, and install old extension versions that were not upgraded in previous step (step 21.5. This recompiles other published extensions that do not have new versions (from the previous step)

**Comment by aconcato** [comment]
Solved!
Thank you!
