### ISSUE TITLE
List<T> says "A copy of a list is a shallow copy." - What does that mean in BC?

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2395]
https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2265 asked this, but it didn't lead to a clear enough answer, in my opinion.

The OP there used "shallow copy" to mean 'List is a reference type, so assigning an one List variable to another causes both to refer to / read / write the same set of values'.

But in my experience, from other languages, "shallow copy" means only that contained values are copied shallowly, i.e. that a copy of a reference (whether alone or as a subobject) still refers to the same instance...]

...whereas a 'deep copy' would mean that references would cause new instances to be cloned from the source and placed in the destination. This is never the case in AL.

So a `List<T>` does a shallow copy in the latter sense. The former sense is not so clear.

To explain the former sense, I would prefer to see documentation saying something like

> A List is a reference type, so copying an instance - e.g. by assigning to another variable or passing as a method parameter by value (i.e. without `var`) - creates a second variable that reads/writes the same set of values. It does not create an independent set of values.

We should then explain how one **could** create an independent set of values. I believe that would be something like this, but please correct me if I'm wrong... (e.g. perhaps if `GetRange()` receives `Count := 0` it just Does The Right Thing without us having to check?)

> To create an independent copy of a List, do something like this:
> ```al
> procedure CopyList(Src: List of [Integer]) Dst: List of [Integer]
> begin
>     if Src.Count >= 1 then Dst := Src.GetRange(1, Src.Count);
> end;
> ```

Can this be improved please? And ditto for `Dictionary`, I should mention :-D Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c760a1-0ba5-814b-94bf-c50008364769
* Version Independent ID: 235f987b-1062-26ba-81a7-b72ff35c099b
* Content: [List Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/list/list-data-type)
* Content Source: [dev-itpro/developer/methods-auto/list/list-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/list/list-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks much for the input, we will update this topic with the next doc refresh.

**Comment by dnpb** [comment]
Thank you :-)
