### ISSUE TITLE
`List.GetRange()` methods should explain what they mean by "shallow copy"

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2398]
See also https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2395

The page linked below, and [this other overload](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/list/list-getrange-integer-integer-list[t]-method), say this:

> Get a shallow copy of a range of elements in the source.

What does this mean? Is it the same as at the above link, so that if I do `getRange()` to get a sublist of a List, then update values in the subrange, the parent range will reflect those changes? What if I expand/shrink the sublist; does that affect the parent?

Or does it just mean that elements that are/contain reference types will refer to the same instances in the new List, but otherwise the resulting List instance is independent from its parent?

I ask because I'm not convinced that most NAV/BC developers will be very familiar with the concept of a "shallow copy", nor am I certain that the term is always used in correct or consistent ways over the docs.

Thanks :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9271a4-4f27-7402-10eb-62e4094f6430
* Version Independent ID: b339567e-adb8-999b-47ef-735a9d2a1406
* Content: [List.GetRange(Integer, Integer) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/list/list-getrange-integer-integer-method)
* Content Source: [dev-itpro/developer/methods-auto/list/list-getrange-integer-integer-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/list/list-getrange-integer-integer-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. For your previous issue, the List Data Type topic will be updated with examples and more info with the next doc refresh. For the questions in this issue, generally it depends on whether you are working with a reference or a value type. For reference types you will always only operate on a reference and thereby update the parent as well if you update your sublist. We will add links to the List Data Type from the getrange overloads too. Thanks.

**Comment by dnpb** [comment]
Thanks!

So it sounds like `GetRange()` copies the elements - so that

* if I have an initial `List1` consisting of `[4, 8, 15, 16, 23, 42]`,
* then I do `List2 := List1.GetRange(3, 2); List2.Set(1, 123); List2.Set(1, 456);` -
* I will *not* now see that `List1` contains `[4, 8, 123, 456, 23, 42]` - right?

i.e.: the new `List` is not just a sharing view into the original one, but instead gets its own copy of each element.

I understand that the reference-ness of the contained values matters - but I'm only asking whether those values are copied (which, for a reference, still refers to the same instance) - and hence are indepedent from the values they were copied from.
