### ISSUE TITLE
Using a flowfilter

### ISSUE THREAD

**Issue by BrianThorChristensen** [MicrosoftDocs/dynamics365smb-devitpro-pb#24]
Hi,
I would like to know how a user can change the output of a flowfield using a flowfilter in Business Central.
I can't find any way to do this in the web client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ea41599-f702-15a8-c9dd-13a41d6ab8df
* Version Independent ID: 27f4af23-40fa-8f99-d1e8-28e81692715d
* Content: [FlowFilter Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-flowfilter-overview)
* Content Source: [dev-itpro/developer/devenv-flowfilter-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-flowfilter-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. You have reached the developer documentation and you were probably looking for our application help. Please find that here: [Dynamics 365 Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/). FlowFields and FlowFilters are programatically added to calculate values that the user can see, but usually not modify or filter on. An example of how FlowFields display can be seen, for example, on the Sales Invoice page at the bottom of the page.
