### ISSUE TITLE
No examples?

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#2400]
The text mentions

_then default text is used as shown in the following examples_

But the page does not contain any examples ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8757295-183d-afeb-3030-cee24e0516e1
* Version Independent ID: c8757295-183d-afeb-3030-cee24e0516e1
* Content: [Record.FieldError(Any \[, Text\]) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-fielderror-joker-string-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-fielderror-joker-string-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-fielderror-joker-string-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, if you scroll down a bit, there are three examples....?

**Comment by fvet** [comment]
You're absolutely rights, I must have been dreaming either or had a browser slitch ... :)
Thanks for double checking
