### ISSUE TITLE
team member permissions

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-devitpro-pb#2401]
can we please get a definitive answer on what the team member license offers?

Not a link to the license guide its too detailed for such a simple answer

Thank you
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7e6932-b672-a55a-1217-b7aadf7fc275
* Version Independent ID: 73ae4240-a595-ba84-d4b5-4da9d5186214
* Content: [Licensing in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/licensing)
* Content Source: [dev-itpro/deployment/licensing.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/deployment/licensing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
The reason we link to the license guide is that this is the main document for all information regarding licenses. I have copied the information about team member license for Business Central for your reference here. Hope that helps. Thanks.

The Dynamics 365 Business Central Team Members license, not to be confused with Dynamics 365 Team 
Members license, grants a named user the following rights for their own use only (not for, or on behalf of, 
others):
• Read data within Business Central
• Update existing data and entries in Business Central, such as previously created customer, vendor, or 
item records. Entries are defined as specific accounting information that, may be updated, such as a 
due date on customer ledger entries.
• Approve or reject tasks in all workflows assigned to that user, with the limit that approvals and 
rejections can only update data in records that Business Central Team Members can access.
• Create, edit, and delete a sales or purchase quote 
• Create, edit, and delete personal information
• Edit job time sheets for approval
• Use the Dynamics 365 Power Apps/Power Automate use rights provided with a Dynamics 365 license
• Business Central Team Members application module may be customized with maximum 15 additional 
tables (custom tables or standard Dataverse tables) available to the Business Central Team Members 
license.

**Comment by makdaddy8888** [comment]
Thanks but can’t you add this to the docs?

Why’s it so hard to find this info?

Kind Regards
Ben Opit
+61411707070

**Comment by SusanneWindfeldPedersen** [comment]
License information does not, traditionally, belong in core documentation. Also, for maintenance reasons, should license information change, we do not have outdated information in the docs. But thanks for the feedback.

**Comment by makdaddy8888** [comment]
Hi Susan

That statement doesn’t make sense because the docs go into details how the essential and premium experience works. The Team Member limitations should also be discussed. More over if I go and hunt for this information on the dynamics licensing guide the details are offered there. There’s just time wasting trying to find the specific page on the 188 page document.

Just my feedback from all partners in Australia

Kind Regards
Ben Opit
