### ISSUE TITLE
Task 1 didn't create any extension when Upgrading Customized C/AL Application to Microsoft Base Application version 20

### ISSUE THREAD

**Issue by yishengcao** [MicrosoftDocs/dynamics365smb-devitpro-pb#2415]
In the Task 1 section, we didn't be asked to create an extension. However, at Task 13, the document asked to publish the extension created from Task 1. It should be talking Task 3? I am not sure.

![image](https://user-images.githubusercontent.com/23348297/175793647-6b08c052-e073-41ee-94fe-f6081ed59d3f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54fd2f80-bc84-9513-e36a-80bc01271483
* Version Independent ID: 54fd2f80-bc84-9513-e36a-80bc01271483
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application for version 20 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v20)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app-v20.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v20.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
We've fixed the article, and the update will be published soon. Thanks for the feedback!
