### ISSUE TITLE
How can there be parameters and how are they applied?

### ISSUE THREAD

**Issue by thphan75** [MicrosoftDocs/dynamics365smb-devitpro-pb#2416]
This page mentions parameters for a property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11a68b90-c1f3-9bf2-3421-53ed79cc2b56
* Version Independent ID: b2a98fb2-c7cc-706b-0ad9-65cd897d9ab9
* Content: [InstructionalText Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-instructionaltext-property)
* Content Source: [dev-itpro/developer/properties/devenv-instructionaltext-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-instructionaltext-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

Sorry, the article lacks some information. The parameters are applied according to the following syntax:

```al
InstructionalText = '<text>'[, Locked = true|false][, Comment = '<text>'][, MaxLength = <integer>];
```
For example:

```al
InstructionalText = 'Add an entity from your list of contacts. The entity can be a person or a company.', Locked = true, Comment = 'Keep like this, do not translate.', MaxLength = 100;
```
We hope this helps. We've added some more info to the article, which will be published soon. Thanks for the feedback.
