### ISSUE TITLE
Snapshot versus regular debugging: first description seems to have an error

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2417]
Snapshot versus regular debugging: first description seems to have an error.

Is
```
Breakpoints can be added and removed and they will be hit if given a breakpoint; the breakpoint is in the execution context of a recorded state.
```
Should be (?)
```
Breakpoints can be added and removed and they will be hit if given a breakpoint is in the execution context of a recorded state.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc5e406-d2a3-14dd-7399-92e7df9707a2
* Version Independent ID: 2f75dceb-4b27-fa4f-60d2-f797175c8da0
* Content: [Snapshot Debugging - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-snapshot-debugging)
* Content Source: [dev-itpro/developer/devenv-snapshot-debugging.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-snapshot-debugging.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Has been fixed with a previous doc refresh.
