### ISSUE TITLE
Requirement for overriding the resource policy improvement

### ISSUE THREAD

**Issue by foodware365** [MicrosoftDocs/dynamics365smb-devitpro-pb#2419]
Hi,

An important detail that is missing is to set the "tenant" in the configuration in VsCode..

        {            
            "name": "Publish: Microsoft cloud Sandbox",
            "type": "al",
            "request": "launch",
            "environmentType": "Sandbox",
            "environmentName": "{target environment name}",
            "startupObjectId": 22,
            "breakOnError": true,
            "breakOnRecordWrite": false,
            "launchBrowser": true,
            "enableSqlInformationDebugger": true,
            "enableLongRunningSqlStatements": true,
            "longRunningSqlStatementsThreshold": 500,
            "numberOfSqlStatements": 10,
            >>"tenant": "{target tenant-id}"<<
        }

..in addition to being delegated admins on the target environment and putting the tenantid also in the BC-ResourceExposurePolicy-Overrides JSON in the key vault secret.

Best regards,
Huub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 161ddd1b-3d2c-d2fc-0d20-ad8331c809e4
* Version Independent ID: d5153e86-ac7c-4b93-43e2-ae6b06becb8e
* Content: [Resource Exposure Policy Setting - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-security-settings-and-ip-protection)
* Content Source: [dev-itpro/developer/devenv-security-settings-and-ip-protection.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-security-settings-and-ip-protection.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. That's true, this will be added to the topic with the next doc refresh. Thanks.
