### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by DenisTudora** [MicrosoftDocs/dynamics365smb-devitpro-pb#2421]
[Enter feedback here]

I have a support case where a partner is complaining that the article doesn't specify exactly that the “Authentication Email” for GDAP users will return the company name. And the contact email will return a unique ID in the following format User123456@partnerdomain.com.
The information is provided for Users generally, not specifically for the mentioned fields.
If this could be included, it would be very helpful.

Excerpt from the documentation:
"With granular delegated admin privileges (GDAP), the user is shown in the Users list and can be assigned any permissions. They are not shown with name and other personal information but with their company name and a unique ID. Both internal and external admins can see these users in the Users list, and they have full transparency into what these users do through the [change log](https://docs.microsoft.com/en-us/dynamics365/business-central/across-log-changes), for example. But they can't see the actual name of these users. GDAP users are listed with user names in the following format: User123456@partnerdomain.com"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66412cff-bccf-0553-ad97-7bb9ea6c63a9
* Version Independent ID: 6d046b65-1832-bf77-6eec-3d8350f4d83e
* Content: [Delegated admin access to Business Central online - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/delegated-admin)
* Content Source: [dev-itpro/administration/delegated-admin.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/delegated-admin.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Denis,
Just for clarification, is the partner complaining that the GDAP users' names in BC reveal the partner's company name? Or are they complaining that the email address is not an actual email address?

**Comment by DenisTudora** [comment]
Hello Eva,

Thank you for your fast response!
In the beginning he was complaining that the email address is not an actual email address and wanted to know if this behavior can be changed. I have informed him that for now this is the behavior and he understood this.
I have advised him to leave his feedback directly in the Partner Center Portal regarding this behavior, as this goes directly to our Engineering team.
He understood the change in the design and lastly he wanted to know if the documentation can be updated, as in the article the it is not clearly mentioned that the Authentication Email will only return the Company Name and the contact email will be in the form of ***@***.******@***.***>,
there is only a general mention that "the user is shown in the Users list as.."
From my last discussion with him, he told me that he will also leave his feedback regarding the documentation.

If you have any questions or concerns, please don't hesitate in contacting me directly.
Thank you,

Denis Tudora
Support Engineer | Partner Center Technical Support
Working hours: M-F 9 AM - 6 PM (UTC+2)
Manager: Cami Iordache | ***@***.******@***.***>
Technical Advisor: Camelia Cristina Bajau | ***@***.******@***.***>

**Comment by edupont04** [comment]
I'm closing this loop since the current wording says the following:

1. "They are not shown with name and other personal information but with their company name and a unique ID. "
2. "GDAP users are listed with user names in the following format: User123456@partnerdomain.com"

That wording covers the experience. If the partner disagrees with the experience, then they can submit a feature request.
