### ISSUE TITLE
"Text004" instead of "Change credit limit" will be displayed

### ISSUE THREAD

**Issue by sauerkreut** [MicrosoftDocs/dynamics365smb-devitpro-pb#2427]
In the code example of pageextension 50100 CreditBalanceNotification extends "Sales Order" "Text004" instead of "Change credit limit" will be displayed. Code should read
`            //Add an action that calls the ActionHandler codeunit, which you define in the next step.
            CreditBalanceNotification.AddAction(Text004, Codeunit::"ActionHandler", 'OpenCustomer');
`
Thank you for your attention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87fc7637-4e16-c566-a99a-0f2e01aa22a6
* Version Independent ID: cb3cd413-3471-8411-98c5-5d25b22ba777
* Content: [Notifications - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-notifications-developing)
* Content Source: [dev-itpro/developer/devenv-notifications-developing.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-notifications-developing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by gggdttt** [comment]
Hi, 
Thank you so much for your feedback and solution. It will be updated in our next publish version. 😄 

Best regards,
