### ISSUE TITLE
i belive this document is total wrong !!

### ISSUE THREAD

**Issue by Markstewartpedersen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2432]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac07d83-45c1-324d-d292-b79e04939cdc
* Version Independent ID: 76985863-66fa-1583-7632-27949149d90c
* Content: [Upgrading AppSource Apps in Production - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrade-appsource-app-in-prod)
* Content Source: [dev-itpro/developer/devenv-upgrade-appsource-app-in-prod.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-upgrade-appsource-app-in-prod.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **freddyk**

**Comment by Markstewartpedersen** [comment]
upgrade should always be done via the admin and never via uninstalling . 
if there is some kind of error on the upgrade then you will not be able to roll back

**Comment by gggdttt** [comment]
Hi,
Thanks for your feedback. We will update the change in the next publish version.

Best regards,

**Comment by gggdttt** [comment]
Hi @Markstewartpedersen ,

Thank you so much for your suggestion.  I checked with developers but currently we only support such way to upgrade. What you worried is right. Could you go to this website https://experience.dynamics.com/ideas/ to share your idea?  Then we can schedule it. Here is the repo for doc only. 😸 

Best regards,
