### ISSUE TITLE
Error in Production and Sandbox types

### ISSUE THREAD

**Issue by yannj-fr** [MicrosoftDocs/dynamics365smb-devitpro-pb#2437]
There seams to be an error in the Production and Sandbox type, the type have been switched,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee7eedbd-9294-dd35-31b0-2a562f40b3ef
* Version Independent ID: ee7eedbd-9294-dd35-31b0-2a562f40b3ef
* Content: [Business Central Admin Center API - Environment Database Export - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api_environment_database_export)
* Content Source: [dev-itpro/administration/administration-center-api_environment_database_export.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/administration-center-api_environment_database_export.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
