### ISSUE TITLE
Not proper Example code  

### ISSUE THREAD

**Issue by DmitrijYudin** [MicrosoftDocs/dynamics365smb-devitpro-pb#2439]
It seems to me that Example code isn't so proper.

Initial code:
Text003: Label 'The original sentence is \\\\\: %1';
Text004: Label 'The sentence is converted to:\\\\ %1';

new code:
Text003: Label 'The original sentence is:\\\\%1';
Text004: Label 'The sentence is converted to:\\\\%1';

**Comment by gggdttt** [comment]
Hi @DmitrijYudin 
Thank you for your feedback, but we can not check which page contains the error without the link. Could you please go to the bottom of this page and click on the button **FeedBack->This Page** to report this issue?
Thank you so much 😸 
![image](https://user-images.githubusercontent.com/31087545/178250496-a4e4ce68-19f3-47fe-9845-f1943c6db48b.png)

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue because information is missing. Please open a new issue with topic information. Thanks.
