### ISSUE TITLE
Example of a request is not correct

### ISSUE THREAD

**Issue by zielus13** [MicrosoftDocs/dynamics365smb-devitpro-pb#2445]
Example of a request is actually a response. Trying to POST example request will raise "Invalid Request Body" error. To make it work you need to remove fields: id, name, taxAreaDisplayName and lastModifiedDateTime. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74270a57-78cf-d98a-d640-725f6740be26
* Version Independent ID: cb3f681d-baef-b0be-a828-45c7edfcde40
* Content: [Create customers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_customer_create)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_customer_create.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_customer_create.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by gggdttt** [comment]
Hi, 

Thank you for your feedback. It will be updated in our next publish version. 😸 

Best regards,
