### ISSUE TITLE
Links to Updates for On Prem Now Available

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#2447]
[Enter feedback here]

Making sure it's not forgotten - people can download the July Update for on-prem that resolves this issue, but the links section still says "Pending".

For example, v20 has Update 3 now:
https://support.microsoft.com/en-us/topic/update-20-3-for-microsoft-dynamics-365-business-central-on-premises-2022-release-wave-1-application-build-20-3-43026-platform-build-20-0-43007-6ea32067-5166-4c80-b635-af9c57bf42c5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d86d7ba3-2d51-943a-a341-0772b0ffcacf
* Version Independent ID: d86d7ba3-2d51-943a-a341-0772b0ffcacf
* Content: [Chromium browser issue affecting Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/chromium-browser-issue-affecting-business-central)
* Content Source: [dev-itpro/deployment/chromium-browser-issue-affecting-business-central.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/deployment/chromium-browser-issue-affecting-business-central.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **mikebc**

**Comment by edupont04** [comment]
Hej Jeremy,
Not exactly forgotten but pushed to today due to vacations. This will be fixed in the next doc update. Thanks for the reminder!

**Comment by edupont04** [comment]
Live since yesterday.

**Comment by JeremyVyska** [comment]
🥰  Thank you!  I was looking at it wanting to send this page to folks, since it's a great guide - was waiting for the links.
