### ISSUE TITLE
Wrong Property Value

### ISSUE THREAD

**Issue by JacekFijalkowski** [MicrosoftDocs/dynamics365smb-devitpro-pb#245]
Should be
Yes if zeros and No aren't displayed; otherwise, No. The default is No.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51978479-313d-d09f-fbe4-ffabf44ed1e4
* Version Independent ID: a32c966d-e3a7-b61b-5aa3-c4e7683854ca
* Content: [BlankZero Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/blankzero-property#feedback)
* Content Source: [dynamics-nav/BlankZero-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/BlankZero-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
