### ISSUE TITLE
Not proper Example code

### ISSUE THREAD

**Issue by DmitrijYudin** [MicrosoftDocs/dynamics365smb-devitpro-pb#2455]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00cbc1a8-c16b-9069-68bd-603b6040b672
* Version Independent ID: 86f2b783-bc69-f44b-6139-3a3c72f2cb89
* Content: [Text.ConvertStr(Text, Text, Text) Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-convertstr-method)
* Content Source: [dev-itpro/developer/methods-auto/text/text-convertstr-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/text/text-convertstr-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the example as suggested and the update will be published soon.
