### ISSUE TITLE
Re-publishing of System symbols is not mentioned in Minor Update guide

### ISSUE THREAD

**Issue by Pixelstrudel** [MicrosoftDocs/dynamics365smb-devitpro-pb#2456]
The _Installing a Minor Update_ article mentions unpublishing the System symbols as follows:

`Unpublish-NAVApp -ServerInstance $BcServerInstance -Name System`

However nowhere in this article the necessary re-publishing of the updated System extension is mentioned. This results in an error when following the documentation and trying to publish the System Application.

A guide on how to publish new System symbols can already be found in [Publishing, Upgrading, and Installing Extensions During Upgrade](https://docs.microsoft.com/de-de/dynamics365/business-central/dev-itpro/upgrade/upgrade-publish-extensions#publish-new-system-test-and-application-symbols) however this article is not mentioned until the _Upgrade Microsoft extensions step_ which is way too late.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1c6e3f3d-2927-52e9-f629-59c4f17c5b38
* Version Independent ID: 1c6e3f3d-2927-52e9-f629-59c4f17c5b38
* Content: [Install a version 20 update - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v20)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v20.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrading-cumulative-update-v20.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, 

Starting with version 18, it shouldn't be necessary to install the system symbols manually because the System extension should be installed by Invoke-NAVApplicationDatabaseConversion. I can't seem to repro this issue. Just to be sure, are updating version 20?

**Comment by Pixelstrudel** [comment]
> Hello,
> 
> Starting with version 18, it shouldn't be necessary to install the system symbols manually because the System extension should be installed by Invoke-NAVApplicationDatabaseConversion. I can't seem to repro this issue. Just to be sure, are updating version 20?

Good to know, that this should be obsolete since v18, thanks! However I did update from version 20.2 to 20.3 and got the message that the version already matches:

![image](https://user-images.githubusercontent.com/16477556/180235361-6aaeae56-dab6-4d9c-9518-bbd707cbdec9.png)

So I guess that is why the manual publishing of the symbols was necessary?

**Comment by jswymer** [comment]
Hi,

I'm not sure about this, actually. The 'application version`, in this case, and the platform version are both hardcoded, and independent of the symbols app version. I'm not sure why you got this error. I can get a similar message when I run the Invoke-NAVApplicationDatabaseConversion more than once.

**Comment by Pixelstrudel** [comment]
Weird. Since I got issues related to the new OnAfterIntermediateDocumentReady event with the manually published symbols I now created a support case for this any way. 

Anyhow I didn't know that publishing the System.app should be obsolete since v18 and the step missing from the guide is correct. So this can be closed.

**Comment by jswymer** [comment]
Perhaps I'll add a note in the article that states that the latest system symbols are published as part of Invoke-NAVApplicationDatabaseConversion. This might help avoid some confusion. 

Thanks for the feedback!
