### ISSUE TITLE
Get-NAVDataUpgrade has state "Completed" when the Upgrade is finished

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#2459]
In task 13, you give instructions to update the Application Version Information and synchronize it. You also give information that you have to wait until Get-NAVDataUpgrade returns `State = Operational` This will never happen because the State seems to get set to "Completed" at least for BC20. See my result for reference:
```
ExtensionData             : System.Runtime.Serialization.ExtensionDataObject
TenantId                  : default
TotalFunctionCount        : 12
ExecutedFunctions         : 12
UpgradeExecutionMode      : UsingParallelOrSerialTransaction
Progress                  : 100.00 %
Details                   : {}
Errors                    :
ExecutionDetails          : {BASE, BASE, BASE, BASE...}
ExecutionErrors           :
State                     : Completed
NumericProgress           : 1
IsTenantInExclusiveAccess : False
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8b81664-172f-fdaf-90d4-222624e4a6a9
* Version Independent ID: f8b81664-172f-fdaf-90d4-222624e4a6a9
* Content: [Upgrading Version 15, 16, 17, or 18 Base Application to Version 20 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v20#task-8-synchronize-tenant)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v20.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v20.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
We've corrected the article as suggested. It will be published soon. Thanks for the feedback!
