### ISSUE TITLE
Reference to release wave 1 should read release wave 2

### ISSUE THREAD

**Issue by PeterBizz** [MicrosoftDocs/dynamics365smb-devitpro-pb#2461]
small mistake:
Starting from 2022 release wave 2, the Dynamics 365 Business Central server is running on .NET Standard and if you are using on-premises .NET add-ins that targets .NET Framework, you need to convert them to use .NET Standard, because add-ins compiled with .NET Framework will stop working in Business Central 2022 release wave **1.**

Starting from 2022 release wave 2, the Dynamics 365 Business Central server is running on .NET Standard and if you are using on-premises .NET add-ins that targets .NET Framework, you need to convert them to use .NET Standard, because add-ins compiled with .NET Framework will stop working in Business Central 2022 release wave **2**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Version Independent ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Content: [Migrating from .NET Framework to .NET Standard - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard)
* Content Source: [dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md)
* Service: **dynamics365-business-central**
* GitHub Login: @KennieNP
* Microsoft Alias: **kepontop**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The article has been fixed in one of our latest doc refreshes.
