### ISSUE TITLE
error in article

### ISSUE THREAD

**Issue by LuvkyDave** [MicrosoftDocs/dynamics365smb-devitpro-pb#2467]
Configure the Business Central Server for multitenancy
To set up the Business Central Server instance for multitenancy, make the following changes to the server instance configuration:

Enable the Multitenant setting.
Set the server instance to connect to the application database by changing these settings: DatabaseServer, DatabaseServer, and DatabaseServer.

Last section should read -

Set the server instance to connect to the application database by changing these settings: DatabaseServer, DatabaseInstance , and DatabaseName.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369ef361-8740-4777-2f6d-32e73df71e43
* Version Independent ID: e2d76464-650f-3a97-d15c-f6d50245bfa4
* Content: [Manage Application and Tenant Databases in a Multitenant Deployment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/multitenant-setup-guide)
* Content Source: [dev-itpro/administration/multitenant-setup-guide.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/multitenant-setup-guide.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and the update will be published soon.
