### ISSUE TITLE
same link three times

### ISSUE THREAD

**Issue by KSH-audibene** [MicrosoftDocs/dynamics365smb-devitpro-pb#247]
After "See Also" there is three identical links 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2b76c5-f423-c043-45dd-ca14112dc273
* Version Independent ID: 681d5096-daa4-5413-629e-793624a377c7
* Content: [Word Report Layouts on Custom XML Parts - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/custom-xml-part-overview-for-word-report-layouts)
* Content Source: [dynamics-nav/Custom-XML-Part-Overview-for-Word-Report-Layouts.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Custom-XML-Part-Overview-for-Word-Report-Layouts.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Yeah, that seems to be a little too much :) Thanks for the feedback, this will be fixed with the next doc refresh.
