### ISSUE TITLE
Broken Markdown Table

### ISSUE THREAD

**Issue by njackson1582** [MicrosoftDocs/dynamics365smb-devitpro-pb#2473]
Broken markdown table on this page: 

![image](https://user-images.githubusercontent.com/92820461/181507256-b525e12b-39ea-4d52-8b2b-71a6b53829a5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85df9a62-d76a-2103-43aa-494c591fa6aa
* Version Independent ID: cbf95b02-bc23-f9f2-7cce-d623cea6b813
* Content: [Ruleset for the Code Analysis Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools)
* Content Source: [dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
We've fixed the table. The update will be published soon. Thanks for the feedback!
