### ISSUE TITLE
I can't add "Authorization" tag..

### ISSUE THREAD

**Issue by aconcato** [MicrosoftDocs/dynamics365smb-devitpro-pb#248]
I can't add Key called "Authorization"... 

contentHeaders.Add('Authorization', 'Basic xxx');

Error: "Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0e98450-9f21-aeea-f030-0ba4990d6e4e
* Version Independent ID: 10a90ae1-94d4-9db8-a853-533737c8b4fb
* Content: [Add Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpheaders/httpheaders-add-method)
* Content Source: [dev-itpro/developer/methods-auto/httpheaders/httpheaders-add-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/httpheaders/httpheaders-add-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, can you try and use HttpHeaders.Add(Name: String, Value: String)? Thanks.

**Comment by aconcato** [comment]
Hi Susanne,
Yes I'm doing this..
contentHeaders is variable contentHeaders: HttpHeaders;
but the error is the same
