### ISSUE TITLE
Incorrect or incomplete information on availability.

### ISSUE THREAD

**Issue by sd484** [MicrosoftDocs/dynamics365smb-devitpro-pb#2481]
As far as I know the isolated events have been added with release 2022, wave 1 (v. 20)/ runtime 9.0. 
Unfortunately the documentation on the InternalEvent/ IntegrationEvent/ BusinessEvent Atribute does not show any information about availability of the event argument "Isolated". Availability is indicated as follows:

- InternalEvent Attribute: Version: Available or changed with runtime version 4.0.
- IntegrationEvent Attribute: Version: Available or changed with runtime version 1.0.
- BusinessEvent Attribute: Version: Available or changed with runtime version 1.0.

In my opinion, either the availability should be specified for the individual parameter, or the general specification of the attribute should be adjusted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 991e2674-d0e7-683b-dd7d-5fd0420ff91a
* Version Independent ID: 683eff1d-947e-869b-08a3-cec91920f30a
* Content: [InternalEvent Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-internalevent-attribute)
* Content Source: [dev-itpro/developer/attributes/devenv-internalevent-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/attributes/devenv-internalevent-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. I agree that the granularity of when parameters are introduced would be nice to have. It would, however, require a change in our tooling, if it's even possible to harvest that specific information. Currently we do not have bandwidth to implement this. But I will instead encourage you to post this as an [Idea](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature and if this is upvoted, we might be able to take it into consideration. Thanks.

**Comment by sd484** [comment]
Why not adding a note to those help pages with the information since when a specific parameter is available, if added after initial release?
