### ISSUE TITLE
Handling UTC dates in AL

### ISSUE THREAD

**Issue by wmstreet** [MicrosoftDocs/dynamics365smb-devitpro-pb#249]
I am receiving a UTC date from an external web service call, it is in the format
2018-11-06 21:25:06
Which in US Eastern Time would be 11/6/2018 4:25PM.
In C/AL we used dotnet System.DateTime calls to properly convert to a DateTime variable.
In AL we tried using TypeHelper function EvaluateUTCDateTime, but with the above format, it just returns an empty datetime.  Could I receive some feedback on the recommended way to accomplish this.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This is a bug, can you please file it in this repo: https://github.com/Microsoft/ALAppExtensions - I will then close the issue here on the documentation repo. Thanks.
