### ISSUE TITLE
Compatibility matrix page - broken markdown link in "Version 17 compatibility" section

### ISSUE THREAD

**Issue by ViliusMink** [MicrosoftDocs/dynamics365smb-devitpro-pb#2495]
The last row of the table within ["Version 17 compatibility"](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility#version-17-compatibility) section contains a cell value that looks like:
`[19.7](https://support.microsoft.com/help/5014490|20.1|`

It seems like there is a missing ')' symbol at the end of the link, which also ruins the next cell (20.1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8868c4-fb29-4b1f-e8ba-7560642481fc
* Version Independent ID: e838d8a4-07b9-02a8-f0b5-756220b3e64d
* Content: [Business Central compatibility matrix - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility)
* Content Source: [dev-itpro/upgrade/upgrade-v14-v15-compatibility.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-v14-v15-compatibility.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
We've fixed the article and the update will be published soon. Thanks for the feedback!
