### ISSUE TITLE
V2.0 Documentation

### ISSUE THREAD

**Issue by dydent** [MicrosoftDocs/dynamics365smb-devitpro-pb#2496]
- It would be great to have a documentation for the Business Central API V2.0 just as there is one vor V1.0.
- Is there one that can be found or is it planned it release one in the near future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8eb2c50-c0d1-7e64-0d00-8ad72f8a968a
* Version Independent ID: f0fd2b39-733e-c38d-ad5f-02f6538d06e6
* Content: [API(V2.0) for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/)
* Content Source: [dev-itpro/api-reference/v2.0/index.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the topic that you link to here is v2.0 of the BC API. If you're looking for the v1.0 you can find it here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v1.0/. Hope this helps? Thanks

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
