### ISSUE TITLE
Typo "Nessage"

### ISSUE THREAD

**Issue by DominicMatheis** [MicrosoftDocs/dynamics365smb-devitpro-pb#2498]
[Enter feedback here]
Typo "Nessage"

![image](https://user-images.githubusercontent.com/35301079/184129397-b9688c7f-bbb3-4dad-9f2b-12bbbae5b302.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc55fbd6-d3a1-b67b-0698-32a7c4d48fbc
* Version Independent ID: 23783867-a29a-e92d-e92c-ba404e08f5a7
* Content: [Progress Windows, Message, Error, and Confirm Methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-progress-windows-message-error-and-confirm-methods)
* Content Source: [dev-itpro/developer/devenv-progress-windows-message-error-and-confirm-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-progress-windows-message-error-and-confirm-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be fixed with the next release of the docs. Thanks.
