### ISSUE TITLE
several issues with install guide

### ISSUE THREAD

**Issue by CanuckNav74** [MicrosoftDocs/dynamics365smb-devitpro-pb#25]
forgive the typo in the git issue title - this pertains to the data upgrade guide. 

I used this guide to upgrade a Canadian NAV2016 CU3 customer to NAV2018 CU3. Found several issues with the documented data upgrade procedure:

Task 1.4: modify 130400 CAL Test Runner and 130402 CAL Command Line Test Runner from the old dev environment
It states this step is needed for NAV2016 and earlier if these codeunits are present. In our nav 2016 dev environment, there was no "TestPermissions" data type in the C/AL editor, making it impossible to modify these codeunits as this step suggests. At any rate, our earlier merge of the application objects via the Merge-NavApplicationObject cmdlet ensured these codeunits would have the parameters that the data upgrade expects in the upgrade .fob my merge efforts produced. 

Task 7: Clear Dynamics NAV Server instance records from old database
Microsoft should add another T-SQL task AFTER that step. If there are records in the "Debugger Breakpoint" table, the data upgrate will fail at task 9 (Import the upgraded application objects and upgrade toolkit objects into the converted database). Those records have to be purged.
This needs to be executed via SQL Management studio BEFORE task 9 is executed:
DELETE from [My NAV Database Name].[dbo].[Debugger Breakpoint] 

Task 9: Import the upgraded application objects and upgrade toolkit objects into the converted database.
Documentation is INCOMPLETE for certain regions. In the case of my upgrade (Canadian NAV 2016 to NAV 2018), as per pre-requisite #2, I grabbed Upgrade9001100.FOB (the upgrade toolkit objects for NAV 2016 to NAV 2018). However, after following all the steps (import the nav 2018 app objects fob, THEN the toolkit fob)

however....

Step 13 (synchronize schema with validation) FAILED as it detected destructive changes. Below is the error I received from the admin powershell when I tried to sync the schema with validation:

Sync-NAVTenant : The schema synchronization may result in deleted data. The following destructive changes were detected:
Table: 4, Currency
Field: 10000, Symbol: Deleted
Table: 79, Company Information
Field: 10018, US Country/Region Code: Deleted
Field: 10019, Canada Country/Region Code: Deleted
Field: 10020, Mexico Country/Region Code: Deleted
Table: 81, Gen. Journal Line
Field: 10005, Check Exported: Deleted
Field: 10007, Check Transmitted: Deleted
Table: 311, Sales & Receivables Setup
Field: 10000, G/L Freight Account No.: Deleted
Examples of code to migrate data:
DataUpgradeMgt.SetTableSyncSetup(DATABASE::"Currency",[Upgrade Table Id],TableSynchSetup.Mode::[Mode]);
DataUpgradeMgt.SetTableSyncSetup(DATABASE::"Company Information",[Upgrade Table Id],TableSynchSetup.Mode::[Mode]);
DataUpgradeMgt.SetTableSyncSetup(DATABASE::"Gen. Journal Line",[Upgrade Table Id],TableSynchSetup.Mode::[Mode]);
DataUpgradeMgt.SetTableSyncSetup(DATABASE::"Sales & Receivables Setup",[Upgrade

This was very puzzling, until I discovered the .fob contents in the DVD > UpgradeToolkit > Local Objects. There is no mention of these localized objects in this guide, nor their importance to the data upgrade workflow. Secondly, I don't think the file should have been named Upgrade9001100.US.fob. This clearly affects both Canada and presumably Mexico as well. Shouldn't these localized files be named "UpgradeXXXXXXX.NA.fob"? For a new-comer who has never upgraded a database before, I found this missing piece of important information extremely frustrating. 

At any rate, to resolve this I imported the following fobs (synchronize schema >> later)  in the following order for my 2016 to 2018 upgrade:

1) import the upgraded/merged .fob of ALL NAV2018 objects 
2) import Upgrade9001100.FOB 
3) import Upgrade9001100.US.FOB 

Doing so allowed me to successfully sync with validation @ step 13 and proceed with finishing the data upgrade. 

Please correct the documented steps accordingly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec2bde3-7aa2-0d9b-2d60-0fc57aa85645
* Version Independent ID: c37bcc83-3482-b533-8e9a-8feb56a6b88e
* Content: [Upgrading the Database - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/upgrading-the-data)
* Content Source: [dynamics-nav/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Upgrading-the-Data.md)
* Service: **unspecified**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the valuable feedback! The issues have been addressed, and the content updated accordingly. The updates will be available the next time we refresh the content. 

As for the name of the local upgrade toolkit fob file, I spoke with the development team. As you experienced, the US fob file covers all the languages in the NA version. For whatever reason, the name has always included US, not NA. We realize that it is confusing, and will look into possibly changing this in the future.

Thanks again

**Comment by CanuckNav74** [comment]
Thank you for the follow-up - always happy to provide input
