### ISSUE TITLE
 .NET Portability Analyzer not avalaiable for VS 2022

### ISSUE THREAD

**Issue by dwilliss** [MicrosoftDocs/dynamics365smb-devitpro-pb#2506]
This page mentions the  .NET Portability Analyzer.
It turns out that this VS extension is not available for Visual Studio 2022.
It does appear to be available for Visual Studio 2019.

You could modify the page to mention that fact or go bug the team who works on that extension to update it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Version Independent ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Content: [Migrating from .NET Framework to .NET Standard - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard)
* Content Source: [dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md)
* Service: **dynamics365-business-central**
* GitHub Login: @KennieNP
* Microsoft Alias: **kepontop**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We'll update the topic to mention that. Will be available with the next refresh of the docs. Thanks.
