### ISSUE TITLE
Runtime 9.1 and 9.2 is missing

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#2507]
Runtime 9.1 and 9.2 is missing from this page.

9.1 works from BC20.1 (ref. https://www.yammer.com/dynamicsnavdev/threads/1867199253872640)
9.2 works from BC20.4 (but not on SaaS currently, it seems - ref. https://www.yammer.com/dynamicsnavdev/threads/1876697947463680)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bac24fa-c9eb-695a-bdd5-3dbe4109a0dc
* Version Independent ID: a09fc47a-123f-a136-d4e5-e986dfc94522
* Content: [Choosing Runtime Version in AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-choosing-runtime)
* Content Source: [dev-itpro/developer/devenv-choosing-runtime.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-choosing-runtime.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next refresh of the docs.
