### ISSUE TITLE
Typo : ReadTet > ReadText

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#2512]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d18c1c7a-f4d0-83ff-d98c-53fac1217223
* Version Independent ID: 1eeae16c-253e-c94e-ac57-edfae49e8b95
* Content: [InStream.EOS() Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/instream/instream-eos-method)
* Content Source: [dev-itpro/developer/methods-auto/instream/instream-eos-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/instream/instream-eos-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This will be fixed with the next refresh of the docs.
