### ISSUE TITLE
Can we have better description?

### ISSUE THREAD

**Issue by tinfister** [MicrosoftDocs/dynamics365smb-devitpro-pb#2513]
Description of attachments API is misleading. See this issue from 3 years ago
https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/674

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51edc43-5bc1-0c5b-7772-dbd64f2050e2
* Version Independent ID: 412ca319-7903-8726-e6b5-f00191903faa
* Content: [attachment resource type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/resources/dynamics_attachment)
* Content Source: [dev-itpro/api-reference/v2.0/resources/dynamics_attachment.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/resources/dynamics_attachment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for bringing this up again. The naming is not going to change, so we have added extra information in the topics to be specific the attachment definition here. Will be available with the next doc refresh. Thanks.
