### ISSUE TITLE
Error AL0132 when try to publish

### ISSUE THREAD

**Issue by DynamiaDevelopmentGIT** [MicrosoftDocs/dynamics365smb-devitpro-pb#2515]
hi,

I got more than 2000 error lines such as 

'DotNet "System.Security.Cryptography.SHA512Managed"' does not contain a definition for 'Dispose'
'DotNet "System.Version"' does not contain a definition for 'TryParse'

i have add al.assemblyProbingPaths in user settings in VScode as follow:
"al.assemblyProbingPaths": [
  "./.netpackages",
  "C:/Windows/assembly/",
  "C:\\Program Files\\Microsoft Dynamics 365 Business Central\\200\\Service",
  "C:\\Program Files (x86)\\Microsoft Dynamics 365 Business Central\\200",
  "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\WindowsPowerShell",
  "C:/Program Files/Assemblies",
  "C:\\Program Files\\Microsoft Dynamics 365 Business Central\\200\\Service\\Add-ins\\",
  "C:\\Windows\\Microsoft.NET\\Framework\\",
  "C:\\Windows\\Microsoft.NET\\Framework64\\",
  "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\"
]

Am i missing something? 
thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146303e1-568e-7a5c-ea4f-b40afbc503fc
* Version Independent ID: 53de4696-feb9-ff31-160e-a858a0be3d40
* Content: [Publishing a Code-Customized Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-publish-code-customization)
* Content Source: [dev-itpro/developer/devenv-publish-code-customization.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-publish-code-customization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. We're not able to help you look into this particular issue, which could be caused by a specific setup. The topic was validated to work with the scenario described. Please use your usual support channel for further troubleshooting. Thanks.
