### ISSUE TITLE
Get ItemProperties 

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/dynamics365smb-devitpro-pb#253]
Hello,

Is there a list of subtables linked to articles? For example the ItemAttributes, Dimensions, Attachments, Special Prices?

When I issue the request described above in the article I get all basic info that is directly on the specific item.
I can append /defaultDimensions to the url to get the dimensions but is there a way to get for example "Attributes" or other tables that are linked to an "Item"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e48baa0-43d9-8e1b-64f4-a54fef7b8eb5
* Version Independent ID: d2f82b0a-493b-1a37-f97c-ee4618c5419f
* Content: [Get items - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_item_get)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_item_get.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_item_get.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
If you view the metadata (/$metadata) you can see all 'NavigationProperty'. A NavigationProperty can be included in the request using the $expand: /companies({{companyId}})/items{{itemId}}/?$expand=picture,defaultDimensions,itemCategory
Or it can be navigated to directly like you do with defaultDimensions.

What scenario are you looking into and which entities are needed?

**Comment by egbertwietses** [comment]
https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-how-work-item-attributes

We are trying to receive and set the item attributes

**Comment by Mr-Pingu** [comment]
Thanks for your reply. This isn't however what I want to achieve. For defaultDimensions and ItemCategory. I can acces them directly but as my colleague above said we are looking into a way to receive and set itemattributes. 

Not only Itemattributes but also other attributes that can be found in underlaying table. Like Item No2, which is a field on Table 27 but not exposed to the API or even the GUI.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. I will close this issue and kindly ask you to provide product feedback by, for example, using the Product feedback button at the bottom of a Help topic. Thanks again.
