### ISSUE TITLE
Typo at the end of header section

### ISSUE THREAD

**Issue by Kowa63** [MicrosoftDocs/dynamics365smb-devitpro-pb#2530]
Last sentence in Header seems to have a typo at the end, should be 2 instead of 1.
"will stop working in Business Central 2022 release wave 1".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Version Independent ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Content: [Migrating from .NET Framework to .NET Standard - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard)
* Content Source: [dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md)
* Service: **dynamics365-business-central**
* GitHub Login: @KennieNP
* Microsoft Alias: **kepontop**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next refresh of the docs.
