### ISSUE TITLE
Parameters, please?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2531]
Hi,
Try as I might, I cannot seem to find any documentation on minimum/maximum/default lengths for Text, Label, TextConstant data types. The Label page gives an example that uses the MaxLength property

`var
    a : Label 'Label Text', Comment='Foo', MaxLength=999, Locked=true;`

but no mention of how big MaxLength can actually be. Or what the length is if none is specified. It is very helpful when developing, to know these parameters.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15813f6-f9d6-5008-5d18-c69fd4f0f761
* Version Independent ID: 0ac4ae64-4482-818b-b0fd-0b59f7d7a962
* Content: [Label Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/label/label-data-type)
* Content Source: [dev-itpro/developer/methods-auto/label/label-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/label/label-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. The article has been updated since this issue, explaining that "If no maximum length is specified, the string can be any length." Closing. Thanks.
