### ISSUE TITLE
Please make more clear that Restrictive is default value

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2532]
Now the topic says:

Value | Description
------ | ------
 Restrictive | This is the default value. Setting the Restrictive value will cause the permission execution context of every test in the codeunit to be set by default to 'D365 Full Access’. It is required to lower the level of permissions within every test to any permission sets other than 'D365 Full Access’. Otherwise, it will result in a runtime error. The change of the permission execution context is supported by Codeunit "Library - Lower Permissions". 

In this "default" does not show out well. It could be bold faced or put next sentence on a next line.

**Justification**: apparently there are question that relate to the fact that this is the default value, so, IMHO we need to put stress more on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9a88b1-f7e9-e4cb-6b06-4d9e11ef4e35
* Version Independent ID: c9b7c384-2643-75e6-c9cd-308d3b77042f
* Content: [TestPermissions Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-testpermissions-property)
* Content Source: [dev-itpro/developer/properties/devenv-testpermissions-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-testpermissions-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. It does not stand out in the table definition, but it is called out in the Remarks section: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-testpermissions-property#remarks. We auto-generate the table that you see in the topic, and in the source code we don't use markdown, which is why we have chosen to repeat the info in the Remarks section. Hope this makes sense. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue for now. Thanks.
