### ISSUE TITLE
Code example/preview is wrong

### ISSUE THREAD

**Issue by davewe04** [MicrosoftDocs/dynamics365smb-devitpro-pb#2535]
Hello.
I just regonized that the code example on this page is wrong. The label text ends with a double quotation mark instead of a single or half quotation mark. Thereby the hole begin-end statement is colored orange. Maybe just a little mistake, but it can cause some confusion. Especially if you copy paste the entire code :D

Kind regards,
davewe04

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa5d32e0-32cd-9b9b-7b7f-ad113f8b161a
* Version Independent ID: 476a26b8-0e62-d07b-57bb-acb32df88b8d
* Content: [System.Time() Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-time-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-time-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/system/system-time-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. It will be fixed with the next push to live of the docs.
