### ISSUE TITLE
It would be great if you could update a product based on number

### ISSUE THREAD

**Issue by egbertwietses** [MicrosoftDocs/dynamics365smb-devitpro-pb#254]
Now microsoft forces 3rd party's to store business central reference id in order to update an item

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e66208b-b5fb-56c6-d79f-9a265dbe70d4
* Version Independent ID: edc41b5f-6e39-e586-82f2-e97578d22f76
* Content: [Update items - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_item_update)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_item_update.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_item_update.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello - please use the Product feedback button from the topic - this repo is meant for documentation feedback only. Thanks.
