### ISSUE TITLE
Error in Example

### ISSUE THREAD

**Issue by ThomasBrodkorb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2543]
The timestamp server referenced in the example does not exist anymore.
I used http://timestamp.digicert.com instead

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21426684-ae01-f266-f21c-065bb2499692
* Version Independent ID: c8058293-0160-a4cf-6706-f904349eb194
* Content: [Sign an APP Package File - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sign-extension)
* Content Source: [dev-itpro/developer/devenv-sign-extension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-sign-extension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
