### ISSUE TITLE
Compiler Warning AL0717 is confusing

### ISSUE THREAD

**Issue by mitrov** [MicrosoftDocs/dynamics365smb-devitpro-pb#2544]
> The property '**TableRelation' **or** the property 'CalcFormula**' is required for the field '{0}' in {1} '{2}' because the field's property '**FieldClass**' is set to '**FlowField**'.

Hi,
I have some questions about warning AL0717.

First, see this post from Luc: https://twitter.com/lucvanvugt/status/1572475036824440838

The questions are:
What's the point of this warning?
Why does the warning imply that the property TableRelation has something to do with FlowFields and CalcFormula?

My understanding is that a FlowField always has to have a CalcFormula.
If a FlowField is defined as editable, then maybe one could additionally specify the TableRelation to make sure that the users type in only values which are allowed. But that's optional and not really used a lot (if at all).

Best,
Džoka 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5f8acf9-59b0-31ec-0ada-69e42d60d8f2
* Version Independent ID: d5f8acf9-59b0-31ec-0ada-69e42d60d8f2
* Content: [Compiler Warning AL0717 - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al717)
* Content Source: [dev-itpro/developer/diagnostics/diagnostic-al717.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/diagnostics/diagnostic-al717.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug or a question about the product. Please use your usual support channel to file a bug. Thanks.
