### ISSUE TITLE
 AL0717 "either TableRelation **or** CalcFormula on a FlowField" does not make sense.

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2545]
IMHO it does not make sense to set either TableRelation **or** CalcFormula on a FlowField.

As I asked on [twitter](https://twitter.com/lucvanvugt/status/1572475036824440838): Does it make sense at all to set TableRelation?

This question was answered, but still **or** does not make sense. You always have to set **CalcFormula **, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5f8acf9-59b0-31ec-0ada-69e42d60d8f2
* Version Independent ID: d5f8acf9-59b0-31ec-0ada-69e42d60d8f2
* Content: [Compiler Warning AL0717 - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al717)
* Content Source: [dev-itpro/developer/diagnostics/diagnostic-al717.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/diagnostics/diagnostic-al717.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by mitrov** [comment]
Hey Luc ;-)

https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2544

**Comment by lvanvugt** [comment]
Thanx @mitrov, abd even better then mine. Before I reported I checked in the topic _View all page feedback_, and there was nothing. ;-)
