### ISSUE TITLE
n

### ISSUE THREAD

**Issue by Amonkipt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2547]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f977f692-d1a6-2b82-9ece-15816b81644b
* Version Independent ID: f977f692-d1a6-2b82-9ece-15816b81644b
* Content: [Compiler Error AL0249 - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al249)
* Content Source: [dev-itpro/developer/diagnostics/diagnostic-al249.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/diagnostics/diagnostic-al249.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Looks like this issue was created by mistake. Closing
