### ISSUE TITLE
There is now an extra menu step to find the Personal access tokens page

### ISSUE THREAD

**Issue by ashirokikh** [MicrosoftDocs/dynamics365smb-devitpro-pb#2548]
Hi folks,

In order to find Personal access tokens page, we need to go to Settings -> Developer Settings -> Personal access tokens. It's no longer on the main pane on the left. Please update the path to make instructions clearer. 

![image](https://user-images.githubusercontent.com/17916422/192438546-05f9aa7c-1af4-4ffa-a075-04d202640e90.png)

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49174b9e-9063-6b52-0458-de643578771b
* Version Independent ID: 49174b9e-9063-6b52-0458-de643578771b
* Content: [Update AL-Go System Files - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/al-go/algo-update-system-files)
* Content Source: [dev-itpro/al-go/algo-update-system-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/al-go/algo-update-system-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @freddyk
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next refresh of the docs.
