### ISSUE TITLE
Example `GetUserNameFromSecurityId()` has wrongly/poorly named parameter variable, too much indentation

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2556]
Some syntactical and cosmetic errors here:

![image](https://user-images.githubusercontent.com/63455896/193253795-d17db246-7458-4109-a413-408f38d201a1.png)

* The parameter is named in `camelCase`, but your standard is `PascalCase`.
* The parameter is named different in the argument list, vs. its use in the body - and that means this won't compile.
* Lines after the 1st are indented one stop too far.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a94f5d0b-5b58-a07b-b25f-1a110abe099a
* Version Independent ID: 2cf485d7-57d6-3713-0b69-2628df305e35
* Content: [Table System fields - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-system-fields#audit)
* Content Source: [dev-itpro/developer/devenv-table-system-fields.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-table-system-fields.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
