### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by Kwok-he-Chu** [MicrosoftDocs/dynamics365smb-devitpro-pb#2557]
Rename "_custome telemtery_" to "_custom telemetry_"

This can be found in subsection "_To configure custom **telemtery** logging to the Windows Application log by using the Business Central Server Administration tool_" - https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/disable-logging-events-windows-application-log

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24aca21e-77e8-7d40-ef6f-c5d4ba01c909
* Version Independent ID: f32c8de9-5503-2260-3673-62d3d5e5f67d
* Content: [Disable Logging Events to the Windows Application Log - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/disable-logging-events-windows-application-log)
* Content Source: [dev-itpro/administration/disable-logging-events-windows-application-log.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/disable-logging-events-windows-application-log.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
