### ISSUE TITLE
Wrong references

### ISSUE THREAD

**Issue by kwettermann** [MicrosoftDocs/dynamics365smb-devitpro-pb#256]
The references to InvokeExtensibilityMethod and GetImageResource are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d0df0f4-4a47-ac16-3a37-a18d04987bcf
* Version Independent ID: b755489a-52d2-fa1c-dda8-f6e2dfce983b
* Content: [Asynchronous Considerations for Control Add-ins - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-control-addin-asynchronous-considerations)
* Content Source: [dev-itpro/developer/devenv-control-addin-asynchronous-considerations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-control-addin-asynchronous-considerations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi! Thank your for your feedback! The links are fixed and the update of this topic will be available soon.
