### ISSUE TITLE
AutoUpdate property default value is false, not true

### ISSUE THREAD

**Issue by christian-clausen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2563]
I believe the AutoUpdate property default value is false, not true. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b30b2bf4-ae84-3700-152f-3a349d221087
* Version Independent ID: 2e5a66a7-bdc1-e7b4-5923-cde9a6486310
* Content: [AutoUpdate Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-autoupdate-property)
* Content Source: [dev-itpro/developer/properties/devenv-autoupdate-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-autoupdate-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
