### ISSUE TITLE
Your "good example" gives error in VSC

### ISSUE THREAD

**Issue by agerstroma** [MicrosoftDocs/dynamics365smb-devitpro-pb#2564]
[Enter feedback here]
"Label" gives error and suggests use of "label" instead.
Your code uses "Label"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07ad8bd3-2712-42b5-4647-c26d90852435
* Version Independent ID: fc42bbd3-e20d-400f-926e-b48b83d0717e
* Content: [CodeCop Warning AA0241 - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0241)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0241.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/analyzers/codecop-aa0241.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
