### ISSUE TITLE
Update Documenation - Property "PageNo" Only Relevant for Sections

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#2565]
Could you please add to the documentation, that this property was only relevant for reports till 2009 with old report layout format ("Sections). 

Similar as you did it for the property `createtotals`.

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/reportinstance-createtotals-decimal-decimal-method
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2f69c6a-f2a2-4be9-4b31-f9f2ff2928ee
* Version Independent ID: 25ba9ba3-39af-5434-5ac1-55e25fabdc18
* Content: [Report.PageNo(\[Integer\]) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/reportinstance-pageno-method)
* Content Source: [dev-itpro/developer/methods-auto/report/reportinstance-pageno-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/report/reportinstance-pageno-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next doc refresh.
