### ISSUE TITLE
The index seems to be off by 1.

### ISSUE THREAD

**Issue by DuttaSoumya** [MicrosoftDocs/dynamics365smb-devitpro-pb#2566]
Instead of the following line,
`The index of the element in the JsonArray that you want to retrieve.`

please change it to 
`The zero- based index of the element in the JsonArray that you want to retrieve.`

Indices in Business Central are always 1- based. So this is really an exception it seems- may be even a bug!
This means that all functions on JsonArrays that use indexes should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48f5c8ec-fa98-7869-bcb7-7b55feb4aef4
* Version Independent ID: 069473b9-c74f-60f7-a090-ba747f0daf39
* Content: [JsonArray.Get(Integer, var JsonToken) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonarray/jsonarray-get-method)
* Content Source: [dev-itpro/developer/methods-auto/jsonarray/jsonarray-get-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/jsonarray/jsonarray-get-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The JsonArray is 0-based by design. The articles for this data type will be updated with the next doc refresh.
