### ISSUE TITLE
Misleading Information about Report.PageNo

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#2567]
On this page it says that Report.PageNo "Gets or sets the current page number of a report.", but that was true for Dynamics NAV 2009 version and before, but since Dynamics NAV 2013 nothing is doing. So this has been resolved and should be reflected in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2f69c6a-f2a2-4be9-4b31-f9f2ff2928ee
* Version Independent ID: 25ba9ba3-39af-5434-5ac1-55e25fabdc18
* Content: [Report.PageNo(\[Integer\]) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/reportinstance-pageno-method)
* Content Source: [dev-itpro/developer/methods-auto/report/reportinstance-pageno-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/report/reportinstance-pageno-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We've added a remark to this deprecated method. Will be available with the next doc refresh.
