### ISSUE TITLE
Compiler Warning AL0729 "Promoted can only be set..." is wrong

### ISSUE THREAD

**Issue by craigbarberini-theta** [MicrosoftDocs/dynamics365smb-devitpro-pb#2568]
I think this warning is invalid because actions do not only open pages. For example, this warning gets raised for promoted actions that execute the action using the OnAction trigger. I think this warning should only be raised if the RunObject is a page.

Warnings: 
![image](https://user-images.githubusercontent.com/45742682/194729293-d6d9b626-a57c-44be-8df1-3cc418b15d65.png)
Example:
![image](https://user-images.githubusercontent.com/45742682/194729571-1a176bad-ef73-477b-a332-239d827c236e.png)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
