### ISSUE TITLE
API endpoint url for On-Prem is incorrect

### ISSUE THREAD

**Issue by kfuglsang** [MicrosoftDocs/dynamics365smb-devitpro-pb#257]
The correct url for the On-Prem API is:
https://&lt;base URL&gt;:&lt;port&gt;/&lt;instance&gt;/api/&lt;API version&gt;/

E.g.
https://nav.contoso.com:7048/NAV/api/beta/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17c4eef7-2ff2-eeeb-d285-095002e99475
* Version Independent ID: 2beae6be-8b5f-2a48-4b68-81810248b8f6
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics)
* Content Source: [dynamics-nav/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/endpoints-apis-for-dynamics.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback and the long wait. This topic has been updated now. Thanks.

**Comment by UrsWedershoven** [comment]
Not really. The URL still is in the wrong format for OnPrem Access. The article dates to March 2018, so it does not seem likely that there was an update.
