### ISSUE TITLE
Wrong deployment link for  "Action available updates from an Adaptive Card in Teams"

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#2570]
Section https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-notifications#action-available-updates-from-an-adaptive-card-in-teams (Action available updates from an Adaptive Card in Teams)

have wrong deployment link - it will deploy logicapp for "Take action on failed environment updates" (the link is same).

Thanks for fixing it.

With regards

Kamil S.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2082993f-bc69-4992-1b99-276a4c20a055
* Version Independent ID: 0bb64a14-6711-663b-9381-1684fb492927
* Content: [Manage Tenant-Specific Notifications - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-notifications)
* Content Source: [dev-itpro/administration/tenant-admin-center-notifications.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/tenant-admin-center-notifications.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thanks for catching this, Kamil! We'll get it fixed as soon as possible.

**Comment by kine** [comment]
You are welcome. I have noticed that the needed example is not still published in the github repo (I can see some internal repo URL on the BC Launch Event video).

**Comment by edupont04** [comment]
Hi Kamil,
Sorry for the delay, but the article was updated last week: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-notifications#example-post-adaptive-cards-in-teams-for-each-available-environment-update
