### ISSUE TITLE
Mistake in the Example 2

### ISSUE THREAD

**Issue by RadoArvay** [MicrosoftDocs/dynamics365smb-devitpro-pb#2574]
Shouldn't be there a different definition of variable in the Example 2?
```al
- Text000: Label 'Progress from 0 to 9999 #1#####';
+ Text000: Label 'Progress from 0 to 9999 @1@@@@@';
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 163dedae-669d-4f9e-da19-f9812a0a96ab
* Version Independent ID: 22554382-887c-84da-7d21-51b81912c733
* Content: [Dialog.Open(Text \[, var Any,...\]) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-open-method)
* Content Source: [dev-itpro/developer/methods-auto/dialog/dialog-open-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/dialog/dialog-open-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Yes, it definitely should. This will be fixed with the next doc refresh.
