### ISSUE TITLE
Missing version hint

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#2577]
It should be mentioned that the content applies only to BC 21 (2022 release wave 2) or higher.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3474ed-8683-48de-1aae-9042f324445d
* Version Independent ID: 8d3474ed-8683-48de-1aae-9042f324445d
* Content: [Transferring Data Between Tables using DataTransfer - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-data-transfer)
* Content Source: [dev-itpro/developer/devenv-data-transfer.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-data-transfer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've added this to the article.
