### ISSUE TITLE
More information on provided code actions

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#2578]
Regarding the highlighted code actions:
![image](https://user-images.githubusercontent.com/34504100/195538195-15e410bd-e03e-4d97-8470-4ba941dfb347.png)

Could you please add more information on how/where to invoke them? I could not create any code that was able to invoke them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 325dad95-f893-2b85-ca29-f0b019c90d17
* Version Independent ID: 75e0dcf4-2bb8-bd81-e120-240d08d0d0b3
* Content: [AL Code Actions - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-code-actions)
* Content Source: [dev-itpro/developer/devenv-code-actions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-code-actions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. We'll update the article with more information. In the meantime, the spellcheck code can be triggered on certain syntax:

![image](https://user-images.githubusercontent.com/12556556/204999655-acf0e336-e42a-4068-82c1-4f28251727ee.png)

The "make method local" is reactive to the analyzer rule AA0207 (https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0207):

![image](https://user-images.githubusercontent.com/12556556/204999770-dadef59c-9088-44f9-ad87-2b2fbe6e5b95.png)

**Comment by NKarolak** [comment]
Very interesting - thank you!

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, I will close the issue. The docs have been updated and will be pushed with next refresh.
