### ISSUE TITLE
Tantalizingly close

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2583]
The doc says "It creates a spreadsheet that will make it easier to _reuse_ the text from field-level Help topics in your Business Central solution," and then says "Before you _import the tooltips_ into your solution." Which suggest to the reader that there **is** some way to import the tweaked tooltip text into Business Central. But so far I can find no mention of a method for importing. Is there such a thing? No? Either way, it would be helpful if the doc were more explicit about the "import the tooltips" step.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d389dd9-ed8d-4b6f-df05-1829e273e6a0
* Version Independent ID: 3b4c01b3-228a-3e36-e622-ea9666eb587b
* Content: [The FieldTopicTextExtractor tool - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help/custom-help-toolkit-fieldtopictextextractor)
* Content Source: [dev-itpro/help/custom-help-toolkit-FieldTopicTextExtractor.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/help/custom-help-toolkit-FieldTopicTextExtractor.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jowilco
* Microsoft Alias: **jowilco**

**Comment by edupont04** [comment]
Hello David,

The toolkit does not support importing the tooltips into code. Because the mapping from table field to page control may require many manual tweaks, we decided to leave that up to you.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. Since the toolkit and supporting docs are retired, we'll close this issue. Thanks.
