### ISSUE TITLE
Bad example code in article

### ISSUE THREAD

**Issue by Ugniusig** [MicrosoftDocs/dynamics365smb-devitpro-pb#2588]
Example code looks wrong, there should be double colons, the apostrophe is wrong and the table name cannot be plural. I think this corrected example should have been there:
```
[InherentPermissions(PermissionObjectType::Table, Database::"Customer", 'r', InherentPermissionsScope::Both)]
procedure GetCustomersLocation(): CustomerLocation
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44501aeb-bc5c-99db-5a5d-f40c8c722798
* Version Independent ID: 44501aeb-bc5c-99db-5a5d-f40c8c722798
* Content: [Inherent Permissions - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inherent-permissions)
* Content Source: [dev-itpro/developer/devenv-inherent-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-inherent-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the article as suggested. The update will be avialable soon.
