### ISSUE TITLE
Task 17 and 18 should be on the "Upgrading the application code" page

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#259]
Task 17 and 18 should not be in this checklist.
They should be handled during the Application code upgrade, see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-application-code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data#task-17-configure-pages-and-reports-included-in-the-menusuite-to-be-searchable-in-the-)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the valuable feedback! We have made adjustments to the content and an update will be published soon.
