### ISSUE TITLE
Out of Date instllation and configure docker instructions section

### ISSUE THREAD

**Issue by CCC-Lhunter** [MicrosoftDocs/dynamics365smb-devitpro-pb#2591]
As of now the current documentation states: "For Windows Server, use [Docker Enterprise Edition](https://hub.docker.com/editions/enterprise/docker-ee-server-windows). For more information, see [Install instructions](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server)." However that version of docker no longer exists. And the commands don't seem relevant. So what is the current way of configuring docker on a Windows Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6979fc73-1395-b63f-50bf-b2fb1bfda4df
* Version Independent ID: eaf8c4d6-15a5-6444-bc72-48bd0a2e326a
* Content: [Running a Container-Based Development Environment - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-container-development)
* Content Source: [dev-itpro/developer/devenv-running-container-development.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-running-container-development.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This article was updated with the latest refresh of the docs.
