### ISSUE TITLE
OData and SOAP request limits

### ISSUE THREAD

**Issue by eclipses** [MicrosoftDocs/dynamics365smb-devitpro-pb#2592]
Hi, 

A customer would like to receive clarification about limits of calls. When calling an API in the url is specified a specific company, having a database with multiple companies, are the limits written in this page to be considered for the whole Environment or are per company? The documentation does not cover this clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fc3b614-8a3a-0858-80e2-781b1b6e1253
* Version Independent ID: eabcadf6-051e-6631-f5d6-16ccdcef62a7
* Content: [Operation Limits in Dynamics 365 Business Central - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/operational-limits-online)
* Content Source: [dev-itpro/administration/operational-limits-online.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/operational-limits-online.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

The limits are per-Environment. We will make this clearer in the article. Thanks for the feedback!

**Comment by eclipses** [comment]
@jswymer Thank you, really appreciated.
