### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by ThomasBrodkorb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2593]
There is quite some information how to identify the code creating legacy views.
However, there is no information - or link - WITH WHAT these have to be replaced.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198f913c-7331-4482-f2dc-862e1036c575
* Version Independent ID: 198f913c-7331-4482-f2dc-862e1036c575
* Content: [Migrating to modern list views - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-views-legacy)
* Content Source: [dev-itpro/developer/devenv-views-legacy.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-views-legacy.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback, 

The legacy views should be replaced with the modern view that are described here: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-views.

We'll make this clearer in the article.
