### ISSUE TITLE
Retry Attempt information is not correct

### ISSUE THREAD

**Issue by gntpet** [MicrosoftDocs/dynamics365smb-devitpro-pb#2598]
Table, showing retry attempts for saas, looks weird. 

![image](https://user-images.githubusercontent.com/16342128/198667257-55b58533-4838-4e2a-83cc-a0de9372d40b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c2da1a7-cbd8-9412-2bb0-9c61d25c5528
* Version Independent ID: 6b04bae7-3bdd-1582-c49c-a71fc36715ce
* Content: [Task Scheduler - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-task-scheduler)
* Content Source: [dev-itpro/developer/devenv-task-scheduler.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-task-scheduler.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks! We've fixed the article and the update will go live soon.
