### ISSUE TITLE
How about some examples

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#2599]
This is the major topic about text types and there are no examples at all. And how about a list of properties and methods with links so this topic can become the root topic for Text types in AL Code. Seems like this should be a given, but unfortunately, NAV has always been pretty sparse in the documentation area.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27336339-fc8a-6061-4ccc-d6b10aab5286
* Version Independent ID: cb4ce80d-4387-f081-6f2e-81de3874249b
* Content: [Text Data Type - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-data-type)
* Content Source: [dev-itpro/developer/methods-auto/text/text-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/text/text-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by j2associates** [comment]
An example of what I was expecting is the topic for the TextBuilder Class, which is found at [TextBuilder Class](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/textbuilder/textbuilder-data-type). Thanks...

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. There is currently a bug in our auto-generation tooling that doesn't generate the list for this data type like it does for the rest of the data types. We have a bug on this and once it's fixed, we'll refresh the article. Thanks.
