### ISSUE TITLE
should suggest which text editors to use and which ones to avoid when manually merging and resolving conflicts. 

### ISSUE THREAD

**Issue by CanuckNav74** [MicrosoftDocs/dynamics365smb-devitpro-pb#26]
Recently I've gotten into the habit of using Visual Studio Code for all my text editing needs.

What I discovered however is VS Code doesn't properly handle text files encoded in codepage 437 (OEM DOS character set). Since NAV imports/exports txt object files as CP437 text encoding, any and all ESM and FRC ML constants and captions that uses special characters when a file was saved in VS code were affected and irreversible. My only solution was to identify and fix all localized strings in each file and ensure that the file is saved in the proper text encoding that NAV expects (in this case I used notepad++ which has ANSI character set support). 

Visual Studio Code however mis-interprets a CP437-encoded file as UTF-8 it opens one of these NAV txt object files. VS Code is very destructive with any string localizations that use spanish and french accent characters (probably other countries/regions as well). 

my take-away is use notepad++ whenever there is C/AL merging involved.  Avoid VS code (at least for classic dev)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0c9105e-1231-c21c-e6e9-164145258531
* Version Independent ID: dc609d9c-567b-a86b-f1b7-c5f9779d4821
* Content: [Upgrade Application Code - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/upgrading-the-application-code)
* Content Source: [dynamics-nav/Upgrading-the-Application-Code.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Upgrading-the-Application-Code.md)
* Service: **unspecified**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this forum is for documentation feedback only. Please visit [the AL repo](https://github.com/Microsoft/AL) to file issues regarding the AL Language. Thanks.

**Comment by jswymer** [comment]
Thanks for the feedback,

I reproduced the issue described using Visual Studio Code. It seems Visual Studio Code uses utf-8 encoding by default (File > Preferences > Settings > Files). To fix this, in the User Settings, I added the line "files.encoding": "cp437". 

I will update the article to make users aware that they must ensure that the file is saved using the  appropriate codepage/encoding, or ensure that the text editor they use does not change the encoding. This change will be  available the next time we refresh the content.

Thanks again!

**Comment by CanuckNav74** [comment]
Thank you for the update @jswymer  ! That's good to hear. 

Indeed I do see the default files.encoding in the user settings for VS code is "utf8"

Alternately I think you can also specify this setting at the VS Code workspace level. 

The benefit with the workspace approach for those who use VS Code for other tasks besides C/AL merging (I use VS code quite a bit for node development), for those situations I find UTF8 preferrable as a good user default. 

Alternately I don't know how reliable files.autoGuessEncoding is for cp437 (default is false). I discovered that setting this morning as well. Currently I left that setting as-is (false)

With notepad++ on the other hand, I can interchangeably work with both cp437 and utf8 files at the same time.  It knows what text encoding to use when opening a file.
