### ISSUE TITLE
Record Data Type documentation has no functions listed

### ISSUE THREAD

**Issue by eric-silverw-com** [MicrosoftDocs/dynamics365smb-devitpro-pb#260]
All other data types have their applicable functions listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414d9090-1627-86f2-fbef-5a6d0348f8d4
* Version Independent ID: 8af98328-9a31-d2b6-4417-688d2820423e
* Content: [Record Data Type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/record-data-type)
* Content Source: [dynamics-nav/Record-Data-Type.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Record-Data-Type.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We have updated our reference method library for AL and you can see methods listed for [RecordId](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordid/recordid-data-type) and [Record Ref](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-data-type) - going forward you will find more reference topics refreshed in this library. Thanks.
