### ISSUE TITLE
The Link for "Azure Functions" is not working.

### ISSUE THREAD

**Issue by sauerkreut** [MicrosoftDocs/dynamics365smb-devitpro-pb#2601]
The Link for "Azure Functions" is not working. https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/Azure%20AD%20Functions/README.md returns a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d73cb8d0-6cdb-6092-c921-ffa57c756ad3
* Version Independent ID: aec74a54-64eb-a50b-4de2-ebff2bcb96a2
* Content: [Overview of the System Application - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-system-application-overview)
* Content Source: [dev-itpro/developer/devenv-system-application-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-system-application-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by jswymer** [comment]
Thanks for the feedback. The link has been fixed and the updated article will be published soon.
