### ISSUE TITLE
Missing characters in code sniplet

### ISSUE THREAD

**Issue by sauerkreut** [MicrosoftDocs/dynamics365smb-devitpro-pb#2602]
There is a colon missing in the EventSubscriber:
IS: [EventSubscriber(ObjectType::Codeunit, Codeunit::"Guided Experience" 'OnRegisterAssistedSetup', '', true, true)]
SHALL BE: [EventSubscriber(ObjectType::Codeunit, Codeunit::"Guided Experience", 'OnRegisterAssistedSetup', '', true, true)]

Also the "}" at the end of the codeunit is missing.
Best
SK

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07dbbb61-2830-af87-2fbd-ae811e28ce76
* Version Independent ID: 07dbbb61-2830-af87-2fbd-ae811e28ce76
* Content: [Onboard users to your app - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/onboarding-onboard-users-to-your-app)
* Content Source: [dev-itpro/administration/onboarding-onboard-users-to-your-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/onboarding-onboard-users-to-your-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by jswymer** [comment]
Thanks for the feedback! We've made the fixes and the update will be published soon.
