### ISSUE TITLE
Application database conversion fails during minor update installation

### ISSUE THREAD

**Issue by algirdasi** [MicrosoftDocs/dynamics365smb-devitpro-pb#2608]
When upgrading BC21 multitenant application from RTM to CU1, application database conversion fails.

Using the command:
Invoke-NAVApplicationDatabaseConversion -DatabaseServer $DatabaseServer -DatabaseName $ApplicationDatabase -Force

Error:
The database create operation failed due to the following error returned by SQL Server:
Column names in each table must be unique. Column name 'Emit Version' in table 'dbo.Object Metadata' is specified more than once.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 225192fc-756f-88ff-73ca-a4fbbd27956d
* Version Independent ID: 225192fc-756f-88ff-73ca-a4fbbd27956d
* Content: [Install a version 21 update - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v21)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v21.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrading-cumulative-update-v21.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

I have also reproduced this issue on my environment and have notified the development team.

**Comment by algirdasi** [comment]
> 

Thank you for the response. Will there be a hotfix released or will it only be fixed with CU2? If there is a hotfix, would it be possible to get a download link?

Thank you!

**Comment by jswymer** [comment]
Hello again,

This issue has been fixed in 21.3. Sorry for the delay. Thanks for the valuable feedback!
