### ISSUE TITLE
Incomplete sample code

### ISSUE THREAD

**Issue by snehanshumandal** [MicrosoftDocs/dynamics365smb-devitpro-pb#261]
This has incomplete sample code and confuses audience more

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237ce502-edd7-65fb-de3a-8bd4d044a9b7
* Version Independent ID: 6a1f466c-97f8-b5f5-2b99-bc0ee81ffc4c
* Content: [Control Addin Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-control-addin-object)
* Content Source: [dev-itpro/developer/devenv-control-addin-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-control-addin-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. I completely agree with you - the example should be better. I will put this on our backlog and hope to have time to fix this with our next release. Thanks again.

**Comment by hendrik244** [comment]
What's the current status of this? Would be amazing to have a working example of a chartjs controladdin...

**Comment by hendrik244** [comment]
@snehanshumandal Did you made it running? I tried it with a sample chart. But the chart doesn't show up on the page... I don't know what I'm doing wrong.

**Comment by KSH-audibene** [comment]
Is there any chance we can get the full example, which would work?

**Comment by blrobl** [comment]
Hi, a new, simpler and functional example has been added to replace the current one. It will be available in the next doc refresh.
