### ISSUE TITLE
Would be nice to have a reference to IncludedPermissionSets Property on this topic

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2610]
Would be nice to have a reference to [IncludedPermissionSets Property](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-includedpermissionsets-property) on this topic

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4616a537-2a9c-3c00-bece-6382cd050818
* Version Independent ID: 4616a537-2a9c-3c00-bece-6382cd050818
* Content: [ExcludedPermissionSets Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-excludedpermissionsets-property)
* Content Source: [dev-itpro/developer/properties/devenv-excludedpermissionsets-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-excludedpermissionsets-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks! We've added a link.
