### ISSUE TITLE
Would be nice to have a reference to ExcludedPermissionSets Property on this topic

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2611]
Would be nice to have a reference to [ExcludedPermissionSets Property](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-excludedpermissionsets-property) on this topic

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a72678d-5f50-f94b-7be5-f935049d208b
* Version Independent ID: c1dfb841-c028-4a05-2169-e215c17f18c9
* Content: [IncludedPermissionSets Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-includedpermissionsets-property)
* Content Source: [dev-itpro/developer/properties/devenv-includedpermissionsets-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-includedpermissionsets-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks! We've added a link.
