### ISSUE TITLE
Does the Parameter UpdateKey do anything?

### ISSUE THREAD

**Issue by mitrov** [MicrosoftDocs/dynamics365smb-devitpro-pb#2616]
Please see https://twitter.com/FeldhoffDavid/status/1592823910210232320?s=20&t=yJ3pvbuX65Npuu-zh2-mXQ

Can you confim that UpdateKey is actually obsolete?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c04d0987-98cd-f11e-eb8c-432515b70507
* Version Independent ID: 41ad0925-d71c-da6a-6691-5cb6a50f3702
* Content: [Record.FindSet(\[Boolean\] \[, Boolean\]) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-findset-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-findset-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-findset-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, and thanks for your question. We can confirm that we will deprecate the UpdateKey parameter, it doesn't have any function. This will be done in the product, but for now we will update the docs for awareness. The updated article will be available with the next doc refresh. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this.
