### ISSUE TITLE
Text Data Type misses method overview and is duplicate in the menu

### ISSUE THREAD

**Issue by christian-clausen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2617]
Two issues seem to have been introduced when "String" was replaced with "Text":

1. "Text Data Type" page misses the method overview:

The page 
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-data-type
does not list the methods of the data type like other data types do.

Here is an example of the method overview for BigText: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/bigtext/bigtext-data-type---

2. "Text Data Type" is duplicate in the menu

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27336339-fc8a-6061-4ccc-d6b10aab5286
* Version Independent ID: cb4ce80d-4387-f081-6f2e-81de3874249b
* Content: [Text Data Type - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-data-type)
* Content Source: [dev-itpro/developer/methods-auto/text/text-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/text/text-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This is a code defect in our auto-generation tooling. I have opened a bug for this issue, and we'll refresh the topic when it has been fixed. Thanks again.

**Comment by SusanneWindfeldPedersen** [comment]
This article is fixed now with the latest refresh of the docs. Closing this issue.
