### ISSUE TITLE
Please revise

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#2619]
The property does not behave as per documentation:
- It is not deprecated for Code fields (tested in the current AL language version).
- It is unclear how the property works or used to work. The property accepts only true or false. How does this relate to "set a date formula" on text or code fields at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0950071c-1a6e-2817-908d-d65be83c97e6
* Version Independent ID: 85fe0192-206b-93ca-e5c3-88175ca50c34
* Content: [DateFormula Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-dateformula-property)
* Content Source: [dev-itpro/developer/properties/devenv-dateformula-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-dateformula-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi Natalie, thanks for the feedback. It is recommended to use the DateFormula data type. We're currently investigating regarding this property, hope to have an answer for you soon.

**Comment by SusanneWindfeldPedersen** [comment]
Hi again, we'll deprecate this property with a future release. And update the article to mention this. Thanks.
