### ISSUE TITLE
Page Editable method info

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#2628]
[Enter feedback here]

According to this (older but still relevant) thread [here](https://github.com/Microsoft/AL/issues/1664#issuecomment-382323608):

> The CurrPage.Editable property represents both whether a page is editable at all and whether the page is currently in edit mode. We do not support dynamic changes to the page Editable property, except via CurrPage.Editable(FALSE) in OnOpenPage.

This seems a very important restriction that should be noted on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa18ed00-c64a-b31f-6824-fce50ab40319
* Version Independent ID: 862ad8b6-574b-bc16-8633-549b9f8747e6
* Content: [Page.Editable(\[Boolean\]) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-editable-method)
* Content Source: [dev-itpro/developer/methods-auto/page/page-editable-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/page/page-editable-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The article will be updated with the next doc refresh.
