### ISSUE TITLE
`Record[Ref].FilterGroup()` documentation does not mention what the maximal actually working group number is

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2629]
I tried with `FilterGroup(60101)` and filters therein were ignored.

I found a bunch of old discussions stating the maximum is `255`, but no official docs bother to mention...

This should be clearly documented, and invalid arguments should cause an error at build- and run-times, as it should not be possible to silently attempt to apply filters that won't be honoured at runtime (that's a big no for data integrity/security, obv)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2049a29b-bb48-8d52-74a6-dfdfc761c504
* Version Independent ID: 43738a03-e128-6a4f-d07f-39af3267b75a
* Content: [Record.FilterGroup(\[Integer\]) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-filtergroup-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-filtergroup-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-filtergroup-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The limit of 255 is mentioned in a note in the Remarks section: "The maximum number of filtergroups is 255. Greater numbers will be ignored, so don't use them." We'll move the note further up for better discoverability. As for a warning, that's a product change, so please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
