### ISSUE TITLE
How to deal with obsoleted enum values?

### ISSUE THREAD

**Issue by yurim108** [MicrosoftDocs/dynamics365smb-devitpro-pb#2634]
Is there any way to check if a value is obsoleted?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78da2fae-ee31-56f9-c9eb-99ce24161f5d
* Version Independent ID: 3da6fba4-b2d6-4851-dd86-fb16ba1bc52b
* Content: [FieldRef.EnumValueCount() Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-enumvaluecount-method)
* Content Source: [dev-itpro/developer/methods-auto/fieldref/fieldref-enumvaluecount-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/fieldref/fieldref-enumvaluecount-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Closing this. No doc issue.
