### ISSUE TITLE
Re-wording of the Note section?

### ISSUE THREAD

**Issue by DuttaSoumya** [MicrosoftDocs/dynamics365smb-devitpro-pb#2636]
The Note section states,
`This trigger is also available in upgrade codeunits for the base application, not just for extensions.`

May be the following was intended instead?
`This trigger is also available in upgrade codeunits for extensions, not just for the base application.`

I ask because, by default, the base application is trusted and usually has **more functionality** than the extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9e65d76-72e7-345f-ee5a-075be199b168
* Version Independent ID: d3fed441-c8a3-e5ef-f432-5e4974238994
* Content: [OnCheckPreconditionsPerDatabase (Codeunit) Trigger - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/codeunit/devenv-oncheckpreconditionsperdatabase-codeunit-trigger)
* Content Source: [dev-itpro/developer/triggers-auto/codeunit/devenv-oncheckpreconditionsperdatabase-codeunit-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/triggers-auto/codeunit/devenv-oncheckpreconditionsperdatabase-codeunit-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The wording of the note seems to have been reversed - this will be fixed with the next doc refresh.
