### ISSUE TITLE
[CodeCop AA0235] Fix wrong object names

### ISSUE THREAD

**Issue by christianbraeunlich** [MicrosoftDocs/dynamics365smb-devitpro-pb#2638]
Hello there,
as reported by https://github.com/rvanbekkum here https://github.com/microsoft/alguidelines/discussions/203#discussioncomment-4293532 the current state of this rule does not seem to work.

Having a closer look into the documentation page (https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/edit/main/dev-itpro/developer/analyzers/codecop-aa0235.md) we might want to correct a few lines of code:

### 1)
as we are not able to edit code between this section, I'd like to point out that the trigger event is not up-to-date anymore:
![image](https://user-images.githubusercontent.com/25108568/205612203-21efeed8-bd45-4892-93ea-665e9277fa63.png)
~~**OnInstallPerCompany**~~ is not available. This needs to be changed into `OnInstallAppPerCompany`. As we don't have access to the ModernDev-repo, this needs to be changed from your side (or maybe provide a link so that we can create a pr against that repo aswell).
EDIT: related to https://github.com/microsoft/AL/issues/7269

### 2)
as reported by https://github.com/dnpb in issue https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1747, the ~~**Codeunit::"Company - Initialize"**~~ is not valid. This needs to be changed into `Codeunit::"Company-Initialize"`. This is now quite some time ago, but still hasn't changed in the current version https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0235#good-code-example. However, attempting to fix this with a PR shows that the line in the markdown file is correct, leading to the question of when the next doc refresh will occur. (https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1747#issuecomment-792567399)

Thank you 🦦

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1c00b6e-9040-8596-cf21-a595675de1a5
* Version Independent ID: 579de9b9-7eda-77eb-5344-2a365422aa35
* Content: [CodeCop Info AA0235 - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0235)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0235.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/analyzers/codecop-aa0235.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The docs are auto-generated - sourced from code, so this is a code bug fix. We'll open a bug for this. 
For the second issue, I believe it says Codeunit::"Company - Initialize" in the published docs. Thanks
