### ISSUE TITLE
StartUpCompany should be used in combination with other StartUp... settings

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#2639]
Following this issue report (https://github.com/microsoft/AL/issues/7266#issuecomment-1336909138) and the comment of @NKarolak , it would be beneficial if the documentation for the `startupcompany` setting could be updated and mention that at least the `startupObjectId` and `startupObjectType` **must** be filled as well.

Simply using following config in a launch.json file seems not to work.

`"startupCompany": "CRONUS USA, Inc.",`

It must contain the **startupObject** settings as well:

```
"startupCompany": "CRONUS USA, Inc.",
"startupObjectId": 9022,
"startupObjectType": "Page",
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. For now we'll document this for the launch.json - and then we'll await the triage of the issue on the dev side. The updated topic will be available with the next doc refresh.
