### ISSUE TITLE
Subscriptions documentation

### ISSUE THREAD

**Issue by egbertwietses** [MicrosoftDocs/dynamics365smb-devitpro-pb#264]
If I do a metadata request I find some information about subscriptions but cannot find any documentation on it.

            <EntityType Name="subscriptions">
                <Key>
                    <PropertyRef Name="subscriptionId" />
                </Key>
                <Property Name="subscriptionId" Type="Edm.String" Nullable="false" MaxLength="150" />
                <Property Name="notificationUrl" Type="Edm.String" />
                <Property Name="resource" Type="Edm.String" />
                <Property Name="userId" Type="Edm.Guid" />
                <Property Name="lastModifiedDateTime" Type="Edm.DateTimeOffset" />
                <Property Name="clientState" Type="Edm.String" MaxLength="250" />
                <Property Name="expirationDateTime" Type="Edm.DateTimeOffset" />
            </EntityType>

**Comment by egbertwietses** [comment]
have to do a post with something like:

{
	"notificationUrl":"your-url",
	"resource": "https://api.businesscentral.dynamics.com/v1.0/api/beta/companies(*company-id*)/items"
}

it then sends a POST request to your-url with a validation token and then i'm lost...

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We are just about to release docs on subscriptions, so stay tuned - docs will be refreshed (here)[https://docs.microsoft.com/da-dk/dynamics-nav/fin-graph/].

**Comment by SusanneWindfeldPedersen** [comment]
Hey there - just pushed the docs for subscriptions that we have live. Thanks for your interest. Closing this issue for now.

**Comment by egbertwietses** [comment]
Great!
