### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2640]
Because of changes in Dynamics 365 Sales and the integration since *pervious* releases, 
There *a* several new and changed application features
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 385aa170-afd7-9628-9a2e-bd17fa74043b
* Version Independent ID: efb23a4d-df59-08c8-e96b-94229a0d8b07
* Content: [Upgrade Considerations - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-considerations#online)
* Content Source: [dev-itpro/upgrade/Upgrade-Considerations.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/Upgrade-Considerations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
