### ISSUE TITLE
Bad example

### ISSUE THREAD

**Issue by BrianThorChristensen** [MicrosoftDocs/dynamics365smb-devitpro-pb#2643]
Why would you provide an example that doesn't use CopyFields at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb97af30-8a43-648c-75fe-b62c86f425e1
* Version Independent ID: bb97af30-8a43-648c-75fe-b62c86f425e1
* Content: [DataTransfer.CopyFields() Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/datatransfer/datatransfer-copyfields-method)
* Content Source: [dev-itpro/developer/methods-auto/datatransfer/datatransfer-copyfields-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/datatransfer/datatransfer-copyfields-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. We had included the wrong example in the article by mistake. You can read more about using the copyfields method in this article: [Transferring Data Between Tables](../../../developer/devenv-data-transfer.md). And the article will be updated with the correct example with the next doc refresh.
