### ISSUE TITLE
I don't think this is correct

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2647]
Page says "ensure that you've a launch.json file with the request option set to attach" but it never says whether or when to use F5 to start a debug session.

It also says "use Ctrl+F5 to publish the app file and start the attach session." But the Ctrl+F5 only publishes; it specifically does not initiate a debug session.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61bda23d-6d2b-905a-059f-1dc382d506b9
* Version Independent ID: 61bda23d-6d2b-905a-059f-1dc382d506b9
* Content: [Debug Upgrade and Install Code - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-debug-upgrade-install-code)
* Content Source: [dev-itpro/developer/devenv-debug-upgrade-install-code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-debug-upgrade-install-code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, and we realize that the wording might be confusing here. What is meant is that the attach session doesn't publish the app, so you need to ensure that it is published in order to invoke an attach session. We will change the wording here, and in the linked topic to avoid any misunderstanding. This will be fixed with the next doc refresh. Thanks.

**Comment by buzzwick** [comment]
Hi,

This has been closed, but I thought it worth making the effort to report back:

I can confirm that if one is debugging install/startup code, the proper sequence is in fact


  1.  Initiate Attach session (F5).
  2.  Publish without compiling (Ctrl+F5).

This allows breakpoints in the Install codeunit to be caught on execution of the install code. Otherwise the code has already executed before the Attach session is initiated.

Thanks,

David
