### ISSUE TITLE
LOCKTABLE: when is the lock released

### ISSUE THREAD

**Issue by tpokorra** [MicrosoftDocs/dynamics365smb-devitpro-pb#265]
There is no information, when and how the lock is released. Is there a function UNLOCKTABLE? or is the lock released at modify()/insert() calls, or after a commit() call?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7047a340-2c9c-8822-eed8-18744b18c443
* Version Independent ID: 98680dd8-ca47-dfc6-c267-6718b1ee3f47
* Content: [LOCKTABLE Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/locktable-function)
* Content Source: [dynamics-nav/LOCKTABLE-Function.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/LOCKTABLE-Function.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, thanks for the feedback. The table is unlocked automatically after the transaction has been committed. We have updated the articles to include this information. The update will be published soon. I hope this answers your question, otherwise let us know. Thanks!
