### ISSUE TITLE
Read Everything Before Doing Anything?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2651]
If it were me, I would place this information

"Fields in a fixed layout are not editable even if the Editable property is set to true. "

In a big colorful Note at the _beginning_ of the page, to alert developers as soon as possible to the very significant fact that fields laid out using this control cannot be edited. Thus sparing them the trouble of seizing on this display option only to find that it is somewhat useless on a data entry page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9accee14-66b3-70ad-02ff-de86a48d6b78
* Version Independent ID: 17b817ea-9ae1-bf7a-7961-06c908f0c8af
* Content: [Arranging Fields in Rows and Columns Using a Fixed Control - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-fixedlayout-control)
* Content Source: [dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-fixedlayout-control.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-fixedlayout-control.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Although we'd like to think that everybody reads through the entire topic, I think this is really good feedback. We will make that change and it'll be ready with the next doc refresh. Thanks!
