### ISSUE TITLE
Business Central add-in for Excel points to powerbi link

### ISSUE THREAD

**Issue by hvandenborn** [MicrosoftDocs/dynamics365smb-devitpro-pb#2658]
<html>
<body>
<p style="box-sizing: inherit; outline-color: inherit; margin: 1rem 0px 0px; padding: 0px; overflow-wrap: break-word; color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(23, 23, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Use the following table to help you set the minimum permissions:</p><div class="has-inner-focus" style="box-sizing: inherit; outline-color: inherit; color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(23, 23, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Feature | API | Permission name | Type | Description
-- | -- | -- | -- | --
All | Microsoft Graph | User.Read | Delegated | Sign in and read user profile
Business Central add-in for Excel | [Business Central app registration name] | [Business Central app permission name] | Delegated | Allows users of the add-in for Excel to access the OData web services to read and write data.

</div>
</body>
</html>

the link under "Business Central add-in for Excel"
points to 
https://learn.microsoft.com/en-us/dynamics365/business-central/admin-powerbi-setup
which is powerbi and not Addin for excel..

on url:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/register-app-azure

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0026c2a-c249-e240-b077-724a2420e798
* Version Independent ID: b54b5fff-588a-bc42-6838-df1897b825e2
* Content: [Register on-premises as an app in the Azure Management Portal - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/register-app-azure)
* Content Source: [dev-itpro/administration/register-app-azure.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/register-app-azure.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**Use the following table to help you set the minimum permissions:

Feature	API	Permission name	Type	Description
All	Microsoft Graph	User.Read	Delegated	Sign in and read user profile
[Business Central add-in for Excel](https://learn.microsoft.com/en-us/dynamics365/business-central/admin-powerbi-setup)	[Business Central app registration name]	[Business Central app permission name]	Delegated	Allows users of the add-in for Excel to access the OData web services to read and write data.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
