### ISSUE TITLE
Wrong reference

### ISSUE THREAD

**Issue by kwettermann** [MicrosoftDocs/dynamics365smb-devitpro-pb#266]
The link to the application area method is broken and redirects to https://docs.microsoft.com/de-de/dynamics365/business-central/dev-itpro/developer/methods-auto/library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c319f083-b087-7cc9-5d64-807a2c6c0f09
* Version Independent ID: 4b76442b-9264-4f7b-478f-0635b2b24bcd
* Content: [ApplicationArea Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-applicationarea-property)
* Content Source: [dev-itpro/developer/properties/devenv-applicationarea-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-applicationarea-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi, thanks for your feedback! I redirected the link to the "ApplicationArea method" file and the change will be available soon.
We have updated our reference method library for AL and this is why the link was redirected to a different file than you expected. Going forward you will find more reference topics refreshed in this library. Thank you!
