### ISSUE TITLE
This mentioned field but didn't specify Table or Page.  A search of the code appears to yield table fields only.

### ISSUE THREAD

**Issue by thphan75** [MicrosoftDocs/dynamics365smb-devitpro-pb#2663]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 187e578a-a5eb-a76b-5fbf-475692496c1f
* Version Independent ID: 91d875c4-d8f7-4fc9-16c4-1c43a55bef33
* Content: [OptionMembers Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-optionmembers-property)
* Content Source: [dev-itpro/developer/properties/devenv-optionmembers-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-optionmembers-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next doc refresh.
