### ISSUE TITLE
The name [Name] does not exist in the current context. (Compiler Error AL0118)

### ISSUE THREAD

**Issue by sebboe** [MicrosoftDocs/dynamics365smb-devitpro-pb#2664]
The documentation example should be updated for the latest version to compile.

Update leading to the error:
[https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave2/smb/dynamics365-business-central/enable-noimplicitwith-feature-default#feature-details](https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave2/smb/dynamics365-business-central/enable-noimplicitwith-feature-default#feature-details)

Quick fix: add Rec.

```
                field("Reward Id"; Rec."Reward ID")
                {
                    // ApplicationArea sets the application area that 
                    // applies to the page field and action controls. 
                    // Setting the property to All means that the control 
                    // will always appear in the user interface.
                    ApplicationArea = All;
                }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc13a127-253d-6438-52ed-319589d8d3ec
* Version Independent ID: 9bcc413c-55cb-a0e0-8ca2-f111658076fe
* Content: [Building your first sample extension that uses new objects and extension objects - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-example)
* Content Source: [dev-itpro/developer/devenv-extension-example.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-extension-example.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The article will be updated with the next doc refresh.
