### ISSUE TITLE
Example incorrect

### ISSUE THREAD

**Issue by pjllaneras** [MicrosoftDocs/dynamics365smb-devitpro-pb#2682]
Hello,

The example is the same as "CopyRows" method.

It would be interesting if you give some more information, for example... is this the correct method if I want to transfer data between 2 table extensions of the same table? if so, an example will be great, I haven't seen anything about transfer data between table extensions.

Best regards!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb97af30-8a43-648c-75fe-b62c86f425e1
* Version Independent ID: bb97af30-8a43-648c-75fe-b62c86f425e1
* Content: [DataTransfer.CopyFields() Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/datatransfer/datatransfer-copyfields-method)
* Content Source: [dev-itpro/developer/methods-auto/datatransfer/datatransfer-copyfields-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/datatransfer/datatransfer-copyfields-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We had the wrong code example in the CopyFields method. You can read more about datatransfer in this  article: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-data-transfer. The article will be updated with the next doc refresh.
