### ISSUE TITLE
Update Article with Max Length for Permission Sets - Keep length to 20

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#2683]
Could you please add a note about the max length of names for permissionsets.
This is different to other object types, since it is limited to 20 instead of 30 characters for most of the permissionsets.

Here are some more details:

- Assignable permission sets have a compiler max length of 20
- Non-assignable permission set have a compiler max length of 30
- In just limiting the permission set length to 20 - then you're on the safe side.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0a0df1a-4199-f8f7-7a74-a23ae7a61983
* Version Independent ID: 08012c6c-5692-0a9b-fd37-b6ebf17ec957
* Content: [Permission Set Object - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-permissionset-object)
* Content Source: [dev-itpro/developer/devenv-permissionset-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-permissionset-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We will update the article to be specific about this. This is due to an underlying table restriction. The article will be updated with the next doc refresh.
