### ISSUE TITLE
Missing and Incorrect Information on this page

### ISSUE THREAD

**Issue by JennReinhardt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2685]
The following section is missing something and has something incorrect:
-------------------------------------------
In the Client ID field, enter the Application ID from the registered app in Azure Portal.
In the Client Secret field, enter the key generated under Keys that you copied in step 6 in the [Setting up Azure Active Directory (Azure AD) based authentication](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#AAD).
In the Client Authentication field, choose the Send client credentials in body option.
Choose the Request token button. The first time you sign in, you'll get prompted for consent.
Scroll down and choose Use token button.
------------------------------------------
Fixes
------------------------------------------
**after the definition of the Client Secret field we should also put the Scope field it's definition. This field should be populated with the following URL: https://api.businesscentral.dynamics.com/.default   - support had to look this up and find it on a partner blog...we should have this in documentation
**Choose the Request token button. - this should be Choose the 'Get New Access Token' button.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#exploring-the-apis-with-postman-and-azure-ad-authentication)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be updated for the next doc refresh.
