### ISSUE TITLE
Typo on the first line

### ISSUE THREAD

**Issue by DominicMatheis** [MicrosoftDocs/dynamics365smb-devitpro-pb#2691]
[Enter feedback here]
Typo: 'there are two _tasks_ main tasks' 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa8cc45-4637-fad4-4caf-5e55f088ba78
* Version Independent ID: fd32d039-b541-3a10-5d71-cb54aa579da1
* Content: [Creating a Word Layout Report - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-howto-report-layout)
* Content Source: [dev-itpro/developer/devenv-howto-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-howto-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
