### ISSUE TITLE
Picture content API documentation is wrong

### ISSUE THREAD

**Issue by JulianTillmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#2693]
It seems like in v2.0 the api changed from "/picture({pictureId})/content" to "/picture/pictureContent"

Please update the documentation accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57fdeb99-b31c-4083-8f73-de9b10adb10d
* Version Independent ID: d881199f-5575-d19a-14f4-e2d0c5573d1c
* Content: [Get picture - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_picture_get)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_picture_get.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_picture_get.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We're currently looking into this.

**Comment by JulianTillmann** [comment]
great, looking forward to it :-) 

I also created a pull request with my suggestion:
https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/pull/2694

**Comment by SusanneWindfeldPedersen** [comment]
Thanks so much for your contribution, merged and closed.
