### ISSUE TITLE
Need simple code example

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#2699]
I know this is a simple concept, but there is no sample code demonstrating how to execute a codeunit so that it's OnRun trigger is invoked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9546f4da-6878-25a1-7b19-40009110f48b
* Version Independent ID: 9d76bbaa-3150-ddf5-0097-e70d5afe9902
* Content: [OnRun (Codeunit) Trigger - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/codeunit/devenv-onrun-codeunit-trigger)
* Content Source: [dev-itpro/developer/triggers-auto/codeunit/devenv-onrun-codeunit-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/triggers-auto/codeunit/devenv-onrun-codeunit-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The article will be updated with the next doc refresh.
