### ISSUE TITLE
Posibilities for Filename

### ISSUE THREAD

**Issue by AR101** [MicrosoftDocs/dynamics365smb-devitpro-pb#27]
The Filename property documentation should be enriched with possible inputs (Ex. UNC paths)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdda23ef-73dc-5521-d5c0-5896d1a672ea
* Version Independent ID: a7c5d648-e321-e91c-c6d0-4eb3bc107eab
* Content: [SAVEASPDF Function (Report) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/saveaspdf-function--report-)
* Content Source: [dynamics-nav/SAVEASPDF-Function--Report-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SAVEASPDF-Function--Report-.md)
* Service: **unspecified**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback,

The FileName parameter help in article has been updated to include information about possible values, such as UNC. The information will be available the next time we refresh the content.
