### ISSUE TITLE
Replace Report globally

### ISSUE THREAD

**Issue by JulianTillmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#270]
In Directions there was talk About replacing Reports globally in a System via extensions. I can't find any Mention in the documentation, how would we Need to go About that? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 185e15dd-e5ae-2272-7d29-3207bdd08089
* Version Independent ID: dc0cdfd9-7480-6cc4-8c9e-db6ac05f2f6c
* Content: [Report Design Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-design-overview)
* Content Source: [dev-itpro/developer/devenv-report-design-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-report-design-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi! Thank you for your feedback! You can find more information about  "Report substitution" in [this blog post](https://blogs.msdn.microsoft.com/nav/2018/08/31/developer-preview-august-2018/) but also in the "NAV TechDays 2018 - What’s new in Developing for Business Central" [video](https://www.youtube.com/watch?v=7jNByP3kFPk&t=2731s) (from minute 24).
Thanks!

**Comment by JulianTillmann** [comment]
Could you Maybe provide this Information in the documentation? If we have to search the documentation, several Blogs and even look for it in external 90 Minute Videos it's a bit complicated to find what we Need.

**Comment by lvanvugt** [comment]
Fully agree with Julian. A docs topic is needed on this.

**Comment by ThomasBrodkorb** [comment]
I do also agree, please provide information directly, rather than pointing out links, which might be broken at any time.
