### ISSUE TITLE
Ignore Warning

### ISSUE THREAD

**Issue by spiritsip** [MicrosoftDocs/dynamics365smb-devitpro-pb#271]
Not sure if this is a content or product feedback. Probably depends on the answer :) In traditional FXCop, you can exclude a specific instance of a warning and provide a reason why you did it. Is that possible with the AL analyzers? In particular, the "Possible overflow assigning Text to Text[250]" is logged even when you are explicitly using CopyStr to only assign the MaxStrLen of the field in question, so it's a handled warning. Over time, you project tends to fill up with dozens of these false positives making it harder to find the real issues. I do see that it's possible to ignore the overall rule using a ruleset, but that's not particularly ideal either. As in the example above, you would want to know if there actually *was* a possible overrun, but then ignore the warning once you're sure it isn't a problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a5b68ec-d706-ab10-8cb9-22e8d98c3494
* Version Independent ID: 3da84c14-159f-3ac7-ee94-5e0faff222d8
* Content: [Using the Code Analysis Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool)
* Content Source: [dev-itpro/developer/devenv-using-code-analysis-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-using-code-analysis-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. The issue that you mention has been improved with an update of the AL Extension, not sure if you have access to that update. With regards to support for excluding specific instances, I am sorry but this is not (yet) supported. Thanks.
