### ISSUE TITLE
Example wrong: The variable in the example is of type BigText, while documentation says it is of type BigInteger, so example does not compile

### ISSUE THREAD

**Issue by Quivelus** [MicrosoftDocs/dynamics365smb-devitpro-pb#2724]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfdbc066-f5d5-9441-ae8e-efdf67987e57
* Version Independent ID: 2e898797-1f15-0dc6-3159-5e325673099e
* Content: [SessionInformation.SqlStatementsExecuted() Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlstatementsexecuted-method)
* Content Source: [dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlstatementsexecuted-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlstatementsexecuted-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by Quivelus** [comment]
Concerning this page, the previous bug report (https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/754) was incorrect

BigText should be changed to BigInteger

**Comment by jswymer** [comment]
Thanks! Fixed in the the publish
