### ISSUE TITLE
Bizar syntax example

### ISSUE THREAD

**Issue by Quivelus** [MicrosoftDocs/dynamics365smb-devitpro-pb#2725]
Syntax states --> SqlStatementsExecuted :=   SessionInformation.SqlRowsRead()

Seems a copy of SqlStatementsExecuted documentation
Please:
 - Rename variable SqlStatementsExecuted to SqlRowsRead
 - Remove spaces too many after assignment :=

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cce86567-b2c5-aacb-df1f-7bc8e717d88e
* Version Independent ID: 0c92766b-b67e-a28d-fcd0-47e08a3f9db8
* Content: [SessionInformation.SqlRowsRead() Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlrowsread-method)
* Content Source: [dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlrowsread-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlrowsread-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
