### ISSUE TITLE
Both wrong assignment and datatype in example

### ISSUE THREAD

**Issue by Quivelus** [MicrosoftDocs/dynamics365smb-devitpro-pb#2726]
Please change

var
    SqlRowsRead :**=** Big**Text**;

**to**

var
    SqlRowsRead : BigInteger;

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cce86567-b2c5-aacb-df1f-7bc8e717d88e
* Version Independent ID: 0c92766b-b67e-a28d-fcd0-47e08a3f9db8
* Content: [SessionInformation.SqlRowsRead() Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlrowsread-method)
* Content Source: [dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlrowsread-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlrowsread-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks! We've fixed the example and an update will be published soon.
