### ISSUE TITLE
KeyValue Parameter missing in Setting the WSFederationLoginEndpoint Value

### ISSUE THREAD

**Issue by sb-sag** [MicrosoftDocs/dynamics365smb-devitpro-pb#2727]
In the Command for Setting the WSFederationLoginEndpoint Value the **-KeyValue** Parameter is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de3338bf-8bdf-7d6a-884e-3afdb4d37165
* Version Independent ID: de3338bf-8bdf-7d6a-884e-3afdb4d37165
* Content: [Configure Azure Active Directory Authentication with OpenID Connect - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect?tabs=singletenant%2Cadmintool)
* Content Source: [dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've made the fix and an update will be published soon.
