### ISSUE TITLE
Feature management page works for which version of business central

### ISSUE THREAD

**Issue by shellatomic** [MicrosoftDocs/dynamics365smb-devitpro-pb#2728]

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please add information back about the help topic that this issue is about, thanks.

**Comment by shellatomic** [comment]
I want to you use power automate with business central 14, but unfortunately i can't find feature management page to configure power automate any help ?

**Comment by SusanneWindfeldPedersen** [comment]
Not sure if version 14 supports this. This repo is meant for documentation issues and this seems to be a product question. Please contact your usual support channel to get assistance. Thanks.
