### ISSUE TITLE
keeps getting the Attribute <xmlns> is unexpected. when using DefaultNamespace or  Namespaces = "" 

### ISSUE THREAD

**Issue by Michel-up** [MicrosoftDocs/dynamics365smb-devitpro-pb#2729]
keeps getting "The Attribute <xmlns> is unexpected." when using XMLPort to upload XML file with xmlns
when using DefaultNamespace or  Namespaces = "" 
if i remove the xmlns="blabla" from the XML file then the upload will work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f60a24c8-db48-7313-f460-d17ddaa9f542
* Version Independent ID: 0d9fe2ba-e84d-e3f9-394f-ff8622991380
* Content: [Namespaces Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-namespaces-property)
* Content Source: [dev-itpro/developer/properties/devenv-namespaces-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-namespaces-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This might a product bug. Please use your usual support channel for more information. Thanks.
