### ISSUE TITLE
Property ItemCategory description

### ISSUE THREAD

**Issue by egbertwietses** [MicrosoftDocs/dynamics365smb-devitpro-pb#273]
On the right of itemCategory:
"Specifies the category that the item belongs to. Item categories also contain any assigned item attributes."

The second part "Item categories also contain any assigned item attributes." doesn't seem to be true.
I've tested this and don't see the assigned item attributes when requesting the item details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da3d76f8-6996-c2ee-0a26-ab63f798ca6b
* Version Independent ID: 87673447-d246-e5f9-477e-b2cc096df67c
* Content: [items resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/resources/dynamics_item)
* Content Source: [dynamics-nav/fin-graph/resources/dynamics_item.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/resources/dynamics_item.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
Hi egbertwietses,
You are right. API does not contain the item attributes. We will update the docs.
Remember that youre able to develop a custom API to expose this.

Let me know which scenario you are working at, so I can validate if we should get item attributes into the standard API.

Thanks for the feedback!
/Henrik

**Comment by SusanneWindfeldPedersen** [comment]
This is now fixed in the topic and will be live with our next refresh. Thanks again for catching this.
