### ISSUE TITLE
Create customerPayments - URL on Request Example is wrong

### ISSUE THREAD

**Issue by markborges** [MicrosoftDocs/dynamics365smb-devitpro-pb#2730]
Hi, the URL showing under the Request example is wrong. It reads:

POST https://{businesscentralPrefix}/api/v2.0/companies({id})/**customerPayment**

It should read:

POST https://{businesscentralPrefix}/api/v2.0/companies({id})/**customerPayments**

If you use the URL on the current example, you run into the following error message:

"message": "No HTTP resource was found that matches the request URI 'https://api.businesscentral.dynamics.com/v2.0/Production/api/v2.0/companies({companyId})/customerPayment?tenant=msft1a6720t22590909&aid=FIN'."

Rgds.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f2f3e63-0613-e710-4fac-029012b3fc29
* Version Independent ID: 73c05b65-a95b-8286-8e52-acea522d5bc7
* Content: [Create customerPayments - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_customerpayment_create)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_customerPayment_create.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_customerPayment_create.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next refresh of the docs.

**Comment by markborges** [comment]
This was closed but never fixed. Is it still tracked to be fixed? Otherwise, I'll just stop reporting documentation issues. Tks.
