### ISSUE TITLE
PDFDocument API Endpoint - Document Types

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#2736]
Based on a review of the code history for this endpoint, I found the Purchase Order was also a supported Document Type as of version 17.5.

The parentType property needs to be updated.

I'm less sure about Navigations.

(Apologies for not just making a PR, but busy busy)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba3aa524-bf90-7d4c-8b87-2103b3ad173e
* Version Independent ID: 7a787ca8-c2b7-a04f-8ce1-88f6f0ae3a54
* Content: [pdfDocument resource type - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/resources/dynamics_pdfdocument)
* Content Source: [dev-itpro/api-reference/v2.0/resources/dynamics_pdfDocument.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/resources/dynamics_pdfDocument.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching that. We'll get that fixed with the next doc refresh.
