### ISSUE TITLE
Picture API parentType Property

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#2737]
On the parentType property, Contact was added in 18.0.

(Apologies for not doing a PR, busy busy!)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4fd53ca-1ccc-40ec-5901-7d1ad6caa45d
* Version Independent ID: fadf0b46-f83a-5459-e2f4-a64d65a755b0
* Content: [picture resource type - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/resources/dynamics_picture)
* Content Source: [dev-itpro/api-reference/v2.0/resources/dynamics_picture.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/resources/dynamics_picture.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. We'll get that fixed for the next refresh of the docs!
