### ISSUE TITLE
Features not intended for use in Cloud deployments

### ISSUE THREAD

**Issue by MFerragamo1** [MicrosoftDocs/dynamics365smb-devitpro-pb#274]
Hi - when will we have this list? 
Also, when will the missing features be added?
Thanks, Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db917c4-601c-b6f1-863f-17b83d35e814
* Version Independent ID: 22279a66-57b2-7f98-16b6-3cfb394b7fda
* Content: [Features not implemented in on-premises deployments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/features-not-implemented-on-premises)
* Content Source: [dev-itpro/features-not-implemented-on-premises.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/features-not-implemented-on-premises.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Mike,
As stated above, the second section lists features that are not intended for use with on-premises deployments. There are no plans to implement these features.

Please consult the release notes to find out which features are coming: https://docs.microsoft.com/en-us/business-applications-release-notes/

You can also suggest features here: https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1
