### ISSUE TITLE
Wrong sample?

### ISSUE THREAD

**Issue by waldo1001** [MicrosoftDocs/dynamics365smb-devitpro-pb#2745]
I think the example is wrong, and should be "TableData" in stead of "Table", like this:

```al
[InherentPermissions(PermissionObjectType::TableData, Database::Customer, 'r', InherentPermissionsScope::Both)]

Procedure GetCustomersLocation(): CustomerLocation
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44501aeb-bc5c-99db-5a5d-f40c8c722798
* Version Independent ID: 44501aeb-bc5c-99db-5a5d-f40c8c722798
* Content: [Inherent Permissions - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inherent-permissions)
* Content Source: [dev-itpro/developer/devenv-inherent-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-inherent-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback. We've fixed the example and the update will be published soon.
