### ISSUE TITLE
no open api spec for v2.0?

### ISSUE THREAD

**Issue by delly47** [MicrosoftDocs/dynamics365smb-devitpro-pb#2749]
why is there no open api spec for v2.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1baf2582-6d3b-68da-47b9-f42f81ad0f9c
* Version Independent ID: 25a0b3d1-0de8-bce1-083c-974f8921acfb
* Content: [OpenAPI Specification - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/dynamics-open-api)
* Content Source: [dev-itpro/api-reference/v2.0/dynamics-open-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/dynamics-open-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation issues only. We encourage you to contact your usual support channel for product questions. Thanks
