### ISSUE TITLE
Incomplete instruction

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#276]
Hello,
When the doc says "Build the extension (Ctrl+Shift+B) to generate the MyRDLCReport.rdl file.", it does not specify where the .rdl file is created. It would be helpful to include at this point mention of 1) where in the file system the file will be created by default, and 2) how one could redirect that file creation at compile time, and 3) how one could change the default location for .rdl files to be located, if that is possible.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b7f14d-d6ca-7248-7621-47669905bea0
* Version Independent ID: c1e289a5-c3cc-a748-4f59-6a56001c4b8d
* Content: [Creating an RDL Layout Report - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-howto-rdl-report-layout)
* Content Source: [dev-itpro/developer/devenv-howto-rdl-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-howto-rdl-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hello, thank you for your feedback! The file is created in the root of the current project.
2) and 3) are not possible, but you can submit your suggestion on GitHub: https://github.com/microsoft/al. Thanks!
