### ISSUE TITLE
Invalid Note text

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-devitpro-pb#2763]
I think the Note "For now, the InherentPermissions attribute is available for Business Central on-premises only. It'll be added to Business Central online in a later version." is no longer valid since the release of version 21 (2022 wave 2) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44501aeb-bc5c-99db-5a5d-f40c8c722798
* Version Independent ID: 44501aeb-bc5c-99db-5a5d-f40c8c722798
* Content: [Inherent Permissions - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inherent-permissions)
* Content Source: [dev-itpro/developer/devenv-inherent-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-inherent-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, this should be fixed in the live docs. Thanks.
