### ISSUE TITLE
still some issues are there

### ISSUE THREAD

**Issue by incredible-India** [MicrosoftDocs/dynamics365smb-devitpro-pb#2769]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13b96a6c-5af1-38da-92e1-d6fd933efb6b
* Version Independent ID: 377038ff-65c2-2e52-11d3-fa4cf82d8aae
* Content: [PromotedCategory Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-promotedcategory-property)
* Content Source: [dev-itpro/developer/properties/devenv-promotedcategory-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-promotedcategory-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dnpb** [comment]
What issues...???

**Comment by incredible-India** [comment]
in the older version it is not working as expected...like 3.0

**Comment by dnpb** [comment]
"not working as expected" is not a problem description. You could/should show a code sample, describe expected behaviour, and describe actual behaviour and how that's wrong.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. Thanks.
