### ISSUE TITLE
Legacy reference

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#277]
This documentation is written as if C/AL had not existed for some 15+ years. Nearly every developer coming to the AL development environment is coming from the C/AL development environment. This being the case, especially for something like reports, it might be helpful to include references to the C/AL environment, so as to clarify what part of the old C/AL environment a particular AL feature is replacing, or changing, or corresponds to. This would greatly facilitate comprehension and adoption of the new environment. Maybe as footnotes or tooltips or some other web-based way of including helpful clarifying notes. As a simple example: "You build the report dataset by adding data items and columns" (as an aside--by adding data items and columns...to what?) could include a note to the effect that this is what the C/AL Dataset Designer used to accomplish. Then at least we have a point of reference that helps us know right away what we are talking about. It comes across as arbitrary and forced to have AL explained as if it were born in a vacuum, when the reality is that it is simply the code that lay underneath the C/AL visual development environment. And the benefit of legacy references is real: including a simple pointer makes use of the existing schema in the minds of developers, and reduces the cognitive load associated with assimilating the new environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 185e15dd-e5ae-2272-7d29-3207bdd08089
* Version Independent ID: dc0cdfd9-7480-6cc4-8c9e-db6ac05f2f6c
* Content: [Report Design Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-design-overview)
* Content Source: [dev-itpro/developer/devenv-report-design-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-report-design-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. I appreciate your input, and I think a lot of developers do come from C/SIDE. We do, however, not want to make that reference, because our aim is to have a docset that caters for new developers as well. Thanks.

**Comment by buzzwick** [comment]
Thank you for your response. With all due respect, It seems it would be more accurate to say that your aim is to have a docset that caters to new developers ONLY, if the intention is to eliminate references to earlier environments. Fine. Be that as it may--in that case, could we please include somewhere a definition of "data item".  That term is a complete abstraction--it has no intrinsic correspondence to anything in the real world, but as we all know does in fact refer to real objects in the AL programming environment. Which ones?  What properties does/must a "data item" possess? Maybe we don't want to refer to the bad old C/AL environment, but might we refer to such neutral real-world objects as Tables? Lists? Is a "data item" the same as a "data set"? If not, how are they distinct? Invented abstractions have to come from somewhere if they are to be useful in the real programming world. Thanks again.

**Comment by SusanneWindfeldPedersen** [comment]
We appreciate your feedback. We have reporting on our backlog for a future refresh, and I really hope we will be able to improve this area. We do know that we lack information at the moment. Thanks again and happy holidays!
