### ISSUE TITLE
Procedure Naming

### ISSUE THREAD

**Issue by 961919169** [MicrosoftDocs/dynamics365smb-devitpro-pb#2770]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 448c2de3-f23c-108e-6d4e-31cd32586c58
* Version Independent ID: 0dbc9199-71ff-34f4-f7f6-86bd5fb20b66
* Content: [Substituting Reports - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-substituting-reports)
* Content Source: [dev-itpro/developer/devenv-substituting-reports.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-substituting-reports.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **solsen**

**Comment by dnpb** [comment]
Your suggested change has been deleted and is now stuck in the edit history, but I'm not certain about it anyway. The idea of putting a description of the subscriber seems opinion-based. Other developers just do `PublisherName_EventName[_FieldName]` and such. I'm not sure Microsoft state a policy on this, or *should*, so it's not clear why it matters how they name in example code.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, not sure about this issue, can you please elaborate a bit on where you found the bug in the article? Thanks

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue. Please open a new issue if needed, thanks.
