### ISSUE TITLE
Description does not match example

### ISSUE THREAD

**Issue by DuttaSoumya** [MicrosoftDocs/dynamics365smb-devitpro-pb#2772]
The sentence
`Next, you use SetAscending to sort City in descending order instead.`
should be replaced by 
`Next, you use SetAscending to sort Name in descending order instead.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49e7f1e1-e840-8a6f-81bc-a29dd248a327
* Version Independent ID: c2ada013-a751-09ef-cac7-6c50b51e2411
* Content: [Record.SetAscending(Any, Boolean) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setascending-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-setascending-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-setascending-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with next doc refresh.
