### ISSUE TITLE
Wrong text in Example 1

### ISSUE THREAD

**Issue by sauerkreut** [MicrosoftDocs/dynamics365smb-devitpro-pb#2773]
Text in Example 1 says "Next, the FilterGroup method changes the filter group to **100**."
Shall be "Next, the FilterGroup method changes the filter group to **1**."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2049a29b-bb48-8d52-74a6-dfdfc761c504
* Version Independent ID: 43738a03-e128-6a4f-d07f-39af3267b75a
* Content: [Record.FilterGroup(\[Integer\]) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-filtergroup-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-filtergroup-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-filtergroup-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - will be fixed with the next doc refresh.
