### ISSUE TITLE
Delegated Admin doesn't need to be reseller...

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#2774]
On this page is this sentence:

```
Delegated administrators from reselling partners
```

But it is false. Any delegated admin with min. D365 Admin role could do that. Not only the reselling partners. Reseller relation is not connected with GDAP relation. 

Reseller relationship is about selling licenses etc., GDAP is about administering. The sentence is mixing these two things together with no purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 260c1dbe-5f81-7fc3-e0d1-a4cb0df4a962
* Version Independent ID: e74367de-e724-9ac9-5e61-0c176d217bcf
* Content: [Restoring an Environment in the Admin Center - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-backup-restore)
* Content Source: [dev-itpro/administration/tenant-admin-center-backup-restore.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/tenant-admin-center-backup-restore.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the article, An update will be published soon.
