### ISSUE TITLE
Incorrect link?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#278]
The link "For more information on creating a report, see Creating a Report."   actually goes to "Creating a Word Layout Report". There does not seem to actually be a "Creating a Report" page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0042001-b98b-71c6-f659-84af0bd52a7d
* Version Independent ID: 212b2740-288e-8c5a-9e1e-960fcfb5739c
* Content: [Report Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-object)
* Content Source: [dev-itpro/developer/devenv-report-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-report-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. The link text is fixed with the next doc refresh.
