### ISSUE TITLE
Need OpenAPI Specification for Business Central API V2.0

### ISSUE THREAD

**Issue by nigelthomas-mozanta** [MicrosoftDocs/dynamics365smb-devitpro-pb#2787]
Hi,

It would be great if there is an OpenAPI Specification for Business Central API V2.0 provided at the earliest.

The problem that we are facing is creating a Java SDK for Business Central API V2.0 .
Currently there does not seem to be a solution for creating a Java SDK for Business Central APIs based on the OData Metadata file.

Please expedite this requirement for an OpenAPI Spec for Business Central API ver 2.0, so that we can use swagger-codegen-cli for generating the Java SDK.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1baf2582-6d3b-68da-47b9-f42f81ad0f9c
* Version Independent ID: 25a0b3d1-0de8-bce1-083c-974f8921acfb
* Content: [OpenAPI Specification - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/dynamics-open-api)
* Content Source: [dev-itpro/api-reference/v2.0/dynamics-open-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/dynamics-open-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks

**Comment by nigelthomas-mozanta** [comment]
Added Idea in Dynamics 365 Business Central Ideas section

https://experience.dynamics.com/ideas/idea/?ideaid=1af5d907-ccdd-ed11-9139-0003ff45de26
