### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mltytskr** [MicrosoftDocs/dynamics365smb-devitpro-pb#2788]
The [Posting Documents and Journals](https://learn.microsoft.com/en-us/dynamics365/business-central/ui-post-documents-journals.md) link on this page under the "Tables that contain posted entries" section is broken. It appears the ".md" needs to be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 265b0c15-af70-2e2f-a5c4-af5e2686271b
* Version Independent ID: 5c7748be-a724-27ef-fb51-e96a9c46773b
* Content: [Set Up Company Configuration Packages - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/set-up-standard-company-configuration-packages)
* Content Source: [dev-itpro/administration/set-up-standard-company-configuration-packages.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/set-up-standard-company-configuration-packages.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thanks for catching this broken link! And yes, it was a copy-paste error. We'll get it fixed.

**Comment by SusanneWindfeldPedersen** [comment]
Fixed, closing issue
