### ISSUE TITLE
Sampling profiling settings duration & stack frame entries

### ISSUE THREAD

**Issue by StijnBt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2789]
The settings mentioned in:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-profiler-overview#sampling-profiling

These:
The maximum duration of a sampling session is 10 minutes. This is a configurable server setting.
The number of stack frame entries is limited to 2000. This is a configurable server setting

Are nowhere documented on how to modify them?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fafe761-c1cc-3784-07ba-1707c660da27
* Version Independent ID: 8f5e89c6-3d71-a90e-0a69-3d4922190407
* Content: [AL Profiler Overview - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-profiler-overview)
* Content Source: [dev-itpro/developer/devenv-al-profiler-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-al-profiler-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The settings are actually internal and not modifiable. This will be fixed with the next doc refresh. Thanks
