### ISSUE TITLE
Too simple

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#279]
All of the pages and code samples I have seen illustrate only reports using a single table in the dataset. The vast majority of reports I see and write use not only more than one table but also the Integer table. I think it would be useful to include explanations and examples (not to mention Templates) of report datasets using multiple data items. This would greatly speed up the process of recognizing, adopting, and using correct syntax for these structures. Maybe you just add another page--in addition to "Defining a Report Dataset", we could have "Defining a Report Dataset with Multiple Data Items" page. In the same way that there are now 2 "How to: Create a ... Layout Report" pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0042001-b98b-71c6-f659-84af0bd52a7d
* Version Independent ID: 212b2740-288e-8c5a-9e1e-960fcfb5739c
* Content: [Report Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-object)
* Content Source: [dev-itpro/developer/devenv-report-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-report-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We know that content is missing for more advanced reports and this is on our backlog of things to do for a future release. Thanks again.
