### ISSUE TITLE
OpenID documentation not up to date

### ISSUE THREAD

**Issue by hhoutaptean** [MicrosoftDocs/dynamics365smb-devitpro-pb#2793]
[Enter feedback here]

Hi,

I was applying the OpenID configuration on my Business Central environment (W1 22.0 (Platform 22.0.53784.0 + Application 22.0.53859.0)) on basis of the shared documentation on https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect

Described is that ClientServicesFederationMetadataLocation parameter value needs to be configured, I think this was copied by mistake from the old (WS-Federation?) documentation because this parameter doesn't exist anymore in Business Central version W1 22.0 (Platform 22.0.53784.0 + Application 22.0.53859.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de3338bf-8bdf-7d6a-884e-3afdb4d37165
* Version Independent ID: de3338bf-8bdf-7d6a-884e-3afdb4d37165
* Content: [Configure Azure Active Directory Authentication with OpenID Connect - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect?tabs=singletenant%2Cadmintool)
* Content Source: [dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! Correct, the ClientServicesFederationMetadataLocation parameter is no longer available, starting in v22. The documentation has been updated but not yet published. It will be published soon.
