### ISSUE TITLE
It would be worth mentioning that JsonArray is 0-based

### ISSUE THREAD

**Issue by PaulFurlet** [MicrosoftDocs/dynamics365smb-devitpro-pb#2794]
similarly to [List Data Type](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/list/list-data-type.md) it would be good to mention the base for index. Which is 0-based for JsonArray.

> JsonArray are 0-based indexed, that is, the indexing of a JsonArray begins with 0.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2beae7f1-40fb-2e1e-1e53-f7b91ef4ee5b
* Version Independent ID: e364c4d6-5f58-e4b7-13a6-bb5debbaa5de
* Content: [JsonArray Data Type - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonarray/jsonarray-data-type)
* Content Source: [dev-itpro/developer/methods-auto/jsonarray/jsonarray-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/jsonarray/jsonarray-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback - can you elaborate on this? The JsonArray data type has a note saying it's 0-based, and the List data type has description that it is 1-based, under Remarks. Were you thinking of another place to mention 0-based index? Thanks

**Comment by PaulFurlet** [comment]
Ah, I did not notice the Note in the end, shame on me...
Was looking in the methods list next to IndexOf or so, like it is specified in List Data Type help...

Thank you for pointing!
