### ISSUE TITLE
Confusing description

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#2797]
Hi,

The description is a bit confusing.

You have specified serviceName in the url but you never specified what service name is.
But in the reality the example used the Codeunit name as the service name which led me to believe that the servicename should always be equal to the object name.

So for clarity can you specify that the service name is MyOperations and update the url so no one else believes that servicename = object name

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för learn.microsoft.com ➟ länkning till GitHub-problem.*

* ID: bc701118-4d83-4d5a-efcc-420fb870300f
* Version Independent ID: 10a28599-afa8-a4e9-0d9a-b80749421de2
* Content: [Creating and Interacting with an OData V4 Unbound Action - Business Central](https://learn.microsoft.com/sv-se/dynamics365/business-central/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-unbound-action)
* Content Source: [dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-unbound-action.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-unbound-action.md)
* Service: **dynamics365-business-central**
* GitHub Login: @ap3rus
* Microsoft Alias: **vlnagorn**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - will be fixed with the next doc refresh.
