### ISSUE TITLE
Link requires credentials

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#280]
The link "Windows PowerShell Cmdlets for Business Central" points to 
https://review.docs.microsoft.com/en-us/powershell/business-central/overview
and causes a credentials error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbfc9d0-f60a-30b3-8377-e1f56b67a17f
* Version Independent ID: e72a85e4-8fda-9ae0-73f2-015402c04ba5
* Content: [Product Architecture - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/product-and-architecture-overview)
* Content Source: [dev-itpro/deployment/product-and-architecture-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/product-and-architecture-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The wrong link got referenced in the topic, this is the right link: [PowerShell Cmdlets](https://docs.microsoft.com/en-us/powershell/business-central/overview)
The topic will be updated with the next refresh of our docs. Thanks again.
