### ISSUE TITLE
DataTransfer - AddFieldValue -  Add Note aboud audit fields

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#2806]
Could you please add the note about audit fields on this article as well.

> Copying the SystemID and [data audit](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-system-fields#audit) fields using CopyRows is supported in Business Central version 21.5 and later.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 932a01fe-bfc9-dd14-945f-f639f28d3385
* Version Independent ID: 932a01fe-bfc9-dd14-945f-f639f28d3385
* Content: [DataTransfer.AddFieldValue(Integer, Integer) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/datatransfer/datatransfer-addfieldvalue-method)
* Content Source: [dev-itpro/developer/methods-auto/datatransfer/datatransfer-addfieldvalue-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/datatransfer/datatransfer-addfieldvalue-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've added the note. The updated article will be published soon.
