### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by 35kartal35** [MicrosoftDocs/dynamics365smb-devitpro-pb#2807]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95672845-1cc2-6535-bbec-da2ff1acd0a1
* Version Independent ID: 152f5357-cd5d-4e8a-6bdf-839a8c4b8b87
* Content: [Developing Extensions in AL - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-dev-overview)
* Content Source: [dev-itpro/developer/devenv-dev-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-dev-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello to you too :) Closing this issue.

**Comment by 35kartal35** [comment]
ok see you.....
