### ISSUE TITLE
-Path mandatory?

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#281]
According to the instructions, the -Path parameter is mandatory.
Judging by most of the examples it isn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145706b1-b31f-6a74-3161-973e9f24baf0
* Version Independent ID: dcc5eb4b-28b5-5a06-853e-9e7681a21c2e
* Content: [Install-NAVApp (Microsoft.Dynamics.Nav.Apps.Management)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.Dynamics.Nav.Apps.Management/Install-NAVApp?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Apps.Management/Install-NAVApp.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Apps.Management/Install-NAVApp.md)

**Comment by jswymer** [comment]
Hello, the syntax is a bit confusing. There are two parameter sets, which are dependent on the whether you choose the use the -Path or-Name. This means that you can install the app by path or name.  That is if you use -Path, the -Name parameter is not valid and vice versa. It is stange but standard PowerShell syntax representation. We could add an example using -Path that could help clarify this. I hope this helps.
