### ISSUE TITLE
Example for setting DNS identity is faulty

### ISSUE THREAD

**Issue by JuricaB** [MicrosoftDocs/dynamics365smb-devitpro-pb#2810]
1st example in this section:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/implement-security-certificates-production-environment#using--2

is currently this:
Set-NAVWebServerInstanceConfiguration -WebServerInstance <web server instance> -KeyName DnsIdentity -KeyValue <true

Should be this:
Set-NAVWebServerInstanceConfiguration -WebServerInstance <web server instance> -KeyName DnsIdentity -KeyValue <DNSIdentity>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69ed5ffa-3ca0-0393-01d5-9d682719a6bd
* Version Independent ID: 709be381-ff65-c38b-34c0-b1c0dd9ef687
* Content: [Using Security Certificates with Business Central On-Premises - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/implement-security-certificates-production-environment)
* Content Source: [dev-itpro/deployment/implement-security-certificates-production-environment.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/deployment/implement-security-certificates-production-environment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the issues, and the updated article will be published soon.
