### ISSUE TITLE
Add warning about allowed characters in the Field Name for Application Area

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#2811]
Could you please add a warning that someone should only use Characters and Spaces in the field name of the new boolean field for adding an application area?
e.g. a hyphen **-** can lead to runtime errors.

Check out this issue: https://github.com/microsoft/ALAppExtensions/issues/19758

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a3450e9-9c90-8384-3fd1-0a207713fad6
* Version Independent ID: a0d40f3c-17e3-0024-c845-452b05b47354
* Content: [Extending Application Areas - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-application-areas)
* Content Source: [dev-itpro/developer/devenv-extending-application-areas.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-extending-application-areas.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we'll add info about the format in this article - available with next doc refresh. Thanks.
