### ISSUE TITLE
Circular link

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2812]
"For more information" link on this page is a circular link to this page:

Page URL: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/pagefield/devenv-onvalidate-pagefield-trigger

Link in text:

The OnValidate trigger is also a field trigger at the page level. For more information, see [OnValidate (Page Fields) Trigger](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/pagefield/devenv-onvalidate-pagefield-trigger).

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b5a94-9aa5-8b96-4e45-fdba855d9d66
* Version Independent ID: 5fd647f1-c9a6-7e96-cecc-07593eee8eb4
* Content: [OnValidate (Page Field) Trigger - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/pagefield/devenv-onvalidate-pagefield-trigger)
* Content Source: [dev-itpro/developer/triggers-auto/pagefield/devenv-onvalidate-pagefield-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/triggers-auto/pagefield/devenv-onvalidate-pagefield-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The link has been fixed and the update will be published soon.
