### ISSUE TITLE
Query Open - Cases for RunTime Error

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#2819]
Could you please specify which runtime errors can occur on metho `Open()` of a query?
I can't think of any reason.
The follwowing was mentioned on a PR for the business central baseapp:
https://github.com/microsoft/BusinessCentralApps/pull/239
```al
	public bool ALOpen(DataError errorLevel)
	{
		try
		{
			Open();
			return true;
		}
		catch (NavNCLDialogException) when (errorLevel == DataError.TrapError)
		{
			return false;
		}
		catch (NavALException) when (errorLevel == DataError.TrapError)
		{
			return false;
		}
	}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7c57086-19bb-c29b-c1ee-d6142971947b
* Version Independent ID: 7a0ab16a-1940-6220-ee05-a25eb83f95dc
* Content: [Query.Open() Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/query/queryinstance-open-method)
* Content Source: [dev-itpro/developer/methods-auto/query/queryinstance-open-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/query/queryinstance-open-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, but this is out of scope for this reference article - we don't document runtime errors as it is right now. Thanks.
