### ISSUE TITLE
Where on the "Users" page is the "Web Service Access Key field"?

### ISSUE THREAD

**Issue by wolterOnEntocare** [MicrosoftDocs/dynamics365smb-devitpro-pb#282]
When trying to set up Basic Authentication, I find that on the "Users" page there is no "Web Service Access Key field". But if I go to a particular user card (e.g. my own), then there is a "Process" called "Change Web service Key". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. You're right - the instructions have left out information, because you need to go into the User card to see the Web Service Access field and generate a Web Service Access Key. I will fix this in the topic for the next refresh of the docs. Thanks again!
