### ISSUE TITLE
Tyhoai

### ISSUE THREAD

**Issue by Hoaity** [MicrosoftDocs/dynamics365smb-devitpro-pb#2824]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31e72d71-172f-e784-eaab-4f4e26897eae
* Version Independent ID: 36635fe0-cfc5-836a-fdd4-98a422cf0309
* Content: [Image Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-image-property)
* Content Source: [dev-itpro/developer/properties/devenv-image-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-image-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
No description, closing this issue. Thanks.
