### ISSUE TITLE
Please add BC22 to the list of versions

### ISSUE THREAD

**Issue by TF-PDJ** [MicrosoftDocs/dynamics365smb-devitpro-pb#2826]
Please add BC22

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bac24fa-c9eb-695a-bdd5-3dbe4109a0dc
* Version Independent ID: a09fc47a-123f-a136-d4e5-e986dfc94522
* Content: [Choosing Runtime Version in AL - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-choosing-runtime)
* Content Source: [dev-itpro/developer/devenv-choosing-runtime.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-choosing-runtime.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
