### ISSUE TITLE
Could not find a property named 'id' on type 'NAV.SalesOrder'

### ISSUE THREAD

**Issue by nikhil075** [MicrosoftDocs/dynamics365smb-devitpro-pb#2827]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79b41dd1-876e-038e-d81a-371b0ce9ad78
* Version Independent ID: 89f5a8b1-6beb-b511-fa00-506f640f01f4
* Content: [Get salesOrders - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_salesorder_get)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_salesorder_get.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_salesorder_get.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback - I see id as part of the body when making a GET request - can you elaborate on what the issue is? Thanks

**Comment by nikhil075** [comment]
Thank you for your response.The issue is already resolved. As i was using
ODataV4 for get request for the api so i was not getting id field that is
in business central base api .so when  i used api/(beta/v1.0/v2.0) ,i got
the response I wanted along with id field
