### ISSUE TITLE
No examples? 

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#283]
It would be helpful to how the values of this parameter are set, and what they look like in the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 954879e0-7e31-7390-16f6-4f300a393ce0
* Version Independent ID: 06f4b2a0-e642-7816-188e-ec5b73eab494
* Content: [RunPageView Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/runpageview-property)
* Content Source: [dynamics-nav/RunPageView-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/RunPageView-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We know that content is lacking for some properties and this is on our backlog of things to do for a future release. Thanks again.
