### ISSUE TITLE
Record.FindSet Deprecated

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#2835]
This version of the FindSet method comes up first in a lot of searches, but doesn't address the pending runtime 11 deprecation.

It should align with the RecordRef.FindSet(Boolean,Boolean) documentation:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-findset-boolean-boolean-method

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c04d0987-98cd-f11e-eb8c-432515b70507
* Version Independent ID: 41ad0925-d71c-da6a-6691-5cb6a50f3702
* Content: [Record.FindSet(\[Boolean\] \[, Boolean\]) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-findset-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-findset-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-findset-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - this is a code defect. Will open a code defect, and close this doc issue. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
We've fixed this and the docs are refreshed, so hopefully you'll now see what you expect.
