### ISSUE TITLE
Wrong description in the page 'Code Conversion from C/AL to AL'

### ISSUE THREAD

**Issue by yishengcao** [MicrosoftDocs/dynamics365smb-devitpro-pb#2836]
This has a mistake in Task 5 section 2.a
Mistake: Create a folder for storing the AL files for base application objects (for example, **c:\export2al\baseapplication\al**).
Should be: Create a folder for storing the AL files for base application objects (for example, **c:\export2al\testlibrary\al**).

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/devenv-code-conversion#run-the-txt2al-conversion-tool

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
