### ISSUE TITLE
API V.20 salesOrderLines endpoint is no longer working as of Business Central Release 22.0.54157.54644

### ISSUE THREAD

**Issue by blairwatkins** [MicrosoftDocs/dynamics365smb-devitpro-pb#2837]
as referenced from: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_salesorderline_create

It looks as if your endpoint is no longer supported with Business Central Release: 22.0.54157.54644

{{BaseURL}}v2.0/{{TenantID}}/{{EnvName}}/api/v2.0/companies({{companyId}})/salesOrderLines

post:

{
"documentId": "844fdcf3-4ee5-ed11-8848-000d3a622940",
"sequence": 10000,
"itemId": "7d99fe0e-fac9-ed11-94cc-000d3a220b2f",
"lineType": "Item",
"lineObjectNumber": "1996-S",
"description": "ATLANTA Whiteboard, base",
"unitOfMeasureId": "d999fe0e-fac9-ed11-94cc-000d3a220b2f",
"unitOfMeasureCode": "PCS",
"quantity": 12,
"unitPrice": 1397.3,
"discountAmount": 0,
"discountPercent": 0,
"taxCode": "FURNITURE",
"shipmentDate": "2023-05-30",
"invoiceQuantity": 12,
"shipQuantity": 12,
"itemVariantId": "00000000-0000-0000-0000-000000000000",
"locationId": "00000000-0000-0000-0000-000000000000"
}

error:
{
"error": {
"code": "Internal_ServerError",
"message": "You cannot change the value of the SystemId field.\r\n\r\nTable: Sales Line\r\n\r\nIdentification fields and values:\r\nDocument Type='Order',Document No.='S-ORD101010',Line No.='10000' CorrelationId: 328e0d00-87f0-41c3-9d44-4cad01037865."
}
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0c7a1fa-04ce-545a-2e0c-6742cff2a456
* Version Independent ID: 60164a78-9c7e-254c-f2c6-e228dcc943dd
* Content: [Create salesOrderLines - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_salesorderline_create)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_salesOrderLine_create.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_salesOrderLine_create.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blairwatkins** [comment]
{{BaseURL}}v2.0/{{TenantID}}/{{EnvName}}/api/v2.0/companies({{companyId}})/salesOrderLines

post:

{
    "documentId": "844fdcf3-4ee5-ed11-8848-000d3a622940",       
    "sequence": 10000,
    "itemId": "7d99fe0e-fac9-ed11-94cc-000d3a220b2f",
    "lineType": "Item",
    "lineObjectNumber": "1996-S",
    "description": "ATLANTA Whiteboard, base",
    "unitOfMeasureId": "d999fe0e-fac9-ed11-94cc-000d3a220b2f",
    "unitOfMeasureCode": "PCS",
    "quantity": 12,
    "unitPrice": 1397.3,
    "discountAmount": 0,
    "discountPercent": 0,
    "taxCode": "FURNITURE",
    "shipmentDate": "2023-05-30",
    "invoiceQuantity": 12,
    "shipQuantity": 12,
    "itemVariantId": "00000000-0000-0000-0000-000000000000",
    "locationId": "00000000-0000-0000-0000-000000000000"
}

error:
{
    "error": {
        "code": "Internal_ServerError",
        "message": "You cannot change the value of the SystemId field.\r\n\r\nTable: Sales Line\r\n\r\nIdentification fields and values:\r\nDocument Type='Order',Document No.='S-ORD101010',Line No.='10000'  CorrelationId:  328e0d00-87f0-41c3-9d44-4cad01037865."
    }
}

**Comment by blairwatkins** [comment]
I found the issue. "sequence" is no longer supported in the endpoint. I removed from the payload and order / lines insert as expected.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback and investigation! Will be fixed with the next doc refresh.
