### ISSUE TITLE
A version "Dynamics NAV 2019" does not exist

### ISSUE THREAD

**Issue by Kowa63** [MicrosoftDocs/dynamics365smb-devitpro-pb#2838]
[[Enter feedback here]]
[https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-features-platform#changes-in-2024-release-wave-2-version-250](url)
The internal version 14.x is not called _Dynamics NAV 2019_ (such a version does not exist), but _Dynamics 365 Business Central Spring 2019_. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d83e98b9-ae70-d03a-2aa9-2011f1db2eb2
* Version Independent ID: d83e98b9-ae70-d03a-2aa9-2011f1db2eb2
* Content: [Deprecated features in the client, server, database - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-features-platform#changes-in-2024-release-wave-2-version-250)
* Content Source: [dev-itpro/upgrade/deprecated-features-platform.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/deprecated-features-platform.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
