### ISSUE TITLE
Test runner with restrictive permissions

### ISSUE THREAD

**Issue by larswestman** [MicrosoftDocs/dynamics365smb-devitpro-pb#284]
In this sample you are using TestPermissions = Disabled. It would be nice to se the same sample with TestPermissions = Restrictive and the then required Test runner codeunit and how permissions are implemented there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7f2151-4fef-e6ab-bbc1-5b3e1b8c5b17
* Version Independent ID: 20ffa998-58d3-c843-87d5-3533e2fa7765
* Content: [Testing the Advanced Sample Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-advanced-example-test)
* Content Source: [dev-itpro/developer/devenv-extension-advanced-example-test.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-advanced-example-test.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by larswestman** [comment]
You should also explain how to use permissions when using the test runner included in the test toolikt (as in this code example) and if/when to use a custom built test runner. It really takes some time to understand this today since there's no documentation available covering this.

In the documentation I've seen so far it's only mentioned that you can lower permissions in the test runner, but in many scenarios I think it's better the lower the permissions after the required data has been setup. This means that the permissions are set inside the test function and not in a test runner.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We know that content is missing for testing and this is on our backlog of things to do for a future release. Thanks again.
