### ISSUE TITLE
Bug in OnAfterGetCurrRecord Subscriber in BC14

### ISSUE THREAD

**Issue by MacGnol** [MicrosoftDocs/dynamics365smb-devitpro-pb#2841]
I made a subscription to Page 95 "Sales Order Subform" - OnAfterGetCurrRecord and first my Subscriber was executed and after my subscriber the Page trigger "OnAfterGetCurrRecord" was executed.

I have tested it in BC14.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7fac1d7-1081-0cf1-e290-454f2bf46022
* Version Independent ID: 91fa0669-ad94-0224-272b-b423974cca3f
* Content: [OnAfterGetCurrRecordEvent (Page) Trigger Event - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/events/page/devenv-onaftergetcurrrecordevent-page-trigger)
* Content Source: [dev-itpro/developer/triggers-auto/events/page/devenv-onaftergetcurrrecordevent-page-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/triggers-auto/events/page/devenv-onaftergetcurrrecordevent-page-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
