### ISSUE TITLE
How to extend Option Field in CRM Invoice?

### ISSUE THREAD

**Issue by samsiddiquiz** [MicrosoftDocs/dynamics365smb-devitpro-pb#2843]
How to extend Option Field in CRM Invoice? We added new options in CRM Invoice Table Field StatusCode but that options are missing in Business Central?

![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/32498803/48fb0f6f-d9cf-4ba1-863d-532f3ec91d13)

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback - please add the docs article that this issue is related to - thanks
