### ISSUE TITLE
Table field captions are generated even without GenerateCaptions flag

### ISSUE THREAD

**Issue by ViktorasDanielius** [MicrosoftDocs/dynamics365smb-devitpro-pb#2846]
When field doesn't have caption specified it is still included into translation file even without GenerateCaptions flag. That is wrong - there are some buffer tables or system fields which are not shown to a user and we don't want to translate them. It worked correctly on runtime 9. But starting from runtime 10 it works wrongly.

For example if we have field:
        field(1; "Code"; Code[20])
        {
        }

Caption is not specified, but it appears on translation file and there is no way to not include it.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is meant for documentation issues only. This looks like a product bug. Please use your usual support channel to file a bug. Thanks.
