### ISSUE TITLE
This page is five months old. Are these guidelines still valid? 

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2848]
This page is five months old. Are these guidelines still valid? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57f1e99e-e216-3b0e-79b3-d9287e6650e3
* Version Independent ID: 3b93c687-7ed2-8ad6-dce5-3adadb9491d6
* Content: [App type, contact type, and customer leads - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-checklist-e-industries-categories-apptype#listing-type)
* Content Source: [dev-itpro/developer/readiness/readiness-checklist-e-industries-categories-apptype.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/readiness/readiness-checklist-e-industries-categories-apptype.md)
* Service: **dynamics365-business-central**
* GitHub Login: @a-emniel
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Yes, we've reached out to the readiness team, and can confirm that these guidelines still apply. Thanks.
