### ISSUE TITLE
API 2.0 Version missing

### ISSUE THREAD

**Issue by rtslbrnft** [MicrosoftDocs/dynamics365smb-devitpro-pb#2851]
Please add API 2.0 YAML file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3f68316-e01d-f777-6992-40c61ceace15
* Version Independent ID: 0d15da82-fb45-3d49-dfd8-e40913122bdc
* Content: [(v1.0) 'OpenAPI Specification' - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v1.0/dynamics-open-api)
* Content Source: [dev-itpro/api-reference/v1.0/dynamics-open-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v1.0/dynamics-open-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
