### ISSUE TITLE
Fiedref.IsEnum not available

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#2858]
Hi,

It seems like a new(?) or obsoleted command exist in the menu.

![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/34970096/ff45bd90-7af2-4387-83b7-e1914b8abf7b)

But the page isn't available and so is not the command in AL
![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/34970096/f97dd109-1ead-4fc7-9826-a306bd3ad0c6)

![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/34970096/94d95169-b77a-4622-8062-90eb3124984c)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe34b23c-5e03-450d-fe50-205ee30ad08e
* Version Independent ID: 9e04f922-2729-040f-054d-9baf9f22f72b
* Content: [FieldRef.GetEnumValueOrdinal(Integer) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-getenumvalueordinal-method)
* Content Source: [dev-itpro/developer/methods-auto/fieldref/fieldref-getenumvalueordinal-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/fieldref/fieldref-getenumvalueordinal-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dannoe** [comment]
see https://marketplace.visualstudio.com/items/ms-dynamics-smb.al/changelog

>New FieldRef.IsEnum method
>
>Addition of the new FieldRef.IsEnum method, which allows to check if a field is an enum.

FieldRef.IsEnum is introduced with Version 12.0 (still in preview) of the AL VSX. You need to install the preview version if you want to use it right now.
