### ISSUE TITLE
"See Also" lacking Testing content

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#286]
In the "See Also" section, please add some helpful links about the Test Codeunits, hence at least the article that calls the current article. It is in general a big pity that we cannot see where in the TOC we currently are, but the latter applies to all articles actually..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c026a3b-2e03-5166-db04-782fc38d53bf
* Version Independent ID: e47dd45e-1248-4af9-1335-8db047b7c3e4
* Content: [MethodType Property (Test Codeunits) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-methodtype-property-test-codeunits)
* Content Source: [dev-itpro/developer/properties/devenv-methodtype-property-test-codeunits.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-methodtype-property-test-codeunits.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, you have a good point. We are considering adding much more content to the TOC in a future release. Also, the test area is a backlog item that we're well aware of. Thanks again.
