### ISSUE TITLE
codeunit 50100 DoPost should reference Number through Rec.Number

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#2867]
Codeunit 50100 DoPost contains a repeating error: `Number` should be `Rec.Number`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aefac484-b790-e5ed-6944-ef7c7c5398d7
* Version Independent ID: aefac484-b790-e5ed-6944-ef7c7c5398d7
* Content: [Collecting Errors - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-error-collection)
* Content Source: [dev-itpro/developer/devenv-error-collection.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-error-collection.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the article. The update will be published soon.
