### ISSUE TITLE
Incorrect URLs in examples

### ISSUE THREAD

**Issue by ajkauffmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#2868]
The URL's provided in the examples are incorrect.
Bound actions always use lower case for the first character.

So, instead of NAV.Copy it should be NAV.copy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29918409-632f-d4a1-b24b-f91e20c7cf0e
* Version Independent ID: 73df4239-bf75-7b0e-4f32-b62fa4d1356f
* Content: [Creating and Interacting with an OData V4 Bound Action - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-bound-action)
* Content Source: [dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-bound-action.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-bound-action.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next refresh of the docs.
