### ISSUE TITLE
Working as well on Dynamics NAV 2015?

### ISSUE THREAD

**Issue by ricarvalho81** [MicrosoftDocs/dynamics365smb-devitpro-pb#287]
I would like to know if there is oData V4 on Dynamics NAV 2105. Thanks .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc3b124e-b1cf-6169-386c-7ed466e0a78d
* Version Independent ID: 7e63c510-35cb-226b-5d78-7ba7d045a0eb
* Content: [Walkthrough: Creating and Interacting With an OData V4 Bound Action - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough-creating-and-interacting-odata-v4-bound-action)
* Content Source: [dynamics-nav/walkthrough-creating-and-interacting-odata-v4-bound-action.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/walkthrough-creating-and-interacting-odata-v4-bound-action.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Sorry for the delayed response. Unfortunately the ODatav4 endpoint is not supported on Dynamics NAV 2015. It was introduced in NAV 2017. Thanks for the feedback.
