### ISSUE TITLE
Data compression

### ISSUE THREAD

**Issue by DavidCurd** [MicrosoftDocs/dynamics365smb-devitpro-pb#2871]
The article says: 

For more information about data compression, see [Data Access - Using SQL Server data compression](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/optimize-sql-data-access).

However, that page doesn't discuss compression.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df637fa3-b799-f087-eecb-2a7407745159
* Version Independent ID: 014dde78-d534-c35e-d7d5-154c31f5f756
* Content: [Keeping Database Size Under the Limit - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/database-reduce-data)
* Content Source: [dev-itpro/administration/database-reduce-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/database-reduce-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the link and an update will be published soon.
