### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rcfoyn** [MicrosoftDocs/dynamics365smb-devitpro-pb#2873]
Search for DataAccessControl and correct to DataAccessIntent

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44f5e59c-1b47-6ee7-057e-2ac7b42d3974
* Version Independent ID: 5ad0932d-0a68-9547-7644-5f666386e12b
* Content: [Performance Article For Developers - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/performance/performance-developer#using-read-scale-out)
* Content Source: [dev-itpro/performance/performance-developer.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/performance/performance-developer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @KennieNP
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Good catch, thanks! We've fixed the articles and an update will be published soon.
