### ISSUE TITLE
Setting the type of the product doesn't work as described

### ISSUE THREAD

**Issue by egbertwietses** [MicrosoftDocs/dynamics365smb-devitpro-pb#288]
In the example it shows in order to set the type of a product: pass through string 'Inventory'.
On the item overview it says set a numeric value 1 or 2.
While in fact it has to be a string value 0 or 1 ( 0 = Inventory and 1 = Service )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8052735-8b52-cd64-2f6a-d4db2f4f20b2
* Version Independent ID: 2f4a5a8a-c189-5a09-8be1-45cade1e1a08
* Content: [Create items - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_create_item)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_create_item.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_create_item.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by egbertwietses** [comment]
So when i find 5 bugs I get a fee T-shirt right ;)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback :) nice catch - and I cannot promise you a t-shirt, but your feedback is much appreciated. This will be updated with the next refresh of the docs.
