### ISSUE TITLE
borken link

### ISSUE THREAD

**Issue by wic365** [MicrosoftDocs/dynamics365smb-devitpro-pb#2881]
[Enter feedback here]
The multi-file Download link in the "Note" section is broken. It links to [https://community.dynamics.com/forums/thread/?partialUrl=220.multi-file-download]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 200d72e3-3134-b81a-44bf-8e8050aa8b4f
* Version Independent ID: d0003d57-5e71-5e5b-fef3-117b78e406c0
* Content: [File.DownloadFromStream(InStream, Text, Text, Text, var Text) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-downloadfromstream-method?ranMID=46130&ranEAID=mP6UMnc5Ozo&ranSiteID=mP6UMnc5Ozo-dQRD_Wp51vSv1uTrdMZ_DQ&epi=mP6UMnc5Ozo-dQRD_Wp51vSv1uTrdMZ_DQ&irgwc=1&OCID=AID2200057_aff_7806_1243925&tduid=(ir__ngpfghx96skf6zoxfl9yvpgsmf2xe1rfctmwpo1s00)(7806)(1243925)(mP6UMnc5Ozo-dQRD_Wp51vSv1uTrdMZ_DQ)()&irclickid=_ngpfghx96skf6zoxfl9yvpgsmf2xe1rfctmwpo1s00)
* Content Source: [dev-itpro/developer/methods-auto/file/file-downloadfromstream-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/file/file-downloadfromstream-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The link will be fixed with the next doc refresh. In the meantime, please visit https://alguidelines.dev/docs/navpatterns/patterns/multi-file-download/ to read about multi-file download. Thanks
