### ISSUE TITLE
Re-write Partner-Only Assets paragraph

### ISSUE THREAD

**Issue by louisik1** [MicrosoftDocs/dynamics365smb-devitpro-pb#2889]
This paragraph has a grammatical error and an informal tone (see added emphasis).  I recommend it be re-written according to standards:

> Where can I find partner-only assets and links?
> If you were familiar with PartnerSource, then the new [Dynamics 365 Business Central Partner Portal](https://dynamicspartners.transform.microsoft.com/products/dynamics-365-business-central) site is very different. _But it host a lot of useful links and other assets that can help you ramp up on what's going on with Business Central._ The site requires that you sign in with a partner account. Some assets are marked as confidential and cannot be shared with clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0ef3bc-7516-dae7-6cca-d5a9b680364f
* Version Independent ID: 288d30ad-0b2d-8c18-63fa-d5555eb7416e
* Content: [FAQ about developer and admin experiences - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/faq#how-often-are-production-databases-backed-up)
* Content Source: [dev-itpro/faq.yml](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/faq.yml)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the spelling error. The update will be available soon.

Microsoft's tone is a more empathetic, friendly, and conversational tone than we used in the past, with the hope that the content is more relatable and engaging for the audience.
