### ISSUE TITLE
New-NAVCRMTable cmdlet + export to new syntax + TXT2AL?

### ISSUE THREAD

**Issue by CanuckNav74** [MicrosoftDocs/dynamics365smb-devitpro-pb#289]
Is there any reason why these tools are absent in the D365 Sales extension development documentation? 

New entities can be quite hefty to code by hand in VS Code and IMHO these utilities would be essential to expedite extension  development efforts when creating a new CRM entity table in BC. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be8fe372-cf07-dd43-c310-9143eb39d881
* Version Independent ID: e1b5c717-91e3-6045-67ba-9883addb24f5
* Content: [Enabling Sales Tables for Extension Development - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-integrating-dynamics-365-for-sales-extension-development)
* Content Source: [dev-itpro/developer/devenv-integrating-dynamics-365-for-sales-extension-development.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-integrating-dynamics-365-for-sales-extension-development.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We know that content is missing for Sales and this is on our backlog of things to do for a future release. Thanks again.
