### ISSUE TITLE
No mention of latest version (BC22)

### ISSUE THREAD

**Issue by mynhardt7** [MicrosoftDocs/dynamics365smb-devitpro-pb#2893]
In the section "Supported migration paths" it mentions versions 14 to 20 and 21. No mention of the latest available version (22).

Business Central on-premises

Currently, you can migrate to Business Central online from the earlier versions **14 through 20**. For an indication of compatibility across minor versions, see [here](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility). You can also switch to online from the **current version (21)**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed3ca299-5ceb-5fd4-6f80-b9657a742692
* Version Independent ID: f4b4f9ee-f3d9-7ba0-c599-06983245b0cf
* Content: [Migrate on-premises data to the cloud - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/migrate-data)
* Content Source: [dev-itpro/administration/migrate-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/migrate-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the articles and the update will be pusblished soon.
