### ISSUE TITLE
Supported Upgrade Paths missing latest version (22)

### ISSUE THREAD

**Issue by mynhardt7** [MicrosoftDocs/dynamics365smb-devitpro-pb#2894]
The "Supported Upgrade Paths" page makes no mention of the latest available version (22).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a44993a-d0a7-4756-5a75-e20ee9770bae
* Version Independent ID: bf2126fb-1dea-d29e-9273-720512b2061f
* Content: [Supported upgrade paths to Business Central on-premises - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-paths)
* Content Source: [dev-itpro/upgrade/upgrade-paths.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-paths.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the articles and the update will be pusblished soon.
