### ISSUE TITLE
Additional Info

### ISSUE THREAD

**Issue by ThomasBrodkorb** [MicrosoftDocs/dynamics365smb-devitpro-pb#29]
The information, "If they are not there you will be prompted" is maybe not sufficient.
It would be nice to get the info "who" will "at what time" prompt me to download from "where".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a33c82cf-51a6-96a1-4aba-7686df806950
* Version Independent ID: 7dda0849-5fdd-0549-ee80-50ec65287767
* Content: [Symbol Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-symbols)
* Content Source: [dev-itpro/developer/devenv-symbols.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-symbols.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. If the AL extension in Visual Studio Code detects that the referenced symbols are not present on the local disk, you will get a visual prompt in Visual Studio Code to download the symbols from one of the servers specified in the launch.json file. The documentation is updated with the next refresh.
