### ISSUE TITLE
Wrong syntax for idRanges

### ISSUE THREAD

**Issue by larswestman** [MicrosoftDocs/dynamics365smb-devitpro-pb#291]
The square brackets are missing. It's an array.

Correct syntax can be found here: https://community.dynamics.com/business/b/businesscentraldevitpro/archive/2018/11/19/developer-preview-november-2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
We have fixed the syntax and the update will be published soon. Thanks for the feedback!
