### ISSUE TITLE
Clarification on "true Dynamics 365 Business Central SaaS environment"

### ISSUE THREAD

**Issue by larswestman** [MicrosoftDocs/dynamics365smb-devitpro-pb#292]
What do you mean here? Do you mean Azure or is it sufficient with a sandbox in docker? 

On pages like this I would love to see links such as:
- How to test your extension in Azure.
- How to test your extension in a Docker sandbox.
- How to sign your extension.
- How to build automated test routines with lowered permissions.
- How to uninstall, unbulish, republish and reinstall your extension.

You should try to answer all questions the user might have on the text by providing how-to links

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936119a1-4f7e-ed69-f72e-44e41464f964
* Version Independent ID: c30741c6-9408-775a-5ce0-3f6986445447
* Content: [Testing your Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-testingyourextension)
* Content Source: [dev-itpro/compliance/apptest-testingyourextension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-testingyourextension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by ryanweigel** [comment]
It can be Azure or sandbox in Docker. We use Docker for our validation testing so Docker is acceptable.
We are working on improving the documentation around testing your extension and recommendations around that. For your other bullet points, those topics are covered in our technical checklist page. You can check that out here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission

**Comment by larswestman** [comment]
Thanks!
