### ISSUE TITLE
Properties are missing

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#2935]
I've just crated PR #2934 to fix at least the `Obsoleted*` properties, but could you please give the list a complete overhaul?
There are at least two further properties missing, like `DecimalPlaces`. I did not check for more.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5367809-8bc3-af4d-f43c-92ec6bbbace6
* Version Independent ID: 31321a54-c0a5-d7a5-8c6e-62113b479751
* Content: [Table, Table Fields, and Table Extension Properties - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-table-properties)
* Content Source: [dev-itpro/developer/properties/devenv-table-properties.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-table-properties.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, Natalie - I've merged your PR.
