### ISSUE TITLE
Documentation for Property FunctionVisibility is missing

### ISSUE THREAD

**Issue by RaKuNbg** [MicrosoftDocs/dynamics365smb-devitpro-pb#294]
In the section "C/AL Globals Functions Properties" I'm missing a documentation for the property FunctionVisibility.

In general, all the sections from "C/AL Globals Variables Properties" down to "C/AL Locals Return Values Properties" don't belong in the page codeunit-properties as these properties can be set on almost every object type ==&gt; there should be an extra page "General Properties"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee129f4-c53f-05f7-8ac7-99dc3bb0f604
* Version Independent ID: 11efe4b2-5e04-e548-4b29-21d39389a812
* Content: [Codeunit Properties - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/codeunit-properties)
* Content Source: [dynamics-nav/Codeunit-Properties.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Codeunit-Properties.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hi - thanks for your feedback. I agree that the structure isn't ideal. We are working on improving reference documentation, also for properties, in the Business Central [docset](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/?branch=master) going forward. And we do lack info on the FunctionVisibility property, that should be added with one of the next doc refreshes. Thanks.
