### ISSUE TITLE
Workings of itemCategory not clear

### ISSUE THREAD

**Issue by egbertwietses** [MicrosoftDocs/dynamics365smb-devitpro-pb#295]
If i supply the itemCategory on a new item and the itemCategory already exists, I get an error: The record in table Item Category already exists.

This is weird because how am I able to set the itemCategory on an item then? Why does it tries to create it and not just link the existing itemCategory?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da3d76f8-6996-c2ee-0a26-ab63f798ca6b
* Version Independent ID: 87673447-d246-e5f9-477e-b2cc096df67c
* Content: [items resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/resources/dynamics_item)
* Content Source: [dynamics-nav/fin-graph/resources/dynamics_item.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/resources/dynamics_item.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
Hi egbertwietses
I can insert a new item by
POST {{url}}/companies({{companyId}})/items
{
 "displayName" : "Super Chair",
 "itemCategoryId" : "024dc9fa-de7d-40bd-8163-dee35f0ade58"
}

Get the details for categories by issuing:
GET {{url}}/companies({{companyId}})/itemCategories

Let me know if it helps.

/Henrik

**Comment by SusanneWindfeldPedersen** [comment]
Closing issue for now.
