### ISSUE TITLE
Upgrade to Version 21: Missing Step for (Re-)Publishing the system.app (symbolsonly)

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#2950]
This upgrade side misses a step for publishing the system.app.
Check out older upgrade steps (https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v16-to-v17#task-6-publish-symbols-and-extensions)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31423217-760c-0c19-b213-b782ba85ddcb
* Version Independent ID: 31423217-760c-0c19-b213-b782ba85ddcb
* Content: [Upgrading Microsoft System and Base Application to Version 21 - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v21)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v21.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v21.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hi, thanks for the feedback.

Starting around version 20, the Invoke-NavApplicationDatabase should install the system symbols automatically when you are going from one major version to the next. Did you happen to get an error or warning when you ran the Invoke cmdlet?

**Comment by pri-kise** [comment]
But shouldn't we _publish_ the new version of the system.app?

Or did you mean that ` Invoke-NavApplicationDatabase` publishs the new System.App Version?

**Comment by jswymer** [comment]
Sorry, yes what I meant is that Invoke-NAVApplicationDatabaseConversion adds the system symbols for the new version to the database, so you don't have to manually publish the System.app extension, as you had to do with early releases.

**Comment by pri-kise** [comment]
Okay. thanks for you quick response.
Someone on twitter reported this - I will talk to my it guys internally.

**Comment by jswymer** [comment]
Although it doesn't apply to major version upgrades, but when running a minor update, it's important to use the -force switch with the Invoke-NavApplicationDatabaseConversion cmdlet.

**Comment by NAVFreak** [comment]
@jswymer 
> Although it doesn't apply to major version upgrades, but when running a minor update, it's important to use the -force switch with the Invoke-NavApplicationDatabaseConversion cmdlet.

It doesn't apply to version upgrades? Because it specifically states it does in the upgrade manual
![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/34970096/808415cc-87c7-430a-89f0-e88349317fa8)
As described [here](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v22#task-7-publish-extensions).

And it doesn't have force as a mandatory parameter either






 
> https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v22#convert-existing-database-to-new-platform

**Comment by jswymer** [comment]
My statement was referring to using the -force parameter when running a major upprade. The step for the minor update is:

Invoke-NAVApplicationDatabaseConversion -DatabaseServer $DatabaseServer -DatabaseName $TenantDatabase|$ApplicationDatabase -Force
