### ISSUE TITLE
If-Else indenting.

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#296]
The indenting of if-else statements is disgusting.

As an example, and hopefully this keeps the indenting as it is currently auto formatted with the language extension:

        if (x0) then
            y0
        else
            if (x1) then
                y1
            else
                if (x2) then
                    y2;
This is the wrong way to format this. The correct way (maintaining the silly if on new line) would be:

        if (x0) then
            y0
        else
        if (x1) then
            y1
        else
        if (x2) then
            y2;
Or even:

        if (x0) then
            y0
        else
            if (x1) then
                y1
        else
            if (x2) then
                y2;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efb2b7f8-e259-be2b-c7bf-bfdf57002029
* Version Independent ID: 4205d692-adaf-aa55-f66b-211310fe2745
* Content: [AL Formatter - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-formatter)
* Content Source: [dev-itpro/developer/devenv-al-formatter.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-formatter.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. For any product related feedback please use the Product feedback mechanism - this repo is only for doc issues. Thanks.

**Comment by Frantic42** [comment]
mjmatthiesen: You are wrong.
