### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by grahammathias** [MicrosoftDocs/dynamics365smb-devitpro-pb#297]
The link to "Get started with the Container Sandbox Development Environment" is invalid. It should point to this:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-container-sandbox

**Comment by grahammathias** [comment]
The topic was "Features not implemented in on-premises deployments of Dynamics 365 Business Central". Here is the link: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/features-not-implemented-on-premises

**Comment by SusanneWindfeldPedersen** [comment]
Super, thanks. This is fixed with the next refresh of the docs.
