### ISSUE TITLE
Please elaborate.

### ISSUE THREAD

**Issue by jdivis** [MicrosoftDocs/dynamics365smb-devitpro-pb#298]
I landed here looking for a description of the differences between the XML, Variable text and Fixed Text selection values. When should I use XML vs Variable Text vs Fixed Text? What are the ramifications for the file being imported? Can any CSV that matches a particular format be imported, or does the file have to come from the export function first, in order to be imported through either the Fixed Text or Variable Text options?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c9b8e3-5030-dab5-84c3-bc2a69b62f03
* Version Independent ID: 75849367-2a44-165c-e38b-16a8ff3404f1
* Content: [Format Property (XMLports) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/format-property--xmlports-)
* Content Source: [dynamics-nav/Format-Property--XMLports-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Format-Property--XMLports-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We've added XMLports documentation to our backlog for a future release.
