### ISSUE TITLE
Embedded Parameter?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#299]
Page Action "Customer Ledger" on page 116 "G/L Registers" has its RunObject property set to "Codeunit G/L Reg.-Cust.Ledger". Codeunit 236, "G/L Reg.-Cust.Ledger"'s OnRun trigger has a record parameter:  "OnRun(VAR Rec : Record "G/L Register")". But there is no parameter on the RunObject property, and RunPageView and RunPageLink are Undefined. Is the passing of the G/L Register record implicit--passing the record in the G/L Registers page which is selected? And if so, should this fact not be documented here? Is this a general behavior for the RunObject property of any Page Action?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 490b5c3c-075b-91c8-145a-ea2dcbc9f5ce
* Version Independent ID: b6887584-12b6-f744-0e92-abc7d2a519a8
* Content: [RunObject Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/runobject-property)
* Content Source: [dynamics-nav/RunObject-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/RunObject-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset.
