### ISSUE TITLE
Mention Remove-NAVApplication​Object​Language

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#30]
I would expect to be referred to https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.model.tools/Remove-NAVApplicationObjectLanguage as an alternative solution.
The advantage is that you do not need a running NAV service for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eb46b16-7fe3-5ca0-91c7-c45fee81d161
* Version Independent ID: 4a555a27-eb46-2b3a-9450-37d21cfbf8ed
* Content: [How to: Delete Translated Strings - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--delete-translated-strings)
* Content Source: [dynamics-nav/How-to--Delete-Translated-Strings.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Delete-Translated-Strings.md)
* Service: **unspecified**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback!

We have updated the article with a reference to the Remove-NAVApplicationObjectLanguage cmdlet. This change will be available the next time we refresh the content.
