### ISSUE TITLE
Get all items, pagination?

### ISSUE THREAD

**Issue by egbertwietses** [MicrosoftDocs/dynamics365smb-devitpro-pb#300]
Maybe some information on limitations when getting all items.
For example BC returns 20k products max, but I have no idea how to paginate to other items.
Something like: ?filter=Entry_No gt 20000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da3d76f8-6996-c2ee-0a26-ab63f798ca6b
* Version Independent ID: 87673447-d246-e5f9-477e-b2cc096df67c
* Content: [items resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/resources/dynamics_item)
* Content Source: [dynamics-nav/fin-graph/resources/dynamics_item.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/resources/dynamics_item.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by egbertwietses** [comment]
Found out that top and skip is implemented, maybe add it somewhere.
/items?$top=100&$skip=100

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for the suggestion - we support a lot of common OData query types - but it might be a good idea to explicitly mention these. Will put this on our backlog. Thanks again.
