### ISSUE TITLE
Why not part of Business Central documentation?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#302]
This topic only resides under https://docs.microsoft.com/en-us/dynamics-nav. Why not under https://docs.microsoft.com/en-us/dynamics365/business-central?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3b1e0d7-8ea7-c1f4-2b37-da7f1c97a910
* Version Independent ID: 16bd860a-c6d9-4aa8-a435-72b7fc990464
* Content: [C/AL ASSERTERROR Statements - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/c-al-asserterror-statements)
* Content Source: [dynamics-nav/C-AL-ASSERTERROR-Statements.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/C-AL-ASSERTERROR-Statements.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, the content is included in the Business Central documentation, however, it is a sub-section of the [AL Simple Statements](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-simple-statements?#asserterror-statements) article. Although it is not directly linked to the table of contents, it can be found using search. Thanks for the feedback!

**Comment by lvanvugt** [comment]
Hi, OK clear, but if I search with google for "Business Central ASSERERROR" I do not get a hit on that topic. So, something needs to get fixed here.

**Comment by jswymer** [comment]
Hi Ivan, oddly enough, Bing seems finds the article, but not Google. I will see if there is a way we can enhance the search for Google. Thanks again!

**Comment by lvanvugt** [comment]
Thanx, js. What does js stand for? And just call me Luc. lvanvugt = Luc van Vugt ;-)

**Comment by jswymer** [comment]
Hi Luc, sorry about that. My initials are js (John Swymer).

**Comment by lvanvugt** [comment]
Please to meet you. ;-)
