### ISSUE TITLE
Why is topic not part of Business Central documentatio?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#303]
See topic title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceab92c1-9510-ed55-8bac-41b1614ebfb0
* Version Independent ID: 93786902-1621-bfd0-03f4-4dbb5bf35f11
* Content: [Create Handler Functions - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--create-handler-functions)
* Content Source: [dynamics-nav/How-to--Create-Handler-Functions.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Create-Handler-Functions.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We're aware of lacking docs for testing, and this is added to our backlog. Thanks again, closing this issue for now.
