### ISSUE TITLE
Very Informative

### ISSUE THREAD

**Issue by onyangofred** [MicrosoftDocs/dynamics365smb-devitpro-pb#3038]
Thanks for this article, it was very informative.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 310c0962-be0b-09bf-9147-9601f7853152
* Version Independent ID: a5a4068c-fecf-8127-dbe2-66c59320b1ce
* Content: [HttpClient.Post(Text, HttpContent, var HttpResponseMessage) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-post-method)
* Content Source: [dev-itpro/developer/methods-auto/httpclient/httpclient-post-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/httpclient/httpclient-post-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback.
