### ISSUE TITLE
calculator for transactios

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-devitpro-pb#3048]
Can we please get a calculator so we can enter in some key metrics to identify what limits partners can expect on the production environment?

eg. 8000 transactions per hour upload using standard fields no lots details, no serializaltion

People need to be able to test capbilites or expected capabilities 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fc3b614-8a3a-0858-80e2-781b1b6e1253
* Version Independent ID: eabcadf6-051e-6631-f5d6-16ccdcef62a7
* Content: [Operation Limits in Dynamics 365 Business Central - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/operational-limits-online)
* Content Source: [dev-itpro/administration/operational-limits-online.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/operational-limits-online.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback. This sounds like a great idea. Unfortunately we only handle documentation-related features. But you are welcome to submit a feature request at https://aka.ms/bcideas.
