### ISSUE TITLE
No Business Central version of this topic

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#305]
Would be grate to have a Business Central specific topic for this. Not in the least to add a syntax definition. The syntax HandlerFunctions tag for test functions is not that obvious, I think: HandlerFunctions('Handler1[,Handler2,…]')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4376e31d-db97-7c7d-3ed4-04429b7015cf
* Version Independent ID: 67b11555-4419-d7c0-dea7-851ad87d30a0
* Content: [HandlerFunctions Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/handlerfunctions-property)
* Content Source: [dynamics-nav/HandlerFunctions-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/HandlerFunctions-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, we know that we have yet to describe testing in our AL docset, this is on our backlog and will be available with a future refresh. Closing this issue for now. Thanks.
