### ISSUE TITLE
Regarding legacy FLF license file

### ISSUE THREAD

**Issue by Rukkulakki** [MicrosoftDocs/dynamics365smb-devitpro-pb#3052]
We have just run into a problem when updating a BC16 version straight to BC22.
During task 8 Sync-NAVTenant the process would break saying that it was not possible to read the license information.
The problem was tracked down to the database in question running the legacy FLF license, which BC22 is unable to handle. 
So I suggest making a note in the documentation stating that if the database that is being upgraded is running with a FLF license, then an additional step has to be made before Task 4 saying that license information needs to be deleted.

UPDATE [master].[dbo].[$ndo$srvproperty] SET [license] = null
UPDATE [<App DATABASE>].[dbo].[$ndo$dbproperty] SET [license] = null
UPDATE [<Tenant DATABASE>].[dbo].[$ndo$tenantproperty] SET [license] = null

https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2443422042177536

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d172d29-0a39-87a6-bbe0-a834430bcff2
* Version Independent ID: 1d172d29-0a39-87a6-bbe0-a834430bcff2
* Content: [Upgrading Microsoft System and Base Application to Version 22 - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v22)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-to-v22.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-to-v22.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the valuable feedback! We've included this info in the docs. The update will be available soon.
