### ISSUE TITLE
Typo in URL

### ISSUE THREAD

**Issue by rswaroop96** [MicrosoftDocs/dynamics365smb-devitpro-pb#3053]
This is the HTTP request template given 

GET businesscentralPrefix/companies({id})/purchaseReceiptLines({id})/purchaseReceiptLines({purchaseReceiptLineId})
GET businesscentralPrefix/companies({id})/purchaseReceiptLines({purchaseReceiptLineId})

In line 1 there is a typo (purchaseReceiptLines({id}) --> purchaseReceipts({id}))

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47e33fc8-c929-b5ca-39e3-f6ce95afb7dc
* Version Independent ID: 76d5249c-d6fc-bd84-25f2-31260a0bd588
* Content: [GET purchaseReceiptLines - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/api/dynamics_purchasereceiptline_get)
* Content Source: [dev-itpro/api-reference/v2.0/api/dynamics_purchasereceiptline_get.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/api/dynamics_purchasereceiptline_get.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback. This issue has been fixed.
