### ISSUE TITLE
You can use test pages only within test codeunits

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#306]
You can use test pages only within test codeunits.: technically this is not true. I can build a normal codeunit an us a test page. SO either change the remark on this topic and say something like "should only be used", or make the platform prevent it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39a02f64-cf1d-9e3a-500d-c8293d1d4f50
* Version Independent ID: f1bee4ac-5225-b9be-d7c9-5434d6152d51
* Content: [TestPage Data Type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/testpage-data-type)
* Content Source: [dynamics-nav/TestPage-Data-Type.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/TestPage-Data-Type.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Good point. This is gone in the [AL edition](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testpage/testpage-data-type) of the topic for the datatype, but I will change the wording in the Dynamics NAV content as well. Thanks.
