### ISSUE TITLE
page

### ISSUE THREAD

**Issue by Sathyasparta** [MicrosoftDocs/dynamics365smb-devitpro-pb#3067]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91153855-ada2-3420-eb1e-f0f4fa0d46c7
* Version Independent ID: 55d0d4e4-5232-882f-c600-fb9c7d409608
* Content: [Page Data Type - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-data-type)
* Content Source: [dev-itpro/developer/methods-auto/page/page-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/page/page-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

There is no feedback entered for this issue. We'll close this for now, but if you do have some feedback, you're welcome to provide it and we'll reopen the issue.

Thanks!
