### ISSUE TITLE
TestField datatype?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#307]
Since when do we have a data type called TestField? I know we have a TestPage data type and it has field methods, but there is no such thing as a TestField datatype.
Trying to find all methods that related to test pages is a very difficult one to do. Please get this improved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e5a79a-2e68-f63f-5609-bbdd5508bf7b
* Version Independent ID: ad6f513e-ad46-bbf2-87db-4f65dc8ac1cc
* Content: [TestField Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testfield/testfield-data-type)
* Content Source: [dev-itpro/developer/methods-auto/testfield/testfield-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/testfield/testfield-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, we know that we have yet to describe testing in our AL docset, this is on our backlog and will be available with a future refresh. Closing this issue for now. Thanks.

**Comment by ailie13** [comment]
Hi! All the expressions in the language have a type. Until now, the types for test fields and test actions was not formally specified. The types TestField and TestAction cannot be used as the types of variables, parameters, or return types in AL, but they are used by the platform library. Thank you for your feedback!

**Comment by lvanvugt** [comment]
> Hi! All the expressions in the language have a type. Until now, the types for test fields and test actions were not formally specified. The types TestField and TestAction cannot be used as the types of variables, parameters, or return types in AL, but they are used by the platform library. Thank you for your feedback!

Clear. Please add that to the topic.
