### ISSUE TITLE
Feature(s) missing for BC 23?

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#3074]
@KennieNP 
It looks like the following BC 23 feature was not added to this article yet: Tri-state locking in AL
![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/34504100/b86a2db9-05f2-499e-9faa-c3cf640029a0)

Are others maybe missing as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8f7a5f-12e7-b227-7c86-9e415a6c5e99
* Version Independent ID: 8d8f7a5f-12e7-b227-7c86-9e415a6c5e99
* Content: [Optional features now mandatory - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/feature-management-mandatory-features)
* Content Source: [dev-itpro/administration/feature-management-mandatory-features.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/feature-management-mandatory-features.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by KennieNP** [comment]
Thanks for noticing. We will fix it ASAP

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been updated and will be published soon.
