### ISSUE TITLE
Wrong text into section "Next steps"

### ISSUE THREAD

**Issue by lucacostamagnaeos** [MicrosoftDocs/dynamics365smb-devitpro-pb#3075]
I think there is a wrong text inside the "Next steps" section here:

"If you're using Business Central on-premises, the EnableTriStateLocking setting in the server configuration must also be set to false to **enable** tri-state locking. [Learn more about configuring the server](https://learn.microsoft.com/en-us/dynamics365/business-central//dev-itpro/administration/configure-server-instance#Database)."

I think the bolded text should be changed from "enable" to "disable", because if you set the parameter to false it is to disable the feature "EnableTriStateLocking ".
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4682caf-1b4f-6dbf-4007-ce01a8130f97
* Version Independent ID: b4682caf-1b4f-6dbf-4007-ce01a8130f97
* Content: [Tri-state locking in database - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central//dev-itpro/developer/devenv-tri-state-locking)
* Content Source: [dev-itpro/developer/devenv-tri-state-locking.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-tri-state-locking.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Good catch, thanks! The fix will be published soon.
