### ISSUE TITLE
The link to "Creating a rich text editor" is dead

### ISSUE THREAD

**Issue by JMA1972** [MicrosoftDocs/dynamics365smb-devitpro-pb#3079]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fde1227-7179-ab1e-9cbc-eb4415056328
* Version Independent ID: a377e4b5-e402-6d0f-30c8-7b056e89acee
* Content: [ExtendedDatatype Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-extendeddatatype-property)
* Content Source: [dev-itpro/developer/properties/devenv-extendeddatatype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-extendeddatatype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by tonyabriccomeske** [comment]
I think it's supposed to point to this link: 
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-richtext-content-controls

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this (and for helping out again @tonyabriccomeske!) This will be fixed with the next doc refresh
