### ISSUE TITLE
Needs explanation

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#3080]
Article really says nothing (not even formatting which is bare minimum), but it could helpfully link to: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inherent-permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60b455c0-678b-644b-f103-6689e4e8105a
* Version Independent ID: 60b455c0-678b-644b-f103-6689e4e8105a
* Content: [InherentPermissions Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-inherentpermissions-property)
* Content Source: [dev-itpro/developer/properties/devenv-inherentpermissions-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-inherentpermissions-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. Yes, agreed - we'll update with a link to more info with the next doc refresh. Thanks.
