### ISSUE TITLE
Creating a rich text editor link gives 404

### ISSUE THREAD

**Issue by bcapps-co** [MicrosoftDocs/dynamics365smb-devitpro-pb#3083]
[Enter feedback here]

Creating a rich text editor with the following link:

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-create-richtexteditor.md

Gives a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0533f0be-926a-fee4-412d-85917b6c5e73
* Version Independent ID: c4cadb92-3fbb-ed63-ae68-c777edffba67
* Content: [MultiLine Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-multiline-property)
* Content Source: [dev-itpro/developer/properties/devenv-multiline-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-multiline-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by tonyabriccomeske** [comment]
I think it's supposed to point to this link: 
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-richtext-content-controls

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this (and for helping out @tonyabriccomeske) - this will be fixed with the next refresh of the docs.
