### ISSUE TITLE
The code example on the page is missing and 'end;'

### ISSUE THREAD

**Issue by valgameiroconsulting** [MicrosoftDocs/dynamics365smb-devitpro-pb#3087]
var
    Contact: Record Contact;
    CRMIntegrationManagement: Codeunit "CRM Integration Management";
    ContactRecordRef: RecordRef;
begin
    CurrPage.SetSelectionFilter(Contact);
    Contact.Next;

    if Contact.Count = 1 then
        CRMIntegrationManagement.UpdateOneNow(Contact.RecordId)
    else begin
        ContactRecordRef.GetTable(Contact);
        CRMIntegrationManagement.UpdateMultipleNow(ContactRecordRef);
   END; // <<====
end;

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eba62cb1-b031-8836-e164-28229fc2d983
* Version Independent ID: c746c714-2e9d-245a-aa8e-6b97fe26064b
* Content: [Page.SetSelectionFilter(var Record) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/page/page-setselectionfilter-method)
* Content Source: [dev-itpro/developer/methods-auto/page/page-setselectionfilter-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/page/page-setselectionfilter-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
