### ISSUE TITLE
Invokes a field on a test page.

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#309]
An what does that mean "Invokes a field on a test page"? Validating? Putting focus on it? I know what Invoke does in the context of a test page action, but for a field?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee2d063-7a73-7e13-ae22-59304e442946
* Version Independent ID: 42b12905-7b33-a6c3-7fa6-57452eb4872f
* Content: [Invoke Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testfield/testfield-invoke-method)
* Content Source: [dev-itpro/developer/methods-auto/testfield/testfield-invoke-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/testfield/testfield-invoke-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by lvanvugt** [comment]
When I use Invoke on a field on a TestPage I get the error:
> The Invoke method is not supported.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, we know that we have yet to describe testing in our AL docset, this is on our backlog and will be available with a future refresh. Closing this issue for now. Thanks.
