### ISSUE TITLE
Upcoming changes to cloud migration need to be added to Supported Upgrade Paths

### ISSUE THREAD

**Issue by tonyabriccomeske** [MicrosoftDocs/dynamics365smb-devitpro-pb#3094]
Within the Supported Upgrade Paths page there should be some mention of the changes that will be coming in 2025 release wave 1 (version 26.0) 

I know many people reference the Supported Upgrade Paths page, and it's critical they realize that there will be a new "stepping stone" added to their migration/upgrade in the near future.

See documentation here: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-features-platform#changes-in-2025-release-wave-1-version-260

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a44993a-d0a7-4756-5a75-e20ee9770bae
* Version Independent ID: bf2126fb-1dea-d29e-9273-720512b2061f
* Content: [Supported upgrade paths to Business Central on-premises - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-paths)
* Content Source: [dev-itpro/upgrade/upgrade-paths.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-paths.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the valuable feedback! We've made the suggested changes and the updated article will be published soon.
