### ISSUE TITLE
Valid signs in filter expressions

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#3096]
Please take a look at the following articles:
https://learn.microsoft.com/en-us/search/?scope=BusinessCentral&terms=%22one%20or%20more%20of%20the%20following%20operators%3A%22

They all have the same filter expression parameter, but they differ in detail, and are partly wrong.
First of all, this is the list of all allowed operators:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-setfilter-method#remarks
![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/34504100/cda73d6b-4edc-41fd-ac03-cba2070b352c)
Hence, supported signs are `.&|<>=*@`.

But the articles list instead:
- DataTransfer.AddSourceFilter: `<, >, \, &, |, and =`
- FieldRef.SetFilter: `<, >, , &, |, and =`
- Query.SetFilter: `<, >, \, &, |, and =`
- Record.SetFilter: `<, >, \, &, |, and =`

`\` is wrong for sure.

**Comment by v-nithyamut** [comment]
Thanks for catching this, it will be fixed in a coming release.

**Comment by NKarolak** [comment]
Fixed with https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/commit/1928dbc2531bc114fbcafc5189922a48d66fc7a9. Thanks!
