### ISSUE TITLE
Code does not match the explanation below

### ISSUE THREAD

**Issue by Floris-G** [MicrosoftDocs/dynamics365smb-devitpro-pb#3097]
In the Code sample it says: "Value := '19960101'; " while the explanation assumes it is '010196'.

![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/53494433/76e93480-2cd9-4734-8545-7665d07dc912)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d41241e9-853c-ed41-b2fa-8b76423f562b
* Version Independent ID: 06d31e63-b91c-acb7-82b6-98bb66719a47
* Content: [System.Evaluate(var Any, Text \[, Integer\]) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-evaluate-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-evaluate-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/system/system-evaluate-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
