### ISSUE TITLE
Bad Example in Documentation

### ISSUE THREAD

**Issue by simpson123** [MicrosoftDocs/dynamics365smb-devitpro-pb#31]
The example TryFunction calls CODEUNIT.RUN(CODEUNIT::"Purch.-Post") - this is an example of what NOT to do with a TryFunction - it would fail by default as it does Write, and if the service was set to allow writes it would trash the ledgers if not rolled back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a572bd-8d8f-37c6-86e7-ba74ce61e93e
* Version Independent ID: 405f936b-7b89-c5d8-d9e0-76d201354f55
* Content: [Handling Errors by Using Try Functions - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/handling-errors-by-using-try-functions)
* Content Source: [dynamics-nav/Handling-Errors-by-Using-Try-Functions.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Handling-Errors-by-Using-Try-Functions.md)
* Service: **unspecified**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for feedback!

The article has been updated new example of how the try function works. The update will be published soon.
