### ISSUE TITLE
Gets or sets the value of this field.

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#310]
Is Value() "gets or sets the value of this field, why do we need to have a method SetValue()? If there is a difference, please explain. If not, let's get rid of SetValue().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5796590-61d2-9414-8beb-379a297b57e1
* Version Independent ID: 6cebe98e-589f-bc8e-a8db-a317cc2eed6c
* Content: [Value Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testfield/testfield-value-method)
* Content Source: [dev-itpro/developer/methods-auto/testfield/testfield-value-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/testfield/testfield-value-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by lvanvugt** [comment]
Hi Susanne, please read my feedback carefully. It's saying: please explain. So this documentation feedback.

**Comment by lvanvugt** [comment]
Thanx

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, we know that we have yet to describe testing in our AL docset, this is on our backlog and will be available with a future refresh. Closing this issue for now. Thanks.
