### ISSUE TITLE
Remark about Default Value is missing

### ISSUE THREAD

**Issue by TCI-Radek** [MicrosoftDocs/dynamics365smb-devitpro-pb#3100]
In older version of this page:
https://learn.microsoft.com/en-us/dynamics-nav/eventsubscriberinstance-property
It is clearly said that 'Static-Automatic' is a default value of this property.
This information is no longer part of the documentation.
Is anything changed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbfabd4b-c71c-8c33-8ae0-57c1f75ba62b
* Version Independent ID: 905eeb0c-ceca-ff11-3468-95d399e06ff4
* Content: [EventSubscriberInstance Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-eventsubscriberinstance-property)
* Content Source: [dev-itpro/developer/properties/devenv-eventsubscriberinstance-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-eventsubscriberinstance-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The default value is StaticAutomatic, we'll add that to the article with the next doc refresh. Thanks.
