### ISSUE TITLE
Typo: Output instead of Outstream?

### ISSUE THREAD

**Issue by DominicMatheis** [MicrosoftDocs/dynamics365smb-devitpro-pb#3108]
[Enter feedback here]
`    procedure SaveRichText(RichText: Text)
    var
        OutStream: OutStream;
    begin
        Rec.RichTextBlob.CreateOutStream(OutStream);
        Output.WriteText(RichText);
        Rec.Modify();
    end;`

You write `Output`. But it does not exist. Did you mean `OutStream`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3656c45-e2c8-3c64-d518-cbd781e9a279
* Version Independent ID: e3656c45-e2c8-3c64-d518-cbd781e9a279
* Content: [Rich Text and content controls - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-richtext-content-controls)
* Content Source: [dev-itpro/developer/devenv-richtext-content-controls.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-richtext-content-controls.md)
* Service: **dynamics365-business-central**
* GitHub Login: @EmilDamsbo
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Yes, thanks for catching this. Will be fixed with the next doc refresh.
