### ISSUE TITLE
Sets a value for a field on a test page

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#311]
Method Value() "gets or sets the value of this field, why do we need to have a method SetValue()? If there is a difference, please explain. If not, let's get rid of SetValue().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f13ea4e-fc45-8ef2-fed6-dbc732397a43
* Version Independent ID: 0b0e1914-b350-5338-5c14-7d2a48b161c8
* Content: [SetValue Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testfield/testfield-setvalue-method)
* Content Source: [dev-itpro/developer/methods-auto/testfield/testfield-setvalue-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/testfield/testfield-setvalue-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by lvanvugt** [comment]
Hi Susanne, please read my feedback carefully. It's saying: please explain. So this documentation feedback.

**Comment by lvanvugt** [comment]
Thanx

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, we know that we have yet to describe testing in our AL docset, this is on our backlog and will be available with a future refresh. Closing this issue for now. Thanks.
