### ISSUE TITLE
Isabel Go or Isabel Connect? 

### ISSUE THREAD

**Issue by de7erv** [MicrosoftDocs/dynamics365smb-devitpro-pb#3112]
Dear,

Can you please specify the type of application from Isabel? 
Is this about Isabel Go? Because Isabel Connect (API) had no issues as far as I know.

thank you!

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8e4ba8c-335d-bc87-2cc1-7591a0456f61
* Version Independent ID: 7f72d2ee-26a6-c644-274e-f68630315e89
* Content: [Belgian Features that are Moved, Removed, or Replaced - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-features-be)
* Content Source: [dev-itpro/upgrade/deprecated-features-be.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/deprecated-features-be.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by v-nithyamut** [comment]
Thanks for the feedback.

We removed ISABEL integration. As we mentioned in the text, Microsoft partners can provide their solutions for that. So, APIs are not part of that.
