### ISSUE TITLE
Wrong remark section

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#3115]
The remarks of this page is self-referencing.

It says:
_The inserted record **will automatically get assigned a SystemId by the platform**._ And then there is a link to the page itself.

It should be more relevant to get this remark on this page: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-insert-boolean-method

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72996fc4-f0a3-3f7a-85cd-72f566b9cc6a
* Version Independent ID: 0ee88fde-3bd8-c768-3286-8f2a54e569ed
* Content: [Record.Insert(Boolean, Boolean) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-insert-boolean-boolean-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-insert-boolean-boolean-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/record/record-insert-boolean-boolean-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
