### ISSUE TITLE
Create sales order example incorrect

### ISSUE THREAD

**Issue by egbertwietses** [MicrosoftDocs/dynamics365smb-devitpro-pb#312]
Field paymentTerms doesn't work in way described. 
Set through paymentTermsId instead of code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1efa25d6-38ee-22f0-c1d8-0abdbabd4014
* Version Independent ID: 9874b833-a409-5fc2-3add-79966dd508f5
* Content: [Create salesOrders - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_create_salesorder)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_create_salesorder.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_create_salesorder.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Yes, this is an error - we will fix this - this must be set using paymentTermsId for it to work. The topics will be updated with the next refresh.
