### ISSUE TITLE
New option 'Development' for -Mode

### ISSUE THREAD

**Issue by Kowa63** [MicrosoftDocs/dynamics365smb-devitpro-pb#313]
The current versions of the cmdlet also have the new option 'Development' to offer for the -Mode switch. This is an undocumented feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63757c26-d60b-bb54-e570-f1db6af051b5
* Version Independent ID: 5fdebecd-6373-6472-77bb-c9eb68dd10a2
* Content: [Sync-NAVApp (Microsoft.Dynamics.Nav.Apps.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/sync-navapp?view=dynamicsnav-ps-2018)
* Content Source: [dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md)

**Comment by jswymer** [comment]
Hello, good catch! The 'Developer' mode acts similar to `Add`, except it is intended for use during development. It enables you to sync the same version of an App that is already published, eliminating the need to increase the version number. However, to run this mode, only one version the App can be currently published.

We have updated the online content to include this option. The update will be available soon. I hope this answers any questions you may have. Thanks for the feedback!
