### ISSUE TITLE
Possible typo: "We grand indirect Read on the method [...]" should probably read "We grant indirect Read on the method [...]"

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#3138]
"We grand indirect Read on the method [...]" should probably read "We grant indirect Read on the method [...]"
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44501aeb-bc5c-99db-5a5d-f40c8c722798
* Version Independent ID: 44501aeb-bc5c-99db-5a5d-f40c8c722798
* Content: [Inherent Permissions - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inherent-permissions)
* Content Source: [dev-itpro/developer/devenv-inherent-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-inherent-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks! We've made the fix.
