### ISSUE TITLE
Note under task 2 should be under task 1

### ISSUE THREAD

**Issue by lucacostamagnaeos** [MicrosoftDocs/dynamics365smb-devitpro-pb#314]
I think that the "Note" box under the section "Task 2: Preparing the Old Database" should be under the section "Task 1: Preparation".

The text is "Do not perform this task if you are converting the database from one cumulative update of Business Central to the next cumulative update. In this case, you only have to complete task 2." so I think it is placed in the wrong section.

Best Regards,
Luca Costamagna

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22706006-56fc-3aa4-b2dd-03c206f38e07
* Version Independent ID: c089fffa-080b-8c5e-8cba-61053c2c93b6
* Content: [Converting a Database to Dynamics 365 Business Central - Technical Upgrade - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/converting-a-database#task-2-preparing-the-old-database)
* Content Source: [dev-itpro/upgrade/Converting-a-Database.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Converting-a-Database.md)
* Service: **dynamics365-business-central**
* Product: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and the update will be published soon.
