### ISSUE TITLE
Link "Working with API Rate Limits" redirects to the very same page from which it is called

### ISSUE THREAD

**Issue by phenno1** [MicrosoftDocs/dynamics365smb-devitpro-pb#3142]
On Operational Limits for Business Central Online there is a link in bottom of the document stating "Operational Limits for Business Central Online" which points to https://learn.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/dynamics-rate-limits,  but effectively it redirects to the very same document "Operational Limits for Business Central Online".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fc3b614-8a3a-0858-80e2-781b1b6e1253
* Version Independent ID: eabcadf6-051e-6631-f5d6-16ccdcef62a7
* Content: [Operation Limits in Dynamics 365 Business Central - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/operational-limits-online)
* Content Source: [dev-itpro/administration/operational-limits-online.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/operational-limits-online.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the link and the update will be published soon.
