### ISSUE TITLE
No info on API page

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/dynamics365smb-devitpro-pb#315]
There's very little information about making API pages. There are however hints throughout the documentation like on the following page: 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object
"The API page type should not be extended by creating a page extension object. Instead, create a new API by adding a page object."

There's little to no information on how to do this in a correct manner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0035ebd9-2a88-4293-83c4-30b3ee5a69ea
* Version Independent ID: f8716731-3439-dfdb-0bef-489aa515a7dc
* Content: [Page Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-object)
* Content Source: [dev-itpro/developer/devenv-page-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We're lacking some information here, I have one topic in progress that you can take a look at [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-pagetype). And as you note, pages of the API type can only be created as new page objects, not extensions of objects. Thanks.

**Comment by Mr-Pingu** [comment]
Thanks for your reply. I will give it another try. 
There should be somewhere mentioned that one need to have an ID field with GUID:

`
table 50100 "TableForAPI"
{
    DataClassification = ToBeclassified

    fields
    { 
        field(10; Id; Guid)
        {

        }
        field(20; key; Code[20])
        {

        }
    keys
    {
        key(PK; "key")
        {
            Clustered = true;
        }
    }
}
    trigger OnInsert()
    begin
        Id := CreateGuid();
    end;
    
}
`

**Comment by Mr-Pingu** [comment]
Succes! Made a custom API page and Extended the Item one

I think there should be an how to page to make an custom api and there should be some kind of endpoint notation in the following way.


Sandbox tenant
<tenant-id>/sandbox/api/<API-Publisher>/<APIGroup>/<APIVersion>/companies(<companyid>)/<entitySetNames>  
 
Direct Tenant
<tenant-id>/api/<API-Publisher>/<APIGroup>/<APIVersion>/companies(<companyid>)/entitySetNames> 
 
Production
/api/<API-Publisher>/<APIGroup>/<APIVersion>/companies(<companyid>)/<entitySetNames>


Also what's the best way to extend an existing API? If I want to expose more item fields to the API but that leaves me with a different endpoint than the "default" API or do I have to copy all fields to the custom API page too? That's a bit tedious to define all the default fields again...



**Example for ItemExtension API**

1. First Extend the ItemTable with a new field
```
tableextension 50137 ItemTableEx extends Item //MyTargetTableId
{
    fields
    {
        field(50138; "Long name"; TEXT[250])
        {
            Caption = 'LongName';
            DataClassification = ToBeClassified;
        }
    }
}
```

2. Then re-create the ItemAPI with API-page 

page 50138 ItemExt
{
    PageType = API;
    Caption = 'ItemsExt';
    APIPublisher = 'contoso';
    APIGroup = 'api';
    APIVersion = 'v2.0';
    EntityName = 'item';
    EntitySetName = 'items';
    SourceTable = Item;
    DelayedInsert = true;

    layout
    {
        area(Content)
        {
            repeater(GroupName)
            {
                field(Id; Id)
                {
                    Caption = 'Id';

                }
                field("Longname"; "Long name")
                {
                    Caption = 'longname';
                }
            }
        }
    }
}
3. Publish the App
4. Check out the request:

For sandbox
GET https://api.businesscentral.dynamics.com/v1.0/<tenant-id>/sandbox/api/contoso/api/v2.0/companies(<company id>)/items

For direct-tenant
GET https://api.businesscentral.dynamics.com/v1.0/<tenant-id>/api/contoso/api/v2.0/companies(<company id>)/items

For production
GET https://api.businesscentral.dynamics.com/v1.0/api/contoso/api/v2.0/companies(<company id>)/items

5. Happy JSON respones


**Example for new table**
1. Create new table


```
table 50135 ApiTable
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "Key"; Code[20])
        {
            DataClassification = ToBeClassified;
            Caption = 'key';
        }
        field(4; Id; Guid)
        {

        }
    }

    keys
    {
        key(PK; Key)
        {
            Clustered = true;
        }
    }

    var
        myInt: Integer;

     // On insert create GUID -- IMPORTANT, an GUID is mandatory to create an API (see https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md)
    trigger OnInsert()
    begin
        Id := CreateGuid();
    end;


    trigger OnModify()
    begin

    end;

    trigger OnDelete()
    begin

    end;

    trigger OnRename()
    begin

    end;

}

```



```
page 50137 apiAPI
{
    PageType = API;
    Caption = 'APIPage';
    APIPublisher = 'contoso';
    APIGroup = 'app1';
    APIVersion = 'v2.0';
    EntityName = 'api';
    EntitySetName = 'apis';
    SourceTable = ApiTable;
    DelayedInsert = true;
    ODataKeyFields = Id;

    layout
    {
        area(Content)
        {
            repeater(GroupName)
            {
                field(Id; Id)
                {
                    Caption = 'ID';
                    ApplicationArea = All;
                }
                field(key; key)
                {
                    Caption = 'key';
                    ApplicationArea = All;
                }
            }
        }
    }
}

```

**Comment by SusanneWindfeldPedersen** [comment]
This is great, very nice. Thanks!

**Comment by Mr-Pingu** [comment]
> 
> 
> This is great, very nice. Right now our recommendation is to copy all fields over to the new page to get the same endpoint as you also mention. Thanks again.

This however doesn't work for the "item entity" and/or "sales order entity" because it incorporates many graph functions that can't be used in an extension context. Please tell me how am I supposed to expose other fields on the Item or Sales Order page / entity?

**Comment by tomasvanrijsse** [comment]
@SusanneWindfeldPedersen please reopen as question above isn't answered clear.

**Comment by Mr-Pingu** [comment]
@SusanneWindfeldPedersen Can you look this up?

**Comment by Mr-Pingu** [comment]
@SusanneWindfeldPedersen Please?
