### ISSUE TITLE
FormatNumber is missing in syntax definition

### ISSUE THREAD

**Issue by yurim108** [MicrosoftDocs/dynamics365smb-devitpro-pb#3169]
Usage of parameter "FormatNumber" is described in remarcs, but is missing in syntax definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c745c7fa-6517-541f-d18a-36226db7fb64
* Version Independent ID: f41b2a8c-8545-a5a2-4550-092786b1fde9
* Content: [System.Format(Any, Integer, Text) Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, can you please elaborate? The Syntax section is derived from code, whereas the Remarks are edited manually and can contain much more information.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - the method has been updated with two different signatures and we've included the FormatNumber description in the wrong article, so we'll get that fixed. Will be ready with the next doc refresh. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Should be fixed now, closing
