### ISSUE TITLE
More properties for a field

### ISSUE THREAD

**Issue by SUD-D365** [MicrosoftDocs/dynamics365smb-devitpro-pb#317]
Hi @MS,

It should be more effective a page customization, if we can customize a field for different properties.
Like ShowMandatory, NotBlank, BlankZero.

Because if I want to show *Responsibility Center* field with a Red astrick on Sales Order Page, then I have to extend the standard page for only a single property.
However this field is already placed on that page. So it forces me to create this field with different name on that page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa8872c-562c-dd7b-dfca-316ef2ac20c2
* Version Independent ID: 259f7cd2-e56c-9da6-38cc-884176f1dc93
* Content: [Page Customization Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-customization-object)
* Content Source: [dev-itpro/developer/devenv-page-customization-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-customization-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by Mr-Pingu** [comment]
Can't you use modify for this? Just thinking aloud, didn't test it.

**Comment by SUD-D365** [comment]
No, ShowMandatory is not there in modify on PageExtension.

**Comment by Mr-Pingu** [comment]
Too bad :( You are right...
Seems it isn't supported: https://community.dynamics.com/nav/f/34/t/280875

Would like to know how I can make "Item Discount Group" mandatory so I can enforce that all products have atleast a group assigned...

If you happen to find a way. Please let me know.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This repo is meant for doc only issues, please file any suggestions for product features using the Product feedback mechanism. Thanks.
