### ISSUE TITLE
Datasource + Navigation Pane

### ISSUE THREAD

**Issue by jnpatrouillault** [MicrosoftDocs/dynamics365smb-devitpro-pb#3179]
hello

I have to questions :

1.
I would like to know what is the data source of the "Vendor Payment" API because this API returns to me no record.
It's neither linked to "vendor ledger entries" nor to an apply process.

2.
In the navigation pane of this article, we can see customer information instead of vendor information !

customerPaymentJournal | customerPaymentJournal | Gets the customerpaymentjournal of the vendorPayment.

Can you update this article, please ?
Thank you for your 2 answers
best regards

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 63aabc5f-a0c1-1ed8-1244-9d2fa5c464da
* Version Independent ID: fbfca44e-9de9-7ba8-e086-a9f0a88c7b6e
* Content: [vendorPayment resource type - Business Central](https://learn.microsoft.com/fr-fr/dynamics365/business-central/dev-itpro/api-reference/v2.0/resources/dynamics_vendorpayment)
* Content Source: [dev-itpro/api-reference/v2.0/resources/dynamics_vendorPayment.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v2.0/resources/dynamics_vendorPayment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We'll get that fixed. The data source of the Vendor Payment API is the Gen. Journal Line table. 
The article will be refreshed with the next push to live. thanks.
