### ISSUE TITLE
Question possibility to create salesOrder with lines in one request?

### ISSUE THREAD

**Issue by egbertwietses** [MicrosoftDocs/dynamics365smb-devitpro-pb#318]
If this is possible I would love to see some documentation on it, also if it is possible to set shippingAddress.
As for all e-commerce systems there is always an invoice and shipping address but I only see invoice now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab8727c9-7b8e-2c83-680f-7f5c8a4ec22c
* Version Independent ID: dc43f5e7-d5d9-48e7-b74d-460b5a70150e
* Content: [Create salesOrderLines - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_create_salesorderline)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_create_salesorderline.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_create_salesorderline.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by anbelim** [comment]
You will need to add salesOrderLines to a request body to create a salesOrder with lines in one request.
Content-type: application/json
POST /api/beta/companies({companyId})/salesOrders
Content-type: application/json
{
  "customerId":"{customerId}",
  "salesOrderLines": [
    {
      "quantity":  1,
      "itemId":"{itemId}"
    }
  ]
}

Shipping address on sales orders was added in API v1.0. This field is missing in API version beta. You can see all the fields for salesOrder in the $metadata.
POST /api/v1.0/companies({companyId})/salesOrders
Content-type: application/json
{
  "customerId":"{customerId}",
  "shippingPostalAddress": {
    "countryLetterCode":"US",
    "postalCode":"1",
    "city":"A",
    "state":"B",
    "street":"C"
  }
}
