### ISSUE TITLE
Possible error situations

### ISSUE THREAD

**Issue by pmichelsen** [MicrosoftDocs/dynamics365smb-devitpro-pb#319]
It would be helpful if there was a section specifying the possible errors that may be triggered using this function. 
Which error is thrown if the user does not have permission to write to the filename placement? What if there is a file with the same name? Etc.
If the possibilities are generic, i.e. the same for several funcions, you could make a generic section and crossref.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdda23ef-73dc-5521-d5c0-5896d1a672ea
* Version Independent ID: a7c5d648-e321-e91c-c6d0-4eb3bc107eab
* Content: [SAVEASPDF Function (Report) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/saveaspdf-function--report-)
* Content Source: [dynamics-nav/SAVEASPDF-Function--Report-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SAVEASPDF-Function--Report-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for your feedback. We have added this issue to our work backlog.
