### ISSUE TITLE
Guess it should read TDE

### ISSUE THREAD

**Issue by mortenseifert** [MicrosoftDocs/dynamics365smb-devitpro-pb#32]
files to protect data at rest. **TDC** can assist in the ability to comply with many laws, regulations, and guidelines established in various industries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c03613c-ac0a-29a4-7203-1a9243333fae
* Version Independent ID: e2042d10-140b-91a9-bd5a-e82ca5a9fd8c
* Content: [Transparent Data Encryption (TDE) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/transparent-data-encryption)
* Content Source: [dynamics-nav/transparent-data-encryption.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/transparent-data-encryption.md)
* Service: **unspecified**
* GitHub Login: @jswymer
* Microsoft Alias: **kepontop**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for reporting this typo - it has been fixed and will be pushed live with our next refresh. Thanks again!
