### ISSUE TITLE
Will SynchronizeSchemaChanges=force Sync only changed Objects?

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-devitpro-pb#320]
If I run Import-NAVApplicationObject with SynchronizeSchemaChanges = force will the schema sync run for the importet objects only or will all object be synchronized like in sync-navtenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0808529-30f6-b37d-d31b-c6ec292e3724
* Version Independent ID: 0ff726d4-282b-8ba9-530d-3fb1270fc45c
* Content: [Import-NAVApplicationObject (Microsoft.Dynamics.Nav.Ide)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.ide/import-navapplicationobject?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Ide/Import-NAVApplicationObject.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Ide/Import-NAVApplicationObject.md)

**Comment by jswymer** [comment]
Hello, when you run the cmdlet with  SynchronizeSchemaChanges = force or SynchronizeSchemaChanges = Yes, the synch will be run against all objects, similar to sync-navtenant as you state. I have added some more info to the article, and an update will be published soon. Thanks for the feedback!
