### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by rcfoyn** [MicrosoftDocs/dynamics365smb-devitpro-pb#3200]
The following Note ...

> The system permission sets and user groups called D365 AUTOMATION and **EXTEND. MGT. - ADMIN** provide access to most typical objects used with automation.
> 
> The **EXTEND. MGT. - ADMIN** permission set was introduced in Business Central 2021 release wave 1 as a replacement for the D365 EXTENSION MGT permission set in earlier versions.

Should be corrected as follows:

> The system permission sets and user groups called D365 AUTOMATION and **D365 EXTENSION MGT** provide access to most typical objects used with automation.
> 
> The **EXTEN. MGT. - ADMIN** permission set was introduced in Business Central 2021 release wave 1 as a replacement for the D365 EXTENSION MGT permission set in earlier versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1555e693-76e8-b1d9-267f-bf06f068c9f4
* Version Independent ID: 725078be-b4d2-ced1-1ce0-52fc379f6a4e
* Content: [Using Service to Service Authentication - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/automation-apis-using-s2s-authentication)
* Content Source: [dev-itpro/administration/automation-apis-using-s2s-authentication.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/automation-apis-using-s2s-authentication.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We document the newest version, so the article reflects version 2023 and the system permission set name is correct. Thanks.

**Comment by rcfoyn** [comment]
I beg to differ and kindly ask that you reconsider. I have based my feedback on the latest version.

Besides being wrong, the first sentence is badly worded:

> "The system permission sets and user groups called D365 AUTOMATION and EXTEN**D**. MGT. - ADMIN [...]"

The only logical way to read this is that there are both _two permissions sets_ **and** _two user groups_ named like that. I find that to be false information.

Here are my findings with regard to **user groups**:
- D365 AUTOMATION
- D365 EXTENSION MGT

Here are my findings with regard to **permission sets**:
- D365 AUTOMATION
- D365 EXTENSION MGT (Obsolete!)
- EXTEN. MGT. - ADMIN

Thus, the second sentence in question has a typo, as I already pointed out:
- Wrong: "EXTEN**D**. MGT. - ADMIN"
- Correct: "EXTEN. MGT. - ADMIN"

I trust that this has convinced you to rewrite and correct the text in question.
