### ISSUE TITLE
Magic ProfileDescription

### ISSUE THREAD

**Issue by achim-t** [MicrosoftDocs/dynamics365smb-devitpro-pb#3204]
It should be mentioned somewhere, that if you set the Profile Description to 'Navigation menu only.' then the profile is excluded from the page Available Roles, where the user can select his role.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad56e752-ba1d-fb3a-8ea4-4d7e3a780235
* Version Independent ID: c5dcb9d8-8c4e-7952-15f7-82564319d67c
* Content: [ProfileDescription Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-profiledescription-property)
* Content Source: [dev-itpro/developer/properties/devenv-profiledescription-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-profiledescription-property.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by pri-kise** [comment]
I've created an idea to improve the current situation with this dirty workaround.
https://experience.dynamics.com/ideas/idea/?ideaid=f29d01e9-7467-ee11-a81c-00224854d651

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. At this point, we won't document that behavior. The idea has multiple votes at this point, thanks for creating that.
