### ISSUE TITLE
"GetApproval: Check whether a document is approved or rejected." section seems to be double on the page

### ISSUE THREAD

**Issue by cghasvi** [MicrosoftDocs/dynamics365smb-devitpro-pb#3207]
"GetApproval: Check whether a document is approved or rejected." section seems to be double on the page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b7e6073-17cb-93bf-8822-98cc399fd147
* Version Independent ID: 6b7e6073-17cb-93bf-8822-98cc399fd147
* Content: [Extending e-documents functionality - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extend-edocuments)
* Content Source: [dev-itpro/developer/devenv-extend-edocuments.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-extend-edocuments.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @altotovi
* Microsoft Alias: **altotovi**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
