### ISSUE TITLE
Delegated admins can now use a workflow to request the start of job queues

### ISSUE THREAD

**Issue by dannoe** [MicrosoftDocs/dynamics365smb-devitpro-pb#3219]
[https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/delegated-admin#restricted-access-to-business-central-as-delegated-administrator](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/delegated-admin#restricted-access-to-business-central-as-delegated-administrator)

There should be a note about this [new feature](https://learn.microsoft.com/en-us/dynamics365/release-plan/2023wave1/smb/dynamics365-business-central/delegated-admins-job-queue-entries-are-run-user) in this bullet point:
- Run scheduled tasks in the job queue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66412cff-bccf-0553-ad97-7bb9ea6c63a9
* Version Independent ID: 6d046b65-1832-bf77-6eec-3d8350f4d83e
* Content: [Delegated admin access to Business Central online - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/delegated-admin)
* Content Source: [dev-itpro/administration/delegated-admin.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/delegated-admin.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've made an update to the articles, which will be available soon.
