### ISSUE TITLE
Extension of API-page

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/dynamics365smb-devitpro-pb#322]
The page does say I shouldn't extend an API page, why?
"The API page type should not be extended by creating a page extension object. Instead, create a new API by adding a page object."

I could easily extend the API-page "Customer Entity" with the following code:

```
pageextension 50136 CustomerAPIext extends "Customer Entity"
{
    layout
    {
        addafter(shipmentMethodId)
        {
            field("CustomerDiscGroup"; "Customer Disc. Group")
            {

            }
        }
    }
}
```

When I try to to request the api url like specified in the documentation, the field is available for acces.
```
{
    "@odata.context": "https://api.businesscentral.dynamics.com/v1.0/<Tenant-ID>/sandbox/api/beta/$metadata#companies(<Company-id>)/customers/$entity",
    "@odata.etag": "W/\"JzQ0O2RIRUVHMHFPWUEyQ0VSOUdyQzNjaUNlcEpXbUpSN3o4Q0QySmE2VnVId1U9MTswMDsn\"",
    "id": "ee09031b-fdba-4b29-8500-031b5777ab98",
    "number": "0001",
    "displayName": "Name Name",
    "type": "Company",
    "phoneNumber": "0",
    "email": "",
    "website": "",
    "taxLiable": false,
    "taxAreaId": "00000000-0000-0000-0000-000000000000",
    "taxAreaDisplayName": "",
    "taxRegistrationNumber": "",
    "currencyId": "00000000-0000-0000-0000-000000000000",
    "currencyCode": "EUR",
    "paymentTermsId": "00000000-0000-0000-0000-000000000000",
    "shipmentMethodId": "00000000-0000-0000-0000-000000000000",
    "CustomerDiscGroup": "",
    "paymentMethodId": "00000000-0000-0000-0000-000000000000",
    "blocked": " ",
    "balance": 0,
    "overdueAmount": 0,
    "totalSalesExcludingTax": 0,
    "lastModifiedDateTime": "2019-01-09T14:30:22.47Z",
    "address": {
        "street": "",
        "city": "",
        "state": "",
        "countryLetterCode": "",
        "postalCode": ""
    }
}
```
So why is this important?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdda7e30-30d9-ac83-abf7-267a7f634c6d
* Version Independent ID: 5bf5ce87-f59a-d2ae-10b3-05eda02406b5
* Content: [Page Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)
* Content Source: [dev-itpro/developer/devenv-page-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, yes this can currently be done, but we will most likely implement a compiler check to prevent this. The reason for preventing this is that we want to offer a standard contract that should be reliable and not extended. Thanks.
