### ISSUE TITLE
typo in one link

### ISSUE THREAD

**Issue by EidurMar** [MicrosoftDocs/dynamics365smb-devitpro-pb#3220]
just a typo in one of the links.. missing a 'v'
POST https://api.businesscentral.dynamics.com/v2.0/{environment name}/api/microsoft/automation/2.0/companies({companyId})/extensions({packageId})/Microsoft.NAV.install

the ../2.0/companies.. which should be ../v2.0/companies..
just anoying if you happen to copy/paste this one to try out :)

br,
Eidur

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 036fbaa0-3f6b-e4f7-cd1e-c35b37cdee6e
* Version Independent ID: 9efb41bd-bad8-597f-08e8-2b3c7e05f8e9
* Content: [Introduction to automation APIs - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/itpro-introduction-to-automation-apis)
* Content Source: [dev-itpro/administration/itpro-introduction-to-automation-apis.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/itpro-introduction-to-automation-apis.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the article and the update will go live soon.
