### ISSUE TITLE
Precise where to find the "permission value syntax"

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#3222]
The page mentions that the argument Permissions must follow the "permission value" syntax.
But there is no link to this syntax, even in the "See Also" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f646edb3-e528-2914-1315-8d717778ecf0
* Version Independent ID: f646edb3-e528-2914-1315-8d717778ecf0
* Content: [InherentPermissions Attribute - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-inherentpermissions-attribute)
* Content Source: [dev-itpro/developer/attributes/devenv-inherentpermissions-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/attributes/devenv-inherentpermissions-attribute.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback. The permission value syntax can be found in the here: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-permissions-property#values.

We've updated the article with a link. The update will be available soon.
