### ISSUE TITLE
Wrong parameter types

### ISSUE THREAD

**Issue by Gabain1993** [MicrosoftDocs/dynamics365smb-devitpro-pb#324]
The title says the function uses Code and text, despite it being integer and text
The parameter description correctly identifies the first parameter as an integer but says the second is an option, it actually is text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a7b774-52a0-3dfc-8082-101f0c573f90
* Version Independent ID: ba5fc698-f2e5-f1a7-c4b5-61464a0f347f
* Content: [SELECTSTR Function (Code, Text) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/selectstr-function--code--text-)
* Content Source: [dynamics-nav/SELECTSTR-Function--Code--Text-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SELECTSTR-Function--Code--Text-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Yes, this topic is not up-to-date. You can, however, see the newest version of this topic [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/text/text-selectstr-method). Thanks.
