### ISSUE TITLE
Assignable - default value

### ISSUE THREAD

**Issue by stephanweidmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#3254]
Please set the default value. is it true or false?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b056e1ed-6893-0ab2-0836-abaa91533416
* Version Independent ID: e3f268e3-1b6f-c68f-8ec0-fb69b9566d2b
* Content: [Assignable Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-assignable-property?wt.mc_id=d365bc_inproduct_alextension)
* Content Source: [dev-itpro/developer/properties/devenv-assignable-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-assignable-property.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback, the default value is false. We'll get the article updated with the next doc refresh.
