### ISSUE TITLE
Misleading information about extensible properties

### ISSUE THREAD

**Issue by mberlickas** [MicrosoftDocs/dynamics365smb-devitpro-pb#3262]
Hi, in this article of extensible properties it is written that Editable and Enabled property can't be extended (in Extensible column there is no 'True'), however at least on Page Field I can set Editable and Enabled properties, also this change can be published and works in web client. Also editable property can be set on PageExt itself and works, I'm not sure about other components. Can you adjust this article information?
![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/116627568/d9388eec-3227-49f2-9c3e-5ee571e65a7c)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2612295b-ecb2-93f1-2097-c5e055ed5123
* Version Independent ID: ec810858-2ada-8915-c110-7634c6b791b4
* Content: [Page, Page Fields, and Page Extension Properties - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-property-overview)
* Content Source: [dev-itpro/developer/properties/devenv-page-property-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-page-property-overview.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The article that you're pointing to is auto-generated and reflects the source code of the platform, so it should be correct. We've been through the source code to validate and it looks like these properties can't be extended. I can see that we made a change with runtime 12 "Added support for setting the [Editable](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/properties/devenv-editable-property) property of page fields to false from page customizations.".

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
