### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by dennisroczek** [MicrosoftDocs/dynamics365smb-devitpro-pb#327]
There are two optional parameters (wait and versioncheck) - what do they do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb2c36d-7aa4-ebda-3326-7f06ac5dc379
* Version Independent ID: 812861e0-fd9e-b73f-242e-3aba23f30626
* Content: [LOCKTABLE Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/locktable-function--record-)
* Content Source: [dynamics-nav/LOCKTABLE-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/LOCKTABLE-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question - please try this newer version of the topic instead [LockTable Method](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-locktable-method). Thanks.
