### ISSUE TITLE
User Personalization has been renamed to User Settings

### ISSUE THREAD

**Issue by aries-ts-indo** [MicrosoftDocs/dynamics365smb-devitpro-pb#3270]
User Personalization has been renamed to User Settings

https://learn.microsoft.com/en-us/dynamics365/business-central/admin-manage-user-settings-preferences

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0daae815-b465-962a-554f-8c74bf6b2a7d
* Version Independent ID: 116fb81a-0bbb-16fe-5f03-1f84db7e2a73
* Content: [Assign a User to a Profile - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-assign-user-profile)
* Content Source: [dev-itpro/developer/devenv-assign-user-profile.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-assign-user-profile.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, this will be fixed with the next doc refresh.
