### ISSUE TITLE
Wrong Trigger Name

### ISSUE THREAD

**Issue by iAbdulhamid** [MicrosoftDocs/dynamics365smb-devitpro-pb#3277]
In Remarks section, the name of the trigger was written as OnBeforeRename instead of OnAfterRename.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51f34f9f-211d-f322-00b9-e71e38d24bfa
* Version Independent ID: 21d93328-24b2-6a3f-1f33-a953251c84b2
* Content: [OnAfterRename (Table Extension) Trigger - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/tableextension/devenv-onafterrename-tableextension-trigger)
* Content Source: [dev-itpro/developer/triggers-auto/tableextension/devenv-onafterrename-tableextension-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/triggers-auto/tableextension/devenv-onafterrename-tableextension-trigger.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, will be fixed with the next doc refresh.
