### ISSUE TITLE
Valid properties for Page Extensions

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#328]
Can you please inform what the X in the Page Extension column is supposed to mean?
I.e. if I add an action to a page through an extension, can I or can't I use the StyleExpr property? Does the same apply to field controls I add (from a table extension) as to existing field controls on the base page?
Another example: what's different about Editable and Enabled here? (on has an X, the other doesn't).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2612295b-ecb2-93f1-2097-c5e055ed5123
* Version Independent ID: ec810858-2ada-8915-c110-7634c6b791b4
* Content: [Page and Page Extension Properties Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-property-overview)
* Content Source: [dev-itpro/developer/properties/devenv-page-property-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-page-property-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your question. The X means that a certain property applies to Page Extension objects as well as Page objects. I have added some clarification in the topic. Editable and Enabled are two different properties, here are the descriptions: [Enabled](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-enabled-property) and [Editable](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-editable-property). One can be set on page extension objects, the other one cannot.

**Comment by SusanneWindfeldPedersen** [comment]
Will close this issue.
