### ISSUE TITLE
Method names

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#3284]
Under Remarks, the following methods are mentioned:

>  Dialog.Open, Dialog.Update, Window.Open, Window.Update

`Window` is the name developers use (by convention) for Dialog variables, but I don't think `Window` is data type in AL like `Dialog` is. It would make more sense if the sentence read something like:

> Dialog.Open, Dialog.Update, Dialog.Close, System.Confirm, System.StrMenu or System.Error

P.S.: It's one my pet peeves that Dialog.Open should fail in a "headless" (GUI-less) context. In my view, the platform should silently deal with that situation without me having to "pollute" my application code with calls to GuiAllowed(). But that's just me, eh? ;-) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe50572-4213-2b90-5d8c-1c89f439befb
* Version Independent ID: cdecb5a5-93d0-1e65-697a-54c02e95ce2c
* Content: [System.GuiAllowed() Method - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-guiallowed-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-guiallowed-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/system/system-guiallowed-method.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, will be fixed with the next doc refresh.
