### ISSUE TITLE
InDataSet property is not required anymore

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#3288]
The InDataSet property is mentioned as required when the attribute is now deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bb3892e-efef-e88c-e188-6dc5b5bd37f0
* Version Independent ID: fb2b94f2-82d8-ea9c-dbd4-dcf6d86210e5
* Content: [StyleExpr Property - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-styleexpr-property?wt.mc_id=d365bc_inproduct_alextension)
* Content Source: [dev-itpro/developer/properties/devenv-styleexpr-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/properties/devenv-styleexpr-property.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
