### ISSUE TITLE
Limitations of Page Extension Objects

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#329]
Can you please provide content on what you cannot do through Page Extension Objects?
My concern is both as to which properties can be modified for existing controls (and which not), as well as assigned to new controls.
Also, the first phrase on this link indicates that you can add or override page functionality but it's not very clear how to achive this. Please note I'm not referring to layout in this context, but subscribing to triggers, adding functions, etc.
2 practical examples:
- Customer wants to change the Style on "Lot No. Information List": if a lot is blocked, certain fields should change to 'unfavorable'. Can this be achieved through an extension, or must the page be substituted with a new page object? 
- New fields are added to Item Tracking (T336, T337, etc.). Of course they should only be editable on Inbound Entries (basically following the same principle as Expiration Date) on Page 6510. How should this be done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdda7e30-30d9-ac83-abf7-267a7f634c6d
* Version Independent ID: 5bf5ce87-f59a-d2ae-10b3-05eda02406b5
* Content: [Page Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)
* Content Source: [dev-itpro/developer/devenv-page-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by Bleika** [comment]
I've already solved both examples by defining new OnAfterGetRecord and OnOpenPage triggers respectively within my Page Extensions.
I was wary to do so in the first place since I wrongly assumed it was against the rules and the Trigger section of this documentation doesn't address the issue (that is: what happens if you over-write triggers, what is allowed, etc.).
As a dinosaur coming over from C/AL, adapting to Events can be confusing at times (when must you subscribe to a Trigger Event? when is it OK to define your own Trigger?), and a "Where to place code" rules section would be helpful when refactoring old code that modifies standard code (that is: when your not just adding functionality but must really modify existing behavior).

**Comment by Bleika** [comment]
Please - any comments on this?
Let's say you want to catch i.e. OnInit Trigger on PAG6510 or OnFindRecord Trigger on PAG9126?

**Comment by Bleika** [comment]
Please - it's been 2 months already since I opened this thread - any comments?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for the long wait on a reply. There are a number of questions in this issue, and I am not sure that I am giving you a fulfilling reply, but I can try to address some of the issues. At the moment, we do not have any guidance or best practice on when to do what. After the October´19 release, we might be able to provide some based on our experiences. For what's allowed and what is not allowed, IntelliSense and the compiler should be able to give you guidance. Specifically, for the . OnInit Trigger on PAG6510 or OnFindRecord Trigger on PAG9126, these two triggers are not available on page extensions. Objects related to item tracking are not extensible at the moment and would need a big redesign in the product. I hope this helps. Thanks.
