### ISSUE TITLE
Key corresponding to a non existing field

### ISSUE THREAD

**Issue by sadjad1** [MicrosoftDocs/dynamics365smb-devitpro-pb#3292]
[Enter feedback here]
The Keye "key(PK; ID)" is corresponding to a field that does not exists in the dataset. I think the field ID should be added to the table.
![image](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/assets/15630953/f55eecec-2698-435f-8451-dd7791382f86)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3aec94cf-bafc-f64b-fded-9f831bbe6750
* Version Independent ID: 3aec94cf-bafc-f64b-fded-9f831bbe6750
* Content: [Migrating from SIFT to Nonclustered Columnstore Indexes (NCCIs) - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrating-from-sift-to-ncci)
* Content Source: [dev-itpro/developer/devenv-migrating-from-sift-to-ncci.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-migrating-from-sift-to-ncci.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the fix! Very much appreciated. The update will be published soon.
