### ISSUE TITLE
The PromotedActionCategories doesn't seem to work

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [MicrosoftDocs/dynamics365smb-devitpro-pb#33]
I've coded an action, and Promoted it to the "Home" tab on a page.  Nothing seems to work, when it comes to changing the name of the category from "Category6".  I guessing this is a bug in the AL compiler:
pageextension 70094370 "PBSI Time Sheet PE" extends "Time Sheet"
{
    // PromotedActionCategories = 'Manage,Process,Report,Navigate,Lines,PBSI';
    PromotedActionCategories = 'PBSI';
    Caption = 'PBSI';

    actions
    {
        addlast(processing)
        {
            group(PBSI)
            {
                action("Open 24/7 TimeTracker")
                {
                    Caption = 'Open 24/7 TimeTracker';  //I should probably change these to "Caption" and "ToolTip".  The ML's have been deprecated...
                    ToolTip='Click to open the 24/7 TimeTracker screen';
                    Image = AdjustEntries;
                    Promoted = True;
                    PromotedCategory = Category6;
                    PromotedIsBig = True;
                    ApplicationArea = all;

Per my understanding, "PromotedActionCategories" should have taken care of changing the name of "Category6" to "PBSI".  I tried the "Caption" property right below the "PromotedActionCategories" just to see if that would do the trick.  It doesn't generate an error, but it doesn't fix the problem, either.

Am I missing something, or does "PromotedActionCategories" simply not work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2fd2246-25a2-7ac9-62cb-79ef33f911ae
* Version Independent ID: 7dcdfc2c-c67e-cce9-13f3-42a5c0cd6b2c
* Content: [PromotedActionCategoriesML Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-promotedactioncategoriesml-property)
* Content Source: [dev-itpro/developer/properties/devenv-promotedactioncategoriesml-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-promotedactioncategoriesml-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. I've tried out your code - uncommented the first list of PromotedActionCategories and commented out the second. I get the following result: 
![image](https://user-images.githubusercontent.com/12556556/39801946-150c0e9e-536d-11e8-8248-ffe7958d1796.png). The PBSI group shows up (as number 6) under Actions, please see the result in the attached screen shot. Is this not how you want it to display? Thanks, Susanne

**Comment by DaveBoehmPBSI** [comment]
Thanks for responding, Susanne.

Your screen shot looks a lot like either NAV, or the newest version of D365BC.  My sandbox is actually the older version of D365BC.  MS hasn’t yet updated my tenant.

Here is a screen shot of the Time Sheet screen from my sandbox.  It shows the Home tab’s last category on the action ribbon as “Category 6”.  The next screen shot shows the Action Tab, where the Category name displays as “PBSI”:

[cid:image001.jpg@01D3E77E.3D469DD0]

[cid:image002.jpg@01D3E77E.3D469DD0]

--Dave--

David Boehm, CPA
PBSI
www.pbsisoftware.com<http://www.pbsisoftware.com/>
to book an appt.: https://outlook.office365.com/owa/calendar/ProfessionalBusinessSoftwareInc@pbsisoftware.com/bookings/
Office: 817.752.3352 <tel:817.752.3352>
Cell: 214.392.4797<tel:214.392.4797>
***********************************************************
This communication, along with any documents, files or attachments, is intended only for the use of the addressee and may contain legally privileged and confidential information. If you are not the intended recipient, you are hereby notified that any dissemination, distribution or copying of any information contained in or attached to this communication is strictly prohibited. If you have received this message in error, please notify the sender immediately and destroy the original communication and its attachments without reading, printing or saving in any manner. Thank you.

**Comment by SusanneWindfeldPedersen** [comment]
Yes, this is the newest version of Business Central. Unfortunately, I cannot see your screen shots, but if you do get the Category name replaced with PBSI then it should work as intended, right?

**Comment by DaveBoehmPBSI** [comment]
It should, but it doesn’t.

Why can’t you see the screen shots?  If I blow it up to 200% with the magnifier, I can read the code as well as see the image.  Are you simply not receiving the screen shot image?  Do I need to zip the images and resend these?

Thanks,

[cid:image001.jpg@01D3EB5E.1BA72B70]

[cid:image002.jpg@01D3EB5E.4622DF20]
--Dave--

David Boehm, CPA
PBSI
www.pbsisoftware.com<http://www.pbsisoftware.com/>
to book an appt.: https://outlook.office365.com/owa/calendar/ProfessionalBusinessSoftwareInc@pbsisoftware.com/bookings/
Office: 817.752.3352 <tel:817.752.3352>
Cell: 214.392.4797<tel:214.392.4797>
***********************************************************
This communication, along with any documents, files or attachments, is intended only for the use of the addressee and may contain legally privileged and confidential information. If you are not the intended recipient, you are hereby notified that any dissemination, distribution or copying of any information contained in or attached to this communication is strictly prohibited. If you have received this message in error, please notify the sender immediately and destroy the original communication and its attachments without reading, printing or saving in any manner. Thank you.

**Comment by SusanneWindfeldPedersen** [comment]
Hi - the screen shots are not included, I think it might be a restriction on this site. If you think this is a bug in the product, please file a bug through your usual support channel. This site is mainly for documentation feedback. You might also try going through the [AL Language repo](https://github.com/Microsoft/al) repo. Thanks, Susanne.

**Comment by DaveBoehmPBSI** [comment]
I've been communicating through email.  I'll zip the file and attach it, here.
[Susanne.zip](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/files/2005103/Susanne.zip)

**Comment by DaveBoehmPBSI** [comment]
Please see attached zip

Thanks,

--Dave--

David Boehm, CPA
PBSI
www.pbsisoftware.com<http://www.pbsisoftware.com/>
to book an appt.: https://outlook.office365.com/owa/calendar/ProfessionalBusinessSoftwareInc@pbsisoftware.com/bookings/
Office: 817.752.3352 <tel:817.752.3352>
Cell: 214.392.4797<tel:214.392.4797>
***********************************************************
This communication, along with any documents, files or attachments, is intended only for the use of the addressee and may contain legally privileged and confidential information. If you are not the intended recipient, you are hereby notified that any dissemination, distribution or copying of any information contained in or attached to this communication is strictly prohibited. If you have received this message in error, please notify the sender immediately and destroy the original communication and its attachments without reading, printing or saving in any manner. Thank you.

**Comment by moizsoloman** [comment]
Any idea where this issue stands in the queue
