### ISSUE TITLE
What is the difference between API-Query Object & Normal Query Object?

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/dynamics365smb-devitpro-pb#330]
When I type tfield in VSC I can choose API-type or Normal type for a query. What is the difference and what should I use to make a table visible through PowerBI?

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5400914d-d9a4-8bb0-e7f4-814b1476f8ee
* Version Independent ID: f8b799e6-614b-4a2f-4cdb-4d25f4499bec
* Content: [Query Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-query-object)
* Content Source: [dev-itpro/developer/devenv-query-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-query-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. We currently do not have any docs that talk about the query object of the API type, but we will have that. It resembles the page of the API type, but the query object of the API type can be used for viewing data only. Additionally, you can join data from more tables in the query object.
