### ISSUE TITLE
Video unavailable on the page

### ISSUE THREAD

**Issue by yzhums** [MicrosoftDocs/dynamics365smb-devitpro-pb#3300]
[Enter feedback here]

Video unavailable on the page
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60f679a6-a305-0502-b344-99b4bf18f828
* Version Independent ID: f54768bf-9ba2-ad84-542b-762819f9c9fa
* Content: [Performance Overview - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/performance/performance-overview?source=docs)
* Content Source: [dev-itpro/performance/performance-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/performance/performance-overview.md)
* Service: **dynamics-365-business-central**
* GitHub Login: @KennieNP
* Microsoft Alias: **solsen**

**Comment by KennieNP** [comment]
Thanks. I have removed the videos from the page

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, this is pushed live just now.
