### ISSUE TITLE
Subscriber cannot modify the global variable

### ISSUE THREAD

**Issue by himalpatel81** [MicrosoftDocs/dynamics365smb-devitpro-pb#331]
Subscriber can access the global variable but it cannot modify the value. There is no error but the modified value isn't reflected in publisher. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ec19e8-4483-6ff7-1650-f39441c84350
* Version Independent ID: 5ac2dca8-f31d-72b7-2094-18a7c0ad9bed
* Content: [GlobalVarAccess Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/globalvaraccess-property)
* Content Source: [dynamics-nav/GlobalVarAccess-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/GlobalVarAccess-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by zakisaad** [comment]
Did you declare the variable as a 'var' in the method signature?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset.
