### ISSUE TITLE
"Realm"?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#332]
From the doc:
Defining the notification scope: "The scope is the realm..."
"Realm"? I don't know that this word defines anything meaningful in a programming context. Definitions for "realm" include:
1. A community or territory over which a sovereign rules; a kingdom.
2. An area or sphere, as of knowledge or activity: the realm of science.
For purposes of this doc, I think this could be left out altogether--"scope" is a well-understood term, and the doc points out that there are two Scopes. The only implemented scope is defined quite specifically as "the page the user is currently working on." The definitions of "realm" do not seem to have anything to do with this definition. Perhaps something like "context" would be more appropriate, or just leave "realm" out altogether.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7717a802-1a09-69fb-5c54-bcbc27a605f8
* Version Independent ID: 0e99f7e1-d757-1cb2-6876-27ddb111a632
* Content: [Notifications - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/notifications-developing)
* Content Source: [dynamics-nav/notifications-developing.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/notifications-developing.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, the sentence has been rewritten to hopefully something more meaningful. The change will be published soon. Thanks for the feedback!
