### ISSUE TITLE
Wrong headline?

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#335]
Shouldn't this headline be updated to talk about Business Central and not NAV 2017?
Deployment Scenarios Supported in Microsoft Dynamics NAV 2017. 
Besides the headline, then the article also refers to NAV 2017 in other places.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a19d6592-5327-bf52-4cdb-cfd581d14687
* Version Independent ID: 3fa82fba-972e-2097-7036-1d7be39dafd1
* Content: [Multitenant Deployment Architecture - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/multitenant-deployment-architecture)
* Content Source: [dev-itpro/deployment/Multitenant-Deployment-Architecture.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/Multitenant-Deployment-Architecture.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, you are correct. The article has been fixed and an update will be published soon. Thanks for the feedback!
