### ISSUE TITLE
URL in app.json mandatory for AppSource submission

### ISSUE THREAD

**Issue by larswestman** [MicrosoftDocs/dynamics365smb-devitpro-pb#336]
It says here that "url" isn't mandatory but it is for AppSource submission. I also don't think it's super clear what "URL of the extension package" means. What should this URL point to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The url specification isn't mandatory for AppSource submission. The publisher can choose to use this setting to provide a link to the website of the extension package, if it has been created.

**Comment by larswestman** [comment]
Yes it is mandatory. We had an app that failed because of this

![image](https://user-images.githubusercontent.com/43792551/55734057-315a5380-5a1f-11e9-9bc9-e18a98c81685.png)

**Comment by SusanneWindfeldPedersen** [comment]
Hi, on our side it has been confirmed that this should not be mandatory. Can you please raise this issue with the team handling your AppSource submission. Thanks.

**Comment by larswestman** [comment]
Why don't you contact the appsource submission team directly? I can give you contact information if you don't have. I don't see the point in me beeing the middle man in this.
