### ISSUE TITLE
Topics in wrong structure

### ISSUE THREAD

**Issue by makuhn** [MicrosoftDocs/dynamics365smb-devitpro-pb#339]
It seems that all topics related to data types are placed under node Methods. Instead they should placed under a separate node Data Types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f36756-e238-1633-0ff2-b54112355319
* Version Independent ID: 660b2a2d-3c5a-32bf-bda8-5c66d2fbd913
* Content: [Action System Option - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/action/action-option)
* Content Source: [dev-itpro/developer/methods-auto/action/action-option.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/action/action-option.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The structure is intentional, we have chosen to group the methods according to the datatypes they can be used on. We may, in a future release, also expose the methods in the table of contents. Thanks.
