### ISSUE TITLE
the doc should be explicit on the return value of WORKDATE

### ISSUE THREAD

**Issue by grobyns** [MicrosoftDocs/dynamics365smb-devitpro-pb#34]
The documentation is unclear as to what happens when you call the following:
date1 := WORKDATE(date2);
a lot of people mistakenly think that what you get is the old workdate in date1 and that workdate is set to date2. That is not what happens. What happens is that WorkDate is set to Date2 and then Date2 is returned so you end up with WORKDATE = Date2 = Date1.
This should be clarified in the doc, if you want to save the old WORKDATE you must do it BEFORE setting the new date!

Cheers,
Gert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0667eba0-6b74-8f6b-0cd8-46703112e1e2
* Version Independent ID: 7b5dc4d1-cd4d-94ee-e5db-c3c3722a1515
* Content: [WORKDATE Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/workdate-function--date-)
* Content Source: [dynamics-nav/WORKDATE-Function--Date-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/WORKDATE-Function--Date-.md)
* Service: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks Gert, 

I have made some changes, which will be available the next time we refresh the content.
