### ISSUE TITLE
Local server settings have serverIntance twice in documentation?

### ISSUE THREAD

**Issue by mrmnaveed** [MicrosoftDocs/dynamics365smb-devitpro-pb#35]
I think serverIntance setting has been repeated with "NAV" and with "US" values. Is it intentional or a mistake ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by edupont04** [comment]
fix ready

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for feedback. This is now fixed in the latest refresh of the docs.
