### ISSUE TITLE
QuickEntry sequence

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#350]
How is the "jumping" sequence established?
In older versions we had the "NextControl" property but it doesn't seem we have anything like that now.
I did a test looping through fields on a Sales Order, and it doesn't work the same way in the Windows client and the Web client:
Windows: 
Name -&gt; Contact -&gt; Posting Date -&gt; Due Date -&gt; Req. Delivery Date -&gt; External Doc. No. -&gt; Lines subform::Type and then starts jumping between QuickEntry fields on the lines.
Web:
Follows the same sequence until External Doc. No., but then it skippes over the Order Lines and jumps to "Invoice Discount Amount" and it never gets to the lines.
However, if you press Tab in External Doc. No. it'll take you to the first column in the lines...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cb4c867-f156-28bd-5a12-66400778349f
* Version Independent ID: f1a3fcf7-526d-8b92-684f-1194f0d2c00c
* Content: [QuickEntry Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-quickentry-property)
* Content Source: [dev-itpro/developer/properties/devenv-quickentry-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-quickentry-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by mikebcMSFT** [comment]
Good news! We announced on 21st January 2019 that the next major release of Dynamics 365 Business Central will have full support for Quick Entry in the browser and Windows 10 desktop app. Not only will it work effectively in embedded pages (such as Sales Lines), but includes personalization and many improvements too.

Learn more in the April '19 Release Notes: [https://docs.microsoft.com/en-us/business-applications-release-notes/April19/dynamics365-business-central/quick-entry](https://docs.microsoft.com/en-us/business-applications-release-notes/April19/dynamics365-business-central/quick-entry)

In the meantime, the property you are looking for is named **QuickEntry**. Set it to false to skip over that field when using the **Enter** key. Read about it here: https://docs.microsoft.com/en-us/dynamics-nav/quickentry-property

thanks,
Mike Borg Cardona
The Business Central team

**Comment by Bleika** [comment]
Thanks Mike,
I already read the whole release notes yesterday - very impressive and good news indeed!!

Before posting my issue, I had already read about the Quick Entry property and, although the current version is an improvement, I missed the option to control the jumping sequence (within established QuickEntry fields) like we could do in Classic Client through the NextControl property. 
I'm not sure up to what point we'll have control over that as of April, but I'm really looking forward to get my hands on that release...

**Comment by mikebcMSFT** [comment]
Hi @Bleika, glad you like what is coming next :)

If you are enrolled in the Ready To Go program, you should have access to this in pre-release builds already. aka.ms/readytogo

From April, you will be able to write expressions into the  QuickEntry property value, which evaluate to True or False. This will allow you to provide alternating paths through fields on the page, based on your own custom logic. It is not as simple as pointing each field to the next field that Quick Entry should navigate to of course, but allows some flexibility.

thanks,
Mike Borg Cardona
The Business Central team

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your question, glad you got a useful answer, and thanks Mike. Closing this issue.
