### ISSUE TITLE
XMLport example for import missing

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#351]
"XMLports are used to export and import data between an external source and Dynamics 365 Business Central."
Please provide an example of importing data with XMLport.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2f92e5-2f2f-c619-03fb-af306a7fb078
* Version Independent ID: ddcf8182-3bd8-e9d6-030e-0c3ca01155b5
* Content: [XMLport Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-xmlport-object)
* Content Source: [dev-itpro/developer/devenv-xmlport-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-xmlport-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We have improving XMLports docs on our backlog and are aware that we're currently lacking this information. We hope to get this fixed in an upcoming refresh. Thanks.
