### ISSUE TITLE
// Notice, that when SubScriberCodeunit888 goes out of scope, all bindings are removed.  

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#352]
Where is Codeunit888?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46607d02-2c1c-3f01-f59d-8ed8c77a9bd0
* Version Independent ID: ad22b4af-1ce8-6320-bc7e-53ff1f424435
* Content: [BINDSUBSCRIPTION Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/bindsubscription-function)
* Content Source: [dynamics-nav/BINDSUBSCRIPTION-Function.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/BINDSUBSCRIPTION-Function.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, the reference should have been to SubScriberCodeunit5000. This has been fixed. Thanks for the feedback!

**Comment by lvanvugt** [comment]
> Hello, the reference should have been to SubScriberCodeunit5000. This has been fixed. Thanks for the feedback!

Looking at https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/session/session-bindsubscription-method right now it clearly has not been fixed or at least released.
