### ISSUE TITLE
Link is Wrong

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#353]
Hi,
On page https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-applicationarea-property

The link to "ApplicationArea Method" below "See also" points to wrong place. Should be
ApplicationArea Method: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/session/session-applicationarea-method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c319f083-b087-7cc9-5d64-807a2c6c0f09
* Version Independent ID: 4b76442b-9264-4f7b-478f-0635b2b24bcd
* Content: [ApplicationArea Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-applicationarea-property)
* Content Source: [dev-itpro/developer/properties/devenv-applicationarea-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-applicationarea-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi and thank you for your feedback! The link has been corrected and the updated article will be available with one of the next doc refreshes.
