### ISSUE TITLE
The Documentation seems incomplete

### ISSUE THREAD

**Issue by vytjak** [MicrosoftDocs/dynamics365smb-devitpro-pb#355]
For example, it does not specify that tabulator character should be specified as &lt;TAB&gt;.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b23d555-9ad9-464b-3631-07f5da96fa3f
* Version Independent ID: 04cf63d1-bcea-24ca-2b53-92abd7f09898
* Content: [FieldSeparator Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-fieldseparator-property)
* Content Source: [dev-itpro/developer/properties/devenv-fieldseparator-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-fieldseparator-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi and thank you for your feedback! The article has been updated and it will be available with one of the next doc refreshes.
