### ISSUE TITLE
Missing translation and detail for OnPrem

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#356]
Hi,
Currently this page for es-es shows up in English.

Furthermore, I'm sorry to insist, but it's not clear at all in what costs OnPrem solutions will incur - the following Q&A seems to refer to Cloud:
"Is there a cost to configure the Intelligent Cloud?
Currently, the only costs associated with the intelligent cloud are your named user license costs."

For OnPrem, the customer has already invested in OnPrem named users. 
Does this answer mean that there is no extra cost at all to connect such a solution to the Intelligent Cloud or is there any sort of subscription fee required? If there are extra fees, how are they applied? 
(i.e.: will you need a cloud user for every OnPrem user that wants to access this feature?)

Can you please clarify this? I think it's a completely valid and basic question for the Q&A on this specific topic, rather than to tell us to repeat this question (which is already here to begin with) somewhere else...

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 7bffc19c-cc0a-fec5-b46b-16e58b034c19
* Version Independent ID: 0a79027a-c75c-f003-1c89-b0b64d4510de
* Content: [Frequently Asked Questions - Business Central](https://docs.microsoft.com/es-es/dynamics365/business-central/dev-itpro/administration/faq-intelligent-cloud)
* Content Source: [dev-itpro/administration/FAQ-Intelligent-Cloud.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/FAQ-Intelligent-Cloud.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by Bleika** [comment]
Besides the fact that this Q&A is placed under On-Premises -> FAQ about Connecting to the Intelligent Cloud and the obviousness that this is the very first question customers make...

**Comment by edupont04** [comment]
Hi Eyrún,
The content in this area of the docs is available in English only with no plans to translate. As for your request to add an entry to the FAQ about licensing, I will take that up with the PM who owns this.

**Comment by Bleika** [comment]
Hi Eva,
I'm not requesting a new entry in the FAQ - my point is that the existing reply doesn't really answer the question (and sounds "Cloud focused" under the OnPrem branch).

**Comment by edupont04** [comment]
Information in Spanish about Business Central on-premises connecting to Business Central online: [https://docs.microsoft.com/es-es/dynamics365/business-central/about-intelligent-cloud](https://docs.microsoft.com/es-es/dynamics365/business-central/about-intelligent-cloud).

The administration FAQ is being updated Monday with more clarity. closing accordingly.
