### ISSUE TITLE
Upgrade codeunit to handle upgrade with destructive schema changes. Example needed

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#357]
The Linked page claims that there is an option to use an Upgrade Codeunit to handle destructive schema changes to the DB. Can you please provide a working example of such a Codeunit, As I am not aware of any trigger that can be executed before syncing the DB and syncing the DB with a destructive change in the new version of the extension causes a familiar runtime error:
Table MyTable :: Unsupported field change. Field:Remove Me; Change:Remove

Id rather reccomend to point to the new policy that no destructive schema changes are supported and that you're supposed to use the Obsolete properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b266ea7a-049f-9207-c6fb-3f7a144e0d11
* Version Independent ID: 68524337-a503-4f68-2cde-334bbfecd11d
* Content: [Synchronizing extension test data - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-retaining-data-after-publishing)
* Content Source: [dev-itpro/developer/devenv-retaining-data-after-publishing.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-retaining-data-after-publishing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we have updated the topic to be more explicit regarding breaking changes. This topic will be pushed live soon. Thanks.
