### ISSUE TITLE
Missing description for Label attributes

### ISSUE THREAD

**Issue by jvincke** [MicrosoftDocs/dynamics365smb-devitpro-pb#358]
The comment, locked, and maxLength attributes are not explained here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15813f6-f9d6-5008-5d18-c69fd4f0f761
* Version Independent ID: 0ac4ae64-4482-818b-b0fd-0b59f7d7a962
* Content: [Label Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/label/label-data-type)
* Content Source: [dev-itpro/developer/methods-auto/label/label-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/label/label-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by ailie13** [comment]
Hi and thank you for your feedback! The topic has been updated and it will be available with one of the next doc refreshes.
