### ISSUE TITLE
No DynamicsNAVIntegrationSolution.zip file on DVD

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#361]
The DVD does not have a file called DynamicsNAVIntegrationSolution.zip.

Instead there is a DynamicsNAVIntegrationSolution_v8.zip or DynamicsNAVIntegrationSolution_v9.zip.

The question is which one to use when?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d13606d-1b5f-8061-ddbb-65bad9f63e29
* Version Independent ID: ef4faad8-2f82-cd9c-100f-1dc181db3974
* Content: [Preparing for Dynamics 365 for Sales for Integration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration)
* Content Source: [dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration.md)
* Service: **dynamics365-business-central**
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
I will close the issue for now. If this does not answer your question, please let me know and I will re-open it. Thanks for the feedback.

**Comment by epernst** [comment]
I had already guessed that this was the answer, but thanks for clarifying it.
