### ISSUE TITLE
Use more than 16 fields for primary key

### ISSUE THREAD

**Issue by yannicklaemmler** [MicrosoftDocs/dynamics365smb-devitpro-pb#363]
You are still able to use up to 20 unique fields to define a primary key in the newest release of Dynamics 365 Business Central.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6d8214c2-4770-56c6-d9a0-ad2c2e774398
* Version Independent ID: 98d65841-770f-1256-e03d-68275abb2207
* Content: [Set Primary and Secondary Keys - Dynamics NAV](https://docs.microsoft.com/de-de/dynamics-nav/how-to--define-primary-and-secondary-keys)
* Content Source: [dynamics-nav/How-to--Define-Primary-and-Secondary-Keys.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Define-Primary-and-Secondary-Keys.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, you can set up to 20 fields, however only the first 16 are used. Let me know if you experience otherwise. I will update the article to suit. Thanks for the feedback!

**Comment by jswymer** [comment]
This limit is imposed by SQL Server. I have updated the Business Central article about keys, [Table Keys](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-keys), with this info. The update will be published soon.
