### ISSUE TITLE
Outdated instructions?

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#364]
Can the area keyword no longer be used?
Developing against CU3, VSCode does not accept this syntax within a Page Extension:
    actions
    {
        area(SomeArea)
        {
            action(SomeAction)
            {

It gives the following error:
Expected one of the application object keywords (table, tableextension, page, pageextension, pagecustomization, profile, codeunit, report, xmlport, query, controladdin, dotnet, enum, enumextension) [AL0198]

I finally managed to add my action in the following way:
    actions
    {
        addafter(ExistingAction)
        {
            action(MyAction)
            {

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62a7769-3446-41f2-3d06-8c9cc95b95c5
* Version Independent ID: fd778e60-c4bc-4696-ac55-3cf292329d0a
* Content: [Adding Actions to a Page - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-actions-to-a-page)
* Content Source: [dev-itpro/developer/devenv-adding-actions-to-a-page.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-actions-to-a-page.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
You should still be able to use area() - that hasn't changed. Please file a product bug if you cannot make it work with valid syntax. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Sorry, are you trying to create a page extension object? For a page extension you cannot use the area, you must use the layout as it is defined and then use addlast() to place an action for example. But the doc that you're referring to is showing a page object example, and there you can use area. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
We'd really like to provide much more content and in particular code examples, I am sorry that you feel it's trial and error. We hope to be able to provide more code examples in a near future.
