### ISSUE TITLE
Syntax examples

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#365]
There are still no syntax examples since June last year.
Can you please provide some?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d90498e-72df-207a-5344-db408659666d
* Version Independent ID: fde80388-7526-f049-8b62-c5dcc2d1e9e8
* Content: [RunPageLink Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-runpagelink-property)
* Content Source: [dev-itpro/developer/properties/devenv-runpagelink-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-runpagelink-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your patience. The topic has been updated and is available with the next doc refresh.
