### ISSUE TITLE
Valid Page Types for Property and Results according to Client

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#367]
It would be helpful if you added (if not here, then on the individual topic pages) which Page Types support a given Property when limitations exist (i.e. Card Page, List Page, etc.), like for ColumnSpan vs. Width, etc.. 

Also, rendering can be different based on Client and it would also be helpful if the individual pages would add a note when an important difference can be expected - i.e. Promoted property shows differently in Windows or Web Client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2612295b-ecb2-93f1-2097-c5e055ed5123
* Version Independent ID: ec810858-2ada-8915-c110-7634c6b791b4
* Content: [Page and Page Extension Properties Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-property-overview)
* Content Source: [dev-itpro/developer/properties/devenv-page-property-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-page-property-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by Bleika** [comment]
Please improve this page and the underlying ones as the information is misleading or even wrong in some cases (at least as to what properties can be used in page extensions) and lacking in examples for those that should work on page extensions but the compiler won't accept or reckognize.

Some examples:
I've successfully employed the following in page extensions:
Editable AND Enabled (1 of the 2 is indicated as unavailable)
Image
LookupPageId
Scope

Others, like PromotedCategoryActionsCaptionML seem impossible to implement.

I think you should also consider that limitations may apply as to what the developer needs to achieve:
Within a page extension, one thing is if you want to modify the behaviour of  a control or an action that are already present on that page as standard - and thus which properties are available, and another thing alltogether is what you can apply to controls or actions you're adding to that same page.

Actually, if you really need to modify some of the properties listed as "not available for page extensions" for an existing field, there's a simple trick:
You hide the original field:
modify(WhateverField) {Visible = false;}
and simply add it again in the extension:
field(WhateverField) { WhateverProperty}

That way, I was even able to change the Lookup page for the "Item No." column in a Journal to Customer List...

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we have it on our product backlog to auto-generate properties documentation which would give an accurate description of which properties apply to which page type object. Meanwhile, IntelliSense is the guidance for what applies in a given context. Thanks for your feedback.
