### ISSUE TITLE
System Requirements link does not exists

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#368]
In the See Also section there is a link to System Requirements. This link (https://docs.microsoft.com/en-us/deployment/system-requirement-business-central.md) returns a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db917c4-601c-b6f1-863f-17b83d35e814
* Version Independent ID: 22279a66-57b2-7f98-16b6-3cfb394b7fda
* Content: [Features not implemented in on-premises deployments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/features-not-implemented-on-premises)
* Content Source: [dev-itpro/features-not-implemented-on-premises.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/features-not-implemented-on-premises.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Nice catch! Thanks, the link has been fixed and an updated article will be published soon.
