### ISSUE TITLE
Force Parameter

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-devitpro-pb#369]
&gt;&gt;Gets or sets a switch indicating wether the user should be promted that all data in the sandbox will be deleted.
Which data gets deleted when creating a runtime package?
Maybe this is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d4019f-1029-399b-b7c3-2f809ebe649c
* Version Independent ID: 4c738593-41be-a215-4fbc-3bd22ec47d42
* Content: [Get-NavAppRuntimePackage (Microsoft.Dynamics.Nav.Apps.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappruntimepackage?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Apps.Management/Get-NavAppRuntimePackage.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Apps.Management/Get-NavAppRuntimePackage.md)

**Comment by jswymer** [comment]
Hello, the text is incorrect, and was probably inadvertently added at some time. There is no data deleted.  The -Force switch in this case is the standard switch that runs the command user confirmation. We have fixed the article and an update will be published soon. Thanks for the feedback!
