### ISSUE TITLE
Clarification re critical errors

### ISSUE THREAD

**Issue by danielrodgers** [MicrosoftDocs/dynamics365smb-devitpro-pb#37]
"Errors that are not resolved must include an explanation and justification for the error."
The above sentence makes it unclear whether an app may be submitted if it contains critical errors.

Does this mean that if an extension contains a critical error (eg usage of ASSERTERROR) that it may be submitted to App source if the usage can be justified or does this only apply to "important errors"?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b8f96f-eb61-aa86-ed4f-4544e9808aef
* Version Independent ID: fabff680-eeb9-26b4-5253-04713e0e1c74
* Content: [Rules and Guidelines for AL Code - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/dev-itpro/compliance/apptest-overview)
* Content Source: [dev-itpro/compliance/apptest-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by ryanweigel** [comment]
It applies for both important and critical errors. You must have valid justification when you submit your app for App Source. There is a field in the Cloud Partner Portal (where you upload your app for submission), that allows you to upload a justification document explaining why you need any errors

**Comment by danielrodgers** [comment]
Thank you for the clarification.
