### ISSUE TITLE
Only describes On-Prem

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/dynamics365smb-devitpro-pb#370]
Please add url for Odata streams for the cloud variant too.

`https://api.businesscentral.dynamics.com/v1.0/<tenant-id>/ODataV4/Company(<CompanyName>)/`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a858643-0f12-aff0-9480-e19f62f7b219
* Version Independent ID: d5ea3522-ad2e-5fa6-d8fa-57733d1683e7
* Content: [How to: Publish a Web Service - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/publish-web-service)
* Content Source: [dev-itpro/webservices/publish-web-service.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/publish-web-service.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback.

The article has been updated with a link to [Endpoints for the APIs for Dynamics 365 Business Central On-Premises and Online](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics) for an overview of the endpoints. We hope this helps. The update will be published soon.
