### ISSUE TITLE
What is the importance of NAV 2017 in tenancy upgrade?

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#371]
According to this article, then it's a requirement to upgrade to Microsoft Dynamics NAV 2017 before migrating to multi-tenancy. Isn't that wrong? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d21543-2d25-b705-e3c6-4e2df0054b64
* Version Independent ID: da02181d-08c6-a4e6-9d5f-f185b16f9896
* Content: [Migrating to Multitenancy - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/migrating-to-multitenancy)
* Content Source: [dev-itpro/deployment/Migrating-to-Multitenancy.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/Migrating-to-Multitenancy.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by epernst** [comment]
Also, is it a mistake or "per design" that this page is not shown in the table of content in the left side bar?

**Comment by jswymer** [comment]
Hello, good catch! This statement is incorrect, and has been removed from the article. Also, I have added a link to the article from the table of contents. The updates will be published soon. Thanks for the feedback!
