### ISSUE TITLE
Not enough detail

### ISSUE THREAD

**Issue by joshuapearsonnot** [MicrosoftDocs/dynamics365smb-devitpro-pb#373]
This is very brief. It doesn't describe the purpose of a TextConst and why they are used in BC. It does not give an example of how to use it or where to put it on the AL object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5430cd34-1b14-3cea-c29e-f161b6793b78
* Version Independent ID: 36251966-e872-e2f8-d462-5efbec2f66ba
* Content: [TextConst Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/textconst/textconst-data-type)
* Content Source: [dev-itpro/developer/methods-auto/textconst/textconst-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/textconst/textconst-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Yes, you're absolutely right. I've added some more content and will be pushing the topic live soon. The TextConst datatype is typically used for UI messages, below you can see a code example of the data type with local and global declaration:

codeunit 50100 MyCodeunit
{
    procedure MyProcedure(): ErrorType
    var
        localTextConst: TextConst ENU = 'My text', DAN = 'Min tekst';
    begin
        Message(localTextConst);
    end;

    var
        globalTextConst: TextConst ENU = 'My text', DAN = 'Min tekst';
}
