### ISSUE TITLE
New docker image libraries

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#375]
Can you please update the references to the new docker image libraries and which one to use, BC OnPrem, BC Cloud, Dynamics NAV, future releases.

"bcsandbox will move to mcr.microsoft.com/businesscentral/sandbox"
https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/

http://www.waldo.be/2019/01/24/where-to-find-the-microsoft-dynamics-365-business-central-and-nav-docker-images/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6979fc73-1395-b63f-50bf-b2fb1bfda4df
* Version Independent ID: eaf8c4d6-15a5-6444-bc72-48bd0a2e326a
* Content: [Running a Container-Based Development Environment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-container-development)
* Content Source: [dev-itpro/developer/devenv-running-container-development.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-running-container-development.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We will not include all the library information in this topic, but we've added a link to the blog post for more information, which will be pushed live with the next refresh.
