### ISSUE TITLE
"HandlerFunctions", not "HandlerMethods"

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#376]
From what I understand the property is not called "HandlerMethods" - it's called "HandlerFunctions" (both in C/AL and AL...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b8d512-21a9-7235-4559-0a4067c258a7
* Version Independent ID: b04c1739-a7e4-52bc-889e-7923e9059f4f
* Content: [HandlerMethods Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-handlermethods-property)
* Content Source: [dev-itpro/developer/properties/devenv-handlermethods-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-handlermethods-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon. We are also working on revamping the content around application testing, so more changes are to come. Thanks again.
