### ISSUE TITLE
Samples wanted

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#377]
Please provide a short code sample in these kind of pages.

As something like:
```
    [Test]
    [HandlerFunctions('SendNotificationHandler')]
    procedure MyTestFunction();
    begin
      ...
    end
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b8d512-21a9-7235-4559-0a4067c258a7
* Version Independent ID: b04c1739-a7e4-52bc-889e-7923e9059f4f
* Content: [HandlerMethods Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-handlermethods-property)
* Content Source: [dev-itpro/developer/properties/devenv-handlermethods-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-handlermethods-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback. Sorry. we realize that the content around application testing, test codeunits, and methods, lacks information. We are working on improving this content, and more examples is definitely a goal. We hope to have some new content published soon! Thanks again.
