### ISSUE TITLE
The type is called Record, not Table

### ISSUE THREAD

**Issue by vytjak** [MicrosoftDocs/dynamics365smb-devitpro-pb#378]
As per the issue title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9bf9d02-6eb2-6bd1-2e43-edf240d40bdc
* Version Independent ID: 96142ae6-b61b-a1b2-c55c-8d11a40a1751
* Content: [Table Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/table/table-data-type)
* Content Source: [dev-itpro/developer/methods-auto/table/table-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/table/table-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This is due to a bug in our auto-generated tooling. I've filed a product bug and will close this issue. Thanks.
