### ISSUE TITLE
Data Types listed under Methods

### ISSUE THREAD

**Issue by vytjak** [MicrosoftDocs/dynamics365smb-devitpro-pb#379]
Why is the language data type listed under "Methods" section?
Shouldn't this be a proper separate section listing all built-in data types?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c9bdf2-b0eb-ae82-4c62-6e52cdbe310a
* Version Independent ID: 593a228e-3ca3-fb32-149a-45a467e213e8
* Content: [AL Language Reference Library - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/library)
* Content Source: [dev-itpro/developer/methods-auto/library.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/library.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This is an auto-generated topic that lists all the types that are available in AL. It requires a product fix for this to work in a different manner. We will consider it for a future release. Thanks.
