### ISSUE TITLE
Link to "Business Central Windows PowerShell Cmdlets" returns 404

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#381]
The link to Business Central Windows PowerShell Cmdlets (used 4 times in this page) points to https://docs.microsoft.com/en-us/powershell/business-central/overview.md which returns a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f868dd47-4d64-3404-3df1-129de0a04154
* Version Independent ID: e687b0c7-6a0a-2976-820a-89adee0a6255
* Content: [Separating Application Data from Business Data - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/separating-application-data-from-business-data)
* Content Source: [dev-itpro/deployment/Separating-Application-Data-from-Business-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/Separating-Application-Data-from-Business-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by epernst** [comment]
Works if you remove .md from link.

**Comment by jswymer** [comment]
The links have been fixed and an update will be published soon. Thanks for the feedback!
