### ISSUE TITLE
FormatString(): Examples

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#383]
The NAV documentation of the Format function has way better detail about the effects of the different Parameters. This is extended by the Link to the Format-Property Where this particular Parameter is documented in even greater detail. I'd recommend copying this content from the NAV-Docs linked below: (You already replicated the Format-Property)

https://docs.microsoft.com/en-us/dynamics-nav/format-function--code--text-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c745c7fa-6517-541f-d18a-36226db7fb64
* Version Independent ID: f41b2a8c-8545-a5a2-4550-092786b1fde9
* Content: [Format Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/system/system-format-joker-integer-string-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This was due to an auto-generated doc process for the methods, but I have ported the content over and the topic will be refreshed with our next push. Thanks again!
