### ISSUE TITLE
Not able to get fields while using Generic Charts

### ISSUE THREAD

**Issue by RagRawat** [MicrosoftDocs/dynamics365smb-devitpro-pb#384]
Hi,
I created on query in VS Code but not able to view when i am connecting through generic charts.
Able to view Query Id but not able to fill fields for X and Y axis.

Raghubir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5400914d-d9a4-8bb0-e7f4-814b1476f8ee
* Version Independent ID: f8b799e6-614b-4a2f-4cdb-4d25f4499bec
* Content: [Query Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-query-object)
* Content Source: [dev-itpro/developer/devenv-query-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-query-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for the long wait. This seeks to be a product question more, hope you succeeded in solving this issue. Otherwise, please use your usual support channel. Thanks.
