### ISSUE TITLE
Does not work on NAV 2016 CU 37

### ISSUE THREAD

**Issue by s1nn3r** [MicrosoftDocs/dynamics365smb-devitpro-pb#387]
I tried to reproduce "Set up a text link that uses custom text as the display Name", but whatever I try, the Word layout just includes the "var_Url" as plain text, no hyperlink and no replacement of the text with the "var_UrlText".
Any ideas? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00da8a61-2759-fd5d-7018-4418ad1f8bd3
* Version Independent ID: 0af9f0a3-caa9-ef56-82ba-9b1cdfc84726
* Content: [Setting up Hyperlinks in Word Report Layouts - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/setting-up-hyperlinks-in-word-report-layouts)
* Content Source: [dynamics-nav/Setting-up-Hyperlinks-in-Word-Report-Layouts.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Setting-up-Hyperlinks-in-Word-Report-Layouts.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello,

Sorry for the delayed response. We've verified that this works on later versions, but if you are still having problems, please contact support to better troubleshoot the issue. If there is an update to the documentation, then we'll be notified. Thanks!
