### ISSUE TITLE
Missing AssistEdit 

### ISSUE THREAD

**Issue by passports** [MicrosoftDocs/dynamics365smb-devitpro-pb#388]
Where are the AssistEdit button in Visual Studio Code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babe9dc8-8278-49b7-3f8a-0bc75dd8307b
* Version Independent ID: 7cf185fd-3e0e-6d5f-7ed4-8a3773534357
* Content: [SubPageView Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-subpageview-property)
* Content Source: [dev-itpro/developer/properties/devenv-subpageview-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-subpageview-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, sorry, this is referring to the old development environment (CSIDE).  It is not relevant in Visual Studio Code. We have fixed the articles accordingly and updates will be published soon. Thanks for the feedback!
