### ISSUE TITLE
Booleans Wait and VersionCheck are not described

### ISSUE THREAD

**Issue by bctails** [MicrosoftDocs/dynamics365smb-devitpro-pb#389]
I noticed booleans "Wait" and "VersionCheck" back in NAV2016, but couldn't find any documentation whatsoever.
In this document, at least they're mentioned, but it doesn't say what they do. Can anyone explain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416bd343-9ebe-fd9a-aa6d-b77f8f78baf2
* Version Independent ID: bd1a4ba9-9a38-b6b2-2384-8ac7932aee4f
* Content: [LockTable Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/table/table-locktable-method)
* Content Source: [dev-itpro/developer/methods-auto/table/table-locktable-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/table/table-locktable-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! We have fixed the article but the update has not yet been published. The parameters are similar to those on the LockTable method for the RecordRef data type, which you can read about at [LockTable Method](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-locktable-method). Thanks again.
