### ISSUE TITLE
Thanks for Information

### ISSUE THREAD

**Issue by rishichourey** [MicrosoftDocs/dynamics365smb-devitpro-pb#39]
We can Re-Name the  company without altering the data and make it as Single User. If we make Single User then NAV-Server Instance will stop, so it's better to do it without making single user. Once again thanks a lot for sharing such a helpful information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f249e5-7800-d655-0270-dd1e2d1904ca
* Version Independent ID: 2e1ba552-c6ce-9bd4-c5cc-8c3d81b7d9d9
* Content: [How to: Rename Companies - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--rename-companies)
* Content Source: [dynamics-nav/How-to--Rename-Companies.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Rename-Companies.md)
* Service: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback!

It is correct that you can rename a company without setting the database to Single User, and avoid having to restart the server instance. However, you run the risk of another user or operation making changes to the database in the meantime, which could lead to problems. Using Single User is a recommendation , but not a requirement. I made some slight changes to the article to make this more clear. 

Thanks again.
