### ISSUE TITLE
Lacking example

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#390]
Example is lacking a PM value
I can guess that 2359T will give 11:59 PM in the output, but i cant know for sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08da475c-0713-23d5-29f7-02485deb07c6
* Version Independent ID: ea0a5d33-e7ba-2527-9c8c-60de9dcbeaf0
* Content: [Time Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/time/time-data-type)
* Content Source: [dev-itpro/developer/methods-auto/time/time-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/time/time-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. Setting the time to 235900T (it has to have a minimum of 6 digits) gives indeed 11:59:00PM. This example will be included for the next doc refresh.
