### ISSUE TITLE
mandatoryAffixes does not work with AL Language 2.1.79379

### ISSUE THREAD

**Issue by jvincke** [MicrosoftDocs/dynamics365smb-devitpro-pb#391]
Using mandatoryAffixes, as descibed on this help page, does nothing. mandatoryPrefix and mandatorySuffix work as expected. Using AL Language 2.1.79379 and VS Code: Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Datum: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17134

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20b8d3e7-476c-1bd8-abc0-1c36b9cd7707
* Version Independent ID: 1511a762-c037-d01b-63a9-0f31f6d1656e
* Content: [An affix is required. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0011-identifiersmusthaveaffix)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop-as0011-identifiersmusthaveaffix.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop-as0011-identifiersmusthaveaffix.md)
* Service: **dynamics365-business-central**
* GitHub Login: @qutreson
* Microsoft Alias: **qutreson**

**Comment by jvincke** [comment]
The same documentation feedback would be valid for https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This is a product bug, please use the usual system to report this bug. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Reopening - because this is due to a change only in Developer Preview. The mandatoryAffixes will replace the mandatoryPrefix and mandatorySuffix rules with the next release, but if you're not running a Developer Preview build, you can only use mandatoryPrefix and mandatorySuffix so far. The docs will be updated to reflect this. Thanks for your feedback!
