### ISSUE TITLE
Is Microsoft.Dynamics.Nav.CodeAnalysis.dll valid only for AL?

### ISSUE THREAD

**Issue by eclipses24** [MicrosoftDocs/dynamics365smb-devitpro-pb#392]
I can see big steps ahead with the new product and the fact that finally every developer can analyse his custom code using the same rules it's amazing. 
I know that for C/AL Micorosoft has an internal tool that has been never released (publically). 
Are the dll starting for Microsoft.Dynamics.Nav valid only for AL or is there any option to use them for C/AL? 
I know that everyone is looking how to improve AL but as a partner we will continue using C/AL probably for another couple of years. An official support on this would improve quality of code to be moved to AL in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a5b68ec-d706-ab10-8cb9-22e8d98c3494
* Version Independent ID: 3da84c14-159f-3ac7-ee94-5e0faff222d8
* Content: [Using the Code Analysis Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool)
* Content Source: [dev-itpro/developer/devenv-using-code-analysis-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-using-code-analysis-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This is the documentation repo for Business Central and what you're asking is more strategic if I understand correctly. Can you please try the [AL repo](https://github.com/Microsoft/AL) to see if anyone can answer. Thanks.

**Comment by eclipses24** [comment]
Hi Susanne, 

Unfortunately AL repo will reply only to issue related to AL and not C/AL. Please help me to find the correct channel.

Kind Regards
  Sergio Castelluccio
