### ISSUE TITLE
Create Charge Item from API

### ISSUE THREAD

**Issue by aherrick** [MicrosoftDocs/dynamics365smb-devitpro-pb#393]
I'm trying to write back a Sales Order Line with a Charge Item. In Business Central I've created a Charge Item.

![image](https://user-images.githubusercontent.com/586671/52492338-f78fdc80-2b96-11e9-845c-ca52bb1cc7fb.png)

Now via the API I'd like to create a Line with this item.

How do I find the Item Id of the Charge Item via a base entity? Is it not possible? What are the work arounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab8727c9-7b8e-2c83-680f-7f5c8a4ec22c
* Version Independent ID: dc43f5e7-d5d9-48e7-b74d-460b5a70150e
* Content: [Create salesOrderLines - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_create_salesorderline)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_create_salesorderline.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_create_salesorderline.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by AndersLarsenMicrosoft** [comment]
In our Document API’s we only support lines of type Comment , Account, and  Item for Post and patch request. However, we added support for Resource, Fixed Asset, and Charge on get request to support the scenario where an invoice is created in the UI and read through an API to give transparency to totals.

If the user wants to add a Charge to an invoice the can use item of type service or an account to specify this charge.

Regards,
Anders

**Comment by Mr-Pingu** [comment]
@AndersLarsenMicrosoft Will this be adressed in the upcoming release?

**Comment by AndersLarsenMicrosoft** [comment]
It is not a part of our plan to have this in our upcoming release. What scenario are you working on?

Thanks
Anders

**Comment by aherrick** [comment]
@AndersLarsenMicrosoft trying to write back a charge item line to the sales order

**Comment by AndersLarsenMicrosoft** [comment]
for now you use an item of type service or an account to specify this charge.

**Comment by aherrick** [comment]
@AndersLarsenMicrosoft can you expand on what you mean please?

**Comment by Mr-Pingu** [comment]
@AndersLarsenMicrosoft: We always have transport fee or transaction fee, especially transcation fee would ideally be a charge

**Comment by AndersLarsenMicrosoft** [comment]
For outbound documents like sales invoices or orders. Could any transportation fee or order handling fee easily be handled by an item of type Service, or Non-Inventory or a G/L Account. For inbound entries like purchase order or invoice an Item Charge is (often) used to add the transportation fee to the inventory value and therefor we recommend to use Item Charge where charge can be assigned to the individual purchase lines 

Thanks
Anders

**Comment by SusanneWindfeldPedersen** [comment]
Thanks all, closing this issue.
