### ISSUE TITLE
A missing scenario

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#394]
Hi,
I've just read through the updated version of the pages within this topic, and there's still one scenario missing:

Pre NAV2013 -&gt; BC OnPrem with Extensions (no C/SIDE)

In this case, obviously the DB must first be upgraded to 2013 or 2015 (already explained), but there is no topic that walks through what is needed when you upgrade data from customized tables directly into extensions V2 in an OnPrem scenario. (That is: it's not a question of transferring V1 data to V2 extensions).

At some point, data in customized standard tables and 50.### tables must be secured, dropped and then re-injected into extension tables and table extensions.

Can you please add a topic for this scenario, describing where this fits in within the data upgrade sequence for OnPrem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 477f688d-8f74-d141-eef2-bf570c56207b
* Version Independent ID: f56f56c5-07ca-32ff-6f5f-2d57e1cb54b2
* Content: [Upgrading to Microsoft Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-to-business-central)
* Content Source: [dev-itpro/upgrade/upgrading-to-business-central.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-to-business-central.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by Bleika** [comment]
In this thread you can see that many are struggling to reinvent the wheel for the mentioned scenario:
https://www.yammer.com/dynamicsnavdev/threads/1219289941

**Comment by edupont04** [comment]
Hi Eyrun,

I've added this to our backlog.

**Comment by Bleika** [comment]
Thanks Eva - looking forward to it!
As is, there are some more threads in Yammer on this, but it'll be very interesting to see the "official recommendations/best-practices"
