### ISSUE TITLE
count and performance

### ISSUE THREAD

**Issue by monicasuica** [MicrosoftDocs/dynamics365smb-devitpro-pb#395]
Are there any remarks regarding the performance issues when using record.count?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81d75654-e2a2-2155-1254-75a3db953c12
* Version Independent ID: de0cc599-a38e-262b-5807-2f5e3a531a60
* Content: [COUNT Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/count-function--record-)
* Content Source: [dynamics-nav/COUNT-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/COUNT-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we're unfortunately not able to provide any remarks regarding performance at this point. But thanks for your feedback.
