### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by vjekob** [MicrosoftDocs/dynamics365smb-devitpro-pb#396]
I used this URL to get here:
http://aka.ms/getstartedwithapis 

But, this document I got to (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-welcome) has nothing to do with what the short URL indicated. Please fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68de627-9313-57d8-bcfa-ffe741622d91
* Version Independent ID: c65d3f06-f186-2bd6-a95e-d4e95439cec5
* Content: [Build Your Business on Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-welcome)
* Content Source: [dev-itpro/developer/readiness/readiness-welcome.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-welcome.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
This is now fixed to point to the right topic, which is this: [Getting Started Developing Connect Apps for Dynamics 365 Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps). Thanks for your feedback.
