### ISSUE TITLE
Please develop this topic further

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#397]
The preceding help page lists this property as valid for Page Extensions.

If I want to use a PromotedCategory (let's say Category4) to group personalized Actions in a Page Extension, according to this I understand that I should be able to assign a personalized caption somehow like this:

PromotedActionCategoriesML = ENU = 'My Cat', ESP = 'Mi cat.';

However, I don't have a clue as to how to add this code...
group(Category4) isn't accepted
modify(Category4) isn't accepted
PromotedCategory isn't a valid keyword (only as an Action Property)
I even tried adding within my Action definition (which admittedly is a bit absurd for various Actions)
etc.

but nothing works...

Please provide a code example of how this should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2fd2246-25a2-7ac9-62cb-79ef33f911ae
* Version Independent ID: 7dcdfc2c-c67e-cce9-13f3-42a5c0cd6b2c
* Content: [PromotedActionCategoriesML Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-promotedactioncategoriesml-property)
* Content Source: [dev-itpro/developer/properties/devenv-promotedactioncategoriesml-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-promotedactioncategoriesml-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback and sorry for the late answer. The PromotedActionCategoriesML property is applied directly to the Page Extension itself, as follows:

```
pageextension 50100 CustomerCardExtension extends "Customer Card"
{
    PromotedActionCategoriesML = ENU = 'New,Process,Report, ENU Caption for category 4', 
                                 ESP = 'Nuevo, Procesar, Reportar, ESP Caption for category 4';

       ...

}
```
You set the captions as a string list of names in ascending order relative to the categories. That is, the first name of the list corresponds to the caption for the New category, the second to Process one, the third to the Report, the fourth to Category4, the fifth to Category5' and so on. 

This has been made clearer in the documentation and it will be available soon.
