### ISSUE TITLE
The line 'The methods supported for the DataScope option type are:' is wrong

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-devitpro-pb#398]
Should be:
'The methods supported for IsolatedStorage are:'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d134849f-83d2-d0b4-4c6b-92adbca2fdc9
* Version Independent ID: cb7d556c-7419-aa30-474f-60c1a9b14977
* Content: [Isolated Storage - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-isolated-storage)
* Content Source: [dev-itpro/developer/devenv-isolated-storage.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-isolated-storage.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback. We have fixed the article and the update will be published soon.
