### ISSUE TITLE
Wrong file name

### ISSUE THREAD

**Issue by skabaas** [MicrosoftDocs/dynamics365smb-devitpro-pb#399]
not the navsettings.json file should be edited, but the web.config file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a1ea52-a842-bd63-68fa-5163d7e5c8e9
* Version Independent ID: e51d9d66-39b1-20c3-6bfc-95faf80b8dc8
* Content: [Configuring SSL to Secure the Web Client Connection - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/configure-ssl-web-client-connection)
* Content Source: [dev-itpro/deployment/configure-ssl-web-client-connection.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/configure-ssl-web-client-connection.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! The article has been fixed and the update will be published soon.

**Comment by hiimnit** [comment]
It is navsettings.json though, web.config was used in NAV2017 and earlier if I am not mistaken.

**Comment by SUD-D365** [comment]
both secure and nonsecure URLs are using https in example.
One should be http i think.
