### ISSUE TITLE
Page Customization does not need an ID

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#4]
In the example the Page Customization has an ID, which is not needed as far as I now. So please update accordingly. BTW: nice if you provide the reasoning why we do not need an ID for this object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b19fa4-9f14-cbf5-fdc8-e9977148cf37
* Version Independent ID: 819a3ad3-580b-1b95-a7fa-b2856a84fce0
* Content: [Page Customization Object - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-page-customization-object)
* Content Source: [dynamics-nav/developer/devenv-page-customization-object.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/developer/devenv-page-customization-object.md)
* Service: **unspecified**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This is fixed with the next refresh of the docs.
