### ISSUE TITLE
Additional items to delete in Point 9 Clear all Microsoft Dynamics NAV Server instance records from the dbo.Server Instance 

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#40]
You must delete records from the Debugger Breakpoint table as well or you get an error:
---------------------------
Microsoft Dynamics NAV Development Environment
---------------------------
It is not possible to delete a table definition (the Debugger Breakpoint table) if there are records in the table.

Delete all records in the table for all companies before deleting the definition.
---------------------------
OK   
---------------------------

use the SQL command:
DELETE FROM [My NAV Database Name].[dbo].[Debugger Breakpoint] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221f01d5-21a5-b244-e419-f83ed74f84eb
* Version Independent ID: 3327eb70-9edb-cd5b-e935-ccb5c3008d7f
* Content: [Converting a Database - Technical Upgrade - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/converting-a-database)
* Content Source: [dynamics-nav/Converting-a-Database.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Converting-a-Database.md)
* Service: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback!

The article has been updated to include clearing the Debugger Breakpoint table. The change will be published soon.
