### ISSUE TITLE
Query from JsonObject.SelectToken method not working

### ISSUE THREAD

**Issue by MatejKminiak** [MicrosoftDocs/dynamics365smb-devitpro-pb#401]
Hi, 
query from this example is not working correctly and instead of [?(@.id=="'+employeeId+'")] there should be [?(@.id=='''+EmployeeId+''')]   -&gt; Three single quotes, not one double and one single.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2939ccd-b157-e93a-b567-941d90684077
* Version Independent ID: 93d80bd2-e74e-0487-acc1-c9ffb14cfad5
* Content: [SelectToken Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonobject/jsonobject-selecttoken-method)
* Content Source: [dev-itpro/developer/methods-auto/jsonobject/jsonobject-selecttoken-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/jsonobject/jsonobject-selecttoken-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback - this will be fixed with the next refresh.

**Comment by NavDeb** [comment]
Still not updated on https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsontoken/jsontoken-selecttoken-method. Just wasted far too much time before finding this article!
