### ISSUE TITLE
Not correct JsonArray.IndexOf method description

### ISSUE THREAD

**Issue by MatejKminiak** [MicrosoftDocs/dynamics365smb-devitpro-pb#403]
Hi, 
I think the description in JsonArray.IndexOf method is not correct and it is the description of Set methods. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2beae7f1-40fb-2e1e-1e53-f7b91ef4ee5b
* Version Independent ID: e364c4d6-5f58-e4b7-13a6-bb5debbaa5de
* Content: [JsonArray Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonarray/jsonarray-data-type)
* Content Source: [dev-itpro/developer/methods-auto/jsonarray/jsonarray-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/jsonarray/jsonarray-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for pointing that out. This will be fixed in the next doc refresh.

**Comment by jswymer** [comment]
Hello, good catch. Yes, it looks like the descriptions were copied from the SET() methods. The IndexOf() methods determine the index of an item in the JsonArray. The content has been fixed and an update will be published soon. Thanks for the feedback!
