### ISSUE TITLE
Code snipped would be nice

### ISSUE THREAD

**Issue by KSH-audibene** [MicrosoftDocs/dynamics365smb-devitpro-pb#404]
Because it is hard to understand where to place this trigger - it gives me constant error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85b87640-382e-8dff-473e-8ad0271004ba
* Version Independent ID: bff40a5a-0ac2-aeae-30e0-05294121f907
* Content: [OnModify Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onmodify-trigger)
* Content Source: [dev-itpro/developer/triggers/devenv-onmodify-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onmodify-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we currently do not have code samples in all our reference, but I agree, we should have. We'll be working towards this. 

I am not completely sure what you mean with your question where to place the trigger, so this may not be what you're looking for, but for triggers, you place these in code units, use the snippet 'ttrigger' to get the structure in VS Code. It looks something like this

codeunit Id MyCodeunit
{
    trigger OnRun()
    begin
        
    end;
    
    **trigger OnModify()
    var
        myInt: Integer;
    begin
        
    end;**

    var
        myInt: Integer;
}

**Comment by KSH-audibene** [comment]
I found it, the OnModify trigger should be placed before global var section in the table. 
If I put it right in the beginning it gives me an error "there must be at least one normal field in the table".

**Comment by SusanneWindfeldPedersen** [comment]
Good to know - thanks for your feedback!
