### ISSUE TITLE
The license is checked on the server where the runtime package is generated

### ISSUE THREAD

**Issue by larswestman** [MicrosoftDocs/dynamics365smb-devitpro-pb#405]
I think it should be made more clear what is checked. It should be stated that the license still need permissions for the objects used in the app-file (which i assume/guess/hope is correct....).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aea33a83-64c0-a56b-363a-b5aae7eb15f5
* Version Independent ID: a7919faa-7603-573b-ef43-10c60c3803d9
* Content: [Creating Runtime Packages for Business Central On-Premises - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages)
* Content Source: [dev-itpro/developer/devenv-creating-runtime-packages.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-creating-runtime-packages.md)
* Service: **dynamics365-business-central**
* Product: **dynamics-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. When the package is generated on the server, the developer license is checked to validate your extension IDs. When the package is installed at the customer site, they only need execute permission for these IDs, but no modify or insert permissions are required at this point. Hope that makes sense. We will update the topic to be more clear on this. Thanks.
