### ISSUE TITLE
-Tenant mandatory

### ISSUE THREAD

**Issue by larswestman** [MicrosoftDocs/dynamics365smb-devitpro-pb#406]
I hade to use -Tenant Default to get things working

The example should then be:

Get-NAVAppRuntimePackage -ServerInstance DynamicsNAV -Name 'Proseware SmartApp' -Version 2.3.4.500 -ExtensionPath 'Prosware SmartApp_2.3.4.500_runtime.app' -Tenant Default

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc4bb7a-d6f7-2edf-4198-4a399066c0a0
* Version Independent ID: 4c738593-41be-a215-4fbc-3bd22ec47d42
* Content: [Get-NavAppRuntimePackage (Microsoft.Dynamics.Nav.Apps.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/Get-NAVAppRuntimePackage?view=dynamicsnav-ps-2018)
* Content Source: [dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Apps.Management/Get-NavAppRuntimePackage.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Apps.Management/Get-NavAppRuntimePackage.md)

**Comment by blrobl** [comment]
Hi, sorry for the long wait. The example seems to work for us at it is. It is possible that you had a multi-tenant environment?

**Comment by larswestman** [comment]
Hi,

No. No multi-tenant. But I reported it in February and when I test now on BC14 CU2 it works without “-tenant default”, so you can close this ticket.

/Lars

Från: Blanca Robledo Díaz <notifications@github.com>
Skickat: den 2 september 2019 15:19
Till: MicrosoftDocs/dynamics365smb-devitpro-pb <dynamics365smb-devitpro-pb@noreply.github.com>
Kopia: Lars Westman <lars@goprowe.se>; Author <author@noreply.github.com>
Ämne: Re: [MicrosoftDocs/dynamics365smb-devitpro-pb] -Tenant mandatory (#406)


Hi, sorry for the long wait. The example seems to work for us at it is. It is possible that you had a multi-tenant environment?
