### ISSUE TITLE
Open port 7049

### ISSUE THREAD

**Issue by gsimardnet** [MicrosoftDocs/dynamics365smb-devitpro-pb#407]
I was unable to debug because my network was blocking port 7049. You should mention this as a requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3f5d28-1484-ce76-b31d-7ee0d444ba0f
* Version Independent ID: bdea6ca9-e7bc-d324-03d5-364c0fcaee4e
* Content: [Debugging - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-debugging)
* Content Source: [dev-itpro/developer/devenv-debugging.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-debugging.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, we will add this to the topic with the next refresh.
