### ISSUE TITLE
Dead link in portal

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/dynamics365smb-devitpro-pb#409]
Sorry If Post wrong place.

On the Portal Menu of [http://go.microsoft.com/fwlink/?LinkID=294709]
Their is Dead Link in [Find out more here] which toward of following.....

https://go.microsoft.com/fwlink/?linkid=865118
https://azure.microsoft.com/en-us/updates/publishsettings/preview/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836135bf-5f7f-2424-cfaf-11578f1e8d31
* Version Independent ID: 0deea7c7-a15c-fe7e-26ca-b9c0932b29b8
* Content: [How to: Download and Import Publish Settings and Subscription Information - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--download-and-import-publish-settings-and-subscription-information)
* Content Source: [dynamics-nav/How-to--Download-and-Import-Publish-Settings-and-Subscription-Information.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Download-and-Import-Publish-Settings-and-Subscription-Information.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by edupont04** [comment]
Hi Keiro,

This link is not owned by the Dynamics NAV team. I'm closing this issue, but I have frowarded your feedback to the Azure team for further processing.
