### ISSUE TITLE
OnPrem licensing

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#410]
This page is for BC running online. I am missing some link for similar info for OnPrem BC. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98387b95-ce70-594b-b0e1-36ef1b5a6fb6
* Version Independent ID: 8a8d3822-49c4-1422-e046-0d7c9726c9b6
* Content: [Object Ranges - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-object-ranges)
* Content Source: [dev-itpro/developer/devenv-object-ranges.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-object-ranges.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your question. We currently only have information for BC online, but I encourage you to read more about object ranges [in this blog post](https://community.dynamics.com/business/b/businesscentraldevitpro/archive/2018/10/17/which-object-ranges-can-we-use-with-microsoft-dynamics-365-business-central). If you still have questions, please reach out through the Ready to Go program. Thanks.
