### ISSUE TITLE
Labels syntax example missing

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#411]
Hello, there is no example how to write labels (passed as parameters to the RDLC). There is only empty lables section.
Please, add this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0042001-b98b-71c6-f659-84af0bd52a7d
* Version Independent ID: 212b2740-288e-8c5a-9e1e-960fcfb5739c
* Content: [Report Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-object)
* Content Source: [dev-itpro/developer/devenv-report-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-report-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by hiimnit** [comment]
Also struggled with this for a moment, here is what worked for me:
```
labels
{
    SourceAmountLbl = 'Source Amount';
    TargetAmountLbl = 'Target Amount';
    PageLbl = 'Page';
}
```

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Added label syntax to the docs, will be pushed live with our next refresh. Thanks.
