### ISSUE TITLE
Function does not work as described

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#412]
Test the following code:
```
procedure ReadStuffFromRDL()
    var
        InStr: InStream;
        RdlXmlDoc: XmlDocument;
        NsManager: XmlNamespaceManager;
    begin
        report.RdlcLayout(Report::"Order Confirmation", InStr); // I'm using the RDL definition of a report for a realistic scenario
        XmlDocument.ReadFrom(InStr, RdlXmlDoc);
        NsManager.NameTable(RdlXmlDoc.NameTable()); // in this line, i'd expect the NameTable to be transferred from the XMLDoc to the NSManager.
        Doc.SelectNodes('//rd:Selected', NsManager, NodeList);
    end;
```

This will crash in a manner that the WebClient only shows you the "An Error has occured" Page and you have to use the Event Log to find out that you have this error:
```
Type: System.Xml.XPath.XPathException
Message: Namespace prefix 'rd' is not defined.
``` 
I got these results from this image: microsoft/bcsandbox:ch-ltsc2019 (13.0.27183) runtime 2.3

edit: if you add
```NsManager.AddNamespace('rd', 'http://schemas.microsoft.com/SQLServer/reporting/reportdesigner');```
after "setting" the NameTable, you get the expected Node returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35ef7630-349e-9df7-3692-1e8b46e2570d
* Version Independent ID: a2985f22-7746-414a-4c96-17034e0df989
* Content: [NameTable Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/xmldocument/xmldocument-nametable-method)
* Content Source: [dev-itpro/developer/methods-auto/xmldocument/xmldocument-nametable-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/xmldocument/xmldocument-nametable-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please file this issue with your support/partner instead. Thanks.

**Comment by CptBlaubart** [comment]
I represent a partner (I work for one of your gold partners in Switzerland).

I'm reporting a bug. It's either not properly documented or not properly working. I spent 12+ hours researching this for you with try-and-error methods.

When i finally gave up, I build a simple piece of code to replicate my results on your side so you can fix it.

If you like, I will report this bug to any other of your portals but you have to tell me where because I only know of the preview GitHub and this is not preview.
