### ISSUE TITLE
Variable / method / parameter naming?

### ISSUE THREAD

**Issue by vytjak** [MicrosoftDocs/dynamics365smb-devitpro-pb#413]
The section defines well enough how to name the objects and their source files, but what about the variable / method / parameter naming conventions? 

Is this described somewhere else?
Should we reuse conventions from Dynamics NAV? (https://docs.microsoft.com/en-us/dynamics-nav/naming-conventions)

Some example issues I see (and I would like to refer our developers to official guidelines for this): 
1) The documentation briefly mentions using PascalCase, but then immediatelly also states that this is not a mandatory rule. 
2) Can we abbreviate record variables? I.e. "Sales Header" as "SH"?
3) Should variable names indicate whether it's a parameter/global/local variable? Same for methods.
4) Any special rules for TextConst naming?
These are just a few for a start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for you question - yes for now the [Naming Conventions](https://docs.microsoft.com/en-us/dynamics-nav/naming-conventions) still apply. We want to port this topic over to the AL docset and will do that in a future release.
