### ISSUE TITLE
Missing methods in Page Extensions Syntax

### ISSUE THREAD

**Issue by magpet01** [MicrosoftDocs/dynamics365smb-devitpro-pb#414]
This documentation has been lacking for some time now!
Please add which possible methods can be used in the Page Extension Syntax
ex
layout
    {
        // Add changes to page layout here
    --- please add possible methods (addafter, addbefore, moveafter etc..)---
    }
    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdda7e30-30d9-ac83-abf7-267a7f634c6d
* Version Independent ID: 5bf5ce87-f59a-d2ae-10b3-05eda02406b5
* Content: [Page Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)
* Content Source: [dev-itpro/developer/devenv-page-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please see [Pages](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-pages-overview) instead for this. Thanks.
