### ISSUE TITLE
Marooned References

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#415]
This page documents the CurrPage. UPDATE function. But there is no breadcrumb trail that tells us where we are in the documentation or would allow us to navigate in any helpful way.  The breadcrumb trail that does appear goes only as far as "Developer and IT-Pro Help", which is far too broad, and which does not appear in the navigation tree to the left. So the user finds themselves marooned somewhere in the middle of an extensive doc with no indicators as to where they are or where to go.

This means an entire new search has to be initiated to find other CurrPage functions. 
Very helpful would be to see the other CurrPage functions listed under See Also or on the left in a tree.  And the tree on the left should have some specific visual contextual relationship to the content of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d8693a8-e61d-3e35-3dde-b876810ab0ea
* Version Independent ID: a165db8d-6c87-a7bc-7d05-0e279b478f49
* Content: [UPDATE - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/update)
* Content Source: [dynamics-nav/UPDATE.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/UPDATE.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. We're not going to spend resources on implementing breadcrumbs on the Dynamics NAV docset, but we're planning on extending our Table of contents on the Business Central docset to make topics more discoverable going forward. Thanks for your understanding.
