### ISSUE TITLE
Office 365 integration

### ISSUE THREAD

**Issue by BullGR** [MicrosoftDocs/dynamics365smb-devitpro-pb#418]
Hello, can the product integrate with Word/Excel under an Office 365 E1 subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00cf2c71-76d2-87c8-38ca-60ea7a422b14
* Version Independent ID: e11a6a76-d4b9-6b8e-e542-7a415aa2436a
* Content: [System Requirements for Microsoft Dynamics NAV 2017 - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/system-requirements-for-microsoft-dynamics-nav-2017)
* Content Source: [dynamics-nav/System-Requirements-for-Microsoft-Dynamics-NAV-2017.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/System-Requirements-for-Microsoft-Dynamics-NAV-2017.md)
* Product: **dynamics-nav-2017**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi BullGR,
Thank you for your feedback! Since it's about the product, you might want to ask the question in the Community here: https://community.dynamics.com/business/
That said, I would think the integration does not depend on the exact Office 365 subscription.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue in the doc repo. Thanks.
