### ISSUE TITLE
I would like an example

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-devitpro-pb#419]
I would like an example of a valid OptionCaption that includes a blank value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5f9766-4418-5211-fd53-02211b219cca
* Version Independent ID: 7e39317c-3679-9732-8064-e55e029e7bcf
* Content: [OptionCaption Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-optioncaption-property)
* Content Source: [dev-itpro/developer/properties/devenv-optioncaption-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-optioncaption-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by epernst** [comment]
Example:
OptionCaption = 'Value1,Value2,Value3'; (matching OptionMembers = Value1,Value2,Value3;)
Example with blank:
OptionCaption = ' ,Value2,Value3'; (matching OptionMembers = " ",Value2,Value3;)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback; the topic will be updated with the next doc refresh.
