### ISSUE TITLE
Install Codeunit syntax is incorrect

### ISSUE THREAD

**Issue by danielrodgers** [MicrosoftDocs/dynamics365smb-devitpro-pb#42]
The example syntax under the title "Install codeunit syntax" is incorrect and differs from the (correct) full example provided

procedure OnInstallAppPerCompany()
procedure OnInstallAppPerDatabase()

Should be
trigger OnInstallAppPerCompany()
trigger OnInstallAppPerDatabase()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dd7c9e-51a5-eeea-a2f6-dd4d40b93295
* Version Independent ID: d6fb1d1b-fa2e-606e-6c79-115651b60a29
* Content: [Writing extensions installation code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-install-code)
* Content Source: [dev-itpro/developer/devenv-extension-install-code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-install-code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The issue has been fixed and the updated article will be published soon.
