### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by zakisaad** [MicrosoftDocs/dynamics365smb-devitpro-pb#420]
&gt; Is a container for any well-formed JSON object. A default JsonasdasdaObject contains an empty JSON object.

Looks like JsonObject is spelt "JsonasdasdaObject" on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6254d9e0-d1d8-c945-0acb-3fd178506ac4
* Version Independent ID: a42e3814-18be-ffeb-72cc-9952a781c7c6
* Content: [JsonObject Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonobject/jsonobject-data-type)
* Content Source: [dev-itpro/developer/methods-auto/jsonobject/jsonobject-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/jsonobject/jsonobject-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your input, this is now fixed.
