### ISSUE TITLE
Include in See Also

### ISSUE THREAD

**Issue by maveca** [MicrosoftDocs/dynamics365smb-devitpro-pb#421]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-notifications-developing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d61fd2a-1721-5e6c-267f-3fbf5823af90
* Version Independent ID: aa53e3c4-ab3b-4266-3a98-8b50745ddf33
* Content: [Notification Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/notification/notification-data-type)
* Content Source: [dev-itpro/developer/methods-auto/notification/notification-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/notification/notification-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, the link has been added to the article. An update will be published soon. Thanks for the feedback!
