### ISSUE TITLE
Is AllowedFrameAncestors still a valid key?

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#422]
When using the AllowedFrameAncestors key, then we are getting this error:
MessageWithoutPrivateInformation: The configuration setting 'AllowedFrameAncestors' is not valid for Microsoft Dynamics 365 Business Central Server.

We are on BC 13.3.27233 - on-premise and connecting to D365 f. Sales Cloud.
Ref: https://dynamicsuser.net/nav/f/technical/96484/allowedframeancestors-is-not-valid-for-business-central-server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a37d8a7-4a5a-37c8-df1c-4dd28e37c360
* Version Independent ID: badd39bf-9d13-e0d4-0138-8cd9920b3a9f
* Content: [Configuring Business Central Web Server instance - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-web-server)
* Content Source: [dev-itpro/administration/configure-web-server.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configure-web-server.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by lukzog** [comment]
Do you have any other installation of BusinessCentral/NAV on you machine?
It looks like the Set-NAVWebServerInstanceConfiguration points to an old version of the script module.

Could you run following command to verify it?

Get-Command Set-NAVWebServerInstanceConfiguration | % Source

**Comment by epernst** [comment]
Hi,
No this is the only version installed. The machine was created using getbc/aka.ms.
Running the Get-Command returns: Microsoft.Dynamics.Nav.Management 

The Microsoft.Dynamics.Nav.Management.dll is version 13.0.27183.0 (app version 13.3.27233.0-W1).

**Comment by lukzog** [comment]
I just requested new instance, and started navsserver powershell.

```powershell
PS` C:\run> Get-NAVWebServerInstance

WebServerInstance            : NAV
Website                      : NavWebApplicationContainer
Uri                          : https://NAVSERVER:443/NAV
SiteDeploymentType           : SubSite
Configuration File           : C:\inetpub\wwwroot\NAV\navsettings.json
ClientServicesPort           : 7046
ClientServicesCredentialType : NavUserPassword
DnsIdentity                  :
Server                       : localhost
ServerInstance               : NAV
Version                      : 13.0.28871.0
```
Running Set-NAVWebServerInstanceConfiguration worked without any error
```powershell
PS C:\run> Set-NAVWebServerInstanceConfiguration -KeyName "AllowedFrameAncestors" -WebServerInstance NAV -KeyValue "http
s:*.crm4.dynamics.com"
```
I also could verify that the setting was set
```powershell
PS C:\run> Get-Content C:\inetpub\wwwroot\NAV\navsettings.json | ConvertFrom-Json | % NAVWebSettings | % AllowedFrameAncestors
https:*.crm4.dynamics.com
```

**Comment by epernst** [comment]
Looks fine, but exactly what worked fine?
I can do exactly what you showed there. No problem setting and showing that it's set using the CmdLet's (I wrote that in the message to support also).  I only got the above error message once, cannot provoke the error message.
The issue is that it doesn't work. When we try to open an iframe, then it's being denied. 
Here is what the console says:
Header X-Frame-Options found.
The header is set to SAMEORIGIN. You are on a different domain and therefore this page can NOT be included.

**Comment by lukzog** [comment]
Can you share the network log (e.g. using Fiddler)? The host frame should send the ancestor url in a header to BC ('origin' header). The value of this header will then be validated against AllowedFrameAncestors.

**Comment by epernst** [comment]
Not quite sure if this is what you mean?

It looks like it is creating 2 call, but no "origin"
1.
_GET https://VmOnAzure.westeurope.cloudapp.azure.com/NAV/?company=CRONUS%20International%20Ltd.&page=4&showribbon=0&shownavigation=0&showuiparts=0 HTTP/1.1
Host: VmOnAzure.westeurope.cloudapp.azure.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: https://bh-crm-dbc.crm4.dynamics.com/main.aspx?appid=08ac32bd-5828-e911-a82b-000d3ab24119&pagetype=entityrecord&etn=opportunity&id=d384d9fc-1d29-e911-a826-000d3ab244fc
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: SessionId=l22h3viqiyn0vayi3gydinzf; .AspNetCore.Cookies=CfDJ8J4UPWMFsdlClyAl8PV2dBPlofgoTU2dKozttoDnBSwhVdo0hzIJyT78kI_F2PH_pXJ1iq5w6cpiKDa-IyMb5bkcwRmUmlJumEa3mCkMCFrn9vn_mlshgCRSP0EU2Fth0Hu93QQr1OIKubZqmcDN-z1pcTk_Ht4l9YMFqhiWCdObsUmoj4AOFvxx1XsmsblBKcKkPL2NOS39uOreZZJ3_mKH6LU_mD5ej4ZX89k4qNgdYiDNGvQ0PRBwrw2BK-MOVlyDWAj6XCf57aMOui-U-M2f-9_pmbh1iIvGbxkHeFtEx4BSTCHJe40l9SgPlqQqRw_

2.
_GET https://VmOnAzure.westeurope.cloudapp.azure.com/NAV/?company=CRONUS%20International%20Ltd.&page=4&showribbon=0&shownavigation=0&showuiparts=0&runinframe=1 HTTP/1.1
Host: VmOnAzure.westeurope.cloudapp.azure.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: https://VmOnAzure.westeurope.cloudapp.azure.com/NAV/?company=CRONUS%20International%20Ltd.&page=4&showribbon=0&shownavigation=0&showuiparts=0
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: SessionId=l22h3viqiyn0vayi3gydinzf; .AspNetCore.Cookies=CfDJ8J4UPWMFsdlClyAl8PV2dBPlofgoTU2dKozttoDnBSwhVdo0hzIJyT78kI_F2PH_pXJ1iq5w6cpiKDa-IyMb5bkcwRmUmlJumEa3mCkMCFrn9vn_mlshgCRSP0EU2Fth0Hu93QQr1OIKubZqmcDN-z1pcTk_Ht4l9YMFqhiWCdObsUmoj4AOFvxx1XsmsblBKcKkPL2NOS39uOreZZJ3_mKH6LU_mD5ej4ZX89k4qNgdYiDNGvQ0PRBwrw2BK-MOVlyDWAj6XCf57aMOui-U-M2f-9_pmbh1iIvGbxkHeFtEx4BSTCHJe40l9SgPlqQqRw_

**Comment by lukzog** [comment]
Sorry it is 'referer' header not 'origin' header.
From the requests you send I can see that the 'Referer' is set correctly and it should be allowed if AllowedFrameAncestors is set to 'https:*.crm4.dynamics.com'

Is the X-Frame-Options/CSP set to origin/self on the response to "https://VmOnAzure.westeurope.cloudapp.azure.com/NAV/?company=CRONUS%20International%20Ltd.&page=4&showribbon=0&shownavigation=0&showuiparts=0" ?

**Comment by epernst** [comment]
Hi Lukasz,
While looking for the answer to your question, we discovered different behavior when called the first time and when we connect a second time. It appears that the frame-ancestor is used to login first time, and then save a cookie that is used the second time.

I have uploaded the fiddler traces etc. to support.microsoft.com.

**Comment by lukzog** [comment]
I think we found the issue. As part of initial response from BC we set 'AllowedAncestorCookie' with the parent ancestor url. We do that to keep track of the allowed ancestor in case the page is redirected e.g. to authenticate with AAD. Regrettably, AllowedAncestorCookie is not respected by the browser because it is marked with samesite=lax property. This property prevent it from being used in cross site requests.

We will provide a fix by removing the samesite property on AllowedAncestorCookie in the next update.

**Comment by epernst** [comment]
Thanks, is there any work-arounds that we can try until the next update is released?

**Comment by lukzog** [comment]
The workaround could be adding a rewrite rule that removes samesite=lax.

Try adding following rule to the web.config under rewrite/rules
```xml
<outboundRules>
    <rule name="Remove SameSite">
        <match serverVariable="RESPONSE_Set_Cookie" pattern="NAVAllowedAncestor(.+)samesite\=lax\;(.+)" />
        <action type="Rewrite" value="NAVAllowedAncestor{R:1}{R:2}" />
    </rule>
</outboundRules>
```

**Comment by epernst** [comment]
Thanks, just tried out the work around, and it works! 👍
