### ISSUE TITLE
PDF documents in other languages

### ISSUE THREAD

**Issue by LaurensN** [MicrosoftDocs/dynamics365smb-devitpro-pb#424]
Via the UI it is possible to download/send PDF's in other languages. Is it possible to download these also via this route?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305b0fca-6add-c9c8-51ef-1ea23415bbfb
* Version Independent ID: 8498d176-9a71-d879-9122-3fb457ca7b14
* Content: [Get pdfDocument - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_salesquote_pdfdocument)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_salesquote_pdfdocument.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_salesquote_pdfdocument.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by Mr-Pingu** [comment]
Is there any news on this?

**Comment by Mr-Pingu** [comment]
Got an answer.

you need to specificy in the header:
Accept-Language: nl-NL

**Comment by LaurensN** [comment]
This works, would be great if the documentation could be updated to include this information.

**Comment by SusanneWindfeldPedersen** [comment]
Hello all, thanks for your patience. We have just pushed a doc update live with this information. Thanks!
