### ISSUE TITLE
Order for all types

### ISSUE THREAD

**Issue by tinfister** [MicrosoftDocs/dynamics365smb-devitpro-pb#425]
Can you please list order for all variable types?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b5ddc84-66fc-dac7-2473-efbd8abc4ba7
* Version Independent ID: d30b3aa4-da57-3c42-d22b-035d45cdbc71
* Content: [Variable declarations should be ordered by type. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0021-variabledeclarationsshouldbeorderedbytype)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0021-variabledeclarationsshouldbeorderedbytype.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0021-variabledeclarationsshouldbeorderedbytype.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This is auto-generated from the code, so I have filed a product bug/enhancement on this. Thanks.
