### ISSUE TITLE
Example of Adding Onvalidate code to an existing field in a table extension object

### ISSUE THREAD

**Issue by wolterOnEntocare** [MicrosoftDocs/dynamics365smb-devitpro-pb#426]
Suppose I am writing an table extension for the SalesHeader table.
The SalesHeader table already has a CustomerID field, so I am not going to add that field.
But I DO want to add code to the OnValidate event of that field.
People say it's possible. But I cannot find any explanation on how to do it.

There are examples of adding an OnValidate trigger to a new field.
But how to do it for an existing field?
E.g. how to find out the fields existing object ID number? Or its name?
An example for beginners!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7ad6e4-99c3-cf83-c355-62b23b4ec701
* Version Independent ID: 7a43567c-af65-6e50-4076-4945e2606863
* Content: [OnValidate (Fields) Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onvalidate-fields-trigger)
* Content Source: [dev-itpro/developer/triggers/devenv-onvalidate-fields-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onvalidate-fields-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by Hornsyld** [comment]
```
tableextension 50000 SalesHeaderExt extends "Sales Header" //Table 36
{
    fields
    {
        //New field
        field(50000; NewField; Text[100])
        {
            trigger OnValidate()
            begin
                Message('Validating NewField ');
            end;
        }

        //Existing field
        modify("Sell-to Customer Name")
        {
            trigger OnAfterValidate()
            begin
               Message('New Sell-to Customer Name is ' + "Sell-to Customer Name");
            end;
        }
    }
}
```

**Comment by wolterOnEntocare** [comment]
That's the extra information I need!
Could not find 'OnAfterValidate' on this page:
     https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-table-and-field-triggers
It should be there, should it?

**Comment by blrobl** [comment]
Hi, thanks for your feedback . Documentation for the OnBeforeValidate() and OnAfterValidate() triggers has been added, with their corresponding examples, as well as an example of OnValidate(). This will be available in the next doc refresh.

**Comment by GailBowen** [comment]
Thank you - the modify code above solved my problem.
