### ISSUE TITLE
Too lean

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#427]
A developer coming to this page to find out how to use SETSELECTIONFILTER will only find the correct syntax. Which is helpful, but this page sheds no light whatever on how the function is used, what it actually does, when and where it can or can't be used, or any useful examples. Which is what a developer would come to this page for. This page was not useful to me as a developer in its present form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae962bbb-a44c-ee63-d27e-963741ca37c3
* Version Independent ID: 7a7f0756-72c0-f4e3-0034-d9a6067d9594
* Content: [SetSelectionFilter Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/requestpage/requestpage-setselectionfilter-method)
* Content Source: [dev-itpro/developer/methods-auto/requestpage/requestpage-setselectionfilter-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/requestpage/requestpage-setselectionfilter-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your input - yes, I agree - this topic lacks detail. In fact, the version in the [Dynamics NAV library](https://docs.microsoft.com/en-us/dynamics-nav/setselectionfilter-function) has more detail, which we will port over as a start.

**Comment by buzzwick** [comment]
Indeed it does provide more detail. Thank you very much!
