### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#428]
It would be helpful if there were an example of how the RequestPage object is addressed in the context of running a report--or from within a report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca4e8897-904a-365c-184b-3ce5dad80524
* Version Independent ID: a208870a-6a0c-c0bd-150f-521a701c70ed
* Content: [RequestPage Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/requestpage/requestpage-data-type)
* Content Source: [dev-itpro/developer/methods-auto/requestpage/requestpage-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/requestpage/requestpage-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, you're right - this topic doesn't describe that. We do, however, have a topic on the report object with a bit more info on the context of the request page object - you can see it here: [Report Object](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-object). Don't know if that helps a bit? We have the entire reporting story in our backlog, and would really like to update these docs in a near future. Thanks.

**Comment by buzzwick** [comment]
Susanne,
Very helpful, actually.  At least there is an example of the code. The two pages should probably include each other in their See Also lists, while we are at it. Thank you!
