### ISSUE TITLE
MyTimeVariable = 0800T; returns error

### ISSUE THREAD

**Issue by tinfister** [MicrosoftDocs/dynamics365smb-devitpro-pb#429]
I guess the documentation could be better, because you are supposed to type hours minutes and seconds.
When I type MyTimeVariable = 080000T it is fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08da475c-0713-23d5-29f7-02485deb07c6
* Version Independent ID: ea0a5d33-e7ba-2527-9c8c-60de9dcbeaf0
* Content: [Time Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/time/time-data-type)
* Content Source: [dev-itpro/developer/methods-auto/time/time-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/time/time-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The topic does not contradict your statement, does it? Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for finding and reporting this - you're right; time must be specified as hours, minutes, and seconds. This topic will be updated with the next doc refresh. Thanks.

**Comment by tinfister** [comment]
I was just trying to point out that you should write hhmmssT not just hhmmT
like in some examples.

At least for me, its not working when I write just hhmmT
[image: image.png]

Lijep pozdrav
Tin Fišter

e-mail: tinfister@gmail.com
mob: +385989182699
skype: tinfister



pon, 11. ožu 2019. u 14:20 Susanne Windfeld Pedersen <
notifications@github.com> napisao je:
