### ISSUE TITLE
Task 3 Comment about Extension Type is misleading

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#43]
This command is supposed to be run on the "old" version of the database (so NAV 2017 or earlier).  First, extensions were only available in NAV 2016 and NAV 2017 so there should be a note about what version this task applies to.  

Second the comment "In the table that appears, V1 extensions are indicated by CSIDE in the Extension Type column." is confusing because the command, at least for NAV 2017 RTM, does not return any information about Extension Type as there was only one extension type before NAV 2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec2bde3-7aa2-0d9b-2d60-0fc57aa85645
* Version Independent ID: c37bcc83-3482-b533-8e9a-8feb56a6b88e
* Content: [Upgrading the Database - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/upgrading-the-data)
* Content Source: [dynamics-nav/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Upgrading-the-Data.md)
* Service: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback. The issues have been fixed and will be available soon.
