### ISSUE TITLE
Current Build - Developing for Dynamics 365 Business Central Link Broken

### ISSUE THREAD

**Issue by spiritsip** [MicrosoftDocs/dynamics365smb-devitpro-pb#431]
The link to "Current Build - Developing for Dynamics 365 Business Central" link (https://partner.microsoft.com/en-us/dashboard/collaborate/packages/4756) appears to be broken. Following the link just takes me to the dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936119a1-4f7e-ed69-f72e-44e41464f964
* Version Independent ID: c30741c6-9408-775a-5ce0-3f6986445447
* Content: [Testing your Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-testingyourextension)
* Content Source: [dev-itpro/compliance/apptest-testingyourextension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-testingyourextension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. I have updated the doc to instead say that you need to log into Collaborate, then under packages find the **Current Build - Developing for Dynamics 365 Business Central** link. Topic will be updated with the next refresh. Thanks!
