### ISSUE TITLE
Small text change to SQL link

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#432]
Text 
"For more information, see Hardware and Software Requirements for Installing SQL Server 2016. "
should just be
"For more information, see Hardware and Software Requirements for Installing SQL Server."

Link is correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b0aa47-5276-2fd9-173f-f05adcd420c2
* Version Independent ID: fb89206b-f5c1-6f2c-1f83-899c02aa8e89
* Content: [System Requirements for Business Central 2018 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central#feedback)
* Content Source: [dev-itpro/deployment/system-requirement-business-central.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/system-requirement-business-central.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Fixed, thanks for the feedback!
