### ISSUE TITLE
Replace "Dynamics NAV" with "Dynamics 365 Business Central"

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#435]
Suggestion: Replace "Dynamics NAV" with "Dynamics 365 Business Central" on that page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b0aa47-5276-2fd9-173f-f05adcd420c2
* Version Independent ID: fb89206b-f5c1-6f2c-1f83-899c02aa8e89
* Content: [System Requirements for Business Central 2018 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central#feedback)
* Content Source: [dev-itpro/deployment/system-requirement-business-central.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/system-requirement-business-central.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! Incorrect references to NAV have been fixed. Not all reference have been removed because the Windows and CSIDE are still branded as NAV. The updated article will be published soon.

**Comment by DanielGoehler** [comment]
Hi @jswymer,

regarding "[Microsoft Dynamics 365 for Sales Integration Requirements](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central#CRM)": If you using Business Central, do you still need to take the DynamicsNAVIntegrationSolution.zip from the **Dynamics NAV 2016 installation media (DVD)** as stated in the text or could also take this from the Business Central DVD?
