### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by GailBowen** [MicrosoftDocs/dynamics365smb-devitpro-pb#438]
This is wrong:
 
Customer.SETASCENDING(City,Descending);  

It should be: 
Customer.SETASCENDING(City,false);  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ff10faa-77b4-0eef-d6e9-6db31e120638
* Version Independent ID: 257c1e54-8968-f85c-e6f3-789f7f2d4a13
* Content: [SETASCENDING Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/setascending-function--record-#feedback)
* Content Source: [dynamics-nav/SETASCENDING-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SETASCENDING-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - this is fixed with the next refresh of the docs. Thanks!
