### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by mdmagahis** [MicrosoftDocs/dynamics365smb-devitpro-pb#44]
There is a small grammar error in the bullet point, "If no keys can be found that include the field(s) that you specify and sorting on a given field(s) cannot be set, then an runtime error occurs unless you test the Boolean value of SetCurrentKey in your code." 

 The sentence should be, "... field(s) cannot be set, then a runtime error occurs unless you test..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e176d7-aca3-6ef2-46de-27cfa794de32
* Version Independent ID: 356f40be-0f06-d10f-2b4f-af8557ce9ca8
* Content: [SetCurrentKey Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/setcurrentkey-function--record-)
* Content Source: [dynamics-nav/SETCURRENTKEY-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SETCURRENTKEY-Function--Record-.md)
* Service: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback. The issue has been fixed and will be available soon.
