### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#441]
Example: 
setspn -A BCSERVER/BC130.corp:7046 corp\bcdomainuser  
Should be:
setspn -A BC130/BCSERVER.corp:7046 corp\bcdomainuser  

And further down it says:
select Microsoft Dynamics NAV 2017 Web client. Should be changed to Business Central.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9871474-165d-c6bf-93f8-e11ea14c6596
* Version Independent ID: a881c98f-927d-f458-7e42-e9380404da6f
* Content: [Configure Web Client Delegation - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/configure-delegation-web-server)
* Content Source: [dev-itpro/deployment/configure-delegation-web-server.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/configure-delegation-web-server.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The issues have been fixed and an update will be published soon.
