### ISSUE TITLE
Wrong link to GetURL

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#442]
Link to GetURL is currently:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-geturl-method

That page does not exist. 

Instead this page works
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-geturl-clienttype-string-objecttype-integer-recordref-boolean-method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88aa7e3-9b56-f8ef-b63d-c31b7098539a
* Version Independent ID: fb3c85ff-43fa-d496-6ef2-fdad0a24e23d
* Content: [SOAP and ODATA Web Services - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/web-services)
* Content Source: [dev-itpro/webservices/web-services.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/web-services.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, the topic contained an old link. This is fixed with the next refresh of the docs. Thanks.
