### ISSUE TITLE
Is there any way to remove or disable a standard action?

### ISSUE THREAD

**Issue by DaniStark14** [MicrosoftDocs/dynamics365smb-devitpro-pb#443]
Hi!
Does it support to remove or disable a standard action like Statistics?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62a7769-3446-41f2-3d06-8c9cc95b95c5
* Version Independent ID: fd778e60-c4bc-4696-ac55-3cf292329d0a
* Content: [Adding Actions to a Page - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-actions-to-a-page#feedback)
* Content Source: [dev-itpro/developer/devenv-adding-actions-to-a-page.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-actions-to-a-page.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. No, you do not have that option for a page extension. You're able to set it to visible = false, though. Thanks.

**Comment by DaniStark14** [comment]
Thanks for your answer. Now my question is how to set the property visible = false to a standard action, not for a new one created by me.

**Comment by SusanneWindfeldPedersen** [comment]
Hi, you would create a page extension that modifies the standard page action, like this:

pageextension 50100 CustomerListExt extends "Customer List"
{
    layout
    {
        modify(CustomerStatisticsFactBox)
        {
            Visible = false;
        }
..........

I will update the docs to include that information also - this will be done with the next refresh. Thanks for your input.

**Comment by DaniStark14** [comment]
Thank you again! Finally I solved my problem.
