### ISSUE TITLE
Example 3 incomplete

### ISSUE THREAD

**Issue by KristofKlein** [MicrosoftDocs/dynamics365smb-devitpro-pb#444]
Hi,

you may have noticed the missing try { 

on top of this I would also like to give an example 4 that uses the try block in a foreach file loop

Get-ChildItem "C:\BC_OBJ\" | 
Foreach-Object {
   $Filename = $_.Name 
   try {
        Test-NAVApplicationObjectLanguage -Source $_.FullName -LanguageId DEU -ErrorAction Stop
    }   
    catch
    {
        Write-Host 'Failed to find DEU in File' $Filename -ForegroundColor Red
    }
}

Best regards
Kristof

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59fc4afe-27b5-da34-622a-79ec85c24325
* Version Independent ID: 0a82d2d1-2fc9-a7d7-5a97-d69124b4f5dc
* Content: [Test-NAVApplicationObjectLanguage (Microsoft.Dynamics.Nav.Model.Tools)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.model.tools/test-navapplicationobjectlanguage?view=businesscentral-ps#feedback)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Model.Tools/Test-NAVApplicationObjectLanguage.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Model.Tools/Test-NAVApplicationObjectLanguage.md)

**Comment by blrobl** [comment]
Hi, thanks for pointing this out. This will appear as fixed in the next doc refresh.
