### ISSUE TITLE
Please add examples of using NAVAPP.RESTOREARCHIVEDATA

### ISSUE THREAD

**Issue by magpet01** [MicrosoftDocs/dynamics365smb-devitpro-pb#445]
Please add examples of using NAVAPP.RESTOREARCHIVEDATA

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: c6dd7c9e-51a5-eeea-a2f6-dd4d40b93295
* Version Independent ID: d6fb1d1b-fa2e-606e-6c79-115651b60a29
* Content: [Writing extensions installation code - Business Central](https://docs.microsoft.com/sv-se/dynamics365/business-central/dev-itpro/developer/devenv-extension-install-code#feedback)
* Content Source: [dev-itpro/developer/devenv-extension-install-code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-install-code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The RestorAchiveData method is meant for extension upgrade code, and hence it has been added to the [Upgrading Extensions](https://docs.microsoft.com/sv-se/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions) example. It will be available in the next doc refresh.
