### ISSUE TITLE
EXAMPLE 3 Issues

### ISSUE THREAD

**Issue by KristofKlein** [MicrosoftDocs/dynamics365smb-devitpro-pb#446]
Hi,

example 3 should say: 
'Page','Codeunit','Table','XMLport','Report','Query' | % { Compile-NAVApplicationObject -DatabaseName MyApp -Filter "Type=$_" -AsJob } | Receive-Job -Wait

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6fd8a12-b14c-ae47-51df-072f67b4bab1
* Version Independent ID: 43268fed-f5b1-a98d-0f65-e9fecd4bb975
* Content: [Compile-NAVApplicationObject (Microsoft.Dynamics.Nav.Ide)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.ide/compile-navapplicationobject?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Ide/Compile-NAVApplicationObject.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Ide/Compile-NAVApplicationObject.md)

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The -DatabaseName argument has been fixed and the Query suggestion has been included in the example (but note it is not necessary). It will available in the next doc refresh.
