### ISSUE TITLE
Ports and different variants

### ISSUE THREAD

**Issue by eclipses24** [MicrosoftDocs/dynamics365smb-devitpro-pb#447]
Hi, speaking by personal experience with Customers, I would add in the samples the ports numbers and specify that it will work only with the exact hostname as written, for example if the customer internally connect just using servername rather than the full host both version should be declared:
"AllowedFrameAncestors":  "https://servername.domain.com:2433,https://servername:2433",  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e4a174f-78d5-338d-5233-c605c181d222
* Version Independent ID: 03e2249a-d165-1fab-34ed-7fe2dc7792b4
* Content: [Embed the Web Client Pages - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/embedding-microsoft-dynamics-nav-web-client-pages-in-other-websites#feedback)
* Content Source: [dynamics-nav/Embedding-Microsoft-Dynamics-NAV-Web-Client-Pages-in-Other-Websites.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Embedding-Microsoft-Dynamics-NAV-Web-Client-Pages-in-Other-Websites.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset.
