### ISSUE TITLE
Spelling error in syntax example

### ISSUE THREAD

**Issue by davidsb30** [MicrosoftDocs/dynamics365smb-devitpro-pb#448]
String := TestPage.Part.Fiter.GETFILTER(Field);  should be String := TestPage.Part.Filter.GETFILTER(Field);  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3da798f-335c-af5c-d8d3-122fea7cb251
* Version Independent ID: 503d222e-4cdb-a361-86d4-d992645e6536
* Content: [GETFILTER Function (TestPage Filter) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/getfilter-function--testpage-filter-#feedback)
* Content Source: [dynamics-nav/GETFILTER-Function--TestPage-Filter-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/GETFILTER-Function--TestPage-Filter-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - it's fixed in the next refresh of the docs.
