### ISSUE TITLE
See also: Upgrading to Dynamics NAV?

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#449]
Title in See Also says "Upgrading to Microsoft Dynamics NAV" but page is called "Upgrading to Dynamics 365 Business Central".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dde0890-47c3-1cfb-761b-321fe39f9e21
* Version Independent ID: de7dad4e-83a0-4a02-8caa-bde1187396c4
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data-multitenant)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data-Multitenant.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data-Multitenant.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The link text has been fixed and the update will be published soon.
