### ISSUE TITLE
ListPage

### ISSUE THREAD

**Issue by pungggi** [MicrosoftDocs/dynamics365smb-devitpro-pb#45]
It does not seem to apply to ListPages, this would be a nice addition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c40fcac6-97a5-2b0f-b5a3-bf5815a1c0a1
* Version Independent ID: c02b891a-fc05-9f98-004a-894e968f4efb
* Content: [QuickEntry Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/quickentry-property)
* Content Source: [dynamics-nav/QuickEntry-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/QuickEntry-Property.md)
* Service: **unspecified**
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback.

The QuickEntry property should work on lists in the Windows client. However, it is ignored on lists in the Web client. What client were you using? 

I have updated the article to include the Web client limitations. It will be available soon.

Thanks again
