### ISSUE TITLE
Adding Duration to date time

### ISSUE THREAD

**Issue by gwaindepy** [MicrosoftDocs/dynamics365smb-devitpro-pb#450]
Wow. This post helped me a lot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b3b396-df68-228f-3a76-249d5ba43d95
* Version Independent ID: 66e08fab-0ff3-c5ac-3263-0baff79a1229
* Content: [ROUNDDATETIME Function (DateTime) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/rounddatetime-function--datetime-#feedback)
* Content Source: [dynamics-nav/ROUNDDATETIME-Function--DateTime-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/ROUNDDATETIME-Function--DateTime-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback.
