### ISSUE TITLE
Designer doesn't seems to be working 

### ISSUE THREAD

**Issue by Dilli** [MicrosoftDocs/dynamics365smb-devitpro-pb#451]
Designer 'drag and drop' does it seems to be working in chrome, also you could specify minimum supported browser version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc13a127-253d-6438-52ed-319589d8d3ec
* Version Independent ID: 9bcc413c-55cb-a0e0-8ca2-f111658076fe
* Content: [Building your first sample extension that uses new objects and extension objects - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-example#feedback)
* Content Source: [dev-itpro/developer/devenv-extension-example.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-example.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. System requirements can be found [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central). If you cannot make the Designer drag and drop work, please file a product bug using your usual support mechanism. Thanks.
