### ISSUE TITLE
Same description for PteCop and UiCop

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#452]
Currently you describe PteCop and UiCop as doing the same!

AppSourceCop is an analyzer that enforces rules that must be respected by extensions meant to be published to Microsoft AppSource. For more information about the AppSourceCop rules, see AppSourceCop Analyzer Rules.
UserInterfaceCop is an analyzer that enforces rules that must be respected by extensions meant to be installed for individual tenants. For more information about the UserInterfaceCop rules, see UICop Analyzer Rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a5b68ec-d706-ab10-8cb9-22e8d98c3494
* Version Independent ID: 3da84c14-159f-3ac7-ee94-5e0faff222d8
* Content: [Using the Code Analysis Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool)
* Content Source: [dev-itpro/developer/devenv-using-code-analysis-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-using-code-analysis-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, the UserInterfaceCop analyzer description will be fixed with the next doc refresh.
