### ISSUE TITLE
PATCH or POST?

### ISSUE THREAD

**Issue by mikewiese** [MicrosoftDocs/dynamics365smb-devitpro-pb#453]
This documentation mentions both PATCH and POST - which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adaa2694-dbeb-c601-fb7f-a3f58b426cae
* Version Independent ID: d3fd7f4e-2494-dd69-4406-06b0ff60d3e8
* Content: [Update subscription - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_subscription_update)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_subscription_update.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_subscription_update.md)
* Service: **dynamics365-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen, henrikwh**

**Comment by SusanneWindfeldPedersen** [comment]
It's PATCH - thanks for reporting this - doc will be updated with the next refresh. Thanks.
