### ISSUE TITLE
DELETE fails: "Bad Request - Error in query syntax."

### ISSUE THREAD

**Issue by mikewiese** [MicrosoftDocs/dynamics365smb-devitpro-pb#454]
The DELETE request documented here does not work. It returns a 401 Unauthorised.

You should update your documentation to specify that you need to include the tenant ID in the URL. For example to create a subscription you need to POST to 
https://api.businesscentral.dynamics.com/v1.0/{{tenantid}}/api/beta/subscriptions

However, even if you send a DELETE request that augments your documented URL in this way, to make it consistent with a working POST request, i.e. 
DELETE https://api.businesscentral.dynamics.com/v1.0/{{tenantid}}/api/beta/subscriptions(d2b67037a7bb4c1682174612519254d7)

it still fails, returning a 404 with the message "Bad Request - Error in query syntax."

This is observed using Postman, with basic authentication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2094a025-eb09-9ae4-117a-c0b011c21f33
* Version Independent ID: 7f32e6ab-62f1-4ca2-ab8c-3a22d0d4ddf3
* Content: [Delete subscription - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_subscription_delete)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_subscription_delete.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_subscription_delete.md)
* Service: **dynamics365-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen, henrikwh**

**Comment by SusanneWindfeldPedersen** [comment]
This should be fixed by now. Thanks.
