### ISSUE TITLE
Link named "Transparent Data Encryption" should be called "Data Encryption at Rest"

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#455]
Transparent Data Encryption page was renamed to Data Encryption at Rest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 419ca4ec-637d-337d-afd8-a6bc2c4ceae5
* Version Independent ID: 523cc4f6-21da-da47-8d1a-e53381ba2598
* Content: [User Security in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/security/security-onpremises)
* Content Source: [dev-itpro/security/security-onpremises.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/security/security-onpremises.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, this is fixed with the next doc refresh.
