### ISSUE TITLE
example please

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#456]
please provide a few examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e3e1532-e5f6-a9d6-5939-9a22e063ea3a
* Version Independent ID: 41bcfab0-1341-dc2f-29e5-1e4962676054
* Content: [Setting Relationships Between Tables - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-set-relationships-between-tables)
* Content Source: [dev-itpro/developer/devenv-set-relationships-between-tables.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-set-relationships-between-tables.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This topic will be updated with the spring release refresh including an example. For the Developer Preview, February we announced how you can now "extend" TableRelations, and it includes a few examples. Please find the blog post [here](https://community.dynamics.com/business/b/businesscentraldevitpro/archive/2019/02/26/developer-preview-february-2019).
