### ISSUE TITLE
Minor grammar fix

### ISSUE THREAD

**Issue by louiskody** [MicrosoftDocs/dynamics365smb-devitpro-pb#457]
[Enter feedback here]
Under the Deployment Scenarios header, the description of the Two-computer scenario needs revision:

As Is:
Two-computer | Installs the Business Central Web Server components one computer and the Business Central Server and the SQL Server database components.

Change to:
Two-computer | Installs the Business Central Web Server components **on** one computer and the Business Central Server and the SQL Server database components **on another**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a875b48-aeb1-a11b-8a35-58d4c4a9f3e0
* Version Independent ID: ec0f7628-1c5c-f94e-7340-ad3461c21fec
* Content: [Web Server Components Deployment Scenarios - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/deployment-scenarios#feedback)
* Content Source: [dev-itpro/deployment/deployment-scenarios.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/deployment-scenarios.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, it will be fixed with the next doc refresh.
