### ISSUE TITLE
Variables not use in the code

### ISSUE THREAD

**Issue by TweetImrank** [MicrosoftDocs/dynamics365smb-devitpro-pb#458]
Variables TestFile and NVOutStream are not used in the code of codeunit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3498c75c-becd-6b9c-ae23-1638bf2fbe47
* Version Independent ID: 089e177c-4f14-a2ed-5559-fc1aa57efaa7
* Content: [Walkthrough: Uploading a File from a Client to Microsoft Dynamics NAV Server - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--uploading-a-file-from-a-client-to-microsoft-dynamics-nav-server#creating-the-codeunit)
* Content Source: [dynamics-nav/Walkthrough--Uploading-a-File-from-a-Client-to-Microsoft-Dynamics-NAV-Server.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Uploading-a-File-from-a-Client-to-Microsoft-Dynamics-NAV-Server.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for pointing that out. This will be fixed.
