### ISSUE TITLE
minor sample code misprint

### ISSUE THREAD

**Issue by louiskody** [MicrosoftDocs/dynamics365smb-devitpro-pb#459]
[Enter feedback here]
In the sample regarding ASSERTERROR (asterisks added for emphasis)
```
InvalidDate := 010184D;  
**InvalidDateErrorMessage** := Text001;  
ASSERTERROR CheckDate(InvalidDate);  
IF GETLASTERRORTEXT <> InvalidDateErrorMessage THEN  
  ERROR('Unexpected error: %1', GETLASTERRORTEXT);
```
> This example requires the following variables.
```
var
    InvalidDate : Date;
    **CusInvalidDateErrorMessage** : Text; 
    Text001 : TextConst 'The date is outside the valid date range.';
```
The var CusInvalidDateErrorMessage should be named InvalidDateErrorMessage to match the other sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff8af30e-3d81-30c3-44c8-fc4cb631d001
* Version Independent ID: 315c1531-77aa-c602-6c0b-41d160d791e2
* Content: [AL Simple Statements - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-simple-statements)
* Content Source: [dev-itpro/developer/devenv-al-simple-statements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-simple-statements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for reporting this - it's fixed with the next refresh of the docs.
