### ISSUE TITLE
When preview API would become GA?

### ISSUE THREAD

**Issue by ron-lee** [MicrosoftDocs/dynamics365smb-devitpro-pb#46]
Somehow I didn't find any related information on internet. Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a107ff90-611f-c6fc-539b-4ff061b868f5
* Version Independent ID: 4cd881b1-41bc-07b2-7be4-22ef360e267a
* Content: [API for Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/index#feedback)
* Content Source: [dynamics-nav/fin-graph/index.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/index.md)
* Service: **dynamics365-financials**
* Product: **unspecified**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, 
Thanks for your feedback, there were indeed two links in the reported topic that did not work. This has been fixed and will work when the docset is refreshed. In the meantime, for your reference, I am pasting in the links that the topic was supposed to link to: [Getting Started Developing Connect Apps for Dynamics 365 Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps) and [Development in AL](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-dev-overview). As for the question in the title of this feedback, I do not have any update. 
Thanks again for reporting this.
