### ISSUE TITLE
A little Typo maybe regarding "Filter on columns" - and missing "missing feature"

### ISSUE THREAD

**Issue by TheGreatBorg** [MicrosoftDocs/dynamics365smb-devitpro-pb#460]
You write that "Filter on column on FlowFields" is Not supported. But it is - you can make a filter on columns with calculated amounts. What is NOT supported and witch can be business crucial in the Web Client is filtering on fields not shown as a column (that's a very important feature in the Windows Client).	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b3a845-b388-9c69-478f-87cc70b87819
* Version Independent ID: af209cd5-e554-fe3f-30f0-05d771b21a17
* Content: [Feature Limitations of the Web Client - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/feature-limitations-of-the-microsoft-dynamics-nav-web-client#feedback)
* Content Source: [dynamics-nav/Feature-Limitations-of-the-Microsoft-Dynamics-NAV-Web-Client.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Feature-Limitations-of-the-Microsoft-Dynamics-NAV-Web-Client.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset.
