### ISSUE TITLE
Is there any chance we could configure Business Central on-premise to use OKTA for MFA ?

### ISSUE THREAD

**Issue by aconcato** [MicrosoftDocs/dynamics365smb-devitpro-pb#461]
Is there any chance we could configure Business Central on-premise to use OKTA for MFA ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c36d03-7f72-72d0-bbe1-d60f881a9e66
* Version Independent ID: c5775944-717d-d054-c016-a82a2efed79c
* Content: [Multi-Factor Authentication - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/security/multifactor-authentication)
* Content Source: [dev-itpro/security/multifactor-authentication.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/security/multifactor-authentication.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your question - please ask through your product/support channel. Thanks.
