### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#463]
Both these links are broken:
For more information, see CALCSUMS method (Record) and CALCFIELDS method (Record).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a8b439d-5e3b-4dfa-0c8b-7231d994e442
* Version Independent ID: d484f6f6-be68-6244-49a7-65bf3b8e6dcc
* Content: [Data Access - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/optimize-sql-data-access)
* Content Source: [dev-itpro/administration/optimize-sql-data-access.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/optimize-sql-data-access.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, these will be fixed with the next doc refresh.
