### ISSUE TITLE
Unclear what example shows

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#466]
"When you set the argument to true, the signature of event subscriber methods that subscribe to the published event automatically include a VAR parameter for the published event object, as shown in the following example:"

Where can I see the VAR param?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aa34e9b-6f95-c7b4-3993-bd1c89f58c94
* Version Independent ID: 85fca68e-caef-afc2-b7ed-70ceaa6f8b3d
* Content: [BusinessEvent Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-business-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-business-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-business-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback. The description of the example has been changed to bette explain this. The update will be publsihed soon.
