### ISSUE TITLE
example show nothing about using global variables or what IncludeSender means

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#467]
codeunit 50103 MySubscribingCodeunit2
{
    [EventSubscriber(ObjectType::Codeunit, Codeunit::MyPublishingCodeunit2, 'MyIntegrationEvent', '', true, true)]
    local procedure MySubscriber(sender: Codeunit MyPublishingCodeunit2; myGlobalVar: Integer)
    begin
        // My subscriber code
    end;
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36793433-053a-b52e-0fdc-9e67f4733a10
* Version Independent ID: 3c4eebce-a23b-2231-3363-20cc63922ef0
* Content: [IntegrationEvent Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-integration-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-integration-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-integration-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! More information has been added to the article. Hopefully this will help. The update will be published soon.
