### ISSUE TITLE
remove random order

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#468]
We do not randomize the order of execution

"the subscriber methods are run one at a time in random order"
should be
"the subscriber methods are run one at a time in no particular order."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd88d2e-999d-88b4-0867-0519358ef806
* Version Independent ID: 1c99ec09-2eab-9e4e-c1e7-cf69a089a16d
* Content: [Raising Events - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-raising-events)
* Content Source: [dev-itpro/developer/devenv-raising-events.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-raising-events.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, these will be fixed with the next doc refresh.
