### ISSUE TITLE
missing see also links

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#473]
missing see also links to 
BINDSUBSCRIPTION Method
UNBINDSUBSCRIPTION Method 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbfabd4b-c71c-8c33-8ae0-57c1f75ba62b
* Version Independent ID: 905eeb0c-ceca-ff11-3468-95d399e06ff4
* Content: [EventSubscriberInstance Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-eventsubscriberinstance-property)
* Content Source: [dev-itpro/developer/properties/devenv-eventsubscriberinstance-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-eventsubscriberinstance-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, these will be fixed with the next doc refresh.
