### ISSUE TITLE
EventSubscriber syntax

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#474]
[EventSubscriber(ObjectType::ObjectType, ObjectId, 'OnSomeEvent', 'ElementName', SkipOnMissingLicense, SkipOnMissingPermission)]

There is no explanation about what SkipOnMissingLicense or SkipOnMissingPermission does

ObjectType::ObjectType vs. ObjectId: Need better syntax description here. Either use the first form or the second

'OnSomeEvent': I would prefer '&lt;event name&gt;'

'ElementName': I would prefer '&lt;element name&gt;'

There is no mentioning that element name is optional

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847f9637-606b-5022-0891-81481a7eb283
* Version Independent ID: 35643c3c-bb2d-e1ef-6ebd-556158d9d8e7
* Content: [Subscribing to Events - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-subscribing-to-events)
* Content Source: [dev-itpro/developer/devenv-subscribing-to-events.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-subscribing-to-events.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks Kennie, the article has been updated to include your suggestions, The update will be published soon.
