### ISSUE TITLE
ObjectId

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#476]
"ObjectId
Type: Integer

Specifies the ID of the object that publishes the event to subscribe to."

Why is there no mention of the Codeunit::MyEventPublisher syntax here? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d70267f-d9d9-ae2f-f8fc-f2abd435bffe
* Version Independent ID: f52b19f8-a064-81e5-35a2-76a406620fa4
* Content: [EventSubscriber Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-eventsubscriber-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-eventsubscriber-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-eventsubscriber-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hi Kennie, the description of the ObjectId parameter has been changed to include your suggestion. The updated article will be published soon. Thanks for the feedback.
