### ISSUE TITLE
OnSomeEvent

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#477]
"OnSomeEvent
Type: Text"

I would prefer EventName or EventPublisherMethod

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d70267f-d9d9-ae2f-f8fc-f2abd435bffe
* Version Independent ID: f52b19f8-a064-81e5-35a2-76a406620fa4
* Content: [EventSubscriber Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-eventsubscriber-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-eventsubscriber-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-eventsubscriber-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback Kennie! "OnSomeEvent" was changed to "EventName" to match IntelliSense shown for the attribute in Visual Studio Code. The update will be published soon.
