### ISSUE TITLE
SkipOnMissingLicense

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#478]
Hard to read:

Specifies what happens to the event subscriber method call when the Dynamics 365 Business Central license of the user account that is running the current session does not include the codeunit that contains the subscriber method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d70267f-d9d9-ae2f-f8fc-f2abd435bffe
* Version Independent ID: f52b19f8-a064-81e5-35a2-76a406620fa4
* Content: [EventSubscriber Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-eventsubscriber-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-eventsubscriber-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-eventsubscriber-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback Kennie! The description has been rewritten to make it easier to read, hopefully. The update will be published soon.
