### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#48]
It is annoying when the examples given contain syntax errors. The line below copied from above will not run as there is no comma before SL.Amount and no space before the FROM.

SELECT C.Name, C.'No.' SL.AmountFROM Customer AS C, 'Sales Line' AS SL WHERE C.'No.' = SL.'Sell-to Customer No.' 

This corrected version below ran on Sql Server on our system:

SELECT C.Name, C.No_, SL.Amount FROM [CRONUS USA, Inc.$Customer] AS C, [CRONUS USA, Inc.$Sales Line] AS SL WHERE C.No_ = SL.[Sell-to Customer No_]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cae22a9-e48b-fdaf-8dbd-b554e82eac1b
* Version Independent ID: 7f0de03e-45d3-7418-6a63-3d39a2ae87aa
* Content: [Walkthrough: Creating a Query to Link Two Tables - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--creating-a-query-to-link-two-tables)
* Content Source: [dynamics-nav/Walkthrough--Creating-a-Query-to-Link-Two-Tables.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Creating-a-Query-to-Link-Two-Tables.md)
* Service: **unspecified**
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The example has been fixed and verified. The updated content will be available soon.
