### ISSUE TITLE
Do I need to set the EventSubscriberInstance property?

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#480]
"Set the EventSubscriberInstance property of the codeunit to specify how event subscriber methods in the codeunit are bound to codeunit instance"

If the default EventSubscriberInstance is StaticAutomatic, do I need to set it explicitly? If not, then documentation should state this
"Optionally, set the EventSubscriberInstance property of the codeunit if you want to explicitly specify how event subscriber methods in the codeunit are bound to codeunit instance"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847f9637-606b-5022-0891-81481a7eb283
* Version Independent ID: 35643c3c-bb2d-e1ef-6ebd-556158d9d8e7
* Content: [Subscribing to Events - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-subscribing-to-events)
* Content Source: [dev-itpro/developer/devenv-subscribing-to-events.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-subscribing-to-events.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback. The article has been changed to include your suggestion. The update will be published soon.
