### ISSUE TITLE
Change instruction form CNTL+F7 to just F7 to pull extension code from server

### ISSUE THREAD

**Issue by louiskody** [MicrosoftDocs/dynamics365smb-devitpro-pb#483]
[Enter feedback here]

> If you choose not to download the code at the end, you can still pull the changes via the Ctrl+F7 shortcut from Visual Studio Code

For me, Cntl+F7 doesn't work.  According to the AL keyboard shortcuts, it is just F7, which works for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc13a127-253d-6438-52ed-319589d8d3ec
* Version Independent ID: 9bcc413c-55cb-a0e0-8ca2-f111658076fe
* Content: [Building your first sample extension that uses new objects and extension objects - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-example)
* Content Source: [dev-itpro/developer/devenv-extension-example.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-example.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this will be fixed with the next doc refresh.
