### ISSUE TITLE
Change Cntl+F7 to just F7 in Shortcuts page

### ISSUE THREAD

**Issue by louiskody** [MicrosoftDocs/dynamics365smb-devitpro-pb#484]
[Enter feedback here]

"Ctrl+F7 | Download source code"

Doesn't work for me.  Plain 'F7' works.  

I haven't tried all the other shortcuts to validate.

Same as https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/483#issue-425143206  but for different page in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1862aa1-bc2a-c558-f370-181414142331
* Version Independent ID: a7a65168-1a32-69b5-a5e9-d69954a15d95
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-keyboard-shortcuts)
* Content Source: [dev-itpro/developer/devenv-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this will be fixed with the next doc refresh.
