### ISSUE TITLE
No examples for client_credentials flow

### ISSUE THREAD

**Issue by emilw** [MicrosoftDocs/dynamics365smb-devitpro-pb#485]
Hi,
All examples are either for web service key or Delegated(end user flow), there are no examples available anywhere for the client credentials flow(admin consent for the azure ad and application access). The Machine 2 Machine scenario is thereby not working in production if web service key is not allowed, as stated here: https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics
Can you comment on that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#feedback)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for you question. Right now, the client_credentials flow is not supported. Under [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) you can share a product idea, if you want to. Thanks.

**Comment by emilw** [comment]
Hi,
Sorry if I was unclear....my question was not about if it’s supported or not, my question was about the docs. In your current docs it looks like Web service key is mot supported in the production scenarios, which you say it should. Can you clarify that the direct tenant approach is for production use and not only for “Rapid development”?

**Comment by henrikwh** [comment]
Its strongly recommended to use OAuth for production. 

We are not supporting client_credentials flow in SaaS. Each connection to BC needs to be done in the context of a user. We recommend that you use OAuth in production, but you can use Basic Auth for now. Please submit an [ideas](http://aka.ms/bcideas).

**Comment by emilw** [comment]
Hi Henrik,
Yes, I agree that OAuth is the best but without client credentials support it’s not possible to use a e.g windows service(machine to machine integration scenario) to download or upload data to it without using the web service key at the moment(that is why I think you should update the docs to make it clear that it is ok to use web service key in production).

If you look how this exact same scenario have been resolved in your sister product D365 FO they map within D365 FO a user to the client id to have a user in the context(IT approves app access and the business finalize it within D365).

The problem with the support you have now is that you only support add-ons where there is an end user authenticating itself(OAuth access code flow), that’s what makes it unclear in the docs as you more or less shut out the most common integration use case middlewares(Biztalk) etc.

Also, is it in the plan to add the support for client credentials flow? I get a little bit scared that you want me to register a dev suggestion for client credentials flow support...or do you have a suggestion that just need votes?
