### ISSUE TITLE
Example #2, Step 3

### ISSUE THREAD

**Issue by KMG1** [MicrosoftDocs/dynamics365smb-devitpro-pb#486]
"InitializeExternalConnections" is listed as the function name to add, but in the complete code snippet, it is listed as "InitializeTableConnections".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a0a128-219f-7414-800b-69928779471f
* Version Independent ID: d9e6d035-d1dd-708b-892d-68ec7ecc7b7b
* Content: [External Tables - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/external-tables#feedback)
* Content Source: [dynamics-nav/External-Tables.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/External-Tables.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, the article has been fixed, and an update will be published soon. Thanks for the feedback!
