### ISSUE TITLE
Wrong link to RUNREQUESTPAGE Method method

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#487]
Wrong link to  RUNREQUESTPAGE Method method.
Used url:   https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-runrequestpage-method
Correct url: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-runrequestpage-method
Wrong link to  RUNREQUESTPAGE Method method.
Used url:   https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-runrequestpage-method
Actual url: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-runrequestpage-method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 603417a5-e264-835c-6f47-fb1f643e5755
* Version Independent ID: d751df67-69f9-68e8-0ae1-a55ef592939c
* Content: [SaveAs Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-saveas-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/report/report-saveas-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/report/report-saveas-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this will be fixed with the next doc refresh.
