### ISSUE TITLE
Formatting Enum

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-devitpro-pb#488]
Please Provide some explanation and examples about formatting enum values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5468dbfb-e0a2-6c51-58eb-d73580d2bbc1
* Version Independent ID: 63893c18-9b04-b5b9-a8a9-45bf23bb3d56
* Content: [Format Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-format-property)
* Content Source: [dev-itpro/developer/properties/devenv-format-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-format-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback and sorry for the wait. You can build a format the same way you do with the rest of the data types. As for the standard formats for enum values, a table has been added with the available formats and the corresponding examples. It will be available with the next doc refresh.
