### ISSUE TITLE
controladdin missing in Type map

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-devitpro-pb#489]
The Type "controladdin" is missing in the Type Map.
I think a Abbreviation is not necessary. Due to absence of Object Id the filenames are not to long.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. I've updated the topic which will be available with the next doc refresh. Please use **ConAddIn** for controladdin objects. Thanks.
