### ISSUE TITLE
Informative

### ISSUE THREAD

**Issue by SmartNoel** [MicrosoftDocs/dynamics365smb-devitpro-pb#49]
Information contained in this page is important. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 947f4dae-c716-4a49-9e3e-1036c0e23c17
* Version Independent ID: 3c4796d6-9a5b-a652-d66b-508c9cf4ede7
* Content: [Codeunits Functions and Variables - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/understanding-codeunits)
* Content Source: [dynamics-nav/Understanding-Codeunits.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Understanding-Codeunits.md)
* Service: **unspecified**
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback!
