### ISSUE TITLE
Add page to tree of contents

### ISSUE THREAD

**Issue by louiskody** [MicrosoftDocs/dynamics365smb-devitpro-pb#491]
This page along with any similar samples should be added to the Document Tree on the left. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f0b091-b6bd-4ff0-b959-920f84d26605
* Version Independent ID: 8a474282-4882-07dd-132c-39833d4704d5
* Content: [D Simple List Page Example - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-simple-list-page-example)
* Content Source: [dev-itpro/developer/devenv-simple-list-page-example.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-simple-list-page-example.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We have added links in the tree to this article and others. The update will be available soon.
