### ISSUE TITLE
Description refers to Convert-NAVServerUser

### ISSUE THREAD

**Issue by JuricaB** [MicrosoftDocs/dynamics365smb-devitpro-pb#492]
Description section was copied from Convert-NAVServerUser and does not describe this function. 
Examples 3 & 4 do not match the functionality. Switches -ProfileID and -ExportPath do not exist in current version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0358e7c6-3bb8-0f2b-d9f9-2273223f5b37
* Version Independent ID: e1ab5649-84a4-49d8-e981-3eecb84bb777
* Content: [Convert-NAVCustomization (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/convert-navcustomization?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Management/Convert-NAVCustomization.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Management/Convert-NAVCustomization.md)

**Comment by jswymer** [comment]
Thanks for the feedback! The issues have been fixed, and an update will be published soon.
