### ISSUE TITLE
Need better examples

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#493]
If this is going to replace text constants we need more examples that mimics the old functionality
For instance how to use different translations.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: a15813f6-f9d6-5008-5d18-c69fd4f0f761
* Version Independent ID: 0ac4ae64-4482-818b-b0fd-0b59f7d7a962
* Content: [Label Data Type - Business Central](https://docs.microsoft.com/sv-se/dynamics365/business-central/dev-itpro/developer/methods-auto/label/label-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/label/label-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/label/label-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by update-jeremy** [comment]
Agreed.  Even the Label examples in the "Working With Translation Files" are more practical/useful than the ones outlined on the Label page.

Working with Translation Files should also be linked, since that is where the info lives about Translation handling.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The topic has been updated with more information. Thanks.
