### ISSUE TITLE
Function " Generate Test Coverage Map" does not exist

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#494]
I the following part of the topic the ference to "Generate Test Coverage Map" makes no sense as that does not exist on the CAL Test tool:

> To run specific tests based on test coverage maps
> 
>     Open the CAL Test Tool window.
> 
>     Choose the test or test suite that you want to generate a test coverage map for, and then choose Generate Test Coverage Map.

I recon this should be "Update Test Coverage Map".

BTW: why does Business Central do not have this topic.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91d50c9-ef1a-403d-1088-0c37efb445f3
* Version Independent ID: 4505568b-f29f-627a-d993-8b931b451485
* Content: [How to: Run Automated ApplicationTests - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--run-automated-applicationtests?lc=1043)
* Content Source: [dynamics-nav/How-to--Run-Automated-ApplicationTests.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Run-Automated-ApplicationTests.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
The NAV documentation is no longer maintained. Closing this issue. Thanks.

**Comment by lvanvugt** [comment]
LOL, fully agree, but I guess we do agree that this issue has been open for too long (more than 4 years). Keeping it open long enough to make it obsolete, right?
