### ISSUE TITLE
Type field has an invalid description for supported values

### ISSUE THREAD

**Issue by propagating** [MicrosoftDocs/dynamics365smb-devitpro-pb#495]
On the top-level item page, the 'type' field is designated as supporint a numeric value of either 0 or 1. The API does not support a 0 or 1 in the type field for items, nor does it return a 0 or 1 when requesting an item. Instead, the values supported appear to be the configured type names in business central such as "Inventory", "Service", or "Non-Inventory".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86d748a-72b6-3f29-dce5-c1787808a2ea
* Version Independent ID: 09476e73-e50d-244e-fb1d-716c2c619047
* Content: [items resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/resources/dynamics_item)
* Content Source: [dynamics-nav/api-reference/v1.0/resources/dynamics_item.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/resources/dynamics_item.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by propagating** [comment]
This also appears to be the case in the beta documentation located here: https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/resources/dynamics_item

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, nice catch - this was a leftover that we didn't fix. This is fixed in v1.0 and beta and will be available with the next push to live. Thanks again!
