### ISSUE TITLE
v1.0 404 Not Found

### ISSUE THREAD

**Issue by calebsexton5s** [MicrosoftDocs/dynamics365smb-devitpro-pb#496]
When querying the non-beta Common endpoint service at https://api.businesscentral.dynamics.com/v1.0/api/v1.0 we recieve a 404 Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2e0a70-16db-cebb-ff63-e7b0a5f4f70d
* Version Independent ID: 041169de-956b-f1a8-c66b-7bf77f5e5f64
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics#feedback)
* Content Source: [dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The availability of the v1.0 endpoint depends if the tenant has been upgraded to the April '19 release. Please check with your support channel. Thanks.

**Comment by cloudfy** [comment]
Hi Susanne, how do you determine if a tenant is beta or upgraded?
