### ISSUE TITLE
Naming Conventions & CodeCop

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#497]
The CodeCop analyzer page clarifies that there is a rule (AA0074) about approved Suffixes for TextConsts.  That CodeCop page should be linked from here, and the rule should be followed by the sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5430cd34-1b14-3cea-c29e-f161b6793b78
* Version Independent ID: 36251966-e872-e2f8-d462-5efbec2f66ba
* Content: [TextConst Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/textconst/textconst-data-type)
* Content Source: [dev-itpro/developer/methods-auto/textconst/textconst-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/textconst/textconst-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The topic is updated with the next doc refresh.
