### ISSUE TITLE
Multilanguage and Translation Files

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#499]
There should be a huge disclaimer on this page.  In the Working With Translation Files page, it clarifies that TextConst types do NOT get included in the XLF files for translation.

For working in a proper multilanguage development environment, the TextConst should be considered deprecated and Label should be used instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5430cd34-1b14-3cea-c29e-f161b6793b78
* Version Independent ID: 36251966-e872-e2f8-d462-5efbec2f66ba
* Content: [TextConst Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/textconst/textconst-data-type)
* Content Source: [dev-itpro/developer/methods-auto/textconst/textconst-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/textconst/textconst-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Good point, thanks for your feedback. This is updated with the next doc refresh.
