### ISSUE TITLE
HTML tags are showing

### ISSUE THREAD

**Issue by pmohanakrishna** [MicrosoftDocs/dynamics365smb-devitpro-pb#5]
<properties title: "ExtendedDataType Property | Dynamics NAV" description="Partial migration of topic for the ExtendedDataType property." services="" documentationCenter="" authors="edupont04"/> <tags ms.prod="dynamics-nav-2017" ms.topic="article" ms.devlang="na" ms.tgt_pltfrm="na" ms.workload="na" ms.date="08/11/2016" ms.author="edupont04" />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c477f62-7cbb-8da5-eeb4-533268c6d0f4
* Version Independent ID: bb64ddee-1ac5-b599-4dc0-7679b2f375ff
* Content: [ExtendedDataType Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/property-extended-datatype#)
* Content Source: [dynamics-nav/property-extended-datatype.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/property-extended-datatype.md)
* Service: **unspecified**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for finding this. Fixed with the next refresh of the docs.
