### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by KaterynaShn** [MicrosoftDocs/dynamics365smb-devitpro-pb#50]
void ShowPusourhpin(string title, string imageName);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6891bf2-f259-f38e-ea2f-121f3b1157b3
* Version Independent ID: 3e1d16f4-2dcf-b85a-0009-9da15446de02
* Content: [Walkthrough: Creating and Using a Client Control Add-in - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--creating-and-using-a-client-control-add-in#story)
* Content Source: [dynamics-nav/Walkthrough--Creating-and-Using-a-Client-Control-Add-in.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Creating-and-Using-a-Client-Control-Add-in.md)
* Service: **unspecified**
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswmer**

**Comment by jswymer** [comment]
Thanks for the feedback! The issue has been fixed and it be available soon.
