### ISSUE TITLE
Attributes table

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#501]
It should be noted on this page that all the Attributes are optional.

Additionally, if the user omits the value, what is the result?  Does locked default to 'false'?  Does MaxLength default to anything?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15813f6-f9d6-5008-5d18-c69fd4f0f761
* Version Independent ID: 0ac4ae64-4482-818b-b0fd-0b59f7d7a962
* Content: [Label Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/label/label-data-type)
* Content Source: [dev-itpro/developer/methods-auto/label/label-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/label/label-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The topic will be updated with more info with the next refresh. The default value of Locked is 'false' and no definition of MaxLength allows any string length. Thanks.
