### ISSUE TITLE
Maximum number of characters in a text or code field is 2048

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-devitpro-pb#503]
In April 2019 release,

Maximum number of characters in a text or code field 	250

should be 

Maximum number of characters in a text or code field 	2048

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55cfcfb0-bfdf-c874-7231-e7bff02fa2e5
* Version Independent ID: a61a12dd-5e08-b79f-ab4e-ffd5ec677c56
* Content: [Object Specifications and Limitations - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/object-specifications-and-limitations)
* Content Source: [dynamics-nav/Object-Specifications-and-Limitations.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Object-Specifications-and-Limitations.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello Kennie, the increase in the max character size has not changed in Dynamics NAV; this was done only in Business Central, which you can read about at [Object Specifications and Limitation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-object-specifications-limitations).
