### ISSUE TITLE
Differences with earlier MS communications about object ranges

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-devitpro-pb#504]
Cf. the blog by Kurt Juvyns here: https://community.dynamics.com/business/b/businesscentraldevitpro/archive/2018/10/17/which-object-ranges-can-we-use-with-microsoft-dynamics-365-business-central

The information on this page is not equivalent to the information in the blog. Which version is the truth?
I'm mainly interested in the 70M range.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98387b95-ce70-594b-b0e1-36ef1b5a6fb6
* Version Independent ID: 8a8d3822-49c4-1422-e046-0d7c9726c9b6
* Content: [Object Ranges - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-object-ranges#feedback)
* Content Source: [dev-itpro/developer/devenv-object-ranges.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-object-ranges.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The help topic was outdated and will be fixed with the next refresh. Please use the referenced blog post as guidance. Thanks.
