### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#505]
The Remarks refer to "the default validation behavior". If  a developer needs to know what validation has been run prior to code he/she might be inserting in an OnValidate trigger, how would they find out what "the default validation behavior" is? The doc makes a reference to behavior as if all developers somehow already know what that behavior is, and provides no explicit link to an explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7ad6e4-99c3-cf83-c355-62b23b4ec701
* Version Independent ID: 7a43567c-af65-6e50-4076-4945e2606863
* Content: [OnValidate (Fields) Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onvalidate-fields-trigger)
* Content Source: [dev-itpro/developer/triggers/devenv-onvalidate-fields-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onvalidate-fields-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The default validation behavior makes reference to the default checks the system performs on a field entry for validating it.  These are checking if the data type of the value entered matches the field data type and checking that it complies with the property constraints set up in such field. 
This will be soon included in the documentation.
