### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#507]
What is "the default modify behavior" and where is it documented? Otherwise the doc is referring to behavior that will very likely affect results of OnModify code (because it runs after the OnModify trigger), but cannot be investigated by the developer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85b87640-382e-8dff-473e-8ad0271004ba
* Version Independent ID: bff40a5a-0ac2-aeae-30e0-05294121f907
* Content: [OnModify Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onmodify-trigger)
* Content Source: [dev-itpro/developer/triggers/devenv-onmodify-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onmodify-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by klktraveloperations** [comment]
"What is "the default modify behavior" and where is it documented?" Good question!
I would like to know as well.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for the long wait. We have had a similar question regarding the same question, please see [here](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/558) and we're working on updating documentation on triggers which should be available in a refresh within the next weeks. Thanks.
