### ISSUE TITLE
Can't show Image Control on Card Page

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#509]
Can you please provide a working example of the use of a Media or MediaSet Data Type on a Page? I'm Trying to Implement a Picture on a Page. I tried using Media and MediaSet. But in both cases there is no Trace of said TableFields on the Page I'm trying to show it in.

Are there any special actions needed or properties to set? I tried to implement it the same way I would implement any other Data Type.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: 05cda8bb-5704-95ab-ff67-1893af50f569
* Version Independent ID: 968dfd51-77d8-812a-0ff0-97ec0536f1b9
* Content: [Media Data Type - Business Central](https://docs.microsoft.com/de-ch/dynamics365/business-central/dev-itpro/developer/methods-auto/media/media-data-type)
* Content Source: [dev-itpro/developer/methods-auto/media/media-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/media/media-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, code examples for the media and mediaset methods have been added, which will hopefully guide you for doing this. They will be available in the next update.
