### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#51]
For newbies, it would be helpful to have a collapsed area that could be expanded to show the associated C/AL Globals and other information needed, or perhaps also downloadable text files that would contain the query and sample codeunit. These could then be imported for a full working copy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f79f280-f218-14ec-5978-2d14d7113eb3
* Version Independent ID: 4a3c1d00-8742-263e-e2d6-2915b86fdd5d
* Content: [TOPNUMBEROFROWS Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/topnumberofrows-function)
* Content Source: [dynamics-nav/TOPNUMBEROFROWS-Function.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/TOPNUMBEROFROWS-Function.md)
* Service: **unspecified**
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! We can definitely see the value in providing "full" code examples - either embedded in the article or available as downloadable text files. For some articles, we have provided the full sample code (for example see https://docs.microsoft.com/en-us/dynamics-nav/external-tables#Examples), but it not something we do generally. We are currently reworking our content model and will take this into consideration as part of this work.
