### ISSUE TITLE
How to get data changed since some time stamp by using OData Rest API

### ISSUE THREAD

**Issue by windfly2006** [MicrosoftDocs/dynamics365smb-devitpro-pb#510]
Hello, I am reading the Dynamics Business Central REST API such as: [Account Get Rest API](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_account_get) 

We would like to use REST API for some application development although we would like to be able to get data through an incremental approach such as retrieving all data which last modified time is after certain time. Is that possible? 

I do see "lastModifiedDateTime" returned at quite some entities although not all of them. I guess we could try out to see if we could filter by using lastModifiedDateTime. 

If I should submit these type of questions in another place, please let me know.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This repo is meant for doc issues and errors only. Please use your usual support channel to get help with this. Thanks.
