### ISSUE TITLE
Indentation 

### ISSUE THREAD

**Issue by KSH-audibene** [MicrosoftDocs/dynamics365smb-devitpro-pb#512]
"If more than one record is selected on the page" - indentation slipped

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7925335a-cb73-11cc-1466-2844777ea50a
* Version Independent ID: 683c1ae3-9926-2f98-54ee-61ccbb8dc382
* Content: [SETSELECTIONFILTER Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/setselectionfilter-function)
* Content Source: [dynamics-nav/SETSELECTIONFILTER-Function.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SETSELECTIONFILTER-Function.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
