### ISSUE TITLE
The statement makes no sense

### ISSUE THREAD

**Issue by KSH-audibene** [MicrosoftDocs/dynamics365smb-devitpro-pb#513]
"The Record for which you want to specify a table." - but the Record is always the record of specific Table -&gt; it is impossible to  specify a table for the record

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a083160-7dcf-0254-61e4-1fa34c9919b9
* Version Independent ID: 5256417f-e953-cb12-c64a-8f4783e0d5fd
* Content: [SETTABLE Function (RecordRef) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/settable-function--recordref-)
* Content Source: [dynamics-nav/SETTABLE-Function--RecordRef-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SETTABLE-Function--RecordRef-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for your feedback and sorry for the wait. The description has been changed and it will be published soon.
