### ISSUE TITLE
Task 10 is not only for upgrades from Microsoft Dynamics NAV 2018

### ISSUE THREAD

**Issue by lucacostamagnaeos** [MicrosoftDocs/dynamics365smb-devitpro-pb#514]
Task 10 (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data#task-10-upgrade-from--only-increase-the-application-version-of-converted-database) is not only for upgrades from Microsoft Dynamics NAV 2018, but also Business Central October 2018.

Section title should be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data#task-10-upgrade-from--only-increase-the-application-version-of-converted-database)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, thanks for the correction! The updated article will be published soon.
