### ISSUE TITLE
What does Authentication row really means?

### ISSUE THREAD

**Issue by emilw** [MicrosoftDocs/dynamics365smb-devitpro-pb#517]
In the authentication row it says AAD for all production scenarios(Usage column) in Cloud. The feeling you get then is that it's only AAD that is supported in production and not the "Web service access key".
For AAD it's only Access code flow supported(end user interaction) which more or less means that the web service access key is the only option to talk to a tenant if you are a machine and not a user. This then requires you to use "direct tenant" approach(means of connection row). Which is not for production according to Usage row.
Can you clarify this or make it more clear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17c4eef7-2ff2-eeeb-d285-095002e99475
* Version Independent ID: 2beae6be-8b5f-2a48-4b68-81810248b8f6
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics)
* Content Source: [dynamics-nav/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/endpoints-apis-for-dynamics.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
Its recommended to use AAD for production in case of Direct Tenant and Common Endpoint Service. But Basic Auth is permitted for the "Direct Tenant".

**Comment by marknitek** [comment]
That does not clarify the OP question. 
How should unattended machine-to-machine communication in production be done? AAD is not an option here as i understand it (since not unattended) so a token based authentication must be used.
If not please give an advice/example of how to do this. 

Also i would like to know how AAD authentication from a javascript add-in to the api could be done.

**Comment by henrikwh** [comment]
Theres samples on how to use OAuth from JavaScript: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-spa
https://github.com/AzureAD/azure-activedirectory-library-for-js

**Comment by m12lrpv** [comment]
Not all production scenarios involve users. Web jobs are a thing, they exist and are very prominent component of inter app integrations. 

Basic Auth is not acceptible in that scenario. A documented solution is required for that scenario that uses client id and secret.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the documentation currently reflects what is possible. Please use the [ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) forum for suggestions. Will close this. Thanks.
