### ISSUE TITLE
Missing info, ApplicationArea property required

### ISSUE THREAD

**Issue by Frantic42** [MicrosoftDocs/dynamics365smb-devitpro-pb#519]
News ticker will not display unless the page fields have the property ApplicationArea set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e978f7d-5b1b-84f9-dec9-33fdf3792f8c
* Version Independent ID: a2ad8189-852b-f76c-df36-c3fbcea8ce93
* Content: [Create a Role Center Headline - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-create-role-center-headline)
* Content Source: [dev-itpro/developer/devenv-create-role-center-headline.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-create-role-center-headline.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I have just tried out this example and the headers display without the ApplicationArea property set - in fact, I could not make it work when they're set. Can you try again? Are you running on the latest version of AL? Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
