### ISSUE TITLE
Product Owner

### ISSUE THREAD

**Issue by Molly-Reid** [MicrosoftDocs/dynamics365smb-devitpro-pb#52]
Will it be possible to attach image files to purchase or sales invoices via the API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e6db000-1fc7-c65b-617a-30c9dc7331ad
* Version Independent ID: 9cc35823-5d06-0813-7905-36ebb6d8bc48
* Content: [Create purchaseInvoices - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_create_purchaseinvoice)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_create_purchaseinvoice.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_create_purchaseinvoice.md)
* Service: **dynamics365-financials**
* Product: **unspecified**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, it is currently not possible but we will consider the request. Thanks for your feedback.
