### ISSUE TITLE
Integration is not a valid attribute

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#520]
Trying to follow this example and I'm getting an error "Integration is not a valid attribute" AL(AL0112)
If I comment it out, The subscriber cannot see the 'OnAddressLineChanged'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1707a904-2ed1-590e-4a3d-cda6aa6b1d06
* Version Independent ID: 8583221b-8b6f-49c0-f71e-f660fe6f49bb
* Content: [Publishing Events - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-publishing-events#feedback)
* Content Source: [dev-itpro/developer/devenv-publishing-events.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-publishing-events.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, sorry the attribute should be [IntegrationEvent(false, false)], not [Integration(false, false)]. We have fixed the article and the update will be published soon. Thanks for the feedback!
