### ISSUE TITLE
Notification Colour

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#521]
Is there a provision in NAV to change the colour of the notification area programmatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87fc7637-4e16-c566-a99a-0f2e01aa22a6
* Version Independent ID: cb3cd413-3471-8411-98c5-5d25b22ba777
* Content: [Notifications - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-notifications-developing)
* Content Source: [dev-itpro/developer/devenv-notifications-developing.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-notifications-developing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, you cannot change the color of the notification area in any way, it is standard color scheme of the client running. Thanks.
