### ISSUE TITLE
Can't add Power Bi reports 

### ISSUE THREAD

**Issue by Redtable1** [MicrosoftDocs/dynamics365smb-devitpro-pb#522]
In BC on-prem , When I clicked on, 'Get started with Power BI Reports' the wizard  came up . It asked me Azure Active directory permissions. All the permissions given but ,  can not finish the  wizard. 
(can not add the screen shot)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff0aa19-50aa-c461-cd97-4be8fbe4e393
* Version Independent ID: f72d929a-7fea-246f-8b2e-4f3b14c5c92d
* Content: [User Authentication with Azure AD for Single Sign-on - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory#feedback)
* Content Source: [dev-itpro/administration/authenticating-users-with-azure-active-directory.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/authenticating-users-with-azure-active-directory.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please contact your usual support channel for this question. This repo is used for documentation issues and bugs. Thanks.
