### ISSUE TITLE
Missing AdditionalSearchTerms

### ISSUE THREAD

**Issue by mynavblog** [MicrosoftDocs/dynamics365smb-devitpro-pb#523]
Dear Team - there is missing property AdditionalSearchTerms in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2612295b-ecb2-93f1-2097-c5e055ed5123
* Version Independent ID: ec810858-2ada-8915-c110-7634c6b791b4
* Content: [Page and Page Extension Properties Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-property-overview)
* Content Source: [dev-itpro/developer/properties/devenv-page-property-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-page-property-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
duplicate, closing this

**Comment by jswymer** [comment]
Thanks for the feedback. The AdditionalSearchTerms and AdditionalSearchTermsML properties have been added to the page. The update will be published soon.
