### ISSUE TITLE
Missing AdditionalSearchTerms

### ISSUE THREAD

**Issue by mynavblog** [MicrosoftDocs/dynamics365smb-devitpro-pb#524]
Dear Team,
There is missing AdditionalSearchTerms property on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8866e-44ae-917c-8a61-b78888f629bc
* Version Independent ID: 9c5dba2e-21d8-9fe5-ecbb-427b63384ed8
* Content: [Report Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-report-properties)
* Content Source: [dev-itpro/developer/properties/devenv-report-properties.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-report-properties.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for pointing this out, this will be fixed with the next update.
