### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MykhayloYelnikov** [MicrosoftDocs/dynamics365smb-devitpro-pb#525]
Link in line "For more information, see the SQL Server blog." redirects to 
Oops! That page can’t be found.
This page has been disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90bc5fad-1339-2f68-cfc7-ab24acd3d815
* Version Independent ID: 00690d59-5861-9f3d-a740-9057d333e965
* Content: [Intelligent Edge for on-premises - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/about-intelligent-edge#feedback)
* Content Source: [dev-itpro/administration/about-intelligent-edge.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/about-intelligent-edge.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by blrobl** [comment]
Hi, does the error persist? It seems to be working now.

**Comment by SusanneWindfeldPedersen** [comment]
There must have been a glitch on the blog server, the link is working now. Closing this issue.
