### ISSUE TITLE
Wrong related link

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#526]
The related link to New-NAVServerConfiguration is wrong - it leads to Set-NAVServerConfiguration.
The correct link is: https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/new-navserverconfiguration?view=businesscentral-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e1da1f9-d594-be0a-4b14-84dc78efd323
* Version Independent ID: 351aaaee-76e6-6392-4e18-350186aab5b3
* Content: [Set-NAVServerConfiguration (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/set-navserverconfiguration?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Management/Set-NAVServerConfiguration.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Management/Set-NAVServerConfiguration.md)

**Comment by blrobl** [comment]
Hi, thanks for pointing that out. The link will be fixed in the next doc refresh.
