### ISSUE TITLE
Modify Title

### ISSUE THREAD

**Issue by dkip05** [MicrosoftDocs/dynamics365smb-devitpro-pb#527]
Please consider adding the words "Drop-Down Control" to the end of this article's title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9979b71-a2f9-9032-5bba-161f6da5ff63
* Version Independent ID: 7fd0115f-bfec-43e1-e5c3-69bf2e4d383c
* Content: [Field Groups - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-field-groups#feedback)
* Content Source: [dev-itpro/developer/devenv-field-groups.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-field-groups.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The title is based on the technical term used during development, but I will add your suggestion to the article's title - updated with the next doc refresh.
