### ISSUE TITLE
Business Central Translation (Turkish) Question

### ISSUE THREAD

**Issue by barandeniz** [MicrosoftDocs/dynamics365smb-devitpro-pb#528]
Hello all, we are trying to upgrade our localization solution to Business Central from NAV 2017. Since Microsoft does not handle localization and translations in Turkey, partners have to handle these requirements in order to sell/implement NAV/BC. Sometime ago Microsoft published a list of partners/regions who developed a custom localization. My question is how the hell partners managed to release a localization with custom translations which are not built-in languages. How did they managed to add an additional language that is not already added by Microsoft without PLLP? (Partner Translation Toolkit)

We can translate and import the CaptionML as txt file from Development Environment but since we can not choose Turkish language from NAV, translated captions doesn't appear in application. How can we get related ResX files for Business Central?

In NAV 2017, translation was 4 parts;

1) ResX files
2) Captions
3) Profiles
4) .stx and .etx files

Business Central W1 14.0 On-Prem Translations will be still same?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this is a more complex question and I have to ask you to contact your partner to get help with this. This repo is used for reporting doc issues and bugs. Thanks.
