### ISSUE TITLE
asdfasdfsda

### ISSUE THREAD

**Issue by KSH-audibene** [MicrosoftDocs/dynamics365smb-devitpro-pb#529]
under See Also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ec2af20-d598-3625-db5b-5ebe2fb2e734
* Version Independent ID: d997bf90-7e2b-d0cd-9b98-ce1ba726536d
* Content: [AddCertificate Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-addcertificate-method)
* Content Source: [dev-itpro/developer/methods-auto/httpclient/httpclient-addcertificate-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/httpclient/httpclient-addcertificate-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for pointing that out. This will be fixed with the new doc refresh.
