### ISSUE TITLE
AAD Not Working

### ISSUE THREAD

**Issue by joshbooker** [MicrosoftDocs/dynamics365smb-devitpro-pb#53]
I think you want the following for Access Token URL
`https://login.windows.net/<your tenant domain>/oauth2/token`

Still it's not working for my tenancy.  

I get 500 INTERNAL SERVER ERROR when I hit:
`https://api.businesscentral.dynamics.com/v1.0/<tenant>.onmicrosoft.com/api/beta/companies`

Which is better than 401 UNAUTHORIZED, so I'm getting closer.  Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#setting-up-azure-active-directory-(aad)-based-authentication)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* Product: **unspecified**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by joshbooker** [comment]
More info:  It works  when you get token using either of these for resource parameter:
`https://api.financials.dynamics.com` or `996def3d-b36c-4153-8607-a6fd3c01b89f`
rather than 
`https://api.businesscentral.dynamics.com`

**Comment by henrikwh** [comment]
Hi @joshbooker 
Right. We will fix the Acess token URL. It does not need the resource appended. We will fix that.

It might be, that you need to use the old resource (https://api.financials.dynamics.com or 996def3d-b36c-4153-8607-a6fd3c01b89f) if you have registed the app in the AAD before the launch of BC. New app registrations should use https://api.businesscentral.dynamics.com.

It might be, that the user does not have a license in BC? Hence the 401.

Also, please retry connecting to the api. I know we had some issues causing 500 errors in some cases.

**Comment by joshbooker** [comment]
I registered the app in AAD yesterday however my tenency was formerly financials upgraded to BC. Could that require the old resource?

**Comment by henrikwh** [comment]
What is your tenant name? Just to confirm, my URL looks like this for my tenant:

https://login.windows.net/M365x800158.onmicrosoft.com/oauth2/authorize?resource=https://api.businesscentral.dynamics.com

and

https://login.windows.net/M365x800158.onmicrosoft.com/oauth2/token

**Comment by joshbooker** [comment]
I use joshbooker.com or infoconsulting.onmicrosoft.com but I did see the M365xxx in a querystring once like ?tenant=M365xxx. I believe that was in BC but may have popped up in postman auth through trial and error. Can not recall.

**Comment by henrikwh** [comment]
Lets have a quick skype call. Shoot me mail on henrikwh@microsoft.com so we can setup a call to identify the issue.

**Comment by Bhawan-Bhangu** [comment]
Hi I'm getting same issue. I'm super user in BC but sill unauthorized. 
Url is https://api.businesscentral.dynamics.com/v1.0/<tenant-id>/WS/CRONUS%20Canada

Please help me to solve this. Even had tried using postman. Same issue.

**Comment by joshbooker** [comment]
We determined that my problem was a config issue in the BC service for my cluster.  Thanks @henrikwh 

@Bhawan-Bhangu your URL looks incorrect. Should be:
`https://api.businesscentral.dynamics.com/v1.0/api/beta/`

Did you follow all the steps in the article to register an app in AAD? and then get token in Postman?

**Comment by Bhawan-Bhangu** [comment]
Thanks @joshbooker for replying.
My credentials were not correct

**Comment by SusanneWindfeldPedersen** [comment]
Thanks all for your feedback and @henrikwh thanks for your help - I am closing this issue.

**Comment by joshbooker** [comment]
@SusanneWindfeldPedersen 
I think you want the following for Access Token URL
https://login.windows.net/<your tenant domain>/oauth2/token
