### ISSUE TITLE
Hostname Resolution

### ISSUE THREAD

**Issue by spiritsip** [MicrosoftDocs/dynamics365smb-devitpro-pb#530]
Is there some trick to getting the images to resolve by DNS hostname? Whenever I run these, it won't work by hostname (e.g. in the example above, https://cdc633cdb0a2/NAV/), but you can get to them by IP address (https://172.20.203.209/NAV/). Unfortunately, the IP address changes every time you restart the container.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6979fc73-1395-b63f-50bf-b2fb1bfda4df
* Version Independent ID: eaf8c4d6-15a5-6444-bc72-48bd0a2e326a
* Content: [Running a Container-Based Development Environment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-container-development)
* Content Source: [dev-itpro/developer/devenv-running-container-development.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-running-container-development.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this is a technical question that I'll suggest you ask through your usual support channel, alternatively look for more information at [Freddys Blog](https://blogs.msdn.microsoft.com/freddyk/).

**Comment by spiritsip** [comment]
I would highly recommend updating the new-navcontainer snippet to include the -updateHosts flag as this *does* fix the DNS issue and makes it work as advertised (e.g. no additional work or setup).
