### ISSUE TITLE
What is the table number

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#531]
Why do I have to go somewhere else to find out what the table number is in case I want to query that via C/AL code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d462a0-fab8-4335-7609-b29fa83868ef
* Version Independent ID: 3c7796f1-7b72-1de1-d79f-bc206352470e
* Content: [Field Virtual Table - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/field-virtual-table)
* Content Source: [dynamics-nav/Field-Virtual-Table.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Field-Virtual-Table.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, the ID is 2000000041. We have updated the other virtual table articles with IDs as well. The updated articles will be published soon. Thanks for the feedback!

**Comment by j2associates** [comment]
Thanks, very much appreciated.
