### ISSUE TITLE
No table number

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#533]
Why is there no table number on this page? It is ridiculous that I have to go search to find the table number to actually use the data contained in this otherwise helpful page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d2e8df-e8a5-e6ed-3127-13d6d0fa3604
* Version Independent ID: ab6dc40e-8f4b-f39e-3ae9-ebd283eb7e7a
* Content: [Key Virtual Table - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/key-virtual-table)
* Content Source: [dynamics-nav/Key-Virtual-Table.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Key-Virtual-Table.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, I see your point. The ID is 2000000063. We have updated the other virtual table articles with IDs as well. The updated articles will be published soon. Thanks for the feedback!
