### ISSUE TITLE
Extra semicolon ?

### ISSUE THREAD

**Issue by SUD-D365** [MicrosoftDocs/dynamics365smb-devitpro-pb#534]
In first code snippet, 4th procedure. There are semicolon placed before **else**, that should not be.
 procedure ToString(value: Variant) : Text; 
    begin 
        if value.IsInteger then 
            Exit(IntegerToString(value)); 
        else if value.IsDate then 
                Exit(DateToString(value)); 
        else if value.IsText then 
                Exit(TextToString(value)); 
        else 
            Exit(''); 
    end; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03fc1b85-0180-bfd5-8748-d19b8cc3ce4a
* Version Independent ID: 72ebe788-b3e0-b1da-313a-6b93d9862c3e
* Content: [Procedure overload - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-overload-method)
* Content Source: [dev-itpro/developer/methods/devenv-overload-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-overload-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. That's right, it will be fixed with the new doc refresh.
