### ISSUE TITLE
FilterHandler - Note under Signature incomplete

### ISSUE THREAD

**Issue by JuricaB** [MicrosoftDocs/dynamics365smb-devitpro-pb#535]
In section https://docs.microsoft.com/en-us/dynamics-nav/how-to--create-handler-functions#to-create-a-handler-function under 7., in table Function/Signature, Note under FilterHandler is incomplete/incorrect:

"Note: You must a VAR parameter for each record on the FilterPageBuilder object. For more informatiion about Filter"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceab92c1-9510-ed55-8bac-41b1614ebfb0
* Version Independent ID: 93786902-1621-bfd0-03f4-4dbb5bf35f11
* Content: [Create Handler Functions - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--create-handler-functions#feedback)
* Content Source: [dynamics-nav/How-to--Create-Handler-Functions.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Create-Handler-Functions.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, there should have been a link to the [Creating Filter Pages for Filtering Tables](https://docs.microsoft.com/en-us/dynamics-nav/creating-filter-pages-for-filtering-tables) article. The note has been fixed, and the updated article will be published soon. Thanks for the feedback!
