### ISSUE TITLE
Task 4: Delete all objects except tables in old database

### ISSUE THREAD

**Issue by StijnBt** [MicrosoftDocs/dynamics365smb-devitpro-pb#536]
I am upgrading from BC CU2 to the spring release and I am getting this errror when performing task 4:

---------------------------
Microsoft Dynamics NAV Development Environment
---------------------------
You do not have permission to delete the 'Version Triggers' Codeunit.

Contact your system administrator to have your permissions changed.
---------------------------
OK   
---------------------------

**Comment by StijnBt** [comment]
I am spotting this line in our dev licence:
Product Version	        : 13
That should probably be 14?

**Comment by SusanneWindfeldPedersen** [comment]
Hi, this repo is for report documentation issues and bugs. Please contact your usual support channel to get help resolving this.
