### ISSUE TITLE
Đề nghị MS viết Doc bỏ thêm nhiều hình vào

### ISSUE THREAD

**Issue by quocdunginfo** [MicrosoftDocs/dynamics365smb-devitpro-pb#537]
Đọc chữ không, chán bome. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465f9aba-bc43-ef8d-072a-6fa41d0c0df8
* Version Independent ID: 4fbc03f7-a29f-1344-22de-f99c8da4392d
* Content: [Monitoring Microsoft Dynamics 365 Business Central Server Events - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/monitor-server-events#feedback)
* Content Source: [dev-itpro/administration/monitor-server-events.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/monitor-server-events.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Please file any issues in English, otherwise we're not able to help you. Thanks.
