### ISSUE TITLE
Regarding Section Publish to cloud settings

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#538]
It would be nice if the new parameter **sandboxName** would be added. Inside the AL Extension this parameter has the following tooltip: 
> Specifies which sandox to use in cases where multiple sandboxes are owned by the same tenant.

And it would be nice to extend the Parameter **tenant**. Inside the AL Extension this parameter has the following tooltip that would be helpful also in the help page.

> [..] this parameter must contain a tenant AAD domain name, for example: mycustomer.onmicrosoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback - this topic will be updated with the next doc refresh.
