### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#539]
The example being used on this page is for the Set-NAVServerConfiguration cmdlet, not the New-NAVServerConfiguration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb6878c-e087-03d2-6f7f-92688813ce0c
* Version Independent ID: 7a7071c1-393b-c6d1-7a40-9953ee8e36f7
* Content: [New-NAVServerConfiguration (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/new-navserverconfiguration?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Management/New-NAVServerConfiguration.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Management/New-NAVServerConfiguration.md)

**Comment by blrobl** [comment]
Hi, thanks for pointing this out, a new example for the New-NAVServerConfiguration will be available in the next doc refresh.
