### ISSUE TITLE
Extension Capabilities

### ISSUE THREAD

**Issue by mstallmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#54]
It would be helpful for developers if you could include on the documentation for properties whether or not it is available in an extension.  Meaning, can we overwrite this property in a table extension.  I am aware that we cannot with this specific property, but would be useful for others. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4e8d65c-b1bb-2e92-0827-5a206d7a3962
* Version Independent ID: 1113af58-3400-02e3-f6ba-d768a39cd1d7
* Content: [DataPerCompany Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/datapercompany-property)
* Content Source: [dynamics-nav/DataPerCompany-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/DataPerCompany-Property.md)
* Service: **unspecified**
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. If you are looking for AL and extension V2 docs, you can get an overview of the properties in this docset - we have lists for which properties apply to tables and table extensions, and pages and page extensions, for example, here: [Properties](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-properties). Hope this helps.
