### ISSUE TITLE
Which product does this page apply to?

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#541]
I am trying this code in Dynamics 365 BS AL and cannot get the OptionCaption := MyFieldRef.OPTIONCAPTION;  to compile.
I get the following error: "The name 'OptionCaption' does not exist in the current context"

Everything else works fine except for this line.
I tried to move the line in the field property area and it does not work either.
	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6398bb22-5918-c461-4f48-d7b98ce0a5ba
* Version Independent ID: 8c7521a4-30a5-a01c-d884-aef8b774a079
* Content: [OPTIONCAPTION Function (FieldRef) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/optioncaption-function--fieldref-)
* Content Source: [dynamics-nav/OPTIONCAPTION-Function--FieldRef-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/OPTIONCAPTION-Function--FieldRef-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please find all help for development in AL here: [AL](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/?branch=master) and the equivalent of the topic you were looking at is here:
[OptionCaption Method](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-optioncaption-method) - the method is valid, can you make it work with the described syntax. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
