### ISSUE TITLE
Write to Debug Console

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#542]
Would it be possible to add information on how to write to the debug console?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3f5d28-1484-ce76-b31d-7ee0d444ba0f
* Version Independent ID: bdea6ca9-e7bc-d324-03d5-364c0fcaee4e
* Content: [Debugging - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-debugging)
* Content Source: [dev-itpro/developer/devenv-debugging.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-debugging.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, can you please elaborate on what you mean?

**Comment by yannstlo** [comment]
Hi Susan,

I'm coming from a C# programming background and when I'm debugging, I'm able to Write to the console window anything that I want using the Debug.WriteLine() command. This is very useful to see what data is stored in variables and other information pertinent to debugging.

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your reply. The AL debugger hooks into the Visual Studio Code debugger, so this is perhaps something that you can find in their documentation. This is not something that we have been looking into at this point.
