### ISSUE TITLE
upgrade not mentioned at all

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#544]
please also describe the upgrade value in the remarks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd47726a-bec0-b024-a039-63e8a3e0ecd4
* Version Independent ID: 1429b0c8-e13d-0155-a244-b403ca700ec8
* Content: [SubType Property (Codeunit) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-subtype-codeunit-property)
* Content Source: [dev-itpro/developer/properties/devenv-subtype-codeunit-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-subtype-codeunit-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback! This has now been added and will be available in the next doc refresh.
