### ISSUE TITLE
Incorrect example for syncing

### ISSUE THREAD

**Issue by kristjano** [MicrosoftDocs/dynamics365smb-devitpro-pb#545]
I believe the example command should either have the 'Name' parameter or 'Path' but not both.

    Sync-NavApp -ServerInstance YourDynamicsNAVServer -Name ExtensionName -Tenant TenantID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc95f9ad-6f07-d6af-0b08-9ec2742a1fd6
* Version Independent ID: ad1cec21-3e17-820c-7963-f7f51d61e818
* Content: [How to: Publish and Install an Extension v2.0 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-how-publish-and-install-an-extension-v2#feedback)
* Content Source: [dev-itpro/developer/devenv-how-publish-and-install-an-extension-v2.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-how-publish-and-install-an-extension-v2.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! The article has been fixed and an update will be published soon.
