### ISSUE TITLE
Upload of the per-tenant extension

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#546]
The description of Upload of the per-tenant extension is very vague, missing example of the URL. I was not able to test the API at all from given information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036fbaa0-3f6b-e4f7-cd1e-c35b37cdee6e
* Version Independent ID: 9efb41bd-bad8-597f-08e8-2b3c7e05f8e9
* Content: [Introduction to automation APIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/itpro-introduction-to-automation-apis#handling-tenant-extensions)
* Content Source: [dev-itpro/administration/itpro-introduction-to-automation-apis.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/itpro-introduction-to-automation-apis.md)
* Service: **dynamics365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
Hi.
We have linked to the PATCH request in the text (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/dynamics-microsoft-automation-extensionupload-patch).  Please try that.

**Comment by kine** [comment]
Silly me... :-)
