### ISSUE TITLE
Rewrite rule in the navsetting.json configuration file

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [MicrosoftDocs/dynamics365smb-devitpro-pb#548]
Is it not the web.config file that has to be modifed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9601316b-17ac-d019-5c84-8f7ebe32c288
* Version Independent ID: 189101fa-bd2b-68d1-e0a7-2b53616345ad
* Content: [Web Client Configuration for Tenants - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-web-server-to-accept-host-names-for-tenants)
* Content Source: [dev-itpro/administration/configure-web-server-to-accept-host-names-for-tenants.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configure-web-server-to-accept-host-names-for-tenants.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, yes, you are correct. It is the web.config file that must be modified. The article has been fixed and an update will be published soon. Thanks for the feedback!
