### ISSUE TITLE
Usage is unclear, the PATCH URL in example differs from the template

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#549]
Hi,
I am trying to use the info given on the page to upload the PerTenant app to SaaS tenant, but I am confused:

In beginning, the URL is described as 

PATCH /microsoft/automation/{apiVersion}/companies({companyId})/extensionUpload(0)/content

In the exmaple, the URL is 

PATCH https://api.businesscentral.dynamics.com/v1.0/api/microsoft/automation/beta/companies({companyId})//

Why in first there is "extensionUpload(0)/content" part and in example there is just "//"? What should be there in reality? When I use the URL from the example and even from the beginning, I am getting "RequestDataInvalid" error. 

Second unclear thing is the description of "If-Match" attribute - "eTag provided does not match the current tag " - what is the eTag and what is the current tag? Where I can see them? I am totally not knowing about what the doc is talking...

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74b671a8-fd85-72cb-cc6f-ef5cfb9ca6bd
* Version Independent ID: c320f922-3786-7842-94a3-261df0d8d314
* Content: [Patch extensionUpload - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/dynamics-microsoft-automation-extensionupload-patch)
* Content Source: [dev-itpro/administration/dynamics-microsoft-automation-extensionupload-patch.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/dynamics-microsoft-automation-extensionupload-patch.md)
* Service: **dynamics365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **solsen**

**Comment by kine** [comment]
Ok, regarding the If-Match:

Example is "If-Match:-*"
When I use "If-Match:*" I am not getting the "RequestDataInvalid" anymore, but "The request entity's media type 'application/octet-stream' is not supported for this resource.".

WHy the example is using not supported type? What is acceptable type?

**Comment by kine** [comment]
Ok, next labouring leads me that when I use url ending with /extensionUpload(0)/cont the application/octet-stream is accepted... can you fix the example?

**Comment by RasmusTidselbak** [comment]
@kine did you ever get this to work?
I've been struggling with this error every single time I've tried:

 "error": {
        "code": "Request_EntityChanged",
        "message": "Another user has already changed the record."
    }

**Comment by kine** [comment]
@RasmusTidselbak Yes, it works for v13 tenant using https://api.businesscentral.dynamics.com/v1.0/{{TenantID}}/api/microsoft/automation/beta/companies({{CompanyID}})/extensionUpload(0)/content 
and 
headers: Content-type=application/octet-stream and If-Match=* (and Authorization=Bearer xxxxx). Body is the app file content.

**Comment by RasmusTidselbak** [comment]
This is embarrassing, I've been struggling with this for months, because I added the eTag in the If-Match header. All this time I just had to use * instead.

Thank yo so much :)

**Comment by kine** [comment]
Yes, because each time you "contact" the API, new temporary record is generated, thus having different eTag... PATCH and GET will work with different instance...

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, both. The example in the topic was misleading and this is now fixed with the next refresh. Thanks!
