### ISSUE TITLE
AAD example should use common endpoint

### ISSUE THREAD

**Issue by joshbooker** [MicrosoftDocs/dynamics365smb-devitpro-pb#55]
Under section 'Exploring the APIs with Postman and AAD authentication' it says:
for example, call GET `https://api.businesscentral.dynamics.com/v1.0/<your tenant domain>/api/beta`

It would make more sense if the example was the common endpoint (without tenant):
GET `https://api.businesscentral.dynamics.com/v1.0/api/beta`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* Product: **unspecified**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - the docs are updated with the fixed endpoint. Thanks again.
