### ISSUE TITLE
API Properties

### ISSUE THREAD

**Issue by JohnnyUndercover** [MicrosoftDocs/dynamics365smb-devitpro-pb#550]
The follwing properties are missing: QueryType, EntitySetName, EntityName, APIPublisher, APIVersion, APIGroup.
Can you please explain what is the usage of this API-properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43acce6-5b53-7dad-5ae7-ea25291696b6
* Version Independent ID: 999c6e52-cbed-379f-c3ac-9f7affa1f0f1
* Content: [Query Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-query-properties#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-query-properties.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-query-properties.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We will make sure that the overview is updated with these properties. Meanwhile, maybe this [topic](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-querytype) could be helpful. It is not yet added to the table of contents, but will be. Hope this helps. thanks.
