### ISSUE TITLE
Progress Indicator does not work in web client

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#551]
Please add a remark that the Progress Indicator does not work in the web client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 163dedae-669d-4f9e-da19-f9812a0a96ab
* Version Independent ID: 22554382-887c-84da-7d21-51b81912c733
* Content: [Open Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-open-method)
* Content Source: [dev-itpro/developer/methods-auto/dialog/dialog-open-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/dialog/dialog-open-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! We have updated article to state that the progress indicator is not supported in the web client. The changes will be published soon.

**Comment by PaulFurlet** [comment]
Also, backslash does not work in Web Client.
Will this possibility be returned in foreseen future?
