### ISSUE TITLE
Localize/Language

### ISSUE THREAD

**Issue by MiePlougstrup** [MicrosoftDocs/dynamics365smb-devitpro-pb#552]
How do you specify profiles for different languages? Are users supposed to select an english profile name, when english is not their program/data language?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 032a235d-4c55-c10b-87b9-4926e57ed342
* Version Independent ID: a5e89e7e-8291-ed15-d3f9-45840489a057
* Content: [Profile Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-profile-object)
* Content Source: [dev-itpro/developer/devenv-profile-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-profile-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by MiePlougstrup** [comment]
Would someone like to give an answer for this issue?
It is the same issue with Permission Set.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is used for documentation issues and bugs. Please use your usual support channel for product-related questions. Thanks.
