### ISSUE TITLE
Global PingPong

### ISSUE THREAD

**Issue by gycsiak** [MicrosoftDocs/dynamics365smb-devitpro-pb#554]
Hi,

PingPong is great and easy to use, unless you close the Page the PingPong controll add-in is installed on. 

When using PingPong on a PagePart on Role Center Main Page, it works until the user navigates away from that Page particulary, but I would like to use PingPong globally on the client, so nevertheless, where the end-user is in RTC, the PingPong would continue to work. Is it possible somehow? Thank you in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5aebcf8-868f-3779-3fb0-042f111f767d
* Version Independent ID: acb4172f-6afd-3a14-4a0b-2d1814f0c825
* Content: [Using the PingPong Add-in - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/using-the-pingpong-add-in#feedback)
* Content Source: [dynamics-nav/Using-the-PingPong-Add-in.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Using-the-PingPong-Add-in.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, it is not possible to implement a global ping-pong addin. Thanks.
