### ISSUE TITLE
Supporten versions

### ISSUE THREAD

**Issue by ERPgruppenMW** [MicrosoftDocs/dynamics365smb-devitpro-pb#555]
With spring / 14.x release it is possible to choose NAV 2018 as source. But this page states that only BC on Prem is supported?

Seems that sync works correctly with 2018?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bffc19c-cc0a-fec5-b46b-16e58b034c19
* Version Independent ID: 0a79027a-c75c-f003-1c89-b0b64d4510de
* Content: [Frequently Asked Questions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/faq-intelligent-cloud#feedback)
* Content Source: [dev-itpro/administration/FAQ-Intelligent-Cloud.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/FAQ-Intelligent-Cloud.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by edupont04** [comment]
Hi there,
Sorry for the delay in following up on your question. You are right that you can connect Dynamics NAV 2018 with Business Central online for intelligent insights. The documentation will be updated as soon as possible.

**Comment by edupont04** [comment]
The content has been updated.
