### ISSUE TITLE
Example for BLOB Field Appears to be Incorrect

### ISSUE THREAD

**Issue by K1rlian** [MicrosoftDocs/dynamics365smb-devitpro-pb#556]
The example tests that Picture field of the GLAccountRec has a value . This is the record you're transferring too, it will have no value. You should test FromRecord and perform CALCFIELDS on FromRecord and then use TRANSFERFIELDS.

This page pointed me in the right direction but failed when I tried it this way. When I switched it around, it worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05a7129e-57b2-c478-4a83-2b79a5cac753
* Version Independent ID: 789f2307-43d6-3443-893f-f6f56d13c194
* Content: [TRANSFERFIELDS Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/transferfields-function--record-#feedback)
* Content Source: [dynamics-nav/TRANSFERFIELDS-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/TRANSFERFIELDS-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset.
