### ISSUE TITLE
Q: Extension codeunit binding

### ISSUE THREAD

**Issue by Quivelus** [MicrosoftDocs/dynamics365smb-devitpro-pb#557]
Hi,

I have a question concerning AL extensions. Suppose a codeunit in the base version has property EventSubscriberInstance set to 'Manual'. In case you extend this base codeunit in your extension, will it also be bound after calling BINDSUBSCRIPTION on the base codeunit? Or should the extension codeunit be bound seperately? In case of the latter, could there be something like 'OnBeforeBindSubscription' (same for unbound and for OnAfter)?

Regards,
Filip

**Comment by SusanneWindfeldPedersen** [comment]
This repo is meant for documentation feedback and issues. Please contact your usual support channel to get help with this. We will, however, save your question to help us further develop documentation around this area. Thanks.
