### ISSUE TITLE
better description please

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#558]
"Runs when a user modifies an existing record in a table."

Does that mean that it will run if any field is changed?
Does that mean it will not run if changes are made by code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85b87640-382e-8dff-473e-8ad0271004ba
* Version Independent ID: bff40a5a-0ac2-aeae-30e0-05294121f907
* Content: [OnModify Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onmodify-trigger)
* Content Source: [dev-itpro/developer/triggers/devenv-onmodify-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onmodify-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback.

With reference to your first question, the OnModify trigger will run when you modify at least one field of a record that is not the table's primary key (the OnRename trigger is specifically used for this). 

Regarding your second question, it will run only if, when you call the Modify or ModifyAll methods on a record, its *RunTrigger* argument is set to true.

This information will be reflected in the docs soon.
