### ISSUE TITLE
"Intelligent Cloud Sync as a Data Migration Mechanism" link not working

### ISSUE THREAD

**Issue by pmohanakrishna** [MicrosoftDocs/dynamics365smb-devitpro-pb#559]
"Intelligent Cloud Sync as a Data Migration Mechanism" link not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71aa4400-739a-6867-a2f5-2917a72d7620
* Version Independent ID: e0153a2f-2b2f-919a-33b1-43b0e9113413
* Content: [The “Ready to Go” Online learning for developers, architects, and engineers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-learning-dev-archs-engineers#new-videos)
* Content Source: [dev-itpro/developer/readiness/readiness-learning-dev-archs-engineers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-learning-dev-archs-engineers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We're hoping to have the video ready within the next week, and then the link will be updated. Thanks.
