### ISSUE TITLE
Unclear when dealing with multiple field PK

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#56]
Maybe one example with a multiple field Primary Key, such as Sales Header with "Document Type" and "No."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cb8b6b5-8e4b-09f6-a6dc-88e66013488f
* Version Independent ID: 3ec8ccb8-ecc8-64b6-62e7-2c89db329214
* Content: [GetRecIdFromKey - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/getrecidfromkey)
* Content Source: [dynamics-nav/GetRecIdFromKey.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/GetRecIdFromKey.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your input, this is on our backlog of things to do. Closing this issue for now.
