### ISSUE TITLE
If you get: "The value for the WSFederationLoginEndpoint configuration settings cannot be empty"

### ISSUE THREAD

**Issue by gertlynge** [MicrosoftDocs/dynamics365smb-devitpro-pb#560]
If you get ”The value for the WSFederationLoginEndpoint configuration settings cannot be empty.” just after login, you are probably running BC multi-tenancy and have filled the configuration settings AzureActiveDirectoryClientId and 
AzureActiveDirectoryClientSecret like you did on NAV 2018. 
AzureActiveDirectoryClientId and 
AzureActiveDirectoryClientSecret settings should be empty for BC!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff0aa19-50aa-c461-cd97-4be8fbe4e393
* Version Independent ID: f72d929a-7fea-246f-8b2e-4f3b14c5c92d
* Content: [User Authentication with Azure AD for Single Sign-on - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory#feedback)
* Content Source: [dev-itpro/administration/authenticating-users-with-azure-active-directory.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/authenticating-users-with-azure-active-directory.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by kine** [comment]
What is correct settings for Business Central and Multi-tenant environment? I got this error (WSFederationLoginEndpoint) and I am using multitenant v17 environment. I have AAD set on the tenant. What should I set on the service tier? What should I set on the tenant itself?

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. The article has been updated to more clearly indicate the steps for multitenant deployments. The AzureActiveDirectoryClientSecret, AzureActiveDirectoryClientId, and AzureActiveDirectoryClientSecret settings aren't used. We've added a note that they must be empty. The update will be published soon.
