### ISSUE TITLE
valdig guid text formats when assigning?

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#563]
does the {} need to be included in the MyText variable, when doing the following?
MyTableRec.MyGuid  :=  MyTableRec.MyText;
does it work with any valid guid format? (examples here: https://stackoverflow.com/a/4458925)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8805d123-2953-cb91-1894-ec6ec2bbede4
* Version Independent ID: f7e40620-a112-7f91-e75f-abc9666abd7a
* Content: [Guid Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/guid/guid-data-type)
* Content Source: [dev-itpro/developer/methods-auto/guid/guid-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/guid/guid-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. We support the two following formats: 
'11111111-1111-1111-1111-111111111111'
'{22222222-2222-2222-2222-222222222222}'
for formatting a GUID in text to be converted into a variable of the type GUID. Thanks.
