### ISSUE TITLE
Flow & salesOrderLines Api

### ISSUE THREAD

**Issue by jnpatrouillault** [MicrosoftDocs/dynamics365smb-devitpro-pb#564]
Hello
It's impossible to update Business Central from Flow with then salesOrderLine API.

(Using salesOrder API is ok)

error message : 
{
  "status": 400,
  "message": "ErrorCode: Application_DialogException  You must specify a document id to get the lines.\r\nclientRequestId: bf31d2f6-3d8a-46d9-b0e6-0e8048352c7e",
  "source": "api.businesscentral.dynamics.com",
  "errors": []
}

but the "document id" property is missing from Flow.
We see companyname, tablename, itemId, accountId but not "document id".
Where can we specfify that element ?
thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab8727c9-7b8e-2c83-680f-7f5c8a4ec22c
* Version Independent ID: dc43f5e7-d5d9-48e7-b74d-460b5a70150e
* Content: [Create salesOrderLines - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_create_salesorderline)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_create_salesorderline.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_create_salesorderline.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is meant for documentation issues and bugs. Please use your ususal support channel to get help with this issue. Thanks.

**Comment by businessuser123** [comment]
Hi jn, you can use a HTTP request in Flow to create sales order lines for a sales order. You can provide the Document ID in the post request that you will be sending through the HTTP connector. It's a shame it's not possible in one single action, but it's possible with a POST request through the HTTP step.

**Comment by businessuser123** [comment]
I've written a brief blog to give people guidance on how to execute a HTTP request to create sales order lines: https://www.ruudvg.com/2019/05/26/microsoft-business-central-api-beta-create-a-sales-order-and-sales-order-lines-through-powerapps-flow/.
