### ISSUE TITLE
Import Translation via codeunit

### ISSUE THREAD

**Issue by duichwer** [MicrosoftDocs/dynamics365smb-devitpro-pb#565]
Is it possible to import a Translation File with a any codeunit, instead of using the development environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde3484d-cec0-101f-c0c4-09f8b0fa7500
* Version Independent ID: bd4ff161-3dbc-892b-a188-35350db0882c
* Content: [Importing and Exporting Multilanguage Files - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--add-translated-strings-by-importing-and-exporting-multilanguage-files)
* Content Source: [dynamics-nav/How-to--Add-Translated-Strings-By-Importing-and-Exporting-Multilanguage-Files.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Add-Translated-Strings-By-Importing-and-Exporting-Multilanguage-Files.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. We're unfortunately not able to help you here, please use your usual support channel for guidance. Thanks.
