### ISSUE TITLE
Is That All?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#567]
Is this property not also used to define a join, to filter records in a subform, as in 
Item No.=FIELD(Item No.),Customer No.=FIELD(Customer No.),Customer Specification No.=FIELD(Specification No.).  (NAV 2017)?
From page37031449

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6fe1de6-74da-1098-e988-901885d36241
* Version Independent ID: c1982f56-661e-16e0-d6ed-b508bb1bf3e6
* Content: [SubPageLink Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/subpagelink-property)
* Content Source: [dynamics-nav/SubPageLink-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SubPageLink-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset.
