### ISSUE TITLE
Example lacks commonly used properties

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#568]
I think an example with a working SubPageLink and other commonly used properties would be widely appreciated here. I Mean, you mention that you can filter the record. Why don't you show how? At least put up a link to the Page properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 605a1acd-e3b5-7f1b-bdc8-335ff00fb141
* Version Independent ID: 7eb6b1f3-55f5-8ec0-d5fc-89d82decea57
* Content: [Adding a FactBox to a Page - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-a-factbox-to-page)
* Content Source: [dev-itpro/developer/devenv-adding-a-factbox-to-page.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-a-factbox-to-page.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. As you suggested, a code example has been added to illustrate the data filtering using the SubPageLink property. Also, examples now include some Factbox-related properties. This will be available in the next doc refresh.
