### ISSUE TITLE
Example needed (Implement on Card Page)

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#569]
I've already requested this in #509 and @blrobl was so nice to add a more detailed documentation to the Data Types "Media" and "MediaSet". However this didn't really solve my issue, where i don't know how to set up this table field to actually show it in a Card Page. - I can add the Field to the page and set the SourceExpression just like I do it with any other field. It just doesn't show up in the Client.

So, may I ask you to make an actual, working example? I'm pretty sure I'm not the only one with this problem.

I'm not looking for the Import/Export/Delete capabilities. - I just want to show the Content on a Card Page. - Not A Card Part. A Card page (`PageType = Card;`)
```
...
                field("Picture"; "Picture")
                {
                    ApplicationArea = All;
                }
```
Doesn't affect the clients output in any way
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05cda8bb-5704-95ab-ff67-1893af50f569
* Version Independent ID: 968dfd51-77d8-812a-0ff0-97ec0536f1b9
* Content: [Media Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/media/media-data-type)
* Content Source: [dev-itpro/developer/methods-auto/media/media-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/media/media-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. Indeed, Media and MediaSet table fields cannot be implemented in a page as it's done with other data types.  Instead, it must be done through the Factbox area by first creating a CardPart page where you set up the fields you want to display, and then implement it inside the Factboxes control of the Card page. The image will show in the right hand side of the page. Maybe this code example makes it clearer:

```
page 50100 CardPart
{
    PageType = CardPart;
    SourceTable = TableName;

    layout
    {
        area(content)
        {
            field(Picture; Picture)
            {
                ApplicationArea = All;
            }
        }
    }
}

page 50101 CardPage
{
    PageType = Card;

    layout
    {
        area(FactBoxes)
        {
            part(Picture; CardPart)
            {
                ApplicationArea = All;
            }
        }
    }
}
```
