### ISSUE TITLE
Missing QueryType property

### ISSUE THREAD

**Issue by BrianThorChristensen** [MicrosoftDocs/dynamics365smb-devitpro-pb#57]
The Query Property QueryType is missing from this documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fe77fd-9345-227b-47cf-acf857907587
* Version Independent ID: f3b589f4-808e-0042-1192-044a0ae988d5
* Content: [Query Properties - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/query-properties)
* Content Source: [dynamics-nav/Query-Properties.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Query-Properties.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! Sorry for the lack of documentation for this property. This is a gap we are aware of and will be providing content in a future update.
