### ISSUE TITLE
Usage of different suffixes

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [MicrosoftDocs/dynamics365smb-devitpro-pb#570]
Hi,
it would be really useful if there would be some examples about when to use which suffix, i.e. when should be Tok?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8e2178c-0742-1609-6373-4811a1968477
* Version Independent ID: 153d5502-ad26-e321-3c73-df9049553d66
* Content: [TextConst and Label variable names should have an approved suffix. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0074-textconstlabelvariablenamesshouldhaveapprovedsuffix#feedback)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0074-textconstlabelvariablenamesshouldhaveapprovedsuffix.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0074-textconstlabelvariablenamesshouldhaveapprovedsuffix.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, Tok is short for Token - used to indicate a response from a service, for example. The topic will be updated with explanations of the different abbreviations with the next refresh. Thanks.
