### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by MortenRa** [MicrosoftDocs/dynamics365smb-devitpro-pb#571]
The linkn to Docker Community Edition is broken on following page

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-container-development

Link broken : **Use Docker Community Edition** if the host operating system is Windows 10.

Should point to : https://hub.docker.com/editions/community/docker-ce-desktop-windows instead of current link

**Comment by blrobl** [comment]
Hi, thanks for pointing that out, the link has now been fixed.
