### ISSUE TITLE
Property FollowRedirects

### ISSUE THREAD

**Issue by tantainiit** [MicrosoftDocs/dynamics365smb-devitpro-pb#572]
HttpClient Data Type miss property FollowRedirects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 373144e9-348b-22d1-2e92-bfbeeb7ac30d
* Version Independent ID: 5425d7cc-8b63-ead1-c5c9-34366aec93df
* Content: [HttpClient Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/httpclient/httpclient-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/httpclient/httpclient-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, but there is no such FollowRedirects property nor method.
