### ISSUE TITLE
How to get all response header

### ISSUE THREAD

**Issue by tantainiit** [MicrosoftDocs/dynamics365smb-devitpro-pb#573]
Hi,

I want to get all response header if i don't knows header name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3493020e-c73c-e651-7358-bdd348695276
* Version Independent ID: 09c9dce8-5eb9-2977-e9aa-c4cca270d8bb
* Content: [HttpHeaders Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpheaders/httpheaders-data-type)
* Content Source: [dev-itpro/developer/methods-auto/httpheaders/httpheaders-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/httpheaders/httpheaders-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by atoader** [comment]
Hi, @tantainiit ! Have you considered using https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpresponsemessage/httpresponsemessage-headers-method ?

**Comment by atoader** [comment]
@tantainiit I apologize for the confusion. I realized  that there is currently no way to iterate over the collection of headers. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
