### ISSUE TITLE
Filtergroups

### ISSUE THREAD

**Issue by stephanweidmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#574]
If there are filters in different filtergroups, are all filters copied? to the same filtergroup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18136a6-a183-2e19-5419-8850e3704333
* Version Independent ID: 85de3bc7-adfc-22e4-05e0-ee7e0dab0dac
* Content: [COPYFILTERS Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/copyfilters-function--record-)
* Content Source: [dynamics-nav/COPYFILTERS-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/COPYFILTERS-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by cherabomb** [comment]
All filters are copied and remain in their assigned group numbers. I wanted to use this function to copy filters from one group to another but for that it is unsuited. The call
Rec.CopyFilters(FromRec) 
disregards the current FilterGroup on both Rec and FromRec, and copies all filters in FromRec (regardless of group number) into the same Filter Group assignments on Rec.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, both. The topic on the Business Central docs will be updated with the next refresh to live. Thanks.
