### ISSUE TITLE
The type or method 'SendTraceTag' cannot be used for 'Extension' development.AL(AL0296)

### ISSUE THREAD

**Issue by PeterBizz** [MicrosoftDocs/dynamics365smb-devitpro-pb#575]
Apperantly the SendTraceTag procedure cannot be used in Extension development. 
What alternative is available to add Telemetry information to an Extension

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 415b8537-06af-f235-e551-efc252edc54f
* Version Independent ID: c7b53b3d-864f-7576-e935-1924183728cd
* Content: [SENDTRACETAG Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/sendtracetag-function)
* Content Source: [dynamics-nav/sendtracetag-function.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/sendtracetag-function.md)
* Product: **dynamics-nav-2017**
* GitHub Login: @jswymer

**Comment by PeterBizz** [comment]
The SendTraceTag procedure can be used in Extension development when you use this line in the App.Json file: 
...
"target": "Internal",
...
It will give access to all system tables as before. However, note that you will not be able to publish such extensions to the cloud.

Maybe this can be added to the documentation.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Please take a look at the Business Central library [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/session/session-sendtracetag-method). All methods only available for on-prem are marked with a note. Thanks.
