### ISSUE TITLE
Please list the restriction about delegated admin users

### ISSUE THREAD

**Issue by Kielkenny** [MicrosoftDocs/dynamics365smb-devitpro-pb#577]
like not beeing able to export to excel
and not beeing able to run scheduled tasks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f495bb1-bd83-5b17-ad11-fe48910d2315
* Version Independent ID: 65a8141e-9503-3120-6269-88b34e721909
* Content: [Business Central Admin Center - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center)
* Content Source: [dev-itpro/administration/tenant-admin-center.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/tenant-admin-center.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by edupont04** [comment]
Hi Andreas,
Thanks for suggesting this! We'll get a list posted next week.
