### ISSUE TITLE
Test-NAVApplicationObjectLanguage Logpath Option for this Command

### ISSUE THREAD

**Issue by Nody85** [MicrosoftDocs/dynamics365smb-devitpro-pb#578]
It would be greate to have a -Logpath Parameter like "Import-NAVApplicationObject" to investigate the missing translations
and the Link to "Remove-NAVApplicationObjectLanguage" has a typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59fc4afe-27b5-da34-622a-79ec85c24325
* Version Independent ID: 0a82d2d1-2fc9-a7d7-5a97-d69124b4f5dc
* Content: [Test-NAVApplicationObjectLanguage (Microsoft.Dynamics.Nav.Model.Tools)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.model.tools/test-navapplicationobjectlanguage?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Model.Tools/Test-NAVApplicationObjectLanguage.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Model.Tools/Test-NAVApplicationObjectLanguage.md)

**Comment by blrobl** [comment]
Hi, thanks your feedback. The typo in the link has been fixed, but with regards to the -Logpath feature suggestion, please submit product ideas through https://aka.ms/bcideas.
