### ISSUE TITLE
Add info reg. NonDebuggable Attribute

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#579]
Wouldn't it be a good idea to reference the NonDebuggable Attribute? https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-nondebuggable-attribute

As I see it, that's a more fine granular way of protecting your IP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 161ddd1b-3d2c-d2fc-0d20-ad8331c809e4
* Version Independent ID: d5153e86-ac7c-4b93-43e2-ae6b06becb8e
* Content: [Security Setting and IP Protection - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-security-settings-and-ip-protection)
* Content Source: [dev-itpro/developer/devenv-security-settings-and-ip-protection.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-security-settings-and-ip-protection.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thank you for the suggestion, yes that makes good sense. This will be updated with the next doc refresh. Thanks!
