### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#58]
This line under Right Outer Join should say right outer join, NOT left outer join
To specify a left outer join with an SQL statement, you use the RIGHT OUTER JOIN condition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76b57e9-09d9-5fc8-22fa-eac5ff70830a
* Version Independent ID: 27a9ab20-b8a7-01ff-4834-87ddc15eaa75
* Content: [SQL Advanced Options for Data Item Link Types - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/sql-advanced-options-for-data-item-link-types)
* Content Source: [dynamics-nav/SQL-Advanced-Options-for-Data-Item-Link-Types.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SQL-Advanced-Options-for-Data-Item-Link-Types.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback. The issue has been fixed and will be available soon.
