### ISSUE TITLE
Missing URLs for the SaaS version of Business Central.

### ISSUE THREAD

**Issue by FSharpCSharp** [MicrosoftDocs/dynamics365smb-devitpro-pb#580]
This help page is based exclusively on the On-Premises version. In the SaaS version many things don't fit together anymore. Please add the appropriate information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306529fc-4319-ea42-4a6a-3db8e6c34540
* Version Independent ID: 65402969-34ad-201e-cd1e-7e4eb6658ee9
* Content: [SOAP Web Service URIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/soap-web-service-uris)
* Content Source: [dev-itpro/webservices/SOAP-Web-Service-URIs.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/SOAP-Web-Service-URIs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for the late reply. Please find information about endpoints in this [topic](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics).
