### ISSUE TITLE
Missing URLs for the SaaS version of Business Central.

### ISSUE THREAD

**Issue by FSharpCSharp** [MicrosoftDocs/dynamics365smb-devitpro-pb#581]
Is exactly the same error as in topic #580 . This help page is based exclusively on the On-Premises version.  In the SaaS version many things don't fit together anymore. Please add the appropriate information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88aa7e3-9b56-f8ef-b63d-c31b7098539a
* Version Independent ID: fb3c85ff-43fa-d496-6ef2-fdad0a24e23d
* Content: [SOAP and ODATA Web Services - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/web-services)
* Content Source: [dev-itpro/webservices/web-services.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/web-services.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for the late reply. Please find information about endpoints in this [topic](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics).
