### ISSUE TITLE
Documentation Outdated

### ISSUE THREAD

**Issue by eivindgiske** [MicrosoftDocs/dynamics365smb-devitpro-pb#582]
This page is outdated. Field naming does not match with Azure setup and BC Spring Release 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff0aa19-50aa-c461-cd97-4be8fbe4e393
* Version Independent ID: f72d929a-7fea-246f-8b2e-4f3b14c5c92d
* Content: [User Authentication with Azure AD for Single Sign-on - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory)
* Content Source: [dev-itpro/administration/authenticating-users-with-azure-active-directory.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/authenticating-users-with-azure-active-directory.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by DavidCurd** [comment]
I agree, this makes deploying the functionality more difficult than it needs to be.

**Comment by jswymer** [comment]
Hell. The article has been updated to better match the Azure Portal. I hope this helps. Thanks for the feedback!
