### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by spiritsip** [MicrosoftDocs/dynamics365smb-devitpro-pb#583]
In the "Use the right user for your testing" section, it says, "For information on how to setup this user, refer to this blog," but nothing is linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936119a1-4f7e-ed69-f72e-44e41464f964
* Version Independent ID: c30741c6-9408-775a-5ce0-3f6986445447
* Content: [Testing your Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-testingyourextension)
* Content Source: [dev-itpro/compliance/apptest-testingyourextension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-testingyourextension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for spotting this - the blog post has unfortunately not yet been published, but will be within the next couple of weeks. The blog post specifies that if you use a Docker Azure VM, which is encouraged, you get the ESSENTIAL user by default. Thanks.
