### ISSUE TITLE
Maintaining your app

### ISSUE THREAD

**Issue by spiritsip** [MicrosoftDocs/dynamics365smb-devitpro-pb#584]
Is there a pre-requisite or something to see the Packages or Daily Builds area? The aka.ms/collaborate link takes me to a fairly generic page with nothing called Packages or Daily Builds directly visible on that page. At a minimum, it's very unclear how to navigate to them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936119a1-4f7e-ed69-f72e-44e41464f964
* Version Independent ID: c30741c6-9408-775a-5ce0-3f6986445447
* Content: [Testing your Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-testingyourextension)
* Content Source: [dev-itpro/compliance/apptest-testingyourextension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-testingyourextension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Please read about how to gain access to Collaborate [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started#register-on-collaborate).  Thanks.
