### ISSUE TITLE
John should be in quotes

### ISSUE THREAD

**Issue by mortenseifert** [MicrosoftDocs/dynamics365smb-devitpro-pb#585]
if customerNames.Contains('John') then

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c760a1-0ba5-814b-94bf-c50008364769
* Version Independent ID: 235f987b-1062-26ba-81a7-b72ff35c099b
* Content: [List Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/list/list-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/list/list-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/list/list-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for noticing this! It will be fixed in the next doc refresh.
