### ISSUE TITLE
QueryCategory missing

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#586]
I'm missing the docs for the new property QueryCategory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43acce6-5b53-7dad-5ae7-ea25291696b6
* Version Independent ID: 999c6e52-cbed-379f-c3ac-9f7affa1f0f1
* Content: [Query Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-query-properties#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-query-properties.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-query-properties.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback! A page for QueryCategory has been created and it will be available in the next doc refresh.
