### ISSUE TITLE
Unclear error condition

### ISSUE THREAD

**Issue by BrianThorChristensen** [MicrosoftDocs/dynamics365smb-devitpro-pb#588]
Under critical errors I find the following condition unclear:
Code uses AutoIncrement = Yes for a table field that may be used in a Foreign Key relationship. Recommend code comment that the table field will not be used in a Foreign Key relationship to pass validation.

A foreign key relation must have two parts. Which part of the relation is forbidden?
Please provide an example of an illegal foreign key relation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b8f96f-eb61-aa86-ed4f-4544e9808aef
* Version Independent ID: fabff680-eeb9-26b4-5253-04713e0e1c74
* Content: [Rules and Guidelines for AL Code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-overview)
* Content Source: [dev-itpro/compliance/apptest-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The following article should hopefully clarify it - please see [Implementation of surrogate keys using AutoIncrement pattern](https://community.dynamics.com/nav/w/designpatterns/122.implementation-of-surrogate-keys-using-autoincrement-pattern). Thanks.

**Comment by BrianThorChristensen** [comment]
No, it doesn't clarify anything.
this is exactly the pattern I intended to use, but the app validation guidelines has it marked as a critical error.
Why is this pattern *not* allowed?

**Comment by SusanneWindfeldPedersen** [comment]
Let me see if I can loop in an expert on the app validation. If you do not have time to wait for a reply, I suggest contacting d365val@microsoft.com directly with this question. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Hello again, thanks for your patience and your feedback. We have discussed this and agree that the requirement does not make sense; the validation procedure and documentation will be updated with the next refresh. Thanks again!
