### ISSUE TITLE
Need examples

### ISSUE THREAD

**Issue by MikeGlue** [MicrosoftDocs/dynamics365smb-devitpro-pb#590]
Would be nice if we had a table that listed the available values that can be used for this property and what they mean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b62aefc-7ada-dbb7-cc0b-81cd16a2e1ee
* Version Independent ID: b196487a-58e7-b137-2581-5bb4b60aaf57
* Content: [AutoFormatType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-autoformattype-property#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-autoformattype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-autoformattype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, yes we should get this [content](https://docs.microsoft.com/en-us/dynamics-nav/formatting-the-data-in-a-field) available. I will put this on our backlog. Thanks!

**Comment by jswymer** [comment]
Hello, we have updated the article with more information. Hopefully this will help. The updated article will be published soon. Thanks for the feedback!
