### ISSUE TITLE
Duration - code vs. explanation

### ISSUE THREAD

**Issue by catorres** [MicrosoftDocs/dynamics365smb-devitpro-pb#591]
In the new Value set in the code area, "seconds" are set to '3.7'. No duration text/string is shown in the message and the return code will be 'No'.
When changing seconds to the same as the explanation below the code example area - just 3 seconds - the text is shown and the return code will be 'Yes'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e6068c1-60db-86b7-f7b3-bbdcb46c0a5e
* Version Independent ID: b0658a33-8be2-e718-bf85-ed5dbef61b1d
* Content: [EVALUATE Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/evaluate-function#feedback)
* Content Source: [dynamics-nav/EVALUATE-Function.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/EVALUATE-Function.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for your feedback and sorry for the wait. You're right, the current example is not working how it's supposed to, but the issue seems to be in the decimal value for the milliseconds. This will be fixed with the next doc refresh.
