### ISSUE TITLE
Available Builds and Engagements Email Address

### ISSUE THREAD

**Issue by spiritsip** [MicrosoftDocs/dynamics365smb-devitpro-pb#592]
In the "Getting access to the available builds and engagements," section, it states, "your... global administrator should send us an email to complete the on-boarding," but no email address is listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f11a3974-3f3b-33b3-5a55-f0fa5c6d558f
* Version Independent ID: b5fd581c-4f43-24cc-8821-2a8fc5f0a647
* Content: [Add-On Apps - Getting You Started - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started#register-on-collaborate)
* Content Source: [dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-add-on-apps-getting-you-started.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-liober
* Microsoft Alias: **v-liober**

**Comment by v-liober** [comment]
I have updated that information. Thank you. It should reflect on the next pull on Monday, June 3rd.

Lisa Oberg
Program Manager | Dynamics 365 Business Central | v-liober@microsoft.com<mailto:v-liober@microsoft.com>

[cid:image003.png@01D4B8B7.E52D1550]@MSDyn365BC<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FMSDYN365BC&data=02%7C01%7Cv-liober%40microsoft.com%7C1411f11b8dfa40c9ff6e08d68819bb6c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636846074896650099&sdata=S%2B20ZOJrLkh7TK5Ot04MkFW%2Fi2BRWvYhxEQBwRL9nLY%3D&reserved=0> #MSDyn365BC<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fsearch%3Ff%3Dtweets%26vertical%3Ddefault%26q%3D%2523MSDyn365BC%26src%3Dtyah&data=02%7C01%7Cv-liober%40microsoft.com%7C1411f11b8dfa40c9ff6e08d68819bb6c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636846074896660093&sdata=rQdqHTjYvWtZkjfrl%2BufcEOI1oSZrWgYVYPJC2saSF8%3D&reserved=0>

[Microsoft Logo]
