### ISSUE TITLE
Sales special pricing?

### ISSUE THREAD

**Issue by EionRobb** [MicrosoftDocs/dynamics365smb-devitpro-pb#593]
The Item endpoint only seems to have the unitPrice, which endpoint has the item's special prices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da3d76f8-6996-c2ee-0a26-ab63f798ca6b
* Version Independent ID: 87673447-d246-e5f9-477e-b2cc096df67c
* Content: [items resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/resources/dynamics_item)
* Content Source: [dynamics-nav/fin-graph/resources/dynamics_item.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/resources/dynamics_item.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
Item's special prices is currently not exposed in the standard api. Please add an idea on http://aka.ms/bcideas. 

But for now, you need to either expose data as an traditional web service or create an extension containing the API.
