### ISSUE TITLE
Tax percentages

### ISSUE THREAD

**Issue by EionRobb** [MicrosoftDocs/dynamics365smb-devitpro-pb#594]
Is there a way to request the TaxGroups endpoint to provide the percentages that make up the tax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725f4374-e370-af10-8e34-dda227319c28
* Version Independent ID: 2aa45071-83a5-b54b-2ddf-5c2c796ee50f
* Content: [taxGroups resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/resources/dynamics_taxgroups)
* Content Source: [dynamics-nav/fin-graph/resources/dynamics_taxGroups.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/resources/dynamics_taxGroups.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
You can expose page 468 from the web services page. You can also make a custom API that exposes the data you need.
