### ISSUE TITLE
Location code

### ISSUE THREAD

**Issue by EionRobb** [MicrosoftDocs/dynamics365smb-devitpro-pb#595]
How can we specify a location code for the order line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da32d888-9834-bab6-d951-8490fce676ad
* Version Independent ID: 5c4ffaa9-2c02-2d51-7192-28a48959db61
* Content: [salesOrderLines resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/resources/dynamics_salesorderline)
* Content Source: [dynamics-nav/fin-graph/resources/dynamics_salesorderline.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/resources/dynamics_salesorderline.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
Currently not avaliable. But you can vote for this idea: https://experience.dynamics.com/ideas/idea/?ideaid=5d14435f-4731-e911-9461-0003ff68cf1c
