### ISSUE TITLE
OnBeforeCustomerInsert of Table Contact

### ISSUE THREAD

**Issue by RalphSenften** [MicrosoftDocs/dynamics365smb-devitpro-pb#597]
this method should have "Contact" as addtional Parameter. 
Reason: in some installations "Customer" has the same ID as the "Contact" and the ID should be able to be transferred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c9bdf2-b0eb-ae82-4c62-6e52cdbe310a
* Version Independent ID: 593a228e-3ca3-fb32-149a-45a467e213e8
* Content: [Data Types and Methods in AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/library#feedback)
* Content Source: [dev-itpro/developer/methods-auto/library.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/library.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you have filed this issue on the methods overview topic, can you please be more precise on which method you are referring to? If this is an ask for a new feature, please file an idea using [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central). Thanks.
