### ISSUE TITLE
Missing dotnet wrappers in the Codeunits in the 3000 range

### ISSUE THREAD

**Issue by monicasuica** [MicrosoftDocs/dynamics365smb-devitpro-pb#598]
**Missing dotnet in the codeunits in the  3000 range:**
System.IO.FileStream.'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
System.IO.FileMode.'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Missing functions in existing 3000*:**
cu3026 DotNet_Encoding: Encoding.BigEndianUnicode; Encoding := Encoding.UTF7;
cu3008 DotNet_Convert: Convert.ToInt32(Hex,16) 

Can the codeunits in the range 3000 be extended with libraries and functions added above?

Thank you.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is intended for github issues on documentation. Please use your usual support channel for this type of question. Thanks.

**Comment by monicasuica** [comment]
Hello,

I don't know what's the usual support channel. Can you provide more details?

________________________________
