### ISSUE TITLE
What is azure-cli command to download publish settings file

### ISSUE THREAD

**Issue by Nimesh-Msys** [MicrosoftDocs/dynamics365smb-devitpro-pb#599]
I am using azure-cli instead of azure powershell. What could be the equivalent command of `Get-AzurePublishSettingsFile`.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is meant for documentation issues only. You have deleted information about which topic you're referring to. Please add that information back for us to be able to help or use your usual support channel for this question. Thanks.
