### ISSUE TITLE
Error on codeunit 825

### ISSUE THREAD

**Issue by francescomagalini** [MicrosoftDocs/dynamics365smb-devitpro-pb#6]
} missing at the end.
Bye

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b64094-643d-27c5-15c6-3bc5d8238dab
* Version Independent ID: cedb5b8f-1b2b-4999-5933-1005e11fb4d2
* Content: [Mock Code for Codeunit 824 DO Encryption Mgt. - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/resolve-dynamics-online-errors-database-conversion)
* Content Source: [dynamics-nav/Resolve-Dynamics-Online-Errors-Database-Conversion.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Resolve-Dynamics-Online-Errors-Database-Conversion.md)
* Service: **unspecified**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This will be fixed in the next refresh of the documentation.
