### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#60]
This line contains a typo:
Filter that is set to the field thaaat you want to filter,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67aa28dc-9be7-25ed-0b35-b9127e6f00f9
* Version Independent ID: 1f49660a-3c52-d48a-2d79-4ad0b541cee1
* Content: [Filtering From Query Designer and C/AL Code - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/understanding-query-filters)
* Content Source: [dynamics-nav/Understanding-Query-Filters.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Understanding-Query-Filters.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback. The issue has been fixed and will be available soon.
