### ISSUE TITLE
Really multitenant only?

### ISSUE THREAD

**Issue by tfenster** [MicrosoftDocs/dynamics365smb-devitpro-pb#600]
When upgrading a database I had missed tasks 6 and 12 as they were marked as multitenant only. But it very much seems to me like those are necessary in single-tenant as well (https://github.com/microsoft/AL/issues/5004). Why are they marked as multitenant only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b69c11d2-4915-8e2e-f38c-7bb1a3777bf9
* Version Independent ID: 0028111c-4f1a-df24-0d47-48b7f6e6d98a
* Content: [Upgrade Application Code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-application-code#feedback)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Application-Code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Application-Code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, you are correct. The tasks are required for a single-tenant deployment. However, they are covered by Tasks 10 and 14 in the article [Upgrading the Data to Business Central: Single-Tenant Deployment](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data). Let me know whether this answers your question and if you have a suggestion for improvement. Thanks for the feedback!

**Comment by jswymer** [comment]
Sorry for the delay. The article has been updated according to your suggestion. Thanks for the feedback!
