### ISSUE TITLE
Insufficient Client types

### ISSUE THREAD

**Issue by alemarius** [MicrosoftDocs/dynamics365smb-devitpro-pb#601]
API
Background
current
default
Desktop
Management
NAS
ODATA
ODATAV4
Phone
Soap
Tablet
Web
Windows

from Visual studio Code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda1055f-ba8d-d374-08ff-23f98aa42ebc
* Version Independent ID: 1e0bae9b-81a1-3657-2983-191debc51905
* Content: [CURRENTCLIENTTYPE Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/currentclienttype-function)
* Content Source: [dynamics-nav/CURRENTCLIENTTYPE-Function.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/CURRENTCLIENTTYPE-Function.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please see the Business Central developer documentation instead [ClientType System Option](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/clienttype/clienttype-option). Thanks.
