### ISSUE TITLE
Documenting feature original version

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [MicrosoftDocs/dynamics365smb-devitpro-pb#602]
Could you include in documentation pages, from what version a new feature is available? 
e.g. can I use this feature on an older on-prem version? if not, then that information is valuable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd55bfe-2599-257c-fe83-6c5c7d90b04b
* Version Independent ID: 60ac2b4a-d10a-5e8c-d2e7-ac380943cd0b
* Content: [Extensible Enums - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums#feedback)
* Content Source: [dev-itpro/developer/devenv-extensible-enums.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extensible-enums.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for the long wait. We deliberately have a "one version" approach in the docs, for several reasons, including lack of resources to maintain a complete versioned docset. In some cases we do mark topics with information if something does or does not work in a specific version. As a guideline, a new feature works with the product version it was introduced with. Please use the release plan overview for guidance on new functionality [Release Plans](https://docs.microsoft.com/en-us/dynamics365/release-plans/#pivot=dyn365-relplan&panel=dyn365relplan). Thanks.
