### ISSUE TITLE
TestTableRelation obsolete

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#606]
The compiler claims that TestTableRelation is obsolete. What gives?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 471c9309-7706-5af4-420e-6703786acfff
* Version Independent ID: 94825702-7bfc-4370-b95a-05aece876a03
* Content: [ValidateTableRelation Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-validatetablerelation-property)
* Content Source: [dev-itpro/developer/properties/devenv-validatetablerelation-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-validatetablerelation-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, the message is a bit misleading. It is means that the TestTableRelation is pending obsoletion. It will be deprecated in a future release. Until that time, you can still use it, and you only get an error at compilation time. When it is finally marked as obsolete, you will only be able to use it in upgrade code. We are working on content about this out soon. Thanks for the feedback!

**Comment by jswymer** [comment]
I hope this answered your question. We expect to publish more content about this topic in the future. So for now, we will close this issue, but feel free to provide more feedback about this issue as you like. Thanks!

**Comment by mjmatthiesen** [comment]
Is there an update? Nearly a year and I still havne't found an answer on this deprecation, what's replacing it, etc.
