### ISSUE TITLE
Web service timeout

### ISSUE THREAD

**Issue by ClausHamann** [MicrosoftDocs/dynamics365smb-devitpro-pb#607]
I have not been able to find any documentation on docs about web service timeouts. Can you please include this?
In the MicrosoftDynamicsNAV2018LicensingGuide.pdf the following is mentioned on page 8:

Note: When a Full User accesses a session using web services, the session is “locked” to that user for a minimum of two hours, after which time, if the user has logged out, the session becomes available to other users. For Limited Users, the session is tied to that user for a minimum of 15 minutes. The user may release the locked session at any time by logging into the solution through any of the Microsoft Dynamics NAV clients and logging out. At that time, the application will release all sessions tied to that user. Please note that users accessing the application indirectly, such as through a third party application, require to be licensed with and consume the appropriate CAL type, even if those users are not directly logging into the ERP solution. The responsibility for ensuring proper concurrency usage falls to the third party application provider.
Why not include it here and justify what the timeout is 2 hours for full users. Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 101c13e0-d163-31af-23b6-34df03a64530
* Version Independent ID: 460585d8-9ccd-0acf-c818-e57133c3c96d
* Content: [Configure Session Timeout - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/understanding-session-timeouts#feedback)
* Content Source: [dynamics-nav/Understanding-Session-Timeouts.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Understanding-Session-Timeouts.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset. We refer to the Business Central docs, for example: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-server-instance#ODataServices. Thanks.
