### ISSUE TITLE
Database trigger events - Wrong reference for subscribing

### ISSUE THREAD

**Issue by stefanoPrimo** [MicrosoftDocs/dynamics365smb-devitpro-pb#608]
I would like to report this problem: if I follow this page to subscribing to trigger events, vs code will return me errors about wrong params:
The member referenced by event subscriber 'X' parameter 'RunTrigger' is not found.AL(AL0282)
The member referenced by event subscriber 'X' parameter 'CurrentFieldNo' is not found.AL(AL0282)

for this subscriber:
[EventSubscriber(ObjectType::Table, Database::"Sales Header", 'OnAfterValidateEvent', 'Sell-to Customer No.', true, false)]

It is possible to update this page?
If not could you please add another page "Subscribing to Trigger Events"? 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 256aabb4-8d5d-cc06-6c1f-5558c668491b
* Version Independent ID: 51d1427c-130d-b5c0-3d04-89c01caa89f8
* Content: [Event Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-event-types#feedback)
* Content Source: [dev-itpro/developer/devenv-event-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-event-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! I tried to reproduce this error but I could not. I used the guidelines from [Subscribing to Events](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-subscribing-to-events), which includes some specifics about database triggers.  Maybe this article will help. Although, perhaps I am missing something in the scenario that I tried.

**Comment by stefanoPrimo** [comment]
Hi, yes the example works but if you try to copy and paste to an AL project what really it is written to the page that I reported it will not works.
so if you try to paste that to AL (obvs adding the event subscriber declaration [EventSubscriber(...)])
it will not work because it requires other parameters. 

OnBeforeValidateEvent(VAR Rec : Record, VAR xRec : Record, RunTrigger : Boolean; CurrentFieldNo : Integer)

let me know if you can reproduce the issue otherwise, I will share one with you

**Comment by jswymer** [comment]
Hello, it would be great if you could share an example, thanks!

**Comment by stefanoPrimo** [comment]
here you are
[ALProject11.zip](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/files/3305133/ALProject11.zip)

**Comment by jswymer** [comment]
Thanks for the examples! I verified your findings and fixed the article. The updated article will be published soon. Thanks for the feedback!

**Comment by git-no** [comment]
@jswymer Documentation is still wrong.

`OnAfterValidateEvent(VAR Rec : Record; VAR xRec : Record; CurrentFieldNo : Integer)`in
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-event-types

should be `OnAfterValidateEvent(VAR Rec : Record; VAR xRec : Record; CurrFieldNo : Integer)` regarding AL runtime, e.g. 5.0.
Please rewrite ** CurrentFieldNo* to **CurrFieldNo**.

Thank you.
