### ISSUE TITLE
API's need to support Multi Company

### ISSUE THREAD

**Issue by m12lrpv** [MicrosoftDocs/dynamics365smb-devitpro-pb#609]
There are multiple API mechanisms for Dynamics Business Central including the OdataV4 (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/web-services) and the new API's (https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/)

In multi Company scenarios the following error will be returned for all api calls where the company is not specified. Note that the default company configured for the logged in user is ignored by all of the API's.

{
    "error": {
        "code": "Internal_CompanyNotFound",
        "message": "Cannot process the request because the default company cannot be found. You can specify a default company in the service configuration file, or specify one for each tenant, or you can add a query string in the form of \"company=[name]\". You can see the available companies by accessing the default OData web service, Company. For more information, see \"OData Web Services\" in Help."
    }
}

For the Odata API's the error can be overcome by specifying the Company in the URI
e.g. https://api.businesscentral.dynamics.com/v1.0/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/odataV4/Company('CRONUS AU')/VendorLedgerEntries

For the new API's however there is no documented way to specify the Company and attempts to implement the OdataV4 solution do not result in success.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The information about which topic you're submitting this on is gone, so I am not sure precisely where you have been searching. Please take a look at this topic and the topics in the See Also section of the [topic](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#calling-the-api) - hope this helps?

**Comment by m12lrpv** [comment]
Thank you. I did find an alternate workaround by adding the company as a request header.
