### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by ShadowXVII** [MicrosoftDocs/dynamics365smb-devitpro-pb#61]
Can we get some examples added to these property pages? This also applies to field properties such as a FlowField CalcFormula.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d90498e-72df-207a-5344-db408659666d
* Version Independent ID: fde80388-7526-f049-8b62-c5dcc2d1e9e8
* Content: [RunPageLink Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-runpagelink-property)
* Content Source: [dev-itpro/developer/properties/devenv-runpagelink-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-runpagelink-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We're currently working on improving the help on properties; we do know that examples are very important for our readers. Stay tuned for updates during the next period. Thanks for your patience.

**Comment by dejanprvulovic** [comment]
What about this and examples?

**Comment by KSH-audibene** [comment]
Also example of RunPageLink needed
