### ISSUE TITLE
Syntax is incorrect

### ISSUE THREAD

**Issue by BrianThorChristensen** [MicrosoftDocs/dynamics365smb-devitpro-pb#610]
The Permissions parameter is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b95b005-f84a-c5e9-47fd-ebd270205cd2
* Version Independent ID: 5c970ad5-6e42-83ce-62dd-b0d117046ce3
* Content: [OnBeforeTestRun Trigger - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/onbeforetestrun-trigger)
* Content Source: [dynamics-nav/OnBeforeTestRun-Trigger.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/OnBeforeTestRun-Trigger.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this has now been fixed.
