### ISSUE TITLE
Few docs errors

### ISSUE THREAD

**Issue by BastienPerdriau** [MicrosoftDocs/dynamics365smb-devitpro-pb#611]
Hi,
There are few errors on the page :
- There are two '/' on both HTTP requests between "companies({companyId})" and "extensions({{packageId}})"
- On the second HTTP request, "uninstall" is written "ininstall"

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 8c85eedc-e483-a6dd-4d59-582aadd79d43
* Version Independent ID: f6f01af5-0aa8-880c-d205-96b7bac459f4
* Content: [Actions on extension - Business Central](https://docs.microsoft.com/fr-fr/dynamics365/business-central/dev-itpro/administration/dynamics-microsoft-automation-extension-post#feedback)
* Content Source: [dev-itpro/administration/dynamics-microsoft-automation-extension-post.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/dynamics-microsoft-automation-extension-post.md)
* Service: **dynamics365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The errors have been fixed and an updated article will be published soon.
