### ISSUE TITLE
please elaborate

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#612]
This page leaves everything to be desired.
Please explain what this actually does, link back to relevant parents and give good examples of use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a36698f-b732-c524-a131-fd487dcb67af
* Version Independent ID: aa9eec60-29f5-b1cb-87cd-ecf449786333
* Content: [GridLayout Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-gridlayout-property)
* Content Source: [dev-itpro/developer/properties/devenv-gridlayout-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-gridlayout-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! We have updated the article with a bit more information about its use and links to relevant articles that provide more info and examples. The updated article will be published soon. Thanks.
