### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#613]
I couldn't find the syntax for the examples that I needed so I ran a FORNAV convertion on Table 112 "Sales Invoice Header".

Here are some more syntax examples that you should add.

Example from table 112 "Sales invoice Header"

	field(46;Comment;Boolean)
        {
            CalcFormula = exist("Sales Comment Line" where ("Document Type"=const("Posted Invoice"),
                                                            "No."=field("No."),
                                                            "Document Line No."=const(0)));
            Caption = 'Comment';
            Editable = false;
            FieldClass = FlowField;
        }

        field(61;"Amount Including VAT";Decimal)
        {
            AutoFormatExpression = "Currency Code";
            AutoFormatType = 1;
            CalcFormula = sum("Sales Invoice Line"."Amount Including VAT" where ("Document No."=field("No.")));
            Caption = 'Amount Including VAT';
            Editable = false;
            FieldClass = FlowField;
        }

        field(166;"Last Email Sent Time";DateTime)
        {
            CalcFormula = max("O365 Document Sent History"."Created Date-Time" where ("Document Type"=const(Invoice),
                                                                                      "Document No."=field("No."),
                                                                                      Posted=const(true)));
            Caption = 'Last Email Sent Time';
            FieldClass = FlowField;
        }

        field(167;"Last Email Sent Status";Option)
        {
            CalcFormula = lookup("O365 Document Sent History"."Job Last Status" where ("Document Type"=const(Invoice),
                                                                                       "Document No."=field("No."),
                                                                                       Posted=const(true),
                                                                                       "Created Date-Time"=field("Last Email Sent Time")));
            Caption = 'Last Email Sent Status';
            FieldClass = FlowField;
            OptionCaption = 'Not Sent,In Process,Finished,Error';
            OptionMembers = "Not Sent","In Process",Finished,Error;
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0887a61-8d1d-916b-7ecf-35d29714dc7c
* Version Independent ID: 804c1bb1-3812-1cf0-be9d-8e59e17e7c87
* Content: [Create FlowFields and FlowFilters - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-flowfields-and-flowfilters)
* Content Source: [dev-itpro/developer/devenv-creating-flowfields-and-flowfilters.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-creating-flowfields-and-flowfilters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @skundaram
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. Similar syntax examples have been added and they will be available in the next doc refresh.
