### ISSUE TITLE
Bad hyperlink

### ISSUE THREAD

**Issue by jnpatrouillault** [MicrosoftDocs/dynamics365smb-devitpro-pb#614]
The link to "Working with Dynamics 365 Business Central in Microsoft Graph" shows the error #404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a9b13de-4074-d2ab-cf6e-9f32f2a257a0
* Version Independent ID: c04f17f7-f1c7-7386-abd1-e0e51a22a473
* Content: [Error Codes - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/dynamics_error_codes)
* Content Source: [dynamics-nav/api-reference/v1.0/dynamics_error_codes.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/dynamics_error_codes.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, the topic this was aiming at is this [one]([Dynamics 365 Business Central in Graph](https://docs.microsoft.com/en-us/graph/api/resources/dynamics-graph-reference?view=graph-rest-beta) 
). The fix will be pushed live with the next refresh. Thanks.
