### ISSUE TITLE
Need a more thorough example

### ISSUE THREAD

**Issue by Verndroid** [MicrosoftDocs/dynamics365smb-devitpro-pb#615]
It would be nice to have more examples of table relations. Something as simple as a relation to another table where a field needs to have a certain value. IE.

Vendor table has a field referring to another table where "vendor no." = Vendor."No." and second field in the primary key is the value that needs to be present ie. "Code". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f5e5473-a086-1d4c-b524-4f977e0d42b1
* Version Independent ID: 8d211600-be52-36b0-ab1c-94f99b53cb73
* Content: [TableRelation Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-tablerelation-property#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-tablerelation-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-tablerelation-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by Verndroid** [comment]
Like this:
TableRelation = "<SomeTable>"."<Some Field>" where ("<SomeFieldinSomeTable>" = field ("<Field in Other Table>"))

**Comment by Verndroid** [comment]
Hmph.
TableRelation = "SomeTable"."SomeFieldNo." where ("SomeFieldNo." = field ("No."))

**Comment by blrobl** [comment]
Hi, thanks for your feedback. Your suggestion has been taken into account and more examples will be available in the next doc refresh.
