### ISSUE TITLE
Should mention based indexing

### ISSUE THREAD

**Issue by JulienDecottignies** [MicrosoftDocs/dynamics365smb-devitpro-pb#616]
Documentation should mention the based indexing of the List type. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c760a1-0ba5-814b-94bf-c50008364769
* Version Independent ID: 235f987b-1062-26ba-81a7-b72ff35c099b
* Content: [List Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/list/list-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/list/list-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/list/list-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The indexing of the List data type is 1-based. It will be updated in the documentation with the next doc refresh.
