### ISSUE TITLE
shippedQuantity is read-only

### ISSUE THREAD

**Issue by hdrodel** [MicrosoftDocs/dynamics365smb-devitpro-pb#617]
for the field 'shippedQuantity' the docs don't mention that it's read-only. 
when i try to pass a value for it, i get an error message saying that it is read-only. 
so maybe the docs need to include that it's read only 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: da32d888-9834-bab6-d951-8490fce676ad
* Version Independent ID: 5c4ffaa9-2c02-2d51-7192-28a48959db61
* Content: [salesOrderLines resource type - Dynamics NAV](https://docs.microsoft.com/de-de/dynamics-nav/fin-graph/resources/dynamics_salesorderline#feedback)
* Content Source: [dynamics-nav/fin-graph/resources/dynamics_salesorderline.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/resources/dynamics_salesorderline.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by hdrodel** [comment]
content source:
https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/resources/dynamics_salesorderline

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This will be fixed with next doc refresh.

**Comment by hdrodel** [comment]
Is it an error in the docs or an error in the API? 
Is it possible to pass salesOrderLines where the items already have been shipped?
