### ISSUE TITLE
"taxAreaDisplayName" should not be included in an example of a request because it is read-only

### ISSUE THREAD

**Issue by momoto** [MicrosoftDocs/dynamics365smb-devitpro-pb#618]
When I send a POST request to create customer object in Dynamics 365 Business Central, while I am following [this page](https://docs.microsoft.com/ja-jp/dynamics-nav/api-reference/v1.0/api/dynamics_create_customer), I get a 400 Bad Reqeust with the message "Control 'taxAreaDisplayName' is read-only."

"taxAreaDisplayName" should not be included in the example of a request in [docs.microsoft.com](https://docs.microsoft.com/ja-jp/dynamics-nav/api-reference/v1.0/api/dynamics_create_customer) because it might be misleaging.

### Dynamics 365 Business Central Version:

Version: Platform 14.0.29530.33541 + Application 32861 (US Dynamics NAV 14.0)

### Reproduce steps

Send a POST to an entity set and pass a property with "taxAreaDisplayName".

### Additional detail

This issue is in regard to https://docs.microsoft.com/ja-jp/dynamics-nav/api-reference/v1.0/api/dynamics_create_customer

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7e2ab60b-409a-98cf-3730-ec11262c8608
* Version Independent ID: 1b5d4e76-bb2a-8621-c03d-107cc906fd78
* Content: [Create customers - Dynamics NAV](https://docs.microsoft.com/ja-jp/dynamics-nav/api-reference/v1.0/api/dynamics_create_customer#feedback)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_create_customer.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_create_customer.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This will be fixed with the next doc refresh.
