### ISSUE TITLE
The type or method 'CreateOutStream' cannot be used for 'Extension' development.AL(AL0296)

### ISSUE THREAD

**Issue by CorpitalMAS** [MicrosoftDocs/dynamics365smb-devitpro-pb#619]
The type or method 'CreateOutStream' cannot be used for 'Extension' development.AL(AL0296)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feedc94d-9103-2eed-c25f-d37a4d6ed59e
* Version Independent ID: 37a5139b-1be5-a72e-47d3-ef201c59088d
* Content: [RunRequestPage Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-runrequestpage-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/report/report-runrequestpage-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/report/report-runrequestpage-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. File data type methods, including File.CREATEOUTSTREAM, File.CREATE and File.CLOSE methods are only supported in Business Central on-premises, and therefore this compile error while pop up when using the online version. The documentation will be updated to reflect this.
