### ISSUE TITLE
Chart errors

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#62]
In the chart above, either the blank areas need to be filled in for customers 10010 and 10040 or the balances in the top half need to be changed to 50 and 200 respectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 345b82cd-94d8-687b-071d-71921ac6ddd9
* Version Independent ID: fde1756e-b7dd-8569-c2ff-da4e39596fdf
* Content: [FlowFields - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/flowfields)
* Content Source: [dynamics-nav/FlowFields.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/FlowFields.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, thanks for your feedback. The diagram has been corrected and the fix will be published soon!
