### ISSUE TITLE
Is bearer token the only available Authorization header?

### ISSUE THREAD

**Issue by aguayUmbt** [MicrosoftDocs/dynamics365smb-devitpro-pb#620]
I think my title resume my thoughs pretty much. I'd like if I could post an invoice with NTLM credentials?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fd9ab27-0901-40fe-62e5-3b139b29533d
* Version Independent ID: 8b5b87fd-6fc8-c58e-0a45-674ec28651db
* Content: [Create salesInvoices - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/api/dynamics_create_salesinvoice#feedback)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_create_salesinvoice.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/api/dynamics_create_salesinvoice.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset.
