### ISSUE TITLE
Property is ignored on Webclient

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#621]
It looks like this property doesn't work on WebClient (as of Spring release 2019). My Tests show that its always rendered in Columns-Mode. On RTC, it works as documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a36698f-b732-c524-a131-fd487dcb67af
* Version Independent ID: aa9eec60-29f5-b1cb-87cd-ecf449786333
* Content: [GridLayout Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-gridlayout-property)
* Content Source: [dev-itpro/developer/properties/devenv-gridlayout-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-gridlayout-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, the details for which topic you are referring to are gone - can you please add that information? Thanks.

**Comment by CptBlaubart** [comment]
sorry, might be my mistake, i added it again

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry about the waiting time. The note at the bottom says that only columns work on the Web client: "....In the Business Central Web client, fields can only be arranged in columns.". Is this not what you're experiencing?

**Comment by CptBlaubart** [comment]
Hi,
Yeah, that got added by the 1st of August. The documentation is technically correct now.

As "columns" is the default value anyway, you could argue that the property doesn't have any effect on the webclient at all. Or you could argue that it it's ab bug in need of fixing on the Webclient. - We rebuilt the affected Pages already. - Looks a little odd, but i don't know how it would've looked in rows-mode.

Do you want me to close the Issue, or would you like to keep it open so you can forward it to the Devs?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. To create a bug for the devs, you must go to the [AL repo](https://github.com/microsoft/AL) and open a GitHub issue - sorry for the hassle, I cannot transfer it from this repo. I will then close this issue. Thanks again!
