### ISSUE TITLE
this talks about Nav

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-devitpro-pb#623]
is this an old document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe75bfd-75ef-7c5c-1941-35be513b847a
* Version Independent ID: 0b4354b3-f1cc-2249-ed5a-d7683deedbdb
* Content: [Classifying Data in Dynamics NAV - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/classifying-data)
* Content Source: [dynamics-nav/classifying-data.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/classifying-data.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by blrobl** [comment]
Hi, this is an article from the NAV docset, therefore it is supposed to talk about Dynamics NAV. Did you want to refer to another article, maybe?

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. To read about classifying data in Business Central, please see [this article](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-classifying-data-sensitivity).

**Comment by makdaddy8888** [comment]
Hello
I tried to submit feed back for this page 

https://docs.microsoft.com/en-us/dynamics365/business-central/hr-how-register-employees#to-register-various-information-about-an-employee

But when I log in and try to submit feedback I get this error 

“There is currently no feedback for this document. Page feedback will appear here.”

Can I ask for some additional features be shared on this page relating to the hr module and some of the more advanced features in HR?

Kind Regards
Ben Opit
+61411707070
