### ISSUE TITLE
No explanation or links to actual filter groups

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#624]
Unfortunately, the current page is not helpful at all. Please provide all information as it was available the old online help page: https://docs.microsoft.com/en-us/dynamics-nav/filtergroup-function--record-#remarks
Thank you :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2049a29b-bb48-8d52-74a6-dfdfc761c504
* Version Independent ID: 43738a03-e128-6a4f-d07f-39af3267b75a
* Content: [FilterGroup Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-filtergroup-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-filtergroup-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-filtergroup-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
The content has been ported over and will be available with the next refresh. Thanks!
