### ISSUE TITLE
Code to add field to field group does not compile

### ISSUE THREAD

**Issue by josephgress2** [MicrosoftDocs/dynamics365smb-devitpro-pb#625]
I tried to use the following code from this "Field Groups (Drop-Down Controls)" page in an extension

tableextension 50100 CustomerExercise extends Customer
{
    fields
    {
        field(50100); "V02Max"; Decimal) { }
    }
   
    fieldgroups
    {
        addlast(DropDown; V02Max) { }
    }
}

However, Visual Studio Code is giving an error on the word fieldgroups.  The error is "Syntax error.'}' expected.'   I am using NAV 2018 cumulative update 8.  Is this fieldgroups control only available in Business Central?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9979b71-a2f9-9032-5bba-161f6da5ff63
* Version Independent ID: 7fd0115f-bfec-43e1-e5c3-69bf2e4d383c
* Content: [Field Groups - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-field-groups#feedback)
* Content Source: [dev-itpro/developer/devenv-field-groups.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-field-groups.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback - I'm afraid there's a syntax error in the example above, it should be:

tableextension 50107 CustomerExercise extends Customer
{
fields
{
field(50100; "V02Max"; Decimal) { }
}

fieldgroups
{
    addlast(DropDown; V02Max) { }
}
}

Can you make that work? The docs will be updated and refreshed with the next push. Thanks!

**Comment by josephgress2** [comment]
Thanks Susanne,

I tried the exact code that you provided and am still getting the same error.  Here is a screen shot showing the code and the problems

[cid:image002.jpg@01D53708.C23DBE30]

I found the following blog post regarding when the ability to add a field to a field group was added.

https://cloudblogs.microsoft.com/dynamics365/no-audience/2018/08/31/developer-preview-august-2018/?source=nav

The article says that this feature was added to the August 2018 cumulative update.  It turns out that we are on that cumulative update for NAV 2018.   Would you let me know whether this is available in NAV 2018 or only in Business Central?  If it was not in the August 2018 cumulative update for NAV 2018, was it added to a later cumulative update?

Thanks,

Joseph Gress

**Comment by SusanneWindfeldPedersen** [comment]
Hello again, sorry that didn't work. I believe that from March, 2018 we announced that the preview features were not available with the next cumulative updates: "Please note, that the improvements announced in this blog post are not available in Dynamics NAV 2018 and the following cumulative updates of Dynamics NAV 2018." from the [March Update](https://cloudblogs.microsoft.com/dynamics365/no-audience/2018/03/23/developer-preview-march-update/?source=nav), this unfortunately just wasn't repeated in the blog post that you're referring to from August 2019.  Thanks, Susanne.
