### ISSUE TITLE
Redundant description of method 'Get'

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-devitpro-pb#626]
Since the DataScope parameter in the first definition of 'Get' is an optional value, the second definition, Get(String, var Text) , is redundant - it is a special case of the first description. I think it should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2ae4de-5a6f-eff6-1d10-93266bc9df6b
* Version Independent ID: 290ea4c9-e2e3-14bf-9d05-451e13ab5946
* Content: [IsolatedStorage Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/isolatedstorage/isolatedstorage-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/isolatedstorage/isolatedstorage-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/isolatedstorage/isolatedstorage-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, these topics are autogenerated from the code source and this is what our current tooling provides.
