### ISSUE TITLE
Syntax issues in the 'Method name' column

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-devitpro-pb#627]
Since the square brackets indicate optional parts, the syntax of all methods containing the [DataScope] part is wrong: if you omit the DataScope, you also MUST omit the comma in front. So the items in the 'Method Name' column should be:

Set(String, String  [, DataScope])
Get(String [, DataScope], var Text)
Contains(String [, DataScope])
Delete(String [, DataScope])
SetEncrypted(String, String [, DataScope])

Please note that this effects the linked detail pages, too; the syntax there has the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2ae4de-5a6f-eff6-1d10-93266bc9df6b
* Version Independent ID: 290ea4c9-e2e3-14bf-9d05-451e13ab5946
* Content: [IsolatedStorage Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/isolatedstorage/isolatedstorage-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/isolatedstorage/isolatedstorage-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/isolatedstorage/isolatedstorage-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. It is true, and it has been fixed for this article and all the other data type articles. It will be available soon.
