### ISSUE TITLE
Task 14 Misleading description??

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#628]
The task says:
Task 14: Publish and install/upgrade extensions
Complete this task if you are upgrading from a Microsoft Dynamics NAV 2018 deployment that uses V2 extensions or a Denmark (DK) version of Microsoft Dynamics NAV 2017 or earlier.

But earlier in Task 2, regardless of version or region, we uninstall all extensions, the statement indicates we do not reinstall the extensions we uninstalled but that is not true.

Can this be reworded to be clearer?  Maybe a separate step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fdac4a-82ce-2bce-6ebe-d40241f4b715
* Version Independent ID: ee365d3f-f0df-c3e2-7a87-833a84dc9496
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! We have made some changes to the article, and separated a couple of steps, We hope this makes thing more clear. The update will be published soon.
