### ISSUE TITLE
API returns the data type int and not a GUID for G / L Entry property id.

### ISSUE THREAD

**Issue by michael-toolpack** [MicrosoftDocs/dynamics365smb-devitpro-pb#63]
Maybe I'm making an error, but it seems that the API returns the data type int and not a GUID for G / L Entry property id.

I use the API endpoint: https://api.businesscentral.dynamics.com/v1.0/{tenant}/api/beta/
and the company I use is Cronus demo account.

Is it correct that I am using this G / L Entry ID GUID to retrieve dimension lines via the method:

GET / business center / companies ({id}) / dimensionLines? $ Filter = parentId eq ({id})

This does not work if the G / L Entry Object ID is not a GUID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d38b12d6-3fd3-5667-9f33-3777baa8c750
* Version Independent ID: d6fd3545-94f5-ec09-cfe9-d99329a4096c
* Content: [generalLedgerEntries resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/resources/dynamics_generalledgerentries)
* Content Source: [dynamics-nav/fin-graph/resources/dynamics_generalLedgerEntries.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/fin-graph/resources/dynamics_generalLedgerEntries.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
This is not supported for G/L entries. We're only supporting dimensions for gen. journal line. 
But please let me know what your usecase.

**Comment by michael-toolpack** [comment]
I want to get information on what dimensions are used for in relation to the finance postings. 

Journal & Journal line are a mediate step before the will be posted ad G/L Entries right? 
And I can surely see the dimension values are supported when I get JournalLines, but is that information for finance postings not supported ? and will it be supported in the near future ?

**Comment by michael-toolpack** [comment]
basically I want you extract data from your API, that enables the user to create financial posting reports where they can filter on their dimensions

**Comment by michael-toolpack** [comment]
@henrikwh can you reply on my comments?

**Comment by henrikwh** [comment]
Thanks Michael.
We will investigate the possibility to expose dimensions on the generalLedgerEntries api in the future.

To unblock you for now, we're shortly releasing the possibility to create your own apis. PageType = API will be avaliable. From there, you can expose whatevery you want. You can publish the extension as a per tenant extension.
