### ISSUE TITLE
Mentioning Page Extensions

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#632]
Could information be added about whether all or which of all these are available on Table Extensions?
As per VS Code compiler, I can e.g. use both OnDelete, OnBeforeDelete, OnAfterDelete and I do not find any information about them, nor in which order table extension triggers are executed against the standard table triggers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8a0a4d-a5ee-0e97-fb86-838f5aea4394
* Version Independent ID: cbefe940-1d8e-5340-f733-4c701db41f68
* Content: [Table and Field Triggers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-table-and-field-triggers)
* Content Source: [dev-itpro/developer/triggers/devenv-table-and-field-triggers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-table-and-field-triggers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. Documentation for the table extension triggers has been added and it will be available soon.
