### ISSUE TITLE
probably copy paste error

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#634]
hi,

DeleteAllowed Property:
Syntax: shows "DelayedInsert = false;"

should probably be: "DeleteAllowed = false;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd1a5d31-3531-be2d-920d-c1f3a6367469
* Version Independent ID: 918b5cee-1af1-7e39-f043-1552d2535e4d
* Content: [DeleteAllowed Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-deleteallowed-property)
* Content Source: [dev-itpro/developer/properties/devenv-deleteallowed-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-deleteallowed-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching and reporting this - will be fixed with the next refresh.
