### ISSUE TITLE
Update Program Files path

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#635]
Since this article is for BC, the code sample could contain an updated installation path rather than ProgramFiles(x86)\Microsoft Dynamics NAV\90\RoleTailored Client\ ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ee4209-504a-27f8-4ebb-328973820b24
* Version Independent ID: 727e8c0a-57b6-39d4-f654-38233e820977
* Content: [Merging Application Objects using the Example Scripts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/merging-application-objects-using-the-example-scripts)
* Content Source: [dev-itpro/upgrade/Merging-Application-Objects-using-the-Example-Scripts.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Merging-Application-Objects-using-the-Example-Scripts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for pointing this out, the sample path has been updated.

**Comment by blrobl** [comment]
Hi, thanks for your feedback! The path has been updated.

**Comment by NKarolak** [comment]
The explaining text has been updated, but the code sample has not:
```
Import-Module "${env:ProgramFiles(x86)}\Microsoft Dynamics NAV\90\RoleTailored Client\Microsoft.Dynamics.Nav.Model.Tools.psd1" -force  
  
Get-Help "NAV"  
```

**Comment by blrobl** [comment]
The code sample was also updated, but it will not be visible until the next doc refresh.
