### ISSUE TITLE
RefDate is incorrect format

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#637]
RefDate := 052196D;

According to my system the date format must be yyyymmddD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d65f69c7-46fa-a9a3-81c4-f8345708274f
* Version Independent ID: 5224c809-0335-71aa-e1fb-66ce32f6669f
* Content: [CalcDate Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-calcdate-string-date-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-calcdate-string-date-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/system/system-calcdate-string-date-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This is true, and the date format of the example has been corrected.
