### ISSUE TITLE
OnAssistEdit is not shown in web client

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#638]
Hi,

You need to set the property AssistEdit = true in order for the AssistEdit to be shown.
https://github.com/Microsoft/AL/issues/4477

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff1d5388-27bb-4bc9-7c1c-92d91073ed93
* Version Independent ID: 53495f8f-b5b8-cf1a-7d8f-1b0b518fbca6
* Content: [OnAssistEdit Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onassistedit-trigger)
* Content Source: [dev-itpro/developer/triggers/devenv-onassistedit-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onassistedit-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for the feedback, a note of that has been added to the article.
