### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by gary-PSSI** [MicrosoftDocs/dynamics365smb-devitpro-pb#639]
The Arranging Rows and Columns on a Fasttab link does not point to the correct page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 605a1acd-e3b5-7f1b-bdc8-335ff00fb141
* Version Independent ID: 7eb6b1f3-55f5-8ec0-d5fc-89d82decea57
* Content: [Adding a FactBox to a Page - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-a-factbox-to-page#feedback)
* Content Source: [dev-itpro/developer/devenv-adding-a-factbox-to-page.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-a-factbox-to-page.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this, the link has been fixed.
