### ISSUE TITLE
Snippets should reference page object, not table object

### ISSUE THREAD

**Issue by gary-PSSI** [MicrosoftDocs/dynamics365smb-devitpro-pb#640]
In the snippets section, I believe the sentence 'Typing the shortcut tpageext will create the basic layout for a table object when using the AL Language extension in Visual Studio Code.' should be 'Typing the shortcut tpageext will create the basic layout for a **page** object when using the AL Language extension in Visual Studio Code.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdda7e30-30d9-ac83-abf7-267a7f634c6d
* Version Independent ID: 5bf5ce87-f59a-d2ae-10b3-05eda02406b5
* Content: [Page Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object#feedback)
* Content Source: [dev-itpro/developer/devenv-page-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. That was indeed a typo. It has been fixed now.
