### ISSUE TITLE
Circular link

### ISSUE THREAD

**Issue by gary-PSSI** [MicrosoftDocs/dynamics365smb-devitpro-pb#642]
The Numeric Property Properties link refers to itself

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e4674f-88bb-2fed-e110-3995500284cc
* Version Independent ID: 3b06b603-5996-3e72-95f8-a785757ca3e3
* Content: [Numeric Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-numeric-property)
* Content Source: [dev-itpro/developer/properties/devenv-numeric-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-numeric-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this has been fixed.
