### ISSUE TITLE
Invalid list in example code

### ISSUE THREAD

**Issue by gary-PSSI** [MicrosoftDocs/dynamics365smb-devitpro-pb#643]
I believe, based on the comments below this example that ValuesAllowed = Codeunit, Page, Query; should be ValuesAllowed = Codeunit,Page,Query; with no spaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56fb5e69-25e1-75f4-d3eb-85c0d141c867
* Version Independent ID: 29ca6e75-90fa-9460-6337-a0480cd8bbe4
* Content: [ValuesAllowed Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-valuesallowed-property)
* Content Source: [dev-itpro/developer/properties/devenv-valuesallowed-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-valuesallowed-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. It does not really make a difference for the compiler whether there is a space or not. Indeed, by default, the AL formatter includes spaces for a better visualization.
