### ISSUE TITLE
See Also

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#644]
A See Also reference to the SETRECORD function might be appropriate here, as well as a note distinguishing the use of the two functions SETTABLEVIEW and SETRECORD. For instance--what would be the effect of calling both on a page before calling the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2031e754-4cb8-f3b7-b0f4-40e1c99f2cdb
* Version Independent ID: b72fe45a-b0ab-9744-5f26-c3e80a2377f3
* Content: [SETTABLEVIEW Function (Page, Report, XMLport) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/settableview-function--page--report--xmlport-)
* Content Source: [dynamics-nav/SETTABLEVIEW-Function--Page--Report--XMLport-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SETTABLEVIEW-Function--Page--Report--XMLport-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset.
