### ISSUE TITLE
SubPageLink reference could use a syntax example

### ISSUE THREAD

**Issue by bctails** [MicrosoftDocs/dynamics365smb-devitpro-pb#645]
SubPageLink reference could use a syntax example.

for example:

`sorting("No.") where ("Item Category Code"=filter('Computers'));`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: babe9dc8-8278-49b7-3f8a-0bc75dd8307b
* Version Independent ID: 7cf185fd-3e0e-6d5f-7ed4-8a3773534357
* Content: [SubPageView Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-subpageview-property)
* Content Source: [dev-itpro/developer/properties/devenv-subpageview-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-subpageview-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback. We have added a syntax example. The update will be published soon.

**Comment by bctails** [comment]
Thanks a lot!

Hartelijke groet,
Kevin O’Garro
Tel: +31613040029

Sent from my iPhone

On 5 Aug 2019, at 11:31, jswymer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, thanks for the feedback. We have added a syntax example. The update will be published soon.
