### ISSUE TITLE
"Should"?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#647]
Ok
(Boolean) Indicates whether a new record should be inserted.
Could we have some clarification around the meaning of "should" in this context? Do we mean should as in "it would be a good thing", or "you really ought to do this thing"? It just seems a little weird to be speaking in terms of moral imperatives with regard to database record insertions.

Also:

BelowxRec
(Boolean) This return value indicates whether the new record was inserted
First, it takes several readings to understand that BelowxRec as a Boolean must be a parameter passed to the function by reference, because "return value" generally appears to the Left of the := sign. Second, the "was" would indicate that the record has already been inserted, which would render the "new record should be inserted" kind of meaningless. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58818b9-335a-585f-1eac-99b646314820
* Version Independent ID: a784071a-318c-dd92-8748-ecea7a875295
* Content: [OnInsertRecord Trigger - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/oninsertrecord-trigger)
* Content Source: [dynamics-nav/OnInsertRecord-Trigger.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/OnInsertRecord-Trigger.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! I agree. The article has been changes and an update will be published soon.
