### ISSUE TITLE
Inconsistent terminology

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#648]
"Runs after a new record is initialized...Use this trigger to initialize a new record"--presumably this corresponds to the RECORD.INIT function.  But then
"This return value indicates whether the new record was inserted...If false, the record was inserted..." implies the RECORD.INSERT function. The "was inserted" construct reinforces this inference. But I do not believe that an INSERT has actually been executed. I can perform functionality in the OnNewRecord trigger that modifies record values but no record actually has been created in the table. It might be clearer, if I am correct, to use language like "Runs after a new record is initialized, but before it is INSERTED as a table record" instead of "before users can make entries", which is rather ambiguous--make entries where? To what? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8994cf0f-03b0-dc0d-b8c2-0d779fe57536
* Version Independent ID: ad69cc66-6c84-1a21-5d07-1a11540370c3
* Content: [OnNewRecord Trigger - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onnewrecord-trigger)
* Content Source: [dev-itpro/developer/triggers/devenv-onnewrecord-trigger.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-onnewrecord-trigger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, I agree with your assessment. The article has been updated and it will be published soon. Thanks for the feedback!
