### ISSUE TITLE
Example section typo

### ISSUE THREAD

**Issue by AndriiHrynyuk** [MicrosoftDocs/dynamics365smb-devitpro-pb#649]
Hi,
The following example 'finsql.exe command=getbuildversion.txt, file=C:\temp\navbuildversion.txt, logfile= C:\temp\navbuildversionlog.txt' has a .txt extension appended to the command name. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffac18cd-6327-606a-a946-ba247246fc8e
* Version Independent ID: 8ed1d13b-20db-9784-cde3-6a2efd981490
* Content: [GetBuildVersion - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/getbuildversion#feedback)
* Content Source: [dynamics-nav/GetBuildVersion.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/GetBuildVersion.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The error has been fixed and an update will be published soon.
