### ISSUE TITLE
PATCH baseUnitOfMeasure on Item

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/dynamics365smb-devitpro-pb#650]
When I try to patch item with different baseMeasure it doesn't work.
With doesn't work I mean I sent BaseUnitOfMeasureId with the patch.

For example I patch with the following payload

PATCH 
https://api.businesscentral.dynamics.com/v1.0/api/v1.0/companies(<redacted>)/items(<redacted>)

> {"baseUnitOfMeasureId":"32c97035-91a7-4e3a-b845-9b30c7d488b5","number":"GA400028","displayName":"Displayname  Hulst","type":"0","blocked":false,"gtin":"8888847598151","unitPrice":54.95,"priceIncludesTax":true,"itemCategoryId":"<ItemCategoryID"}

I get a 200 OK with the following payload back, BaseMeasureOfUnit isn't changed, it returns the old GUID. Am I missing something in the Payload?

{
    "@odata.context": "https://api.businesscentral.dynamics.com/v1.0/api/v1.0/$metadata#companies(<redacted>)/items/$entity",
    "@odata.etag": "W/\"J"",
    "id": "<redacted>",
    "number": "GA400028",
    "displayName": "DisplayName",
    "type": "Inventory",
    "itemCategoryId": "5fba219d-c16e-4520-b75e-7cf9fd82d1ff",
    "itemCategoryCode": "286",
    "blocked": false,
    "baseUnitOfMeasureId": "532f9d10-4d1e-4cea-a3f2-b58e5edf29bd",
    "gtin": "8718247598151",
    "inventory": 0,
    "unitPrice": 54.95,
    "priceIncludesTax": true,
    "unitCost": 0,
    "taxGroupId": "00000000-0000-0000-0000-000000000000",
    "taxGroupCode": "",
    "lastModifiedDateTime": "2019-07-17T12:28:02.33Z",
    "baseUnitOfMeasure": {
        "code": "ST",
        "displayName": "Stuks",
        "symbol": null,
        "unitConversion": null
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4928f81-a6fd-b80b-de8d-cd8e3e170c3d
* Version Independent ID: 120c6f3e-88cd-2037-e84d-f6e5588c53b2
* Content: [Update items - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_item_update)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_item_update.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_item_update.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by Mr-Pingu** [comment]
Any update?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for the long wait. I hope you found a solution. This is more of a product question, that we're not able to help with, please use your usual support channel. Thanks for your understanding.
