### ISSUE TITLE
Misc suggestions

### ISSUE THREAD

**Issue by gary-PSSI** [MicrosoftDocs/dynamics365smb-devitpro-pb#651]
1. When first starting to use Visual Studio Code, it is not at all intuitive how to open the equivalent of a new Visual Studio project. The page starts with instructions on how to create a table. I would suggest
    a. Start by invoking the New Window command in Visual Studio Code
    b. Then navigate to a folder
    c.  Then begin with the table creation code above
2. There is no mention of what to name the files being created
    a. Based on Best Practices, I would suggest that the file name to be used should be included
3. Add some screenshots of the Visual Studio Code 
4. Add a download of the finished code so that if something is broken in my code I can compare to see what caused the problem
Overall, this is a very good walkthrough

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc13a127-253d-6438-52ed-319589d8d3ec
* Version Independent ID: 9bcc413c-55cb-a0e0-8ca2-f111658076fe
* Content: [Building your first sample extension that uses new objects and extension objects - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-example)
* Content Source: [dev-itpro/developer/devenv-extension-example.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-example.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, sorry for getting back late. We will be looking at updating our getting started content, and we'll consider your suggestions. Thanks.
