### ISSUE TITLE
Incorrect description of CompanyName parameter

### ISSUE THREAD

**Issue by gkakanauskas** [MicrosoftDocs/dynamics365smb-devitpro-pb#654]
CompanyName parameter description is incorrect (copied from Import-NAVData)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d9ee4af-c9b5-97bd-2a20-6dd91f781ccb
* Version Independent ID: d828c63c-2a4a-9791-96d9-3aa4e0a594d4
* Content: [Export-NAVData (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.Dynamics.Nav.Management/Export-NAVData?view=businesscentral-ps#feedback)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Management/Export-NAVData.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Management/Export-NAVData.md)

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
