### ISSUE TITLE
Le nom de type ou d'espace de noms 'Customer' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?

### ISSUE THREAD

**Issue by gtrennert** [MicrosoftDocs/dynamics365smb-devitpro-pb#655]
The following errors are appearing when using your code example.
What am I missing ? Is this code example in your article correct ?

1)
The instruction :
> foreach (**Customer** customer in customers)
generates the following error : 
"Le nom de type ou d'espace de noms '**Customer**' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?"
Translation by me : The name of type or namespace 'Customer' cannot be found

2)
The instruction :
> private static void PrintCustomersCalledCust(NAV.NAV nav)

Un espace de noms ne peut pas contenir directement des membres tels que des champs ou des méthodes
Translation by me : A namespace cannot contain directly members such as fields or methods

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ab2d51-62c3-fa9a-7a3f-556097ef3c43
* Version Independent ID: a93c5d06-2ca9-f8d5-7b49-b69429e7f613
* Content: [Walkthrough: Creating and Interacting with a Page Web Service (OData) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--creating-and-interacting-with-a-page-web-service--odata-)
* Content Source: [dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, I got this working, but I had to make sure that the OData V3 endpoint was enabled on the server and I was using the OData V3 url. This will not work with the V4 endpoint.

**Comment by gtrennert** [comment]
I don't know how you succed the adding of connected services because I can't : 
I get this error message : _cannot access https://instance:port/NAV/OData/$metadata_
And if I try to use the workaround proposed by some : saving the xml file
_Erreur :Échec de l'ajout de OData Connected Service au projet : La valeur ne peut pas être null.
Nom du paramètre : path1_

**Comment by gtrennert** [comment]
I just tried with VS2019 same issue with odata connected service
I also tried unchase odata connected service and here I have this issue : 
Generating Client Proxy for OData V3...
Erreur :Échec de l'ajout de Unchase OData Connected Service au projet : Le schéma spécifié n'est pas valide. Erreurs : 
(0,0) : erreur 0005: L'attribut 'Name' n'est pas valide - La valeur '_Balance_LCY_Payment_in_progress_LCY' n'est pas valide selon son type de données 'http://schemas.microsoft.com/ado/2007/05/edm:TSimpleIdentifier' - Échec de la contrainte Pattern.

**Comment by jswymer** [comment]
Hello, I recently gotten this to work using Visual Studio 2019. A couple corrections have been made to the article. However, the issue about Nom du paramètre : path1 might be an issue with the OData Connected Service, and not an issue specific to Dynamics NAV. You might want to look at this public repo [https://github.com/OData/lab](https://github.com/OData/lab) for a possible solution.

**Comment by jswymer** [comment]
The article should now be up-to-date, so we will close this issue. If you have more feedback, feel free to comment and I will reopen the issue. Thanks!
