### ISSUE TITLE
Only as Administrator ?

### ISSUE THREAD

**Issue by KDGundermann** [MicrosoftDocs/dynamics365smb-devitpro-pb#656]
When you want to see  navcommandresult.txt 
you have to run  finsql  Command=generatesymbolreference as Administrator,
as a normal user has normally no rights to write in the installation folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 156ead7e-1ab8-d9fb-44ca-e9029435e5a6
* Version Independent ID: 5a6899ff-c91d-d2ab-b3d6-0153808a106f
* Content: [Running C/SIDE and AL Side-by-Side - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side)
* Content Source: [dev-itpro/developer/devenv-running-cside-and-al-side-by-side.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-running-cside-and-al-side-by-side.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! You are correct. The article has been fixed and an update will be publishes soon.
