### ISSUE TITLE
XMLNode works very different than it used to, but how?

### ISSUE THREAD

**Issue by bctails** [MicrosoftDocs/dynamics365smb-devitpro-pb#658]
XML Node works very different than it used to, but how?
For instance, getting any data on childnodes is now impossible because XMLNode.HasChildNodes does not exist any more. XMLNode.Name is also not available so I cannot verify where I am in the XML Document.

More documentation and/or examples is necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cf9b387-7dc0-5355-ef60-c53cab899554
* Version Independent ID: a868498d-3cc2-1bd1-00e5-8d0ffd52fcc8
* Content: [XmlNode Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/xmlnode/xmlnode-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/xmlnode/xmlnode-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/xmlnode/xmlnode-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, and sorry for the late reply. We know that a lot of the reference can benefit from more examples, and we're adding examples where we can. This is on our backlog, and we prioritize it accordingly. Thanks.
