### ISSUE TITLE
Wildcard * filter doesnt work

### ISSUE THREAD

**Issue by TheDoubeD** [MicrosoftDocs/dynamics365smb-devitpro-pb#659]
Doing a SETFILTER like the this doesnt work:
Item.SETFILTER(Description, '\*%1\*', 'door');

The filter set to the field Description is literally "\*%1\*"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6bafa7-ca3f-87f1-872c-c74cf6ef8294
* Version Independent ID: 066b6f8b-6444-3f1f-6e31-ecd8047cc8aa
* Content: [SETFILTER Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/setfilter-function--record-#feedback)
* Content Source: [dynamics-nav/SETFILTER-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SETFILTER-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by Andri-Wianto** [comment]
Item.SETFILTER(Description, '%1', '*door*');

**Comment by TheDoubeD** [comment]
Could you explain you answer a little bit?

**Comment by Andri-Wianto** [comment]
Item.SETFILTER(Description, '%1', '*' + door + '*');

**Comment by TheDoubeD** [comment]
Ah, thanks - I will try that

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for the long wait. I think you've come across an error in the product and I suggest that you file a bug for this. Thanks for catching this.

**Comment by imrgroup-ad** [comment]
@SusanneWindfeldPedersen - how about you filing a bug report... would be faster.
