### ISSUE TITLE
Business Central SOAP Authorization for AAD Guest Accounts

### ISSUE THREAD

**Issue by zpfaltersack** [MicrosoftDocs/dynamics365smb-devitpro-pb#66]
Hello,
We have some users that have access to multiple Business Central tenants through a single AAD account that has been added as a Guest to AAD/Business Central. This works fine for the web client but SOAP services rejects them across the board with authentication/authorization errors. I don't see any known issues listed around this type of setup. Is this a use-case that is expected to be supported?

Thanks,
Zachary

**Comment by jswymer** [comment]
Hello Zachery,

As long as the users have a valid license, this should work. I spoke with our development team who confirmed that this a supported scenario. So this might be a bug. We will investigate this in more detail. and provide a fix at some point as required. 


Thanks for the feedback.

**Comment by jswymer** [comment]
Hello Zachery,

The development team tested this functionality, and it worked for them. However, this might be an issue that with a specific scenario. If you could provide some more details about your scenario, I could pass the information on, and they could take another look.

Thanks
John
