### ISSUE TITLE
Sorting not mentioned

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#660]
Please compare this article with with https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-setcurrentkey-setrange-setfilter-getrangemin-and-getrangemax-methods#setcurrentkey-method. I think this should be added to the introducing sentence:
- the main purpose is for sorting 
- selecting key: "if possible".

The most information should be found in this, current article instead of in the linked article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3deb3a10-af88-008f-dbf0-3cd797f4c0c4
* Version Independent ID: 0d3690ac-c99d-0ad7-d803-c72132e90b34
* Content: [SetCurrentKey Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setcurrentkey-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-setcurrentkey-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-setcurrentkey-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback. The article has been updated according to you suggestions. The update will be published soon.
