### ISSUE TITLE
Broken Link for SETCURRENTKEY

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#661]
(Actually, all mentioned method names should we written without capitals)

In section "SETCURRENTKEY Method", at the end: "For more information about this method, see SetCurrentKey Method (Record)." But the link seems to be broken, it leads to "Data Types and Methods in AL".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e600284-07c3-67bd-bf11-5c1f2acd5432
* Version Independent ID: 618552ae-0e4e-e124-1fa2-33b6f2a86c7c
* Content: [SETCURRENTKEY, SETRANGE, SETFILTER, GETRANGEMIN, and GETRANGEMAX Methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-setcurrentkey-setrange-setfilter-getrangemin-and-getrangemax-methods#setcurrentkey-method)
* Content Source: [dev-itpro/developer/devenv-setcurrentkey-setrange-setfilter-getrangemin-and-getrangemax-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-setcurrentkey-setrange-setfilter-getrangemin-and-getrangemax-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, the link has been fixed in the next update. Thanks for the feedback!
