### ISSUE TITLE
Wrong indentation and typo in example code

### ISSUE THREAD

**Issue by GeWuNAV** [MicrosoftDocs/dynamics365smb-devitpro-pb#662]
Hi,
the definition of parameter "Direction" is not intented correctly.
Line "ROUND(1234.56789, 0.001, &gt;) returns 1,234.568" uses &gt; instead of '&gt;'. Should be of type text.
Thank you!
BR GeWU

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 091d0fe9-dbf6-d88d-e249-2af7fc843349
* Version Independent ID: 79b672fd-e549-f1f8-b94f-1f3d5d55cebe
* Content: [ROUND Function (Decimal) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/round-function--decimal-#feedback)
* Content Source: [dynamics-nav/ROUND-Function--Decimal-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/ROUND-Function--Decimal-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! An update will be published soon.
