### ISSUE TITLE
What is a SubType Group

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#664]
"To define the rows and columns of fields, you add SubType Group controls to the Group control". 
Can you please explain how one would add a SubType Group to a Group Control.  The only SubTypes listed in the Designer are Group, Repeater, CueGroup, FixedLayout, and GridLayout. "Add a Subtype Group" implies that a SubType Group is a type of Group. But there does not appear to be such a type of Group. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10104440-fe72-0332-8908-859377294d6c
* Version Independent ID: 8668d4e8-ccc3-577b-73d0-726f2b99eaac
* Content: [Layout Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-layout-property)
* Content Source: [dev-itpro/developer/properties/devenv-layout-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-layout-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback. I agree, with your assessment. There is no Subtype group. The paragraph has been rewritten and an update published soon.
