### ISSUE TITLE
INIT example says FIELDNAME()

### ISSUE THREAD

**Issue by HmmPeculiar** [MicrosoftDocs/dynamics365smb-devitpro-pb#665]
The example for the INIT function is the following:
Name := Record.FIELDNAME(Field)

It should probably contain the INIT function ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e54b3b62-4f19-e3d2-bfdb-a2d25fcaaa4b
* Version Independent ID: a41072e5-ccb0-0795-aef5-bafcdf30c3af
* Content: [CALCFIELDS, CALCSUMS,FIELDERROR, FIELDNAME, INIT, TESTFIELD, and VALIDATE Functions - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/calcfields--calcsums-fielderror--fieldname--init--testfield--and-validate-functions#feedback)
* Content Source: [dynamics-nav/CALCFIELDS--CALCSUMS-FIELDERROR--FIELDNAME--INIT--TESTFIELD--and-VALIDATE-Functions.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/CALCFIELDS--CALCSUMS-FIELDERROR--FIELDNAME--INIT--TESTFIELD--and-VALIDATE-Functions.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
