### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by SofiiaBalushka** [MicrosoftDocs/dynamics365smb-devitpro-pb#666]
Could you update this page with fresh information, please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2612295b-ecb2-93f1-2097-c5e055ed5123
* Version Independent ID: ec810858-2ada-8915-c110-7634c6b791b4
* Content: [Page and Page Extension Properties Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-property-overview#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-page-property-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-page-property-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This page has been updated to reflect the current page and page extension properties. It will be available within the next doc refresh.
