### ISSUE TITLE
Bug in syntax example

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#668]
The syntax example does not look right, there are not many quotation marks:
SubPageLink = "Table ID" = const(36)","DocumentType"" = field("Document Type")","Document No."" = field("No.");
Correct would be
SubPageLink = "Table ID" = const(36),"Document Type" = field("Document Type"),"Document No." = field("No.");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db86cf12-3c9e-5861-0d75-bdde4a6d5d25
* Version Independent ID: 5f912861-d16d-496e-71e8-1a918362506f
* Content: [SubPageLink Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-subpagelink-property)
* Content Source: [dev-itpro/developer/properties/devenv-subpagelink-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-subpagelink-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The syntax has been fixed and an update will be published soon.
