### ISSUE TITLE
Erroneous DateTime Formatting Examples

### ISSUE THREAD

**Issue by Kowa63** [MicrosoftDocs/dynamics365smb-devitpro-pb#669]
The datetime examples have `<Hours24>` in them, and the outputs show a leading zero before the hour. This would in reality require `<Hours24,2>` instead.

![grafik](https://user-images.githubusercontent.com/16236672/62134152-4580d400-b2e0-11e9-805c-d52f43f99013.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdca6cb6-31fa-822e-c163-7ebacf02e623
* Version Independent ID: b664a2f2-99e2-1e7f-4214-3e41f073ef73
* Content: [Format Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/format-property)
* Content Source: [dynamics-nav/Format-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Format-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will go out soon.
