### ISSUE TITLE
Expected values

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#67]
Hi, it will be helpfull to include expected value range for the performance counters. Else I do not have imagination if values I see on my system are OK or could be a problematic. Could you include some ranges for system which is performing ok?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8523b64d-c9c5-7003-f7f6-b35866ec7d80
* Version Independent ID: beb7747c-2277-b9a6-19b9-ddb26be27729
* Content: [Microsoft Dynamics NAV Performance Counters - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/microsoft-dynamics-nav-performance-counters)
* Content Source: [dynamics-nav/Microsoft-Dynamics-NAV-Performance-Counters.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Microsoft-Dynamics-NAV-Performance-Counters.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! We will revisit this content in the coming months and will consider this suggestion.
