### ISSUE TITLE
Create company is taking to Delete Company page

### ISSUE THREAD

**Issue by pmohanakrishna** [MicrosoftDocs/dynamics365smb-devitpro-pb#670]
in See Also section: 
Create company is taking to Delete Company page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30cecf21-b127-861a-7f6e-3df3267c0834
* Version Independent ID: cb9b74e2-5130-8df4-4e59-f26f23b1d53c
* Content: [automationCompany resource type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/dynamics-microsoft-automation-automationcompany)
* Content Source: [dev-itpro/administration/dynamics-microsoft-automation-automationcompany.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/dynamics-microsoft-automation-automationcompany.md)
* Service: **dynamics365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, this is fixed with the next doc refresh.
