### ISSUE TITLE
Last example should have an END

### ISSUE THREAD

**Issue by HmmPeculiar** [MicrosoftDocs/dynamics365smb-devitpro-pb#671]
Hi, 

I think the last example should have an END statement. Also, in the other examples, the ELSE statement was indented by two spaces, like the options. But this is probably just a case of differing conventions ;-).

Like this:

MyCode := 'ABC';  
CASE MyCode OF  
  'abc':  
    MESSAGE('This message is not displayed.');   
  'def':  
    MESSAGE('This message is not displayed.);  
  ELSE  
    MESSAGE('The value set does not match the expression.'); 
END;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 524c5285-95e1-1a99-2f84-e61cf60d617e
* Version Independent ID: f198d3c2-b8f7-8408-c578-d38d53567fe8
* Content: [C/AL Conditional Statements - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/c-al-conditional-statements)
* Content Source: [dynamics-nav/C-AL-Conditional-Statements.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/C-AL-Conditional-Statements.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
