### ISSUE TITLE
Problems Deleting Business Central Environment via API

### ISSUE THREAD

**Issue by JaGrie** [MicrosoftDocs/dynamics365smb-devitpro-pb#673]
Hello,

I followed the instructions on [The Business Central Administration Center API](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api) and it worked for most of the REST methods. So I was able to get information, copy or create new environments. Unfortunately as I am trying to delete an environment, it throws me an internal error (500). My request looks like in the documentation:
DELETE https://api.businesscentral.dynamics.com/v1.2/admin/applications/BusinessCentral/environments/Sandbox

I use Postman and authenticate with a Token (oAuth2), which works fine for the other requests.

I would appreciate any help on this!
Best wishes
Jakob

**Comment by ManTheWeb** [comment]
> Hello,
> 
> I followed the instructions on [The Business Central Administration Center API](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api) and it worked for most of the REST methods. So I was able to get information, copy or create new environments. Unfortunately as I am trying to delete an environment, it throws me an internal error (500). My request looks like in the documentation:
> DELETE https://api.businesscentral.dynamics.com/v1.2/admin/applications/BusinessCentral/environments/Sandbox
> 
> I use Postman and authenticate with a Token (oAuth2), which works fine for the other requests.
> 
> I would appreciate any help on this!
> Best wishes
> Jakob

Hi Jakob

I unfortunately do not have an answer to your question, but obviously you have come further than me, I am having trouble connecting to BC admin api - I only for the "403 Forbidden" error - do you know what this might be?

**Comment by JaGrie** [comment]
Have you registered your app properly in the azure portal (AAD -> App registrations)? There could be many reasons for that error, but that was the reason in my case some time ago.

**Comment by JaGrie** [comment]
@SusanneWindfeldPedersen 

Hi there,

is there anything new on this topic?

Kind regards,
Jakob

**Comment by henrikwh** [comment]
Hi Jakob
I think might be related to a issue we identified. Can you please try to use fiddler, or make sure that Postman is not sending any cookies (RuntimeTenantAffinity)?

Let me know if above works. If so, an update will be rolled out shortly.

/Henrik

**Comment by JaGrie** [comment]
Hi Henrik,

thanks for your response. I tried again by using Invoke-RestMethod in a Powershell script, which is not sending any cookies either. But it is still not working.

Other request however return a 200. Do you have any other suggestions?

Best regards,
Jakob

**Comment by henrikwh** [comment]
I can see if the telemetry for your request reveals anyting. Can you please provide (e-mail or here) the ms-correlation-x value from the response header from the failing requests. But it needs to a request just executed as the telemetry is transient.

**Comment by JaGrie** [comment]
Thanks for your response.
The ms-correlation-x value of the response is 8c17a5bc-19c4-4372-91a1-2e0113cb2ef8
Executed on: Fri, 25 Oct 2019 10:48:34 GMT

**Comment by henrikwh** [comment]
How many environments do you have? Could it be, that you have too many? From what I read in telemetry, that could be the case.

**Comment by JaGrie** [comment]
3 production and 2 sandbox environments, so there should be on more space, according to the Microsoft document saying „Each Business Central tenant is limited to three sandbox environments„

**Comment by henrikwh** [comment]
Ok. I will log an issue to have it investigated. Please send me an email with contact details.

**Comment by SusanneWindfeldPedersen** [comment]
Closing the documentation issue for this.
