### ISSUE TITLE
Attachment is actually 'Incoming Document'

### ISSUE THREAD

**Issue by bas2at** [MicrosoftDocs/dynamics365smb-devitpro-pb#674]
This documentation is confusing: it states 'Represents an attachment object in Dynamics 365 Business Central'. But instead of representing 'Document Attachment' (table 1173) -- that are actually referred to as attachments in the Business Central UI -- this api actually represents an 'Incoming Document' (table 130).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 268f0f59-f23e-b0c9-5485-ce532a73db2e
* Version Independent ID: a1830a8c-3870-9b77-3d47-7d6492c20f66
* Content: [attachment resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/resources/dynamics_attachment#feedback)
* Content Source: [dynamics-nav/api-reference/v1.0/resources/dynamics_attachment.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/resources/dynamics_attachment.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. I agree that this is confusing, which is partially due to an unfortunate naming in the api. If you want to, you can file a product bug. Thanks.
