### ISSUE TITLE
PowerShell cmdlet parameters 

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#68]
Containername and Port parameters shown here have been changed to ContainerSiteName and WebSitePort, respectively, in the PowerShell script

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02444bba-206c-e4ef-50a0-f38f4ae81312
* Version Independent ID: e1796c36-d68f-49c6-117d-d084eb258eaf
* Content: [How to: Set Up Multiple Web Server Instances for the Microsoft Dynamics NAV Web Client - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--set-up-multiple-web-server-instances-for-the-microsoft-dynamics-nav-web-client)
* Content Source: [dynamics-nav/How-to--Set-Up-Multiple-Web-Server-Instances-for-the-Microsoft-Dynamics-NAV-Web-Client.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Set-Up-Multiple-Web-Server-Instances-for-the-Microsoft-Dynamics-NAV-Web-Client.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! 

The article has been fixed and the update will be available soon.
