### ISSUE TITLE
Table Extensions and Table Keys

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#681]
One of the most important things to know about Keys when developing Table Extension objects is that you cannot use the fields from the Table you're extending.  You cannot Enable/Disable keys in the base Table from a Table Extension.  These are *vital* to know limitations and should be noted on this page.

For reference, this has been a two year issue with no plan to fix the massive challenge this poses:  https://github.com/microsoft/AL/issues/730

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7516d3dc-c374-b3b8-e4ee-d01477b9244b
* Version Independent ID: 71253386-31b9-9f63-1919-1e429953a0a7
* Content: [Table Keys - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-keys#feedback)
* Content Source: [dev-itpro/developer/devenv-table-keys.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-table-keys.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. These remarks have been added to the article, and they will be available in the next doc refresh.
