### ISSUE TITLE
StyleExpr Variable in AL Code

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#682]
Please note in the table, with the 'Variable' section, that for AL Code, you must have the Variable tagged to be included in the Page's DataSet.   This relies on (and should link to) the 'InDataSet' attribute to be set on the variable, but that help documentation is 100% incorrect, as per issue #98 (which should not be closed, please reopen!).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bb3892e-efef-e88c-e188-6dc5b5bd37f0
* Version Independent ID: fb2b94f2-82d8-ea9c-dbd4-dcf6d86210e5
* Content: [StyleExpr Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-styleexpr-property)
* Content Source: [dev-itpro/developer/properties/devenv-styleexpr-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-styleexpr-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The documentation for the **StyleExpr** property has been updated to reflect this. As for issue #98, the **InDataSet** property has been now corrected. It will be available within the next doc refresh.

**Comment by update-jeremy** [comment]
Many thanks to your team.  I remain very appreciative that you (as a team) have this way for us to provide feedback and am continually impressed at the speed and quality of the resulting actions.
