### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by TrishDeane** [MicrosoftDocs/dynamics365smb-devitpro-pb#684]
From talking to one of the Microsoft engineers about AL, I specifically asked if spacing was important (like Python) and was told no. So I'm somewhat confused by the instructions regarding code alignment. Is that important or is it personal preference? If particular alignment is not required, then there should be a distinction in this article between what is required and what is recommended. Otherwise, this is all very helpful. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49792c3f-b5cc-d7bb-cb70-23609e64b09c
* Version Independent ID: 805fa013-f489-05bb-2465-e082a03a3a92
* Content: [AL Control Statements - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-control-statements#feedback)
* Content Source: [dev-itpro/developer/devenv-al-control-statements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-control-statements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The article will be updated with the next refresh.
