### ISSUE TITLE
Information scheme no longer up to date.

### ISSUE THREAD

**Issue by JellebBE** [MicrosoftDocs/dynamics365smb-devitpro-pb#685]
Since the the release of Business Central(V13) this scheme is no longer correct.
Codeunit 1 does no longer exists. it has been replaced by Codeunit 42 as far as i can tell. 
Codeunit 42 holds the necessary Subscribers to extend this feature, including the 'resolved' pattern.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d24c5b2-cd1e-63d0-6973-2ec29f60e6d6
* Version Independent ID: ecf4ab2c-822b-86c7-2dfe-80519868f0ca
* Content: [CaptionClass Functionality - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/captionclass-functionality#feedback)
* Content Source: [dynamics-nav/CaptionClass-Functionality.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/CaptionClass-Functionality.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, we're sorry for not getting back sooner. This issue refers to NAV product documentation and we no longer update this docset.
