### ISSUE TITLE
CU 10 (august 2019) has Runtime 2.4

### ISSUE THREAD

**Issue by Farzad-Jalali** [MicrosoftDocs/dynamics365smb-devitpro-pb#687]
my infrastructure guy just install the new BC with CU 10 (August 2019), I double-checked and its runtime is 2.4
I even get the below error when I try to install an extension with Runtime 3.0:

The runtime version of the extension package is currently set to '3.0'. The runtime version must be set to '2.4' or earlier in the app.json file in order to install the extension package on this platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9e8228-e083-4965-22d3-0df35c09ac5d
* Version Independent ID: 3707c154-ea6e-c317-217d-6d0e75570c1e
* Content: [JSON Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)
* Content Source: [dev-itpro/developer/devenv-json-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-json-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is meant for doc issues and bugs. Please contact your usual support channel to get help with the issue reported. Thanks.
