### ISSUE TITLE
Lack of clarity

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#69]
When doing an XMLPort, you read in data to fields, then an action is taken depending on if you're creating vs updating, depending on the AutoSave / etc, properties.

What this document doesn't make clear (as well as related topics is) what places in that sequence this happens.

For example, if you write code in OnAfterModifyRecord that modifies the values of the fields that have been imported, do you have to do your own 2nd MODIFY call?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f46a533d-1d54-5836-b5b3-df902d757f85
* Version Independent ID: 8005da38-2259-66df-a419-513c6bdb224f
* Content: [OnAfterModifyRecord Trigger - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/onaftermodifyrecord-trigger)
* Content Source: [dynamics-nav/OnAfterModifyRecord-Trigger.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/OnAfterModifyRecord-Trigger.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your input, this is on our backlog of things to do. Closing this issue for now.
