### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#690]
Variable definition says "The client was started by %1." but output example says "The system was started by cronus\simon."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbba2c43-a9dd-8030-f1be-45e792411a80
* Version Independent ID: e48e154a-4cf9-4956-ed7e-cfb0633d028a
* Content: [USERID Function (Sessions) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/userid-function--sessions-)
* Content Source: [dynamics-nav/USERID-Function--Sessions-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/USERID-Function--Sessions-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for noticing this, it has been fixed.
