### ISSUE TITLE
Issues in the instructions

### ISSUE THREAD

**Issue by mtaanquist** [MicrosoftDocs/dynamics365smb-devitpro-pb#691]
Hi there,

I've found, what I think to be, some errors in the documentation:

1. There is no description of how to get access to the DLL-library in your AL project. By default, a new AL-project won't know where to look for the `Microsoft.Dynamics.Nav.Client.PingPong.dll`.
2. The alias you assign the dotnet type does not match the alias you pass to the `usercontrol` in the Page-code. `"Microsoft.Dynamics.Nav.Client.PingPong"` vs. `PingPongAddIn`.

Following these instructions directly does not result in success. Making the necessary changes for it to compile also fails, as it is not able to read the triggers `AddInReady` and `Pong` from the PingPong DLL. I've opened an issue for that here: https://github.com/microsoft/AL/issues/5200

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c26019cd-3e6f-71e9-e3c6-764329ff86b2
* Version Independent ID: 71777407-1118-9345-5dd6-7172be5a6dee
* Content: [.NET Control Add-Ins - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-dotnet-controladdins#feedback)
* Content Source: [dev-itpro/developer/devenv-dotnet-controladdins.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-dotnet-controladdins.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The errors 1 and 2 have been fixed. As for the compiler not recognizing the triggers, it is still under investigation.
