### ISSUE TITLE
Only ExportToNewSyntax described

### ISSUE THREAD

**Issue by larswestman** [MicrosoftDocs/dynamics365smb-devitpro-pb#692]
Where is the description of other parameters than ExportToNewSyntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91badd0e-569a-698e-2780-4f7bb259f163
* Version Independent ID: 3222ce52-2cc2-7323-3229-1f3890911d6d
* Content: [Generating Delta files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-generating-delta-files)
* Content Source: [dev-itpro/developer/devenv-generating-delta-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-generating-delta-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. You can read more about the cmdlet parameters [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.model.tools/compare-navapplicationobject?view=businesscentral-ps). We'll update the topic with a link with the next refresh. Thanks.
