### ISSUE TITLE
Example 3 does not work as written

### ISSUE THREAD

**Issue by JuricaB** [MicrosoftDocs/dynamics365smb-devitpro-pb#693]
Example 3 requires flag -PassThru to return depicted result, otherwise it returns just this:

Summary                                                                                                                                                                      
-------                                                                                                                                                                      
Summary: ...   

Correct code should be:
Merge-NAVApplicationObject -OriginalPath C:\Solution\ORIGINAL\*.TXT -ModifiedPath C:\Solution\MODIFIED\*.txt -TargetPath C:\Solution\TARGET\*.TXT -ResultPath C:\Solution\RESULT\  -PassThru | Sort-Object ObjectType, Id | Format-Table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eefa1142-97ca-8354-cc53-bc66e84f9db5
* Version Independent ID: 139e88f8-fc12-e8e3-d13d-470a3800cc30
* Content: [Merge-NAVApplicationObject (Microsoft.Dynamics.Nav.Model.Tools)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.model.tools/merge-navapplicationobject?view=dynamicsnav-ps-2018)
* Content Source: [dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Model.Tools/Merge-NAVApplicationObject.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Model.Tools/Merge-NAVApplicationObject.md)

**Comment by jswymer** [comment]
Thanks for the feedback! The example has been fixed and an update will be published soon.
