### ISSUE TITLE
Wrong shortcut descriptions?

### ISSUE THREAD

**Issue by warloa** [MicrosoftDocs/dynamics365smb-devitpro-pb#694]
The shortcut descriptions seems to be wrong - Ctrl+Alt+F5 will do "Rapid Application Publish without debugging" and Ctrl+F5 will do "Rapid Application Publish with debugging"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7efad2ff-bdd1-ca20-fc9d-334e44755402
* Version Independent ID: 533bc507-d257-32c6-aad5-3b6cc08d6230
* Content: [Working with Rapid Application Development - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rad-publishing#feedback)
* Content Source: [dev-itpro/developer/devenv-rad-publishing.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-rad-publishing.md)
* Service: **dynamics365-business-central**
* Product: **dynamics-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for pointing this out - the fix will be in the next refresh of the docs. Thanks!
