### ISSUE TITLE
Not helpful, needs to be more detailed

### ISSUE THREAD

**Issue by joshp93** [MicrosoftDocs/dynamics365smb-devitpro-pb#695]
I already knew what this help page tells me simply by reading the name of the method.

This needs to tell me how to handle the lookup once I have invoked it and provide examples of it being used. This is the case for almost all of the testing documentation. Tests have been available for at about 3 years now, please update the documentation so that it is more helpful and informative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61fe658d-fd3e-03d4-eaa1-b28186b786fe
* Version Independent ID: 6ba7d7d4-5f33-8293-0fa2-44ce05d057e9
* Content: [LOOKUP Function (TestPage Field) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/lookup-function--testpage-field-#feedback)
* Content Source: [dynamics-nav/LOOKUP-Function--TestPage-Field-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/LOOKUP-Function--TestPage-Field-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
The NAV documentation is no longer maintained. Closing this issue. Thanks.
