### ISSUE TITLE
QueryCategory explanation

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#696]
What are 'query categories' in the first place? Can you please elaborate a more specific scenario on how query categories behave in the client? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecacafbf-bba5-f3e4-8da9-f408e7a17074
* Version Independent ID: 77b1226e-488c-09c6-38ad-44fc2bdbb9ca
* Content: [QueryCategory Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-querycategory-property)
* Content Source: [dev-itpro/developer/properties/devenv-querycategory-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-querycategory-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **t-blrobl**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question - this is a property which is currently used internally only. We will update the documentation to mention this with the next refresh. Thanks!
