### ISSUE TITLE
Whitepaper provided incomplete

### ISSUE THREAD

**Issue by lhtan-dev** [MicrosoftDocs/dynamics365smb-devitpro-pb#697]
The whitepaper link only points to whitepaper 1 of 2. Where is the second document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba60e8ce-4313-a3eb-0ada-d81c240659c1
* Version Independent ID: 7ac62b7a-02fe-efc3-cf55-67335c94c303
* Content: [Development of a Localization Solution - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-develop-localization#getting-started-with-localization-apps)
* Content Source: [dev-itpro/developer/readiness/readiness-develop-localization.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-develop-localization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We will look into the issue. Thanks.
