### ISSUE TITLE
Page Properties missing 'UsageCategory'

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#698]
Very confusing since the latest AL Extension includes it in the Snippit, so a new dev would be confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e1608b-6f65-1cc7-385d-920091b0305a
* Version Independent ID: 6c96ec0a-931c-622c-1475-e480e69b3210
* Content: [Page Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-page-properties)
* Content Source: [dev-itpro/developer/properties/devenv-page-properties.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-page-properties.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback. Can you elaborate on this a little bit, just want to make sure I understand? 
Thanks

**Comment by update-jeremy** [comment]
Oh sure.

The UsageCategory property is pretty important for Pages:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-usagecategory-property

It's so important that the latest VXIS (Modern Development Environment) has the Page Snippet include this property in all new page objects.

But, it's not present on the "Page Properties" section that this issue is tagged to.

**Comment by SusanneWindfeldPedersen** [comment]
Sorry for the waiting time. This is now fixed and will be live with the next refresh. Thanks.
