### ISSUE TITLE
Typo (Word: Temporary)

### ISSUE THREAD

**Issue by javisoft** [MicrosoftDocs/dynamics365smb-devitpro-pb#699]
The word "Temporary" has a typo after step no. 8 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a88d8bb6-ea66-550e-c39d-74765e804825
* Version Independent ID: ee64b91b-40f1-62e0-2500-8dcc6d0836c4
* Content: [Walkthrough: Transferring a File from Microsoft Dynamics NAV Server to the Client - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--transferring-a-file-from-microsoft-dynamics-nav-server-to-the-client)
* Content Source: [dynamics-nav/Walkthrough--Transferring-a-File-from-Microsoft-Dynamics-NAV-Server-to-the-Client.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Transferring-a-File-from-Microsoft-Dynamics-NAV-Server-to-the-Client.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, this will be fixed with the next refresh of the docs. Thanks.
