### ISSUE TITLE
Step 6 under "Configuring the Credential Type on the Microsoft Dynamics NAV Web Client Web Site" is numbered incorrectly

### ISSUE THREAD

**Issue by ShadowXVII** [MicrosoftDocs/dynamics365smb-devitpro-pb#7]
Step 6 under "Configuring the Credential Type on the Microsoft Dynamics NAV Web Client Web Site" is numbered incorrectly. It's showing as 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60af3523-a189-8fd8-92f3-587181ff87c5
* Version Independent ID: cdfa8d10-3744-d7b5-a0b2-cea41a635540
* Content: [Configure Web Client Users Authentication - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--configure-authentication-of-microsoft-dynamics-nav-web-client-users)
* Content Source: [dynamics-nav/How-to--Configure-Authentication-of-Microsoft-Dynamics-NAV-Web-Client-Users.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Configure-Authentication-of-Microsoft-Dynamics-NAV-Web-Client-Users.md)
* Service: **unspecified**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for your feedback. This will be fixed in the next refresh of the documentation.
