### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by gwhuebner** [MicrosoftDocs/dynamics365smb-devitpro-pb#70]
several links don't work, because of assetid:///T:.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466d17d0-7b2a-bc5c-14d8-a12e639318be
* Version Independent ID: 2e4726a4-18bc-ffeb-faaa-b31a38785347
* Content: [Windows Client Control Add-ins - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--create-a-windows-client-control-add-in)
* Content Source: [dynamics-nav/How-to--Create-a-Windows-Client-Control-Add-in.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Create-a-Windows-Client-Control-Add-in.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback. We have fixed the broken links so that the links will open a search results page from which you can then choose the article for the appropriate member.  The change will be available soon. This is a temporary solution to the problem and will be improved in a future release.

**Comment by gwhuebner** [comment]
still many broken links with "assetid" :-(

**Comment by jswymer** [comment]
Hello, The update has not yet been published live, so the links are still brokem. We will push the update live this week. Thanks
