### ISSUE TITLE
This is not useful

### ISSUE THREAD

**Issue by ThomasBrodkorb** [MicrosoftDocs/dynamics365smb-devitpro-pb#700]
The same text is written beside the error.
I would rather have expected a way to solve the issue on this page.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: d3efa525-0eaa-cd4f-0411-62097fb19a2c
* Version Independent ID: 04218950-1a4f-450e-950d-4c87c23e93dc
* Content: [Please enable the TranslationFile feature in the app.json file for your project. - Business Central](https://docs.microsoft.com/de-at/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0015-translationsmustbeenabled)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop-as0015-translationsmustbeenabled.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop-as0015-translationsmustbeenabled.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We'll look into providing a more solution-based type of error messages going forward, at least in cases where the solution is straightforward. For this error message, please see this [JSON Files](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files) topic. Thanks.
