### ISSUE TITLE
NAV 2018

### ISSUE THREAD

**Issue by jflynn2783** [MicrosoftDocs/dynamics365smb-devitpro-pb#701]
Execute Permission column was renamed to "Run Permission"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68478ec5-d3a5-265b-0f8e-86201fb9e81c
* Version Independent ID: af387e3e-6be0-18ea-b2cf-202f0d9480f9
* Content: [Assign Permission to Use About This Page - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--assign-permission-to-use-about-this-page#feedback)
* Content Source: [dynamics-nav/How-to--Assign-Permission-to-Use-About-This-Page.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Assign-Permission-to-Use-About-This-Page.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
