### ISSUE TITLE
Remarks: AssistButton

### ISSUE THREAD

**Issue by MikeInHull** [MicrosoftDocs/dynamics365smb-devitpro-pb#702]
In Business Central, there is not an AssistButton, everything is configured through code.  These remarks are for Dynamics Nav, not Business Central

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 898939ab-12f1-79b3-3e64-61e8d27bdf00
* Version Independent ID: 75b8837c-6bc3-8c41-5d37-e0116f7dcf52
* Content: [SourceTableView Property (XMLports) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-sourcetableview-xmlports-property#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-sourcetableview-xmlports-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-sourcetableview-xmlports-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This will be updated in the next doc refresh to reflect the latest settings.
