### ISSUE TITLE
Unclear Examples and Endpoints

### ISSUE THREAD

**Issue by lekhashreep** [MicrosoftDocs/dynamics365smb-devitpro-pb#703]
As per the API Documentation of Microsoft Dynamics Nav Business Central, only the companies and subscriptions resource have URIs like **endpoints/entity** but for the rest of the resources like Employees, Accounts, Items, etc., operations are performed on a particular company and the URIs are like **endpoints/companies({id})/entity**. How can we determine that from metadata, which property defines that?

**Comment by henrikwh** [comment]
Currently metadata does not reflect "root" entities (subscription and companies). Please add this to aka.ms/bcideas. This is something which can be taken into consideration for an future version of APIs.
