### ISSUE TITLE
Link to Format Method(Code,Text)

### ISSUE THREAD

**Issue by MiePlougstrup** [MicrosoftDocs/dynamics365smb-devitpro-pb#704]
The link in Remarks section is not opening a page about Format Method, and Format Method is not included in the Method Overview in Business Central documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5468dbfb-e0a2-6c51-58eb-d73580d2bbc1
* Version Independent ID: 63893c18-9b04-b5b9-a8a9-45bf23bb3d56
* Content: [Format Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-format-property)
* Content Source: [dev-itpro/developer/properties/devenv-format-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-format-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback, the link has been fixed. You can find the **Format** Method under the [System Data Type](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-data-type).
