### ISSUE TITLE
Example: Building a format - date example missing

### ISSUE THREAD

**Issue by MiePlougstrup** [MicrosoftDocs/dynamics365smb-devitpro-pb#705]
I expect there to be an example after these words:
"For example, a field that is based on a source expression of the Date data type can use the following format string:"
But there is no example, only the result...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5468dbfb-e0a2-6c51-58eb-d73580d2bbc1
* Version Independent ID: 63893c18-9b04-b5b9-a8a9-45bf23bb3d56
* Content: [Format Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-format-property)
* Content Source: [dev-itpro/developer/properties/devenv-format-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-format-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This has been fixed and will be available in the next doc refresh.
