### ISSUE TITLE
ServicesDefaultCompany 

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#706]
The ServicesDefaultCompany keyword is explained to specify "... the Dynamics NAV company that the client services, OData web services, and NAS services use as the default company". But what does the exactly mean?
Does this determine that any session connecting to that NST will be using this company? And what about a NST running the Task Scheduler? My experience so far is that setting ServicesDefaultCompany does not do make any difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e77b5afc-fe2d-56f9-2418-07d17da7a3d8
* Version Independent ID: a1a9791c-0112-6579-8eef-906ef110a82b
* Content: [Dynamics NAV Server Configuration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/configuring-microsoft-dynamics-nav-server#feedback)
* Content Source: [dynamics-nav/Configuring-Microsoft-Dynamics-NAV-Server.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Configuring-Microsoft-Dynamics-NAV-Server.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
The NAV documentation is no longer maintained. Closing this issue. Thanks.

**Comment by lvanvugt** [comment]
LOL, fully agree, but I guess we do agree that this issue has been open for too long (more than 4 years). Keeping it open long enough to make it obsolete, right?
