### ISSUE TITLE
Wrong setting name in Note section

### ISSUE THREAD

**Issue by theschitz** [MicrosoftDocs/dynamics365smb-devitpro-pb#707]
The correct setting name is ODataServicesMaxPageSize. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1f05d4-336f-4276-19f0-08e5c4e090fd
* Version Independent ID: 9cc8d10e-d680-6baf-402a-0c27adaa3c16
* Content: [Server-Driven Paging in OData Web Services - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/server-driven-paging-in-odata-web-services#feedback)
* Content Source: [dynamics-nav/Server-Driven-Paging-in-OData-Web-Services.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Server-Driven-Paging-in-OData-Web-Services.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for noticing this. It will be fixed for both NAV and Business Central docs.
