### ISSUE TITLE
Wrong sample

### ISSUE THREAD

**Issue by UrpoKotipalo** [MicrosoftDocs/dynamics365smb-devitpro-pb#708]
The sample has a single dot where should be two double spots for option field:

MyTable.MyBLOBfield.CREATEOUTSTREAM(MyStream, TextEncoding::WINDOWS) 

---
#### Asiakirjan tiedot

⚠ *Älä muokkaa tätä osiota. Sitä tarvitaan kohteessa docs.microsoft.com GitHub-ongelmien linkityksessä.*

* ID: a24eaf49-8adb-0e32-0800-e30e23a46bbc
* Version Independent ID: 87e447e6-2b31-ade9-b90c-976d361aa8df
* Content: [CreateOutStream Method - Business Central](https://docs.microsoft.com/fi-fi/dynamics365/business-central/dev-itpro/developer/methods-auto/blob/blob-createoutstream-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/blob/blob-createoutstream-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/blob/blob-createoutstream-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for noticing this. It will be fixed in the next doc refresh.
