### ISSUE TITLE
add more examples

### ISSUE THREAD

**Issue by MarkCWEV** [MicrosoftDocs/dynamics365smb-devitpro-pb#709]
can you add more example code: for example joining on multiple columns and multiple filter conditions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40661ecc-d190-694d-a708-c0d601cdb793
* Version Independent ID: 4ac6c2e3-c861-2eef-e88d-eb425d159964
* Content: [Setting Relationships Between Tables - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/setting-relationships-between-tables#feedback)
* Content Source: [dynamics-nav/Setting-Relationships-Between-Tables.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Setting-Relationships-Between-Tables.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
The NAV documentation is no longer maintained. Closing this issue. Thanks.
