### ISSUE TITLE
Enhanced example

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#710]
How about an example that includes one or more of the Text Encoding optional parameters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8301c3-d23a-c4f0-5de0-5d80d8646a0e
* Version Independent ID: 5424de2b-80f0-f8b4-7696-92874a29a1a5
* Content: [CREATE Function (File) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/create-function--file-)
* Content Source: [dynamics-nav/CREATE-Function--File-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/CREATE-Function--File-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
The NAV documentation is no longer maintained. Closing this issue. Thanks.
