### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Illeris** [MicrosoftDocs/dynamics365smb-devitpro-pb#711]
Please replace "purchaseInvoide" by "purchaseInvoice"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1614578a-0f5e-9168-5dc0-f7b23813f2c2
* Version Independent ID: 52c64f2a-9519-691f-39e0-d0bf3f5ccb66
* Content: [Get pdfDocument - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_salesquote_pdfdocument#feedback)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_salesquote_pdfdocument.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_salesquote_pdfdocument.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. It has been fixed and it will be visible in the next doc refresh.
