### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by Illeris** [MicrosoftDocs/dynamics365smb-devitpro-pb#712]
Under "Navigation".
The lines "paymentMethod" are mentioned 3 times, with wrong relation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b17613-4934-5eaa-457e-ef49d67707ec
* Version Independent ID: de142898-74cb-367c-2d42-d13ae24c8d05
* Content: [salesInvoices resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/resources/dynamics_salesinvoice)
* Content Source: [dynamics-nav/api-reference/v1.0/resources/dynamics_salesinvoice.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/resources/dynamics_salesinvoice.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this, it has been fixed and it will be available in the next doc refresh.
