### ISSUE TITLE
ShowMyCode

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#713]
Article should be updated, because there is an Option -ShowMyCode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aea33a83-64c0-a56b-363a-b5aae7eb15f5
* Version Independent ID: a7919faa-7603-573b-ef43-10c60c3803d9
* Content: [Creating Runtime Packages for Business Central On-Premises - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages)
* Content Source: [dev-itpro/developer/devenv-creating-runtime-packages.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-creating-runtime-packages.md)
* Service: **dynamics365-business-central**
* Product: **dynamics-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The article has been updated and will be published soon.
