### ISSUE TITLE
-ShowMyCode is missing

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#714]
Parameter -ShowMyCode is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc4bb7a-d6f7-2edf-4198-4a399066c0a0
* Version Independent ID: 4c738593-41be-a215-4fbc-3bd22ec47d42
* Content: [Get-NavAppRuntimePackage (Microsoft.Dynamics.Nav.Apps.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/Get-NAVAppRuntimePackage?view=dynamicsnav-ps-2018#feedback)
* Content Source: [dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Apps.Management/Get-NavAppRuntimePackage.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/dynamicsnav-ps-2018/Microsoft.Dynamics.Nav.Apps.Management/Get-NavAppRuntimePackage.md)

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The `-ShowMyCode` parameter is only available only in Business Central April 2019 and the upcoming versions, so it's not possible to use it in Dynamics NAV.
