### ISSUE TITLE
Task 12: Run data upgrade on converted database

### ISSUE THREAD

**Issue by MateoPadiernaB** [MicrosoftDocs/dynamics365smb-devitpro-pb#715]
Hi, i'm doing the process from NAV 2015 and i have this error:
SessionId         : 405
CodeunitId        : 104000
FunctionName      : UpdateItem
CompanyName       : COLPLASPROD
StartTime         : 8/30/2019 9:48:26 PM
Duration          :
State             : Failed
Error             : The function UpdateItem in the company initialization codeunit 104000 in company COLPLASPROD has
                    failed due to the following error: 'The UPG Item does not exist. Identification fields and values:
                    No.='01-1477C''.
ExecutionSourceId : 00000000-0000-0000-0000-000000000000
PostUpgrade       : False

I really don't know what do in this case, Can u help me?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we will close this issue as it is not documentation related. Hope you were able to find help through your usual support channel. Thanks.
