### ISSUE TITLE
Mistake in snippet "Tip block"

### ISSUE THREAD

**Issue by stryzhak** [MicrosoftDocs/dynamics365smb-devitpro-pb#716]
It should be tcodeunit instead of tcodunit - symbol **e** is missed 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dd7c9e-51a5-eeea-a2f6-dd4d40b93295
* Version Independent ID: d6fb1d1b-fa2e-606e-6c79-115651b60a29
* Content: [Writing extensions installation code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-install-code#feedback)
* Content Source: [dev-itpro/developer/devenv-extension-install-code.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-install-code.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for noticing this. It will be fixed in the next doc refresh.
