### ISSUE TITLE
Missing documentation for APIs published throught extensions

### ISSUE THREAD

**Issue by Nyryus** [MicrosoftDocs/dynamics365smb-devitpro-pb#717]
Please update this page, making clear that extensions API on Premise are reachable throught this base URL.
https://&lt;base URL&gt;:&lt;port&gt;/&lt;web server instance&gt;/api/&lt;API publisher&gt;/&lt;API group&gt;/&lt;API version&gt;/companies(&lt;Company Guid&gt;)/&lt;Entity set name&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17c4eef7-2ff2-eeeb-d285-095002e99475
* Version Independent ID: 2beae6be-8b5f-2a48-4b68-81810248b8f6
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics#feedback)
* Content Source: [dynamics-nav/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/endpoints-apis-for-dynamics.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - we will update the topic to include the URL for partner developed APIs. The topic will be updated with the next refresh.
