### ISSUE TITLE
ODAVA V4 outparam/inparam is not working in NAV 2018 CU11

### ISSUE THREAD

**Issue by Akil123** [MicrosoftDocs/dynamics365smb-devitpro-pb#718]
Hi i have followed below link for sending outparam and inparam by using ODATA V4.

https://docs.microsoft.com/en-us/dynamics-nav/walkthrough-creating-and-interacting-odata-v4-bound-action#

But i am facing below issue.

![image](https://user-images.githubusercontent.com/33834544/64163250-85e2ed00-ce5e-11e9-94aa-649f3f58875f.png)

can any one please suggest on which build version it is working fine.

Thank you
Ramesh
--

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please contact your usual support channel for this question, we're unfortunately not able to help.
