### ISSUE TITLE
ReadRouding moved to CU 45

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#719]
ReadRounding is no longer located in codeunit 1, but has been moved codeunit 45 (AutoFormatManagement).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3970093-e70d-ef60-fe5c-9df0b183c1a4
* Version Independent ID: c866aded-805b-2637-13e5-3d01ba2d9301
* Content: [Round Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-round-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-round-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/system/system-round-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this. The article will be updated in the next doc refresh.
