### ISSUE TITLE
Grant the Excel add-in application permission to the Business Central on-premise?

### ISSUE THREAD

**Issue by slebodat** [MicrosoftDocs/dynamics365smb-devitpro-pb#720]
under section:
_Register and configure an Azure AD Application for the Excel Add-in in Microsoft Azure_
in point 2 you are refering to Business Central application

_Grant the Excel add-in application permission to the **Business Central application**.
You must give the Azure AD application for the Excel add-in delegated permission to access the Business Central application in Azure AD. This allows users of the Excel add-in to access the OData web services to read and write data.
In the portal, you set up permissions on the configuration/settings page of Excel add-in application, in the permissions section._

However, I'm using BC365 on-premise and my "Business Central application" is another Azure AD Application ([link to doc](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory#task-2-add-an-application-for--to-the-azure-ad-tenant)), which doesn't expose any API therefore there is no way I can add Excel Add-in application delegated permissions to Business Central application.

Currently, I'm getting following error message when I open excel:
AADSTS65001: The user or administrator has not consented to use the application with ID '' named 'Excel Add-in for Dynamics NAV'. Send an interactive authorization request for this user and resource.

AAD was configured correctly, at least it seems to be, as I can successfully login.

Is there something I've missed or this functionallity is not supported in on-premise version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5c53847-a111-f746-cc85-af3dcc702f84
* Version Independent ID: 06c03c31-a8a9-40e7-2847-bc22cea91344
* Content: [Setting up the Excel Add-In for Editing Data - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configuring-excel-addin#see-also)
* Content Source: [dev-itpro/administration/configuring-excel-addin.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configuring-excel-addin.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by slebodat** [comment]
Hi again,
I've figured out step which is missing in the documentations:

1b) In your  **Business Central application in Azure AD** navigate to _Expose an API_ tab and then press + _Add a scope_ button. Enter a _Scope_ name, an _Admin consent display name_, and then an _Admin consent description_ such as user_impersonation. Make sure _State_ is set to _Enabled_. Select _Add scope_.

BR.

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been updated.

**Comment by SUD-D365** [comment]
Under "Configure the Business Central Server Instances" section in point no 3.
The URL format should be without port.
https://localhost/BC150/ODataV4/

Thanks

**Comment by MJECloud** [comment]
@SUD-D365 why should it be without the port?

**Comment by Nasimkhavari** [comment]
hi guys, 
Does anybody know these settings are possible with active directory, not the azure?
