### ISSUE TITLE
Not for modal pages

### ISSUE THREAD

**Issue by JoergPernberg** [MicrosoftDocs/dynamics365smb-devitpro-pb#721]
You can trap only nonmodal pages. 
Is there any plan to expand this function also for modal pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6deba8-65f3-664c-14c3-796480c4447f
* Version Independent ID: d4aa9549-c5fb-4165-8544-4d4aaf965907
* Content: [Trap Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testpage/testpage-trap-method)
* Content Source: [dev-itpro/developer/methods-auto/testpage/testpage-trap-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/testpage/testpage-trap-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We will refresh the topic with that note. With regards to if the functionality will be expanded, please file an [idea](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central).
