### ISSUE TITLE
Update to .NET Framework 4.7.2

### ISSUE THREAD

**Issue by bstaeheli** [MicrosoftDocs/dynamics365smb-devitpro-pb#722]
Modify the part "Prepare Users Computers by Installing .NET Framework 4.6.1" to match version 4.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5756902d-57e8-1fb3-1b6d-67050e852480
* Version Independent ID: c2228f99-c889-04e2-91df-320559bd4504
* Content: [Deploying Microsoft Dynamics NAV Using ClickOnce - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/deploying-microsoft-dynamics-nav-using-clickonce#feedback)
* Content Source: [dynamics-nav/Deploying-Microsoft-Dynamics-NAV-Using-ClickOnce.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Deploying-Microsoft-Dynamics-NAV-Using-ClickOnce.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been updated and will be published soon.
