### ISSUE TITLE
Error in text

### ISSUE THREAD

**Issue by QuantumSupraLogic** [MicrosoftDocs/dynamics365smb-devitpro-pb#724]
The sentence "If the Format Property (XMLports) of the XMLport is set to Both, the XMLport can be used to import or export data. " is wrong. The correct property would be "Direction", not "Format".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a711ef0-24b9-ac80-d8ef-9c4b9dcb3eef
* Version Independent ID: 4294d897-9241-e583-f65b-092696809996
* Content: [Request Pages (XMLPorts) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/request-pages--xmlports-#feedback)
* Content Source: [dynamics-nav/Request-Pages--XMLPorts-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Request-Pages--XMLPorts-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by QuantumSupraLogic** [comment]
The same goes for the sentence "If the Format Property (XMLports) is set to either Import or Export, then the Direction list box is not displayed on the request page."

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
