### ISSUE TITLE
Update the platform instruction must be updated about extensions to make update more hassle free

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#725]
I started making platform upgrade step-by-step according to this page and when new CU server and client etc was installe and I opened DEV environment I got error:
"There are records in the NAV App Tenant App table. You must uninstall all extensions before upgrading the database."

So please add right before "Uninstall the current Business Central components." row:
Uninstall all extensions (both regular and system apps)

Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566ac7ba-c8e2-cd8f-370e-26e1d581a7cf
* Version Independent ID: 6961aefe-7207-d8eb-4b2b-a249d321a309
* Content: [Install a cumulative update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update#feedback)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been updated to include this information, and it will be published soon.
