### ISSUE TITLE
Uploading to specific environment though API

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [MicrosoftDocs/dynamics365smb-devitpro-pb#726]
Looking at the https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/dynamics-microsoft-automation-extensionupload-patch it doesn't look it's possible to upload extension to a specific environment (sandbox instead of production) - is this correct? If that's the case - would that be possible in the foreseeable future?

**Comment by henrikwh** [comment]
Hi. It is possible. 
https://api.businesscentral.dynamics.com/v1.0/sandbox/api/microsoft/automation/v1.0/companies({companyId})/extensionUpload(0)/content

But, I recement using v2.0 of the gateway to use multiple environments. Docs will be updated shortly to reflect newest changes. Heres how you access a named environment with v2.0 of the gateway:
https://api.businesscentral.dynamics.com/v2.0/<environment name>/api/v1.0/customers

With custom namespace, in this case microsoft/automation:
https://api.businesscentral.dynamics.com/v2.0/<environment name>/api/microsoft/automation/v1.0/companies({companyId})/extensionUpload(0)/content

With tenant identifier (need for basic auth or if you're using delegated admin)
https://api.businesscentral.dynamics.com/v2.0/<tenant id>/<environment name>/api/microsoft/automation/v1.0/companies({companyId})/extensionUpload(0)/content

I hope it helps.
