### ISSUE TITLE
Error in Set up a local-hosted container sandbox. 

### ISSUE THREAD

**Issue by anand-tiwari23** [MicrosoftDocs/dynamics365smb-devitpro-pb#73]
Hi, 
I am trying to Set up a local-hosted container sandbox. The moment i am clicking on the 'SANDBOX ENVIRONMENT (CONTAINER)' after searching it,I am getting the message 
'This feature is only available in the online production version of the product'. 

Any clue on this ?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3441a5d0-c228-82f5-7513-cb47359f9414
* Version Independent ID: b70a968d-33d6-04c0-9b59-aaac53b8b5db
* Content: [Get started with the Container Sandbox Development Environment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-container-sandbox#set-up-a-local-hosted-container-sandbox)
* Content Source: [dev-itpro/developer/devenv-get-started-container-sandbox.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-get-started-container-sandbox.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is meant for documentation feedback only. Please file a bug or question through the product option on the topic. Thanks.
