### ISSUE TITLE
Invalid Role Center

### ISSUE THREAD

**Issue by spiritsip** [MicrosoftDocs/dynamics365smb-devitpro-pb#730]
In the profile portion of the sample code, the "Business Manager" RoleCenter is invalid. It should be "Business Manager Role Center"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa8872c-562c-dd7b-dfca-316ef2ac20c2
* Version Independent ID: 259f7cd2-e56c-9da6-38cc-884176f1dc93
* Content: [Page Customization Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-customization-object)
* Content Source: [dev-itpro/developer/devenv-page-customization-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-customization-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - the topic will be updated with the next refresh.
