### ISSUE TITLE
How to delete a table field on SaasProduction 

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/dynamics365smb-devitpro-pb#731]
It says deprecated, how should obsolete fields be treated now?

I want to remove a certain field from a table in my  extension on a production SaaS environment. What's the procedure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 065836e3-0874-ca58-4f76-2ca76891bb83
* Version Independent ID: 4cec430d-5aeb-cbe2-b9b9-6e4f22269596
* Content: [ObsoleteState Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-obsoletestate-property)
* Content Source: [dev-itpro/developer/properties/devenv-obsoletestate-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-obsoletestate-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The deprecated remark is a bit unfortunate here - the ObsoleteState property is not deprecated, you should still use it. We will update the topic with the next refresh.
