### ISSUE TITLE
Example 3

### ISSUE THREAD

**Issue by DavidCurd** [MicrosoftDocs/dynamics365smb-devitpro-pb#734]
Example 3 is incorrect, it includes the output of the command.  Instead of :
Set-NAVServerUser DynamicsNAV90 -UserName USER1 -NewUserName USER2 -ChangePasswordAtNextLogOn -Password (Read-Host "Enter password for USER2" -AsSecureString)Enter password for USER2: ************

It should read:
Set-NAVServerUser DynamicsNAV90 -UserName USER1 -NewUserName USER2 -ChangePasswordAtNextLogOn -Password (Read-Host "Enter password for USER2" -AsSecureString)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5681b0a1-cd84-19c8-bd3d-af9f9b1fcf51
* Version Independent ID: a93713b8-b619-36d3-5a1d-cac11be91966
* Content: [Set-NAVServerUser (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/set-navserveruser?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Management/Set-NAVServerUser.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Management/Set-NAVServerUser.md)

**Comment by jswymer** [comment]
Thanks for the feedback! The example has been fixed and an update will be published soon.
