### ISSUE TITLE
 PFX file link broken

### ISSUE THREAD

**Issue by Miki-84** [MicrosoftDocs/dynamics365smb-devitpro-pb#736]
Hello The  PFX file link pointing to https://uk.godaddy.com/help/windows-install-codedriver-signing-certificate-and-create-pfx-file-2698 it's broken.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21426684-ae01-f266-f21c-065bb2499692
* Version Independent ID: c8058293-0160-a4cf-6706-f904349eb194
* Content: [Signing an APP Package File - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sign-extension#feedback)
* Content Source: [dev-itpro/developer/devenv-sign-extension.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-sign-extension.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. It seems to be working now, probably the website was momentarily unavailable.
