### ISSUE TITLE
Response size is limited by the Development/HttpClient AL Function Response Size setting

### ISSUE THREAD

**Issue by gertlynge** [MicrosoftDocs/dynamics365smb-devitpro-pb#737]
Please add to the documentation that the size of the response is limited by the Service Tier configuration setting Development / "HttpClient AL Function Response Size". Default is 15MB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb27052e-5f74-353b-a5da-c32c0d14e417
* Version Independent ID: 97d595ac-8dcb-76ac-4b82-52520f97ade5
* Content: [HttpResponseMessage Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpresponsemessage/httpresponsemessage-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/httpresponsemessage/httpresponsemessage-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/httpresponsemessage/httpresponsemessage-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, much appreciated! We will update this topic with the next refresh.
