### ISSUE TITLE
This is not fully true for AL development.

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#738]
"The Caption property value is taken from the value of the CaptionML Property for the current user language if the CaptionML Property is set." This is not fully true for AL development.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bab3db4-745f-2c66-eac3-be6d6e168200
* Version Independent ID: e1479a2b-49cd-9edb-63c1-e1b0e9907d9f
* Content: [Caption Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-caption-property)
* Content Source: [dev-itpro/developer/properties/devenv-caption-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-caption-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, no this was a left over from old days - thanks for catching this. The topic will be fixed with the next doc refresh.
