### ISSUE TITLE
How about AL development?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#739]
CaptionML is only there for a kind of backwards compatibility. But will be deprecated. Shouldn't this be explained?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bfbb9ca-3b27-7151-5fbc-5986c81f6b23
* Version Independent ID: 03fd2eed-c11c-16b4-9588-26feea722301
* Content: [CaptionML Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-captionml-property)
* Content Source: [dev-itpro/developer/properties/devenv-captionml-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-captionml-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, we have taken the note out deliberately. Please reach out on the [AL repo](https://github.com/microsoft/AL) for any questions. Thanks.
