### ISSUE TITLE
Remaining Amt. (LCY) field name is not matching with EntryType_DetailedCustLedgEntry 

### ISSUE THREAD

**Issue by mrmnaveed** [MicrosoftDocs/dynamics365smb-devitpro-pb#74]
Please have a look at the Adding Fields to the Data Items section for cust ledger entry field name is Remaining Amt. (LCY) and it name is specified as EntryType_DetailedCustLedgEntry  which is not consistent with other documentation standards.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 865c6fff-f9f0-a385-15b0-4b93cd1982a7
* Version Independent ID: 8a0af785-5196-3de8-9e70-e987a8d63061
* Content: [Walkthrough: Designing a Report from Multiple Tables - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--designing-a-report-from-multiple-tables)
* Content Source: [dynamics-nav/Walkthrough--Designing-a-Report-from-Multiple-Tables.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Designing-a-Report-from-Multiple-Tables.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback!

The issue has been fixed and will be published soon.
