### ISSUE TITLE
Wrong description op OptionMembers.

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#740]
Gets the list of options that are available in the field that is currently selected? Nope, it does not get, but defines ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e845063-6484-9104-1441-042482cc55ec
* Version Independent ID: 33f0aa0d-598d-2b30-7659-45aaf317da6c
* Content: [OptionMembers Property (Field) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-optionmembers-field-property)
* Content Source: [dev-itpro/developer/properties/devenv-optionmembers-field-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-optionmembers-field-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @ailie13
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with our next refresh.

**Comment by dnpb** [comment]
This was never changed. What should it have been changed to? I don't see how this defines anything; it looks to be only a getter.

**Comment by lvanvugt** [comment]
Changed **get** to **set** in my initial post.

**Comment by dnpb** [comment]
OK, so it was wrong but is not OK :-)

**Comment by dnpb** [comment]
OK, so it was wrong but is now OK :-)
