### ISSUE TITLE
please update this page with more current references

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#742]
This guide is referring a lot to old names and concepts. (eg. DynamicsNAV90)
Please update this guide to reflect the modern AL tools and names.
Please also provide information if this is possible in SaaS environment, and what differences you might run in to in that case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b3196a-00cc-3382-f040-ef813b4029e4
* Version Independent ID: cbd09737-7acd-2534-d9aa-96a8b34c8c4f
* Content: [Walkthrough: Creating and Interacting With an OData V4 Bound Action - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action)
* Content Source: [dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/walkthrough-creating-and-interacting-odata-v4-bound-action.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We still have work on our backlog to get web services updated. For now you might find this topic useful [Creating and Interacting with an OData V4 Bound Action](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-bound-action)
