### ISSUE TITLE
Any Bound action example for a List?

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#743]
I don't suppose we could ask for a List example, such as a Contact List, maybe a function to change the Salesperson Code?

I'm running into issues that Bound actions only seem to work on single entities, so if it *is* possible against a collection, then I really could use an example/pointer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc3b124e-b1cf-6169-386c-7ed466e0a78d
* Version Independent ID: 7e63c510-35cb-226b-5d78-7ba7d045a0eb
* Content: [Walkthrough: Creating and Interacting With an OData V4 Bound Action - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough-creating-and-interacting-odata-v4-bound-action)
* Content Source: [dynamics-nav/walkthrough-creating-and-interacting-odata-v4-bound-action.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/walkthrough-creating-and-interacting-odata-v4-bound-action.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by JeremyVyska** [comment]
To the best of my API knowledge in the intervening 3 years since opening this ticket, you cannot use Bound Actions on a Collection.  So, rather than requesting a Code Sample of an Impossible, perhaps a new Note section to clarify that "Bound actions are performed against single Entity endpoints, not Collections"?

**Comment by SusanneWindfeldPedersen** [comment]
The NAV documentation is no longer maintained. Closing this issue. Thanks.
