### ISSUE TITLE
OAuth2 Authentication for Business Central through C# code

### ISSUE THREAD

**Issue by ivan9876** [MicrosoftDocs/dynamics365smb-devitpro-pb#744]
Does anyone have working example of C# code that successfully communicates with Business Central through OAuth2 authentication.

I have successfully retrieved the token from Postman but when I try to get the token from my C# code I can't get the correct token. I get wrong one. Maybe I miss some configuration in Azure or something.  

Thanks

**Comment by SusanneWindfeldPedersen** [comment]
Hello - this repo is meant for reporting doc issues. Please use other communities or support to get help with this. Thanks.
