### ISSUE TITLE
Better explanation of parameter "Value"

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#745]
I tend to double check this out quite often during the years, since the intellisense and compiler is not that helpful with this...

Copied from the old C/AL help file:
```
Specifies what the function returns. The valid options are 1, 2, and 3.
The value 1 corresponds to day of the week (1-7, Monday = 1).
The value 2 corresponds to week number (1-53).
The value 3 corresponds to year.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d363fcd-5067-f6db-afc7-33d2e8dff372
* Version Independent ID: 58c55fa0-bb86-c573-c656-09bdc586ba4d
* Content: [Date2DWY Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-date2dwy-method)
* Content Source: [dev-itpro/developer/methods-auto/system/system-date2dwy-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/system/system-date2dwy-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. The parameter descriptions have been updated, they will be available with the next doc refresh.
