### ISSUE TITLE
Wrong date format example

### ISSUE THREAD

**Issue by spiritsip** [MicrosoftDocs/dynamics365smb-devitpro-pb#747]
In the part that reads "The syntax for defining Date format is yyyymmddD, where D is a mandatory letter. For example, 20180325D, read as the 26th of March, 2018." That's not actually correct. 20180325D should be the 25th of March, 2018, right? The days should match?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9509e6-4dc9-caa5-c1ca-68858fa746c6
* Version Independent ID: aa577216-65a7-6750-56a2-a7448e107d24
* Content: [Date Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/date/date-data-type)
* Content Source: [dev-itpro/developer/methods-auto/date/date-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/date/date-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this. Yes, they should match, that is a typo. It will be fixed with the next doc refresh.
