### ISSUE TITLE
Extending Enum Fields

### ISSUE THREAD

**Issue by MBK75** [MicrosoftDocs/dynamics365smb-devitpro-pb#748]
Hello,

I am working on extending an in-house product.  In particular, I changed a field which used to be an option field to an enum field as follows:

enum 82100 "Sales Trade Agreement Sales Type Enum"
{
    Extensible = true;

    value(0; Customer) { CaptionML = ENU = 'Customer'; }
    value(1; "Customer Price Group") { CaptionML = ENU = 'Customer Price Group'; }
    value(2; "All Customers") { CaptionML = ENU = 'All Customers'; }
    value(3; Campaign) { CaptionML = ENU = 'Campaign'; }
}

In the table

//...
field(4; "Sales Type"; enum "Sales Trade Agreement Sales Type Enum")
        {
            CaptionML = ENU = 'Sales Type',
                        ESM = 'Tipo venta',
                        FRC = 'Type de vente',
                        ENC = 'Sales Type';
//...

Since this is a "base" product in-house, we are writing an extension for it for a client that wants to add a couple of additional choices.  Thus, in another extension, I did the following:

enumextension 50300 "WCI TM Trade Mgt. Sales Type" extends "Sales Trade Agreement Sales Type Enum"
{
    value(50300; "Some Price Level 1")
    {
        CaptionML = ENU = 'Some Price Level 1';
    }
    value(50301; "Some Price Level 2")
    {
        CaptionML = ENU = 'Some Price Level 2';
    }
}

However, when the custom extension is installed along with our "base" product, the drop list is completely empty (there are no choices).  If I only have our "base" product, then it works (without the client's customization, of course).  

Are extensible enums not intended to apply to existing fields?

**Comment by blrobl** [comment]
Hi, thanks for your feedback.
I tried to replicate that behavior using your code, but I didn't get that error. I'll describe below the steps that I've followed, so please let me know if I have missed something which can lead to the source of the problem.

1. In a new extension, I created the `"Sales Trade Agreement Sales Type Enum"` enum, as you defined it.
2. I created a table, with `"Sales Type"` as only field. 
3. I created the corresponding List and Card pages for the table.
4. I created a new version of the extension, where I define the `"WCI TM Trade Mgt. Sales Type"` enumextension.
5. I publish the extension and open the Card Page, where all five options for the field appear.

**Comment by MBK75** [comment]
Thanks for looking into this!

May I ask what version you ran this against?  I should have mentioned that this is the current (pre-Wave 2) BC On Premise.  I don't know if that makes a difference.  I am definitely seeing the problem.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry to hear that you're having problems with this. We probably have a newer version of the AL extension than you have. I have to ask you to file a bug through your usual support or try to file an issue on the [AL repo](https://github.com/microsoft/AL). I cannot transfer this issue directly, because it's in a different org. Thanks again.
