### ISSUE TITLE
NavNclHttpClientTimeoutTooLargeException

### ISSUE THREAD

**Issue by BartBourgeois** [MicrosoftDocs/dynamics365smb-devitpro-pb#749]
The 'Duration' in 'SetTimeout' is limited by the 'NavHttpClientMaxTimeout' parameter in the NAV-ServerConfiguration.
When you try to set the Duration higher than this limit a 'NavNclHttpClientTimeoutTooLargeException' is thrown.
Default  'NavHttpClientMaxTimeout' is set to '00:05:00' and can be modified as needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db11588e-817a-b507-d49f-fa4bce22e4be
* Version Independent ID: 2f865b81-0110-3965-2e6d-ba1388a02461
* Content: [Timeout Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-timeout-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/httpclient/httpclient-timeout-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/httpclient/httpclient-timeout-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! We have updated the article to include this information. The updated article will be published soon.
