### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by dkatson** [MicrosoftDocs/dynamics365smb-devitpro-pb#75]
1. Codeunit should be SubType of Upgrade. If we use SubType of Normal, we have compilation errors.
2. Procedures (like OnUpgradePerCompany) should be triggers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c52c6c53-d4f9-a427-5b21-4dae2665443b
* Version Independent ID: 558ab716-02b1-1a31-298a-f1cadd25d9e2
* Content: [How to: Write Extension Upgrade Code - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/extensions-upgrade-howto)
* Content Source: [dynamics-nav/extensions-upgrade-howto.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/extensions-upgrade-howto.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dkatson** [comment]
Hi, yes you are right.
I’m using V2 and found that document after.
Sorry for inconvenience 

Dmitry

**Comment by SusanneWindfeldPedersen** [comment]
Sounds great, thanks!
