### ISSUE TITLE
Links points to the wrong page

### ISSUE THREAD

**Issue by ChethanT** [MicrosoftDocs/dynamics365smb-devitpro-pb#750]
Links for FILTERGROUP Method (Record) and SETRECFILTER Method (RecordRef) takes you to the page about data types

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c8b6db-97af-ace5-aa2d-9b53750e409d
* Version Independent ID: 51db8bb8-8aa6-d7ed-7e34-20caf23097da
* Content: [FilterGroup Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-filtergroup-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/recordref/recordref-filtergroup-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/recordref/recordref-filtergroup-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks, will be fixed with next refresh of the docs.
