### ISSUE TITLE
dependencyPublishingOption - app.json

### ISSUE THREAD

**Issue by adrian-panaite** [MicrosoftDocs/dynamics365smb-devitpro-pb#751]
The property "dependencyPublishingOption" appears in App.json section and in Launch.json section. I tried to set it in both files, but i get and error "error AL0124: The property 'dependencyPublishingOption' cannot be used in this context"

Is the property valid only in Launch.json?

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this - it is a bug; the property can only be set in the launch.json file. This will be fixed shortly. Thanks!
