### ISSUE TITLE
Translating other extensions

### ISSUE THREAD

**Issue by adrian-panaite** [MicrosoftDocs/dynamics365smb-devitpro-pb#752]
I created a project and added dependencies on base application, system application and a custom extension.
I expected the generated xlf file to include captions from all the other 3 extensions. From "you can add .xlf files in your current project that translates the object captions of the referenced extension." i guess i have to add myself the files for these extensions. This is not a problem for custom extensions, but how can i generate an xlf file for Base Application and System Application?

**Comment by SusanneWindfeldPedersen** [comment]
Please add back the information about the topic that you are referring to. Thanks.

**Comment by adrian-panaite** [comment]
My question is based on "https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translating-other-extensions" topic.
I found the xliff for base application and system application in a docker container.

**Comment by SusanneWindfeldPedersen** [comment]
Okay, thanks for the follow-up. Do you have what you need now?

**Comment by adrian-panaite** [comment]
Yes.

**Comment by r4luk** [comment]
Hello Adrian,
Could you please help me with the path where you found the xliff for the base and system application?

Thanks a lot.

**Comment by adrian-panaite** [comment]
The source files are in C:\Applications\BaseApp\Source\Base Application.Source.zip and
 C:\Applications\System Application\Source\System Application.Source.zip.
Each archive contains a folder named Translations. There are the xliff files you want.

**Comment by r4luk** [comment]
Thanks a lot. :)
