### ISSUE TITLE
StrMenuHandler function: Wrong parameter type - typing error

### ISSUE THREAD

**Issue by Nyryus** [MicrosoftDocs/dynamics365smb-devitpro-pb#753]
There is a typing error in the signature column of the StrMenuHandler function.
The correct parameters are : &lt;Function name&gt;(&lt;Options&gt; : Text[1024]; VAR &lt;Choice&gt; : Integer; &lt;Instruction&gt; : Text[1024])
Not: &lt;Function name&gt;(&lt;Options : Test[1024]; VAR &lt;Choice&gt; : Integer; &lt;Instruction&gt; : Text[1024])

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceab92c1-9510-ed55-8bac-41b1614ebfb0
* Version Independent ID: 93786902-1621-bfd0-03f4-4dbb5bf35f11
* Content: [Create Handler Functions - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--create-handler-functions#feedback)
* Content Source: [dynamics-nav/How-to--Create-Handler-Functions.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Create-Handler-Functions.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The error has been fixed and an update will be published soon.
