### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by mynavblog** [MicrosoftDocs/dynamics365smb-devitpro-pb#754]
Instead of SqlStatementsExecuted := BigText;
should be: SqlStatementsExecuted : BigText;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfdbc066-f5d5-9441-ae8e-efdf67987e57
* Version Independent ID: 2e898797-1f15-0dc6-3159-5e325673099e
* Content: [SqlStatementsExecuted Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlstatementsexecuted-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlstatementsexecuted-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/sessioninformation/sessioninformation-sqlstatementsexecuted-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This will be fixed with the next doc refresh.
