### ISSUE TITLE
Allowed Extension Target Level is set to OnPrem is not available in BC130

### ISSUE THREAD

**Issue by MarkCWEV** [MicrosoftDocs/dynamics365smb-devitpro-pb#755]
Allowed Extension Target Level is set to OnPrem is not available in BC130

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8497fb5b-00c8-6346-941f-ebc4ee762aa5
* Version Independent ID: 502ddf94-207b-7eaf-680f-900ad8198681
* Content: [Getting Started with C/SIDE and AL Side-By-Side for On-Premises - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-al-for-onprem)
* Content Source: [dev-itpro/developer/devenv-get-started-al-for-onprem.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-get-started-al-for-onprem.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
That's true - the topic reflects the latest version. For BC130 you must use Internal. Thanks.
