### ISSUE TITLE
Code snippet below?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#756]
The desription of the Option data type is mentioning a "code snippet below". But it's not there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c9bdf2-b0eb-ae82-4c62-6e52cdbe310a
* Version Independent ID: 593a228e-3ca3-fb32-149a-45a467e213e8
* Content: [Data Types and Methods in AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/library)
* Content Source: [dev-itpro/developer/methods-auto/library.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/library.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The overview is autogenerated and takes the first line from the Option Data Type topic, which mentions a code snippet. Will fix this with the next autogenerated round of methods. Thanks again!

**Comment by lvanvugt** [comment]
Thanx, Susanne. I thought so as it looks too techie and less human unfortunately.

**Comment by SusanneWindfeldPedersen** [comment]
Yes, I agree. But there's a lot of goodness in a 100% reflection on the code, so that we ensure that all methods are surfaced in help, because it is otherwise very error-prone and hard to maintain. But thanks for your input.

**Comment by SusanneWindfeldPedersen** [comment]
Should be updated now, so closing this issue.

**Comment by lvanvugt** [comment]
Hi @SusanneWindfeldPedersen, meaning it should also be appearing in the site? Not yet.
![image](https://user-images.githubusercontent.com/18466198/66488967-20ae9700-eaaf-11e9-975e-aa6845069254.png)
