### ISSUE TITLE
Migrating translation

### ISSUE THREAD

**Issue by adrian-panaite** [MicrosoftDocs/dynamics365smb-devitpro-pb#758]
For Wave 2 and later, what is the method to migrate old translation in txt files to format in xliff files for very large extensions like Base Application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#feedback)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we're finalizing a short topic that describes how to use a script that we provide access to from the Microsoft/AL repo. To convert language translations written in .txt files to xliff files, follow these steps:

1) Find the source code the translation was created for ie. C/AL code either provided from a Docker container or your local server.
2) Go through the steps for converting C/AL to AL with Txt2AL, and make sure the flag --addLegacyTranslationInfo is specified when invoking Txt2AL.
[Docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool)
3) Step 2 generated xliff translation(s), Run the script TxT2Xliff.ps1 and provide it the TxtTranslation, XliffTranstion and the output folder. Find the script here: [Microsoft/AL](https://github.com/microsoft/AL/blob/master/scripts/Txt2Xliff.ps1).

**Comment by r4luk** [comment]
Hi Susanne,
Thanks a lot for your detailed explanation.
I'm trying to follow the steps you provided above.
I have the translations for BC13 CU8, in the ,txt format.

1. I did manage to export the files from C/AL
2. At step 2, when i add the flag --addLegacyTranslationInfo, it seems this flag is not recognized:
![image](https://user-images.githubusercontent.com/21063415/68600234-cdaf7180-04aa-11ea-966a-9ff670b5618a.png)
If I'm not using this flag, the files are exported in AL.

What am I doing wrong? This flag works only on BC14 maybe?

Thanks in advance for your help :)

**Comment by r4luk** [comment]
I found the flag in BC14. :)
