### ISSUE TITLE
Broken reference

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#760]
"The file should contain something similar to the example shown below." There is no example shown below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfebcfad-5d9d-5365-5ae0-524780e74355
* Version Independent ID: 0a3a2ef5-ceeb-7b4d-572f-6a80a4c90c46
* Content: [The Txt2Al Conversion Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool)
* Content Source: [dev-itpro/developer/devenv-txt2al-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-txt2al-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this, it didn't make sense. The topic will be updated with the next refresh.
