### ISSUE TITLE
Rules introduced in BC15 (Business Central Wave II release) are not listed

### ISSUE THREAD

**Issue by LauraNicolas** [MicrosoftDocs/dynamics365smb-devitpro-pb#761]
I am developing for the new version: BC15. I am using the CodeAnalyzers and I am getting warnings for rules that are not listed in this page.

For example, I am getting a message for rule AA0210.

Could the documentation be updated with rules introduced in the last release? Thanks!

Salut!
Laura Nicolàs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4cb6345-f9b7-5018-355c-6125088171f9
* Version Independent ID: c7764a10-88ca-8146-6b45-b27e12423ae0
* Content: [CodeCop Analyzer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop#feedback)
* Content Source: [dev-itpro/developer/analyzers/codecop.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We're aware that these are not updated and looking into solving this. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
This is now fixed and will be pushed live with the next doc refresh. Thanks!
