### ISSUE TITLE
-1 represents true?

### ISSUE THREAD

**Issue by emeriksp** [MicrosoftDocs/dynamics365smb-devitpro-pb#762]
"For Boolean values, -1 represents true and 0 represents false." 
I believe this is wrong. -1 cannot be evaluated into a boolean. 
The text should have been "For Boolean values, 1 represents true and 0 represents false."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9522a987-a499-0673-ffd6-87a59045b3ff
* Version Independent ID: 72b6d1c7-d09b-578e-cd01-ac985c40e645
* Content: [Integer Data Type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/integer-data-type#feedback)
* Content Source: [dynamics-nav/Integer-Data-Type.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Integer-Data-Type.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - it is an error that's been around for quite a while. We will fix this with the next refresh of the docs. Thanks!
