### ISSUE TITLE
A walkthrough should describe steps to a working solution

### ISSUE THREAD

**Issue by stephskf** [MicrosoftDocs/dynamics365smb-devitpro-pb#763]
The walktrough starts with OData and change to ODataV4 halfway.. please test your procedure before publishing a walktrough, this doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ab2d51-62c3-fa9a-7a3f-556097ef3c43
* Version Independent ID: a93c5d06-2ca9-f8d5-7b49-b69429e7f613
* Content: [Walkthrough: Creating and Interacting with a Page Web Service (OData) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--creating-and-interacting-with-a-page-web-service--odata-#feedback)
* Content Source: [dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Sorry for the inconvenience. We have adjusted and tested the walkthrough so that it works now. We will publish the update soon.  Thanks for the feedback!
