### ISSUE TITLE
"To enable AL Code Actions" not clear

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#764]
In section "To enable AL Code Actions", points 2 and 3 clearly refer to editing the settings.json file, whereas point 1 refers to open the settings page, where is no "al.enableCodeActions", but "Al: Enable Code Actions" and a checkbox instead.

IMHO it would be more helpful to open Ctrl+P instead, choosing "settings.json" and edit the values there (as described in points 2 and 3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 325dad95-f893-2b85-ca29-f0b019c90d17
* Version Independent ID: 75e0dcf4-2bb8-bd81-e120-240d08d0d0b3
* Content: [AL Code Actions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-code-actions#feedback)
* Content Source: [dev-itpro/developer/devenv-code-actions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-code-actions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. You're right, there are two ways of enabling AL Code Actions, through the Settings page and the `settings.json` file, and the instructions seem to mix them up. This has been corrected and will be published soon.
