### ISSUE TITLE
Information up to date?

### ISSUE THREAD

**Issue by CptBlaubart** [MicrosoftDocs/dynamics365smb-devitpro-pb#765]
As fas as I can tell, the SETCURRENTKEY command only selects the order in which the records are returned on SQL Databases. It does not affect the selection of any secondary keys anymore as the SQL indexing has rendered this feature obsolete. - I'm not 100% sure about this, but several sources including my own analyzation of the generated SQL Queries suggest that it basicly sets the  parameters after the "ORDER BY" function and doesn't affect anything else.

EDIT: I opened the Page the wrong way and didn't get the attached details below

EDIT 2: I forgot to add a second source for my suspicion: It's in the Book "The NAV/SQL Performance Field Guide" By Jörk A. Stryk ISBN: 978-3-8370-1442-6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e176d7-aca3-6ef2-46de-27cfa794de32
* Version Independent ID: 356f40be-0f06-d10f-2b4f-af8557ce9ca8
* Content: [SetCurrentKey Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/setcurrentkey-function--record-)
* Content Source: [dynamics-nav/SETCURRENTKEY-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SETCURRENTKEY-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
The NAV documentation is no longer maintained. Closing this issue. Thanks.
