### ISSUE TITLE
Placeholders should be included into Text Constants, otherwise it is misleading

### ISSUE THREAD

**Issue by KSH-audibene** [MicrosoftDocs/dynamics365smb-devitpro-pb#769]
Separating text constant from placeholder is: 
1) misleading - easy to miss the concept of placeholders; 
2) against the code style; 

I suggest  Text001	"The number: %1", Text002	"The text: %2" instead 
and the following as example: 
MESSAGE(Text000 + Text001 +Text002, Number, Text);  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe8f7471-828e-f2e1-ec8c-5320d472386f
* Version Independent ID: 65c26e72-6079-4052-17d3-da4b46aa3916
* Content: [MESSAGE Function (Dialog) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/message-function--dialog-#feedback)
* Content Source: [dynamics-nav/MESSAGE-Function--Dialog-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/MESSAGE-Function--Dialog-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, that is very true. This will be changed with the next doc refresh, thanks.
