### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#77]
1. When an event is raised, the subscriber function is a called and it code is run.
In the above sentence, the a after is a called should be deleted, also should be and it's code is run

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a632a8b6-4115-8baf-e40b-85c579d9fc8e
* Version Independent ID: 02b25bb1-01ba-e401-cd97-f4a6279f791b
* Content: [Introducing Events - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/introducing-events)
* Content Source: [dynamics-nav/Introducing-Events.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Introducing-Events.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The issue has been fixed and will be available with the next update to the live site.
