### ISSUE TITLE
Bussiness Central OnPrem 2019 wave 2 ES setup errors on Windows 10 1903

### ISSUE THREAD

**Issue by JavierFuentes** [MicrosoftDocs/dynamics365smb-devitpro-pb#770]
I've trying to install BC OnPrem 2019 Wave 2.ES on mi Windows 10 1903 version 18362.387 laptop but have this critical errors because seems some files are missing and service doesn't run at the end:

># Microsoft Dynamics 365 Business Central compilación 36510
>### Informe de errores
>
>*Herramienta de administración de servidor*
*Componentes del cliente*
**Error irrecuperable durante la instalación.**
>
>Error al leer el archivo D:\Business Central OnPrem - versiones\Dynamics 365 Business Central 2019 Release Wave 2.ES.36649_v15.DVD\LegacyDlls\program files\Microsoft Dynamics NAV\150\RoleTailored Client\sr-Latn-RS\ Microsoft.Dynamics.Framework.UI.WinForms.DataVisualization.resources.dll.  
Compruebe que el archivo existe y que puede obtener acceso a él.
>
>*Servidor*
*Componentes de Microsoft Dynamics 365 Business Central Server*
**Error irrecuperable durante la instalación.**
>
>Error al leer el archivo D:\Business Central OnPrem - versiones\Dynamics 365 Business Central 2019 Release Wave 2.ES.36649_v15.DVD\ServiceTier\program files\Microsoft Dynamics NAV\150\Service\Add-ins\Timeline\et-EE\ Microsoft.Dynamics.Framework.UI.WinForms.DataVisualization.Timeline.resources.dll.
Compruebe que el archivo existe y que puede obtener acceso a él.

This is the LOG:

_=== Logging started: 2019/10/12 19:30:41 ===
Executable: D:\Business Central OnPrem - versiones\Dynamics 365 Business Central 2019 Release Wave 2.ES.36649_v15.DVD\setup.exe v15.0.36510.0
Computer  : XYZ
--- logging level: standard ---
RegistrySearch: Id = 'SqlServerInstalled', checking registry key existence. 
                Id = 'SqlServerInstalled', Key = 'SYSTEM\CurrentControlSet\Services\MSSQLSERVER', Exists = '1'
RegistrySearch: Id = 'SqlNCLIInstalled', checking registry key existence. 
                Id = 'SqlNCLIInstalled', Key = 'SOFTWARE\Microsoft\SQLNCLI11', Exists = '1'
RegistrySearch: Id = 'DotNetFxRelease', searching for registry key value. 
                Id = 'DotNetFxRelease', Key = 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', Value = '528040'
RegistrySearch: Id = 'VstoInstalled', searching for registry key value. 
                Id = 'VstoInstalled', Key = 'SOFTWARE\Microsoft\VSTO Runtime Setup\v4R', Value = '1'
RegistrySearch: Id = 'PowerShell30Installed', searching for registry key value. 
                Id = 'PowerShell30Installed', Key = 'SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', Value = '5.1.18362.1'
RegistrySearch: Id = 'WindowsSearchInstalled', checking registry key existence. 
                Id = 'WindowsSearchInstalled', Key = 'SYSTEM\CurrentControlSet\Services\WSearch', Exists = '1'
RegistrySearch: Id = 'Outlook', checking registry key existence. 
                Id = 'Outlook', Key = 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\OUTLOOK.EXE', Exists = '1'
RegistrySearch: Id = 'Outlook15', checking registry key existence. 
                Id = 'Outlook15', Key = 'Software\Microsoft\Office\15.0\Outlook\Setup', Exists = '1'
RegistrySearch: Id = 'Outlook16', checking registry key existence. 
                Id = 'Outlook16', Key = 'Software\Microsoft\Office\16.0\Outlook\Setup', Exists = '0'
RegistrySearch: Id = 'VCPPSpLevel', searching for registry key value. 
                Id = 'VCPPSpLevel', Key = 'SOFTWARE\Microsoft\DevDiv\VC\Servicing\12.0', Value = '0'
RegistrySearch: Id = 'VCPPInstalled', checking registry key existence. 
                Id = 'VCPPInstalled', Key = 'SOFTWARE\Microsoft\DevDiv\VC\Servicing\12.0', Exists = '1'
RegistrySearch: Id = 'VCPP64Installed', checking registry key existence. 
                Id = 'VCPP64Installed', Key = 'SOFTWARE\Microsoft\DevDiv\VC\Servicing\12.0', Exists = '1'
RegistrySearch: Id = 'VCPP201764Installed', checking registry key existence. 
                Id = 'VCPP201764Installed', Key = 'SOFTWARE\Microsoft\DevDiv\VC\Servicing\14.0', Exists = '1'
RegistrySearch: Id = 'IISInstalled', checking registry key existence. 
                Id = 'IISInstalled', Key = 'SOFTWARE\Microsoft\InetStp', Exists = '1'
RegistrySearch: Id = 'IISWinAuthInstalled', searching for registry key value. 
                Id = 'IISWinAuthInstalled', Key = 'SOFTWARE\Microsoft\InetStp\Components', Value = '1'
RegistrySearch: Id = 'IISASPNETInstalled', searching for registry key value. 
                Id = 'IISASPNETInstalled', Registry value not found. Key = 'SOFTWARE\Microsoft\InetStp\Components', Value = 'ASPNET'
RegistrySearch: Id = 'IISASPNET45Installed', searching for registry key value. 
                Id = 'IISASPNET45Installed', Key = 'SOFTWARE\Microsoft\InetStp\Components', Value = '1'
RegistrySearch: Id = 'IISNETFXInstalled', searching for registry key value. 
                Id = 'IISNETFXInstalled', Registry value not found. Key = 'SOFTWARE\Microsoft\InetStp\Components', Value = 'NetFxExtensibility'
RegistrySearch: Id = 'IISNETFX45Installed', searching for registry key value. 
                Id = 'IISNETFX45Installed', Key = 'SOFTWARE\Microsoft\InetStp\Components', Value = '1'
RegistrySearch: Id = 'IISISAPEXInstalled', searching for registry key value. 
                Id = 'IISISAPEXInstalled', Key = 'SOFTWARE\Microsoft\InetStp\Components', Value = '1'
RegistrySearch: Id = 'HttpActivationInstalled', checking registry key existence. 
                Id = 'HttpActivationInstalled', Key = 'SYSTEM\CurrentControlSet\Services\WAS', Exists = '1'
RegistrySearch: Id = 'IISISAPIFIInstalled', searching for registry key value. 
                Id = 'IISISAPIFIInstalled', Key = 'SOFTWARE\Microsoft\InetStp\Components', Value = '1'
RegistrySearch: Id = 'IISREQSTFIInstalled', searching for registry key value. 
                Id = 'IISREQSTFIInstalled', Key = 'SOFTWARE\Microsoft\InetStp\Components', Value = '1'
RegistrySearch: Id = 'IISSTATICInstalled', searching for registry key value. 
                Id = 'IISSTATICInstalled', Key = 'SOFTWARE\Microsoft\InetStp\Components', Value = '1'
RegistrySearch: Id = 'WebComponentsPrerequisitesInstalled', searching for registry key value. 
                Id = 'WebComponentsPrerequisitesInstalled', Registry key not found. Key = 'SOFTWARE\Microsoft\Microsoft Dynamics NAV\150\Web Components Prerequisites'
RegistrySearch: Id = 'IdentityFoundationInstalled', checking registry key existence. 
                Id = 'IdentityFoundationInstalled', Key = 'SOFTWARE\Microsoft\Windows Identity Foundation\Setup\v3.5', Exists = '1'
RegistrySearch: Id = 'IISAspNetCoreModuleInstalled', searching for registry key value. 
                Id = 'IISAspNetCoreModuleInstalled', Key = 'SOFTWARE\Microsoft\IIS Extensions\IIS AspNetCore Module', Value = '1'
Configuring package. Id = 'ARP'
MSI log file set to: C:\Users\JAVIER1\AppData\Local\Temp\setup.wix.msi.19.log
Done configuring package. Id = 'ARP' ReturnCode = 0
Configuring package. Id = 'WebClientDependency'
Path to executable = 'D:\Business Central OnPrem - versiones\Dynamics 365 Business Central 2019 Release Wave 2.ES.36649_v15.DVD\WebClientDependencyInstaller.exe', Arguments = '/detect'
Done configuring package. Id = 'WebClientDependency' ReturnCode = 0
Configuring package. Id = 'DevelopmentEnvironment'
MSI log file set to: C:\Users\JAVIER1\AppData\Local\Temp\setup.wix.msi.1a.log
Done configuring package. Id = 'DevelopmentEnvironment' ReturnCode = 0
Configuring package. Id = 'RoleTailoredClient'
MSI log file set to: C:\Users\JAVIER1\AppData\Local\Temp\setup.wix.msi.1b.log
Windows Installer: Error: Error reading from file: D:\Business Central OnPrem - versiones\Dynamics 365 Business Central 2019 Release Wave 2.ES.36649_v15.DVD\LegacyDlls\program files\Microsoft Dynamics NAV\150\RoleTailored Client\sr-Latn-RS\Microsoft.Dynamics.Framework.UI.WinForms.DataVisualization.resources.dll.   Verify that the file exists and that you can access it.
Done configuring package. Id = 'RoleTailoredClient' ReturnCode = 1603
Configuring package. Id = 'SQLDemoDatabase'
MSI log file set to: C:\Users\JAVIER1\AppData\Local\Temp\setup.wix.msi.1c.log
Done configuring package. Id = 'SQLDemoDatabase' ReturnCode = 0
Configuring package. Id = 'ServiceTier'
MSI log file set to: C:\Users\JAVIER1\AppData\Local\Temp\setup.wix.msi.1d.log
Windows Installer: Error: Error reading from file: D:\Business Central OnPrem - versiones\Dynamics 365 Business Central 2019 Release Wave 2.ES.36649_v15.DVD\ServiceTier\program files\Microsoft Dynamics NAV\150\Service\Add-ins\Timeline\et-EE\Microsoft.Dynamics.Framework.UI.WinForms.DataVisualization.Timeline.resources.dll.   Verify that the file exists and that you can access it.
Done configuring package. Id = 'ServiceTier' ReturnCode = 1603
Configuring package. Id = 'WebClient'
MSI log file set to: C:\Users\JAVIER1\AppData\Local\Temp\setup.wix.msi.1e.log
Done configuring package. Id = 'WebClient' ReturnCode = 0
SUCCESS: Package Componentes de la instalación de Microsoft Dynamics 365 Business Central executed sucessfully.
SUCCESS: Package Requisitos previos de IIS para componentes de servidor web executed sucessfully.
SUCCESS: Package Microsoft Dynamics 365 Business Central AL Development Environment executed sucessfully.
ERROR: Package Componentes del cliente failed with error. See detailed message above.
SUCCESS: Package Base de datos de ejemplo Cronus para Microsoft Dynamics 365 Business Central executed sucessfully.
ERROR: Package Componentes de Microsoft Dynamics 365 Business Central Server failed with error. See detailed message above.
SUCCESS: Package Componentes de servidor web executed sucessfully.
=== Logging stopped: 2019/10/12 19:38:53 ===_

**Comment by JavierFuentes** [comment]
# Solved.

The problem was path total lenght was too long for some files

**Comment by danny-situ** [comment]
Hi Javier,
I experienced the same issue when trying to install the 365 BC OnPrem 2019 Wave 2 for Update 15.2. How to solve the path's total length that is too long for some files?

**Comment by danny-situ** [comment]
The issue is solved by doing the following:
1. Uninstall the current installation that has the issue of path length that is too long. Please note that we cannot just "repair the installation" as it always look for the necessary files from the previous path / folder when we installed it.
2. Copy the whole installation folder to shorter path for example: c:\Temp
3. Repeat the installation from this new installation path or folder.
