### ISSUE TITLE
SubType Json is missing

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#772]
There is a forth property value "Json" existing, but not explained anywhere, just like in  https://docs.microsoft.com/en-us/dynamics-nav/subtype-property--blob- 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f4a8c1-6e45-d3f5-1326-fec1d629d1e6
* Version Independent ID: 0189005d-9381-7a8d-cbfa-bd5915612e94
* Content: [SubType Property (BLOB) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-subtype-blob-property)
* Content Source: [dev-itpro/developer/properties/devenv-subtype-blob-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-subtype-blob-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, the Json value has been added to the article in both repos and will be available with the next doc refresh. Thanks!
