### ISSUE TITLE
Visual Studio for RDLC

### ISSUE THREAD

**Issue by ReneGubler** [MicrosoftDocs/dynamics365smb-devitpro-pb#775]
Whicht versions of Visual Studio are compatible to develop RDLC Reports? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dbce66b-fa62-827f-b712-13534fd92ab7
* Version Independent ID: e7b1c5dc-ead8-738b-bee9-173c491a5904
* Content: [System Requirements for Business Central 2019 Release Wave 2 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central-v15#feedback)
* Content Source: [dev-itpro/deployment/system-requirement-business-central-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/system-requirement-business-central-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! This information is currently missing from the article, sorry. We will verify and add the info soon. For now, the support is the same as for Business Central Spring 2019:  Visual Studio 2017 with Microsoft Rdlc Report Designer for Visual Studio installed or Visual Studio 2015 Professional or Enterprise edition with SQL Server Data Tools installed.
