### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by DavidRoys** [MicrosoftDocs/dynamics365smb-devitpro-pb#776]
Please provided more examples covering the filter syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcee11f-b950-4e3e-0bd3-826c561d0839
* Version Independent ID: dbbf5913-661a-4ada-b9dd-9084f10c0c00
* Content: [DataItemTableView Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-dataitemtableview-property#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-dataitemtableview-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-dataitemtableview-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your request. These have been added - they will be available with the next doc refresh.
