### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#777]
Why is there no list of links to RecordRef functions as there is for the FieldRef object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac9c7e2-7824-ffaf-1ba2-04ea75ed8373
* Version Independent ID: 4a1f51a8-33e1-fb20-5131-d31d8200660a
* Content: [RecordRef Data Type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/recordref-data-type)
* Content Source: [dynamics-nav/RecordRef-Data-Type.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/RecordRef-Data-Type.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for your feedback. These have been added to the article and will be available with the next doc refresh.

**Comment by j2associates** [comment]
Hello,

It is really helpful when the notification includes a link back to the
original page. Susanne Windfeld Pedersen always includes a link, some
others do not so you have no way of going back to see what was changed.

Have a great day!
