### ISSUE TITLE
system parts such as Microsoft Outlook, Notes, and Record Links

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#778]
Is there still a Microsoft Outlook system part?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 605a1acd-e3b5-7f1b-bdc8-335ff00fb141
* Version Independent ID: 7eb6b1f3-55f5-8ec0-d5fc-89d82decea57
* Content: [Adding a FactBox to a Page - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-a-factbox-to-page)
* Content Source: [dev-itpro/developer/devenv-adding-a-factbox-to-page.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-a-factbox-to-page.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question - yes, you should be able to specify a systempart as either Notes, Links or Outlook.

**Comment by jswymer** [comment]
Hello again, we double checked and the Outlook system part is only supported on Dynamics NAV Connected to Business Central (i.e. the Windows client). Although you can set it in AL, the part will be ignored at runtime in the Web client. Sorry for the confusion.

**Comment by lvanvugt** [comment]
Thanx for the extra investigation. So you are going to update the topic?

**Comment by jswymer** [comment]
Yes, we will publish an update soon.

**Comment by jswymer** [comment]
We have adjusted the article to suit and an update will be published soon. Thanks for the feedback!
