### ISSUE TITLE
Multiple Typos

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#78]
1. An event is published by adding C/AL function that is specifically set up as an event publisher.
Should be by adding a C/AL function

2. Trigger events are by predefined event publisher functions that are called automatically at runtime. 
Should be Trigger events are predefined event

3. restrictions that you must follow, otherwise you not able to compile your code changes:
Should be otherwise you will not be able to compile

4a. Set the function Event Property to Publisher and the EventType Property to either Business or Integration.
4b. Set the function EventType Property to Business or Integration.
Should either delete line 4b or remove and the EventType Property to either Business or Integration in line 4a

5. that are defined in the other objects than publisher function object, set the Local Property to No.
Should be that are defined in other objects than the publisher function

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07689958-6e86-fb5c-3540-cbbc6bf94704
* Version Independent ID: b0023147-971a-f105-7c65-c40a124e9aae
* Content: [Publishing Events - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/publishing-events)
* Content Source: [dynamics-nav/Publishing-Events.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Publishing-Events.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The issues have been fixed and will be available with the next update to the live site.

**Comment by ph-jo** [comment]
Another typo: "You can create a new object or use and existing object."
and -> an
