### ISSUE TITLE
Cloud Solution Provider for Developers link to https://aka.ms/pcsdkhol not working

### ISSUE THREAD

**Issue by Quivelus** [MicrosoftDocs/dynamics365smb-devitpro-pb#780]
Cloud Solution Provider for Developers link to https://aka.ms/pcsdkhol not working. I get and "HTTP Error 404. The requested resource is not found." error when following the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71aa4400-739a-6867-a2f5-2917a72d7620
* Version Independent ID: e0153a2f-2b2f-919a-33b1-43b0e9113413
* Content: [The “Ready to Go” Online learning for developers, architects, and engineers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-learning-dev-archs-engineers?tabs=forexperts)
* Content Source: [dev-itpro/developer/readiness/readiness-learning-dev-archs-engineers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-learning-dev-archs-engineers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Unfortunately, the link is broken and we're not able to fix it. The [Read](https://channel9.msdn.com/Series/cspdev) link points to the same broken link. We will take it out for now with the next refresh of the docs.
