### ISSUE TITLE
Obsolete general rule

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#782]
This general rule is not needed so please leave it out:

For pages/tables in the base application of BC that you extend, you must set the prefix/suffix at the top object level

Justification:
I can build two extensions which extend the same table or page with a table/pageextension object. Object IDs are unique (non-conflicting) but the extension object namescan be exactly the same. I can deploy both extensions on the same database.
So teher is no need to use a pre/suffix here, and as such do not make a general rule that says a pre/suffix should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e572f37f-91f5-e8b2-aa5b-242adb0ad329
* Version Independent ID: 32e50127-f6e4-1107-289e-c0b18b1c2d91
* Content: [Prefix and suffix for naming in extensions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix)
* Content Source: [dev-itpro/compliance/apptest-prefix-suffix.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-prefix-suffix.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by navaddict** [comment]
Interesting post Ivan.  I **REALLY** need an answer from Microsoft on this as I'm currently building an App with (many) hundreds of objects and changing all the object names to include or omit a prefix/suffix is a major pain I'd **much** prefer to avoid..!!

**Comment by lvanvugt** [comment]
Any update on this?

**Comment by atoader** [comment]
Hi @lvanvugt ! We will keep the prefix/suffix in place until we have support for namespaces. This could be optimized, but we believe there are issues that are more valuable to the community in which we can invest our resources at the moment.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue. Thanks.

**Comment by lvanvugt** [comment]
> 
> 
> Hi @lvanvugt ! We will keep the prefix/suffix in place until we have support for namespaces. This could be optimized, but we believe there are issues that are more valuable to the community in which we can invest our resources at the moment.

Can fully undrstand, but does not sav us the pain.
