### ISSUE TITLE
Typo: RLD file

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#783]
Little typo: RLD file (section "Remarks")
The article mentions both RDL and RDLC files, whereas the property is named RDLC. The code example uses RDL. 
Are RDL and RDLC the same, when to use what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 436eb8cb-77fd-8ada-81a0-3a11efae7d53
* Version Independent ID: 678e32c0-3c87-eb24-1339-f206fc8bf223
* Content: [RDLCLayout Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-rdlclayout-property)
* Content Source: [dev-itpro/developer/properties/devenv-rdlclayout-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-rdlclayout-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching that. RDL is server-side and RDLC is client-side. Although the DefaultLayout property can be set to RDLC, we support RDL format on reporting for Business Central. The topic will be fixed with the next refresh of the docs. Thanks.
