### ISSUE TITLE
Broken syntax

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#784]
The name should indicate what the operation that the subscriber performs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb5fd8d8-9755-4584-b6ed-c00f8569332e
* Version Independent ID: 208da94e-f3f9-ba2b-6087-24906fe16d4a
* Content: [Best Practices with Microsoft Dynamics NAV Events - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/best-practices-with-microsoft-dynamics-nav-events)
* Content Source: [dynamics-nav/Best-Practices-with-Microsoft-Dynamics-NAV-Events.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Best-Practices-with-Microsoft-Dynamics-NAV-Events.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for catching this, it will be fixed with the next doc refresh.
