### ISSUE TITLE
Copies of data bases

### ISSUE THREAD

**Issue by carlmhead-theta** [MicrosoftDocs/dynamics365smb-devitpro-pb#785]
As of now it's possible to download copies of production databases through the admin portal; this page seems to be outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0ef3bc-7516-dae7-6cca-d5a9b680364f
* Version Independent ID: 288d30ad-0b2d-8c18-63fa-d5555eb7416e
* Content: [FAQ about developer and IT-Pro experiences - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/faq#feedback)
* Content Source: [dev-itpro/faq.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello @carlmhead-theta,
Thank you for your feedback. This has now been fixed.
