### ISSUE TITLE
Wrong ODATA Base URL for OnPrem

### ISSUE THREAD

**Issue by fommo** [MicrosoftDocs/dynamics365smb-devitpro-pb#786]
The URL:s are still wrong for OnPrem. Instead of this
  https://&lt;base URL&gt;:&lt;port&gt;/v1.0/api/&lt;API version&gt;/
it should be
  https://&lt;base URL&gt;:&lt;port&gt;/&lt;tenant&gt;/api/&lt;API version&gt;/
Example:
  https://nav.contoso.com:7048/NAV/api/v1.0/

It took us a very long time to figure out why v1.0 was before /api/ as that is not working nor making any sense.
Also, could you please explain the difference between the API Version "beta" and "v1.0". Shouldn't this be "v1.0" now when the product is already on it's third release (counting from R13 to R15)? Will the "beta" version be deprecated or can it always be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17c4eef7-2ff2-eeeb-d285-095002e99475
* Version Independent ID: 2beae6be-8b5f-2a48-4b68-81810248b8f6
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics#feedback)
* Content Source: [dynamics-nav/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/endpoints-apis-for-dynamics.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This is fixed with the next refresh of the docs.
