### ISSUE TITLE
Wrong ODATA Base URL for OnPrem

### ISSUE THREAD

**Issue by fommo** [MicrosoftDocs/dynamics365smb-devitpro-pb#787]
This was reported for the beta version (https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics) on december 8, 2018 and it's still wrong for OnPrem for version 1.0
Instead of this
  https://&lt;base URL&gt;:&lt;port&gt;/v1.0/api/&lt;API version&gt;/
it should be
  https://&lt;base URL&gt;:&lt;port&gt;/&lt;instance&gt;/api/&lt;API version&gt;/
Example:
  https://nav.contoso.com:7048/NAV/api/v1.0/

It took us a very long time to figure out why v1.0 was before /api/ as that is not working nor making any sense. Please correct this as it causes confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2e0a70-16db-cebb-ff63-e7b0a5f4f70d
* Version Independent ID: 041169de-956b-f1a8-c66b-7bf77f5e5f64
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics)
* Content Source: [dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This will be fixed with the next refresh of the docs.
