### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#79]
1. For more information about raiding and event, see Raising Events.
Should be for more information about raising an event

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08956d43-b153-66d1-a163-6d9612170d36
* Version Independent ID: ecf298fa-b831-51e3-5f12-fbe6edc6e30c
* Content: [Debugging Events - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/debugging-events)
* Content Source: [dynamics-nav/Debugging-Events.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Debugging-Events.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The issue has been fixed and will be available with the next update to the live site.
