### ISSUE TITLE
[!INCLUDEd365fin_md operates with some standard rules for classification:

### ISSUE THREAD

**Issue by QuantumSupraLogic** [MicrosoftDocs/dynamics365smb-devitpro-pb#790]
[!INCLUDEd365fin_md operates with some standard rules for classification:
Something has gone wrong there

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: 361bcd16-f67f-a66d-8451-e864ef80104f
* Version Independent ID: 70a445f0-1b3e-4838-2093-e821fda8e750
* Content: [Classifying Data in Dynamics 365 - Business Central](https://docs.microsoft.com/de-at/dynamics365/business-central/dev-itpro/developer/devenv-classifying-data)
* Content Source: [dev-itpro/developer/devenv-classifying-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-classifying-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by blrobl** [comment]
Hi, thanks for catching it, this will be fixed with the next doc refresh.
