### ISSUE TITLE
AL Development Requirements for Hardware are surely incorrect

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#792]
AL Development Requirements
The following table shows the minimum system requirements for customizing or extending Business Central using the AL language in Visual Studio Code.
..
Hardware resources	
Hard disk space: 500 MB.
CPU: 4 cores minimum
Memory: 16 GB for development only.
32 GB for developing and deploying locally.
64 GB for developing large apps

Please make a correction ... these hardware requirements must be nonsense...32GB of RAM for making page extension and deploying locally .... must be incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dbce66b-fa62-827f-b712-13534fd92ab7
* Version Independent ID: e7b1c5dc-ead8-738b-bee9-173c491a5904
* Content: [System Requirements for Business Central 2019 Release Wave 2 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central-v15)
* Content Source: [dev-itpro/deployment/system-requirement-business-central-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/system-requirement-business-central-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! According to the development team, for the most part the requirements depend on the size of the project. For example, when developing and deploying an extension that has fewer than 1000 objects, 16 GB should be enough.

**Comment by jswymer** [comment]
We have tweaked the requirements and the updated article will be published soon. Thanks!
