### ISSUE TITLE
Dropdown must be in Camel Case - DropDown

### ISSUE THREAD

**Issue by stefanoPrimo** [MicrosoftDocs/dynamics365smb-devitpro-pb#793]
Hi,
I've just found out that if I create a fieldgroup for showing certain fields in a drop-down, the name of this fieldgroup must be in camel case, so like that "DropDown". 
In the first example, the name has only the first letter capitalized. 
I've please you to fix this.

It would be better if you add like a Warning block saying that the name must respect the right capitalization. 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9979b71-a2f9-9032-5bba-161f6da5ff63
* Version Independent ID: 7fd0115f-bfec-43e1-e5c3-69bf2e4d383c
* Content: [Field Groups - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-field-groups)
* Content Source: [dev-itpro/developer/devenv-field-groups.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-field-groups.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next refresh of the docs.
