### ISSUE TITLE
XMLport and web client - what is the alternative

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#795]
Indeed as written above "In the Dynamics 365 Business Central Web client, Request pages are not supported." So what is the alternative? Please provide info on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2f92e5-2f2f-c619-03fb-af306a7fb078
* Version Independent ID: ddcf8182-3bd8-e9d6-030e-0c3ca01155b5
* Content: [XMLport Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-xmlport-object)
* Content Source: [dev-itpro/developer/devenv-xmlport-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-xmlport-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by lvanvugt** [comment]
Update: BC 15 does support XMLport request page, so update accordingly.

But then still what is the alternative on BC 14 and previous version?

**Comment by jswymer** [comment]
Thanks for the feedback! We have corrected the article and the messaging about request pages on XMLports, which as you mention are now supported in the Web client. For versions prior to BC15, the only alternative is the Windows client.

The updated content will be published soon. I will close this issue for now but if you have additional feedback, please feel free to add a comment and I will be happy to reopen the issue.

**Comment by lvanvugt** [comment]
Almost two months later the article still is the same haveing date October 1 on it. When wil it be updated?

**Comment by jswymer** [comment]
Hello,

The [Request pages ](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-request-pages) article has been updated to include a note about this. I hope this answers the issue; otherwise let us know. Thanks!
