### ISSUE TITLE
Microsoft SQL Server 2014

### ISSUE THREAD

**Issue by rainersmel** [MicrosoftDocs/dynamics365smb-devitpro-pb#797]
Why is Microsoft SQL Server 2014 not supported anymore? In the next next release(wave 2) it is supported. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b0aa47-5276-2fd9-173f-f05adcd420c2
* Version Independent ID: fb89206b-f5c1-6f2c-1f83-899c02aa8e89
* Content: [System Requirements for Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central#feedback)
* Content Source: [dev-itpro/deployment/system-requirement-business-central.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/system-requirement-business-central.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hell, sorry for the mistake. SQL Server 2014 is not supported on Business Central 2019 Release Wave 2. The article have been fixed and an update will be published soon. Thanks for the feedback!
