### ISSUE TITLE
Wrong name for the setting ClientServicesKeepAliveInterval

### ISSUE THREAD

**Issue by RasmusTidselbak** [MicrosoftDocs/dynamics365smb-devitpro-pb#798]
The setting ClientServicesKeepAliveInterval is called ClientServiceKeepAliveInterval in the text, which is missing an "s" in the middle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 568840c5-7c08-aa1d-fe62-fa580d0d9ba6
* Version Independent ID: 821381f5-a857-d106-b5f2-65c36d52f1d9
* Content: [Configure Session Timeout - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/understanding-session-timeouts#feedback)
* Content Source: [dev-itpro/administration/understanding-session-timeouts.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/understanding-session-timeouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
