### ISSUE TITLE
User Scenario wrong link

### ISSUE THREAD

**Issue by TheDenSter** [MicrosoftDocs/dynamics365smb-devitpro-pb#8]
https://docs.microsoft.com/en-gb/dynamics-nav/developer/devenv-extension-advanced-example-test#identifying-the-areas-of-the-extension-that-need-to-be-tested

In this section there is a mention of User Scenario, but it links to the "building an advanced sample extension" page, instead of the "User Scenario Documentation" page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13813e4d-d070-3e56-dcb6-f433ff04d945
* Version Independent ID: 0688f2ca-06fd-01d5-0355-64984443c54f
* Content: [Testing the Advanced Sample Extension - Dynamics NAV](https://docs.microsoft.com/en-gb/dynamics-nav/developer/devenv-extension-advanced-example-test#identifying-the-areas-of-the-extension-that-need-to-be-tested)
* Content Source: [dynamics-nav/developer/devenv-extension-advanced-example-test.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/developer/devenv-extension-advanced-example-test.md)
* Service: **unspecified**
* GitHub Login: @solsen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The link is pointing back to the right topic, but the text is misleading, so we will fix this in the next doc refresh.
