### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#80]
1. The walkthrough illustrates to the following tasks:
Should be illustrates the following tasks

2. OnAddressLineChanged function in codeunit 50001 My Publishers.
Should be 50001 My Subscribers

3. LOCAL [EventSubscriber] CheckAddressLine(line : Text[100])
The above function should NOT have LOCAL as a modifier - This is CRITICAL as the code will not run successfully as coded above. The actual code instructions to not mention setting Local to Yes, but anyone with any C/AL coding experience knows that is the requirement for the LOCAL modifier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b807fbe-3d0c-e3ae-6ba9-a2e23cb40329
* Version Independent ID: d5f8a07f-ec3b-0412-8af9-dcdaeb91ab1e
* Content: [Walkthrough: Publishing, Raising, and Subcribing to an Event in Microsoft Dynamics NAV - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--publishing--raising--and-subcribing-to-an-event-in-microsoft-dynamics-nav)
* Content Source: [dynamics-nav/Walkthrough--Publishing--Raising--and-Subcribing-to-an-Event-in-Microsoft-Dynamics-NAV.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Publishing--Raising--and-Subcribing-to-an-Event-in-Microsoft-Dynamics-NAV.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The issues have been fixed and will be available with the next update to the live site.
