### ISSUE TITLE
Task 6 - steps 3 and 4 use wrong version for System and Base application

### ISSUE THREAD

**Issue by JuricaB** [MicrosoftDocs/dynamics365smb-devitpro-pb#800]
Installing the System and Base application from 15.0 DVD results in following apps installed on the tenant:

Id            : 63ca2fa4-4f03-4f2b-a480-172fef340d3f
Name          : System Application
Version       : 15.0.36560.36649

Id            : 437dbf0e-84ff-417a-965d-ed2bb9650972
Name          : Base Application
Version       : 15.0.36560.36649

Running the commands described in Task 6- steps 3 and 4 then results in following error:
Sync-NAVApp : No published extensions match the specified parameter values.

Solution: Do not specify Version parameter, or use Get-NAVAppInfo to retrieve correct version before running this step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e435e27-0b74-7dcd-555d-977517fd3774
* Version Independent ID: ea922161-12f9-3f86-69f9-2044369d6574
* Content: [Upgrade an unmodified application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application#prerequisite)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! Sorry for the confusion. The version number must match the version number of the published extension. We have made some changes to the article that will hopefully make this clearer. The update will be published soon.
