### ISSUE TITLE
invalid space after comma in parameters

### ISSUE THREAD

**Issue by xgaronnat** [MicrosoftDocs/dynamics365smb-devitpro-pb#801]
finsql.exe dont't support spaces after comma in parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70281ae8-ff67-de91-c2e5-2fc310905189
* Version Independent ID: 7b5569e8-77b2-a6b3-f48d-df9fb90c52ae
* Content: [Using the Development Environment from the Command Prompt - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/cside/cside-command-prompt#feedback)
* Content Source: [dev-itpro/cside/cside-command-prompt.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/cside/cside-command-prompt.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, thanks for the feedback. I might be misunderstanding this issue, but for example, I am able to run the following command (with spaces after the commas):  `finsql.exe Command=generatesymbolreference, Database="MyDatabaseName", ServerName=MyDatabaseServer\MyDatabaseInstance`

Am I understanding this correctly, or do you have an example? Thanks

**Comment by jswymer** [comment]
The article has been updated and will be published soon. Thanks for the feedback!
