### ISSUE TITLE
Not true anymore

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#802]
This topic should be adjusted (removed) as BC 15 does suppikrt XMLport request pages. Similar issue reported here: #795

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 942855d1-dc6e-495a-ff56-1a0734f48fd4
* Version Independent ID: 6ca88cee-4066-a171-13eb-4847698c69c3
* Content: [The Web client does not support displaying the Request page of XMLPorts. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/uicop-aw0001-requestpageofxmlportscannotbedisplayed)
* Content Source: [dev-itpro/developer/analyzers/uicop-aw0001-requestpageofxmlportscannotbedisplayed.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/uicop-aw0001-requestpageofxmlportscannotbedisplayed.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Correct, thanks for the feedback! The article has been fixed to indicate that the rule only applies to Business Central Spring 2019 (BC14). The update will be published soon.
