### ISSUE TITLE
Wrong URLs for CLEAR and CLEARALL

### ISSUE THREAD

**Issue by adamLiveware** [MicrosoftDocs/dynamics365smb-devitpro-pb#808]
The URLs for CLEAR and CLEARALL in this page just go to the page for data types. I believe the correct URLs are:
CLEAR: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-clear-joker-method
CLEARALL: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-clearall-method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec57bfe-c887-74c6-319f-e7b995951edf
* Version Independent ID: 435de486-8089-eee7-93a9-97cbf6c836a9
* Content: [InitValue Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-initvalue-property#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-initvalue-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-initvalue-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Yes, it seems they were being redirected, this has just been fixed with the latest doc refresh. Thanks.
