### ISSUE TITLE
Task 6 Step 4 failed

### ISSUE THREAD

**Issue by rakeshcoder** [MicrosoftDocs/dynamics365smb-devitpro-pb#809]
I am upgrading from BC14 CU5 to BC15. While synching the base application app, the following error occurs. I tried -mode forcesync also but same error.

PS C:\WINDOWS\system32> Sync-NAVApp -ServerInstance bc150 -Name "Base Application" -Version 15.0.36560.36649            Sync-NAVApp : The following SQL error was unexpected:
There is already an object named 'SAMADHAN$G_L Entry$437dbf0e-84ff-417a-965d-ed2bb9650972$VSIFT$Key6' in the database.
At line:1 char:1
+ Sync-NAVApp -ServerInstance bc150 -Name "Base Application" -Version 1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$bc150/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Manag
   ement.Cmdlets.SyncNavApp

**Comment by jswymer** [comment]
Hello, thanks for the feedback. I have a couple questions that might help identify the problem. The link to the article is missing. Are you following this article [Upgrading an unmodified application to Dynamics 365 Business Central 2019 Release Wave 2](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application)? Also, is this a local version or W1?

**Comment by rakeshcoder** [comment]
Yes. I followed the article
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application

I am using W1.
I am upgrading from BC14 CU5 to BC15.

Regards,
Rakesh Kumar

**Comment by jswymer** [comment]
Unfortunately, this is a known issue between BC14 CU5 and the current version of BC15. It seems SumIndexFields where added to the key in BC15. For now, we recommend that you either upgrade from BC14 CU4 to BC15 or wait to upgrade until BC15 CU1 is released. Alternatively, you can modify the key in the G_L Entry table in C/AL environment of BC14 to match the key in the BC 15 AL base application. This will require that you synchronize your BC14 database again. ¤

**Comment by rakeshcoder** [comment]
Ok. Thank you.
