### ISSUE TITLE
Notification handlers are not documented.

### ISSUE THREAD

**Issue by salgiza** [MicrosoftDocs/dynamics365smb-devitpro-pb#81]
I was searching the docs on how to test methods that show notifications, and I could not find any handlers related to them. After checking within NAV, thought, I found that there are indeed two Handlers for notifications: SendNotificationHandler and RecallNotificationHandler.

I don't know when those handlers where introduced in NAV, but it doesn't look like the doc has been updated since.

Furthermore, it is practically impossible to understand how to use the MethodType property (and the related HandlerMethod property) just by looking at the docs, due to the lack of examples. Either there should be a small example on how to add the attribute to a procedure, link to the AL example in https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-advanced-example-test or, better, both.

And, just as final comment: procedure properties, in AL, are inserted using a syntax that, at least in C# is called Attributes. Wouldn't it have sense to use that naming in AL as well, in order to differentiate it from... well, properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c026a3b-2e03-5166-db04-782fc38d53bf
* Version Independent ID: e47dd45e-1248-4af9-1335-8db047b7c3e4
* Content: [MethodType Property (Test Codeunits) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-methodtype-property-test-codeunits)
* Content Source: [dev-itpro/developer/properties/devenv-methodtype-property-test-codeunits.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-methodtype-property-test-codeunits.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We've worked on improving the docs for describing handlers and the MethodType property and this is now pushed live. Thanks again.

**Comment by salgiza** [comment]
Thanks! Just a small detail, though: some of the examples are like:

`PROCEDURE StrMenuHandler@57(Option@1000 : Text[1024];VAR Choice@1001 : Integer;Instruction@1002 : Text[1024]);`

Which looks like someone exported a txt in NAV2018, not like a real AL code example.

**Comment by SusanneWindfeldPedersen** [comment]
We'll look into that and fix it with one of the next refreshes. Thanks for your patience and feedback.
