### ISSUE TITLE
Batch Request in API ($batch)

### ISSUE THREAD

**Issue by manichoy** [MicrosoftDocs/dynamics365smb-devitpro-pb#811]
how to use $batch in Business Central API?

I tried below in postman. 

POST https://api.businesscentral.dynamics.com/v1.0/{tenantid}/api/v1.0/$batch
Content-Type: application/json
Accept: application/json

{
"requests": [
{
"id":"1",
"method":"get",
"url":"/companies"
}
]
}

Currently above call get a "No HTTP resource" message

Response
{
"responses": [
{
"id": "1",
"status": 404,
"headers": {
"content-type": "application/json; charset=utf-8"
},
"body": {
"Message": "No HTTP resource was found that matches the request URI https://XXXXXXXXXXXXX.applicationservices.businesscentral.dynamics.com:7048/companies'."
}
}
]
}

**Comment by henrikwh** [comment]
Following uses OAuth (no tenant id I URL).

POST https://api.businesscentral.dynamics.com/v2.0/production/api/v1.0/$batch
Content-Type : multipart/mixed; boundary=batch_ef817c93-f6ca-4c82-8cbe-0260a6c6535f
And there the body:
--batch_ef817c93-f6ca-4c82-8cbe-0260a6c6535f
Content-Type: application/http 
Content-Transfer-Encoding:binary

GET companies HTTP/1.1

--batch_ef817c93-f6ca-4c82-8cbe-0260a6c6535f—

**Comment by manichoy** [comment]
Thanks @henrikwh 
it works!
