### ISSUE TITLE
MERGE returns an error

### ISSUE THREAD

**Issue by wintg-zns** [MicrosoftDocs/dynamics365smb-devitpro-pb#812]
The table at the top of this article shows:
PUT and MERGE 	Modifies the specified existing entity. 	OnModify

However, using MERGE returns an error:
BadRequest_MethodNotImplemented
'MERGE' requests for 'Entity' are not supported by Dynamics 365 Business Central OData web services.

Please correct the documentation with the verbs that are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23807fb-19f1-a393-5b35-fcb3bcbbd477
* Version Independent ID: 63c4d7b1-fe48-765b-5560-ca2d85ab6c68
* Content: [OData Web Services Data Modification - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-odata-to-modify-data#feedback)
* Content Source: [dev-itpro/webservices/use-odata-to-modify-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/use-odata-to-modify-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, this will be fixed in the next refresh of the docs. Thanks!
