### ISSUE TITLE
No mention of ETag

### ISSUE THREAD

**Issue by wintg-zns** [MicrosoftDocs/dynamics365smb-devitpro-pb#813]
An ETag is required in the request header for update operations. Without an ETag, the following error is returned:
BadRequest_InvalidToken
Could not validate the client concurrency token required by the service. Please provide a valid token in the client request. 

Please update the article with the proper use of an ETag as needed to make updates/modifications to records in Business Central.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23807fb-19f1-a393-5b35-fcb3bcbbd477
* Version Independent ID: 63c4d7b1-fe48-765b-5560-ca2d85ab6c68
* Content: [OData Web Services Data Modification - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-odata-to-modify-data#feedback)
* Content Source: [dev-itpro/webservices/use-odata-to-modify-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/use-odata-to-modify-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, this will be fixed in the next refresh of the docs. Thanks!
