### ISSUE TITLE
Problem with New-NAVApplicationDatabase cmdlet

### ISSUE THREAD

**Issue by JulioGandaraBPO** [MicrosoftDocs/dynamics365smb-devitpro-pb#814]
Hi,

I have a problem with this cmdlet, it returns an error:

New-NAVApplicationDatabase : The database create operation failed due to the following error returned by SQL Server:
No se puede quitar la base de datos 'migracionobjetos'; está en uso.
En línea: 1 Carácter: 1
+ New-NAVApplicationDatabase -DatabaseServer .\SQL2016 -DatabaseName mi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [New-NAVApplicationDatabase], NavCommandException
    + FullyQualifiedErrorId : .\SQL2016,Microsoft.Dynamics.Nav.Management.Cmdlets.CreateNavDatabase

There isn't any Database in the server with this name.

Thank you!

Best regards,

Julio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402665e0-ee3c-027b-a64f-3b4d718f0424
* Version Independent ID: 3d4a0497-8c48-1ebb-cb8c-4471eed7ea3b
* Content: [Code Conversion from C/AL to AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/devenv-code-conversion#feedback)
* Content Source: [dev-itpro/upgrade/devenv-code-conversion.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/devenv-code-conversion.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, just to be sure, the New-NAVApplicationDatabase cmdlet has the syntax: `New-NAVApplicationDatabase -DatabaseServer <SQL server>\<SQL server instance> -DatabaseName <database name>` .  In your example, the SQL server instance is SQL2016, correct?

**Comment by JulioGandaraBPO** [comment]
Hi, it's correct! Thank you

**Comment by jswymer** [comment]
Hello, I just spoke with the development team, and there is a known issue with this cmdlet if you are using SQL Server in a language other than English (US). This will be fixed in an upcoming cumulative update.

**Comment by JulioGandaraBPO** [comment]
OK, thank you! I hope it will be fixed soon.

Best regards,

Julio

**Comment by jswymer** [comment]
You are welcome. Sorry for the inconvenience. Check the BC15 CU1 when it comes out.
