### ISSUE TITLE
Handling Missing Option Values

### ISSUE THREAD

**Issue by JuricaB** [MicrosoftDocs/dynamics365smb-devitpro-pb#815]
Link for Handling Missing Option Values is broken - refers to (Handling Missing Option Values in Mapping.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7851ac36-bcd0-f45d-25d4-eb2a896347f3
* Version Independent ID: 47ac9f40-d705-945f-b7b4-637918d9d8f2
* Content: [Customizing Dynamics 365 for Sales and Dynamics NAV Integration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/customizing-dynamics-crm-and-dynamics-nav-integration)
* Content Source: [dynamics-nav/Customizing-Dynamics-CRM-and-Dynamics-NAV-Integration.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Customizing-Dynamics-CRM-and-Dynamics-NAV-Integration.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The file name was not valid so the topic in the link was never published, and the link never valid. This will be fixed with the next refresh which we will push as soon as possible. Thanks.
