### ISSUE TITLE
-LogPath parameter does not exist 

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/dynamics365smb-devitpro-pb#816]
-LogPath c:\temp\myerror.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5b38ef2-6154-f01c-a30c-172072000e27
* Version Independent ID: 8adc343a-3f0b-34d6-ad25-076b81b9cbcc
* Content: [Publish-NAVApp (Microsoft.Dynamics.Nav.Apps.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/publish-navapp?view=businesscentral-ps-15)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Apps.Management/Publish-NAVApp.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Apps.Management/Publish-NAVApp.md)

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
