### ISSUE TITLE
Double entry in Constraints table

### ISSUE THREAD

**Issue by PaulFurlet** [MicrosoftDocs/dynamics365smb-devitpro-pb#817]
2000000170	Configuration Package File

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a0b001a-5079-eb95-e02e-990a2fdc60f0
* Version Independent ID: 081f3805-06ab-c4dc-8459-22f11a146da5
* Content: [Viewing Table Data in Browser - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-view-table-data#feedback)
* Content Source: [dev-itpro/developer/devenv-view-table-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-view-table-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
