### ISSUE TITLE
Tenant domain is not easy to figure out

### ISSUE THREAD

**Issue by FBS-Martin** [MicrosoftDocs/dynamics365smb-devitpro-pb#82]
I signed up for a Dynamics 365 Business Central account and followed the directions for basic authentication, but the tenant domain had me stumped for a while. What worked for me was "&lt;tenant domain&gt; = &lt;default azure active directory GUID&gt;/sandbox".   That is not obvious from any NAV documentation. I figured it out by looking at an existing Web Service URI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The docs will be updated to reflect this.

**Comment by ohabash** [comment]
so where do we find `default azure active directory GUID`

Im worried about how smooth the rest of this will go if the docs keep hitting dead ends in the first few hours
