### ISSUE TITLE
Instance maybe should be BCDEMO?

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#820]
&gt;you must create a SQL Server instance named NAVDEMO
Since BC14 installer has created instance BCDEMO in SQL express.
So instance maybe should be BCDEMO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed67f405-48a3-f88e-5b33-9b1379a375c1
* Version Independent ID: 9f932e48-548b-5bbc-6a5e-88794105c8c5
* Content: [Installation Considerations for Microsoft SQL Server and Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/installation-considerations-for-microsoft-sql-server)
* Content Source: [dev-itpro/deployment/installation-considerations-for-microsoft-sql-server.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/installation-considerations-for-microsoft-sql-server.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed as suggested and the update will be published soon.
