### ISSUE TITLE
Technical error in page header

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#825]
At the very top of the page, you find
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory--- title: "Installation Considerations for Microsoft SQL Server and Business Central" ms.custom: na ms.date: 10/01/2019 ms.reviewer: na ms.suite: na ms.tgt_pltfrm: na ms.topic: article ms.service: "dynamics365-business-central"

Also as an menu item on the right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed67f405-48a3-f88e-5b33-9b1379a375c1
* Version Independent ID: 9f932e48-548b-5bbc-6a5e-88794105c8c5
* Content: [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-active-directory---
title: ](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/installation-considerations-for-microsoft-sql-server)
* Content Source: [dev-itpro/deployment/installation-considerations-for-microsoft-sql-server.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/installation-considerations-for-microsoft-sql-server.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback! The issue has been fixed and an update will be published soon.
