### ISSUE TITLE
Example of file naming should include prefix and have better object naming

### ISSUE THREAD

**Issue by ajkauffmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#829]
I think that this example for object name and corresponding file name could be improved:

page 1234 "MyPage" extends "Customer Card"	MyPage.PageExt.al

My suggestion is to use
page 50100 "PRE Customer Card" extends "Customer Card"  and file name: CustomerCard.PageExt.al

This shows
- custom object id
- Prefix in the object name (the file naming convention talks about leaving out prefix, so use it in the example for object names)
- The file name MyPage.PageExt.al doesn't tell me at all to which page this is a pageextension. It's way more clear when it just includes the name of the base object that you extend.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#feedback)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for this suggestion. The topic will be updated with the next doc refresh. Thanks!
