### ISSUE TITLE
How to get isv range and appsource rang no

### ISSUE THREAD

**Issue by clausmacali** [MicrosoftDocs/dynamics365smb-devitpro-pb#83]
Hi
As a partner i would like have my delevlopment in ISV range and appsource range
how to get their

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98387b95-ce70-594b-b0e1-36ef1b5a6fb6
* Version Independent ID: 8a8d3822-49c4-1422-e046-0d7c9726c9b6
* Content: [Object Ranges - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-object-ranges)
* Content Source: [dev-itpro/developer/devenv-object-ranges.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-object-ranges.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your question. This repo is for documentation issues only. Please reach out to us through the Ready to Go program, more info here: [https://aka.ms/readytogo](https://aka.ms/readytogo).
