### ISSUE TITLE
Not able to download Page 46 Sales Order Subform and Sales Invoice Subform

### ISSUE THREAD

**Issue by ui2607** [MicrosoftDocs/dynamics365smb-devitpro-pb#830]
I am working on BC 13 Onprem where I have been working without any problems. Suddenly I am not able to find page 46 and page 47. I am able to download symbol without any problems. All other objects work fine for now.
I was not able to download symbol if I use "application": "13.0.0.0", so I changed it to "application": "11.0.0.0" and did not experience any issues.
 The app setup is following:

"id": "a7fa6ff1-73f0-4ddd-a30b-81bf6fcc9e85",
  "name": "Extension",
  "publisher": "XXXX",
  "brief": "",
  "description": "Extensions",
  "version": "1.0.0.32",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
    "screenshots": [],
  "platform": "13.0.0.0",
  "application": "11.0.0.0",
  "dependencies": [
  {
    "appId": "ac762be1-e90f-4a72-b519-612a5e3ddc2e",
    "name": "OIOUBL",
    "publisher": "Microsoft",
    "version": "1.0.25940.2"
  } 
  ],
  "showMyCode": true,
  "target":"Internal",
    "idRange": {
    "from": 52000,
    "to": 52999
    },
    "runtime": "2.1"

The launch is following:
 "name": "NAVBC",
            "type": "al",
            "request": "launch",
            "server": "http://localhost:7349",
            "serverInstance": "BC130",
            "authentication":"Windows"

When I try to compile I get this error message 

alesOrderSubform.al(7,39): error AL0118: The name Quantity DM.' does not exist in the current context
error AL0118: The name 'Days DM' does not exist in the current context
error AL0247: The target Page "Sales Order Subform" for the extension object is not found
error AL0118: The name 'Quantity DM.' does not exist in the current context
error AL0118: The name Days DM' does not exist in the current context
error AL0247: The target Page "Sales Invoice Subform" for the extension object is not found

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please use your usual support channel to get help. This repo is used for filing documentation issues. Thanks.
