### ISSUE TITLE
custom fields did not show in AL

### ISSUE THREAD

**Issue by RioArfn** [MicrosoftDocs/dynamics365smb-devitpro-pb#831]
Hi,
I have tried to use this instruction to use custom fields in C/Side in AL. When generating symbols and compiling all objects ends, the command succeeded.
But, when I successfully download the symbol in AL, I can not use my custom fields. I have tried to view the table that contains custom fields, the fields are not there.

Note: I'm using BC version 14.0.35916

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please use your usual support channel to get help. This repo is used for filing documentation issues. Thanks.
