### ISSUE TITLE
<ObjectType>::<ObjectName> not supported for Tables; Table examples

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#832]
About parameter ObjectId: you reommend to declare it "by its name using the syntax &lt;ObjectType&gt;::&lt;ObjectName&gt;" - but this is not supported by object type = Table. For Tables, you have to Write `Database::`

Please also add a complete example for  table OnAfterValidateEvent, such as 
```
    [EventSubscriber(ObjectType::Table, 1802, 'OnAfterValidateEvent', 'Package Imported', false, false)]
    local procedure OnAfterPackageImportedValidate(var Rec: Record "Assisted Company Setup Status"; var xRec: Record "Assisted Company Setup Status"; CurrFieldNo: Integer)
    begin
       
    end;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d70267f-d9d9-ae2f-f8fc-f2abd435bffe
* Version Independent ID: f52b19f8-a064-81e5-35a2-76a406620fa4
* Content: [EventSubscriber Attribute - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-eventsubscriber-attribute)
* Content Source: [dev-itpro/developer/methods/devenv-eventsubscriber-attribute.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods/devenv-eventsubscriber-attribute.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by NKarolak** [comment]
Seems like this one has been overlooked, @SusanneWindfeldPedersen?

Could you also please add the tipp, that since BC 16, you can use [Shift + Alt + E](https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave1/dynamics365-business-central/lookup-events-insert-event-subscriber-code) to easily insert a complete subsriber?

**Comment by blrobl** [comment]
Hi, thanks for your feedback and sorry for the very delayed response. This article has been updated taking into account all your suggestions, and it will be available with the next refresh.
