### ISSUE TITLE
Wrong example for calling API with AAD authentication

### ISSUE THREAD

**Issue by Farzad-Jalali** [MicrosoftDocs/dynamics365smb-devitpro-pb#834]
the current example is useless, the authentication is interactive (popup to get username & password), but in real world , you really want your app to do it seamlessly, for example I like to implement an "Azure Function" to post new items in D365BC API.
you can't have popup dialog for username & password.

The current way of doing it is to use ROPC (OAuth 2.0 ROPC), so your code will do it for you.

Next problem :
Having said that I don't know if it possible or not to have 2 scopes from 2 different places while using ROPC.
he user_impersonation permissions is for the Dynamics 365 Business Central API, while the User.Read is for MS Graph.

 hopefully, I'm wrong, but I think if you are using ROPC then:
You can’t pass scopes for different APIs when getting an access_token. You can only get an access_token, either for Dynamics 365 Business Central or for MS Graph, you can’t request both at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#feedback)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by henrikwh** [comment]
Hi Fazad-Jalali
Currently Business Central only supports Implicit and Auth Code flow.  I dont think that ROPC or Password Grant should be used with 3rd party apps. So for your scenario, I suggest you use Auth Code flow, then use the refresh token to maintain the access token.
Flow and Logic apps, can maintain a connection. So you could use that if needed.

**Comment by SusanneWindfeldPedersen** [comment]
Closing issue.
