### ISSUE TITLE
Step Missing in Business Central Upgrade 2019 wave 2

### ISSUE THREAD

**Issue by git-no** [MicrosoftDocs/dynamics365smb-devitpro-pb#835]
Is Step ```Install-NAVApp``` in Task 9 missing, e.g. between step 2 and 3?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: 5e435e27-0b74-7dcd-555d-977517fd3774
* Version Independent ID: ea922161-12f9-3f86-69f9-2044369d6574
* Content: [Upgrade an unmodified application - Business Central](https://docs.microsoft.com/de-at/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, as long as the old version of the extension was published and installed on the tenant, the Start-NavAppDataUpgrade should automatically install the new version on the tenant.

**Comment by jswymer** [comment]
I hope this answered the question, but if not, feel free to provide more feedback and I will reopen the issue. Thanks!
