### ISSUE TITLE
Problem when using Fields with CaptionClass in the fieldgroup

### ISSUE THREAD

**Issue by supercruel** [MicrosoftDocs/dynamics365smb-devitpro-pb#837]
Hi, there is a Problem when using Fields with CaptionClass in the fieldgroup.

To keep things easy i've created an example that shows the problem. So please don't focus on code details or if the example makes sense.
So basically i have 2 Tables. The first table has an Option and a Code field. The Code Field has defined an Caption Class based on the Option field.
The second Table has the TableRelation to the first Code field with an additional filter on the type field.
The Problem occurs in the fieldgroup-preview from the LookUp. It always shows the CaptionClass from the first Option (see first img)
Select from full list works fine.

![image](https://user-images.githubusercontent.com/24191418/68548312-d4c37a80-03eb-11ea-8b96-3324b83e7924.png)

Select from full list works fine:

![image](https://user-images.githubusercontent.com/24191418/68548315-df7e0f80-03eb-11ea-8383-f0f42d5a0920.png)

Here is the Code for the  example:

table 50000 "NCCA Test"
{
    DataClassification = CustomerContent;
    Caption = 'NCCA Test';
    LookupPageId = "NCCA Test";

    fields
    {
        field(1; Type; Option)
        {
            DataClassification = CustomerContent;
            Caption = 'Type';
            OptionMembers = TestA,TestB;
        }
        field(2; Code; Code[20])
        {
            DataClassification = CustomerContent;
            Caption = 'Code';
            CaptionClass = GetCodeCaption();
        }
    }

    keys
    {
        key(Key1; Type, Code)
        {
        }
    }

    fieldgroups
    {
        fieldgroup(DropDown; Code)
        {
        }
    }

    local procedure GetCodeCaption(): Text
    begin
        exit(Format(Type));
    end;
}

table 50001 "NCCA Test Group"
{
    DataClassification = CustomerContent;
    Caption = 'NCCA Test Group';

    fields
    {
        field(1; "Test Type"; Option)
        {
            DataClassification = CustomerContent;
            Caption = 'Test Type';
            OptionMembers = TestA,TestB;
        }
        field(2; "Test Code"; Code[20])
        {
            DataClassification = CustomerContent;
            Caption = 'Test Code';
            TableRelation = "NCCA Test".Code where(Type = field("Test Type"));
        }
        field(3; Group; Code[20])
        {
            DataClassification = CustomerContent;
            Caption = 'Group';
        }
    }

    keys
    {
        key(Key1; "Test Type", "Test Code", Group)
        {
        }
    }
}

page 50000 "NCCA Test"
{
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = "NCCA Test";
    Caption = 'NCCA Test';
    DelayedInsert = true;

    layout
    {
        area(Content)
        {
            repeater(Group1)
            {
                ShowCaption = false;

                field(Type; Type)
                {
                    ApplicationArea = All;
                }
                field(Code; Code)
                {
                    ApplicationArea = All;
                }
            }
        }
    }
}

page 50001 "NCCA Test Groups"
{
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = "NCCA Test Group";
    Caption = 'NCCA Test Groups';
    DelayedInsert = true;

    layout
    {
        area(Content)
        {
            repeater(Group1)
            {
                ShowCaption = false;

                field("Test Type"; "Test Type")
                {
                    ApplicationArea = All;
                }
                field("Test Code"; "Test Code")
                {
                    ApplicationArea = All;
                }
                field(Group; Group)
                {
                    ApplicationArea = All;
                }
            }
        }
    }
}

thx!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9979b71-a2f9-9032-5bba-161f6da5ff63
* Version Independent ID: 7fd0115f-bfec-43e1-e5c3-69bf2e4d383c
* Content: [Field Groups - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-field-groups#feedback)
* Content Source: [dev-itpro/developer/devenv-field-groups.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-field-groups.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you've reached the repo for documentation issues - judging from your feedback, it seems that this is more of an unexpected behavior? Please use your usual support channel to get help or for filing a product bug. Thanks.
