### ISSUE TITLE
Endpoints?

### ISSUE THREAD

**Issue by BartBourgeois** [MicrosoftDocs/dynamics365smb-devitpro-pb#838]
None of the endpoints in this document seem to match/work.

For retrieving Environments for example, the document states to use:
      GET /admin/v2.0/applications/BusinessCentral/environments
Which results in 404 errors

However, the following Endpoint does to generate the expected result:
     GET /v1.2/admin/applications/BusinessCentral/environments
Full Uri:
     GET https://api.businesscentral.dynamics.com/v1.2/admin/applications/BusinessCentral/environments

What are we missing about the endpoint Urls? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c4240e-3064-4e29-63cf-202b47e86c96
* Version Independent ID: fa3bfa13-4b7b-011c-62a6-1baa9aab4792
* Content: [Business Central Administration Center API - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api)
* Content Source: [dev-itpro/administration/administration-center-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/administration-center-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. I believe there is an update on the way for this topic including this: GET GET /admin/v2.0/applications/environments. The topic will be refreshed asap. Thanks.
