### ISSUE TITLE
Magic token for "al.assemblyProbingPaths" is undocumented

### ISSUE THREAD

**Issue by rdebath** [MicrosoftDocs/dynamics365smb-devitpro-pb#84]
The path required in this list for the standard libraries (except core) is not documented and not obvious. The path added for the default setting is an empty directory (into which I assume third party DLLs are to be dropped).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6350ffb-3e0f-92de-8455-bbf3a316f62e
* Version Independent ID: 96ee3cfc-16c4-ae11-6a69-15e33ae85c1d
* Content: [Getting started with Microsoft .NET Interoperability from AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-call-dotnet-from-al)
* Content Source: [dev-itpro/developer/devenv-get-started-call-dotnet-from-al.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-get-started-call-dotnet-from-al.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi thanks for your feedback, this feature is not yet fully documented and is in preview under the Ready to Go program. We expect to have more information by fall, I will add your feedback to our backlog. Thanks again.
