### ISSUE TITLE
RequestFilterFields mandatory on Web Client to get filter tab displayed

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#840]
It seems that, contrary to running a report in Windows Client filter tabs are not displayed in Web Client if RequestFilterFields is not defined. Could there please be made a note that one needs to define RequestFilterFields to have filter tab(s) on RequestPage on Web Client.

So action for "If you do not want users to add filters on fields, then use one of the following methods" is (partly) a different one for Web Client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aecc14d-10a7-e0a8-d938-e93f0d1feade
* Version Independent ID: 650e453d-8025-1a50-3368-30fb6c0c2503
* Content: [RequestFilterFields Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-requestfilterfields-property)
* Content Source: [dev-itpro/developer/properties/devenv-requestfilterfields-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-requestfilterfields-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-requestfilterfields-property.md - this topic needs to be updated too.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. We've fixed this and it'll be available with the next doc refresh. Thanks again.
