### ISSUE TITLE
AS0055

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#841]
Im getting AS0055 in my compiler right now. AS0048 is the last one in this document.
Please update the documentation to reflect the latest version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03cc1f40-cea7-5449-10a6-9736f9713c53
* Version Independent ID: afcd6e13-c135-08ba-f973-cab671fb579c
* Content: [AppSourceCop Analyzer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by tinfister** [comment]
AS0056 here

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We've just updated the analyzer rulesets including the [appsourcecop](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop).
