### ISSUE TITLE
More Code Example Please

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#842]
I'm trying to find a way to link 2+ tables within a report dataset but the internet is very sparse with examples on how to do this...
I would like to create a report that will be used to print POs but the report should display information from the vendor table as well as the customer table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f03c56-75e1-2026-13be-6ce506022646
* Version Independent ID: c6a06930-0277-2951-b684-6cdb8b5ca57a
* Content: [DataItemLink Property (Reports) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-dataitemlink-reports-property)
* Content Source: [dev-itpro/developer/properties/devenv-dataitemlink-reports-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-dataitemlink-reports-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This is currently on our radar and we're working on an example, which we will hopefully be able to publish soon. Thanks for your patience!

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we have a walkthrough on this subject available [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-walktrough-designing-reports-multiple-tables). Hope this helps. Thanks!
