### ISSUE TITLE
Incomplete profile property list

### ISSUE THREAD

**Issue by pri-kise** [MicrosoftDocs/dynamics365smb-devitpro-pb#844]
The list of the profile properties isn't complete.

There are missing

- Description
- Caption
- RoleCenter
- Customizations

The ML Properties are missing too, but since xliff is the future, that's okay for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20446c43-f374-740f-2539-08af50441519
* Version Independent ID: 642859b6-87ca-8b02-ee31-edc84a5d3f49
* Content: [Profile Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-profile-properties)
* Content Source: [dev-itpro/developer/properties/devenv-profile-properties.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-profile-properties.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback - this topic will be updated with the next doc refresh.
