### ISSUE TITLE
Please add AS0051

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#845]
Please add rule AS0051: The property 'contextSensitiveHelpUrl' must be specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03cc1f40-cea7-5449-10a6-9736f9713c53
* Version Independent ID: afcd6e13-c135-08ba-f973-cab671fb579c
* Content: [AppSourceCop Analyzer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We've just updated the analyzer rulesets including the [appsourcecop](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop).
