### ISSUE TITLE
XMLPort or XMLport

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#846]
In various places in this topic it is written XMLPort, but I guess should be XMLport.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdf995f-2dfb-1be8-c224-f8107fee3f54
* Version Independent ID: 575f952a-9ec8-51c8-aaca-7d8bc7994d49
* Content: [Defining an XMLport schema - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-xmlport-schema)
* Content Source: [dev-itpro/developer/devenv-xmlport-schema.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-xmlport-schema.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **t-blrobl**

**Comment by blrobl** [comment]
Hi, it should indeed be XMLport, thanks for catching it. It will be fixed with the next doc refresh.
