### ISSUE TITLE
Multitenant error on Task 7: Install system application and base 

### ISSUE THREAD

**Issue by ERPgruppenMW** [MicrosoftDocs/dynamics365smb-devitpro-pb#848]
Hi,
I am trying upgrade on multitenant tenant database from NAV 2016 through BC 14.5.
I am just mounting tenant on freshly installed BC 15 Release Wave 2 instance.
In Task 7: Install system application and base application extensions, with this command:
"Install-NAVApp -ServerInstance &lt;instance&gt; -Tenant &lt;tenant&gt; -Name "System Application" -Version '15.0.36560.36649'"
I get error:
"Install-NAVApp : Cannot install apps due to the state of the tenant: OperationalDataUpgradePending"

If I try jump to task 8 and do that before I get error in upgrade:
"State: Failedpending Resume"
"Error: No object found with type Codeunit and Id 2"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e435e27-0b74-7dcd-555d-977517fd3774
* Version Independent ID: ea922161-12f9-3f86-69f9-2044369d6574
* Content: [Upgrade an unmodified application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application#feedback)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,
I could reproduce the same error following the guidelines. The article has been updated with the steps that should work. I recommend that you use the latest update  to be sure (you will find a link in the article). Sorry for the inconvenience. Thanks for the feedback.

**Comment by jswymer** [comment]
I will close this issue for now, but if you have other comments, please feel free to provide them and I will reopen the issue. Thanks!
