### ISSUE TITLE
File.Copy() does not work in BC.

### ISSUE THREAD

**Issue by nareshwar** [MicrosoftDocs/dynamics365smb-devitpro-pb#849]
In BC, instead of using FIle.Copy(), you can just use Copy().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d48d074-3ae5-fa96-5f37-16c0ff9b12dd
* Version Independent ID: 7d0e64d4-de67-7bda-8ee6-96eca4d51a20
* Content: [Copy Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-copy-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/file/file-copy-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/file/file-copy-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. I think this topic has the right notes to explain that it works for on-premises and can be used without specifying the data type. Please elaborate if you disagree. Thanks.
