### ISSUE TITLE
Incorrect display of sample data in the JSON area for test creation

### ISSUE THREAD

**Issue by FSharpCSharp** [MicrosoftDocs/dynamics365smb-devitpro-pb#85]
The following sentence is followed by a code box with sample code for integrating the test toolkit into the extension project.

_Import symbols for the Test framework.
We do this by adding a test setting to the app.json file with the minimum supported value, for example: "test" : "11.0.0.0"._

The text in the box starts as follows:
_Machine generated alternative text:_

However, this example cannot be used because it is gibberish. Something's completely broken. It's not possible to use anything else here. Please correct accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7f2151-4fef-e6ab-bbc1-5b3e1b8c5b17
* Version Independent ID: 20ffa998-58d3-c843-87d5-3533e2fa7765
* Content: [Testing the Advanced Sample Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-advanced-example-test#feedback)
* Content Source: [dev-itpro/developer/devenv-extension-advanced-example-test.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-advanced-example-test.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. You're right - this text was broken unfortunately. The topic is fixed with the next refresh of the docs. The machine generated alternative text looks like this: 

"screenshots": [],
  "platform": "11.0.0.0",
  "application": "11.0.0.0",
  "test": "11.0.0.0",
  "idRange": {
    "from": 50100,
    "to": 50149}

Thanks again!
