### ISSUE TITLE
Are you sure this property still exists?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#850]
MethodType seems not to be available in AL? Isn't is fully replaced with the Method property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baab9371-697c-893f-86fe-a083a633e895
* Version Independent ID: b6a73bb8-3a1d-8c0e-0b97-e089bb62a148
* Content: [MethodType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-methodtype-property)
* Content Source: [dev-itpro/developer/properties/devenv-methodtype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-methodtype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hi,

You are correct. This property does not apply to AL. We have added a note in the article. The update will be published soon. Thanks for the feedback!
