### ISSUE TITLE
Are you sure this is working?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#851]
It does not seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed12fbfa-7725-0dcf-fcc9-f11c775fed61
* Version Independent ID: c85b67e7-9466-f838-92fa-33c2db1d1467
* Content: [TopNumberOfRows Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/query/queryinstance-topnumberofrows-method)
* Content Source: [dev-itpro/developer/methods-auto/query/queryinstance-topnumberofrows-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/query/queryinstance-topnumberofrows-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Can you be more specific? Is it the method or the code example that doesn't seem to work? Thanks.

**Comment by lvanvugt** [comment]
Hi Sussane.

The method seeems not to work when you view the query (run it from web client using ?query= in url. It will always show all records. It dos worl when called from code.

**Comment by SusanneWindfeldPedersen** [comment]
Hi Luc - okay, thanks - we'll look into it. It sounds like a product bug, but I will keep this issue open for now, while we're investigating.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we tested this and it seems to not be working, so we've created a bug for the prod team. Will be closing this doc issue then. Thanks!

**Comment by lvanvugt** [comment]
Great, Susanne. However, could an update be given here once fixed, so I am in the know?

**Comment by SusanneWindfeldPedersen** [comment]
Yes, I can follow up once we know more.

**Comment by SusanneWindfeldPedersen** [comment]
Hello Luc, sorry for the wait. An update on this: using ?query= in the URL in connection with the topnumberofrows method is not working and will not be fixed after all. Please feel free to file an external bug on this. Thanks.

**Comment by lvanvugt** [comment]
OK, that's a pity. Could you atleast share the reasion for not fixing it?

**Comment by SusanneWindfeldPedersen** [comment]
Yes, I agree - I'm sorry for any hassle it brings. The reason is that it is a costly change and that we will rather focus on improving support on queries from the UI.

**Comment by lvanvugt** [comment]
Clear and thanx.
