### ISSUE TITLE
Dokumentation is not up to date

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#852]
In the section/PDF: How do I get my Add-on app published in Microsoft AppSource?
It says that "The Cloud Partner Portal is the place where you first will submit your App for the marketing validation and later submit it for publication. "

However this is no longer true since it has been moved to Partner Center. When you try to create new offer att Cloud Portal you get:
"Dynamics 365 Business Central offers have moved to Partner Center"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960a354e-57d7-bc95-7fcb-71a571076bfe
* Version Independent ID: 70d18c91-586e-ffef-cf32-301c2a5b0929
* Content: [Add-on Apps - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-add-on-apps#feedback)
* Content Source: [dev-itpro/developer/readiness/readiness-add-on-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-add-on-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback - this should be fixed very soon. Thanks!
