### ISSUE TITLE
Application Insights Instrumentation Key

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-devitpro-pb#853]
Could you precise if the Instrumention Key have to be in the same Azure Tenant than the Business Central environment ?
Or if the Instrument Key can be in another Azure Tenant ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5110b5f-fbc7-66de-b57b-3c4a3adc7ff4
* Version Independent ID: 24a63a6f-3667-faa1-dbb9-4c8ba42b4bf1
* Content: [Environment Telemetry - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-telemetry#feedback)
* Content Source: [dev-itpro/administration/tenant-admin-center-telemetry.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/tenant-admin-center-telemetry.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by jaredha** [comment]
Good question. The Application Insights key can be in any Azure Tenant. We expect that partners may need to be the one analyzing the telemetry, and may not have access to the customer's Azure instance. This scenario enables the partner to send the telemetry to her own Application Insights instance.

**Comment by edupont04** [comment]
We'll get this clarification added to the Help in a few days.
