### ISSUE TITLE
Task 7 - Missing Publish System Application Extension

### ISSUE THREAD

**Issue by eivindgiske** [MicrosoftDocs/dynamics365smb-devitpro-pb#858]
Theres is a missing publish step. Publish-NavApp Microsoft_System Application.app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1d264c-efcd-b879-76d8-84966207ff17
* Version Independent ID: 5e5d562b-caad-3e0e-6cb8-064fd323519d
* Content: [Technical Upgrade - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15)
* Content Source: [dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The scenario described in the article does not use the System Application extension, so you do not have to publish it. In this scenario, the custom base application that you  convert to AL still includes the "system application objects", so to speak. I would be interested in hearing a bit more about your scenario, so I can better answer this. Thanks!

**Comment by jswymer** [comment]
Hello, I hope the answer helps to clear things up. I will close this issue for now, but if you have more comments, please feel free to provide them and I will reopen the issue. Thanks!
