### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DavidRoys** [MicrosoftDocs/dynamics365smb-devitpro-pb#859]
depneding 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05ac89ef-8c34-7d8e-f8db-9f66b32609a4
* Version Independent ID: 20692e88-8f1f-a98f-055a-7da5998e7582
* Content: [Upgrading to Microsoft Dynamics 365 Business Central On-Premises - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-to-business-central-on-premises)
* Content Source: [dev-itpro/upgrade/upgrading-to-business-central-on-premises.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-to-business-central-on-premises.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The typo has been fixed and the updated article will be published soon.
