### ISSUE TITLE
bracket is missing

### ISSUE THREAD

**Issue by Bhawan-Bhangu** [MicrosoftDocs/dynamics365smb-devitpro-pb#86]
This is a typing error on this page.  See this line:- 
Data is entered in a field or when the VALIDATE Record) is executed. 
Here round bracket is closed but not opened. Can you please fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8a0a4d-a5ee-0e97-fb86-838f5aea4394
* Version Independent ID: cbefe940-1d8e-5340-f733-4c701db41f68
* Content: [Table and Field Triggers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-table-and-field-triggers)
* Content Source: [dev-itpro/developer/triggers/devenv-table-and-field-triggers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-table-and-field-triggers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Nice catch. Thanks for the feedback. This is fixed in the next refresh of the docs.
