### ISSUE TITLE
Caption on table extension or page extension

### ISSUE THREAD

**Issue by RaKuNbg** [MicrosoftDocs/dynamics365smb-devitpro-pb#860]
In the code example above the property 
Caption = 'ShoeSize'; 
is defined for the page extension instead of the table extension.
I would have expected (as used from the c/side development environment) that the caption is defined on the table extension and the page extension would inherit it, as long as there is nothing else defined in the page extension.
==&gt; Is that an error here in the documentation or is in done on purpose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdda7e30-30d9-ac83-abf7-267a7f634c6d
* Version Independent ID: 5bf5ce87-f59a-d2ae-10b3-05eda02406b5
* Content: [Page Extension Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object#feedback)
* Content Source: [dev-itpro/developer/devenv-page-ext-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-ext-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by thpeder** [comment]
Hi @RaKuNbg, 
That is correct, if the page doesn't specify a caption and if you don't have other translations for the page control then it will take the caption of the table field.
It is not an error, it is more a matter of how you like to write the code.

**Comment by RaKuNbg** [comment]
Hi @thpeder,
but in my opinion the default (Style Guide) should be that the caption is defined in table(-extension) and so the code example in the documentation should be changed to make it clear for new developers.

Image a new field added e.g. as an extension to table Sales Header, that should be shown on all list pages and document pages for the sales documents.
If the caption is set in page exension, there are at least 10 pages where the caption must be added.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. The topic will be fixed with the next refresh of the docs. Thanks.
