### ISSUE TITLE
collation error

### ISSUE THREAD

**Issue by wic365** [MicrosoftDocs/dynamics365smb-devitpro-pb#862]
Hi, 
My BC On-Prem has a windows collation, and running snchronization, I get an error claiming collations are different.
On-Prem I've the "Latin1_General100_CS_AS" which seems not compatible with the SQL_Latin1_General_CP1_CI_AS  for BC365. 
If I convert my local collation to SQL_Latin, I can start the NST because it's not supported. Any idea?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bffc19c-cc0a-fec5-b46b-16e58b034c19
* Version Independent ID: 0a79027a-c75c-f003-1c89-b0b64d4510de
* Content: [Frequently Asked Questions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/faq-intelligent-cloud#feedback)
* Content Source: [dev-itpro/administration/FAQ-Intelligent-Cloud.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/FAQ-Intelligent-Cloud.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by jswymer** [comment]
Hello, 

Thanks for the feedback. SQL collations, like SQL_Latin1_General_CP1_CI_AS, are not supported on-premise. I am not sure why the BC365 Online collation is set to SQL_Latin1_General_CP1_CI_AS, but perhaps I do not fully understand the scenario. The support channel might be the best way to get an answer to this question.

**Comment by jswymer** [comment]
Hello,  I hope this has answered your question or got you in touch with someone who could help. I will close this issue for now, but if you have additonal information about this, feel free to provide comments and we will reopen the issue as needed.
