### ISSUE TITLE
New and deprecated options for "Allowed Extension Target Level"

### ISSUE THREAD

**Issue by Kowa63** [MicrosoftDocs/dynamics365smb-devitpro-pb#864]
The options "Cloud" and "OnPrem" for "Allowed Extension Target Level" are available in BC 15, but not in older versions. Which versions e.g. in 14.x do actually support these new options that were introduced lately? That is not mentioned.
![grafik](https://user-images.githubusercontent.com/16236672/69145004-eaf8c700-0acc-11ea-8d39-01717839830e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30dd402-c112-00be-9c66-4f8bd6a2184f
* Version Independent ID: 215be880-512c-a76b-5463-bfd1b349dd81
* Content: [Microsoft Dynamics 365 Business Central Server Configuration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-server-instance#Development)
* Content Source: [dev-itpro/administration/configure-server-instance.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configure-server-instance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The Cloud and OnPrem options were introduced in version 15 and are not supported in previous versions. Thanks.
