### ISSUE TITLE
Incorrect example to call back from javascript.

### ISSUE THREAD

**Issue by alemarius** [MicrosoftDocs/dynamics365smb-devitpro-pb#867]
changes in documentation: 
 // In main.js code, there should be a global 
    function CallJavaScript(i,s,d,c) {
        Microsoft.Dynamics.NAV.InvokeExtensibilityMethod('CallBack', [i, s, d, c])
    }
othervise this function calls does nothing. This change in documentation would have solved me A LOT of time investigating, ty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237ce502-edd7-65fb-de3a-8bd4d044a9b7
* Version Independent ID: 6a1f466c-97f8-b5f5-2b99-bc0ee81ffc4c
* Content: [Control Addin Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-control-addin-object)
* Content Source: [dev-itpro/developer/devenv-control-addin-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-control-addin-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This has been included in the documentation and will be available with the next doc refresh. Sorry for the inconvenience.
