### ISSUE TITLE
When must we Uninstall previous version and do we need to stop BC server instances at some point?

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#869]
There is section "Install Business Central components of the update" but don't we have to Uninstall previous version of BC right before that? If so, please add this.

Also this instruction is for installing cumulative updates meaning we already have Database and therefore I would like to see instructions how to install BC so that current database remains untouched during install and so that no SQL Express is installed (especially when SQL Standard already is installed).

And do we need to stop BC server instances at any point or is that all handled automatically?

I managed to upgrade using this instruction but had huge headache with installation of "SQL Server Components". 
Solution was to NOT enter SQL Database name "Demo Database BC (15-0)" in Specify parameters page although i had not selected to install Demo database.

Since we have "Connect the server instance to connect to the database." there must be section where we remove Database name from BC service instance ... and how to achieve that? If solution is NOT enter SQL Database name in Specify parameters then please add this to instruction.

Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71477e4-f2ea-1481-7597-29b324bd4f57
* Version Independent ID: a2bb3a05-e5c1-d9f7-f47f-d2f34c4a91ea
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15#synchronize-the-tenant)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,
Thanks for the feedback. The instructions were not sufficient, sorry. 

When you install using setup.exe, you must first uninstall the current version. Then, when you run setup.exe again, choose the **Custom** option, and choose to install the **SQL Server components** and the **Demo Database**. However, on the **Specify parameters** page, set the  **SQL Database** to a name other than your database. The reason for this is that to install the BC Server using setup.exe, it must connect to database that is compatible with the new platform. So you cannot connect to the old database until it is converted. Once installed, you can convert your old database and then connect it to the server instance. 

We have updated the article. I hope this helps.

**Comment by erolkunman** [comment]
> install the SQL Server components and the Demo Database.
I find that hard to believe.
In that case selecting demo database as an option should not be allowed.

>reason for this is that to install the BC Server using setup.exe, it must connect to database that is compatible with the new platform
I installed in one of my tests without Demo Database, leaving blank Demo Database name and all installed correctly.

**Comment by jswymer** [comment]
Hello,

You are correct. If you leave the SQL Database field empty during setup, you will be able to install the server instance without installing the demo database.

**Comment by jswymer** [comment]
Hello, the article has been updated to hopefully make things more clear. We will close the issue for now, but if you have more comments, feel free ro provide them and we will reopen the issue. Thanks!
