### ISSUE TITLE
purchaseInvoices in URLs

### ISSUE THREAD

**Issue by dcenic** [MicrosoftDocs/dynamics365smb-devitpro-pb#87]
Please use purchaseInvoices({invoiceid}) instead of purchaseinvoice({invoiceid}) in all URLs.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6951bc4a-152d-533e-a5af-e1694e7460fb
* Version Independent ID: f8e70ff6-d125-90fb-f042-022dd75516fb
* Content: [Post purchase invoices - Dynamics NAV](https://review.docs.microsoft.com/en-gb/dynamics-nav/fin-graph/api/dynamics_purchaseinvoice_post?branch=Update17#feedback)
* Content Source: [dynamics-nav/fin-graph/api/dynamics_purchaseinvoice_post.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/Update17/dynamics-nav/fin-graph/api/dynamics_purchaseinvoice_post.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
fixed
