### ISSUE TITLE
Example of making field visible for test

### ISSUE THREAD

**Issue by AmandaTest** [MicrosoftDocs/dynamics365smb-devitpro-pb#871]
We need an example of making a field visible on a test page in order to complete a test scenario. In some situations the field is not shown by default and customers personalize the page.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for input #870 and this one. When providing feedback on documentation, we'd appreciate if you keep the information in the feedback item about the topic that you're coming from. This is part of the template when you open an issue. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
We have improving report documentation on our backlog and will hopefully soon be able to provide some content. Closing this issue. Thanks.
