### ISSUE TITLE
"Production services" - what does it mean?

### ISSUE THREAD

**Issue by KSH-audibene** [MicrosoftDocs/dynamics365smb-devitpro-pb#872]
Could you maybe provide an example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 259bfcfa-ad5b-a264-9400-193459f34bad
* Version Independent ID: e61ee3e5-f778-ed02-869d-fe8a03b1b06d
* Content: [Choosing Your Dynamics 365 Business Central Development Sandbox Environment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sandbox-overview#feedback)
* Content Source: [dev-itpro/developer/devenv-sandbox-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-sandbox-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, production services are services that use Microsoft accounts, such as Yodlee, and therefore cannot be used in Docker scenarios. Thanks.
