### ISSUE TITLE
Notification Recipients / powershell

### ISSUE THREAD

**Issue by jnpatrouillault** [MicrosoftDocs/dynamics365smb-devitpro-pb#873]
Hello
Is there a cmdlet for checking or updating the notification recipients stored if the admin center of Business Central ? (@ https://businesscentral.dynamics.com/xxxxxxxxxx/admin)
If not I will open a new idea.

Thank you for your help
best regards

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2082993f-bc69-4992-1b99-276a4c20a055
* Version Independent ID: 0bb64a14-6711-663b-9381-1684fb492927
* Content: [Managing Tenant Notifications - Business Central](https://docs.microsoft.com/fr-fr/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-notifications)
* Content Source: [dev-itpro/administration/tenant-admin-center-notifications.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/tenant-admin-center-notifications.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by chrishdmicrosoftcom** [comment]
Hi!

There is a REST API that you can call. It is documented here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-center-api#get-notification-recipients.

E.g., to get the list of notification recipients, you need to make a request to
  https://api.businesscentral.dynamics.com/admin/v2.0/settings/notification/recipients

/Christian

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue. Thanks.
