### ISSUE TITLE
CompanyName parameter

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#875]
The description says: "Specifies the name of the company that you want to run the codeunit in. If you do not set this parameter, the codeunit will run in the default company for the Business Central Server instance."
But when I do setup a default company on the NST calling Invoke-NAVCodeunit keeps on saying: "You must choose a company before you can access the "CAL Test Suite" table."

Am I doing something wrong or is the description wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 113c2baa-a212-ae0e-41c3-37bee091a322
* Version Independent ID: dbaa42c1-9740-f8a6-c515-b0402c06339b
* Content: [Invoke-NAVCodeunit (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/invoke-navcodeunit?view=businesscentral-ps-15)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Invoke-NAVCodeunit.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Invoke-NAVCodeunit.md)

**Comment by jswymer** [comment]
Hello, thanks for the feedback!

Strange. I just tried this on BC 19, for example, by invoking codeunit 2. First, without setting the **Services Default Company**. In this case I got an error similar to yours. Then, I set the **Services Default Company**, restarted the server instance, and it worked. I haven't tried on 15 yet.

**Comment by jswymer** [comment]
Hello, I've checked with the dev team, and this should be working as documented. If you are experiencing problems, they recommend to contact support to get traction on this. Thanks,
