### ISSUE TITLE
Newline not working in Dialog.Message

### ISSUE THREAD

**Issue by fommo** [MicrosoftDocs/dynamics365smb-devitpro-pb#877]
The information for Dialog.Message has been obsolete for quite some time. TextConst should be replaced by Labels.
Also, the example will not give this result in the printout. Using \ does not work in Business Central (I have tried all versions R13 - R15) and even if it did it would not give this result as there is no \ after Text000.
Please update this and let us know how do get newline working in BC.
Kind regards /Simon
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: febf221e-8516-290d-b39c-94f8aaacd0ca
* Version Independent ID: d2bd766f-40b3-0d01-40cf-6b63d1314d0a
* Content: [Message Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-message-method)
* Content Source: [dev-itpro/developer/methods-auto/dialog/dialog-message-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/dialog/dialog-message-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. Yes, it should be using the Label data type instead. This will be fixed with the next doc refresh. You should be able to use the backslash for newline. The following code:
...
begin
        Message('App published: Hello world');

        Text := 'ABCDE';
        Number := 12345.678;

        // The backslash indicates a new line.  
        // You can concatenate strings using the + operator.  
        // You can insert variable values using the % symbol.  
        MESSAGE(Text000 + Text001 + '%1\' + Text002 + '%2\', Number, Text);
    end;


    var
        Text: Text;
        Number: Decimal;
        Text000: Label 'You can use message windows to display text and numbers: \';
        Text001: Label 'The number: ';
        Text002: Label 'The text: ';
....
prints a message like this:

You can use message windows to display text and numbers:
The number: 12,345.678
The text: ABCDE

**Comment by PaulFurlet** [comment]
This does not work for Web Client. Given code example will print:
You can use message windows to display text and numbers: The number: 12,345.678 The text: ABCDE

Is this something to be changed within foreseen future?
