### ISSUE TITLE
(typo) nun-blocking numbering

### ISSUE THREAD

**Issue by achim-t** [MicrosoftDocs/dynamics365smb-devitpro-pb#878]
Please don't block nuns :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2d764fe-ffa6-17e6-a5db-3a9089a10b66
* Version Independent ID: 986e0cf4-24aa-cd21-78ba-12875794b406
* Content: [Number Sequences - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-number-sequences)
* Content Source: [dev-itpro/developer/devenv-number-sequences.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-number-sequences.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Oops, thanks for the feedback! This has been fixed.
