### ISSUE TITLE
Database Conversion fails

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#879]
I tried again to upgrade ... multiple times with different 15-0. databases. Every time when I run:
Invoke-NAVApplicationDatabaseConversion -DatabaseServer &lt;database server name&gt;\&lt;database server instance&gt; -DatabaseName "&lt;database name&gt;"
I get error:
A technical upgrade of database 'Demo15-0' on server 'MINION\BCDEMO' cannot be run, because the database’s application version '130580' is greater than or equal to the platform version '130580'.

So there must be some step missing in this instruction.

Steps to repeat this issue:
Install BC 15.0 (RTM) W1.  Then download BC15.1 and follow this update instruction.
I'm using NavAdminTool.ps1 from BC CU1 installer folder:
Import-Module "$BCinstallerPath\ServiceTier\program files\Microsoft Dynamics NAV\150\Service\NavAdminTool.ps1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71477e4-f2ea-1481-7597-29b324bd4f57
* Version Independent ID: a2bb3a05-e5c1-d9f7-f47f-d2f34c4a91ea
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15#feedback)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. Sorry, but I cannot reproduce this error but perhaps, I am doing something slightly different than you. I have only seen this error when the database was already on the target platform, for example, I'd run the cmdlet twice or I inadvertently targeted a 15.1 database.

**Comment by erolkunman** [comment]
My PS sctipt for updating (I run variables as combination and other commands row by row):
`# VARIABLES
    $DataBaseServerName = "MINION"
    $DataBaseServerInstance = "BCDEMO"
    $DataBaseName = "Demo15-0"
    $servInst = "BC150"
    $BCinstallerPath = "C:\Install\BC.15.1.38071.W1.DVD"

# Commands
Import-Module "$BCinstallerPath\ServiceTier\program files\Microsoft Dynamics NAV\150\Service\NavAdminTool.ps1"

    Get-NAVAppInfo -ServerInstance $servInst -Tenant Default| % { Uninstall-NAVApp -ServerInstance $servInst -Name $_.Name -Version $_.Version -Force}

    Stop-NAVServerInstance -ServerInstance $servInst

    & cmd.exe /c "$BCinstallerPath\setup.exe" /uninstall

    & cmd.exe /c "$BCinstallerPath\setup.exe"

    Invoke-NAVApplicationDatabaseConversion -DatabaseServer $DataBaseServerName\$DataBaseServerInstance -DatabaseName $DataBaseName`

And then I get the error:
A technical upgrade of database 'Demo15-0' on server 'MINION\BCDEMO' cannot be run, because the database’s application version '130580' is greater than or equal to the platform version '130580'.

I did manage to upgrade on 2 different times. But failed with about 5 databases I tested on.

**Comment by jswymer** [comment]
Hello, I tried this using a similar script and did not have any problems. In your steps, what happens if, before you convert the Demo15-0 datbase, you try to connect it to the BC15.1 server instance and start the instance? You should get an error.

**Comment by erolkunman** [comment]
Yes, I get:
BC150 is not starting because “The database on the server must be converted..”

**Comment by jswymer** [comment]
Cool. Then, what happens when you run Invoke-NAVApplicationDatabaseConversion -DatabaseServer MINION\BCDEMO -DatabaseName "Demo15-0"? Do you get the error?

**Comment by salmosa1** [comment]
You are having this error because you have to update the dll's after install Nav. I mean, you have to restart powershell, after install Nav, and then, launch the Invoke. I don't know if you can "re-import" module to have new dll's

**Comment by erolkunman** [comment]
>you have to restart powershell, after install Nav, and then, launch the Invoke.

Thanks, That worked.
