### ISSUE TITLE
Add instructions how to create BC database in BC 15

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#880]
Please make step-by-step instruction on how to create BC 15 database.
In ideal situation we install BC without Demo database and create new clean database (via PowerShell) only with System and Base app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47148bfa-24f7-2e0b-422a-35e368643d8a
* Version Independent ID: cfb618d7-4de4-232e-6b7a-682d38c38578
* Content: [Creating and Altering Business Central Databases - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/cside/cside-create-databases)
* Content Source: [dev-itpro/cside/cside-create-databases.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/cside/cside-create-databases.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by shereen-yong** [comment]
Yes, agree, I also require this i.e. instructions for BC 15.

**Comment by jswymer** [comment]
Hi, thanks for the feedback. There will be an article soon, byt until then here are the basic instructions:

To create an application database, for either a single-tenant or multitenant deployment, you use the [New-NAVApplicationDatabase cmdlet](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/new-navapplicationdatabase). This cmdlet is available in the [!INCLUDE[adminshell](../developer/includes/adminshell.md)].

1. Run the [!INCLUDE[adminshell](../developer/includes/adminshell.md)] as an administrator.
2. Run the [New-NAVApplicationDatabase cmdlet](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/new-navapplicationdatabase) to create a new database.

    ```powershell
    New-NAVApplicationDatabase [-DatabaseServer <database server name>\<database server instance>] -DatabaseName <String> [-DatabaseLocation <String>] [[-Collation] <String>] [-ApplicationDatabaseCredentials <PSCredential>]
    ```
    For example, the following command creates the database called MyBCApplicationDB with the collation Latin1_General_100_CS_AS on the SQL Server instance BCDEMO.

    ```powershell
    New-NAVApplicationDatabase -DatabaseServer .\BCDEMO -DatabaseName "MyBCApplicationDB"
    ```

    When the database has been successfully created, text similar to the following displays:
    ```powershell
    DatabaseServer      : .\BCDEMO
    DatabaseName        : MyBCApplicationDB
    DatabaseCredentials :
    DatabaseLocation    :
    Collation           : Latin1_General_100_CS_AS
    ```powershell
3. Connect [!INCLUDE[server](../developer/includes/server.md)] instance to the new database.

    For example:
    ```powershell
    Set-NAVServerConfiguration BC150 -KeyName DatabaseName -KeyValue "MyBCApplicationDB"
    ```
4. Run the [Set-NAVApplication cmdlet](powershell/module/microsoft.dynamics.nav.management/set-navapplication) to set the application version on the database.

    To set the application version, use the `-ApplicationVersion` parameter. The value must have the format `major.minor.[build[.revision]]`, such as '15.1', '15.1.0., or 15.1.0.0'. For example:
    
    ```powershell
    Set-NAVApplication BC150 -ApplicationVersion 15.1.0.0 -Force
    ```

    This is required in order to synchronize your tenant and extensions later. This step sets a value to the `applicationversion` column in the **$ndo$dbproperty** table of the application database.

5. Grant the [!INCLUDE[server](../developer/includes/server.md)] service account [permission](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/provision-server-account#dbo) to the database.

6. Run the [Sync-NAVTenant](https://docs.microsoft.com/powershell/module/microsoft.dynamics.nav.management/sync-navtenant) cmdlet to synchronize the tenant.

    ```powershell
    Sync-NAVTenant -ServerInstance BC150
    ```

**Comment by jswymer** [comment]
Hello,

We have created the article [Creating Databases](https://docs.microsoft.com/dynamics365/business-central/dev-itpro/deployment/devenv-create-databases) to cover BC 15. Thanks for the feedback!

**Comment by shereen-yong** [comment]
Great, will check it out, thanks.
