### ISSUE TITLE
Codeunit::TextManagement should be changed to Codeunit::"Filter Tokens"

### ISSUE THREAD

**Issue by tinfister** [MicrosoftDocs/dynamics365smb-devitpro-pb#881]
title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8ca63e-19c6-5ecc-e195-c65cd67f5931
* Version Independent ID: 18a89028-7ce4-51f1-0d1a-b119dd2303de
* Content: [Adding custom filter tokens - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-filter-tokens)
* Content Source: [dev-itpro/developer/devenv-adding-filter-tokens.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-filter-tokens.md)
* Service: **dynamics365-business-central**
* GitHub Login: @mikebcMSFT
* Microsoft Alias: **solsen**

**Comment by tinfister** [comment]
OnAfterMakeTextFilter should be changed also to OnResolveTextFilterToken

**Comment by jswymer** [comment]
Thanks for the feedback! the article has been updated.
