### ISSUE TITLE
should not => cannot

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#882]
Most of these rules say "should not" while they are really "cannot". I cannot rename a field, delete a table, modify the field type, etc. All of these are a hard no.

"Should not" is a strong recommendation. "Cannot" is a hard no.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03cc1f40-cea7-5449-10a6-9736f9713c53
* Version Independent ID: afcd6e13-c135-08ba-f973-cab671fb579c
* Content: [AppSourceCop Analyzer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I agree that the wording of mandatory rules must be phrased more precisely. We have the rules on our radar, in the backlog to go through wording like this among other things. I will close this issue and we will hopefully be able to get to fixing this soon. Thanks.
