### ISSUE TITLE
Error at starting web client

### ISSUE THREAD

**Issue by salmosa1** [MicrosoftDocs/dynamics365smb-devitpro-pb#883]
We have upgrade to CU 1 our Nav, and after do all steps, the nav instance starts, but when I try to start Web Client, it doesn't do anything. It stays on the first screen with dots infinetly.
I've seen the Event Log, and the NavClientWebClient throws the error:

Connection id "0HLRIK8LTHHRG", Request id "0HLRIK8LTHHRG:00000008": An unhandled exception was thrown by the application.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.Dynamics.Nav.Types.InvalidHomepageException: The metadata object Page 0 was not found. ---> Microsoft.Dynamics.Nav.Types.InvalidHomepageException: The metadata object Page 0 was not found.

I've synced (Sync-NavTentant) several times, but it does nothing.

What should I do? What did I miss?

Thanks!

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you've reached the documentation repo for Business Central. Please use your usual support channel for help with this. Thanks.

**Comment by salmosa1** [comment]
I post this theme from Business Central Repo, so, if it's not the channel, you have something wrong, because you redirect to the wrong site.
Anyway, thanks, I've solved it my way

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I am glad you solved it. When opening issues on the [Business Central Developer docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/?branch=master) you can choose doc feedback or product feedback. If you choose doc feedback, you get to this repo and attached is information about the topic that you're giving feedback on. This issue doesn't contain that information and is product-related. Please let me know if you reached this repo in a different way, then I will investigate. Thanks!

![image](https://user-images.githubusercontent.com/12556556/69710154-20ba3300-10ff-11ea-80af-6eb288d66466.png)
