### ISSUE TITLE
Debugging the extension publishing process BC150

### ISSUE THREAD

**Issue by krregg** [MicrosoftDocs/dynamics365smb-devitpro-pb#884]
I have a situation with a custom extension that worked perfectly on `Business Central 14 CU6`. 
Now when I try to run `Sync-NAVApp` (after publishing it) for my custom extension I get first this error:

`-> Sync-NAVApp : Object reference not set to an instance of an object.`

If I try to run `Sync-NAVApp` once again I get another error:

`-> Sync-NAVApp : An item with the same key has already been added.`

I assume there is a problem with the code when installing the extension. Regarding that, I disabled all install codeunits because I thought there is maybe a problem with them, but unfortunately, that's not true. I still can't find anything that could cause trowing me above errors. 

When I try to publish an extension from VSC I always get error `Object reference not set to an instance of an object.`

I checked Event Viewer and there is something but totally unreadable. The Exception Stack Trace doesn't contain any useful information that would lead me somewhere. 

Cloud be any issue with enums, I have to check that...

My question: is there any tool or way that could help me debug the publish-sync-install process? I would like to find where the code breaks when I press F5 in VSC.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you've reached the documentation repo for Business Central. Please use your usual support channel for help with this. Thanks.
