### ISSUE TITLE
Edit a Setup configuration file

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/dynamics365smb-devitpro-pb#886]
It would be great if it was possible to find a bit more information about the different options in the setup configuration.xml file, when using the /CONFIG: setup option. Not just what the file properties mean. 
We have been using this option, but after the upgrade to v15, then it seems some of the options used with v14 are no longer supported. Some are obvious, others are not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f446fc6-3475-7b86-3ba3-a0bdaebf80e8
* Version Independent ID: 722a12dd-e281-ee5b-96ec-581d94166274
* Content: [Install Business Central Using Setup - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/install-using-setup?source=docs#feedback)
* Content Source: [dev-itpro/deployment/install-using-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/install-using-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by shereen-yong** [comment]
Agreed, I am also having problems with installing V15 running this setup process. It said somewhere that if existing older versions exist, there will be an error installing the latest version V15? (Need to verify if this is true?)
and 

The error seems to occur when attempting to install the server instance of BC
When I look in the error logs during installation in the event viewer, there is a log:
"Service MicrosoftDynamicsNavServer$BC150
System.ServiceModel.AddressAlreadyInUseException"
I am unsure if this means that during installation of the server component the port number is being used already so I have to manually specify another port?? or if it means something else... 
I have tried repair - with the same error and additional SQL server DB already exists conflict error (which I am guessing is because I already attempted to install once without success)
So I have now run uninstall and restarted. However I can still see in Program Files the installation of BC... quite confused here

**Comment by jswymer** [comment]
Hi, thanks for the feedback. I will try to answer the questions.

1. The elements in BC 14 xml that are no longer used in BC 15 include:
<Component ShowOptionNode="yes" State="Local" Id="RoleTailoredClient"/>
<Component ShowOptionNode="yes" State="Local" Id="ExcelAddin"/>
<Component ShowOptionNode="yes" State="Local" Id="ClassicClient"/>
<Component ShowOptionNode="yes" State="Absent" Id="ClickOnceInstallerTools"/>
<Component ShowOptionNode="yes" State="Absent" Id="STOutlookIntegration"/>
<Parameter Id="PublicWinBaseUrl" Value=""/>
<Parameter Id="ACSUri" Value=""/>
These feature have been deprecated. However, I have been able to use a BC14 xml that includes these elements to install BC 15 without errors. 

2. The error "Service MicrosoftDynamicsNavServer$BC150 Sstem.ServiceModel.AddressAlreadyInUseException" typically occurs if a port is already in use. For example, if a BC 14 server instance is running and you try to install BC 15 using the same ports, you will get this error.

**Comment by epernst** [comment]
Thanks. That's exactly what I guessed it was and it's actually the <Component ShowOptionNode="yes" State="Local" Id="RoleTailoredClient"/> I'm concerned about. I removed this option (and the others above) from our previously, but then our DevOps builds scripts would not run. Adding RoleTailoredClient back and it worked again.

**Comment by shereen-yong** [comment]
Hello thanks for your response.

In attempt to solve the conflicts I have fully uninstalled all instances of BC (v14 and 15) and deleted the app as well (for PC downloaded from Microsoft store), then re-ran setup an chose the “install demo” option. Doing so, I could see BC15 server installed and running. No conflicts yet. Then I went to Microsoft store to install the BC app. I assume this is the “client”? (Sorry NAV/ BC365 is brand new to me – and we are a partner but there is no one here to assist so I am sort of fumbling around in the dark here trying to understand deployment, the architecture of BC15 etc). The BC app asked me to either:

  1.  Enter work or school email address to connect to my data in the cloud OR
  2.  “Learn about BC an get a trial” -> this takes me to a my internet browser where I can login with my office credentials and see “My apps” and add more from Appsource
  3.  Connect to a local or hosted service

I tried option 1 with my work office credentials it said “Microsoft User does not exist”
I am actually trying to setup and deploy an on-premise version of V15 here. Does this mean I should choose option 3? If yes (and click next) , what should I enter where it asks for “Service name”?  - Do I need to do something else before this step like set up some new user for BC 365 or … ?

Sorry if these questions sound confusing or silly but I feel totally confused as to the structure and what is what right now. Please help!
Thanks so much

**Comment by jswymer** [comment]
Hello Shereen-yong,

No worries, it can be a bit confusing. You can see an overview of the architecture here: [Deploying Business Central in a Single-Computer Topology](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/deploy-single-computer-environment)

To see which components are installed with the Demo option, see [Deploying the Business Central Demonstration Environment](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/deploy-demonstration-environment#components]. With the Demo installation, even without installing the Business Central App from the store, you should have access to application by using the Web client. There should be a desktop shortcut on the installation computer called Business Central Web Client. If not open a browser and enter http://localhost:8080/BC150 in the address.

**Comment by jswymer** [comment]
Hello, the article has been updated to address these issues. The updated article will be published soon. If you have more feedback, let us know and we will reopen this issue. Thanks!

**Comment by shereen-yong** [comment]
Thank you for your assistance and for the update!
