### ISSUE TITLE
Please specify that this only works with V15+ of Business Central.

### ISSUE THREAD

**Issue by o365guru** [MicrosoftDocs/dynamics365smb-devitpro-pb#887]
We just tried to create a backup due to extension errors in Production which is on V14 and found out at the end that this is only available for V15 and above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96cf996c-8032-c6aa-4b0c-54eefff3ec8a
* Version Independent ID: 8a08c2ab-3bc7-6f43-a87c-08ac3f779132
* Content: [Exporting Databases - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-database-export#feedback)
* Content Source: [dev-itpro/administration/tenant-admin-center-database-export.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/tenant-admin-center-database-export.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! We have added a note to the article. The update will be published soon.
