### ISSUE TITLE
MyNotes no longer supported?

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#888]
Can you please elaborate on the MyNotes usage? In RTC, this used to show 'Notes assigned to my user' in the rolecenter pages. Seems like in the webclient this is no longer supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c192126f-6103-4039-9555-ef914039dc86
* Version Independent ID: 84caee29-f5e0-589f-f3d3-2efb5bedbd8d
* Content: [SystemPartID Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-systempartid-property)
* Content Source: [dev-itpro/developer/properties/devenv-systempartid-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-systempartid-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback. MyNotes is not supported on the web client. We will update the article to make this clear. Sorry for the confusion.

**Comment by jswymer** [comment]
Hello, the article has been updated. I will close this issue, but please feel free to provide more feedback as you like, and I will reopen the issue as needed. Thanks again.

**Comment by gatsby011** [comment]
Is there any replacement for this?  We have a client that uses it quite a bit.
