### ISSUE TITLE
Correlation between translation file and name in app.json

### ISSUE THREAD

**Issue by TheDenSter** [MicrosoftDocs/dynamics365smb-devitpro-pb#889]
This page mentions that there is 'no enforced naming' but my observations say otherwise. See my reported issue in the AL repo https://github.com/microsoft/AL/issues/5485. I've found that there does seem to be a correlation between the name property in app.json and the name of the xlf files, at least when I create a new workspace for a modified Base Application.

Publishing the app from VSCode only works for me if I make sure that the translation files have the same name as the name in app.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this issue is currently being addressed in https://github.com/microsoft/AL/issues/5485#issuecomment-559439349.

**Comment by SusanneWindfeldPedersen** [comment]
This seems to have been fixed in the NavContainerHelper now. Closing this issue.

**Comment by TheDenSter** [comment]
well the Doc says there is no naming enforcement, but there does seem to be because it only lets me create the package when the translation file name matches the name property in app.json.
