### ISSUE TITLE
URL points to Danish site

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#89]
The "How To:" link under "See also" in the bottom points to the Danish site instead of the users preference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback and good catch. This is fixed in the next refresh of the docs.
