### ISSUE TITLE
Are You sure SQL Server Components are always needed during BC install?

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#891]
&gt;On the Customize the installation page, select the following components as a minimum:
&gt;AL Development Environment (optional but recommended); Server; SQL Server Components; Web Server Components.

I just did Update from 15.0 to 15.1 in customer environment without installing SQL Server Components.
Customer has SQL database along with SQL Standard in another server.

If I selected SQL Server Components to install I got error:
"The SQL Server instance 'InstanceName' could not be found. A new instance will be created for you. If a compatible version of SQL Server is not found, Setup will install SQL Server Express."

So hence I installed BC without installing SQL Server Components. So far all seems to be working fine.
Or am I totally wrong about something?

Please add to instructions how to install update when SQL express is not needed (since most customers use SQL Standard and some SQL Enterprise and SQL Express is mainly used by NAV consultant PC-s).

Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71477e4-f2ea-1481-7597-29b324bd4f57
* Version Independent ID: a2bb3a05-e5c1-d9f7-f47f-d2f34c4a91ea
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,
You are correct. The SQL Server Components are not required in this case. This option is only required if there is not already a compatible version of SQL Server on the database machine, in which case SQL Server Express 2016 will be installed. However, if you do choose this option and SQL Server is already installed, then SQL Express is not installed. I will update the article to make thing clearer. Thanks for the feedback!

**Comment by jswymer** [comment]
Hello,
You are correct. The SQL Server Components are not required in this case. This option is only required if there is not already a compatible version of SQL Server on the database machine, in which case SQL Server Express 2016 will be installed. However, if you do choose this option and SQL Server is already installed, then SQL Express is not installed. I will update the article to make things clearer. Thanks for the feedback!

**Comment by jswymer** [comment]
Hello, the article has been an updated and will be published soon. Thanks for the feedback!
