### ISSUE TITLE
Please add  step "Restart the server instance" after reinstalling the Base Application

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#892]
After reinstalling System and Base app I tried to install other published non Microsoft apps but they failed.
Error was like "Could not find table ...... in ...." and after that "Install-NAVApp : An item with the same key has already been added"

So after few hours of troubleshooting I decided to:
Restart-NAVServerInstance -ServerInstance &lt;server instance&gt;

and after that all my extensions got installed with one command:
Get-NAVAppInfo -ServerInstance &lt;server instance&gt; | Install-NAVApp

So I suggest to update topic "(Single-tenant only) Reinstall extensions" to this:
1.Install System app
2.Install Base app
3.Restart the server instance
4.Install other extensions, including Microsoft and third-party extensions.

Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71477e4-f2ea-1481-7597-29b324bd4f57
* Version Independent ID: a2bb3a05-e5c1-d9f7-f47f-d2f34c4a91ea
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. I have tried several times to reproduce this issue but with no luck, so perhaps there is something triggering this that is not happening on my installations, like an extension.

**Comment by erolkunman** [comment]
Hi,
Let me clarify, that all Microsoft extensions installed fine without the Service instance restart but my other extensions (like Estonian official localization apps) failed to install.

**Comment by jswymer** [comment]
Hi, I am curious whether it has anything do with the fact that we do recommend that you restart the server after you run Repair-NAVApp cmdlet. The instructions to not sate this.

**Comment by jswymer** [comment]
Hello, the article has been updated. Hopefully this resolves the issue. Otherwise, let us know and we will reopen this. Thanks for the feedback!
