### ISSUE TITLE
Incorrect spelling in testcustomerhasbronzerewardlevelafterpostedsalesorders

### ISSUE THREAD

**Issue by MelPhan** [MicrosoftDocs/dynamics365smb-devitpro-pb#894]
[Enter feedback here]
in the code example of: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-advanced-example-test#testcustomerhasbronzerewardlevelafterpostedsalesorders-test

the sentence:
// [Then] Reward fiels are exist 

should be changed to:
// [Then] Reward fields exist 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7f2151-4fef-e6ab-bbc1-5b3e1b8c5b17
* Version Independent ID: 20ffa998-58d3-c843-87d5-3533e2fa7765
* Content: [Testing the Advanced Sample Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-advanced-example-test)
* Content Source: [dev-itpro/developer/devenv-extension-advanced-example-test.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-extension-advanced-example-test.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by jswymer** [comment]
Thanks for the feedback! The error has been fixed and an update will be published soon.
