### ISSUE TITLE
'Ratio' description is wrong

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#897]
The text is handled as a progress bar. &gt; This is wrong

Since webclient, the 'ratio' value is no longer shown as a progress bar like on RTC.
Also see https://partner.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/191718

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fde1227-7179-ab1e-9cbc-eb4415056328
* Version Independent ID: a377e4b5-e402-6d0f-30c8-7b056e89acee
* Content: [ExtendedDataType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-extendeddatatype-property)
* Content Source: [dev-itpro/developer/properties/devenv-extendeddatatype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-extendeddatatype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for reporting this. The topic is fixed and content is updated with the next doc refresh. Thanks!
