### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by markbrummel** [MicrosoftDocs/dynamics365smb-devitpro-pb#899]
An example or howto would be nice here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992582b8-b20a-0524-ff19-47832a64fd02
* Version Independent ID: 4b5654ec-3f41-fef8-6322-02eaead88fc7
* Content: [The AppSourceCop configuration must specify the set of affixes used by the application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0054-appsourcecopconfigurationmustspecifyaffixes#feedback)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop-as0054-appsourcecopconfigurationmustspecifyaffixes.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop-as0054-appsourcecopconfigurationmustspecifyaffixes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for your feedback - yes, I agree. The topic will be updated with the next doc refresh including a link to a topic that explains a bit more in-depth [AppSourceCop Rule AS0011](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0011-identifiersmusthaveaffix). Thanks!
