### ISSUE TITLE
please provide a sample

### ISSUE THREAD

**Issue by TheDenSter** [MicrosoftDocs/dynamics365smb-devitpro-pb#9]
It would be nice to have an example of an acceptable user scenario.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1a3dd1-7ef2-af15-6e88-4fe596bcffdd
* Version Independent ID: a0702f0c-7fd3-63e4-6464-cb90b7ca871c
* Content: [User Scenario Documentation - Dynamics NAV](https://docs.microsoft.com/en-gb/dynamics-nav/compliance/apptest-userscenario)
* Content Source: [dynamics-nav/compliance/apptest-userscenario.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/compliance/apptest-userscenario.md)
* Service: **unspecified**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We will consider this for a future update of the documentation.
