### ISSUE TITLE
How a user can change the value of a FlowFilter

### ISSUE THREAD

**Issue by aproehl79** [MicrosoftDocs/dynamics365smb-devitpro-pb#90]
You write 

> In FlowFilter fields, a user can enter a filter value via the user interface in the application that will affect the calculation of a FlowField.

How a user can do this in the business central web client? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ea41599-f702-15a8-c9dd-13a41d6ab8df
* Version Independent ID: 27f4af23-40fa-8f99-d1e8-28e81692715d
* Content: [FlowFilter Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-flowfilter-overview)
* Content Source: [dev-itpro/developer/devenv-flowfilter-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-flowfilter-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. You should be able to use the filtering described here: [Entering Criteria in Filters](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters). Thanks.

**Comment by aproehl79** [comment]
This is not an answer to my question. FlowFilters are not visible Fields that takes effect on how FlowFields are calculated.
For example the "Date Filter" in the Item table has effect on how the "Inventory" Field is calculated.

FlowFilters are not visible columns, so the normal way to filter on columns is not possible.

Can you please provide screenshots how the user can specify the "Date Filter" in the "Item List"

**Comment by SusanneWindfeldPedersen** [comment]
You are in the developer documentation, please go to the end-user documentation here: [Dynamics 365 Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/index?branch=master) - there you will also be able to provide feedback through GitHub. Thanks.
