### ISSUE TITLE
SaaS / OnPrem

### ISSUE THREAD

**Issue by jnpatrouillault** [MicrosoftDocs/dynamics365smb-devitpro-pb#903]
Hello,
Are that cmdlet available for Business Central SaaS ? This documentation tells nothing about that.

Thank you for your help.
regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d50c8108-9fba-55e7-136f-59f32aefafc1
* Version Independent ID: 73358440-79e4-6080-e653-95e96f644f84
* Content: [Microsoft.Dynamics.Nav.Management](https://docs.microsoft.com/en-us/powershell/module/Microsoft.Dynamics.Nav.Management/?view=businesscentral-ps-15)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Microsoft.Dynamics.Nav.Management.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Microsoft.Dynamics.Nav.Management.md)

**Comment by jswymer** [comment]
Hello, 

The cmdlets are only for use with on-premises deployments and sandbox development environments. We will add a note to make this clearer. Thanks for the feedback!
