### ISSUE TITLE
The NavUserPassword auth mechanism needs more explanation

### ISSUE THREAD

**Issue by etlweather** [MicrosoftDocs/dynamics365smb-devitpro-pb#904]
In the section on NavUserPassword authentication, it states:

&gt; The credentials are then validated by an external mechanism. 

Where can I find out more about what *external mechanism* are supported, how that works, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1fd7a9e-7ba2-62b1-14bd-6e45e15b26ff
* Version Independent ID: da31ff3b-726f-03a8-f05a-4e2d7d8e694d
* Content: [Users and Credential Authorization - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/users-credential-types#feedback)
* Content Source: [dev-itpro/administration/users-credential-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/users-credential-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Thanks for the feedback. Sorry for the long delay on the response. The text was incorrect.  NavUserPassword authentication is handled within Business Central. We've updated the article accordingly. The update will be published soon.
