### ISSUE TITLE
Business Central Version in Help & Support is not changed

### ISSUE THREAD

**Issue by vasla** [MicrosoftDocs/dynamics365smb-devitpro-pb#906]
After upgrading from RTM to CU 15.1 on premise, Business Central version not changed in Help & Support.
Are the missing some steps to update version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71477e4-f2ea-1481-7597-29b324bd4f57
* Version Independent ID: a2bb3a05-e5c1-d9f7-f47f-d2f34c4a91ea
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15#feedback)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,
It is  misleading. The Application Version shown on the Help and Support page and by the Get-NavApplication cmdlet comes from the $ndo$dbproperty table in the database. This version is not automatically updated during upgrade or by the Invoke-NAVpplicationDatabaseConversion cmdlet; it can only be changed manually by using the Set-NavApplication cmdlet. This is a result of the move to a fully extension-based solution. For now, the best way to get the application version is looking at the version of the base application extension. I hope this helps.

**Comment by jswymer** [comment]
Hello,

An optional task and explanation about this have been added to the article. The update will be published soon. Thanks for the feedback!

**Comment by erolkunman** [comment]
ok - this helped us to change Application no. But how can we update shown platform version?
Currently I see this:
Version: W1 15.3 (Platform 15.0.40073.40791 + Application 15.3.40822)

But clearly the platform is old no. Correct no should be 15.3.40791

**Comment by jswymer** [comment]
Hello,

Sorry mor misleading information. The platform number reflects the version number of the binaries. This cannot be changed.

I am guessing that the platform version you're referring to comes from the Update page on support, for example [Update 15.3 for Microsoft Dynamics 365 Business Central 2019 Release Wave 2 (Application Build 15.3.40822, Platform Build 15.3.40791)](https://support.microsoft.com/da-dk/help/4539530).

For this update the actual platform number would be something like 15.0.40791.1234. Version numbers have the format <major>.<minor>.<build>.<revision>. For minor updates, we do not increase the <minor> number for the platform; only the <build> and <revision>.  So for all BC 15 updates, the platform will have a version number 15.0.<build>.<revision>.  We have the article [Version Numbers](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/version-numbers) about version numbers, which I will update to explain this situation.

I hope this helps.
