### ISSUE TITLE
Correct link in Description section

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#909]
Instead of a link, we see [/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12419013-90c4-b413-eb21-47f2873a88aa
* Version Independent ID: f92a516c-815f-0510-bf47-533e361c0e3e
* Content: [The country codes specified in the 'supportedCountries' property must be valid ISO 3166-1 alpha-2 codes - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0056-appsourcecopconfigurationsupportedcountriesmustbevalidcountrycode)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop-as0056-appsourcecopconfigurationsupportedcountriesmustbevalidcountrycode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop-as0056-appsourcecopconfigurationsupportedcountriesmustbevalidcountrycode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this bug. It will be fixed with the next doc refresh. Thanks.
