### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#910]
It would be very helpful to see an example, e.g.
In the AppSourceCop.json, add
"supportedCountries": ["DE", "AT"]

Can you please also explain why this setting is required at all, since there is already a "supportedLocales" in the app.json?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9471c819-8dea-3604-c752-3420dcd9efa1
* Version Independent ID: 25bb21f8-6825-9c7d-7cf8-98cbec7faa17
* Content: [The AppSourceCop configuration must specify the list of countries targeted by the application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0055-appsourcecopconfigurationmustspecifysupportedcountries)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop-as0055-appsourcecopconfigurationmustspecifysupportedcountries.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop-as0055-appsourcecopconfigurationmustspecifysupportedcountries.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by atoader** [comment]
Hi! The property in app.json specifies ```The list of locales that are supported in your Help if different from all locales. ``` while the one in AppSourceCop.json specifies the list of countries in which the extension will be supported in AppSource. This is used by AppSourceCop to validate that the user has provided translations for all the supported countries. 
As the requirement to provide translations for all supported countries has been removed, we are considering removing this property from AppSourceCop.json

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. Closing this - the topic is refreshed today. Thanks.
