### ISSUE TITLE
Addfirst and addlast for controls in general?

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#911]
The article states as a last point "Use addfirst and addlast for placing your actions on Business Central pages. This eliminates breaking your app due to Business Central core changes.". 
Should we really update actions only, or controls in general? The standard might change fields and field groups as well. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b5ed4b-07ce-a1ea-3d84-188b5eb4de2b
* Version Independent ID: c249ea03-2ce7-6607-b19e-8e26f2333a40
* Content: [Step 3 - How to Develop Your App - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-develop-your-app)
* Content Source: [dev-itpro/developer/readiness/readiness-develop-your-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/readiness/readiness-develop-your-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by atoader** [comment]
Good point, @NKarolak ! The guidance applies to actions as well.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback! We will update the topic with the next doc refresh. Thanks.
