### ISSUE TITLE
I like the flowchart... very helpful!

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#913]
I like the flowchart... very helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c95669-cf57-f5a6-cbd2-2ee42f81f740
* Version Independent ID: ba9ab523-41d9-3c7d-7886-89466fe3da4c
* Content: [Report Triggers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-report-triggers)
* Content Source: [dev-itpro/developer/triggers/devenv-report-triggers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-report-triggers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thank you for taking the time to give this feedback, much appreciated!
