### ISSUE TITLE
The type or method 'Open' cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#915]
I'm working on an Extension in an On-Prem install v13 and i'm getting the following error: The type or method 'Open' cannot be used for 'Extension' development.

This page states that this method is supported only in Business Central on-premises.
Why is VS Code complaining?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62de8ebe-cc5e-68f7-3b03-1377cf3be6d5
* Version Independent ID: 3a75b258-8fb3-194d-a2d1-c4775cd990ed
* Content: [Open Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/file/file-open-method)
* Content Source: [dev-itpro/developer/methods-auto/file/file-open-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/file/file-open-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. I am not sure why VS Code is complaining, but you can check that your Allowed Extension Target Level is set to Internal in the Business Central Administration Console, and that the app.json file target setting is likewise set to Internal. If you already tried, please use your usual support channel. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.

**Comment by yannstlo** [comment]
> Hello, thanks for your feedback. I am not sure why VS Code is complaining, but you can check that your Allowed Extension Target Level is set to Internal in the Business Central Administration Console, and that the app.json file target setting is likewise set to Internal. If you already tried, please use your usual support channel. Thanks.

I had my server setup for "Internal" Dev but the app.json wasn't in VS code.

Thanks for the help.
Yann
