### ISSUE TITLE
KeyValue link to Options - Wrong NAV version

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#916]
When I wanted to see which "KeyValue" options are valid for the BC15 version (what I expected from this page), the link to "Configuring Business Central Server" links to the Dynamics NAV 2009 documentation (http://go.microsoft.com/fwlink/?LinkID=163750).

The correct link should be: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-server-instance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd6df1d-d589-c4c7-0f4b-ab278082d0f2
* Version Independent ID: 351aaaee-76e6-6392-4e18-350186aab5b3
* Content: [Set-NAVServerConfiguration (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/set-navserverconfiguration?view=businesscentral-ps-15)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Set-NAVServerConfiguration.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Set-NAVServerConfiguration.md)

**Comment by jswymer** [comment]
Hi, Thanks for the feedback! The link has been fixed as you suggested. The updated article will be published soon.
