### ISSUE TITLE
List of supported tokens

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#917]
How are end users supposed to know the standard supported % tokens?
Is there a list available of tokens (e.g. %mycustomers) on docs, and preferably within BC (via help?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8ca63e-19c6-5ecc-e195-c65cd67f5931
* Version Independent ID: 18a89028-7ce4-51f1-0d1a-b119dd2303de
* Content: [Adding custom filter tokens - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-filter-tokens)
* Content Source: [dev-itpro/developer/devenv-adding-filter-tokens.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-adding-filter-tokens.md)
* Service: **dynamics365-business-central**
* GitHub Login: @mikebcMSFT
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, end-users have this topic on Business Central app help available: https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters#-filter-tokens, which should help them get started with the tokens. Hope this answers your question. Thanks.
