### ISSUE TITLE
Please add Remarks, Example

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#918]
Please add the same information (Remarks, Example) available for RecRef.Init https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/recordref/recordref-init-method

It would be helpful to mention additionally, that Init also clears the SystemId field. 
If you are using Init on an already inserted record, and if you intend to use Modify somewhere after, make sure to save the current SystemID before Init, and to apply it back before Modify to avoid a run-time error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc14828-785a-2bd1-fb5a-c22687895b6e
* Version Independent ID: c3f726ed-c7fe-4e47-50d2-95949461fd8e
* Content: [Init Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-init-method)
* Content Source: [dev-itpro/developer/methods-auto/record/record-init-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/record/record-init-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, sorry for the late reply. The topic will be updated with the next doc refresh. Thanks.
