### ISSUE TITLE
And then what???

### ISSUE THREAD

**Issue by Bob-Dzimbowski** [MicrosoftDocs/dynamics365smb-devitpro-pb#921]
This page tells you the features and what you can or can't do. Once you are done in the sandbox, then how do you get it to the production environment? Shouldn't you mention what's next? Like download Visual Studio, load in the downloaded file you created, compile it into an .app, go to production environment in Extension Management, upload and install. I think this is probably it but where does it tell you truly what to do and how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e31ad37-068e-3007-2e46-7afc15f6b73b
* Version Independent ID: cd16bd61-cd0d-be6b-0af7-c1e9d81c81f5
* Content: [Using Designer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inclient-designer#feedback)
* Content Source: [dev-itpro/developer/devenv-inclient-designer.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-inclient-designer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hello, thanks for your feedback. You can read about this in the [Start and Stop designing](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-inclient-designer#start-and-stop-designing) section of the article.

**Comment by Bob-Dzimbowski** [comment]
I guess maybe I wasn't clear as to what I was getting at. It is fine to do all these things in sandbox designer. Once you have it that way you like it, how do you get it to the production environment. The link you sent me only speaks to the design. How do you get it to the live production environment?


Bob Dzimbowski
Manufacturing Consultant, VOX ISM<http://www.voxism.com/>
Phone: 416-457-6884<mailto:416-457-> | Email: bdzimbowski@voxism.com<mailto:bzimbowski@voxism.com> | Fax: 416.488-6309<file:///C:/Users/VoxUser/Downloads/416.488-6309>
www.voxism.com<http://www.voxism.com/> | Sign up for our newsletter<http://visitor.r20.constantcontact.com/d.jsp?llr=849qb9dab&p=oi&m=1103606868987&sit=ey6xwojfb&f=d065e3e0-9e2c-4753-aa29-1b508a9a0bbb>
[cid:5014887f-f6c3-4a13-9f26-29ad3ff20549]<http://www.linkedin.com/company/vox-ism/> [cid:c99fe61a-4f8d-423e-a8fd-0df2e672a611] <http://www.youtube.com/channel/UC5ra-iSkqSSmx9MYYYAtt7g>  [cid:2bc5e198-f562-435f-a614-0eed2ba9fe8d] <http://twitter.com/vox_ism>  [cid:47c32757-aa6c-4ccf-97f2-d63e58576d0a] <http://www.facebook.com/VoxISMCanada/>  [cid:9903d549-d805-441f-9491-6bbb319e9e1b] <http://www.instagram.com/voxismcanada/?hl=en>

[cid:1b169d29-fb0e-412d-8eef-0e7a240d2fd7]<https://voxism.com/events/>

________________________________

**Comment by blrobl** [comment]
Thanks for clarifying, this is now explained in the article.

**Comment by gmpopplewell** [comment]
Can I just say, this appears to be a terriblly thought out feature! you've just turned something that should be a nice convenient super user feature into a dev only feature as far as I can see? unless people only want the change in their sandbox?!!

The download code option doesn't give an app file which presumably means you have to use either powershell or vscode to package the app? ... anyone that can do that would just do the change in VS code surely?
