### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#922]
Seems like the links are not available as hyperlink (/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3407b42e-5d0e-56e7-aabe-3051fca1de3a
* Version Independent ID: d8b8251e-b4ad-9988-f762-2306e1470580
* Content: [Follow the best practices for naming ('/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming'). - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0215-followfilenameguide)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0215-followfilenameguide.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0215-followfilenameguide.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This needs to be resolved with the product, and then pushed to the docs. The link is supposed to point [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming). Thanks!

**Comment by SusanneWindfeldPedersen** [comment]
Fixed and pushed live. Thanks.
