### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#924]
"Ensure all objects are complied, unlocked, and tables are synchronized."

should be

"Ensure all objects are compiled, unlocked, and tables are synchronized."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5856d30d-b2c7-44b4-0aa9-45c09421f1e6
* Version Independent ID: b7fba357-9603-ac13-1191-c08b0faa34be
* Content: [Technical Upgrade Quick Reference - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/technical-upgrade-checklist)
* Content Source: [dev-itpro/upgrade/technical-upgrade-checklist.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/technical-upgrade-checklist.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by blrobl** [comment]
Hi, this will be fixed with the next doc refresh, thanks.
