### ISSUE TITLE
"Prepare for transitioning from codeunit 1."

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#925]
I could be made more clear that this is prep for later on in technical upgrade. I did interpret this that all objects effected should have been edited before the upgrade.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5856d30d-b2c7-44b4-0aa9-45c09421f1e6
* Version Independent ID: b7fba357-9603-ac13-1191-c08b0faa34be
* Content: [Technical Upgrade Quick Reference - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/technical-upgrade-checklist)
* Content Source: [dev-itpro/upgrade/technical-upgrade-checklist.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/technical-upgrade-checklist.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

This step has been updated to hopefully make it clear that it is not a preparation step. The update will be published soon. Thanks for the feedback.
