### ISSUE TITLE
Error on COD6723

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#926]
Why is there no solution given?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2138b94a-e63a-3e08-6a34-7be758f2c9ef
* Version Independent ID: c61aad3a-3624-5ece-049a-bbb4859cdd0b
* Content: [Compilation Errors When Converting a Microsoft Dynamics NAV 2017 Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/resolve-compile-errors-when-converting-dynamics-nav-2018-database)
* Content Source: [dev-itpro/upgrade/resolve-compile-errors-when-converting-dynamics-nav-2018-Database.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/resolve-compile-errors-when-converting-dynamics-nav-2018-Database.md)
* Service: **dynamics365-business-central**
* Product: **dynamics-nav-2017**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

I tried to repro this on the latest BC 14 CU, but I did not get an error on this codeunit. I am not sure whether I missed something or the error was fixed during an update.

**Comment by lvanvugt** [comment]
Meaning? That this point should be removed form the topic?

**Comment by jswymer** [comment]
Hello,

Yes, I intend to remove it from the list along with the error on page 9623, which no longer occurs.

**Comment by jswymer** [comment]
Hello, the article has been updated. I will close this issue. If you have additional feedback on this issue, l will reopen as needed. Thanks!
