### ISSUE TITLE
Suggested code throws compile error

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#929]
When implementing the suggested code it throws the following compile error:

---------------------------
You have specified an unknown variable.

GetAzureADGraphhResourceUrl

Define the variable under 'Global C/AL symbols'.
---------------------------

Apparently the COD6400 (Flow Service Management) does not containing this function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60332096-2cdc-b2b3-b684-a604c5be579f
* Version Independent ID: 3251bac0-b9f7-13d2-6519-474ddbb5e7bf
* Content: [Page 6400 and 6401 Errors  - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/resolve-page-6400-6401-error-converting-database)
* Content Source: [dev-itpro/upgrade/resolve-page-6400-6401-error-converting-database.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/resolve-page-6400-6401-error-converting-database.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by lvanvugt** [comment]
Typically this function exist in COD6400 in BC 14 (f.e.) but not in NAV 2018. So more needs to be done to fix this.

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! You are correct, the provided resolution did not work. The fix actually requires that you also make changes to codeunit 6400 as well. The article has been fixed and an update will be published soon.
