### ISSUE TITLE
Applying an Array of string to StyleExpr property

### ISSUE THREAD

**Issue by MihoubAhmed** [MicrosoftDocs/dynamics365smb-devitpro-pb#93]
Hi,
is there any way to Apply an Array of string to StyleExpr property
When i try to do it, an exception was thrown (errorCS0030 : cannot convert type 'Microsoft.Dynamics.Nav.Runtime.NavValue'
to 'Microsoft.Dynamics.Nav.Runtime.NAvArray&lt;Microsoft.Dynamics.Nav.Runtime.NavText&gt;')
have you any idea please?

![ss](https://user-images.githubusercontent.com/4196033/42624860-b2204c78-85c6-11e8-8f3b-093dd5ef6eb8.png)

![sscode](https://user-images.githubusercontent.com/4196033/42624868-b6a03bdc-85c6-11e8-81c4-2bd3436b83e8.png)

![exc](https://user-images.githubusercontent.com/4196033/42624879-ba370320-85c6-11e8-8bf4-a70b3389703f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370966c5-f451-4b3c-b24a-51c6047503fa
* Version Independent ID: 19065783-919f-6228-5286-e1a587ed66ba
* Content: [How to: Set Up Colored Indicators on Cues by Using the Style and StyleExpr Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--set-up-colored-indicators-on-cues-by-using-the-style-and-styleexpr-property)
* Content Source: [dynamics-nav/How-to--Set-Up-Colored-Indicators-on-Cues-by-Using-the-Style-and-StyleExpr-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Set-Up-Colored-Indicators-on-Cues-by-Using-the-Style-and-StyleExpr-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This repo is for reporting documentation issues only, please use the regular support channel for help on this issue.

**Comment by Divyesh071087** [comment]
Hello any solution for this issue. Can we assign Text Array to StyleExpr ?
