### ISSUE TITLE
Change the field that has the SourceExpr="Display Name" to have the SourceExpr="Customer Name".

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#930]
There is no Customer Name on the source table of this page. There is "Company Name", though. And the same for Description, it does not exist on source table in NAV 2018. For tim being I have used "Table Name".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b614a25e-958b-299f-d0f5-7d3b9612a01d
* Version Independent ID: 47077ab0-e647-3afd-59ae-0cf434f27606
* Content: [Resolving Page 9624 Compilation Error on Technical Upgrade  - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/resolve-page-9624-error-converting-database)
* Content Source: [dev-itpro/upgrade/resolve-page-9624-error-converting-database.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/resolve-page-9624-error-converting-database.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback. We have created a defect for the dev team to look into the resolution.

**Comment by jswymer** [comment]
Hello, sorry for the long delay. 

In Business Central, page 9624 is no longer used or referenced. It's source table re-purposed for other features, so we recommend that it not be used as a source table for other purposes.

We have updated the article, which will be published soon. But in the meantime, the resolution is to replace page 9624 in the converted database with an empty page object as shown in the following code. 

```
OBJECT Page 9624 Finish Design List Part
{
  OBJECT-PROPERTIES
  {
    Date=;
    Time=;
    Version List=;
  }
  PROPERTIES
  {
  }
  CONTROLS
  {
  }
  CODE
  {

    BEGIN
    END.
  }
}
```

For example:

1. Copy the code to a text editor, and save it as a .txt file type.
2. Use the Microsoft Dynamics NAV Development Environment to import the file and compile the object, which replaces the existing page.
