### ISSUE TITLE
Suggested solution is not sufficient

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#931]
Function GetGraphUserPlans also needs to be adjusted with BC code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc3f4e5-9162-4300-a96e-467d741ae8e8
* Version Independent ID: fe5b4e8e-f79a-dbe2-a2af-476262a13de9
* Content: [Resolving Codeunit 9010 Compilation Error - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/resolve-cu-9010-error-converting-database)
* Content Source: [dev-itpro/upgrade/resolve-cu-9010-error-converting-database.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/resolve-cu-9010-error-converting-database.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by lvanvugt** [comment]
And the suggest fix for CreateNewUsersFromAzureAD givs an error on Graph.GetUsers(50). It apparently does not have the method Users.

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback. You are correct. The resolution no longer worked for the latest CUS. The article has been updated with the correct resolution.
