### ISSUE TITLE
this page is outdated

### ISSUE THREAD

**Issue by RafaelKoch** [MicrosoftDocs/dynamics365smb-devitpro-pb#936]
This page is outdated. At this time 15.2 is released but not shown here. 

It would be better to refer the link to &lt;https://support.microsoft.com/en-us/help/4528706/released-updates-for-microsoft-dynamics-365-business-central-2019&gt; instead of trying to keep this redundant info up to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2611e33-f1d9-c337-8b8e-d5bfef60f5c1
* Version Independent ID: dde5a348-b0f0-ef81-7f1e-d6ad740e5ed1
* Content: [Updates for the Business Central 2019 Release Wave 2 version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/update-versions-15)
* Content Source: [dev-itpro/deployment/update-versions-15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/update-versions-15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @MartinNielander
* Microsoft Alias: **martinni**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. The article has been updated and will be published soon. I agree with your suggestion. We are currently revamping the update articles, so this issue will hopefully be solved in the future.
