### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by mikebcMSFT** [MicrosoftDocs/dynamics365smb-devitpro-pb#938]
Please link this to docs that describe how to substitute reports and the substitution-related events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa764a5b-a3d3-8248-7f47-b5b68c3aba3a
* Version Independent ID: 04019291-c4aa-87bf-de91-d808716bb9de
* Content: [GetSubstituteReportId Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/report/report-getsubstitutereportid-method#feedback)
* Content Source: [dev-itpro/developer/methods-auto/report/report-getsubstitutereportid-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/report/report-getsubstitutereportid-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. Good point. Report substitution, however, is currently on our backlog and will be prioritized along with other documentation. We have an item to track this, so will close this issue for now. Thanks.
