### ISSUE TITLE
Table format

### ISSUE THREAD

**Issue by HmmPeculiar** [MicrosoftDocs/dynamics365smb-devitpro-pb#939]
Small thing: the table under the following header isn't formatted correctly:
#write-upgrade-code-to-move-data-from-v1-extensions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dba54fc-a7cd-d3ad-f53c-6f0aa0b12d23
* Version Independent ID: e1554d91-f623-5fe2-0525-2fd37e0c30ec
* Content: [Converting Extensions V1 to V2 Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrade-v1-to-v2-overview#write-upgrade-code-to-move-data-from-v1-extensions)
* Content Source: [dev-itpro/developer/devenv-upgrade-v1-to-v2-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-upgrade-v1-to-v2-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. Will be fixed with the next doc refresh.
