### ISSUE TITLE
Need some examples

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-devitpro-pb#94]
It would be helpful to show some examples here, especially for an Option which could be problematic for a new developer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6d2910-e0f8-6d9f-b7d5-081ad840cb5f
* Version Independent ID: 06e57438-5d7a-bb36-7b8c-7f958b7d1cbd
* Content: [InitValue Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/initvalue-property)
* Content Source: [dynamics-nav/InitValue-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/InitValue-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thank you for your feedback. We are currently working on improving the properties by adding more examples and information. Over the next period of time, we'll be making updates to the AL development environment here: (Properties](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-properties).Thanks in advance for your patience.
