### ISSUE TITLE
ExternalType/ExternalAccess properties missing?

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#941]
According to their respective pages on docs.microsoft.com, ExternalType and ExternalAccess are also BC field properties, but they are not listed on this page (which does describe other field-level properties). Unless they were left out intentionally, please consider adding ExternalType and ExternalAccess. Thanks! :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5367809-8bc3-af4d-f43c-92ec6bbbace6
* Version Independent ID: 31321a54-c0a5-d7a5-8c6e-62113b479751
* Content: [Table and Table Extension Properties - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-table-properties#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-table-properties.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-table-properties.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The properties for integration with Dynamics 365 for Sales are listed in a separate topic - please find it [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-integrating-dynamics-365-for-sales-extension-development). Thanks.
