### ISSUE TITLE
What to do about it?

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#943]
Hi,
It would be nice if this page contained a few hint to why i might be seeing this message and maybe even provide basic troubleshooting steps.
"The previous version was not found." does not tell me anything about what is going on and im even in doubt about what piece of software is referenced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f61cd59-2143-1f4f-5e63-379979e98ab4
* Version Independent ID: 165b0142-f0aa-ac06-df78-ba0645be1fc3
* Content: [The previous version was not found - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0003-previousversionnotfound)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop-as0003-previousversionnotfound.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop-as0003-previousversionnotfound.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This topic has been improved with an earlier refresh. Thanks.
