### ISSUE TITLE
Visible? Editable!

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#944]
Isn't the last Note supposed to have "Editable" instead of "Visible" as an emphasized word? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd6c70d-7fef-0f5a-1a0b-37f102b853f5
* Version Independent ID: f5637137-69b3-9b33-1ba6-786ace43bf90
* Content: [Editable Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-editable-property)
* Content Source: [dev-itpro/developer/properties/devenv-editable-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-editable-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Yes, it should - thanks for catching this - will be fixed with the next refresh.
