### ISSUE TITLE
Add an example / link to Invoke method

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#946]
It took me quite a while to understand what this article is actually about.

If I'm right, the No method is mostly (if not always?) used in combination with the Invoke method https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testaction/testaction-invoke-method.

It would be handy to see a code example in both articles, e.g. from the Codeunit 134262 "Bank Pmt. Appl. Tolerance", ModalPageHandler PmtTolWarningAssertDocModalPageHandler, and to link each articles with each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e497f92-b128-5f90-4925-c56b88f66c0e
* Version Independent ID: f3fc2368-0145-0338-9587-3ca5f9dd4cd1
* Content: [No Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/testpage/testpage-no-method)
* Content Source: [dev-itpro/developer/methods-auto/testpage/testpage-no-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/testpage/testpage-no-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback and your patience. This information has been added, together with some examples, and will be available with the next refresh.
