### ISSUE TITLE
Translation extension, what's the priority?

### ISSUE THREAD

**Issue by devzom** [MicrosoftDocs/dynamics365smb-devitpro-pb#948]
Trying to translate field from base app -> **Sales Invoice** _list name_

The problem is that other extension which is added to dependency in our extension also translate this field name, but we want to change it to other translation. Even if we tried add caption to this field the higher priority translation is comming from the dependent extension.
How to do it and what's the priority in xlf. file means? 
Does it have any influence ?

`<trans-unit id="PageExtension 3030406131 - Property 2879900210" size-unit="char" translate="yes" xml:space="preserve" al-object-target="Page 4034894651">
          <source>Sales Invoice</source>
          <target>Faktura sprzedaży</target>
          <note from="Developer" annotates="general" priority="3"></note>
          <note from="Xliff Generator" annotates="general" priority="3">PageExtension LST_SalesInnvoicePageExt - Property Caption</note>
        </trans-unit>`

**Comment by thpeder** [comment]
Hi @devzom, 
If they have taken a dependency on your app then it means they are resolved after yours and if you want the application translated a certain way I would suggest that you make a new app that depend on their app which supplies the wanted captions. Note that you don't need a page extension to change the caption of a page, see the docs [Translating other extensions](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translating-other-extensions). 
The main mechanism for controlling the resolution order is by dependencies.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, regarding the priority setting in the .xlf file, this is an .xlf syntax support only and not used in connection with Business Central. Hope this and the reply above answers your question, so closing this issue. Thanks.
