### ISSUE TITLE
Inversion in chapter "Standard Microsoft Dynamics 365 for Sales Entity Mappings for Synchronization"

### ISSUE THREAD

**Issue by Maaaxime** [MicrosoftDocs/dynamics365smb-devitpro-pb#95]
In the chapter "Standard Microsoft Dynamics 365 for Sales Entity Mappings for Synchronization", there is an inversion between NAV tables and Dynamics 365 entities.

Dynamics NAV | Microsoft Dynamics 365 for Sales | Synchronization Direction | Default Filter
-- | -- | -- | --
[...] | [...] | [...] | [...] 
Transaction Currency | Currency | From Dynamics NAV to Microsoft Dynamics 365 for Sales. |  
Unit Group | Unit of Measure | From Dynamics NAV to Microsoft Dynamics 365 for Sales. |  
Product | Item | From Dynamics NAV to Microsoft Dynamics 365 for Sales. |  
  | Resource | From Dynamics NAV to Microsoft Dynamics 365 for Sales. |  

Should be :

Dynamics NAV | Microsoft Dynamics 365 for Sales | Synchronization Direction | Default Filter
-- | -- | -- | --
[...] | [...] | [...] | [...] 
Currency | Transaction Currency| From Dynamics NAV to Microsoft Dynamics 365 for Sales. |  
Unit of Measure | Unit Group | From Dynamics NAV to Microsoft Dynamics 365 for Sales. |  
Item | Product | From Dynamics NAV to Microsoft Dynamics 365 for Sales. |  
Resource  | | From Dynamics NAV to Microsoft Dynamics 365 for Sales. |  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb5e7ec-6f9e-3435-46ca-b01e31af41d9
* Version Independent ID: 23a6fcb0-1755-387c-76d1-01099e7c0cc6
* Content: [Synchronization and Data Integration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/synchronizing-dynamics-nav-and-dynamics-crm)
* Content Source: [dynamics-nav/Synchronizing-Dynamics-NAV-and-Dynamics-CRM.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Synchronizing-Dynamics-NAV-and-Dynamics-CRM.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The issue has been fixed and will be published soon.
