### ISSUE TITLE
First link incomplete

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#950]
Hi, the first used link in this article is not complete. It is missing the &topicid=38066 part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ec6892-6853-a52a-095c-f4cf7f8a6f49
* Version Independent ID: db918e3c-7dde-0a8d-41db-7c6d6fa1ff57
* Content: [You must write a tooltip in the Tooltip property for all controls of type Action and Field that exist on page objects (https://styleguides.azurewebsites.net/Styleguide/Read?id=2748&topicid=38066). - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0218-tooltipmustbefilledonpageforfieldsandactions)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0218-tooltipmustbefilledonpageforfieldsandactions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0218-tooltipmustbefilledonpageforfieldsandactions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this is due to a bug in the generation of the topic, but it has been fixed now. The topic will be fixed with the next refresh. Thanks!
