### ISSUE TITLE
First Link incomplete

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#952]
Hi, the first link is incomplete. It is missing the &topicid=38066 part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8148554f-85a8-ff4f-007c-4697f25469d5
* Version Independent ID: a541c49a-aac7-6925-678d-3b6543861bae
* Content: [The value of the Tooltip property of Fields must be filled (https://styleguides.azurewebsites.net/Styleguide/Read?id=2748&topicid=38066). - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0220-tooltiplanguagevaluemustbefilled)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0220-tooltiplanguagevaluemustbefilled.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0220-tooltiplanguagevaluemustbefilled.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this is due to a bug in the generation of the topic, but it has been fixed now. The topic will be fixed with the next refresh. Thanks!
