### ISSUE TITLE
First link incomplete

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#953]
The first link is incomplete. It is missing the &topicid=38066 part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a408cb8a-7d85-3d84-e86c-bd116696bef4
* Version Independent ID: c7f25bcc-bb8e-0262-fffb-d97208246674
* Content: [The Tooltip property of Fields must start with 'Specifies' (https://styleguides.azurewebsites.net/Styleguide/Read?id=2748&topicid=38066). - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0219-tooltipforfieldmuststartwithspecifies)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0219-tooltipforfieldmuststartwithspecifies.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0219-tooltipforfieldmuststartwithspecifies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this is due to a bug in the generation of the topic, but it has been fixed now. The topic will be fixed with the next refresh. Thanks!
