### ISSUE TITLE
Update section Prerequisites

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#954]
Section Prerequisites says:
If your current deployment is already running cumulative update 6 (version 14.7), we recommend to wait until the Update 2 for version 15 is released.
As 15.2 has already been released (https://www.microsoft.com/en-us/download/details.aspx?id=100784), I think this section can be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1d264c-efcd-b879-76d8-84966207ff17
* Version Independent ID: 5e5d562b-caad-3e0e-6cb8-064fd323519d
* Content: [Technical Upgrade - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15)
* Content Source: [dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback! The article has been updated and the update will be published soon.
