### ISSUE TITLE
Tiles on ListParts

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#955]
I can't get tiles to work in list parts - are you sure tiles are really supported for those pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40fb1c6f-690d-f75e-8980-b2e81b01f7c1
* Version Independent ID: 82261d08-c471-e886-38c3-126c715cd859
* Content: [Display Data as Tiles - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-lists-as-tiles#feedback)
* Content Source: [dev-itpro/developer/devenv-lists-as-tiles.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-lists-as-tiles.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

Unfortunately, tiles will not work on a ListPart type page. The documentation is incorrect and it will be updated. Sorry for the inconvenience. Thanks for the feedback!
