### ISSUE TITLE
Upgrade Tags

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#956]
It would be helpful to include information about using Upgrade Tags for ensuring that the upgrade code is run only one time: https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Upgrade%20Tags

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aad761f-ad97-7f15-fd0b-81f5716d2d90
* Version Independent ID: d0f0fb7c-6a1f-efef-e43c-955bb10b1404
* Content: [Upgrading an Extension V2 to a new version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions)
* Content Source: [dev-itpro/developer/devenv-upgrading-extensions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-upgrading-extensions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by NKarolak** [comment]
Any update on this?

**Comment by epernst** [comment]
Would like some additional docs on that too. Please. :)

**Comment by jswymer** [comment]
Hello, we've added some content about upgrade tags to the article. We'll close this for now, but if you have any feedback, let us know. Thanks!

**Comment by NKarolak** [comment]
Looks great, thank you! :-)
