### ISSUE TITLE
Supported by mobile clients, but not by Web Client

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#957]
The article mentions that this property is not supported by the Web Client, but it should write about the availability for mobile clients: https://github.com/microsoft/ALAppExtensions/issues/4963#issuecomment-568483738

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6a40d6-72c1-4f6f-946f-453af2c9c013
* Version Independent ID: d429b2c6-e43f-1cd9-1e92-cc339e74a7b6
* Content: [RunOnClient Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-runonclient-property)
* Content Source: [dev-itpro/developer/properties/devenv-runonclient-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-runonclient-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, this will be specified in the next refresh. Thanks.

**Comment by NKarolak** [comment]
@blrobl After 3 months, the content has not been updated.

**Comment by blrobl** [comment]
Hi, the article has recently been re-updated to reflect the latest changes from release wave 1 2020, such that the RunOnClient property is supported by the Web Client.
