### ISSUE TITLE
Get-NAVAddIn BC -IncludeResource does not export Resource as Byte[]

### ISSUE THREAD

**Issue by noclogic** [MicrosoftDocs/dynamics365smb-devitpro-pb#958]
It seems `Get-NAVAddIn BC -IncludeResource` does not export Resource as Byte[]

**Steps to reproduce**:
1. 
```
$addins = (Get-NAVAddIn BC -IncludeResource) | Where-Object {$_.Description -eq "Microsoft Dynamics BusinessChart control add-in" }  
$addins.Resource.GetType()
[Convert]::ToBase64String($addins.Resource)
```
brings error
```
Cannot convert argument "inArray", with value: "System.Byte[]", for "ToBase64String" to type "System.Byte[]": "Cannot convert value "System.Byte[]" to type "System.Byte[]". Error: "Cannot 
convert value "System.Byte[]" to type "System.Byte". Error: "Input string was not in a correct format."""
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
```

**Use Case**
Writing addins into XML file and import / insert addins into a other database, e.g. as a custom upgrade step (create XML file)
```
((Get-NAVAddIn BC -IncludeResource) | ForEach-Object { $_.ResourceBase64 = [Convert]::ToBase64String($_.Resource) }) | Export-Clixml -Path .\my\addins.xml
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed8fecc-d4d1-eb37-e3fd-0bf7f39f096f
* Version Independent ID: ca1fcab0-4eff-b883-7d64-bccd0e899ca8
* Content: [Get-NAVAddIn (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/get-navaddin?view=businesscentral-ps-15)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Get-NAVAddIn.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Get-NAVAddIn.md)

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is for reporting documentation issues only, please file a bug through your usual support channel for this. Thanks.
