### ISSUE TITLE
 "The" article used twice

### ISSUE THREAD

**Issue by mrmnaveed** [MicrosoftDocs/dynamics365smb-devitpro-pb#96]
"The" article used twice in the line "In general there is no restriction on line length, but lengthy lines can make the the code unreadable" for Line Length heading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by skundaram** [comment]
Thanks for the feedback. This is fixed in the next refresh of the docs.

**Comment by edupont04** [comment]
fixed.
