### ISSUE TITLE
correct example

### ISSUE THREAD

**Issue by tomvoj** [MicrosoftDocs/dynamics365smb-devitpro-pb#962]
codeunit 50113 CreateCustomer
{
    TableNo = Customer;
    trigger OnRun();
    begin
        CheckSize(Rec);
    end;
    procedure CheckSize(var Cust : Record Customer)
    begin
        if not Cust.HasShoeSize() then
            Cust.ShoeSize := 42;
    end;
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8e2bc7-a074-f049-1aab-e6edabae7446
* Version Independent ID: 62cea729-2f73-a526-de07-c5a23684a210
* Content: [Codeunit Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object#feedback)
* Content Source: [dev-itpro/developer/devenv-codeunit-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-codeunit-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for catching this. It will be fixed with the next refresh.
