### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#963]
"The Business Central base application is now delivered as an AL in an extensions instead of C/AL" sems to be a faulty senctence. A number of words are probably missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa6ac4e-7108-24ae-cf48-649864aaa872
* Version Independent ID: e8692393-899e-e511-4b42-5e4c230e5178
* Content: [Upgrade to Business Central 2019 Wave 2 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-overview-v15)
* Content Source: [dev-itpro/upgrade/upgrade-overview-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-overview-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! It has been fixed and an update will be published soon.
