### ISSUE TITLE
Page not indexed?

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#964]
I cannot find this page when searching, e.g. for "upgrade compatibility matrix".
https://docs.microsoft.com/en-us/search/?search=%22Upgrade+Compatibility+Matrix%22&category=All&scope=BusinessCentral

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8868c4-fb29-4b1f-e8ba-7560642481fc
* Version Independent ID: e838d8a4-07b9-02a8-f0b5-756220b3e64d
* Content: [Business Central 14.X to 15.X compatibility matrix - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-v14-v15-compatibility)
* Content Source: [dev-itpro/upgrade/upgrade-v14-v15-compatibility.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-v14-v15-compatibility.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, that's a little bit weird, I agree - I cannot search and make the page appear either. The metadata of this page is not different from other pages, so I am afraid that there is not so much we can do about it - other than making sure it is visible from other topics by linking to it. Then, I would expect the page to be picked up for indexing at some point. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing issue.

**Comment by NKarolak** [comment]
The page is finally indexed :-)

**Comment by SusanneWindfeldPedersen** [comment]
Yay, that took a long time, though - thanks for getting back :)
