### ISSUE TITLE
Upgrade Error: BC140 CU04 to BC150 Wave2 - During Syncronize Base Application

### ISSUE THREAD

**Issue by shameemap** [MicrosoftDocs/dynamics365smb-devitpro-pb#965]
The below issue occurs during syncronizing the base application from BC140 CU04 to BC150 Wave2.

Note: This is a customized database. upgraded 2009R2 to NAV2014. Then upgraded again to BC140 CU04 and working. But now when upgrading again to BC150 Wave2 this issue occurs

Command:
Sync-NAVApp -ServerInstance BC150 -Tenant default -Name "Base Application" -Version 15.2.39040.0

ERROR:

Sync-NAVApp : The following SQL error was unexpected:
Either the parameter @objname is ambiguous or the claimed @objtype (INDEX) is wrong.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
At line:1 char:1
+ Sync-NAVApp -ServerInstance BC150 -Tenant default -Name "Base Applica ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC150/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.
   SyncNavApp

**Comment by SusanneWindfeldPedersen** [comment]
Hello, this repo is meant for documentation issues and in this template there is information about which topic you are referring to, but this was deleted. Please contact support to get help with this issue.

**Comment by itsned911** [comment]
Hello I'm having the same issue whenever I  Sync-NAVApp -ServerInstance BC150 -Name "Base 
Application" -Version 15.2.39040.0

I'm getting the below error

Sync-NAVApp : The following SQL error was unexpected:

No item by the name of '"dbo"."COMP$Payment Terms$0"' could be found in the current database 'BC15', given that @itemtype was input as '(null)'.
Caution: Changing any part of an object name could break scripts and stored procedures.
Caution: Changing any part of an object name could break scripts and stored procedures.
At line:2 char:1
+ Sync-NAVApp -ServerInstance BC150 -Name "Base Application" -Version 1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC150/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.SyncNavApp"
Any help would be appreciated.
