### ISSUE TITLE
Caption has addtional parameters

### ISSUE THREAD

**Issue by MikeInHull** [MicrosoftDocs/dynamics365smb-devitpro-pb#966]
Caption also has parameters Comment, Locked, MaxLength.  Syntax would be:
Caption = 'Name', Locked = true;
However, there is no documentation on what Comment, Locked or MaxLength can be used for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bab3db4-745f-2c66-eac3-be6d6e168200
* Version Independent ID: e1479a2b-49cd-9edb-63c1-e1b0e9907d9f
* Content: [Caption Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-caption-property#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-caption-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-caption-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This was fixed with an earlier update.
