### ISSUE TITLE
Task 5 (Increase the application version) is to general

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#968]
What rules apply to the version change? In other words: given a certain version in the old database The DYNBC14T_STS database has version 1210 which is not supported by this version of Microsoft Dynamics 365 Business Central Server. Please contact your administrator.

And also do not set a value that will block running Start-NAVDataUpgrade.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e435e27-0b74-7dcd-555d-977517fd3774
* Version Independent ID: ea922161-12f9-3f86-69f9-2044369d6574
* Content: [Upgrade an unmodified application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application#task-5-increase-the-application-version)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-unmodified-application.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,
Thanks for the feedback. Sorry if I have misunderstood the question.

I need to double-check but I think the application version can be set independent of the version shown in the error: “ DYNBC14T_STS database has version 1210 which is not supported by this version of Microsoft Dynamics 365 Business Central Server error”. The ‘version’ in this error comes from the $ndo$tenantdatbaseproperty table in the database. This is be updated to the server instance version when you synchronize the tenant. 

Regarding the application version, the article has been updated with more information about setting the new application version. Hopefully this clears up some confusion. The update will be published soon.

**Comment by jswymer** [comment]
Hello,
I hope the reply and the changes to the article have provided some clarification. Otherwise, let us know and we will reopen the issue.  Thanks for the feedback!
