### ISSUE TITLE
Add task to "Post-upgrade tasks" section

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#969]
In the full upgrade topic https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/converting-a-database task 4 has a step 3 to publish the system.app and test.app symbol files. I totally missed this one using the Quick Reference and it appeared to be essential. So please at this task here too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5856d30d-b2c7-44b4-0aa9-45c09421f1e6
* Version Independent ID: b7fba357-9603-ac13-1191-c08b0faa34be
* Content: [Technical Upgrade Quick Reference - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/technical-upgrade-checklist)
* Content Source: [dev-itpro/upgrade/technical-upgrade-checklist.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/technical-upgrade-checklist.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback! The article has been updated with an important note to publish the system and test symbols, and generate application symbols. The updated article will be published soon.
