### ISSUE TITLE
Incorrect spelling of word validation

### ISSUE THREAD

**Issue by mrmnaveed** [MicrosoftDocs/dynamics365smb-devitpro-pb#97]
In this article validation has incorrect spellings i.e. validatation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 032a235d-4c55-c10b-87b9-4926e57ed342
* Version Independent ID: a5e89e7e-8291-ed15-d3f9-45840489a057
* Content: [Profile Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-profile-object)
* Content Source: [dev-itpro/developer/devenv-profile-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-profile-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Thanks for the feedback. We have fixed the mistake, and an update will be published soon.
