### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by MarceeMarc** [MicrosoftDocs/dynamics365smb-devitpro-pb#972]
Without a report extension object, the UsageCategory property cannot be changed on the standard report to exclude it from the menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 448c2de3-f23c-108e-6d4e-31cd32586c58
* Version Independent ID: 0dbc9199-71ff-34f4-f7f6-86bd5fb20b66
* Content: [Substituting Reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-substituting-reports#feedback)
* Content Source: [dev-itpro/developer/devenv-substituting-reports.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-substituting-reports.md)
* Service: **dynamics365-business-central**
* GitHub Login: @blrobl
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Thanks for your feedback. That is true, the article will be fixed with the next refresh.
