### ISSUE TITLE
Missing Azure SQL support

### ISSUE THREAD

**Issue by NicolaiH** [MicrosoftDocs/dynamics365smb-devitpro-pb#974]
Would be nice if this cmdlet included a DatabaseCredentials parameter, so it would support Azure SQL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1907a8e5-3029-ba5c-daea-ca5c5e144ef7
* Version Independent ID: a068db26-c5e5-78be-8c7c-dc0f69a04f90
* Content: [Export-NAVApplication (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/export-navapplication?view=businesscentral-ps-15#feedback)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Export-NAVApplication.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Export-NAVApplication.md)

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. For product suggestions please file an idea at [Ideas](https://aka.ms/bcideas). Thanks.
