### ISSUE TITLE
Tenant domain and environment name are mixed up

### ISSUE THREAD

**Issue by etl-emma** [MicrosoftDocs/dynamics365smb-devitpro-pb#975]
Hi,

It seems that &lt;your tenant domain&gt; and &lt;environment name&gt; are mixed up in the section: https://docs.microsoft.com/en-gb/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#exploring-the-apis-with-postman-and-basic-authentication

It says this: https://api.businesscentral.dynamics.com/v2.0/&lt;environment name&gt;/&lt;your tenant domain&gt;/api/v1.0
It should be this: https://api.businesscentral.dynamics.com/v2.0/&lt;your tenant domain&gt;/&lt;environment name&gt;/api/v1.0

Issue originally solved by: https://stackoverflow.com/a/59563728/12768536

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#exploring-the-apis-with-postman-and-basic-authentication)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by ferryferry** [comment]
Yup, indeed. I had the same issue today... Can this be fixed since this is a minor change and this issue is already open for 3 months now

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback and for your patience, this will be fixed with the next refresh of the docs.
