### ISSUE TITLE
Better info on where AppSourceCop.json needs to be to work properly

### ISSUE THREAD

**Issue by RafaelKoch** [MicrosoftDocs/dynamics365smb-devitpro-pb#976]
The documentation says: "We continue by adding the configuration file AppSourceCop.json in the project's root folder and setting its content to the following."

This is misleading in a multi-root workspace. It only works if one AppSourceCop.json is in every Extension root folder. It does not work when it is just placed in the root of the multi-root workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03cc1f40-cea7-5449-10a6-9736f9713c53
* Version Independent ID: afcd6e13-c135-08ba-f973-cab671fb579c
* Content: [AppSourceCop Analyzer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop)
* Content Source: [dev-itpro/developer/analyzers/appsourcecop.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/appsourcecop.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **SusanneWindfeldPedersen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The topic will be updated to describe this with the next doc refresh.
