### ISSUE TITLE
HttpHeaders.GetValues(String, Array of [Text]) is missing the var keyword in front of the second argument

### ISSUE THREAD

**Issue by Sven-Niehus** [MicrosoftDocs/dynamics365smb-devitpro-pb#979]
The method HttpHeaders.GetValues(String, Array of [Text]) is missing the var keyword in front of the second argument in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3493020e-c73c-e651-7358-bdd348695276
* Version Independent ID: 09c9dce8-5eb9-2977-e9aa-c4cca270d8bb
* Content: [HttpHeaders Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpheaders/httpheaders-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/httpheaders/httpheaders-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/httpheaders/httpheaders-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. This content is auto-generated from the code base, so regarding the syntax it is reflecting the code base and cannot be fixed. Thanks.

**Comment by Sven-Niehus** [comment]
Hi @SusanneWindfeldPedersen, 

are you able to elaborate on how you are auto generating the documentation? It would be really helpful for our own code base.

**Comment by SusanneWindfeldPedersen** [comment]
Hi, I can definitely understand it would be helpful, but these tools are - at least for now - only internally available. Thanks.
