### ISSUE TITLE
Obsolete documentation

### ISSUE THREAD

**Issue by salgiza** [MicrosoftDocs/dynamics365smb-devitpro-pb#98]
There are several problems with this help document:

* In AL it has been renamed as "InDataSet".
* Variables don't have properties (not in the same way as fields have properties) so it is totally non-obvious how to use it.
* At least a simple example, would be useful:
```
var
[InDataSet]MyVariable: Boolean;
```

And, best of all...

* Since at least NAV2015, **this property is no longer required in order for the variable to be used in Editable, Enable and Visible properties** (in fact, I just asked a few coworkers, and no-one is sure whether this property has any use in current versions of NAV/Business Central).

If the property is still required in any particular cases (I guess so, as it has been ported to AL), the docs should be updated to better describe them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4303a34-3414-7e92-00b5-fef5ef3d2c57
* Version Independent ID: 06466a11-4f02-7279-e7d4-a27643a13741
* Content: [IncludeInDataSet Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-includeindataset-property)
* Content Source: [dev-itpro/developer/properties/devenv-includeindataset-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-includeindataset-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by skundaram** [comment]
Hello, thank you for your feedback. We are currently working on improving the properties by adding more examples and information. Over the next period of time, we'll be making updates to the AL development environment here: [Properties](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-properties). Thanks in advance for your patience.

**Comment by vytjak** [comment]
As of NAV 2018 CU08, the property is still valid and needed in AL.

**Comment by rvanbekkum** [comment]
Why is this issue closed? It looks like the documentation is not yet up to date for AL (i.e., `IncludeInDataSet` property changed to `InDataSet` attribute).

**Comment by update-jeremy** [comment]
@SusanneWindfeldPedersen  Please reopen this.  The original request was never addressed.  This documentation remains 100% incorrect for AL.
