### ISSUE TITLE
Which version of Business Central does this apply to?

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#980]
I'm on BC13 On-Prem and I don't think I can use the views feature...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f8cd0a0-2764-97df-81bb-5d9ac3db87b9
* Version Independent ID: c04a1423-39f1-3466-3176-93b5e35597b6
* Content: [Views - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-views)
* Content Source: [dev-itpro/developer/devenv-views.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-views.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, views were introduced with the Business Central 2019, spring release. Thanks.
