### ISSUE TITLE
Technical Upgrade to Dynamics 365 Business Central 2019 Wave 2 Issue on install Base Application

### ISSUE THREAD

**Issue by Push0005** [MicrosoftDocs/dynamics365smb-devitpro-pb#982]
Hi,
Im trying to do technical upgrade wave 2.when i try to install base application i got bellow error.Could you please help me to solve this?
command-Install-NAVApp -ServerInstance bc150 -Name "Base Application" -Version "14.5.0.0"
Error
Install-NAVApp : Cannot install apps due to the state of the tenant: OperationalDataUpgradePending.
At line:1 char:1
+ Install-NAVApp -ServerInstance bc150 -Name "Base Application" -Versio ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$bc150/Default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.
   InstallNavApp

**Comment by jswymer** [comment]
Hello,

This would typically indicate that the application version is greater than the tenant database version. Did you happen to increase the application version, for example, running Set-NavApplication [ServerInstance] -ApplicationVersion [n.n.n.n]? You can see the application version by running Get-NAVApplication [ServerInstance], and the tenant database version by running Get-NavTenant [ServerInstance] -Tenant [ID).

**Comment by mabessghaier** [comment]
@Push0005 , did you find a solution, i followed Microsoft documentation , but I had exactly the same error .

**Comment by SylvioDg01** [comment]
@Push0005, @mabessghaier,
 
We had the same issue and solved it using the following commands:

1. Check the Application using the "Get-NavApplication -serverinstance [ServerInstance]" (as stated by @jswymer)
2. Check the Tenant Application ID using "Get-NAVTenant -ServerInstance [ServerInstance]" (as stated by @jswymer)
3. Reset the Application ID using "Set-NAVApplication -ServerInstance [ServerInstance] -ApplicationVersion [ApplicationVersion]"
4. Synchronised the Tenant using "Sync-NAVTenant -ServerInstance [ServerInstance] -Mode Sync -Force"
5. Started the DataUpgrade using "Start-NAVDataUpgrade -ServerInstance [ServerInstance] -FunctionExecutionMode Serial -Force"
6. Checked the Tenant again using "Get-NAVTenant -ServerInstance [ServerInstance]"
This will show you the State and in the DetailedState you can see the progress of the synchronization.

In the end the State will show operational and then you can again install applications

**Comment by MeliEmmanuelK** [comment]
This worked for me except at the point of installing the instance and I got Install-NAVApp : Cannot install apps due to the state of the tenant: OperationalWithSyncPending.

**Comment by jswymer** [comment]
Hello, The link to the article is missing. Just to be sure, is this the article you're following?

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v15#task-7-synchronize-tenant-and-synchronizeinstall-base-application-and-test-library-extensions

What do you get if you try to sync-navtenant again, then run Get-NAVTenant -ServerInstance [ServerInstance] -tenant [tenant ID or default] -ForceRefresh?

**Comment by SusanneWindfeldPedersen** [comment]
Closing this issue.
