### ISSUE TITLE
Office Requirements

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-devitpro-pb#983]
In the case of all the sections mentioning Office Requirements, it does not clarify 32 or 64 bit.  Our experience is that it seems to require 32 bit.  Can you confirm 32 vs 64 bit in the requirements?   If 64 bit is OK, I'll open support cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b0aa47-5276-2fd9-173f-f05adcd420c2
* Version Independent ID: fb89206b-f5c1-6f2c-1f83-899c02aa8e89
* Content: [System Requirements for Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central)
* Content Source: [dev-itpro/deployment/system-requirement-business-central.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/system-requirement-business-central.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

According to the development team, 64-bit should work. If you are experiencing issues, it might be a good idea to open a support case so that we can look into it. Thanks for the feedback.

**Comment by jswymer** [comment]
Hello, 

I hope that you found a solution to this issue. We will close this for now. If you have found anything that required a documentation update, let us know and we will gladly reopen the issue. Thanks!
