### ISSUE TITLE
old sample library link

### ISSUE THREAD

**Issue by dzsquared** [MicrosoftDocs/dynamics365smb-devitpro-pb#985]
The code samples link on this page (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started) links to the Microsoft/AL repository "Build and get inspired by our sample library on GitHub." - but one of the samples on this repository shows that the samples are being moved to Microsoft/BCTech

https://github.com/microsoft/AL/tree/master/samples/PageBackgroundTask.Currency -> https://github.com/microsoft/BCTech

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e08e71d8-8646-47c4-31d4-b3227fa4d958
* Version Independent ID: 12dcd23f-6600-b90a-7724-5d5cf3f4a5c3
* Content: [Getting Started with AL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started#feedback)
* Content Source: [dev-itpro/developer/devenv-get-started.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-get-started.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be updated with the next doc refresh.
