### ISSUE TITLE
Report bug in supported in-market versions

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-devitpro-pb#987]
[You can't open Support Request for Dynamics NAV/Business Central on PartnerSource anymore.](https://mbs.microsoft.com/partnersource/northamerica/help/help/technicalsupportrequest) This went to support.microsoft.com. Since PartnerSource will discontiuned, these are the links to create a new Support Case for [Microsoft Dynamics 365 Business Central on-premises​](http://support.microsoft.com/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f) and for [Microsoft Dynamics NAV](http://support.microsoft.com/supportforbusiness/productselection?&sapId=dea12e4a-4dd3-35e1-2577-45df252a2b9c).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9c875d8-3401-cfe3-d7d8-aac436b2b53b
* Version Independent ID: 4459ce33-7e99-adf3-591a-a665e3db0067
* Content: [Resources for Help and Support - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help-and-support#summary-of-where-to-file-bugs-and-issues)
* Content Source: [dev-itpro/help-and-support.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/help-and-support.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! We added a new entry in the table for Business Central on-premises with the link to support.microsoft.com site.
