### ISSUE TITLE
elaborate please

### ISSUE THREAD

**Issue by klktraveloperations** [MicrosoftDocs/dynamics365smb-devitpro-pb#988]
"Sets whether user-specific control values are saved for this page."
I have no idea what the above means. Google gives me nothing. Please elaborate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dce95ba-a175-0884-d851-173c7c13e897
* Version Independent ID: 711c1256-ed89-152c-3fca-bf11363bdc00
* Content: [SaveValues Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-savevalues-property)
* Content Source: [dev-itpro/developer/properties/devenv-savevalues-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-savevalues-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, we have added more information to this article. It will be available with the next refresh.
