### ISSUE TITLE
Index base

### ISSUE THREAD

**Issue by Peter-Conijn** [MicrosoftDocs/dynamics365smb-devitpro-pb#989]
Given that the .Net StringBuilder has a zero-based index and that Dynamics BC entities tend to have one-based indices (mostly), it might be worth adding that the index used in TextBuilder is one-based and not zero-based as one might be lead to believe given that it's a wrapped .Net StringBuilder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e16c1a67-67d9-346b-19f6-86b94819974f
* Version Independent ID: 6ed39805-e221-124b-aad7-d15a44471da6
* Content: [TextBuilder Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/textbuilder/textbuilder-data-type#feedback)
* Content Source: [dev-itpro/developer/methods-auto/textbuilder/textbuilder-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/textbuilder/textbuilder-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hello, thanks for your feedback. We made a note of this and it will be visible with the next doc refresh.
