### ISSUE TITLE
When using the dark Microsoft Docs theme, the white text in the first image is difficult to read

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#990]
Possibly due to the way the text is anti-aliased.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591f8762-9808-22f5-112d-f6d80f337b0e
* Version Independent ID: 6731b849-04f3-9bd2-5877-8c2bf26b8f34
* Content: [Page Background Tasks - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-background-tasks)
* Content Source: [dev-itpro/developer/devenv-page-background-tasks.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-page-background-tasks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for making us aware. We have a lot of incoming requests for fixes and issues, and will for now not prioritize fixing this issue. Maybe when we have more bandwidth. Hope you understand. Thanks.
