### ISSUE TITLE
Example 3 wrong Parameter name 'Details'

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [MicrosoftDocs/dynamics365smb-devitpro-pb#991]
Parameter in Example 3 should be -detailed i think

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae46cfe-f535-5084-1f08-3c00379fd877
* Version Independent ID: e5b58a03-b62b-4475-804b-6ab09247d066
* Content: [Get-NAVDataUpgrade (Microsoft.Dynamics.Nav.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/get-navdataupgrade?view=businesscentral-ps-15#feedback)
* Content Source: [businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Get-NAVDataUpgrade.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps-15/Microsoft.Dynamics.Nav.Management/Get-NAVDataUpgrade.md)

**Comment by jswymer** [comment]
Thanks for the feedback! The example has been fixed and an update will be published soon.
