### ISSUE TITLE
List of extendable pages

### ISSUE THREAD

**Issue by rnavarro2706** [MicrosoftDocs/dynamics365smb-devitpro-pb#992]
Hello,

Can I get a list of all the pages I am able to extend from (with the name I should use in AL)? I can't seem to find them in the docs.

Thanks,

**Comment by SusanneWindfeldPedersen** [comment]
Hello, we currently do not have such a list in the docs - the IntelliSense (Ctrl+Tab) will help look up the list of extendable pages. Thanks.
