### ISSUE TITLE
Max number of fields

### ISSUE THREAD

**Issue by mynavblog** [MicrosoftDocs/dynamics365smb-devitpro-pb#993]
Dear Team,

I do not know if it is issue related to documentation or this is functionality bug. But it is possible to add more than 6 fields in Brick and all are shown on the page correctly. 

So either documentation need to be fixed or it should be fixed in the system if it meant to be only 6 fields. 

Best regards,
Krzysztof

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40fb1c6f-690d-f75e-8980-b2e81b01f7c1
* Version Independent ID: 82261d08-c471-e886-38c3-126c715cd859
* Content: [Display Data as Tiles - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-lists-as-tiles#feedback)
* Content Source: [dev-itpro/developer/devenv-lists-as-tiles.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-lists-as-tiles.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback! We are investigating this issue, and will get back as soon as we have an answer.

**Comment by jswymer** [comment]
Hello again, 
As you expected, there is no limit to the number of fields that you can display on a tile. However, we recommend that you do not use more than 5 or 6 fields, including a image. This is only a guideline. We have updated the article to make it more clear. The update will be published soon. I hope we have answered your question. We will close this issue for now, but let us know and we will reopen it if you have more feedback. Thanks!
