### ISSUE TITLE
Which version of Business central added : AdditionalSearchTerms 

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#994]
I'm running 13 and would love to have this feature... Can you tell me when it was implemented?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d79af7-cfe4-dff9-f65f-d0fc83138ebf
* Version Independent ID: 00c0d953-450e-37f9-375c-daedd1d3edbb
* Content: [AdditionalSearchTerms Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-additionalsearchterms-property#feedback)
* Content Source: [dev-itpro/developer/properties/devenv-additionalsearchterms-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-additionalsearchterms-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

This was introduced in Business Central Spring 2019 (version 14). You can read a bit about it in the [release plan](https://docs.microsoft.com/en-us/business-applications-release-notes/april19/dynamics365-business-central/tell-me-more). Thanks for the feedback!
