### ISSUE TITLE
Setup for users with different plans

### ISSUE THREAD

**Issue by MikeInHull** [MicrosoftDocs/dynamics365smb-devitpro-pb#996]
These permissions do not ellicit the same experience as a user with said Subscription Plan applied.  For example, a user set-up with D365 TEAM MEMBER permission can run the Make Order function.  However a user with a Team Member Subscription Plan cannot perform this action.  This makes development testing results using this method inaccurrate.  Can you please update the documentation with a method for replicating Team Member licensing for testing purposes?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db94f60-5e26-c703-7beb-1fce11b25ddc
* Version Independent ID: 388e5659-b00b-126d-541a-2028024cdb09
* Content: [Working with Sandboxes and Entitlements - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/dev-itpro/developer/devenv-work-sandbox-entitlements#feedback)
* Content Source: [dev-itpro/developer/devenv-work-sandbox-entitlements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-sandbox-entitlements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @freddydk
* Microsoft Alias: **freddyk**

**Comment by freddydk** [comment]
I can see that a few things are wrong in the doc. - will fix that.
Wrt the team member permissions - what docker image are you using?

**Comment by freddydk** [comment]
Just tried to run this script:
```
$imagename = "mcr.microsoft.com/businesscentral/sandbox:us"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
New-NavContainer -accept_eula -accept_outdated -containerName test -imageName $imagename -licenseFile "C:\temp\build.flf" -auth UserPassword -Credential $credential -updateHosts -assignPremiumPlan
Setup-NavContainerTestUsers -containerName test -Password $credential.Password -credential $credential
```
log in as TEAMMEMBER, and create an order:
![image](https://user-images.githubusercontent.com/10775043/74730524-90dfdd00-5246-11ea-9796-2b264a075605.png)

If you are using onprem docker containers, you won't have entitlements and probably be allowed to create an order.

**Comment by MikeInHull** [comment]
Hi Freddy - Thanks for the update.  I had not used the Setup-NavContainerTestUsers commandlet.  I was only using the information contained in this article.  After using that commandlet it worked perfectly!

Perhaps it is worth adding a reference to this commandlet on the documentation as the documentation alone is not suffice?

Thanks again,

Mike

**Comment by SusanneWindfeldPedersen** [comment]
thanks for the feedback. The documentation was updated with an earlier refresh. Closing this issue.
