### ISSUE TITLE
[Question] Creating Database in Business Central with customized Base Application

### ISSUE THREAD

**Issue by g-franck** [MicrosoftDocs/dynamics365smb-devitpro-pb#997]
Hi,

I followed the [Creating Databases in Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/devenv-create-databases) documentation to build a Dynamics 365 Business Central wave 2 On-Premises environment with my own customized **Base Application**.
I also used [Provisioning the Business Central Server Service Account](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/provision-server-account) documentation to create my server instance, together with [Setting Up Multiple Business Central Web Server Instances Using PowerShell](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/configure-multiple-web-server-instances) documentation to create the corresponding web server instance.
I can access to this new environment with the WebClient, no problem.

### Question:
Are these documentations recommended for building this kind of environment with an own customized **Base Application**, or should I take into consideration others best practices / documentations ?

My environment works but as you can imagine, my database is empty, application tables (ex: Permission Set, _only SUPER_, etc...), business tables, and my own customized **Base Application** tables (ex: Customer, Item, etc...) have no data.
I would like to include data, as Cronus, but I didn't find any rapidstart package in the install DVD zip.

### Question:
What are the best practices / documentations to reach this goal (ex: full Permission Set list, etc... as Cronus, and Customer, Item, etc... as we can find in standard, evaluation or extended packages) ?

Thanks for your feedback.
Cordially

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. In general, we do not recommend building your own customized base application, we strongly advise you to build extensions on the existing base application instead. This will harden your solution and make upgrades easier. So, we do unfortunately not, have any documentation around how you'd do that. Instead, please use your usual support channel. Thanks.
