### ISSUE TITLE
Query key is $filter not filter

### ISSUE THREAD

**Issue by cparker4486** [MicrosoftDocs/dynamics365smb-devitpro-pb#998]
This suggestion comes from being a novice and wanting to make this page more explicit in that regard.

I believe all instances of `filter` should be written as `$filter` because that's what's required when writing an OData filter. Except for two occurrences at the top, all other instances of `$filter` are written without the dollar symbol.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc2d41b-a16e-2eb8-5acf-963df0a6020b
* Version Independent ID: 337d82f5-41e3-05d0-bde4-1ea6bd61b372
* Content: [Using Filter Expressions in OData URIs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris)
* Content Source: [dev-itpro/webservices/use-filter-expressions-in-odata-uris.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/use-filter-expressions-in-odata-uris.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Thanks for suggestion! We have updated the article and a new version will be published soon.
